force-app/main/default/objects/HS_Code__c/HS_Code__c.object-meta.xml
<CustomObject>
    <customHelpPage>HSCodeOnlineHelp</customHelpPage>
    <label>HSコード</label>
    <nameField>
        <label>HS Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HS_Code__c/fields/Chapter__c.field-meta.xml
<CustomField>
    <fullName>Chapter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chapter</label>
    <referenceTo>HS_Code__c</referenceTo>
    <relationshipName>HS_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HS_Code__c/fields/Has_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Has_Subcategory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate whether the HS Code has sub-catetory</description>
    <inlineHelpText>Indicate whether the HS Code has sub-category</inlineHelpText>
    <label>Has Subcategory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HS_Code__c/fields/HS_Code__c.field-meta.xml
<CustomField>
    <fullName>HS_Code__c</fullName>
    <label>HS Code</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HS_Code__c/fields/Is_Chapter__c.field-meta.xml
<CustomField>
    <fullName>Is_Chapter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Chapter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HSCodeTriggerTest.cls
@isTest
private class HSCodeTriggerTest {
    @testsetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object> {'HS_Code__c' => '111100', 'Is_Chapter__c' => true};
		TestDataFactory.createSObject(new HS_Code__c(), true, additionalFields);
    }
    
    testmethod static void shouldAssignParentForSubCategory() {
        HS_Code__c parent = [select Id, HS_Code__c from HS_Code__c limit 1];
        System.assertNotEquals(null, parent);
        System.assertEquals('111100', parent.HS_Code__c);
        
        Map<String, Object> additionalFields = new Map<String, Object> {'HS_Code__c' => '111110', 'Is_Chapter__c' => false};
		HS_Code__c hsCode = (HS_Code__c) TestDataFactory.createSObject(new HS_Code__c(), false, additionalFields);
        
        Test.startTest();
        FlsService.doInsert(hsCode);
        Test.stopTest();
        
        hsCode = [select Id, HS_Code__c, Chapter__c from HS_Code__c where Id = :hsCode.Id];
        System.assertEquals(parent.Id, hsCode.Chapter__c);
        
        parent = [select Id, Has_Subcategory__c from HS_Code__c where Id = :parent.Id];
        System.assertEquals(true, parent.Has_Subcategory__c);
    }
}