force-app/main/default/objects/HS_Code__c/HS_Code__c.object-meta.xml
<CustomObject>
    <customHelpPage>HSCodeOnlineHelp</customHelpPage>
    <label>HSコード</label>
    <nameField>
        <label>HS Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HS_Code__c/fields/HS_Code__c.field-meta.xml
<CustomField>
    <fullName>HS_Code__c</fullName>
    <label>HS Code</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BarCodeImage__c.field-meta.xml
<CustomField>
    <fullName>BarCodeImage__c</fullName>
    <inlineHelpText>Please take a picture of Barcode on product and attach image of Barcode.</inlineHelpText>
    <label>Barcode Photo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/CodeImageType__c.field-meta.xml
<CustomField>
    <fullName>CodeImageType__c</fullName>
    <label>Code Image Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CodeImageType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ForeignCurrency__c.field-meta.xml
<CustomField>
    <fullName>ForeignCurrency__c</fullName>
    <label>Foreign Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/HSCode__c.field-meta.xml
<CustomField>
    <fullName>HSCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HS CODE</label>
    <referenceTo>HS_Code__c</referenceTo>
    <relationshipLabel>PRODUCTS</relationshipLabel>
    <relationshipName>PRODUCTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IF(ISBLANK(External_ID__c), Name, External_ID__c)</formula>
    <inlineHelpText>Manufacture Code will be set as default. If there is no Manufacture Code, the Product ID will be set.</inlineHelpText>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QR_Image__c.field-meta.xml
<CustomField>
    <fullName>QR_Image__c</fullName>
    <formula>IF( Text(CodeImageType__c)=&quot;Barcode&quot;,
IMAGE(&quot;https://www.scandit.com/wp-content/themes/bridge-child/wbq_barcode_gen.php?symbology=code128&amp;value=&quot;+QR_Code__c +&quot;&amp;size=80&amp;ec=L&quot;,QR_Code__c), IMAGE(&apos;https://chart.googleapis.com/chart?chs=100x100&amp;cht=qr&amp;chl=&apos; + QR_Code__c, &apos;Product QR Code&apos; ))</formula>
    <inlineHelpText>Code Text will be automatically converted to either QR image or Barcode image base on Code Image Type.</inlineHelpText>
    <label>Code Image in Document</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QRCodeImage__c.field-meta.xml
<CustomField>
    <fullName>QRCodeImage__c</fullName>
    <formula>IMAGE(&apos;https://chart.googleapis.com/chart?chs=75x75&amp;cht=qr&amp;chl=&apos; + QR_Code__c, &apos;Product QR Code&apos; )</formula>
    <inlineHelpText>Code Text will be automatically converted to QR image.</inlineHelpText>
    <label>QR Code Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QuantityPerUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityPerUnit__c</fullName>
    <label>QUANTITY PER UNIT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SellingUnitPriceLocal__c.field-meta.xml
<CustomField>
    <fullName>SellingUnitPriceLocal__c</fullName>
    <label>SELLING UNIT PRICE(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SellingUnitPriceLocalKg__c.field-meta.xml
<CustomField>
    <fullName>SellingUnitPriceLocalKg__c</fullName>
    <label>SELLING UNIT PRICE(LOCAL)/Kg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SKUNumber__c.field-meta.xml
<CustomField>
    <fullName>SKUNumber__c</fullName>
    <label>Product SKU Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/SALES_ORDER__c.object-meta.xml
<CustomObject>
    <label>Goods S/O</label>
    <nameField>
        <displayFormat>GS-{000000}</displayFormat>
        <label>GOODS SALES ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods S/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_ORDER__c/fields/CustomerCompanyName__c.field-meta.xml
<CustomField>
    <fullName>CustomerCompanyName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER COMPANY NAME</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/PlannedQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlannedQuantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>GOODS S/O</relationshipLabel>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>RECOMMENDED QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupAmountSellingTax__c.field-meta.xml
<CustomField>
    <fullName>RollupAmountSellingTax__c</fullName>
    <label>ROLLUP AMOUNT OF SELLING TAX</label>
    <summarizedField>SalesOrderProduct__c.AmountOfSellingTax__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupFinalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>RollupFinalNetWeight__c</fullName>
    <label>ROLLUP FINAL NET WEIGHT</label>
    <summarizedField>SalesOrderProduct__c.FinalNetWeight__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupSellingAmountInclTax__c.field-meta.xml
<CustomField>
    <fullName>RollupSellingAmountInclTax__c</fullName>
    <label>ROLLUP SELLING AMOUNT INCL TAX</label>
    <summarizedField>SalesOrderProduct__c.SellingAmountInclTax__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupTotalAmountSelling__c.field-meta.xml
<CustomField>
    <fullName>RollupTotalAmountSelling__c</fullName>
    <label>ROLLUP TOTAL AMOUNT OF SELLING</label>
    <summarizedField>SalesOrderProduct__c.TotalAmountOfSelling__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupTotalGrossWeight__c.field-meta.xml
<CustomField>
    <fullName>RollupTotalGrossWeight__c</fullName>
    <label>ROLLUP TOTAL GROSS WEIGHT</label>
    <summarizedField>SalesOrderProduct__c.TotalGrossWeight__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupTotalMeasurement__c.field-meta.xml
<CustomField>
    <fullName>RollupTotalMeasurement__c</fullName>
    <label>ROLLUP TOTAL MEASUREMENT</label>
    <summarizedField>SalesOrderProduct__c.TotalMeasurement__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupTotalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>RollupTotalNetWeight__c</fullName>
    <label>ROLLUP TOTAL NET WEIGHT</label>
    <summarizedField>SalesOrderProduct__c.TotalNetWeight__c</summarizedField>
    <summaryForeignKey>SalesOrderProduct__c.GoodSalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/SalesOrderProduct__c.object-meta.xml
<CustomObject>
    <label>Goods S/O+Product</label>
    <nameField>
        <displayFormat>GSPD-{000000}</displayFormat>
        <label>GOODS S/O+PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods S/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProduct__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <formula>text( ProductID__r.BillingType__c )</formula>
    <label>BILLING TYPE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/FinalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>FinalNetWeight__c</fullName>
    <label>FINAL NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/ForeignCurrency__c.field-meta.xml
<CustomField>
    <fullName>ForeignCurrency__c</fullName>
    <label>Foreign Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/PlannedQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlannedQuantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>GOODS S/O+PRODUCT</relationshipLabel>
    <relationshipName>GoodsSalesOrderProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/SellingAmountInclTax__c.field-meta.xml
<CustomField>
    <fullName>SellingAmountInclTax__c</fullName>
    <label>SELLING AMOUNT INCL TAX</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/TotalGrossWeight__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossWeight__c</fullName>
    <label>TOTAL GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/TotalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>TotalNetWeight__c</fullName>
    <label>TOTAL NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/SwitchToInternalBarCodePhoto__c.field-meta.xml
<CustomField>
    <fullName>SwitchToInternalBarCodePhoto__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When 3rd party barcode site has problem, clofor_com_cfs__QR_Image__c will not work.
when it happen, switch to clofor_com_cfs__BarCodeImage__c for barcode image.
To use this, barcode should be upload as image.</inlineHelpText>
    <label>Switch to Internal Bar Code Photo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CodeImageType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barcode</fullName>
    </customValue>
    <customValue>
        <fullName>QR code</fullName>
    </customValue>
    <masterLabel>Code Image Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
        <default>true</default>
        <label>VND</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>PHP</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <masterLabel>CURRENCY</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/L</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bale</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liquid</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, fineparticles(powders）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, granular particles(grains）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, large particles(nodules）</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Cage</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,non-protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Cask</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>Chest</fullName>
    </customValue>
    <customValue>
        <fullName>Coil</fullName>
    </customValue>
    <masterLabel>CARGO TYPE(UNIT)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SOSummaryNoteController.cls
public with sharing class SOSummaryNoteController {
    public Site_Custom_Settings__c siteSetting {get; set;}
    public SALES_ORDER__c so {get; set;}
    public List<GoodsSOProductNode> listGoodSOProductNode {get; set;}
    public Total total {get; set;}
    public string receiverAdress {get; set;}
    public string printType {get; set;}
    public Map<String, String> translations{get; set;}
    public SOSummaryNoteController() {
        translations = new Map<String, String>();
		translations = getTranslationMap();
        printType = ApexPages.currentPage().getParameters().get('printType');
        so = new SALES_ORDER__c();
        listGoodSOProductNode = new List<GoodsSOProductNode>();
        receiverAdress = '';
        total = new Total();
        siteSetting = Site_Custom_Settings__c.getOrgDefaults();
        String soId = ApexPages.currentPage().getParameters().get('id');
        if(!String.isBlank(soId)){
            so = getShipingOder(soId);
            total.totalNetWeight = so.RollUpTotalNetWeight__c;
            total.totalFinalNetWeight = so.RollupFinalNetWeight__c;
            total.totalGrossWeight = so.RollUpTotalGrossWeight__c;
            total.totalMeasurement = so.RollupTotalMeasurement__c;
            total.totalAmount = so.RollupTotalAmountSelling__c;
            total.totalAmountTax = so.RollupAmountSellingTax__c;
            total.totalAmountIncludeTax = so.RollupSellingAmountInclTax__c;
            List<String> adresses = new List<String>();
            if(!String.isBlank(so.CustomerCompanyName__r.BillingStreet)){
                adresses.add(so.CustomerCompanyName__r.BillingStreet);
            }
            if(!String.isBlank(so.CustomerCompanyName__r.BillingCity)){
                adresses.add(so.CustomerCompanyName__r.BillingCity);
            }
            if(!String.isBlank(so.CustomerCompanyName__r.BillingState)){
                adresses.add(so.CustomerCompanyName__r.BillingState);
            }
            if(!String.isBlank(so.CustomerCompanyName__r.BillingPostalCode)){
                adresses.add(so.CustomerCompanyName__r.BillingPostalCode);
            }
            if(!String.isBlank(so.CustomerCompanyName__r.BillingCountry)){
                adresses.add(so.CustomerCompanyName__r.BillingCountry);
            }

            if(!adresses.isEmpty()){
                receiverAdress = String.join(adresses, ', ');
            }

        }
        if(!String.isBlank(SO.Id)){
            List<SalesOrderProduct__c> listGoodSOProduct = getListGoodSOProduct(soId);
            for(SalesOrderProduct__c gp : listGoodSOProduct){
                GoodsSOProductNode node = new GoodsSOProductNode();
                node.ID = gp.Id;
                node.Product = gp.ProductID__r.Name;
                node.ProductId = gp.ProductId__c;
                node.ProductName = gp.ProductName__c;
                node.SKUNumber = gp.ProductID__r.SKUNumber__c;
                node.HSCode = gp.ProductID__r.HSCode__r.HS_Code__c;
                node.ProductQRCode = gp.ProductID__r.QR_Code__c;
                node.ProductQRImage = gp.ProductID__r.QR_Image__c;
                node.CodeImageType = gp.ProductID__r.CodeImageType__c;
                // if(!siteSetting.SwitchToInternalBarCodePhoto__c){
                //     node.ProductQRImage = gp.ProductID__r.QR_Image__c;
                // }else{
                //     if(gp.ProductID__r.CodeImageType__c != 'Barcode'){
                //         node.ProductQRImage = gp.ProductID__r.QRCodeImage__c;
                //     }else {
                //         node.ProductQRImage = gp.ProductID__r.BarCodeImage__c;
                //     }
                // }
                node.Type = gp.ProductID__r.UnitType__c;
                node.FinalQuantity = gp.FinalQuantity__c;
                node.PlanQuantity = gp.PlannedQuantity__c;
                node.BQ = gp.ProductID__r.QuantityPerUnit__c;
                node.curr = gp.ForeignCurrency__c;
                node.NetWeight = gp.TotalNetWeight__c == null? 0 : gp.TotalNetWeight__c;
                node.GrossWeight = gp.TotalGrossWeight__c == null? 0 : gp.TotalGrossWeight__c;
                node.Measurement = gp.TotalMeasurement__c == null? 0 : gp.TotalMeasurement__c;
                node.BillingType = gp.ProductID__r.BillingType__c;
                if(gp.ProductID__r.BillingType__c == 'Weight'){
                    node.NetPurchaseValue = gp.ProductID__r.SellingUnitPriceLocalKg__c;
                }else{
                    node.NetPurchaseValue = gp.ProductID__r.SellingUnitPriceLocal__c;
                }
                
                node.VAT = (node.NetPurchaseValue != null? node.NetPurchaseValue : 0) * (gp.ProductID__r.TaxRateBuying__c != null? gp.ProductID__r.TaxRateBuying__c:0) / 100;
                node.Amount = gp.TotalAmountOfSelling__c;
                node.AmountTax = gp.AmountOfSellingTax__c;
                node.TotalAmount = gp.SellingAmountInclTax__c;
                node.FinalNetWeight = gp.FinalNetWeight__c == null? 0 : gp.FinalNetWeight__c;
                listGoodSOProductNode.add(node);
            }

        }

    }

    private SALES_ORDER__c getShipingOder(String soId){

        SALES_ORDER__c shipingOder = [ SELECT Id, SOQRLabel__c, ShippingAddress__c, SalesOrderStatus__c,
                        CustomerCompanyName__c, CustomerCompanyName__r.Name, OrderDate__c,
                        CustomerCompanyName__r.BillingStreet, CustomerCompanyName__r.BillingCity, 
                        CustomerCompanyName__r.BillingState, CustomerCompanyName__r.BillingPostalCode,
                        CustomerCompanyName__r.BillingCountry,CustomerCompanyName__r.Phone, CustomerCompanyName__r.Fax,
                        CustomerOrderNumber__c, Name, DeliveryTargetDate__c,  CreatedBy.Name, CreatedBy.Email,
                        LastModifiedBy.Name, LastModifiedBy.Email, RollUpTotalGrossWeight__c,RollupFinalNetWeight__c,
                        RollupTotalMeasurement__c, RollupTotalAmountSelling__c, RollupAmountSellingTax__c, RollupSellingAmountInclTax__c, RollUpTotalNetWeight__c
                        FROM SALES_ORDER__c
                        WHERE Id = : soId ];

        return shipingOder;
    }

    private List<SalesOrderProduct__c> getListGoodSOProduct(String soId){

        List<SalesOrderProduct__c> goodSOProducts = [ SELECT Id, PlannedQuantity__c, FinalQuantity__c, AmountOfSellingTax__c, SellingAmountInclTax__c, 
                                                    GoodSalesOrderID__c, ProductID__c, ProductName__c, Quantity__c, ShippingTypeAtWarehouse__c,
                                                    TotalAmountOfSelling__c, TotalGrossWeight__c, TotalMeasurement__c, TotalNetWeight__c,
                                                    ProductID__r.Name,ProductID__r.QR_Code__c, ProductID__r.UnitType__c,ForeignCurrency__c,
                                                    ProductID__r.QuantityPerUnit__c,ProductID__r.SellingCommercialValuePerUnitLocal__c,
                                                    ProductID__r.TaxRateBuying__c, FinalNetWeight__c,ProductID__r.SellingUnitPriceLocal__c,
                                                    ProductID__r.QR_Image__c,ProductID__r.CodeImageType__c, ProductID__r.BarCodeImage__c,
                                                    ProductID__r.SellingUnitPriceLocalKg__c, ProductID__r.BillingType__c, ProductID__r.SKUNumber__c, ProductID__r.HSCode__r.HS_Code__c
                                                     
                                                FROM SalesOrderProduct__c
                                                WHERE GoodSalesOrderID__c = : soId];

        return goodSOProducts;
    }

    public Map<String,String> getTranslationMap(){
        String langCode = UserInfo.getLanguage();
        Map<String, Object> translate = TranslationService.getByLanguage(langCode.substringBefore('_'));
        Map<String, String> translateMapResult = new Map<String, String>();
        for(String key : translate.keySet()){
            if(key.contains('summary_note') || key.contains('unit_translation')){
                translateMapResult.put(key.substringAfter('.'), (String)translate.get(key));
            }
            
        }
        return translateMapResult; 
    }

    public class Total{
        public Decimal totalFinalQuantity {get; set;}
        public Decimal totalBQ {get; set;}
        public Decimal totalNetWeight {get; set;}
        public Decimal totalFinalNetWeight {get; set;}
        public Decimal totalGrossWeight {get; set;}
        public Decimal totalMeasurement {get; set;}
        public Decimal totalAmount {get; set;}
        public Decimal totalAmountTax {get; set;}
        public Decimal totalAmountIncludeTax {get; set;}
        public Boolean isPlan{get; set;}
        
        public Total(){
            this.totalFinalQuantity = 0;
            this.totalBQ = 0;
            this.totalNetWeight = 0;
            this.totalFinalNetWeight = 0;
            this.totalGrossWeight = 0;
            this.totalMeasurement = 0;
            this.totalAmount = 0;
            this.totalAmountTax = 0;
            this.totalAmountIncludeTax = 0;
            this.isPlan = false;
        }

        public String getTotalAmountVND(){
            if(totalAmount == 0 || totalAmount == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###'};

            return String.format(totalAmount.format(), args);

            
        }
		public String getTotalAmountJPY(){
            if(TotalAmount == 0 || TotalAmount == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###,###,###,###.0'};

            String s = String.format(TotalAmount.format(), args);  
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s; 
        }
        public String getTotalAmountTaxVND(){
            if(totalAmountTax == 0 || totalAmountTax == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###,0'};

            String s =  String.format(totalAmountTax.format(), args);
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s;
            
        }
        public String getTotalAmountTaxJPY(){
            if(totalAmountTax == 0 || totalAmountTax == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###,###,###,###.0'};

            String s =  String.format(totalAmountTax.format(), args);
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s;
            
        }
        public String getTotalAmountIncludeTaxVND(){
            if(TotalAmountIncludeTax == 0 || TotalAmountIncludeTax == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###,0'};

            String s =  String.format(TotalAmountIncludeTax.format(), args);
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s;
            
        }
    }

    public class GoodsSOProductNode{
        public String ID{get;set;}
        public String ProductId{get;set;}
        public String SKUNumber{get; set;}
        public String HSCode{get; set;}
        public String Product {get; set;}
        public String ProductName {get; set;}
        public String ProductQRCode {get; set;}
        public String ProductQRImage {get; set;}
        public String Type {get; set;}
        public Decimal FinalQuantity {get; set;}
        public Decimal PlanQuantity {get; set;}
        public Decimal BQ {get; set;}
        public Decimal GrossWeight {get; set;}
        public Decimal NetWeight {get; set;}
        public Decimal FinalNetWeight {get; set;}
        public Decimal Measurement {get; set;}
        public Decimal NetPurchaseValue {get; set;}
        public Decimal VAT {get; set;}
        public Decimal Amount {get; set;}
        public Decimal TotalAmount {get; set;}
        public Decimal AmountTax {get; set;}
        public String CodeImageType{get;set;}
        public String BillingType {get; set;}
        public Boolean isPlan{get; set;}
        public String curr{get; set;}
        
        public GoodsSOProductNode(){
            this.ProductId = '';
            this.SKUNumber = '';
            this.HSCode = '';
            this.BillingType = '';
            this.Product = '';
            this.ProductName = '';
            this.ProductQRCode = '';
            this.ProductQRImage = '';
            this.Type = '';
            this.FinalQuantity = 0;
            this.BQ = 0;
            this.NetWeight = 0;
            this.GrossWeight = 0;
            this.Measurement = 0;
            this.NetPurchaseValue = 0;
            this.VAT = 0;
            this.Amount = 0;
            this.TotalAmount = 0;
            this.AmountTax = 0;
            this.isPlan = false;
            this.FinalNetWeight = 0;
        }
        public String getNetPurchaseValueVND(){
            if(NetPurchaseValue == 0 || NetPurchaseValue == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###'};

            return String.format(NetPurchaseValue.format(), args);
            
        }

        public String getVATVND(){
            if(VAT == 0 || VAT == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###,0'};

            String s = String.format(VAT.format(), args);  
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s; 
        }

        public String getAmountVND(){
            if(Amount == 0 || Amount == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###'};

            return String.format(Amount.format(), args);   
        }

        public String getTotalAmountVND(){
            if(TotalAmount == 0 || TotalAmount == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###,0'};

            String s = String.format(TotalAmount.format(), args);  
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s; 
        }
        
        public String getAmountTaxVND(){
            if(AmountTax == 0 || AmountTax == null){
                return '0';
            }
            List<String> args = new String[]{'0','number','###.###.###.###,0'};

            String s = String.format(AmountTax.format(), args);  
            if(!s.contains(',')){
               s += ',0'; 
            }
            return s; 
        }

        
    }
}