force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/BookingNv__c.field-meta.xml
<CustomField>
    <fullName>BookingNv__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter Shipping Company in case of FCL, Co-loader in case of LCL, Your company in case of Consolidation</inlineHelpText>
    <label>MASTER CARRIER/CONSOLIDATOR</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ConsolidationType__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationType__c</fullName>
    <label>SERVICE REQUIRED(CONSOL/1MMultiH/NORMAL)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>通常貨物(Normal Cargo)</fullName>
                <default>true</default>
                <label>通常貨物(Normal Cargo)</label>
            </value>
            <value>
                <fullName>複数BL貨物(Multiple BL Cargo)</fullName>
            </value>
            <value>
                <fullName>自社混載(Consolidation Cargo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ContainerSeal_No__c.field-meta.xml
<CustomField>
    <fullName>ContainerSeal_No__c</fullName>
    <description>Changed Label name from CONTAINER &amp; SEAL NO to CONTAINER INFORMATION, so as client will not input container &amp; seal number directly in the field

Aoki</description>
    <inlineHelpText>Please Entry Container Number and Seal Number in Container Detail Section at bottom. Also allow for directly input Container Number and Seal Number only when need to be amended manually.</inlineHelpText>
    <label>CONTAINER NO/SEAL NO-OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Devan__c.field-meta.xml
<CustomField>
    <fullName>Devan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>When it&apos;s import consolidation cargo, input the name of the company responsible for devanning</inlineHelpText>
    <label>DEVAN OPERATION COMPANY</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Devan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DevanningDate__c.field-meta.xml
<CustomField>
    <fullName>DevanningDate__c</fullName>
    <label>DEVAN DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + Id, &apos;S&apos; &amp;  WkInitial__c  &amp; Name , &apos;_top&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FORWARDING ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/LoadingTime__c.field-meta.xml
<CustomField>
    <fullName>LoadingTime__c</fullName>
    <label>MANIFEST SUBMISSION DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/LoadLocation__c.field-meta.xml
<CustomField>
    <fullName>LoadLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Refer to Master A/N to confirm about loading Warehouse</inlineHelpText>
    <label>CARGO LOADING WAREHOUSE(LOCAL)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>LoadLocation__c.WharehouseCompany__c</field>
            <operation>equals</operation>
            <valueField>$Source.BookingNv__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LoadLocation__c</referenceTo>
    <relationshipLabel>F/TMS S/O</relationshipLabel>
    <relationshipName>LoadLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Master_B_L__c.field-meta.xml
<CustomField>
    <fullName>Master_B_L__c</fullName>
    <label>M B/L NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Place_Of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Place_Of_Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Delivery</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_DELIVERY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Place_Of_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Place_Of_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Receipt</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_RECEIPT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/POL__c.field-meta.xml
<CustomField>
    <fullName>POL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/T_ETD__c.field-meta.xml
<CustomField>
    <fullName>T_ETD__c</fullName>
    <inlineHelpText>Input the ETD at Transit Port. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. ETD at Transit Port in final Transit record will be automatically inserted in this field.</inlineHelpText>
    <label>ETD AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TransitV__c.field-meta.xml
<CustomField>
    <fullName>TransitV__c</fullName>
    <inlineHelpText>Input the Vessel/Flight before transit(in import case) or after transit(in export case). Transit Vessel/Flight can be automatically inserted from Transit Vessel/Flight in final Transit record in Shipment Order.</inlineHelpText>
    <label>1ST VESSEL/FLIGHT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TS__c.field-meta.xml
<CustomField>
    <fullName>TS__c</fullName>
    <inlineHelpText>Input the transit port of the shipment. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. Transit Port in final Transit record  will be automatically inserted in this field.</inlineHelpText>
    <label>TRANSIT PORT</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Vessle__c.field-meta.xml
<CustomField>
    <fullName>Vessle__c</fullName>
    <inlineHelpText>Final Vessel or Flight arrived to POD</inlineHelpText>
    <label>VESSEL/FLIGHT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Voy_No__c.field-meta.xml
<CustomField>
    <fullName>Voy_No__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/WkInitial__c.field-meta.xml
<CustomField>
    <fullName>WkInitial__c</fullName>
    <formula>CASE(  RecordType.DeveloperName  
, &apos;RecordType1&apos;, &apos;IS&apos;
, &apos;oceanimport_lock&apos;, &apos;IS&apos;

, &apos;RecordType&apos;, &apos;OS&apos;
, &apos;oceanexport_lock&apos;, &apos;OS&apos;

, &apos;InAir&apos;, &apos;IA&apos;
, &apos;airimportlock&apos;, &apos;IA&apos;

, &apos;OutAir&apos;, &apos;OA&apos;
, &apos;OutAir_lock&apos;, &apos;OA&apos;

, &apos;Domestic_Transportation&apos;, &apos;DT&apos;
, &apos;Domestic_Transportation_Lock&apos;, &apos;DT&apos;

, &apos;LogisticsService&apos;, &apos;LG&apos;
, &apos;LogisticsServiceLock&apos;, &apos;LG&apos;

, &apos;CrossBoarder&apos;, &apos;CB&apos;
, &apos;CrossBoarderLock&apos;, &apos;CB&apos;

, &apos;Express&apos;, &apos;ES&apos;
, &apos;ExpressLock&apos;, &apos;ES&apos;

, &apos;QUOTATION&apos;, &apos;QT&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>wkHEAD CHARACTER</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/MasterAnken__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLOnlineHelp</customHelpPage>
    <description>M B/L - SHIPMENTS</description>
    <label>混載</label>
    <nameField>
        <label>MASTER SHIPMENT NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnken__c/fields/META__c.field-meta.xml
<CustomField>
    <fullName>META__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/METD__c.field-meta.xml
<CustomField>
    <fullName>METD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPlace_Of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>MPlace_Of_Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Delivery</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_DELIVERY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPlace_Of_Receipt__c.field-meta.xml
<CustomField>
    <fullName>MPlace_Of_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Receipt</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_RECEIPT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPOD__c.field-meta.xml
<CustomField>
    <fullName>MPOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Dispatch</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPOL__c.field-meta.xml
<CustomField>
    <fullName>MPOL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <customHelpPage>OnlineHelpPorts</customHelpPage>
    <description>Port</description>
    <label>ポートコード</label>
    <nameField>
        <label>Port name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Port__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
            <value>
                <fullName>BULGARIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CopyingMShipDataToHShipController.cls
public with sharing class CopyingMShipDataToHShipController {
    public transient Boolean selectAll {get; set;}
    public List<HBLShipmentWrapper> shipmentWrappers {get; private set;}
    private static List<String> fieldsToQueryFromHShip = new List<String>();
    private static List<String> fieldsToQueryFromMShip = new List<String>();
    private String mshipId;
    private MasterAnken__c mship;
    public String errorMessage {get;set;}
    public Map<String, String> translations {get; private set;}
    
    static {
        fieldsToQueryFromHShip.add('Id');
        fieldsToQueryFromHShip.add('Name');
        fieldsToQueryFromHShip.add('WkInitial__c');
        fieldsToQueryFromHShip.add('ID__c');
        fieldsToQueryFromHShip.add('POL__r.Country_Name__c');
        fieldsToQueryFromHShip.add('POL__r.City_Name__c');
        fieldsToQueryFromHShip.add('Place_of_Receipt__r.Name');
        fieldsToQueryFromHShip.add('ETD__c');
        fieldsToQueryFromHShip.add('POD__r.Country_Name__c');
        fieldsToQueryFromHShip.add('POD__r.City_Name__c');
        fieldsToQueryFromHShip.add('Place_of_Delivery__r.Name');
        fieldsToQueryFromHShip.add('ETA__c');
        fieldsToQueryFromHShip.add('Vessle__c');
        fieldsToQueryFromHShip.add('Voy_No__c');
        fieldsToQueryFromHShip.add('ContainerSeal_No__c');
        fieldsToQueryFromHShip.add('Devan__r.Name');
        fieldsToQueryFromHShip.add('Devan__c');
        //fieldsToQueryFromHShip.add('DevanRep__r.Name');
        //fieldsToQueryFromHShip.add('DevanRep__c');
        fieldsToQueryFromHShip.add('DevanningDate__c');
        fieldsToQueryFromHShip.add('TransitV__c');
        fieldsToQueryFromHShip.add('TS__c');
        fieldsToQueryFromHShip.add('T_ETD__c');
        fieldsToQueryFromHShip.add('Master_B_L__c');
        fieldsToQueryFromHShip.add('BookingNv__c');
        fieldsToQueryFromHShip.add('LoadLocation__c');
        fieldsToQueryFromHShip.add('BookingNv__r.Name');
        fieldsToQueryFromHShip.add('LoadLocation__r.Name');
        fieldsToQueryFromHShip.add('LoadingTime__c');
        fieldsToQueryFromHShip.add('ConsolidationType__c');
      
        fieldsToQueryFromMShip.add('Id');
        fieldsToQueryFromMShip.add('Name');
        fieldsToQueryFromMShip.add('MPOL__r.Country_Name__c');
        fieldsToQueryFromMShip.add('MPOL__r.City_Name__c');
        fieldsToQueryFromMShip.add('MPlace_of_Receipt__r.Name');
        fieldsToQueryFromMShip.add('METD__c');
        fieldsToQueryFromMShip.add('MPOD__r.Country_Name__c');
        fieldsToQueryFromMShip.add('MPOD__r.City_Name__c');
        fieldsToQueryFromMShip.add('MPlace_of_Delivery__r.Name');
        fieldsToQueryFromMShip.add('META__c');
        fieldsToQueryFromMShip.add('MVessel__c');
        fieldsToQueryFromMShip.add('MVoy_No__c');
        fieldsToQueryFromMShip.add('MContainer_No__c');
        fieldsToQueryFromMShip.add('MDevan__r.Name');
        fieldsToQueryFromMShip.add('MDevan__c');
        fieldsToQueryFromMShip.add('MDevanRep__r.Name');
        fieldsToQueryFromMShip.add('MDevanRep__c');
        fieldsToQueryFromMShip.add('MDevanningDate__c');
        fieldsToQueryFromMShip.add('MTRANSIT_VESSEL__c');
        fieldsToQueryFromMShip.add('MTRANSIT_PORT__c');
        fieldsToQueryFromMShip.add('MTRANSIT_T_ETD__c');
        fieldsToQueryFromMShip.add('MMaster_B_L_No__c');
        fieldsToQueryFromMShip.add('MBookingNv__c');
        fieldsToQueryFromMShip.add('MLoadLocation__c');
        fieldsToQueryFromMShip.add('MBookingNv__r.Name');
        fieldsToQueryFromMShip.add('MLoadLocation__r.Name');
        fieldsToQueryFromMShip.add('bondedtimetoCFS__c');
    }
    
    public CopyingMShipDataToHShipController() {
        mshipId = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('id'));
        shipmentWrappers = new List<HBLShipmentWrapper>();
        
        initializeTranslation();
        loadRelatedHShips(mshipId);    
        loadMBLShip(mshipId);
        selectAll = true;
    }
    
    private void initializeTranslation() {
        TranslationService translationService = new TranslationService('COPY_MBL_HBL', UserInfo.getLanguage());
        translations = translationService.getTranslations();
    }
    
    private void loadRelatedHShips(String mshipId) {
        String queryFields = String.join(fieldsToQueryFromHShip, ',');
        String query = 'SELECT ' + queryFields + ' FROM CustomObject1__c WHERE MasterAnkenName__c = \'' + mshipId + '\'';
        
        if (PermissionValidationUtil.isAccessibleAccount() && PermissionValidationUtil.isAccessiblePort() 
            	&& PermissionValidationUtil.isAccessibleWarehouse() && PermissionValidationUtil.isAccessibleHBL()) {
            List<CustomObject1__c> shipments = (List<CustomObject1__c>) Database.query(query);
            for (CustomObject1__c shipment : shipments) {
                shipmentWrappers.add(new HBLShipmentWrapper(true, shipment));
            }
        }
    }

    public class HBLShipmentWrapper {
        public Boolean selected {get;set;}
        public CustomObject1__c shipment {get;set;}
        
        public HBLShipmentWrapper(Boolean checked, CustomObject1__c shipment) {
            this.selected = checked;
            this.shipment = shipment;
        }   
    }
    
    private void loadMBLShip(String mshipId) {
        String queryFields = String.join(fieldsToQueryFromMShip, ',');  
        String query = 'SELECT ' + queryFields + ' FROM MasterAnken__c WHERE Id = \'' + mshipId + '\'';
        
        if (PermissionValidationUtil.isAccessibleAccount() && PermissionValidationUtil.isAccessiblePort() 
            	&& PermissionValidationUtil.isAccessibleWarehouse() && PermissionValidationUtil.isAccessibleMBL()) {
        	mship = (MasterAnken__c) Database.query(query);
		}
    }
    
    public List<MasterAnken__c> getMBLShips() {
        List<MasterAnken__c> mships = new List<MasterAnken__c>();
        if (mship != null) {
                mships.add(mship);    
        }
        
        return mships;
    }
    
    public PageReference copy() {
        String message = '';
        if (mship != null && PermissionValidationUtil.isEditableHBL()) {        
            List<CustomObject1__c> toBeUpdated = new List<CustomObject1__c>();
    
            for (HBLShipmentWrapper shipmentWrapper : shipmentWrappers) {
                if (shipmentWrapper.selected) {
                    CustomObject1__c shipment = shipmentWrapper.shipment;
                    
                    shipment.POD__c = mship.MPOD__c;
                    shipment.POL__c = mship.MPOL__c;
                    shipment.Place_Of_Delivery__c = mship.MPlace_Of_Delivery__c;
                    shipment.Place_Of_Receipt__c = mship.MPlace_Of_Receipt__c;
                    shipment.ETD__c = mship.METD__c;
                    shipment.ETA__c = mship.META__c;
                    shipment.Vessle__c = mship.MVessel__c;
                    shipment.Voy_No__c = mship.MVoy_No__c;
                    shipment.Devan__c = mship.MDevan__c;
                    //shipment.DevanRep__c = mship.MDevanRep__c;
                    shipment.DevanningDate__c = mship.MDevanningDate__c;
                    shipment.TransitV__c = mship.MTRANSIT_VESSEL__c;
                    shipment.TS__c = mship.MTRANSIT_PORT__c;
                    shipment.T_ETD__c = mship.MTRANSIT_T_ETD__c;
                    shipment.Master_B_L__c = mship.MMaster_B_L_No__c;
                    shipment.BookingNv__c = mship.MBookingNv__c;
                    shipment.LoadLocation__c = mship.MLoadLocation__c;
                    
                    if (mship.bondedtimetoCFS__c != null) {
                		shipment.LoadingTime__c = Date.newInstance(mship.bondedtimetoCFS__c.year(), mship.bondedtimetoCFS__c.month(), mship.bondedtimetoCFS__c.day()) ;
            		}
                    
                    if (PicklistReference.CONSOLIDATION_TYPE_CONSOLIDATION.equals(shipment.ConsolidationType__c) 
                        	&& !StringUtils.isEmpty(mship.MContainer_No__c)) {
                        shipment.ContainerSeal_No__c = ContainerInfoService.extractContainerNo(mship.MContainer_No__c);
                    } else if (PicklistReference.CONSOLIDATION_TYPE_MULTIPLE_BL.equals(shipment.ConsolidationType__c)) {
                        shipment.ContainerSeal_No__c = mship.MContainer_No__c;
                    }
                    
                    toBeUpdated.add(shipment);
                }
            }
            
            if (toBeUpdated.size() > 0) {
                try {
                    Database.SaveResult[] results = Database.update(FlsService.checkFls(AccessType.UPDATABLE, toBeUpdated).getRecords(), false);
                    if (results != null){
                        Integer index = 0;
                        String errorMessage = '';
                        
                        for (Database.SaveResult result : results) {
                            if (!result.isSuccess()) {
                                errorMessage = 'There are some H B/L_SHIPMENTs were failed to synchonize with M B/L-SHIPMENT';	
                                Database.Error[] errors = result.getErrors();
                                
                                for (Database.Error error : errors) {
                                }
                            }
							
                            index++;
                        }
                        
                        if (errorMessage.length() > 0) {
                            errorMessage = 'There is error occurred for some H B/L-SHIPMENTS. Error: ' + errorMessage;
                            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, errorMessage));
                        } else {
                            message = translations.get('MBL_HBL_COPY_COMPLETED');
                            if (StringUtils.isEmpty(message)) {
                            	message = 'Copying data from M B/L-SHIPMENT to H B/L-SHIPMENTS completed';
                            }
                            
	                    	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, message));    
                            shipmentWrappers = new List<HBLShipmentWrapper>();
                            loadRelatedHShips(mshipId);
                        }
                    }
                } catch (Exception e) {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'ERROR: ' + e.getMessage()));
                }
            }
        } else {
            errorMessage = 'Insufficient Permissions';
        }

        return null;
    }
}