force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Cnee__c.field-meta.xml
<CustomField>
    <fullName>Cnee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cnee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL_Number_SEA_AIR__c.field-meta.xml
<CustomField>
    <fullName>HBL_Number_SEA_AIR__c</fullName>
    <formula>IF ( ISNULL(HBL__c) || ISBLANK(HBL__c) ,  HAWB__c , HBL__c)</formula>
    <label>HBL Number（SEAorAIR）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + Id, &apos;S&apos; &amp;  WkInitial__c  &amp; Name , &apos;_top&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FORWARDING ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/REFNO__c.field-meta.xml
<CustomField>
    <fullName>REFNO__c</fullName>
    <label>REF NO</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/shipper__c.field-meta.xml
<CustomField>
    <fullName>shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shprs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>CARGO STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>輸出 出荷情報入手(Cargo Info Received)</fullName>
            </value>
            <value>
                <fullName>輸出 ブッキング情報入手(Booking Info Received)</fullName>
            </value>
            <value>
                <fullName>輸出 ブッキング情報変更(Booking Info Changed)</fullName>
            </value>
            <value>
                <fullName>輸出 ブッキング済(Booking Confirmed)</fullName>
            </value>
            <value>
                <fullName>輸出 貨物集荷済(Cargo Picked Up)</fullName>
            </value>
            <value>
                <fullName>輸出 配送出発済(On Delivery)</fullName>
            </value>
            <value>
                <fullName>輸出 入庫済(In Storage)</fullName>
            </value>
            <value>
                <fullName>輸出 通関申告書作成中(Application for Customs Clearance)</fullName>
            </value>
            <value>
                <fullName>輸出 税関審査中(Customs Examination)</fullName>
            </value>
            <value>
                <fullName>輸出 税関検査予定(Customs Inspection)</fullName>
            </value>
            <value>
                <fullName>輸出 輸出許可(Export Permitted)</fullName>
            </value>
            <value>
                <fullName>輸出 船積指示書情報登録済み(SI Data Registered)</fullName>
            </value>
            <value>
                <fullName>輸出 船積指示書(SI Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 フレイトメモ情報登録済み(Freight Memo Data Registered)</fullName>
            </value>
            <value>
                <fullName>輸出 フレイトメモ送付済(Freight Memo Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 B/L情報登録済み(B/L Data Registered)</fullName>
            </value>
            <value>
                <fullName>輸出 チェックB/L送付済(Check B/L Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 船荷証券送付済(B/L Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 データファイリング済み(Data Filed)</fullName>
            </value>
            <value>
                <fullName>輸出 本船/フライト出発済(Departured)</fullName>
            </value>
            <value>
                <fullName>輸出 本船/フライト遅延(Delayed)</fullName>
            </value>
            <value>
                <fullName>Outbound - Selling/Buying Amount Confirmed</fullName>
            </value>
            <value>
                <fullName>輸出  お客様入金処理/業者支払処理済</fullName>
            </value>
            <value>
                <fullName>輸出 許可書/請求書メール・ファクス送信済(An Export Permit/Invoice Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 請求書訂正有メール・ファクス再送信済(Revised Invoice Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 請求書送付済(Original Invoice Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 入金確認(Receipt of payment Confirmed)</fullName>
            </value>
            <value>
                <fullName>輸出 支払確認(Payment Confirmed)</fullName>
            </value>
            <value>
                <fullName>輸出 DEBIT/CREDITノート送付済み(Debit/Credit Note Issued)</fullName>
            </value>
            <value>
                <fullName>輸出 入金・支払確認(Deposit・Payment Confirmed)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Non_Standard_Exchange_Rate__c/Non_Standard_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_NonStandardExRateOnlineHelp</customHelpPage>
    <label>指定為替</label>
    <nameField>
        <displayFormat>NE-{000000}</displayFormat>
        <label>NON STANDARD EXCHANGE RATE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SyncExRateController.cls
/**
 * Created by khanhpham on 3/13/18.
 */

public with sharing class SyncExRateController {
    public List<ShipmentOrderWrapper> shipmentOrderWrappers { get; private set; }
    private Map<Id, CustomObject1__c> toBeSyncedShipmentOrders;
    public Non_Standard_Exchange_Rate__c dummyNonExRate { get; set; }
    public SearchCriteria searchCriteria { get; set; }
    private String queryString;

    public SyncExRateController() {
        shipmentOrderWrappers = new List<ShipmentOrderWrapper>();
        toBeSyncedShipmentOrders = new Map<Id, CustomObject1__c>();
        dummyNonExRate = new Non_Standard_Exchange_Rate__c();
        searchCriteria = new SearchCriteria();
        queryString = 'SELECT Id, ID__c, Name, REFNO__c, HBL_Number_SEA_AIR__c, toLabel(status__c), shipper__r.Name, ' +
                'Cnee__r.Name, ETA__c, ETD__c ' +
                'FROM CustomObject1__c';
    }

    public ApexPages.StandardSetController con {
        get {
            if (con == null) {
                con = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
                con.setPageSize(10);
            }
            return con;
        }
        set;
    }

    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }

    public void first() {
        con.first();
        prepareResult();
    }

    public void last() {
        con.last();
        prepareResult();
    }

    public void previous() {
        con.previous();
        prepareResult();
    }

    public void next() {
        con.next();
        prepareResult();
    }

    public void searchShipmentOrders() {
        con = null;

        queryString = 'SELECT Id, ID__c, Name, REFNO__c, HBL_Number_SEA_AIR__c, toLabel(status__c), shipper__r.Name, ' +
                'Cnee__r.Name, ETA__c, ETD__c ' +
                'FROM CustomObject1__c';
        String whereClause = '';

        if (!StringUtils.isEmpty(searchCriteria.shipmentName)) {
            queryString += (StringUtils.isEmpty(whereClause) ? ' WHERE ' : ' AND ');
            queryString += ' Name LIKE \'%' + searchCriteria.shipmentName + '%\'';
        }

        if (!StringUtils.isEmpty(searchCriteria.hblNo)) {
            queryString += (StringUtils.isEmpty(whereClause) ? ' WHERE ' : ' AND ');
            queryString += ' HBL_Number_SEA_AIR__c LIKE \'%' + searchCriteria.hblNo + '%\'';
        }

        prepareResult();
    }

    private void prepareResult() {
        shipmentOrderWrappers = new List<ShipmentOrderWrapper>();
        List<CustomObject1__c> shipmentOrders = (List<CustomObject1__c>) con.getRecords();

        if (shipmentOrders != null && !shipmentOrders.isEmpty()) {
            for (CustomObject1__c shipmentOrder : shipmentOrders) {
                shipmentOrderWrappers.add(new ShipmentOrderWrapper(shipmentOrder));
            }
        }
    }

    public PageReference addToList() {
        for (ShipmentOrderWrapper wrapper : shipmentOrderWrappers) {
            if (wrapper.checked & !toBeSyncedShipmentOrders.containsKey(wrapper.shipmentOrder.Id)) {
                toBeSyncedShipmentOrders.put(wrapper.shipmentOrder.Id, wrapper.shipmentOrder);
            }
        }

        return null;
    }

    public void synchronizeExchangeRate() {
        for (CustomObject1__c shipmentOrder : toBeSyncedShipmentOrders.values()) {
            ExchangeRateSynchronizationService.syncHBLShipmentAndSellingBuyings(shipmentOrder.Id);
        }
    }

    public PageReference removeFromList() {
        String removedId = ApexPages.currentPage().getParameters().get('shipmentOrderId');

        if (toBeSyncedShipmentOrders.containsKey(removedId)) {
            toBeSyncedShipmentOrders.remove(removedId);
        }

        return null;
    }

    public List<CustomObject1__c> getSelectedShipmentOrders() {
        return toBeSyncedShipmentOrders.values();
    }

    public class ShipmentOrderWrapper {
        public Boolean checked { get; set; }
        public CustomObject1__c shipmentOrder { get; private set; }

        public ShipmentOrderWrapper(CustomObject1__c shipmentOrder) {
            this.shipmentOrder = shipmentOrder;
            checked = false;
        }
    }

    public class SearchCriteria {
        public String shipmentName { get; set; }
        public String hblNo { get; set; }

        public SearchCriteria() {
            shipmentName = '';
            hblNo = '';
        }
    }
}