force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>従業員</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>EMPLOYEE MANAGEMENT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LunchBreakHours__c.field-meta.xml
<CustomField>
    <fullName>LunchBreakHours__c</fullName>
    <defaultValue>1</defaultValue>
    <description>How many hours for lunch break</description>
    <label>Lunch Break Hours</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time Entry</description>
    <label>打刻記録</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>TIME ENTRY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/BusinessHours__c.field-meta.xml
<CustomField>
    <fullName>BusinessHours__c</fullName>
    <description>Number of business hours of a worked day</description>
    <label>BUSINESS HOURS</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/BusinessHoursEndTime__c.field-meta.xml
<CustomField>
    <fullName>BusinessHoursEndTime__c</fullName>
    <label>BUSINESS HOUR END TIME</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/BusinessHoursStartTime__c.field-meta.xml
<CustomField>
    <fullName>BusinessHoursStartTime__c</fullName>
    <label>BUSINESS HOUR START TIME</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>USER ACCOUNT NAME</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TimeEntry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/EnterTime__c.field-meta.xml
<CustomField>
    <fullName>EnterTime__c</fullName>
    <label>ENTER TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/LeaveTime__c.field-meta.xml
<CustomField>
    <fullName>LeaveTime__c</fullName>
    <label>LEAVE TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/LogDate__c.field-meta.xml
<CustomField>
    <fullName>LogDate__c</fullName>
    <formula>DATEVALUE( EnterTime__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LOG DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/LoggedHours__c.field-meta.xml
<CustomField>
    <fullName>LoggedHours__c</fullName>
    <label>LOGGED HOUR</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/OnLeave__c.field-meta.xml
<CustomField>
    <fullName>OnLeave__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ON LEAVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/OT__c.field-meta.xml
<CustomField>
    <fullName>OT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OVERTIME WORKING</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/PublicHoliday__c.field-meta.xml
<CustomField>
    <fullName>PublicHoliday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PUBLIC HOLIDAY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TimeEntryService.cls
/**
 * Created by khanhpham on 6/21/17.
 */

public with sharing class TimeEntryService {
    private CalendarService caService;

//    public TimeEntryService() {
//        caService = new CalendarService();
//    }
//
//    public void updateLoggedTime(TimeEntry__c te) {
//        if (te.LeaveTime__c != null) {
//            te.LoggedHours__c = ((Decimal)DateTimeUtils.timeDiffInMinutes(te.EnterTime__c, te.LeaveTime__c))/60;
//        }
//    }
//
//    public void populateBusinessHours(TimeEntry__c te) {
//        Site_Custom_Settings__c settings = Site_Custom_Settings__c.getOrgDefaults();
//        CalendarService.BusinessHourWrapper bizHours = caService.getBusinessHours(te.LogDate__c);
//
//        if (bizHours.startTime == null || bizHours.endTime == null) {
//            throw new CustomException('No Business Hours found for the day');
//        }
//
//        DateTime beginTime = DateTime.newInstanceGmt(te.LogDate__c, bizHours.startTime);
//        te.BusinessHoursStartTime__c = beginTime.format('hh:mm a');
//
//        DateTime endTime = DateTime.newInstanceGmt(te.LogDate__c, bizHours.endTime);
//        te.BusinessHoursEndTime__c = endTime.format('hh:mm a');
//
//        Decimal businessHours = DateTimeUtils.timeDiffInMinutes(beginTime, endTime)/60;
//        if (businessHours > 4) {
//            Decimal lunchBreakHours = (settings.LunchBreakHours__c != null ? settings.LunchBreakHours__c : 1);
//            te.BusinessHours__c = businessHours - lunchBreakHours;
//        } else {
//            te.BusinessHours__c = businessHours;
//        }
//    }
//
//    public List<TimeEntry__c> findTimeEntryByUserAndDate(Id userId, Date findDate) {
//        try {
//            return [SELECT Id, EnterTime__c, LeaveTime__c, LoggedHours__c, OnLeave__c, PublicHoliday__c, OT__c
//            FROM TimeEntry__c
//            WHERE Employee__c = :userId AND LogDate__c = :findDate];
//        } catch(Exception e) {
//            return null;
//        }
//    }
//
//    public boolean isHoliday(Date dateToCheck) {
//        return caService.isHoliday(dateToCheck);
//    }
//
//    public String validate(TimeEntry__c te, boolean isNew) {
//        String result = '';
//
//        if (te.Employee__c == null) {
//            result = 'Employee field is required';
//        } else {
//            List<TimeEntry__c> existingTEs = findTimeEntryByUserAndDate(te.Employee__c, te.LogDate__c);
//
//            if (!existingTEs.isEmpty()) {
//                if (existingTEs.size() > 1) {
//                    result = 'There is an issue with existing data where having more than one time entries in the date '
//                            + te.LogDate__c.format() + ' for employee ' + te.Employee__c;
//                } else {
//                    TimeEntry__c existingTE = existingTEs.get(0);
//
//                    if ((isNew && (existingTE.OT__c || !existingTE.PublicHoliday__c)) || (!isNew && te.Id != existingTE.Id)) {
//                        result = 'Duplicated time entry';
//                    }
//                }
//            }
//        }
//
//        return result;
//    }
}