force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>従業員</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>EMPLOYEE MANAGEMENT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>BIRTH DAY</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/CloHRMStandard__c.field-meta.xml
<CustomField>
    <fullName>CloHRMStandard__c</fullName>
    <label>HR POLICY</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>HRStandard__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>HRStandard__c</referenceTo>
    <relationshipLabel>EMPLOYEE</relationshipLabel>
    <relationshipName>EMPLOYEE_MANAGEMENT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmployeeID__c.field-meta.xml
<CustomField>
    <fullName>EmployeeID__c</fullName>
    <label>EMPLOYEE ID NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRStandard__c/HRStandard__c.object-meta.xml
<CustomObject>
    <description>To setup basic information to manage Human Resources.</description>
    <label>人事管理標準</label>
    <nameField>
        <displayFormat>HR-{000000}</displayFormat>
        <label>HR STANDARD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HRStandard__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>After approval, checkbox will be checked.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HRStandard__c/fields/HealthInsuranceRatioByEmployee__c.field-meta.xml
<CustomField>
    <fullName>HealthInsuranceRatioByEmployee__c</fullName>
    <defaultValue>0.015</defaultValue>
    <label>HEALTH INSURANCE RATIO BY EMPLOYEE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HRStandard__c/fields/salarytocontributesocialinsurance__c.field-meta.xml
<CustomField>
    <fullName>salarytocontributesocialinsurance__c</fullName>
    <label>Salary to Contribute Social Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HRStandard__c/fields/SocialInsuracneRatioByEmployee__c.field-meta.xml
<CustomField>
    <fullName>SocialInsuracneRatioByEmployee__c</fullName>
    <defaultValue>0.08</defaultValue>
    <label>SOCIAL INSURANCE RATIO BY EMPLOYEE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HRStandard__c/fields/UnemploymentFundRatioByEmployee__c.field-meta.xml
<CustomField>
    <fullName>UnemploymentFundRatioByEmployee__c</fullName>
    <defaultValue>0.01</defaultValue>
    <label>UNEMPLOYMENT FUND RATIO BY EMPLOYEE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PayrollOrder__c/PayrollOrder__c.object-meta.xml
<CustomObject>
    <label>給料支払指示</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>PAYROLL ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PayrollOrder__c/fields/PayrollOrderName__c.field-meta.xml
<CustomField>
    <fullName>PayrollOrderName__c</fullName>
    <label>PAYROLL ORDER NAME</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayrollSlip__c/PayrollSlip__c.object-meta.xml
<CustomObject>
    <label>給料明細</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>PAYROLL SLIP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayrollSlip__c/fields/EmployeeID__c.field-meta.xml
<CustomField>
    <fullName>EmployeeID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EMPLOYEE ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>PAYROLL_SLIP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PayrollSlip__c/fields/hrpolicy__c.field-meta.xml
<CustomField>
    <fullName>hrpolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HR Policy</label>
    <referenceTo>HRStandard__c</referenceTo>
    <relationshipLabel>PAYSLIP</relationshipLabel>
    <relationshipName>PAYSLIP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PayrollSlip__c/fields/PayrollOrder__c.field-meta.xml
<CustomField>
    <fullName>PayrollOrder__c</fullName>
    <label>PAYROLL ORDER</label>
    <referenceTo>PayrollOrder__c</referenceTo>
    <relationshipName>PAYROLL_SLIP</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayrollSlip__c/fields/SalaryToContributeSocialInsurance__c.field-meta.xml
<CustomField>
    <fullName>SalaryToContributeSocialInsurance__c</fullName>
    <formula>hrpolicy__r.salarytocontributesocialinsurance__c</formula>
    <inlineHelpText>If Actual Gross Base is greater or equal to Minimum Salary Base Amount in HR Policy, Salary to Contribute Social Insurance=Minimum Salary Base Amount in HR Policy,
Otherwise, Salary To Contribute Social Insurance=Actual Gross Base</inlineHelpText>
    <label>SALARY TO CONTRIBUTE SOCIAL INSURANCE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PayslipTriggerHandlerTest.cls
@isTest
private class PayslipTriggerHandlerTest {
	private static Employee__c employee;
	private static PayrollOrder__c payOrder;
	private static HRStandard__c hrPolicy;
	static{
		hrPolicy = new HRStandard__c(
			salarytocontributesocialinsurance__c = 30000,
			SocialInsuracneRatioByEmployee__c = 8,
			HealthInsuranceRatioByEmployee__c = 2,
			UnemploymentFundRatioByEmployee__c = 1,
			Active__c = true);
        FlsService.doInsert(hrPolicy);
		employee = new Employee__c(
			CloHRMStandard__c = hrPolicy.Id,
			Birthday__c = Date.today()
		);
        FlsService.doInsert(employee);
		payOrder = new PayrollOrder__c(
			PayrollOrderName__c ='test');
        FlsService.doInsert(payOrder);
	}
	
	@isTest static void test_method_one() {
		Test.startTest();

		 PayrollSlip__c payslip = new PayrollSlip__c(
		 	EmployeeID__c = employee.Id,
		 	PayrollOrder__c = payOrder.Id,
			hrpolicy__c = hrPolicy.Id
			 );
        FlsService.doInsert(payslip);
		 system.assert(payslip != null);
		Test.stopTest();
	}
}