force-app/main/default/objects/PurchasingOrder__c/PurchasingOrder__c.object-meta.xml
<CustomObject>
    <label>購買注文</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>PURCHASING ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>PURCHASING STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <label>Payment processing</label>
            </value>
            <value>
                <fullName>Payment Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchasingOrder__c/recordTypes/LockedPurchasingOrder.recordType-meta.xml
<RecordType>
    <fullName>LockedPurchasingOrder</fullName>
    <active>true</active>
    <label>Locked Purchasing Order</label>
</RecordType>

force-app/main/default/objects/PurchasingOrder__c/recordTypes/PurchasingOrder.recordType-meta.xml
<RecordType>
    <fullName>PurchasingOrder</fullName>
    <active>true</active>
    <label>Purchasing Order</label>
</RecordType>

force-app/main/default/classes/PurchasingOrderTriggerHandlerTest.cls
/**
 * Created by khanhpham on 5/25/17.
 */
@IsTest(SeeAllData = false)
private with sharing class PurchasingOrderTriggerHandlerTest {
    @TestSetup static void setUp() {
        String poRecordTypeId = RecordTypeUtil.getRecordTypeIdByDeveloperName(PurchasingOrder__c.SObjectType, 'PurchasingOrder');

        Map<String, Object> additionalFields = new Map<String, Object>{
                'RecordTypeId' => poRecordTypeId
        };
        TestDataFactory.createSObject(new PurchasingOrder__c(), true, additionalFields);
    }

    @IsTest static void shouldLockOnCompletion() {
        PurchasingOrder__c po = [SELECT Status__c FROM PurchasingOrder__c LIMIT 1];
        String poLockedRecordTypeId = RecordTypeUtil.getRecordTypeIdByDeveloperName(PurchasingOrder__c.SObjectType, 'LockedPurchasingOrder');

        System.assertNotEquals(po.Status__c, 'Payment Settled');
        Test.startTest();
        po.Status__c = 'Payment Settled';
        FlsService.doUpdate(po);
        Test.stopTest();
        po = [SELECT RecordTypeId, Status__c FROM PurchasingOrder__c LIMIT 1];
        System.assertEquals(po.RecordTypeId, poLockedRecordTypeId);
    }
}