force-app/main/default/objects/PurchasingOrder__c/PurchasingOrder__c.object-meta.xml
<CustomObject>
    <label>購買注文</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>PURCHASING ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>PURCHASING STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Payment Processing</fullName>
                <label>Payment processing</label>
            </value>
            <value>
                <fullName>Payment Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchasingOrder__c/fields/TotalUnpaidBalanceLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalUnpaidBalanceLocal__c</fullName>
    <inlineHelpText>Roll-up Sum of Unpaid Balance of Purchasing(Local) in Purchasing Invoice Object.</inlineHelpText>
    <label>TOTAL UNPAID PURCHASING BALANCE(LOCAL)</label>
    <summarizedField>PurchasingInvoice__c.UnpaidBalanceLocal__c</summarizedField>
    <summaryFilterItems>
        <field>PurchasingInvoice__c.Currency__c</field>
        <operation>notEqual</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryForeignKey>PurchasingInvoice__c.PurchasingOrder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/PurchasingOrderTriggerHandler.cls
/**
 * Created by khanhpham on 5/18/17.
 */

public with sharing class PurchasingOrderTriggerHandler extends AbstractTriggerHandler {
    public override void beforeUpdate(SObject oldSo, SObject so) {
        PurchasingOrder__c oldPO = (PurchasingOrder__c) oldSo;
        PurchasingOrder__c newPO = (PurchasingOrder__c) so;

        lockRecordOnCompletion(oldPO, newPO);
    }

    private void lockRecordOnCompletion(PurchasingOrder__c oldPO, PurchasingOrder__c newPO) {
        if (!(PicklistReference.PO_PAYMENT_SETTLED.equalsIgnoreCase(oldPO.Status__c) && oldPO.TotalUnpaidBalanceLocal__c == 0)
                && (PicklistReference.PO_PAYMENT_SETTLED.equalsIgnoreCase(newPO.Status__c) && newPO.TotalUnpaidBalanceLocal__c == 0)) {
            String recordTypeId = RecordTypeUtil.getRecordTypeIdByDeveloperName(PurchasingOrder__c.SObjectType, Constants.PO_LOCK_RT);

            if (recordTypeId != null) {
                newPO.RecordTypeId = recordTypeId;
            }
        }
    }
}