force-app/main/default/objects/LoadingLocation__c/LoadingLocation__c.object-meta.xml
<CustomObject>
    <description>Location where truck will load or unload cargo</description>
    <label>荷積み・荷下ろし</label>
    <nameField>
        <displayFormat>LL-{000000}</displayFormat>
        <label>LOADING LOCATION NUMBER</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LoadingLocation__c/fields/CargoMeasurement__c.field-meta.xml
<CustomField>
    <fullName>CargoMeasurement__c</fullName>
    <label>CARGO MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/CargoWeight__c.field-meta.xml
<CustomField>
    <fullName>CargoWeight__c</fullName>
    <label>CARGO WEIGHT(KG)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/HandlingType__c.field-meta.xml
<CustomField>
    <fullName>HandlingType__c</fullName>
    <label>HANDLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Load</fullName>
            </value>
            <value>
                <fullName>Moving</fullName>
            </value>
            <value>
                <fullName>Unload</fullName>
            </value>
            <value>
                <fullName>Partially Load</fullName>
            </value>
            <value>
                <fullName>Partially Unload</fullName>
            </value>
            <value>
                <fullName>Return To Truck Carage</fullName>
                <label>Return To Truck Garage</label>
            </value>
            <value>
                <fullName>From Truck Garage to ICD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>ROUTE ID</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>LoadingLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>SEQUENCE NUMBER</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>ルート</label>
    <nameField>
        <displayFormat>RL-{000000}</displayFormat>
        <label>ROUTE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/RoutingDate__c.field-meta.xml
<CustomField>
    <fullName>RoutingDate__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>ROUTING START DATE</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TRUCK ID</label>
    <referenceTo>TruckFleet__c</referenceTo>
    <relationshipLabel>ROUTE (TRUCK)</relationshipLabel>
    <relationshipName>RouteTruck</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TruckFleet__c/TruckFleet__c.object-meta.xml
<CustomObject>
    <label>トラック・車両</label>
    <nameField>
        <displayFormat>TF-{000000}</displayFormat>
        <label>TRUCK &amp; FLEET ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TruckFleet__c/fields/MaximumMeasurement__c.field-meta.xml
<CustomField>
    <fullName>MaximumMeasurement__c</fullName>
    <label>MAXIMUM MEASURMENT(CBM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TruckFleet__c/fields/MaximumWeight__c.field-meta.xml
<CustomField>
    <fullName>MaximumWeight__c</fullName>
    <inlineHelpText>In case of Vessel, input Gross Tonnage into this field.</inlineHelpText>
    <label>MAXIMUM WEIGHT(TON)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ObjectCloningServiceTest.cls
/**
 * Created by khanhpham on 5/7/17.
 */
@IsTest(SeeAllData = false)
private class ObjectCloningServiceTest {
    @TestSetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object>{
                'MaximumWeight__c' => 1, 'MaximumMeasurement__c' => 100
        };
        TruckFleet__c truckFleet = (TruckFleet__c) TestDataFactory.createSObject(new TruckFleet__c(), true, additionalFields);

        additionalFields = new Map<String, Object>{
                'RoutingDate__c' => Date.today(), 'Truck__c' => truckFleet.Id
        };
        Route__c route = (Route__c) TestDataFactory.createSObject(new Route__c(), true, additionalFields);

        additionalFields = new Map<String, Object>{
                'HandlingType__c' => LoadingLocationTriggerHandler.TRUCK_HANDLE_LOAD, 'SequenceNumber__c' => 1,
                'Route__c' => route.Id, 'CargoWeight__c' => 100, 'CargoMeasurement__c' => 10
        };
        TestDataFactory.createSObject(new LoadingLocation__c(), true, additionalFields);

        additionalFields = new Map<String, Object>{
                'HandlingType__c' => LoadingLocationTriggerHandler.TRUCK_HANDLE_LOAD, 'SequenceNumber__c' => 2,
                'Route__c' => route.Id, 'CargoWeight__c' => 200, 'CargoMeasurement__c' => 20
        };
        TestDataFactory.createSObject(new LoadingLocation__c(), true, additionalFields);
    }

    @IsTest static void shouldDeepCloneRoute() {
        Route__c route = [SELECT Id, RoutingDate__c, Truck__c FROM Route__c LIMIT 1];

        Test.startTest();
        String clonedId = ObjectCloningService.cloneDeepRoute(route.Id);
        Test.stopTest();

        Route__c clonedRoute = [SELECT Id, RoutingDate__c, Truck__c FROM Route__c LIMIT 1];
        System.assertNotEquals(null, clonedId);
        System.assertEquals(route.Truck__c, clonedRoute.Truck__c);

        List<LoadingLocation__c> locations = [SELECT Id FROM LoadingLocation__c WHERE Route__c = :clonedId];
        System.assertEquals(2, locations.size());
    }
}