force-app/main/default/objects/LoadingLocation__c/LoadingLocation__c.object-meta.xml
<CustomObject>
    <description>Location where truck will load or unload cargo</description>
    <label>荷積み・荷下ろし</label>
    <nameField>
        <displayFormat>LL-{000000}</displayFormat>
        <label>LOADING LOCATION NUMBER</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LoadingLocation__c/fields/ActualArrivalTime__c.field-meta.xml
<CustomField>
    <fullName>ActualArrivalTime__c</fullName>
    <label>ACTUAL ARRIVAL TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/ArrivalTime__c.field-meta.xml
<CustomField>
    <fullName>ArrivalTime__c</fullName>
    <label>ESTIMATED ARRIVAL TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/LoadingUnloadingStatus__c.field-meta.xml
<CustomField>
    <fullName>LoadingUnloadingStatus__c</fullName>
    <label>LOADING &amp; UNLOADING STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>On Arrangement</fullName>
            </value>
            <value>
                <fullName>CompletedInSchedule</fullName>
                <label>Completed in Schedule</label>
            </value>
            <value>
                <fullName>Completed In Delay</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>ROUTE ID</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>LoadingLocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LoadingLocation__c/fields/StartingTime__c.field-meta.xml
<CustomField>
    <fullName>StartingTime__c</fullName>
    <label>ESTIMATED START TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>ルート</label>
    <nameField>
        <displayFormat>RL-{000000}</displayFormat>
        <label>ROUTE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ObjectCloningService.cls
/**
 * This is a webservice to clone object
 *
 * Created by khanhpham on 5/5/17.
 */

global with sharing class ObjectCloningService {
    webService static String cloneDeepRoute(final String routeId) {
        String clonedRouteId = cloneRoute(routeId);

        if (String.isNotBlank(clonedRouteId)) {
            cloneLoadLocationsByRoute(routeId, clonedRouteId);
        }

        return clonedRouteId;
    }

    private static void cloneLoadLocationsByRoute(final String routeId, final String clonedRouteId) {
        Schema.SObjectType objectType = LoadingLocation__c.Schema.SObjectType;
        String query = 'SELECT Id, Name, ' + getCustomFieldNames(objectType)
                + ' FROM ' + objectType
                + ' WHERE Route__r.Id =\'' + routeId + '\'';
        List<LoadingLocation__c> loadingLocationList = Database.query(query);

        if (loadingLocationList != null && !loadingLocationList.isEmpty()) {
            List<LoadingLocation__c> clonedLoadingLocationList = loadingLocationList.deepClone();

            if (clonedLoadingLocationList != null && !clonedLoadingLocationList.isEmpty()) {
                for (LoadingLocation__c location : clonedLoadingLocationList) {
                    location.Route__c = clonedRouteId;

                    /*
                        Reset fields
                     */
                    location.LoadingUnloadingStatus__c = null;
                    location.ActualStartTime__c = null;
                    location.ActualArrivalTime__c = null;
                    location.StartingTime__c = null;
                    location.ArrivalTime__c = null;
                }

                FlsService.doInsert(clonedLoadingLocationList);
            }
        }
    }

    private static String cloneRoute(final String routeId) {
        Schema.SObjectType objectType = Route__c.Schema.SObjectType;
        String query = 'SELECT Id, Name, ' + getCustomFieldNames(objectType)
                + ' FROM ' + objectType
                + ' WHERE Id =\'' + routeId + '\'';
        List<Route__c> routeList = Database.query(query);

        if (routeList != null && !routeList.isEmpty()) {
            List<Route__c> clonedRouteList = routeList.deepClone();

            if (clonedRouteList != null && !clonedRouteList.isEmpty()) {
                FlsService.doInsert(clonedRouteList);
                return clonedRouteList.get(0).Id;
            }
        }

        return null;
    }

    private static String getCustomFieldNames(Schema.SObjecttype tp){
        List<String> customFieldNames = new List<String>();

        Map<String,Schema.sObjectField> fmap = tp.getDescribe().fields.getMap();
        for(String fn:fmap.keySet()){
            if(fn.endswith('__c')){
                customFieldNames.add(fn);
            }
        }
        return String.join(customFieldNames, ',');
    }
}