force-app/main/default/objects/ContainerGoodSO__c/ContainerGoodSO__c.object-meta.xml
<CustomObject>
    <label>Container (Goods S/O)</label>
    <nameField>
        <displayFormat>CTR-{000000}</displayFormat>
        <label>CNTR (Goods S/O) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Container (Goods S/Os)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContainerGoodSO__c/fields/ContainerNumber__c.field-meta.xml
<CustomField>
    <fullName>ContainerNumber__c</fullName>
    <label>Container Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/GOODSSO__c.field-meta.xml
<CustomField>
    <fullName>GOODSSO__c</fullName>
    <label>GOODS S/O</label>
    <referenceTo>SALES_ORDER__c</referenceTo>
    <relationshipLabel>Container (Goods S/Os)</relationshipLabel>
    <relationshipName>Container_Goods_S_Os</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/GrossWeightMT__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightMT__c</fullName>
    <label>Gross Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/NetWeightMT__c.field-meta.xml
<CustomField>
    <fullName>NetWeightMT__c</fullName>
    <label>Net Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/SealNumber__c.field-meta.xml
<CustomField>
    <fullName>SealNumber__c</fullName>
    <label>Seal Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/TRSBill__c.field-meta.xml
<CustomField>
    <fullName>TRSBill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TRS Bill</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TRSBill__c.SalesOrderID__c</field>
            <operation>equals</operation>
            <valueField>$Source.GOODSSO__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TRSBill__c</referenceTo>
    <relationshipLabel>Container (Goods S/Os)</relationshipLabel>
    <relationshipName>TRSBill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract.</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>CONTRACT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_ORDER__c/SALES_ORDER__c.object-meta.xml
<CustomObject>
    <label>Goods S/O</label>
    <nameField>
        <displayFormat>GS-{000000}</displayFormat>
        <label>GOODS SALES ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods S/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_ORDER__c/fields/ContractID__c.field-meta.xml
<CustomField>
    <fullName>ContractID__c</fullName>
    <label>CONTRACT ID</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/TRSBill__c.object-meta.xml
<CustomObject>
    <label>TRS Bill</label>
    <nameField>
        <displayFormat>TB-{000000}</displayFormat>
        <label>TRS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TRS Bill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TRSBill__c/fields/GrossWeightMT__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightMT__c</fullName>
    <label>Gross Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/fields/NetWeightMT__c.field-meta.xml
<CustomField>
    <fullName>NetWeightMT__c</fullName>
    <label>Net Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/fields/ProductNameonPackingList__c.field-meta.xml
<CustomField>
    <fullName>ProductNameonPackingList__c</fullName>
    <label>Product Name on Packing List</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/fields/SalesOrderID__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderID__c</fullName>
    <label>SALES ORDER ID</label>
    <referenceTo>SALES_ORDER__c</referenceTo>
    <relationshipLabel>TRS BILL</relationshipLabel>
    <relationshipName>TRSBill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorldExportControllerTest.cls
@isTest
private class WorldExportControllerTest {
    private static SALES_ORDER__c so {get; set;}
    static{
        Contract__c contract = new Contract__c();
        FlsService.doInsert(contract);

        so = new SALES_ORDER__c(
            ContractID__c = contract.Id
        );
        FlsService.doInsert(so);

        TRSBill__c trsBill = new TRSBill__c(
        	SalesOrderID__c = so.Id,
            ProductNameonPackingList__c = 'Test TRS Bill'
        );
        FlsService.doInsert(trsBill);
        
        ContainerGoodSO__c container = new ContainerGoodSO__c(
        	GOODSSO__c = so.Id,
            TRSBill__c = trsBill.Id,
            ContainerNumber__c = 'c123',
            SealNumber__c = 's123',
            NetWeightMT__c = 5,
            GrossWeightMT__c = 10
        );
        FlsService.doInsert(container);
    }
    
    @isTest static void testWorldExportController() {
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', so.Id);
        ApexPages.currentPage().getParameters().put('showFooter', 'true');
		WorldExportController weController = new WorldExportController();
        System.assert(true == true, 'Success');
        Test.stopTest();
    }
}