force-app/main/default/objects/ApplicationLineCargo__c/ApplicationLineCargo__c.object-meta.xml
<CustomObject>
    <label>Application Line+Cargo</label>
    <nameField>
        <displayFormat>ALCG-{000000}</displayFormat>
        <label>APPLICATION LINE+CARGO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line+Cargo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLineCargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>APPLICATION LINE+CARGO</relationshipLabel>
    <relationshipName>Cargo</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>LastWosLineItem__r.WorkOrderID__r.Customer__r.Name</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ExpiredDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiredDate__c</fullName>
    <label>EXPIRED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locator for Manual Operation</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ManufacturedDate__c.field-meta.xml
<CustomField>
    <fullName>ManufacturedDate__c</fullName>
    <label>MANUFACTURED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <deprecated>true</deprecated>
    <description>Quantity of product inside the cargo</description>
    <inlineHelpText>Quantity of product inside the cargo</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/QuantityCal__c.field-meta.xml
<CustomField>
    <fullName>QuantityCal__c</fullName>
    <formula>IF( 
ISPICKVAL(Product__r.BillingType__c, &apos;Weight&apos;),
WeightCal__c,
MAX(1,LotQuantity__c) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity (calculated)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/LOCATOR__c.object-meta.xml
<CustomObject>
    <label>Locator</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>LOCATOR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>LOCATOR</relationshipLabel>
    <relationshipName>Locator</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>STOCK LIST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>STOCK (CUSTOMER)</relationshipLabel>
    <relationshipName>STOCK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/ExpiredDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiredDate__c</fullName>
    <label>EXPIRED DATE(Old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/ManufacturedDate__c.field-meta.xml
<CustomField>
    <fullName>ManufacturedDate__c</fullName>
    <label>MANUFACTURED DATE(Old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WorkOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/ActualEndTime__c.field-meta.xml
<CustomField>
    <fullName>ActualEndTime__c</fullName>
    <label>ACTUAL END TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/InitialQuantity__c.field-meta.xml
<CustomField>
    <fullName>InitialQuantity__c</fullName>
    <label>INITIAL QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/MissingQuantity__c.field-meta.xml
<CustomField>
    <fullName>MissingQuantity__c</fullName>
    <label>MISSING QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PlannedQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlannedQuantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WorkStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/CargoStatus__c.field-meta.xml
<CustomField>
    <fullName>CargoStatus__c</fullName>
    <label>Cargo Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
                <isActive>false</isActive>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>WorkOrderService__r.WorkOrder__r.Customer__c</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipName>WOSLineItemID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/WorkStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Resource Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Accept Cargo Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>On Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Data Transfer To Next Process</fullName>
        <isActive>false</isActive>
        <label>Data Transfer To Next Process</label>
    </customValue>
    <masterLabel>WORK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderServiceTriggerHelper.cls
public with sharing class WorkOrderServiceTriggerHelper {
    public static void autoPopulateFields(List<WorkOrderService__c> listNew, Map<Id, WorkOrderService__c> mapOld) {
        Set<Id> setLocator = new Set<Id>();
        List<WorkOrderService__c> listUpdateFromLocator = new List<WorkOrderService__c>();
        for (WorkOrderService__c item : listNew) {
            //default values
            item.InitialQuantity__c = item.InitialQuantity__c == null ? 0 : item.InitialQuantity__c;
            item.PlannedQuantity__c = item.PlannedQuantity__c == null ? 0 : item.PlannedQuantity__c;
            item.MissingQuantity__c = item.MissingQuantity__c == null ? 0 : item.MissingQuantity__c;

            if (item.Locator__c != null && item.Warehouse__c == null) {
                setLocator.add(item.Locator__c);
                listUpdateFromLocator.add(item);
            }
            if (item.InitialQuantity__c == 0) {
                item.InitialQuantity__c = item.PlannedQuantity__c;
            }
            item.MissingQuantity__c = item.PlannedQuantity__c - item.InitialQuantity__c;

            if (item.Status__c == 'Completed' && item.ActualEndTime__c == null) {
                item.ActualEndTime__c = System.now();
            }
        }
        Map<Id, Locator__c> mapLocator = new Map<Id, Locator__c>([SELECT WarehouseId__c FROM Locator__c WHERE Id IN :setLocator]);
        for (WorkOrderService__c item : listUpdateFromLocator) {
            item.Warehouse__c = mapLocator.get(item.Locator__c).WarehouseId__c;
        }
    }

    public static void generateStockAndUpdateCargoLifeCycle(List<WorkOrderService__c> listNew, Map<Id, WorkOrderService__c> mapOld) {
        Set<Id> setIdToGenStock = new Set<Id>();
        Set<Id> setIdToUpdateCargo = new Set<Id>();

        for (WorkOrderService__c item : listNew) {
            if (item.Status__c != 'Completed' || mapOld.get(item.Id).Status__c == item.Status__c) {
                return;
            }

            if (item.RecordTypeId == Constants.RecordTypeId_Wos_Picking || item.RecordTypeId == Constants.RecordTypeId_Wos_PutAway) {
                setIdToGenStock.add(item.Id);
                setIdToUpdateCargo.add(item.Id);
            } else if (item.RecordTypeId == Constants.RecordTypeId_Wos_OutboundDispatch) {
                setIdToUpdateCargo.add(item.Id);
            }
        }
        
        if (!setIdToGenStock.isEmpty()) {
            genStockAndUpdateCount(setIdToGenStock);
        }
        
        if (!setIdToUpdateCargo.isEmpty()) {
            updateCargoStatus(setIdToUpdateCargo);
        }
    }

    @future
    private static void genStockAndUpdateCount(Set<Id> setWosIds) {
        List<WosLineItem__c> listWosLineToGenStock = [
            SELECT Id, Locator__c
                , Locator__r.WarehouseID__c
                , WorkOrderService__r.RecordTypeId, WorkOrderService__r.WorkOrder__r.Customer__c
                , Cargo__r.ExpiredDate__c, Cargo__r.ManufacturedDate__c, Cargo__r.Product__c, Cargo__r.QuantityCal__c
            FROM WosLineItem__c
            WHERE WorkOrderService__c IN :setWosIds
                AND CargoStatus__c = 'Completed'
        ];

        if (listWosLineToGenStock.isEmpty()) {
            return;
        }

        List<Stock__c> listStock = new List<Stock__c>();
        Map<String, Integer> invLogStockIn = new Map<String, Integer>();
        Map<String, Integer> invLogStockOut = new Map<String, Integer>();
        for(WosLineItem__c item: listWosLineToGenStock) {
            String invLogCid = item.Locator__r.WarehouseID__c + '-' + item.Cargo__r.Product__c;
            if (item.WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_Picking) {
                invLogStockOut.put(invLogCid, (invLogStockOut.containsKey(invLogCid) ? invLogStockOut.get(invLogCid) : 0) + Integer.valueOf(item.Cargo__r.QuantityCal__c));
            } else if (item.WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_PutAway){
                invLogStockIn.put(invLogCid, (invLogStockIn.containsKey(invLogCid) ? invLogStockIn.get(invLogCid) : 0) + Integer.valueOf(item.Cargo__r.QuantityCal__c));
            }

            listStock.add(new Stock__c(
                Customer__c = item.WorkOrderService__r.WorkOrder__r.Customer__c,
                ExpiredDate__c = item.Cargo__r.ExpiredDate__c,
                ManufacturedDate__c = item.Cargo__r.ManufacturedDate__c,
                ProductID__c = item.Cargo__r.Product__c,
                Quantity__c = item.Cargo__r.QuantityCal__c,
                StockDate__c = System.today(),
                StockCountStartDate__c = System.today(),
                StockLocator__c = item.Locator__c,
                StockStatus__c = 'Completed',
                WOSLineID__c = item.Id,
                WorkOrderServiceID__c = item.WorkOrderService__r.Id,
                RecordTypeId = item.WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_Picking ? Constants.RecordTypeId_Stock_StockOut : Constants.RecordTypeId_Stock_StockIn
            ));
        }
        
        FlsService.doInsert(listStock);

        //UPDATE INVENTORY LOG
        List<InventoryLog__c> listInvLog = [SELECT Id, CompoundId__c, StockInQuantity__c, StockOutQuantity__c FROM InventoryLog__c WHERE CompoundId__c IN :invLogStockIn.keySet()  OR CompoundId__c IN :invLogStockOut.keySet()];
        for (InventoryLog__c item : listInvLog) {
            item.StockInQuantity__c = (item.StockInQuantity__c == null ? 0 : item.StockInQuantity__c) + (invLogStockIn.containsKey(item.CompoundId__c) ? invLogStockIn.get(item.CompoundId__c) : 0);
            item.StockOutQuantity__c = (item.StockOutQuantity__c == null ? 0 : item.StockOutQuantity__c) + (invLogStockOut.containsKey(item.CompoundId__c) ? invLogStockOut.get(item.CompoundId__c) : 0);
        }
        
        if (!listInvLog.isEmpty()) {
		    FlsService.doUpdate(listInvLog);
        }
    }
    
    @future
    private static void updateCargoStatus(Set<Id> setWosIds) {
        List<Cargo__c> listCargoes = [SELECT Id, CargoLifeCycle__c, LastWosLineItem__r.WorkOrderService__r.RecordTypeId, LastWosLineItem__r.WorkOrderService__r.ActualEndTime__c FROM Cargo__c WHERE LastWosLineItem__r.WorkOrderService__c IN :setWosIds];
        
        if (listCargoes.isEmpty()) {
            return;
        }

        Set<String> listExcludedStatuses = new Set<String> { 'Damaged', 'Missing' };

        for (Cargo__c item : listCargoes) {
            if (item.LastWosLineItem__r.WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_PutAway) {
                item.InboundDate__c = item.LastWosLineItem__r.WorkOrderService__r.ActualEndTime__c;
                item.InboundDate__c = item.InboundDate__c == null ? System.now() : item.InboundDate__c;

                if (!listExcludedStatuses.contains(item.CargoLifeCycle__c)) {
                    item.CargoLifeCycle__c = 'For sales';
                }
            } else if (item.LastWosLineItem__r.WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_OutboundDispatch) {
                item.OutboundDate__c = item.LastWosLineItem__r.WorkOrderService__r.ActualEndTime__c;
                item.OutboundDate__c = item.OutboundDate__c == null ? System.now() : item.OutboundDate__c;
                
                if (!listExcludedStatuses.contains(item.CargoLifeCycle__c)) {
                    item.CargoLifeCycle__c = 'No longer exists';
                }
            }
        }

		FlsService.doUpdate(listCargoes);
    }
}