force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>WMS Bill</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>WMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WMS Bill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/BillingDisplayNo__c.field-meta.xml
<CustomField>
    <fullName>BillingDisplayNo__c</fullName>
    <label>BILLING DISPLAY NO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/ChargeUnitFormula__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnitFormula__c</fullName>
    <formula>IF(TEXT( Unit__c ) != NULL
, TEXT( Unit__c )
, TEXT(   PricingName__r.UNIT__c   )
)</formula>
    <label>Charge Unit-Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/ChargeUnitinPrint__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnitinPrint__c</fullName>
    <label>Charge Unit in Print</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/ContainerrSizeFormula__c.field-meta.xml
<CustomField>
    <fullName>ContainerrSizeFormula__c</fullName>
    <formula>IF(TEXT( ContainerSize__c ) != NULL
, TEXT( ContainerSize__c )
, TEXT( PricingName__r.ContainerSize__c )
)</formula>
    <label>Container Size-Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipName>BILLING</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Standard Billing</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/MaxNoBilling__c.field-meta.xml
<CustomField>
    <fullName>MaxNoBilling__c</fullName>
    <label>MaxNoBilling</label>
    <summarizedField>Billing__c.BillingDisplayNo__c</summarizedField>
    <summaryForeignKey>Billing__c.WorkOrderID__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BillingTriggerHelper.cls
public with sharing class BillingTriggerHelper {
	public static void onBeforeInsert(List<Billing__c> newBilling){
		Set<Id> workOrderIdSet = new Set<Id>();
		for( Billing__c billing : newBilling){
			if(billing.WorkOrderID__c != null){
				workOrderIdSet.add(billing.WorkOrderID__c);
			}
			
		}
		Map<Id, Decimal> mapMaxNoBilling = new Map<Id, Decimal>();
		// get list oldBilling
		List<WorkOrder__c> listWorkOrder = [SELECT Id, MaxNoBilling__c FROM WorkOrder__c WHERE Id IN: workOrderIdSet];
		for(WorkOrder__c workOrder : listWorkOrder){
			Decimal maxNo = 0;
			if(workOrder.MaxNoBilling__c ==null){
				mapMaxNoBilling.put(workOrder.Id, 0);
			}else{
				mapMaxNoBilling.put(workOrder.Id, workOrder.MaxNoBilling__c);
			}
			
		}
		for( Billing__c billing : newBilling){
			if(billing.WorkOrderID__c == null){
				continue;
			}
			billing.BillingDisplayNo__c = 0;
			billing.BillingDisplayNo__c = mapMaxNoBilling.get(billing.WorkOrderID__c) + 1;
			mapMaxNoBilling.put(billing.WorkOrderID__c, billing.BillingDisplayNo__c);
		}
	}
    
    public static void translateUnitValue(List<Billing__c> newBills){
        //get unit formula value.
        
        for(Billing__c bill : newBills){
            
            bill.ChargeUnitInPrint__c = bill.ChargeUnitFormula__c;
            if(bill.ChargeUnitFormula__c =='本'){
                bill.ChargeUnitInPrint__c = 'Unit';
            } 
            if(bill.ChargeUnitFormula__c =='コンテナ' || bill.ChargeUnitFormula__c =='Container'){
                bill.ChargeUnitInPrint__c = bill.ContainerrSizeFormula__c;
            }
            if(bill.ChargeUnitFormula__c =='件'){
                bill.ChargeUnitInPrint__c = 'Case';
            }
        }
    }
	public static void onBeforeUpdate(List<Billing__c> newBilling){
		//Set<Id> workOrderIdSet = new Set<Id>();
		//for( Billing__c billing : newBilling){
		//	if(billing.WorkOrderID__c != null){
		//		workOrderIdSet.add(billing.WorkOrderID__c);
		//	}
			
		//}
		//Map<Id, Decimal> mapMaxNoBilling = new Map<Id, Decimal>();
		//// get list oldBilling
		//List<WorkOrder__c> listWorkOrder = [SELECT Id, MaxNoBilling__c FROM WorkOrder__c WHERE Id IN: workOrderIdSet];
		//for(WorkOrder__c workOrder : listWorkOrder){
		//	Decimal maxNo = 0;
		//	if(workOrder.MaxNoBilling__c ==null){
		//		mapMaxNoBilling.put(workOrder.Id, 0);
		//	}else{
		//		mapMaxNoBilling.put(workOrder.Id, workOrder.MaxNoBilling__c);
		//	}
			
		//}
		//for( Billing__c billing : newBilling){
		//	if(billing.WorkOrderID__c == null){
		//		continue;
		//	}
		//	billing.BillingDisplayNo__c = 0;
		//	billing.BillingDisplayNo__c = mapMaxNoBilling.get(billing.WorkOrderID__c) + 1;
		//	mapMaxNoBilling.put(billing.WorkOrderID__c, billing.BillingDisplayNo__c);
		//}
	}
}