force-app/main/default/objects/CloFMSBillBank__c/CloFMSBillBank__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+Bank</label>
    <nameField>
        <displayFormat>BB-{000000}</displayFormat>
        <label>FMS BILL+BANK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+Bank</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CloFMSBillBank__c/fields/BankTransactionID__c.field-meta.xml
<CustomField>
    <fullName>BankTransactionID__c</fullName>
    <label>BANK TRANSACTION ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipName>CloFMSBillBank</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CloFMSBillBank__c/fields/CloFMSBillID__c.field-meta.xml
<CustomField>
    <fullName>CloFMSBillID__c</fullName>
    <label>CloFMS BILL ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>AnkenMeisai__c.BuyDifferentiation__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>AnkenMeisai__c.UNPAID_BALANCE_OF_BUYING_USD__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>AnkenMeisai__c.SellDifferentiation__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>AnkenMeisai__c.UNPAID_BALANCE_OF_SELLING_USD__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>CloFMSBillBank</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/FMSBillPayReq__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+TRX Plan</label>
    <nameField>
        <displayFormat>FBPR-{000000}</displayFormat>
        <label>FMS BILL+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FMSBillPayReq__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipLabel>FMS BILL+TRX PLAN</relationshipLabel>
    <relationshipName>FMSBillTrxPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSBillID__c.field-meta.xml
<CustomField>
    <fullName>FMSBillID__c</fullName>
    <label>FMS BILL ID</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayReqBank__c/PayReqBank__c.object-meta.xml
<CustomObject>
    <label>TRX Plan+Bank</label>
    <nameField>
        <displayFormat>PRBT-{000000}</displayFormat>
        <label>TRX PLAN+BANK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TRX Plan+Bank</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayReqBank__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipName>PayReqBank</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayReqBank__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>PayReqBank</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PayReqBankTriggerHelper.cls
public with sharing class PayReqBankTriggerHelper {
    public static void connectBillToBank(List<PayReqBank__c> payReqBankNews) {
        Set<Id> paymentRequestIds = new Set<Id>();
		Set<Id> bankIds = new Set<Id>();
		Map<String, Set<String>> bankByPaymentRquestMap = new Map<String, Set<String>>();
		for(PayReqBank__c payReqBank : payReqBankNews){
			bankIds.add(payReqBank.BankID__c);
			paymentRequestIds.add(payReqBank.PaymentRequestID__c);
			if(bankByPaymentRquestMap.containsKey(payReqBank.PaymentRequestID__c)){
				bankByPaymentRquestMap.get(payReqBank.PaymentRequestID__c).add(payReqBank.BankID__c);
			}else{
				bankByPaymentRquestMap.put(payReqBank.PaymentRequestID__c, new Set<String>{payReqBank.BankID__c});
			}
		}

		// get all bill combined to VAT
		List<FMSBillPayReq__c> listBillPaymentRequest = [SELECT Id, PaymentRequestID__c, FMSBillID__c
													FROM FMSBillPayReq__c 
		
													WHERE PaymentRequestID__c IN: paymentRequestIds ];
		Set<Id> billIds = new Set<Id>();
		for(FMSBillPayReq__c billPayReq: listBillPaymentRequest){
			billIds.add(billPayReq.FMSBillID__c);
		}
		// get bill combined to planed
		List<CloFMSBillBank__c> listBillBank = [SELECT Id, BankTransactionID__c, CloFMSBillID__c
													FROM CloFMSBillBank__c 
		
													WHERE BankTransactionID__c IN: bankIds
													AND  CloFMSBillID__c IN: billIds];
		Map<String, Set<String>> mapBillsByBank = new Map<String, Set<String>>();
		for(CloFMSBillBank__c billBank : listBillBank){
			if(mapBillsByBank.containsKey(billBank.BankTransactionID__c)){
				mapBillsByBank.get(billBank.BankTransactionID__c).add(billBank.CloFMSBillID__c);
			}else{
				mapBillsByBank.put(billBank.BankTransactionID__c, new Set<String>{billBank.CloFMSBillID__c});
			}
		}

		Set<String> billPayReqs = new Set<String>();

		List<CloFMSBillBank__c> billBankNews = new List<CloFMSBillBank__c>();

		for(FMSBillPayReq__c billPayReq: listBillPaymentRequest){
			String key = (String)billPayReq.FMSBillID__c + (String)billPayReq.PaymentRequestID__c;
			if(!billPayReqs.contains(key)){
				billPayReqs.add(key);
				for(String bankId : bankByPaymentRquestMap.get(billPayReq.PaymentRequestID__c)){
					if(!mapBillsByBank.containsKey(bankId) 
						|| (mapBillsByBank.containsKey(bankId) && !mapBillsByBank.get(bankId).contains(billPayReq.FMSBillID__c)) ){

						CloFMSBillBank__c billBank = new CloFMSBillBank__c(
							BankTransactionID__c = bankId,
							CloFMSBillID__c = billPayReq.FMSBillID__c);
						billBankNews.add(billBank);
						if(mapBillsByBank.containsKey(bankId)){
							mapBillsByBank.get(bankId).add(billPayReq.FMSBillID__c);
						}else{
							mapBillsByBank.put(bankId, new Set<String>{billPayReq.FMSBillID__c});
						}
					}
					
				}
            }
        }
        try{
        	FlsService.doInsert(billBankNews);
		}catch(Exception ex){
			payReqBankNews[0].addError(ex.getMessage());
		}
    }
}