force-app/main/default/objects/CloFMSBillBank__c/CloFMSBillBank__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+Bank</label>
    <nameField>
        <displayFormat>BB-{000000}</displayFormat>
        <label>FMS BILL+BANK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+Bank</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CloFMSBillBank__c/fields/BankTransactionID__c.field-meta.xml
<CustomField>
    <fullName>BankTransactionID__c</fullName>
    <label>BANK TRANSACTION ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipName>CloFMSBillBank</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CloFMSBillBank__c/fields/CloFMSBillID__c.field-meta.xml
<CustomField>
    <fullName>CloFMSBillID__c</fullName>
    <label>CloFMS BILL ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>AnkenMeisai__c.BuyDifferentiation__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>AnkenMeisai__c.UNPAID_BALANCE_OF_BUYING_USD__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>AnkenMeisai__c.SellDifferentiation__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>AnkenMeisai__c.UNPAID_BALANCE_OF_SELLING_USD__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>CloFMSBillBank</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/INVOICING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS BILL+VAT</label>
    <nameField>
        <displayFormat>IV-{0000000}</displayFormat>
        <label>FMS BILL+VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipLabel>FMS BILL+VAT</relationshipLabel>
    <relationshipName>FMSBillVATBank</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/fields/INVOICING__c.field-meta.xml
<CustomField>
    <fullName>INVOICING__c</fullName>
    <inlineHelpText>Filter Type:Optional.
-Pricing:Active equals True</inlineHelpText>
    <label>INVOICING</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>AnkenMeisai__c.Tariff__r.ProductFlag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Filter Type:Optional.
-PRICING:ACTIVE equals True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False. 
VAT Invoice is approved and locked. Contact System Administrator to unlock VAT Invoice.</errorMessage>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VAT_INVOICE__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipName>VATInvBank</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VATBank__c/VATBank__c.object-meta.xml
<CustomObject>
    <label>VAT+Bank</label>
    <nameField>
        <displayFormat>VTB-{000000}</displayFormat>
        <label>VAT+BANK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VAT+Bank</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VATBank__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipLabel>VAT+BANK</relationshipLabel>
    <relationshipName>VATBank</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VATBank__c/fields/VATInvoiceID__c.field-meta.xml
<CustomField>
    <fullName>VATInvoiceID__c</fullName>
    <label>VAT INVOICE ID</label>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipLabel>VAT+BANK</relationshipLabel>
    <relationshipName>VATBank</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VATBankTriggerHelper.cls
public with sharing class VATBankTriggerHelper {
    public static void connectBillToBank(List<VATBank__c> newVATBanks) {
        Set<Id> vatIds = new Set<Id>();
		Set<Id> bankIds = new Set<Id>();
		Map<String, Set<String>> bankByVATMap = new Map<String, Set<String>>();
		for(VATBank__c vatBank : newVATBanks){
			bankIds.add(vatBank.BankID__c);
			vatIds.add(vatBank.VATInvoiceID__c);
			if(bankByVATMap.containsKey(vatBank.VATInvoiceID__c)){ 
				bankByVATMap.get(vatBank.VATInvoiceID__c).add(vatBank.BankID__c);
			}else{
				bankByVATMap.put(vatBank.VATInvoiceID__c, new Set<String>{vatBank.BankID__c});
			}
		}

		// get all bill combined to VAT
		List<INVOICING_VAT__c> listBillVAT = [SELECT Id, VAT_INVOICE__c, INVOICING__c
													FROM INVOICING_VAT__c 
		
													WHERE VAT_INVOICE__c IN: vatIds ];
		Set<Id> billIds = new Set<Id>();
		for(INVOICING_VAT__c billVAT: listBillVAT){
			billIds.add(billVAT.INVOICING__c);
		}
		// get bill combined to planed
		List<CloFMSBillBank__c> listBillBank = [SELECT Id, BankTransactionID__c, CloFMSBillID__c
													FROM CloFMSBillBank__c 
		
													WHERE BankTransactionID__c IN: bankIds
													AND  CloFMSBillID__c IN: billIds];
		Map<String, Set<String>> mapBillsByBank = new Map<String, Set<String>>();
		for(CloFMSBillBank__c billBank : listBillBank){
			if(mapBillsByBank.containsKey(billBank.BankTransactionID__c)){
				mapBillsByBank.get(billBank.BankTransactionID__c).add(billBank.CloFMSBillID__c);
			}else{
				mapBillsByBank.put(billBank.BankTransactionID__c, new Set<String>{billBank.CloFMSBillID__c});
			}
		}

		Set<String> billVATs = new Set<String>();

		List<CloFMSBillBank__c> billBankNews = new List<CloFMSBillBank__c>();
		for(INVOICING_VAT__c billVAT: listBillVAT){
			String key = (String)billVAT.INVOICING__c + (String)billVAT.VAT_INVOICE__c;
			if(!billVATs.contains(key)){
				billVATs.add(key);
				for(String bankId : bankByVATMap.get(billVAT.VAT_INVOICE__c)){
					if(!mapBillsByBank.containsKey(bankId) 
						|| (mapBillsByBank.containsKey(bankId) && !mapBillsByBank.get(bankId).contains(billVAT.INVOICING__c)) ){

						CloFMSBillBank__c billBank = new CloFMSBillBank__c(
							BankTransactionID__c = bankId,
							CloFMSBillID__c = billVAT.INVOICING__c);
						billBankNews.add(billBank);
						if(mapBillsByBank.containsKey(bankId)){
							mapBillsByBank.get(bankId).add(billVAT.INVOICING__c);
						}else{
							mapBillsByBank.put(bankId, new Set<String>{billVAT.INVOICING__c});
						}
					}
					
				}
            }
        }
        try{
			FlsService.doInsert(billBankNews);
		}catch(Exception ex){
			newVATBanks[0].addError(ex.getMessage());
		}
				
    }
}