force-app/main/default/objects/OrganizationPerformance__c/OrganizationPerformance__c.object-meta.xml
<CustomObject>
    <label>ORG Performance</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>ORGANIZATION PERFORMANCE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ORG Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrganizationPerformance__c/fields/AccumulatedAnnualPerformance__c.field-meta.xml
<CustomField>
    <fullName>AccumulatedAnnualPerformance__c</fullName>
    <label>ACCUMULATED ANNUAL PERFORMANCE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrganizationPerformance__c/fields/ParentOrganizationalPerformanceID__c.field-meta.xml
<CustomField>
    <fullName>ParentOrganizationalPerformanceID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PARENT ORGANIZATIONAL PERFORMANCE ID</label>
    <referenceTo>OrganizationPerformance__c</referenceTo>
    <relationshipLabel>ORGANIZATION PERFORMANCE</relationshipLabel>
    <relationshipName>ParentOrganizationalPerformance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrganizationPerformance__c/fields/SumPerformanceFromChildOrg__c.field-meta.xml
<CustomField>
    <fullName>SumPerformanceFromChildOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SumPerformanceFromChildOrg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrganizationPerformanceTriggerHandler.cls
public with sharing class OrganizationPerformanceTriggerHandler {
	public static void onBeforeDelete(List<OrganizationPerformance__c> listOrganizationPerformance){
		Set<Id> parentOrgPerformanceIds = new Set<Id>();

		for(OrganizationPerformance__c orgPerformance : listOrganizationPerformance){
			parentOrgPerformanceIds.add(orgPerformance.ParentOrganizationalPerformanceID__c);

		}

		Map<Id, OrganizationPerformance__c> parentOrgPerformanceMap = new Map<Id, OrganizationPerformance__c>([SELECT 
																		Id, 
																		AccumulatedAnnualPerformance__c, 
																		SumPerformanceFromChildOrg__c 
																		FROM OrganizationPerformance__c
																		WHERE Id IN: parentOrgPerformanceIds]);
		for(OrganizationPerformance__c orgPerformance : listOrganizationPerformance){
			if(!parentOrgPerformanceMap.containsKey(orgPerformance.ParentOrganizationalPerformanceID__c)){
				continue;
			}

			if(parentOrgPerformanceMap.get(orgPerformance.ParentOrganizationalPerformanceID__c).SumPerformanceFromChildOrg__c > 0){

				parentOrgPerformanceMap.get(orgPerformance.ParentOrganizationalPerformanceID__c).SumPerformanceFromChildOrg__c = parentOrgPerformanceMap.get(orgPerformance.ParentOrganizationalPerformanceID__c).SumPerformanceFromChildOrg__c - orgPerformance.AccumulatedAnnualPerformance__c;
			}

		}

        FlsService.doUpdate(parentOrgPerformanceMap.values());
	}
}