force-app/main/default/objects/OrganizationPerformance__c/OrganizationPerformance__c.object-meta.xml
<CustomObject>
    <label>ORG Performance</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>ORGANIZATION PERFORMANCE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ORG Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrganizationPerformance__c/fields/AccumulatedAnnualPerformance__c.field-meta.xml
<CustomField>
    <fullName>AccumulatedAnnualPerformance__c</fullName>
    <label>ACCUMULATED ANNUAL PERFORMANCE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrganizationPerformance__c/fields/OrganizationPerformanceName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationPerformanceName__c</fullName>
    <label>ORGANIZATION PERFORMANCE NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrganizationPerformance__c/fields/ParentOrganizationalPerformanceID__c.field-meta.xml
<CustomField>
    <fullName>ParentOrganizationalPerformanceID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PARENT ORGANIZATIONAL PERFORMANCE ID</label>
    <referenceTo>OrganizationPerformance__c</referenceTo>
    <relationshipLabel>ORGANIZATION PERFORMANCE</relationshipLabel>
    <relationshipName>ParentOrganizationalPerformance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrganizationPerformance__c/fields/SumPerformanceFromChildOrg__c.field-meta.xml
<CustomField>
    <fullName>SumPerformanceFromChildOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SumPerformanceFromChildOrg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrganizationPerformanceTriggerHdlerTest.cls
@isTest
private class OrganizationPerformanceTriggerHdlerTest {

	private static OrganizationPerformance__c orgPerformanceParent;
	private static OrganizationPerformance__c orgPerformanceChild;

	static{
		orgPerformanceParent = new OrganizationPerformance__c(
			OrganizationPerformanceName__c = 'Org test',
			AccumulatedAnnualPerformance__c = 10,
			SumPerformanceFromChildOrg__c = 10);
        FlsService.doInsert(orgPerformanceParent);

		orgPerformanceChild = new OrganizationPerformance__c(
			OrganizationPerformanceName__c = 'Org test',
			AccumulatedAnnualPerformance__c = 10,
			SumPerformanceFromChildOrg__c = 10,
			ParentOrganizationalPerformanceID__c = orgPerformanceParent.Id);
        FlsService.doInsert(orgPerformanceChild);
	}
	
	@isTest static void test_method_onBeforeDelete() {
		// Implement test code
		Test.startTest();
			FlsService.doDelete(orgPerformanceChild);
			Integer x =1;
			System.assert(x != null);
		Test.stopTest();
	}
	
}