force-app/main/default/objects/Carrier_Code__c/Carrier_Code__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CarrierCodeOnlineHelp</customHelpPage>
    <description>Carrier Code</description>
    <label>CARRIER/AIRLINER CODE</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Code__c/fields/Carrier_Code__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Code__c</fullName>
    <inlineHelpText>This code of Liner/Airliner includes both number and letter (2-4).</inlineHelpText>
    <label>Carrier Code</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carrier_Code__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CarrierCodeTrigerTest.cls
@isTest
private class CarrierCodeTrigerTest {
    @testsetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object> {'Name' => 'NAME', 
            										'Carrier_Code__c' => 'AB01', 'Company_Name__c' => 'ABC Corp.'};
		TestDataFactory.createSObject(new Carrier_Code__c(), true, additionalFields);
        System.assert(true);
    }
    
    testmethod static void shouldUpdateNameOnInsert() {
        Map<String, Object> additionalFields = new Map<String, Object> {'Name' => 'NAME', 
            										'Carrier_Code__c' => 'CD01', 'Company_Name__c' => 'ABC Corp.'};
		Carrier_Code__c cc = (Carrier_Code__c) TestDataFactory.createSObject(new Carrier_Code__c(), true, additionalFields);
        
        Test.startTest();
        cc = [select Id, Carrier_Code__c, Name from Carrier_Code__c where Id = :cc.Id];
        
        System.assertEquals('CD01', cc.Carrier_Code__c);
        System.assertEquals('CD01', cc.Name);
        Test.stopTest();
    }
    
    testmethod static void shouldUpdateNameOnUpdate() {
		Carrier_Code__c cc = [select Id, Name, Carrier_Code__c from Carrier_Code__c limit 1];
        System.assertEquals('AB01', cc.Carrier_Code__c);
        System.assertEquals('AB01', cc.Name);
        
        Test.startTest();
        cc.Carrier_Code__c = 'XY01';
        FlsService.doUpdate(cc);
        Test.stopTest();
        
        cc = [select Id, Name, Carrier_Code__c from Carrier_Code__c where Id = :cc.Id];
        System.assertEquals('XY01', cc.Carrier_Code__c);
        System.assertEquals('XY01', cc.Name);
    }
}