force-app/main/default/objects/CONTAINER__c/CONTAINER__c.object-meta.xml
<CustomObject>
    <label>CNTR In W/D/Y</label>
    <nameField>
        <displayFormat>CTNR-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR In W/D/Y</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Info__c/Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Info__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <label>CONTAINER TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexitank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/Container_NO__c.field-meta.xml
<CustomField>
    <fullName>Container_NO__c</fullName>
    <inlineHelpText>Please enter 11digits(4digit container ownership code+7digit container code)</inlineHelpText>
    <label>CONTAINER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/Empty_Full_Container_Identification__c.field-meta.xml
<CustomField>
    <fullName>Empty_Full_Container_Identification__c</fullName>
    <description>空/実入りコンテナ表示（UN/EDIFACT8169）	

「4」は入力不可	
5	Full 


Empty/Full Container Identification	

4 is not allowed.	
5	Full</description>
    <inlineHelpText>Empty/Full Container Identification. 4 is not allowed. 5 is Full container.</inlineHelpText>
    <label>Empty/Full Container Identification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
                <default>true</default>
                <label>Full</label>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Container_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>F/TMS CNTR (P.O.D)</relationshipLabel>
    <relationshipName>FTMSCNTRPOD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/POL__c.field-meta.xml
<CustomField>
    <fullName>POL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>F/TMS CNTR (P.O.L)</relationshipLabel>
    <relationshipName>FTMSCNTRPOL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Clearance__c/Custom_Clearance__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CustomClearanceOnlineHelp</customHelpPage>
    <description>Custom Clearance</description>
    <label>通関</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Custom Clearance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Clearance__c/fields/Customs_Release_Day__c.field-meta.xml
<CustomField>
    <fullName>Customs_Release_Day__c</fullName>
    <label>CUSTOMS CLEARANCE PERMIT DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Clearance__c/fields/DeclarationNo__c.field-meta.xml
<CustomField>
    <fullName>DeclarationNo__c</fullName>
    <label>APPLICATION DECLARATION NO</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Clearance__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L-SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Custom_Clearance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <inlineHelpText>When Container Type and Container Qnty is input, Container Information object is automatically created. Input Container/Seal No in the object accordingly.</inlineHelpText>
    <label>CONTAINER TYPE-1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DevanningDate__c.field-meta.xml
<CustomField>
    <fullName>DevanningDate__c</fullName>
    <label>DEVAN DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/MASTER_BOOKINGNO__c.field-meta.xml
<CustomField>
    <fullName>MASTER_BOOKINGNO__c</fullName>
    <inlineHelpText>Input Booking Number from Carrier for FCL and Consolidator for LCL.</inlineHelpText>
    <label>MASTER BOOKING NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/POL__c.field-meta.xml
<CustomField>
    <fullName>POL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PrintDate__c.field-meta.xml
<CustomField>
    <fullName>PrintDate__c</fullName>
    <formula>if(LEN( text(PrinteDate_ED__c) ) &gt; 0 , PrinteDate_ED__c , TODAY() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>if Fixed Issue Date(If Fixed) is not set, automatically will be set as today.</inlineHelpText>
    <label>DATE INVOICE ISSUED</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/QuotationVer__c.field-meta.xml
<CustomField>
    <fullName>QuotationVer__c</fullName>
    <description>見積書・請求書の参照番号に付与される枝番。
両方とも共通の枝番としてカウントされます。</description>
    <label>VERSION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/WkInitial__c.field-meta.xml
<CustomField>
    <fullName>WkInitial__c</fullName>
    <formula>CASE(  RecordType.DeveloperName  
, &apos;RecordType1&apos;, &apos;IS&apos;
, &apos;oceanimport_lock&apos;, &apos;IS&apos;

, &apos;RecordType&apos;, &apos;OS&apos;
, &apos;oceanexport_lock&apos;, &apos;OS&apos;

, &apos;InAir&apos;, &apos;IA&apos;
, &apos;airimportlock&apos;, &apos;IA&apos;

, &apos;OutAir&apos;, &apos;OA&apos;
, &apos;OutAir_lock&apos;, &apos;OA&apos;

, &apos;Domestic_Transportation&apos;, &apos;DT&apos;
, &apos;Domestic_Transportation_Lock&apos;, &apos;DT&apos;

, &apos;LogisticsService&apos;, &apos;LG&apos;
, &apos;LogisticsServiceLock&apos;, &apos;LG&apos;

, &apos;CrossBoarder&apos;, &apos;CB&apos;
, &apos;CrossBoarderLock&apos;, &apos;CB&apos;

, &apos;Express&apos;, &apos;ES&apos;
, &apos;ExpressLock&apos;, &apos;ES&apos;

, &apos;QUOTATION&apos;, &apos;QT&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>wkHEAD CHARACTER</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <customHelpPage>OnlineHelpPorts</customHelpPage>
    <description>Port</description>
    <label>ポートコード</label>
    <nameField>
        <label>Port name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContainerListingController.cls
/**
 * Created by khanhpham on 10/25/17.
 */

public with sharing class ContainerListingController {
    private static final Integer PAGE_SIZE = 20;
    private String shipmentId;
    public List<ContainerListingPageWrapper> pages {get; private set;}
    public Date printDate {get; private set;}
    public String invoiceNo {get; private set;}
    public Integer numberOfPages {get; private set;}
    public Boolean fullList {get; private set;}

    public ContainerListingController() {
        readParameters();
    }

    public void buildContainerLists() {
        buildReportData();

        numberOfPages = 0;

        if (pages != null && !pages.isEmpty()) {
            numberOfPages = pages.size();
        }
    }

    private void readParameters() {
        shipmentId = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get(Constants.REQUEST_ID));

        try {
            fullList = Boolean.valueOf(ApexPages.currentPage().getParameters().get(Constants.REQUEST_CHECK_FLAG));
        } catch (Exception e) {
            fullList = true;
        }
    }

    private void buildReportData() {
        CustomObject1__c shipment = [
                SELECT MASTER_BOOKINGNO__c, POD__r.Name, POL__r.Name, ETD__c, ETA__c, PrintDate__c, WkInitial__c, QuotationVer__c, Name, DevanningDate__c,
                    (SELECT Id, DeclarationNo__c, Customs_Release_Day__c FROM Custom_Clearance__r),
                    (SELECT Id, Name, Container__c, Container_NO__c, Empty_Full_Container_Identification__c FROM Container_Info__r)
                FROM CustomObject1__c
                WHERE Id = :shipmentId
        ];

        if (shipment != null) {
            printDate = shipment.PrintDate__c;
            invoiceNo = 'S' + shipment.WkInitial__c + shipment.Name + '-' + shipment.QuotationVer__c;

            List<Container_Info__c> containerInfos = shipment.Container_Info__r;

            if (containerInfos != null && !containerInfos.isEmpty()) {
                List<Custom_Clearance__c> customClearances = shipment.Custom_Clearance__r;
                Custom_Clearance__c customClearance = null;

                if (customClearances != null && !customClearances.isEmpty()) {
                    customClearance = customClearances.get(0);
                }

                Integer lineCount = 0;
                Integer index = 0;
                Integer pageNo = 0;
                pages = new List<ContainerListingPageWrapper>();
                ContainerListingPageWrapper page = null;

                for (Container_Info__c containerInfo : containerInfos) {
                    lineCount++;
                    if (lineCount == 1) {
                        pageNo++;
                        page = new ContainerListingPageWrapper();
                        page.pageNo = pageNo;
                        pages.add(page);
                    } else if (lineCount == PAGE_SIZE) {
                        lineCount = 0;
                    }

                    ContainerListingLineWrapper line = new ContainerListingLineWrapper();
                    line.index = ++index;
                    line.bookingNumber = shipment.MASTER_BOOKINGNO__c;
                    line.portOfDischarge = shipment.POD__r.Name;
                    line.portOfLoading = shipment.POL__r.Name;
                    line.etd = shipment.ETD__c;
                    line.eta = shipment.ETA__c;
                    line.stuffingUnstuffingDate = shipment.DevanningDate__c;

                    if (customClearance != null) {
                        line.appDeclarationNo = customClearance.DeclarationNo__c;
                        line.ccPermitDate = customClearance.Customs_Release_Day__c;
                    }

                    line.containerId = containerInfo.Name;
                    line.containerType = containerInfo.Container__c;
                    line.containerNumber = containerInfo.Container_NO__c;
                    line.fullOrEmpty = containerInfo.Empty_Full_Container_Identification__c;

                    page.addLine(line);
                }
            }
        }
    }

    class ContainerListingPageWrapper {
        public Integer pageNo {get; set;}
        public List<ContainerListingLineWrapper> lines { get; private set; }

        public ContainerListingPageWrapper() {
            lines = new List<ContainerListingLineWrapper>();
        }

        public void addLine(ContainerListingLineWrapper line) {
            lines.add(line);
        }
    }

    class ContainerListingLineWrapper {
        public Integer index { get; set; }
        public String bookingNumber { get; set; }
        public String portOfDischarge { get; set; }
        public String portOfLoading { get; set; }
        public Date etd { get; set; }
        public Date eta { get; set; }
        public Date stuffingUnstuffingDate {get; set;}
        public String appDeclarationNo { get; set; }
        public Date ccPermitDate { get; set; }
        public String containerId { get; set; }
        public String containerType { get; set; }
        public String containerNumber { get; set; }
        public String fullOrEmpty { get; set; }
    }
}