force-app/main/default/objects/ConnectWOSWorker__c/ConnectWOSWorker__c.object-meta.xml
<CustomObject>
    <label>W/O/S+Worker</label>
    <nameField>
        <displayFormat>WW-{000000}</displayFormat>
        <label>CONNECT WOS &amp; WORKER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S+Worker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectWOSWorker__c/fields/Worker__c.field-meta.xml
<CustomField>
    <fullName>Worker__c</fullName>
    <label>WORKER ID</label>
    <referenceTo>WORKER__c</referenceTo>
    <relationshipLabel>CONNECT WOS &amp; WORKER</relationshipLabel>
    <relationshipName>WosWorker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectWOSWorker__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>CONNECT WOS &amp; WORKER</relationshipLabel>
    <relationshipName>WosWorker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WORKER__c/WORKER__c.object-meta.xml
<CustomObject>
    <label>ドライバー・作業員</label>
    <nameField>
        <displayFormat>WK-{000000}</displayFormat>
        <label>WORKER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WORKER__c/fields/FULL_NAME__c.field-meta.xml
<CustomField>
    <fullName>FULL_NAME__c</fullName>
    <label>FULL NAME</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WORKER__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EmploymentStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>WorkOrderDestinationWarehouseID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-DESTINATION</relationshipLabel>
    <relationshipName>WorkOrderServiceDestination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/ServiceStage__c.field-meta.xml
<CustomField>
    <fullName>ServiceStage__c</fullName>
    <description>Unique key within a process, used to identify the service in a process</description>
    <inlineHelpText>Unique key within a process, used to identify the service in a process</inlineHelpText>
    <label>Service Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WorkStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASRequirement__c.field-meta.xml
<CustomField>
    <fullName>VASRequirement__c</fullName>
    <label>VAS REQUIREMENT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASServiceType__c.field-meta.xml
<CustomField>
    <fullName>VASServiceType__c</fullName>
    <label>VAS SERVICE TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueAddedServiceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/EmploymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>On Training</fullName>
    </customValue>
    <customValue>
        <fullName>On Employment</fullName>
    </customValue>
    <customValue>
        <fullName>On Vacation</fullName>
    </customValue>
    <customValue>
        <fullName>Retired</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Employment Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ValueAddedServiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Quality Check</fullName>
        <default>true</default>
        <label>Quality Check</label>
    </customValue>
    <customValue>
        <fullName>Quality Assurance</fullName>
    </customValue>
    <customValue>
        <fullName>Damage Root-cause Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>Labelling</fullName>
    </customValue>
    <customValue>
        <fullName>Sorting</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Split Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Packing/Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Measuring</fullName>
    </customValue>
    <customValue>
        <fullName>Marking</fullName>
    </customValue>
    <customValue>
        <fullName>Repairing</fullName>
    </customValue>
    <customValue>
        <fullName>Consol</fullName>
    </customValue>
    <customValue>
        <fullName>De-Consol</fullName>
    </customValue>
    <customValue>
        <fullName>Fumigation</fullName>
    </customValue>
    <customValue>
        <fullName>Kitting</fullName>
    </customValue>
    <customValue>
        <fullName>Assembling</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Physical Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Cyclic Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Elimination of Losts From Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Updates</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Reconditioning</fullName>
        <isActive>false</isActive>
        <label>Reconditioning</label>
    </customValue>
    <customValue>
        <fullName>Accumulating</fullName>
        <isActive>false</isActive>
        <label>Accumulating</label>
    </customValue>
    <masterLabel>VALUE ADDED SERVICE TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WorkStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Resource Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Accept Cargo Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>On Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Data Transfer To Next Process</fullName>
        <isActive>false</isActive>
        <label>Data Transfer To Next Process</label>
    </customValue>
    <masterLabel>WORK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WMS_WO_CreateService.cls
public with sharing class WMS_WO_CreateService {

	@AuraEnabled
	public static Object getInfo(Id recordId) {
		List<Map<String, String>> picklistVas = new List<Map<String, String>>();

		for (PicklistEntry item : clofor_com_cfs__WorkOrderService__c.clofor_com_cfs__VASServiceType__c.getDescribe().getPicklistValues()) {
			picklistVas.add(new Map<String, String>{ 'label' => item.Label, 'value' => item.Value });
		}

        // Thao start
        List<Map<String, String>> picklistWorker = new List<Map<String, String>>();
        for(ConnectWOSWorker__c worker : [ SELECT Id, Worker__r.Name, Worker__r.EMPLOYEE_ID__c, Worker__r.FULL_NAME__c, Name FROM ConnectWOSWorker__c ]){
            picklistWorker.add(new Map<String, String>{'label' => worker.Worker__r.Name, 'value' => worker.Id});
        }
        // Thao end

		return new Map<String, Object> {
			'workOrder' => (WorkOrder__c)[
				SELECT
					RecordType.Name, RecordType.DeveloperName, WarehouseId__c, DestinationWarehouse__c, 
					(
						SELECT Id, Warehouse__c, DestinationWarehouse__c, VASServiceType__c, VASRequirement__c, Status__c, ServiceStage__c, RecordTypeId FROM WorkOrderService__r
					)
				FROM WorkOrder__c
				WHERE Id = :recordId
			],
			'serviceRecordTypes' => [
				SELECT Id, Name, DeveloperName
				FROM RecordType
				WHERE SobjectType = 'clofor_com_cfs__WorkOrderService__c'
			],
			'picklistVas' => picklistVas,
            'picklistWorker' => picklistWorker
		};
	}

	@AuraEnabled
	public static void deleteServices(List<Id> listServiceIds) {
		try {
			FlsService.doDelete([SELECT Id FROM WorkOrderService__c WHERE Id IN :listServiceIds]);
		}
		catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage() + ex.getStackTraceString());
		}
	}

	@AuraEnabled
	public static void saveServices(Id workOrderId, List<WorkOrderService__c> listServices) {
		try {
			WorkOrder__c wo = [
				SELECT Id, WarehouseId__c, DestinationWarehouse__c
				FROM WorkOrder__c
				WHERE Id = :workOrderId
				LIMIT 1
			];
			List<WorkOrderService__c> listToInsert = new List<WorkOrderService__c>();
			List<WorkOrderService__c> listToUpdate = new List<WorkOrderService__c>();

			for (WorkOrderService__c item : listServices) {
				item.WorkOrder__c = wo.id;
				if (item.Id != null) {
					listToUpdate.add(item);
				}
				else {
					listToInsert.add(item);
				}
			}
			
		    FlsService.doInsert(listToInsert);
		    FlsService.doUpdate(listToUpdate);
		}
		catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage() + ex.getStackTraceString());
		}
	}
}