force-app/main/default/objects/LOCATOR__c/LOCATOR__c.object-meta.xml
<CustomObject>
    <label>Locator</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>LOCATOR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/fields/ActualOccupiedCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>ActualOccupiedCapacityCBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (CBM) INCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/ActualOccupiedCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>ActualOccupiedCapacityKG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (KG) INCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CurrentOccupiedCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>CurrentOccupiedCapacityCBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (CBM) EXCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CurrentOccupiedCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>CurrentOccupiedCapacityKG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (KG) EXCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <inlineHelpText>= cubic inch/61023.744 or cubic feet/35.315 or cubic yard/1.308</inlineHelpText>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/NETWeight__c.field-meta.xml
<CustomField>
    <fullName>NETWeight__c</fullName>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RollupStockIn__c.field-meta.xml
<CustomField>
    <fullName>RollupStockIn__c</fullName>
    <label>ROLLUP STOCK-IN</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RollupStockOut__c.field-meta.xml
<CustomField>
    <fullName>RollupStockOut__c</fullName>
    <label>ROLLUP NUMBER OF STOCK OUTBOUND</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>STOCK LIST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>STOCK (CUSTOMER)</relationshipLabel>
    <relationshipName>STOCK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MEASUREMENT (CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/NETWeight__c.field-meta.xml
<CustomField>
    <fullName>NETWeight__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK_LIST</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/PurchasingOrderID__c.field-meta.xml
<CustomField>
    <fullName>PurchasingOrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GOODS PURCHASING ORDER ID</label>
    <referenceTo>GoodsPurchasingOrder__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/STOCK__c.field-meta.xml
<CustomField>
    <fullName>STOCK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stock</relationshipLabel>
    <relationshipName>Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/StockLocator__c.field-meta.xml
<CustomField>
    <fullName>StockLocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>STOCK LOCATOR</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>LOCATOR__c.LocationAreaType__c</field>
            <operation>equals</operation>
            <value>Storage Area, Storage Area</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK_LIST</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/StockStatus__c.field-meta.xml
<CustomField>
    <fullName>StockStatus__c</fullName>
    <label>STOCK STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StockStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/WOSLineID__c.field-meta.xml
<CustomField>
    <fullName>WOSLineID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>W/O/S LINE ID</label>
    <referenceTo>WOSLineItem__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>StockWOSLineID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/recordTypes/StockIn.recordType-meta.xml
<RecordType>
    <fullName>StockIn</fullName>
    <active>true</active>
    <description>Record Type when Goods increase</description>
    <label>Stock-In</label>
</RecordType>

force-app/main/default/objects/Stock__c/recordTypes/StockOut.recordType-meta.xml
<RecordType>
    <fullName>StockOut</fullName>
    <active>true</active>
    <description>Record Type when Number of Goods decrease</description>
    <label>Stock-Out</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WorkOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/DataPull__c.field-meta.xml
<CustomField>
    <fullName>DataPull__c</fullName>
    <label>DATA PULL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DataPull</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/DataUpdateMethod__c.field-meta.xml
<CustomField>
    <fullName>DataUpdateMethod__c</fullName>
    <inlineHelpText>If want to automatic data updates from other process 
-Select Automatic 
If want to input data manually 
-Select Manual</inlineHelpText>
    <label>DATA UPDATE METHOD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DataUpdateMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>WorkOrderService__r.WorkOrder__r.Customer__c</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipName>WOSLineItemID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Cargo__r.Product__c ,  Cargo__r.Product__r.Name  , &apos;_top&apos;)</formula>
    <label>PRODUCT ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WOSLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DataPull.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data Pull From PREVIOUS WORK ORDER SERVICE</fullName>
    </customValue>
    <customValue>
        <fullName>Data Pull From Work Order</fullName>
        <label>Data Pull From WORK ORDER</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From SHIPMENT ORDER</fullName>
        <label>Data Pull From CloFMS SHIPMENT ORDER</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Stock</fullName>
        <label>Data Pull From STOCK</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Purchasing Order</fullName>
        <label>Data Pull From GOODS PURCHASING ORDER</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Sales Order</fullName>
        <label>Data Pull From GOODS SALES ORDER</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Contract</fullName>
        <label>Data Pull From CONTRACT</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From WORK ORDER SERVICE</fullName>
    </customValue>
    <customValue>
        <fullName>Data Pull From ROLLUP INFORMATION</fullName>
    </customValue>
    <customValue>
        <fullName>Data Pull From Receiving</fullName>
        <isActive>false</isActive>
        <label>Data Pull From RECEIVING</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Putaway</fullName>
        <isActive>false</isActive>
        <label>Data Pull From PUTAWAY</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Picking</fullName>
        <isActive>false</isActive>
        <label>Data Pull From PICKING</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From VAS</fullName>
        <isActive>false</isActive>
        <label>Data Pull From VAS</label>
    </customValue>
    <customValue>
        <fullName>Data Pull From Dispatch</fullName>
        <isActive>false</isActive>
        <label>Data Pull From DISPATCH</label>
    </customValue>
    <masterLabel>CloWMS/CloTRS DATA PULL</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DataUpdateMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Automatic</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <masterLabel>DATA UPDATE METHOD</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/StockStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planning</fullName>
        <label>Plannned</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>STOCK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StockTriggerHelper.cls
public with sharing class StockTriggerHelper {
	/*
	   Method Name: calculateLocatorWhenDeleteStock
	   prarams: list of delete stock
	   Description: re-Calculate Actual and Current Occupied Capacity of Locator
	   Author: Nga Do
	 */
	public static void calculateOccupiedCapacity(List<Stock__c> newStocks, Map<Id, Stock__c> oldStock){
	}
	public static void calculateLocatorWhenDeleteStock(List<clofor_com_cfs__Stock__c > oldStocks){
		RecordType stockInRecId = getRecIdByName('StockIN', 'clofor_com_cfs__Stock__c');
		RecordType stockOutRecId = getRecIdByName('StockOut', 'clofor_com_cfs__Stock__c');
		Set<Id> idLocators = new Set<Id>();
		for(Stock__c stock: oldStocks) {
			idLocators.add(stock.StockLocator__c);
		}
		Map<Id, LOCATOR__c> mapLocators = new Map<Id, LOCATOR__c>([SELECT
		                                                           Id,
		                                                           ActualOccupiedCapacityCBM__c,
		                                                           ActualOccupiedCapacityKG__c,
		                                                           CurrentOccupiedCapacityCBM__c,
		                                                           CurrentOccupiedCapacityKG__c
		                                                           FROM LOCATOR__c
		                                                           WHERE Id IN: idLocators]);
		for(Stock__c stock: oldStocks) {
			if(!mapLocators.containsKey(stock.StockLocator__c)) {
				continue;
			}

			if(stockInRecId != null &&
			   stockInRecId.Id == stock.RecordTypeId &&
			   stock.StockStatus__c != 'Cancelled') {
				if(stock.Measurement__c != null) {
					if(mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c == null) {
						mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c = 0;
					}
					mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c -= stock.Measurement__c;
				}
				if(stock.GrossWeight__c != null) {
					if(mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c == null) {
						mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c = 0;
					}
					mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c -= stock.GrossWeight__c;
				}
				if(stock.StockStatus__c == 'Completed') {
					if(stock.Measurement__c != null) {
						if(mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c == null) {
							mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c = 0;
						}
						mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c -= stock.Measurement__c;
					}
					if(stock.GrossWeight__c != null) {
						if(mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c == null) {
							mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c = 0;
						}
						mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c -= stock.GrossWeight__c;
					}
				}
			}

			if(stockOutRecId != null &&
			   stockOutRecId.Id == stock.RecordTypeId &&
			   stock.StockStatus__c != 'Cancelled') {
				if(stock.Measurement__c != null) {
					if(mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c == null) {
						mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c = 0;
					}
					mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c += stock.Measurement__c;
				}
				if(stock.GrossWeight__c != null) {
					if(mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c == null) {
						mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c = 0;
					}
					mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c += stock.GrossWeight__c;
				}
				if(stock.StockStatus__c == 'Completed') {
					if(stock.Measurement__c != null) {
						if(mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c == null) {
							mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c = 0;
						}
						mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c += stock.Measurement__c;
					}
					if(stock.GrossWeight__c != null) {
						if(mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c == null) {
							mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c = 0;
						}
						mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c += stock.GrossWeight__c;
					}
				}
			}

			if(mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c < 0) {
				mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityCBM__c = 0;
			}
			if(mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c < 0) {
				mapLocators.get(stock.StockLocator__c).ActualOccupiedCapacityKG__c = 0;
			}
			if(mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c < 0) {
				mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityKG__c = 0;
			}
			if(mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c < 0) {
				mapLocators.get(stock.StockLocator__c).CurrentOccupiedCapacityCBM__c = 0;
			}
		}
		try{
			FlsService.doUpdate(mapLocators.values());
		}catch(Exception ex) {
			oldStocks[0].addError(ex.getMessage());
		}
	}
	private Static RecordType getRecIdByName(String nameRec, String objectName){
		List<RecordType> recRecs = [SELECT Id FROM RecordType WHERE DeveloperName =: nameRec AND SobjectType =: objectName Limit 1];

		if(!recRecs.isEmpty()) {
			return recRecs[0];
		}

		return null;
	}

	public static void rollUpStockInAndOut(List<Stock__c> listNew, Map<Id, Stock__c> mapOld){
        Set<Id> setProductIds = new Set<Id>();
		List<Stock__c> listStock = new List<Stock__c>();
		for (Stock__c item : listNew) {
			if (item.StockStatus__c == 'Completed' && (mapOld == null || mapOld.get(item.Id).StockStatus__c != 'Completed')) {
				listStock.add(item);
				setProductIds.add(item.ProductId__c);
			}
		}
        if (setProductIds.isEmpty()) {
            return;
        }
        Map<Id, Product__c> mapProducts = new Map<Id, Product__c> ([SELECT Id, BillingType__c, RollupStockOut__c, RollupStockIn__c FROM Product__c WHERE Id IN : setProductIds]);

        for(Stock__c item : listStock) {
            Product__c prod = mapProducts.get(item.ProductId__c);
            Decimal amount = prod.BillingType__c == 'Unit' ? item.Quantity__c : item.NetWeight__c;
            amount = amount == null ? 0 : amount;

            if (item.RecordTypeId == Constants.RecordTypeId_Stock_StockIn) {
                prod.RollupStockIn__c = prod.RollupStockIn__c == null ? amount : (prod.RollupStockIn__c + amount);
            }
            else if (item.RecordTypeId == Constants.RecordTypeId_Stock_StockOut) {
                prod.RollupStockOut__c = prod.RollupStockOut__c == null ? amount : (prod.RollupStockOut__c + amount);
            }
        }
		FlsService.doUpdate(mapProducts.values());
	}


	public static void setRecordTypeIdByWosLine(List<Stock__c> listNew) {
		Set<Id> setWosLineId = new Set<Id>();
		List<Stock__c>  listStock= new List<Stock__c>();
		for (Stock__c item : (List<Stock__c>)Trigger.new) {
			if (item.WOSLineID__c != null) {
				listStock.add(item);
				setWosLineId.add(item.WOSLineID__c);
			}
		}

		Map<Id, WosLineItem__c> mapWosLines = new Map<Id, WosLineItem__c>([
			SELECT WorkOrderService__r.RecordTypeId
			FROM WosLineItem__c
			WHERE Id IN: setWosLineId
		]);

		for (Stock__c item : listStock) {
			if (mapWosLines.get(item.WOSLineID__c).WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_Picking) {
				item.RecordTypeId = Constants.RecordTypeId_Stock_StockOut;
			}
			else if (mapWosLines.get(item.WOSLineID__c).WorkOrderService__r.RecordTypeId == Constants.RecordTypeId_Wos_PutAway) {
				item.RecordTypeId = Constants.RecordTypeId_Stock_StockIn;
			}
		}
	}

	public static void autoPopulateFields(List<Stock__c> listNew, Map<Id, Stock__c> mapOld) {
		autoPopulateFields_fromWorkOrder(listNew, mapOld);
		autoPopulateFields_fromProduct(listNew, mapOld);
		autoPopulateFields_fromWos(listNew, mapOld);
		autoPopulateFields_fromLocator(listNew, mapOld);
	}	

	private static void autoPopulateFields_fromWorkOrder(List<Stock__c> listNew, Map<Id, Stock__c> mapOld) {
		Set<Id> setWorkOrder = new Set<Id>();
		List<Stock__c> fromWorkOrder = new List<Stock__c>();
		for (Stock__c item : listNew) {
			if (item.RecordTypeId != Constants.RecordTypeId_Stock_StockIn) {
				continue;
			}
			if ((item.WorkOrderId__c != null && item.DataUpdateMethod__c == 'Automatic' && item.DataPull__c == 'Data Pull From Work Order')
				&& (mapOld == null || 
					mapOld.get(item.Id).WorkOrderId__c != item.WorkOrderId__c ||
					mapOld.get(item.Id).DataUpdateMethod__c != item.DataUpdateMethod__c ||
					mapOld.get(item.Id).DataPull__c != item.DataPull__c
				)
			) {
				setWorkOrder.add(item.WorkOrderId__c);
				fromWorkOrder.add(item);
			}
		}
        if (setWorkOrder.isEmpty()) {
            return;
        }
		Map<Id, WorkOrder__c> mapWorkOrder = new Map<Id, WorkOrder__c>([SELECT Id, Customer__c, ProductId__c, PurchasingOrderId__c, Quantity__c, WarehouseId__c, UnitType__c FROM WorkOrder__c WHERE Id IN :setWorkOrder]);
		for (Stock__c item : fromWorkOrder) {
			WorkOrder__c workOrder = mapWorkOrder.get(item.WorkOrderId__c);
			item.Customer__c = workOrder.Customer__c;
			item.ProductId__c = workOrder.ProductId__c;
			item.PurchasingOrderId__c = workOrder.PurchasingOrderId__c;
			item.Quantity__c = workOrder.Quantity__c;
			item.StockWarehouseID__c = workOrder.WarehouseId__c;
			item.UnitType__c = workOrder.UnitType__c;
		}
	}
	
	private static void autoPopulateFields_fromProduct(List<Stock__c> listNew, Map<Id, Stock__c> mapOld) {
		Set<Id> setProduct = new Set<Id>();
		List<Stock__c> fromProduct  = new List<Stock__c>();
		for (Stock__c item : listNew) {
			if (item.RecordTypeId != Constants.RecordTypeId_Stock_StockIn) {
				continue;
			}
			if (item.ProductId__c != null && (mapOld == null || mapOld.get(item.Id).ProductId__c != item.ProductId__c)) {
				setProduct.add(item.ProductId__c);
				fromProduct.add(item);
			}
		}
        if (setProduct.isEmpty()) {
            return;
        }
		Map<Id, Product__c> mapProduct = new Map<Id, Product__c>([SELECT Id, GoodOwner__c, GrossWeight__c, Measurement__c, NetWeight__c, ProductName__c FROM Product__c WHERE Id IN :setProduct]);
		for (Stock__c item : fromProduct) {
			Product__c product = mapProduct.get(item.ProductId__c);
			item.GoodsOwner__c = product.GoodOwner__c;
			item.GrossWeight__c = product.GrossWeight__c;
			item.Measurement__c = product.Measurement__c;
			item.NetWeight__c = product.NetWeight__c;
			item.ProductName__c = product.ProductName__c;
		}
	}
	
	private static void autoPopulateFields_fromWos(List<Stock__c> listNew, Map<Id, Stock__c> mapOld) {
		Set<Id> setWos = new Set<Id>();
		List<Stock__c> fromWos = new List<Stock__c>();
		for (Stock__c item : listNew) {
			if (item.RecordTypeId != Constants.RecordTypeId_Stock_StockIn) {
				continue;
			}
			if ((item.WorkOrderServiceId__c != null && item.DataUpdateMethod__c == 'Automatic' && item.DataPull__c == 'Data Pull From WORK ORDER SERVICE')
				&& (mapOld == null || 
					mapOld.get(item.Id).WorkOrderServiceId__c != item.WorkOrderServiceId__c ||
					mapOld.get(item.Id).DataUpdateMethod__c != item.DataUpdateMethod__c ||
					mapOld.get(item.Id).DataPull__c != item.DataPull__c
				)
			) {
				setWos.add(item.WorkOrderServiceId__c);
				fromWos.add(item);
			}
		}
        if (setWos.isEmpty()) {
            return;
        }
		Map<Id, WorkOrderService__c> mapWos = new Map<Id, WorkOrderService__c>([SELECT Id, GrossWeightKg__c, Measurement__c, NetWeightKg__c, Locator__c FROM WorkOrderService__c WHERE Id IN :setWos]);
		for (Stock__c item : fromWos) {
			WorkOrderService__c wos = mapWos.get(item.WorkOrderServiceId__c);
			item.GrossWeight__c = wos.GrossWeightKg__c;
			item.Measurement__c = wos.Measurement__c;
			item.NetWeight__c = wos.NetWeightKg__c;
			item.StockLocator__c = wos.Locator__c;
		}
	}
	
	private static void autoPopulateFields_fromLocator(List<Stock__c> listNew, Map<Id, Stock__c> mapOld) {
		Set<Id> setLocator = new Set<Id>();
		List<Stock__c> fromLocator = new List<Stock__c>();
		for (Stock__c item : listNew) {
			if (item.StockLocator__c != null && (mapOld == null || mapOld.get(item.Id).StockLocator__c != item.StockLocator__c)) {
				setLocator.add(item.StockLocator__c);
				fromLocator.add(item);
			}
		}
        if (setLocator.isEmpty()) {
            return;
        }
		Map<Id, Locator__c> mapLocator = new Map<Id, Locator__c>([SELECT Id, WarehouseId__c FROM Locator__c WHERE Id IN :setLocator]);
		for (Stock__c item : fromLocator) {
			Locator__c locator = mapLocator.get(item.StockLocator__c);
			item.StockWarehouseID__c = locator.WarehouseId__c;
		}
	}
}