force-app/main/default/objects/Cargo_Delivery__c/Cargo_Delivery__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CargoDeliveryOnlineHelp</customHelpPage>
    <description>Cargo Delivery</description>
    <label>配送</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Cargo Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo_Delivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Expected Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/fields/Pickupdate__c.field-meta.xml
<CustomField>
    <fullName>Pickupdate__c</fullName>
    <inlineHelpText>Pickup Date must be earlier than Delivery Date.</inlineHelpText>
    <label>Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Clearance__c/Custom_Clearance__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CustomClearanceOnlineHelp</customHelpPage>
    <description>Custom Clearance</description>
    <label>通関</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Custom Clearance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Clearance__c/fields/Customs_Release_Day__c.field-meta.xml
<CustomField>
    <fullName>Customs_Release_Day__c</fullName>
    <label>CUSTOMS CLEARANCE PERMIT DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/CutDay__c.field-meta.xml
<CustomField>
    <fullName>CutDay__c</fullName>
    <label>CUT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>EXPECTED DELIVERY DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/T_ETD__c.field-meta.xml
<CustomField>
    <fullName>T_ETD__c</fullName>
    <inlineHelpText>Input the ETD at Transit Port. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. ETD at Transit Port in final Transit record will be automatically inserted in this field.</inlineHelpText>
    <label>ETD AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ValidationUtils.cls
public class ValidationUtils {
    public static final String AGGREGATE_MAX = 'MAX';
    public static final String AGGREGATE_MIN = 'MIN';
    
    public static boolean canExecuteTrigger() {
        Custom_Application_Config__c config = Custom_Application_Config__c.getOrgDefaults();
        Boolean disabledTrigger = config.Disabled_Trigger__c;
        
        return (disabledTrigger == null || disabledTrigger == false ? true : false);
    }
    
    public static String validateDeliveryDates(CustomObject1__c shipment, List<Cargo_Delivery__c> cds, List<Custom_Clearance__c> ccs) {
        String errorMessage = '';
        Date maxPickupDate = null;
        Date maxDeliveryDate = null;
        Date minPickupDate = null;
        Date minDeliveryDate = null;
        Date maxCustomClearanceDate = null;
        Date minCustomClearanceDate = null;
        List<Date> vDates = new List<Date>();
        boolean isImport = ObjectClassificationUtils.isImportHBL(shipment);
        boolean isExport = ObjectClassificationUtils.isExportHBL(shipment);

        if (cds != null && !cds.isEmpty()) {
            maxPickupDate = getAggregateDateForCargo(cds, Constants.NAMESPACE + 'Pickupdate__c', AGGREGATE_MAX);
            maxDeliveryDate = getAggregateDateForCargo(cds, Constants.NAMESPACE + 'DeliveryDate__c', AGGREGATE_MAX);
            minPickupDate = getAggregateDateForCargo(cds, Constants.NAMESPACE + 'Pickupdate__c', AGGREGATE_MIN);
            minDeliveryDate = getAggregateDateForCargo(cds, Constants.NAMESPACE + 'DeliveryDate__c', AGGREGATE_MIN);
        }            
       
        if (ccs != null && !ccs.isEmpty()) {
            maxCustomClearanceDate = getAggregateDateForCustomClearance(ccs, AGGREGATE_MAX);
            minCustomClearanceDate = getAggregateDateForCustomClearance(ccs, AGGREGATE_MIN);
        }
      
        if (isImport) {
            if (shipment.ETD__c != null) vDates.add(shipment.ETD__c);
            if (shipment.T_ETD__c != null) vDates.add(shipment.T_ETD__c);
            if (shipment.ETA__c != null) vDates.add(shipment.ETA__c);
            if (minCustomClearanceDate != null) vDates.add(minCustomClearanceDate);
            if (minPickupDate != null) vDates.add(minPickupDate);
            if (minDeliveryDate != null) vDates.add(minDeliveryDate);
        } else if (isExport) {
            if (maxPickupDate != null) vDates.add(maxPickupDate);
            if (maxDeliveryDate != null) vDates.add(maxDeliveryDate);
            if (minCustomClearanceDate != null) vDates.add(minCustomClearanceDate);
            if (shipment.CutDay__c != null) vDates.add(shipment.CutDay__c);
            if (shipment.ETD__c != null) vDates.add(shipment.ETD__c);
            if (shipment.T_ETD__c != null) vDates.add(shipment.T_ETD__c);
            if (shipment.ETA__c != null) vDates.add(shipment.ETA__c);
        }
        
        if (!vDates.isEmpty()) {
            Integer size = vDates.size();

            for (Integer i=0; i<(size-1); i++) {
                if (vDates.get(i) > vDates.get(i+1)) {
                    if (isExport) {
                        // errorMessage = Constants.INVALID_EXPORT_PROCESS_TIME_ORDER;    
                    } else if (isImport) {
                        // errorMessage = Constants.INVALID_IMPORT_PROCESS_TIME_ORDER;    
                    }
                    break;
                }
            }
        }

        return errorMessage;
    }

    public static Date getAggregateDateForCargo(List<Cargo_Delivery__c> cds, String aggFieldName, String aggType) {
        Date aggDate = null;
        
        if (!cds.isEmpty()) {
            for (Cargo_Delivery__c cd : cds) {
                Date aggFieldValue = (Date) cd.get(aggFieldName);
                
                if (aggDate == null 
                        || (aggFieldValue != null && AGGREGATE_MAX.equals(aggType) && aggFieldValue > aggDate) 
                        || (aggFieldValue != null && AGGREGATE_MIN.equals(aggType) && aggFieldValue < aggDate)) {
                    aggDate = aggFieldValue;
                }
            }
        }
        
        return aggDate;
    } 

  
    public static Date getAggregateDateForCustomClearance(List<Custom_Clearance__c> ccs, String aggType) {
        Date aggDate = null;
        
        if (!ccs.isEmpty()) {
            for (Custom_Clearance__c cc : ccs) {
                if (aggDate == null 
                        || (cc.Customs_Release_Day__c != null && AGGREGATE_MAX.equals(aggType) && cc.Customs_Release_Day__c > aggDate) 
                        || (cc.Customs_Release_Day__c != null && AGGREGATE_MIN.equals(aggType) && cc.Customs_Release_Day__c < aggDate)) {
                    aggDate = cc.Customs_Release_Day__c;
                }
            }
        }
        return aggDate;
    }
  
    
}