force-app/main/default/objects/Cargo_Delivery__c/Cargo_Delivery__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CargoDeliveryOnlineHelp</customHelpPage>
    <description>Cargo Delivery</description>
    <label>配送</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Cargo Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo_Delivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Expected Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L-SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Cargo_Delivery</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/fields/Pickupdate__c.field-meta.xml
<CustomField>
    <fullName>Pickupdate__c</fullName>
    <inlineHelpText>Pickup Date must be earlier than Delivery Date.</inlineHelpText>
    <label>Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Clearance__c/Custom_Clearance__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CustomClearanceOnlineHelp</customHelpPage>
    <description>Custom Clearance</description>
    <label>通関</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Custom Clearance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Clearance__c/fields/Customs_Release_Day__c.field-meta.xml
<CustomField>
    <fullName>Customs_Release_Day__c</fullName>
    <label>CUSTOMS CLEARANCE PERMIT DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Clearance__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L-SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Custom_Clearance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/CustomsReleaseDay__c.field-meta.xml
<CustomField>
    <fullName>CustomsReleaseDay__c</fullName>
    <label>CUSTOMS CLEARANCE PERMIT DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/CutDay__c.field-meta.xml
<CustomField>
    <fullName>CutDay__c</fullName>
    <label>CUT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>EXPECTED DELIVERY DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DeliveryService_required__c.field-meta.xml
<CustomField>
    <fullName>DeliveryService_required__c</fullName>
    <inlineHelpText>Choose the number of Pickup or Delivery Required and TRANSPORT object will be created according to the number. To create object, Transportation Type must be chosen. Input the detail of pickup/delivery information to the object.</inlineHelpText>
    <label>PICKUP OR DELIVERY REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/T_ETD__c.field-meta.xml
<CustomField>
    <fullName>T_ETD__c</fullName>
    <inlineHelpText>Input the ETD at Transit Port. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. ETD at Transit Port in final Transit record will be automatically inserted in this field.</inlineHelpText>
    <label>ETD AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CargoDeliveryTriggerHandler.cls
public with sharing class CargoDeliveryTriggerHandler extends AbstractTriggerHandler {
    private Map<Id, CustomObject1__c> mapParentShipments = new Map<Id, CustomObject1__c>();
    private Set<CustomObject1__c> toBeUpdatedShipments = new Set<CustomObject1__c>();
    private static TranslationService translationService;

    static {
        translationService = new TranslationService('ERROR', UserInfo.getLanguage());
    }

    public override String getHandlerName() {
        return 'CargoDeliveryTriggerHandler';
    }

    public override void bulkBefore() {
        loadParentShipments();
    }

    public override void bulkAfter() {
        loadParentShipments();
    }

    public override void beforeInsert(SObject so) {
        Cargo_Delivery__c cd = (Cargo_Delivery__c) so;

        if (!validate(cd)) {
            return;
        }
    }

    public override void afterInsert(SObject so) {
        Cargo_Delivery__c cd = (Cargo_Delivery__c) so;

        if (!TriggerExecutionHelper.isRunning('HBLShipmentsTriggerHandler')) {
            addCargoDeliveryToHBL(cd.HBL_SHIPMENT__c);
        }
    }

    public override void beforeUpdate(SObject oldSo, SObject so) {
        Cargo_Delivery__c newCD = (Cargo_Delivery__c) so;

        if (!validate(newCD)) {
            return;
        }
    }

    public override void afterUpdate(SObject oldSo, SObject so) {
        Cargo_Delivery__c newCD = (Cargo_Delivery__c) so;
        Cargo_Delivery__c oldCD = (Cargo_Delivery__c) oldSo;

        if (oldCD.HBL_SHIPMENT__c != newCD.HBL_SHIPMENT__c) {
            addCargoDeliveryToHBL(newCD.HBL_SHIPMENT__c);
            removeCargoDeliveryFromHBL(oldCD.HBL_SHIPMENT__c);
        }

        if (newCD.DeliveryDate__c != null) {
            updateHBLDeliveryDate(newCD);
        }
    }

    public override void afterDelete(SObject so) {
        Cargo_Delivery__c cd = (Cargo_Delivery__c) so;

        if (!TriggerExecutionHelper.isRunning('HBLShipmentsTriggerHandler')) {
            removeCargoDeliveryFromHBL(cd.HBL_SHIPMENT__c);
        }
    }

    public override void andFinally() {
        if (toBeUpdatedShipments.size() > 0) {
		    FlsService.doUpdate(new List<CustomObject1__c>(toBeUpdatedShipments));
        }
    }

    private void loadParentShipments() {
        Set<Id> parentId = new Set<Id>();
        Set<Cargo_Delivery__c> cds = new Set<Cargo_Delivery__c>();

        if (Trigger.IsInsert) {
            cds.addAll((List<Cargo_Delivery__c>) Trigger.new);
        } else if (Trigger.IsUpdate) {
            cds.addAll((List<Cargo_Delivery__c>) Trigger.new);
            cds.addAll((List<Cargo_Delivery__c>) Trigger.old);
        } else if (Trigger.IsDelete) {
            cds.addAll((List<Cargo_Delivery__c>) Trigger.old);
        }

        for (Cargo_Delivery__c cd : cds) {
            parentId.add(cd.HBL_SHIPMENT__c);
        }

        mapParentShipments = new Map<Id, CustomObject1__c>([
                SELECT Id, DeliveryService_required__c, RecordTypeId, ETD__c, T_ETD__c,
                        ETA__c, CustomsReleaseDay__c, CutDay__c, (SELECT Id, Pickupdate__c, DeliveryDate__c FROM Cargo_Delivery__r),
                        (SELECT Id, Customs_Release_Day__c FROM Custom_Clearance__r)
                FROM CustomObject1__c
                WHERE Id IN :parentId
        ]);
    }

    private void addCargoDeliveryToHBL(Id shipmentId) {
        CustomObject1__c shipment = mapParentShipments.get(shipmentId);

        if (shipment != null) {
            String delieryLocations = LegacyResourceUtils.getHBLDeliveryServiceRequired(shipment.DeliveryService_required__c);
            Integer locations = (StringUtils.isEmpty(delieryLocations) ? 0 : Integer.valueOf(delieryLocations));

            locations++;
            shipment.DeliveryService_required__c = String.valueOf(locations);
            toBeUpdatedShipments.add(shipment);
        }
    }

    private void removeCargoDeliveryFromHBL(Id shipmentId) {
        CustomObject1__c shipment = mapParentShipments.get(shipmentId);

        if (shipment != null) {
            String deliveryLocations = LegacyResourceUtils.getHBLDeliveryServiceRequired(shipment.DeliveryService_required__c);
            Integer locations = (StringUtils.isEmpty(deliveryLocations) ? 0 : Integer.valueOf(deliveryLocations));

            if (locations > 0) {
                locations--;
                shipment.DeliveryService_required__c = String.valueOf(locations);
                toBeUpdatedShipments.add(shipment);
            }
        }
    }

    private boolean isValidRecordType(Cargo_Delivery__c cd) {
        // 2019/08/13 Chien Truong DELETE START
        /*
        CustomObject1__c shipment = mapParentShipments.get(cd.HBL_SHIPMENT__c);
        String recordTypeName = RecordTypeUtil.getRecordTypeDeveloperNameById(CustomObject1__c.SObjectType, shipment.RecordTypeId);

        if (Constants.DOMESTIC_TRANSPORTATION_RT.equalsIgnoreCase(recordTypeName) || Constants.DOMESTIC_TRANSPORTATION_LOCK_RT.equalsIgnoreCase(recordTypeName)
           || Constants.CROSS_BOARDER_RT.equalsIgnoreCase(recordTypeName) || Constants.CROSS_BOARDER_LOCK_RT.equalsIgnoreCase(recordTypeName)) {
            return true;
        }
        boolean isImportHBL = ObjectClassificationUtils.isImportHBL(shipment);
        boolean isExportHBL = ObjectClassificationUtils.isExportHBL(shipment);
        boolean isImportCargo = ObjectClassificationUtils.isImportCargoDelivery(cd.RecordTypeId);
        boolean isExportCargo = ObjectClassificationUtils.isExportCargoDelivery(cd.RecordTypeId);

        if ((isImportHBL && isImportCargo) || (isExportHBL && isExportCargo)) {
            return true;
        }

        return false;
        */
        // 2019/08/13 Chien Truong DELETE END

        // 2019/08/13 Chien Truong ADD START
        return true;
        // 2019/08/13 Chien Truong ADD END
    }

    private boolean validate(Cargo_Delivery__c cd) {
        boolean result = true;

        if (!isValidRecordType(cd)) {
            cd.addError(translationService.getTranslation(Constants.INVALID_RECORD_TYPE));
            result = false;
        } else {
            CustomObject1__c shipment = mapParentShipments.get(cd.HBL_SHIPMENT__c);
            List<Cargo_Delivery__c> cds = shipment.Cargo_Delivery__r;
            if (cd.Id == null) {
                cds.add(cd);
            } else {
                for (Cargo_Delivery__c cargo : cds) {
                    if (cd.Id == cargo.Id) {
                        cargo.Pickupdate__c = cd.Pickupdate__c;
                        cargo.DeliveryDate__c = cd.DeliveryDate__c;
                    }
                }
            }

            String errorMessage = ValidationUtils.validateDeliveryDates(shipment, cds, shipment.Custom_Clearance__r);
            if (!Stringutils.isEmpty(errorMessage)) {
                cd.addError(translationService.getTranslation(errorMessage));
                result = false;
            }
        }

        return result;
    }

    private void updateHBLDeliveryDate(Cargo_Delivery__c cd) {
        CustomObject1__c shipment = mapParentShipments.get(cd.HBL_SHIPMENT__c);
        List<Cargo_Delivery__c> cds = shipment.Cargo_Delivery__r;
        cds.add(cd);

        Date minDeliveryDate = ValidationUtils.getAggregateDateForCargo(cds, 'DeliveryDate__c', ValidationUtils.AGGREGATE_MIN);
        if (minDeliveryDate != null) {
            shipment.DeliveryDate__c = minDeliveryDate;
            toBeUpdatedShipments.add(shipment);
        }
    }
}