force-app/main/default/objects/Amount_Wording_Setting__mdt/Amount_Wording_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Amount Wording Setting</label>
    <pluralLabel>Amount Wording Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Amount_Wording_Setting__mdt/fields/API_Amount_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Amount_Field_Name__c</fullName>
    <label>API Amount Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amount_Wording_Setting__mdt/fields/API_En_Wording_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>API_En_Wording_Field_Name__c</fullName>
    <label>API English Wording Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amount_Wording_Setting__mdt/fields/API_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Object_Name__c</fullName>
    <label>API Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amount_Wording_Setting__mdt/fields/API_Wording_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Wording_Field_Name__c</fullName>
    <label>API VietNamese Wording Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amount_Wording_Setting__mdt/fields/Currency_Type__c.field-meta.xml
<CustomField>
    <fullName>Currency_Type__c</fullName>
    <label>Currency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
                <default>true</default>
                <label>VND</label>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaJPY__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input. 1. It will refer the amount in Unit Price of Buying(Local) in Service Master Object. 2. If not, take the amount =Unit Price of Buying(USD)×Exchange Rate-Buying</inlineHelpText>
    <label>UNIT PRICE OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTaxInitial__c.field-meta.xml
<CustomField>
    <fullName>BuyTaxInitial__c</fullName>
    <defaultValue>0</defaultValue>
    <description>管理者コメント 
2013/09/10
消費税率に販売用と仕入れ用が必要になるため（例）仕入は免税・販売は課税など
こちらの項目は仕入用とする。
【注意】消費税率(販売)のAPI名が
「SellTaxInitial__c」
「TaxInitial__c」な点に注意</description>
    <inlineHelpText>The consumption tax ratio will be input automatically when remain empty. Input the Tax ratio and the amount of value will be changed to amount that included the Tax. For item that is Tax-free or non-Tax, the Tax Ratio will be set 0%.</inlineHelpText>
    <label>CONSUMPTION TAX RATIO-BUYING</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Cost_Allocation_Margin__c.field-meta.xml
<CustomField>
    <fullName>Cost_Allocation_Margin__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Use to add/deduct when Total of Unit Price of Buying is different from Total Buying After Allocation-Checking</description>
    <label>Cost Allocation Margin</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>SellTankaJPY__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input.1. It will refer the amount in Unit Price of Selling(Local) in Service Master Object. 2. If not, take the amount =Unit Price of Selling(USD)×Exchange Rate-Selling</inlineHelpText>
    <label>UNIT PRICE OF SELLING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Suryo__c.field-meta.xml
<CustomField>
    <fullName>Suryo__c</fullName>
    <inlineHelpText>Multiplied to Unit Price of Selling(Buying) and automatically calculates Total Amount of Selling(Buying).</inlineHelpText>
    <label>CHARGE UNIT (TOTAL)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/TAX_ADJUSTMENTSELL__c.field-meta.xml
<CustomField>
    <fullName>TAX_ADJUSTMENTSELL__c</fullName>
    <inlineHelpText>Input the difference between the calculated Tax by formula and actual amount to customer.</inlineHelpText>
    <label>TAX-SELLING ADJUSTMENT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/TaxInitial__c.field-meta.xml
<CustomField>
    <fullName>TaxInitial__c</fullName>
    <defaultValue>0</defaultValue>
    <description>管理者コメント
2013/09/02
本来はレコード作成時にデフォルトで「0.05」の値を持ち、数式「TaxShow__c」に値を渡して金額系の計算をしていた。
しかし、この項目を普段の運用から手で入力したいとのこと。以下の変更を行う
・デフォルト値を空にする
・ワークフローで値を自動代入する（TaxDefaultの値）

2013/09/10
消費税率に販売用と仕入れ用が必要になるため（例）仕入は免税・販売は課税など
こちらの項目は販売用とする。
【注意】消費税率(販売)のAPI名が
「SellTaxInitial__c」
「TaxInitial__c」な点に注意</description>
    <inlineHelpText>The consumption Tax Ratio will be input automatically when remain Empty. Input the Tax ratio and the amount of value will be changed to amount that included the Tax. For item that is Tax-free or non-Tax, the Tax Ratio will be set 0%.</inlineHelpText>
    <label>CONSUMPTION TAX RATIO-SELLING</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Util.cls
/**
 * Created by khanhpham on 6/13/17.
 */

public with sharing class Util {
	public static Map<String, Decimal> WeightConversionRate = new Map<String, Decimal>{
		'g'     => 1,
		'Kg'    => 1000,
		'Ton'   => 1000000
	};
    public static Map<String, Amount_Wording_Setting__mdt> mapWording = new Map<String, Amount_Wording_Setting__mdt>();

	public static Decimal ConvertWeightToBaseUnit(String unit, Decimal weight) {
        if (!WeightConversionRate.containsKey(unit) || weight == null) {
            return weight;
        }
		return weight * WeightConversionRate.get(unit);
	}

	public static Decimal ConvertWeightFromBaseUnit(String unit, Decimal weight) {
        if (!WeightConversionRate.containsKey(unit) || weight == null) {
            return weight;
        }
		return weight / WeightConversionRate.get(unit);
	}

	public static Decimal ConvertWeightToUnit(String fromUnit, String toUnit, Decimal weight) {
        if (fromUnit == toUnit || !WeightConversionRate.containsKey(fromUnit) || !WeightConversionRate.containsKey(toUnit) || weight == null) {
            return weight;
        }
		return weight * (WeightConversionRate.get(fromUnit) / WeightConversionRate.get(toUnit));
	}

    private static final String SF_CUSTOM_DOMAIN_SUFFIX = '.my.salesforce.com';

    public static List<String> getObjectCustomFields(Schema.SObjectType objectType) {
        List<String> customFields = new List<String>();
        Map<String, Schema.sObjectField> fieldMap = objectType.getDescribe().fields.getMap();

        for (String fn : fieldMap.keySet()) {
            if (fn.endswith('__c')) {
                customFields.add(fn);
            }
        }
        return customFields;
    }

    public static String getObjectTypeId(final String objectType) {
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType sObjectType = schemaMap.get(objectType);
        String objectTypeId = sObjectType.getDescribe().getKeyPrefix();

        return objectTypeId;
    }

    public static String getServerInstance() {
        String orgId = UserInfo.getOrganizationId();
        String userId = UserInfo.getUserId();
        String sessionId = UserInfo.getSessionId();

        PageReference pr = new PageReference('/id/' + orgId + '/' + userId);
        pr.getParameters().put('oauth_token', sessionId);
        pr.getParameters().put('format', 'json');

        String data = Test.isRunningTest() ? '{"urls": {"rest": "' + Url.getSalesforceBaseUrl().toExternalForm() + '"}}' : pr.getContent().toString();
        Map<String,Object> result = (Map<String,Object>)Json.deserializeUntyped(data);
        Map<String,Object> urls = (Map<String,Object>)result.get('urls');

        Url rest = new Url((String)urls.get('rest'));
        String baseURL = rest.getHost();

        String instanceName = null;

        if (baseURL.contains(SF_CUSTOM_DOMAIN_SUFFIX)) {
            String domainName = getSFDomainFromBaseURL(baseURL);
            instanceName = getServerInstanceByDomainName(domainName);
        } else {
            String sfdcURL = baseURL.remove('https://');
            Integer index = sfdcURL.indexOf('.salesforce.com');
            instanceName = sfdcURL.substring(0, index);
        }

        return instanceName;
    }

    public static String getServerInstanceByDomainName(final String domainName) {
        String instanceName = null;

        try {
            String endpoint = 'https://api.status.salesforce.com/v1/instanceAliases/' + domainName;

            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint);
            request.setMethod('GET');
            HttpResponse response = http.send(request);

            JSONParser parser = JSON.createParser(response.getBody());
            while (parser.nextToken() != null) {
                if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText().equalsIgnoreCase('instanceKey')) {
                    parser.nextToken();
                    instanceName = parser.getText();
                }
            }
        } catch (Exception ex) {
        }

        return instanceName;
    }

    public static String getSFDomainFromBaseURL(String baseURL) {
        String domainName = null;

        if (baseURL.contains(SF_CUSTOM_DOMAIN_SUFFIX)) {
            baseURL = baseURL.remove('https://');
            Integer index = baseURL.indexOf(SF_CUSTOM_DOMAIN_SUFFIX);
            domainName = baseURL.substring(0, index);
        }

        return domainName;
    }

    public static Boolean isCashOut(CASH_BOOK__c cashBook) {
        return cashBook.RecordTypeId == Constants.RecordTypeId_CashBook_CashOut;
        // String recordTypeName = RecordTypeUtil.getRecordTypeDeveloperNameById(CASH_BOOK__c.SObjectType, cashBook.RecordTypeId);

        // return (Constants.CASH_OUT_RT.equalsIgnoreCase(recordTypeName));
    }

    public static Boolean isCashIn(CASH_BOOK__c cashBook) {
        return CashBook.RecordTypeId == Constants.RecordTypeId_CashBook_CashIn;
        // String recordTypeName = RecordTypeUtil.getRecordTypeDeveloperNameById(CASH_BOOK__c.SObjectType, cashBook.RecordTypeId);

        // return (Constants.CASH_IN_RT.equalsIgnoreCase(recordTypeName));
    }

    public static Decimal calculateSellingAmount(AnkenMeisai__c record) {
        Decimal chargeUnit = (record.Suryo__c != null ? record.Suryo__c : 0);
        Decimal sellingUnitPrice = (record.SellTankaJPY__c != null ? record.SellTankaJPY__c : 0);

        return (chargeUnit * sellingUnitPrice);
    }

    public static Decimal calculateSellingInTaxAmount(AnkenMeisai__c record) {
        Decimal sellingAmount = calculateSellingAmount(record);
        Decimal taxRatio = (record.TaxInitial__c != null ? record.TaxInitial__c : 0);
        Decimal taxAdjustment = (record.TAX_ADJUSTMENTSELL__c != null ? record.TAX_ADJUSTMENTSELL__c : 0);

        return (sellingAmount * (1 + taxRatio / 100) + taxAdjustment);
    }

    public static Decimal calculateBuyingAmount(AnkenMeisai__c record) {
        Decimal chargeUnit = (record.Suryo__c != null ? record.Suryo__c : 0);
        Decimal buyingUnitPrice = (record.BuyTankaJPY__c != null ? record.BuyTankaJPY__c : 0);
        Decimal taxRatio = (record.BuyTaxInitial__c != null ? record.BuyTaxInitial__c : 0);
        Decimal costAllocationMargin = (record.Cost_Allocation_Margin__c != null ? record.Cost_Allocation_Margin__c : 0);

        return (chargeUnit * buyingUnitPrice + costAllocationMargin/(1 + taxRatio));
    }

    public static Decimal calculateBuyingInTaxAmount(AnkenMeisai__c record) {
        Decimal buyingAMount = calculateBuyingAmount(record);
        Decimal taxRatio = (record.BuyTaxInitial__c != null ? record.BuyTaxInitial__c : 0);
        Decimal taxAdjustment = (record.TAX_ADJUSTMENTSELL__c != null ? record.TAX_ADJUSTMENTSELL__c : 0);
        
        return (buyingAMount * (1 + taxRatio / 100) + taxAdjustment);
    }

  //  public static Map<String, String> listOutWordingForObject(String objectName){
  //      List<Amount_Wording_Setting__mdt> listWordingField = [SELECT 
  //                                                              API_Object_Name__c, 
  //                                                              API_Amount_Field_Name__c, 
  //                                                              API_Wording_Field_Name__c,
  //                                                              Currency_Type__c,
  //                                                              API_En_Wording_Field_Name__c
  //                                                          FROM Amount_Wording_Setting__mdt 
  //                                                          WHERE API_Object_Name__c =: objectName];
  //      Map<String, String> mapWording = new Map<String, String>();
  //      Map<String, Schema.SObjectType> global_describe = Schema.getGlobalDescribe();
		//Map<String, Schema.SObjectField> object_fields_map = global_describe.get(objectName).getDescribe().fields.getMap();
  //      for(Amount_Wording_Setting__mdt wordingSetting : listWordingField){
  //          if(object_fields_map.containsKey(wordingSetting.API_Amount_Field_Name__c)
  //            && object_fields_map.containsKey(wordingSetting.API_Wording_Field_Name__c)){
  //              mapWording.put(wordingSetting.API_Amount_Field_Name__c, wordingSetting.API_Wording_Field_Name__c);
  //          }
  //      }

  //      return mapWording;
  //  }

    

  //  public static void wordingFields(sobject argSObject, Map<String, String> mapFieldWording){
  //      for(String amountField : mapFieldWording.keySet()){
  //          String wording = '';
  //          Decimal amount = (Decimal)(argSObject.get(amountField) != null? argSObject.get(amountField) : 0);
  //          wording = NumbericUtils.convertNumberToText(amount);
  //          argSObject.put(mapFieldWording.get(amountField), wording) ;
  //      }
  //  }

    public static void listOutFieldsWordingForObject(String objectName){
        List<Amount_Wording_Setting__mdt> listWordingField = [SELECT 
                                                                API_Object_Name__c, 
                                                                API_Amount_Field_Name__c, 
                                                                API_Wording_Field_Name__c,
                                                                Currency_Type__c,
                                                                API_En_Wording_Field_Name__c
                                                            FROM Amount_Wording_Setting__mdt 
                                                            WHERE API_Object_Name__c =: objectName];
        
        for(Amount_Wording_Setting__mdt wordingSetting : listWordingField){
            
            mapWording.put(wordingSetting.API_Amount_Field_Name__c, wordingSetting);
        }
    }
    public static void wordingFields(sobject argSObject, Map<String, Amount_Wording_Setting__mdt> mapFieldWording){
        Schema.SObjectType typeObject = argSObject.getSObjectType();
        Map<String, Schema.SObjectField> object_fields_map = typeObject.getDescribe().fields.getMap();
        //Schema.DescribeSObjectResult  describeObject = typeObject.getDescribe();
        
        for(String amountField : mapFieldWording.keySet()){
            if(object_fields_map.containsKey(amountField.toLowerCase())){
                Amount_Wording_Setting__mdt setting = mapFieldWording.get(amountField);
                String wording = '';

                Decimal amount = (Decimal)(argSObject.get(amountField) != null? argSObject.get(amountField) : 0);
                if(setting.Currency_Type__c == 'VND'){
                    // WORDING IN VI
                    if(!String.isBlank(setting.API_Wording_Field_Name__c)
                        && object_fields_map.containsKey(setting.API_Wording_Field_Name__c)){
                        wording = NumbericUtils.convertNumberToText(amount, setting.Currency_Type__c);
                        argSObject.put(setting.API_Wording_Field_Name__c, wording);
                    }

                    // WORDING IN EN
                    if(!String.isBlank(setting.API_En_Wording_Field_Name__c)
                        && object_fields_map.containsKey(setting.API_En_Wording_Field_Name__c)){
                        wording = NumbericUtils.readVNDAmountInEn(amount);
                        argSObject.put(setting.API_En_Wording_Field_Name__c, wording);
                    }
                }else{
                    // WORDING IN VI
                    if(!String.isBlank(setting.API_Wording_Field_Name__c)
                        && object_fields_map.containsKey(setting.API_Wording_Field_Name__c)){
                        wording = NumbericUtils.convertNumberToText(amount, setting.Currency_Type__c);
                        argSObject.put(setting.API_Wording_Field_Name__c, wording);
                    }

                    // WORDING IN EN
                    if(!String.isBlank(setting.API_En_Wording_Field_Name__c)
                        && object_fields_map.containsKey(setting.API_En_Wording_Field_Name__c)){
                        wording = NumbericUtils.readUSDAmountInEn(amount);
                        argSObject.put(setting.API_En_Wording_Field_Name__c, wording);
                    }
                }
            }
        }
    }
}