force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract.</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>CONTRACT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Unitpricewillbechargedbaseon__c.field-meta.xml
<CustomField>
    <fullName>Unitpricewillbechargedbaseon__c</fullName>
    <label>Unit price will be charged base on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gross Weight</fullName>
            </value>
            <value>
                <fullName>Net Weight</fullName>
            </value>
            <value>
                <fullName>G.W (MT)</fullName>
            </value>
            <value>
                <fullName>N.W (MT)</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Bag</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractProduct__c/ContractProduct__c.object-meta.xml
<CustomObject>
    <label>Contract+Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contract+Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract+Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractProduct__c/fields/BillNameatPrintENG__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintENG__c</fullName>
    <label>Bill Name at Print(ENG)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/CONTRACT__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT__c</fullName>
    <label>CONTRACT</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract+Products</relationshipLabel>
    <relationshipName>Contract_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanChargeQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlanChargeQuantity__c</fullName>
    <label>Plan Charge Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanGrossWeightMT__c.field-meta.xml
<CustomField>
    <fullName>PlanGrossWeightMT__c</fullName>
    <label>Plan Gross Weight(MT)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanNetWeightMT__c.field-meta.xml
<CustomField>
    <fullName>PlanNetWeightMT__c</fullName>
    <label>Plan Net Weight(MT)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/UnitPriceofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingFCY__c</fullName>
    <label>Unit Price of Selling(FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProformaInvoiceControllerTest.cls
@isTest
private class ProformaInvoiceControllerTest {
  private static Contract__c contract { get; set; }
  static {
    contract = new Contract__c(
      Unitpricewillbechargedbaseon__c = 'Gross Weight'
    );
    FlsService.doInsert(contract);

    ContractProduct__c conPro = new ContractProduct__c(
      CONTRACT__c = contract.Id,
      BillNameatPrintENG__c = 'Product A',
      PlanGrossWeightMT__c = 20,
      PlanNetWeightMT__c = 15,
      UnitPriceofSellingFCY__c = 1,
      PlanChargeQuantity__c = 5
    );
    FlsService.doInsert(conPro);
  }

  @isTest
  static void testProInvController() {
    Test.startTest();
    ApexPages.currentPage().getParameters().put('id', contract.Id);
    ApexPages.currentPage().getParameters().put('showFooter', 'true');
    ProformaInvoiceController proInvController = new ProformaInvoiceController();
    System.assert(proInvController.contractProducts.size() == 1);
    Test.stopTest();
  }
}