force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/ChargeUnitFormula__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnitFormula__c</fullName>
    <formula>/*IF(TEXT( clofor_com_cfs__ContainerSize__c) != NULL 
, TEXT( clofor_com_cfs__ContainerSize__c) 
, IF(TEXT( clofor_com_cfs__ChargeUnit__c ) != NULL 
  , TEXT( clofor_com_cfs__ChargeUnit__c ) 
  , TEXT( clofor_com_cfs__Tariff__r.clofor_com_cfs__UNIT__c )
  )
)*/


IF(TEXT( ChargeUnit__c ) != NULL 
, TEXT( ChargeUnit__c ) 
, TEXT( Tariff__r.UNIT__c )
)</formula>
    <label>Charge Unit-Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/ChargeUnitInPrint__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnitInPrint__c</fullName>
    <label>Charge Unit in Print</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/ContainerSizeFormula__c.field-meta.xml
<CustomField>
    <fullName>ContainerSizeFormula__c</fullName>
    <formula>IF(TEXT( ContainerSize__c ) != NULL 
, TEXT( ContainerSize__c ) 
, TEXT( Tariff__r.ContainerSize__c )
)</formula>
    <label>Container Size-Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/excuteTriggerControll.cls
public class excuteTriggerControll {
	public static boolean firstRunCashPaymentAutoProcesing = true;
    public static boolean firstRunHBLSellingBuyingTrigger = true;
    public static boolean firstRun = true;
    public static void translateUnitValueInsert(List<AnkenMeisai__c> newBills){
        //get unit formula value.
        //List<AnkenMeisai__c> bills = [SELECT Id, ChargeUnitFormula__c, ContainerSizeFormula__c from AnkenMeisai__c where Id IN: mapNewBills.keySet()];
        for(AnkenMeisai__c bill : newBills){
            if (bill.ChargeUnitInPrint__c == null){ 
                if (bill.ContainerSizeFormula__c != null){
                    bill.ChargeUnitInPrint__c = bill.ContainerSizeFormula__c;
                } else {
                    bill.ChargeUnitInPrint__c = bill.ChargeUnitFormula__c;
                }
                // bill.ChargeUnitInPrint__c = bill.ChargeUnitFormula__c;
                // if(bill.ChargeUnitFormula__c =='本'){
                    // bill.ChargeUnitInPrint__c = 'Unit';
                // } 
                // if(bill.ChargeUnitFormula__c =='コンテナ' || bill.ChargeUnitFormula__c =='Container'){
                    // bill.ChargeUnitInPrint__c = bill.ContainerSizeFormula__c;
                // }
                // if(bill.ChargeUnitFormula__c =='件'){
                    // bill.ChargeUnitInPrint__c = 'Case';
                // }
            }
        }
    }

    public static void translateUnitValueUpdate(List<AnkenMeisai__c> oldBills, List<AnkenMeisai__c> newBills){
        //get unit formula value.
        //List<AnkenMeisai__c> bills = [SELECT Id, ChargeUnitFormula__c, ContainerSizeFormula__c from AnkenMeisai__c where Id IN: mapNewBills.keySet()];
        for (AnkenMeisai__c billold : oldBills){
            for(AnkenMeisai__c bill : newBills){
                if ((bill.Id == billold.Id ) && (bill.ChargeUnitInPrint__c == null || bill.clofor_com_cfs__ContainerSize__c != billold.clofor_com_cfs__ContainerSize__c || bill.clofor_com_cfs__ChargeUnit__c != billold.clofor_com_cfs__ChargeUnit__c)){       
                    // bill.ChargeUnitInPrint__c = bill.ChargeUnitFormula__c;
                    // if(bill.ChargeUnitFormula__c =='本'){
                        // bill.ChargeUnitInPrint__c = 'Unit';
                    // } 
                    // if(bill.ChargeUnitFormula__c =='コンテナ' || bill.ChargeUnitFormula__c =='Container'){
                        // bill.ChargeUnitInPrint__c = bill.ContainerSizeFormula__c;
                    // }
                    // if(bill.ChargeUnitFormula__c =='件'){
                        // bill.ChargeUnitInPrint__c = 'Case';
                    // }
                    if (bill.ContainerSizeFormula__c != null){
                        bill.ChargeUnitInPrint__c = bill.ContainerSizeFormula__c;
                    } else {
                        bill.ChargeUnitInPrint__c = bill.ChargeUnitFormula__c;
                    }
                }
            }
        }
    }
}