force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>BuyDifferentiation__c</fullName>
    <formula>BuyInTaxAmountJPY__c - Siharaigaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Buying(Local)=Amount Buying including Tax(Local)-Amount Paid-Buying(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF BUYING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>To search available Bank Account list, please tab the mouse point on top of the company name in Payment to</inlineHelpText>
    <label>PAYMENT TO-BUYING</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>CustomerB2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bill (PAYMENT TO-BUYING)</relationshipLabel>
    <relationshipName>PaymentTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Seikyusaki__c.field-meta.xml
<CustomField>
    <fullName>Seikyusaki__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Export and Not EXW--&gt;Set shipper
Export and EXW--&gt;Set Partner
Import and Not DDP/DDU--&gt;Set Consignee
Import &amp; DDP/DDU--&gt;Set Partner</inlineHelpText>
    <label>INVOICE TO</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerB2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS BILL (INVOICE TO)</relationshipLabel>
    <relationshipName>Seikyusakis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>SellDifferentiation__c</fullName>
    <formula>SellInTaxAmountJPY__c - Nyukingaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Selling(Local)=Amount Selling including Tax(Local)-Amount Paid-Selling(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF SELLING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/UNPAID_BALANCE_OF_BUYING_USD__c.field-meta.xml
<CustomField>
    <fullName>UNPAID_BALANCE_OF_BUYING_USD__c</fullName>
    <formula>BuyInTaxAmountUSD__c - AMOUNT_PAID_BUYING_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Buying(FCY)=Amount Buying including Tax(FCY)-Amount Paid-Buying(FCY)</inlineHelpText>
    <label>UNPAID BALANCE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/UNPAID_BALANCE_OF_SELLING_USD__c.field-meta.xml
<CustomField>
    <fullName>UNPAID_BALANCE_OF_SELLING_USD__c</fullName>
    <formula>SellInTaxAmount_USD__c - AMOUNT_PAID_SELLING_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Selling(FCY)=Amount Selling including Tax(FCY)-Amount Received from Customer(FCY)</inlineHelpText>
    <label>Unreceived Balance of Selling(FCY)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FMSBillLoan__c/FMSBillLoan__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+Loan</label>
    <nameField>
        <displayFormat>FBL-{000000}</displayFormat>
        <label>FMS BILL+LOAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+Loan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FMSBillLoan__c/fields/FMSBillID__c.field-meta.xml
<CustomField>
    <fullName>FMSBillID__c</fullName>
    <label>FMS/TMS BILL ID</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>FMSBillLoan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillLoan__c/fields/LoanID__c.field-meta.xml
<CustomField>
    <fullName>LoanID__c</fullName>
    <label>LOAN ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipName>FMSTMSBillLoan</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/FMSBillPayReq__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+TRX Plan</label>
    <nameField>
        <displayFormat>FBPR-{000000}</displayFormat>
        <label>FMS BILL+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FMSBillPayReq__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipLabel>FMS BILL+TRX PLAN</relationshipLabel>
    <relationshipName>FMSBillTrxPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/CashID__c.field-meta.xml
<CustomField>
    <fullName>CashID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CASH ID</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipLabel>FMS BILL+TRX PLAN</relationshipLabel>
    <relationshipName>FMSBillTrxPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSBillID__c.field-meta.xml
<CustomField>
    <fullName>FMSBillID__c</fullName>
    <label>FMS BILL ID</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSUnpaidBalOfBuyingLocalPayReq__c.field-meta.xml
<CustomField>
    <fullName>FMSUnpaidBalOfBuyingLocalPayReq__c</fullName>
    <label>FMS UNPAID BAL OF BUYING(LOCAL)-PAY REQ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSUnpaidBalOfBuyingUSDPayReq__c.field-meta.xml
<CustomField>
    <fullName>FMSUnpaidBalOfBuyingUSDPayReq__c</fullName>
    <label>FMS UNPAID BAL OF BUYING(USD)-PAY REQ</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSUnreceivedBalOfSellingLocalTrx__c.field-meta.xml
<CustomField>
    <fullName>FMSUnreceivedBalOfSellingLocalTrx__c</fullName>
    <label>FMS UNRECEIVED BAL OF SELLING(LOCAL)-TRX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSUnreceivedBalOfSellingUSDTrx__c.field-meta.xml
<CustomField>
    <fullName>FMSUnreceivedBalOfSellingUSDTrx__c</fullName>
    <label>FMS UNRECEIVED BAL OF SELLING(USD)-TRX</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <formula>FMSBillID__r.Seikyusaki__r.Name</formula>
    <label>Invoice To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/LoanID__c.field-meta.xml
<CustomField>
    <fullName>LoanID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOAN ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>FMS BILL+TRX PLAN</relationshipLabel>
    <relationshipName>FMSBillTrxPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <formula>FMSBillID__r.PaymentTo__r.Name</formula>
    <label>Payment To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/PayReqRollupStatus__c.field-meta.xml
<CustomField>
    <fullName>PayReqRollupStatus__c</fullName>
    <label>PAY REQ ROLLUP STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RECEIVABLE_PAYABLE_ROLLUP_STATUS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/PaymentRequest__c.object-meta.xml
<CustomObject>
    <label>TRX Plan</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>PAYMENT REQUEST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TRX Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentRequest__c/fields/AmountLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountLocal__c</fullName>
    <label>AMOUNT(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/AmountLocalForCollection__c.field-meta.xml
<CustomField>
    <fullName>AmountLocalForCollection__c</fullName>
    <label>AMOUNT(LOCAL) FOR COLLECTION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/AmountUSD__c.field-meta.xml
<CustomField>
    <fullName>AmountUSD__c</fullName>
    <label>AMOUNT(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/AmountUSDForCollection__c.field-meta.xml
<CustomField>
    <fullName>AmountUSDForCollection__c</fullName>
    <label>AMOUNT(USD) FOR COLLECTION</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/AutoConnectSourceToTransaction__c.field-meta.xml
<CustomField>
    <fullName>AutoConnectSourceToTransaction__c</fullName>
    <label>AUTO-CONNECT SOURCES TO TRANSACTION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RecordCreationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/BankID__c.field-meta.xml
<CustomField>
    <fullName>BankID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BANK ID</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipLabel>TRX PLAN</relationshipLabel>
    <relationshipName>TrxPlanBank</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/CashID__c.field-meta.xml
<CustomField>
    <fullName>CashID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CASH ID</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipLabel>TRX PLAN</relationshipLabel>
    <relationshipName>TrxPlanCash</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TRX PLAN (INVOICE TO)</relationshipLabel>
    <relationshipName>TrxPlanInvoiceTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/LoanID__c.field-meta.xml
<CustomField>
    <fullName>LoanID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOAN ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>TRX PLAN</relationshipLabel>
    <relationshipName>TrxPlanLoan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentRequest__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TRX PLAN(PAYMENT TO)</relationshipLabel>
    <relationshipName>TrxPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VATPayReq__c/VATPayReq__c.object-meta.xml
<CustomObject>
    <label>VAT+TRX Plan</label>
    <nameField>
        <displayFormat>VIPR-{000000}</displayFormat>
        <label>VAT+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VAT+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VATPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>PaymentRequestID</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/RECEIVABLE_PAYABLE_ROLLUP_STATUS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Yet Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Processing Requested</fullName>
        <default>true</default>
        <label>Processing Requested</label>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>RECEIVABLE &amp; PAYABLE ROLLUP STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RecordCreationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Yet Processed</fullName>
        <default>true</default>
        <label>Not Yet Processed</label>
    </customValue>
    <customValue>
        <fullName>Processing Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>RECORD CREATION STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FMSBillPayReqTriggerHelper.cls
public class FMSBillPayReqTriggerHelper {
    public static Boolean rollupFlag = false;
    public static Boolean recalculateFlag = false;
    public static void checkDuplicate(List<FMSBillPayReq__c> billRequestList){
        Set<String> uniqueKeys = new Set<String>();
        Set<String> billIds = new Set<String>();
        Set<String> requestIds = new Set<String>();
        for(FMSBillPayReq__c billReq : billRequestList){
           String uniqueKey = String.valueOf(billReq.PaymentRequestID__c) + String.valueOf(billReq.FMSBillID__c);
            if(uniqueKeys.contains(uniqueKey)){
                String errorStr = 'Duplicate found : Already connected bill {0} with TRX Plan {1}';
                errorStr = String.format(errorStr, new List<String> {billReq.FMSBillID__r.Name, billReq.PaymentRequestID__r.Name});
                billRequestList[0].addError(errorStr);
            }else{
                billIds.add(billReq.FMSBillID__c);
                requestIds.add(billReq.PaymentRequestID__c);
                uniqueKeys.add(uniqueKey);
            }
        }
        // get in database
        List<FMSBillPayReq__c> billRequestDB = [SELECT Id, PaymentRequestID__c, PaymentRequestID__r.Name, 
                                                FMSBillID__c,  FMSBillID__r.Name
                                                FROM FMSBillPayReq__c
                                                WHERE PaymentRequestID__c IN: requestIds
                                               	AND FMSBillID__c IN: billIds];
        if(!billRequestDB.isEmpty()){
            for(FMSBillPayReq__c billReqDB : billRequestDB){
                String errorStr = 'Duplicate found : Already connected bill {0} with TRX Plan {1}';
                errorStr = String.format(errorStr, new List<String> {billReqDB.FMSBillID__r.Name, billReqDB.PaymentRequestID__r.Name});
                billRequestList[0].addError(errorStr);
            }
            
        }
    }


    public static void rollupAmountToPaymentRequest(List<FMSBillPayReq__c> billRequestList, Map<Id, FMSBillPayReq__c> billReqOldMap){
        Map<Id, List<FMSBillPayReq__c>> billByRequestMap = new Map<Id, List<FMSBillPayReq__c>>();
        Set<Id> billIds = new Set<Id>();
        for(FMSBillPayReq__c billReq : billRequestList){
            billIds.add(billReq.FMSBillID__c);
            if(billByRequestMap.containsKey(billReq.PaymentRequestID__c)){
                billByRequestMap.get(billReq.PaymentRequestID__c).add(billReq);
            }else{
                billByRequestMap.put(billReq.PaymentRequestID__c, new List<FMSBillPayReq__c>{billReq});
            }
        }
        Map<Id, PaymentRequest__c> mapPaymentRequest = new Map<Id, PaymentRequest__c>([SELECT Id, PaymentTo__c, InvoiceTo__c 
                                                                                        FROM PaymentRequest__c 
                                                                                        WHERE Id IN: billByRequestMap.keySet()]);
        // get list bill
        Map<Id, AnkenMeisai__c> billMap= new Map<Id, AnkenMeisai__c>([SELECT Id, 
                                            BuyDifferentiation__c, 
                                            UNPAID_BALANCE_OF_BUYING_USD__c, 
                                            SellDifferentiation__c,
                                            UNPAID_BALANCE_OF_SELLING_USD__c,
                                            PaymentTo__c,
                                            Seikyusaki__c
                                            FROM AnkenMeisai__c
                                            WHERE Id IN: billIds]);
        // get list PaymentRequest
        Map<Id, PaymentRequest__c> paymentRequestMap = new Map<Id, PaymentRequest__c>([SELECT Id, 
                                            AmountLocalForCollection__c, 
                                            AmountUSDForCollection__c, 
                                            PaymentTo__c,
                                            InvoiceTo__c,
                                            BankID__c,
                                            CashID__c,
                                            LoanID__c,
                                            AmountLocal__c,
                                            AmountUSD__c
                                            FROM PaymentRequest__c
                                            WHERE Id IN: billByRequestMap.keySet()]);


        Set<String> setBillBankIds = new Set<String>();
        Set<String> setBillCashIds = new Set<String>();
        Set<String> setBillLoanIds = new Set<String>();
        List<CloFMSBillBank__c> billBankList = new List<CloFMSBillBank__c>();
        List<ConnectInvoicingAndCash__c> billCashList = new List<ConnectInvoicingAndCash__c>();
        List<FMSBillLoan__c> billLoanList = new List<FMSBillLoan__c>();
        
        for(PaymentRequest__c paymentReq : paymentRequestMap.values()){
            List<FMSBillPayReq__c> billIdsofReq =  billByRequestMap.get(paymentReq.Id);
            
            for(FMSBillPayReq__c billReq : billIdsofReq){

                if(billMap.containsKey(billReq.FMSBillID__c)){
                    AnkenMeisai__c bill = billMap.get(billReq.FMSBillID__c);
                    Decimal  buyDifferentiation = bill.BuyDifferentiation__c == null ? 0 :  bill.BuyDifferentiation__c;
                    Decimal  unpaidBalanceOfBuyingUSD = bill.UNPAID_BALANCE_OF_BUYING_USD__c == null ? 0 :  bill.UNPAID_BALANCE_OF_BUYING_USD__c;
                    Decimal  sellDifferentiation = bill.SellDifferentiation__c == null ? 0 :  bill.SellDifferentiation__c;
                    Decimal  unpaidBalanceOfSellingUSD = bill.UNPAID_BALANCE_OF_SELLING_USD__c == null ? 0 :  bill.UNPAID_BALANCE_OF_SELLING_USD__c;
                    if(billReq.PayReqRollupStatus__c != 'Processed'){
                        if(paymentRequestMap.get(paymentReq.Id).PaymentTo__c == bill.PaymentTo__c
                            || paymentRequestMap.get(paymentReq.Id).InvoiceTo__c == bill.PaymentTo__c){
                            billReq.FMSUnpaidBalOfBuyingLocalPayReq__c = buyDifferentiation;
                            billReq.FMSUnpaidBalOfBuyingUSDPayReq__c = unpaidBalanceOfBuyingUSD;
                        }
                        if(paymentRequestMap.get(paymentReq.Id).InvoiceTo__c == bill.Seikyusaki__c
                            || paymentRequestMap.get(paymentReq.Id).PaymentTo__c == bill.Seikyusaki__c){
                            billReq.FMSUnreceivedBalOfSellingLocalTrx__c = sellDifferentiation;
                            billReq.FMSUnreceivedBalOfSellingUSDTrx__c = unpaidBalanceOfSellingUSD;
                        }
                        

                        if(buyDifferentiation != null 
                            || unpaidBalanceOfBuyingUSD != null
                            || sellDifferentiation != null
                            || unpaidBalanceOfSellingUSD != null){

                            billReq.PayReqRollupStatus__c = 'Processed';
                        }
                    }
                    if(billReq.AutoConnectSourceToTransaction__c == 'Processing Requested'){
                        if(paymentReq.BankID__c != null){
                            String keyBillBankId = String.valueOf(paymentReq.BankID__c) + String.valueOf(billReq.FMSBillID__c);
                            if(!setBillBankIds.contains(keyBillBankId)){
                                setBillBankIds.add(keyBillBankId);
                                CloFMSBillBank__c newBillBank = new CloFMSBillBank__c(
                                    CloFMSBillID__c = billReq.FMSBillID__c,
                                    BankTransactionID__c = paymentReq.BankID__c
                                );
                                billBankList.add(newBillBank);
                                billReq.AutoConnectSourceToTransaction__c = 'Processed';
                            }
                        }

                        if(paymentReq.CashID__c != null){
                            String keyBillCashId = String.valueOf(paymentReq.CashID__c) + String.valueOf(billReq.FMSBillID__c);
                            if(!setBillCashIds.contains(keyBillCashId)){
                                setBillCashIds.add(keyBillCashId);
                                ConnectInvoicingAndCash__c newBillCash = new ConnectInvoicingAndCash__c(
                                    Invoicing__c = billReq.FMSBillID__c,
                                    Cashbook__c = paymentReq.CashID__c
                                );
                                billCashList.add(newBillCash);
                                billReq.AutoConnectSourceToTransaction__c = 'Processed';
                            }
                        }

                        if(paymentReq.LoanID__c != null){
                            String keyBillLoanId = String.valueOf(paymentReq.LoanID__c) + String.valueOf(billReq.FMSBillID__c);
                            if(!setBillLoanIds.contains(keyBillLoanId)){
                                setBillLoanIds.add(keyBillLoanId);
                                FMSBillLoan__c newBillLoan = new FMSBillLoan__c(
                                    FMSBillID__c = billReq.FMSBillID__c,
                                    LoanID__c = paymentReq.LoanID__c
                                );
                                billLoanList.add(newBillLoan);
                                billReq.AutoConnectSourceToTransaction__c = 'Processed';
                            }
                        }

                    }
                    
                }
            }
        }
        try{
            FlsService.doInsert(billBankList);
            FlsService.doInsert(billCashList);
            FlsService.doInsert(billLoanList);
        }catch(Exception ex){
             billRequestList[0].addError(ex.getMessage());
        }
	}

    public static void reCacualateAmountToPaymentRequest(List<FMSBillPayReq__c> lisBillReqOld){
        try{
            Set<Id> paymentRequest = new Set<Id>();
            for( FMSBillPayReq__c paymentReq : lisBillReqOld){
                paymentRequest.add(paymentReq.PaymentRequestID__c);
            }

            Set<Id> accountIds = new Set<Id>();
            Map<Id, PaymentRequest__c> mapPaymentRequest = new Map<Id, PaymentRequest__c>([SELECT Id, 
                                                                                            PaymentTo__c, 
                                                                                            InvoiceTo__c, 
                                                                                            AmountLocal__c,
                                                                                            AmountUSD__c,
                                                                                            AmountLocalForCollection__c,
                                                                                            AmountUSDForCollection__c,
                                                                                            RecordType.DeveloperName
                                                                                            FROM PaymentRequest__c WHERE Id IN: paymentRequest]);
            for(PaymentRequest__c pr : mapPaymentRequest.values()){
                if(!String.isBlank(pr.PaymentTo__c)){
                    accountIds.add(pr.PaymentTo__c);
                }
                 if(!String.isBlank(pr.InvoiceTo__c)){
                    accountIds.add(pr.InvoiceTo__c);
                }
            }
            List<AggregateResult> listBillPaymentRedRemaining = [SELECT PaymentRequestID__c,
                                                                    FMSBillID__r.PaymentTo__c PaymentTo, 
                                                                    FMSBillID__r.Seikyusaki__c InvoiceTo,
                                                                    sum(FMSUnpaidBalOfBuyingLocalPayReq__c) AmountLocal,
                                                                    sum(FMSUnpaidBalOfBuyingUSDPayReq__c) AmountUSD,
                                                                    sum(FMSUnreceivedBalOfSellingLocalTrx__c) AmountLocalForCollection,
                                                                    sum(FMSUnreceivedBalOfSellingUSDTrx__c) AmountUSDForCollection 
                                                                    FROM FMSBillPayReq__c
                                                                    WHERE PayReqRollupStatus__c = 'Processed'
                                                                    AND PaymentRequestID__c IN: paymentRequest
                                                                    AND (
                                                                        FMSBillID__r.PaymentTo__c IN: accountIds
                                                                        OR  FMSBillID__r.Seikyusaki__c IN: accountIds
                                                                    )
                                                                    GROUP BY  PaymentRequestID__c, FMSBillID__r.PaymentTo__c, FMSBillID__r.Seikyusaki__c
                                                                    ORDER BY PaymentRequestID__c];
            //List<PaymentRequest__c> paymentReqListToUpdate = [SELECT Id FROM PaymentRequest__c WHERE Id IN: paymentRequest];
            Map<String, List<AggregateResult>> mapSum = new Map<String, List<AggregateResult>>();
            for(AggregateResult result : listBillPaymentRedRemaining){
                if(result.get('clofor_com_cfs__PaymentRequestID__c') != null){
                    if(!mapSum.containsKey((String)result.get('clofor_com_cfs__PaymentRequestID__c'))){
                        mapSum.put((String)result.get('clofor_com_cfs__PaymentRequestID__c'), new List<AggregateResult>{result});
                    }else{
                        mapSum.get((String)result.get('clofor_com_cfs__PaymentRequestID__c')).add(result);
                    }
                    
                }
            }
            for(PaymentRequest__c request : mapPaymentRequest.values()){
                request.AmountLocal__c = 0;
                request.AmountUSD__c = 0;
                request.AmountLocalForCollection__c = 0;
                request.AmountUSDForCollection__c = 0;
                if(mapSum.containsKey(request.Id)){
                    List<AggregateResult> results = mapSum.get(request.Id);
                    for(AggregateResult result : results){
                        if(!String.isBlank(request.InvoiceTo__c)){

                            if(result.get('InvoiceTo') != null && request.InvoiceTo__c == (String)result.get('InvoiceTo')){
                                    if(result.get('AmountLocalForCollection') != null){
                                        request.AmountLocalForCollection__c = request.AmountLocalForCollection__c == null? 0 : request.AmountLocalForCollection__c;
                                        request.AmountLocalForCollection__c += (Decimal)result.get('AmountLocalForCollection');
                                    }

                                    if(result.get('AmountUSDForCollection') != null){
                                        request.AmountUSDForCollection__c = request.AmountUSDForCollection__c == null? 0 : request.AmountUSDForCollection__c;
                                        request.AmountUSDForCollection__c += (Decimal)result.get('AmountUSDForCollection');
                                    }
                            }
                            if(result.get('PaymentTo') != null && request.InvoiceTo__c == (String)result.get('PaymentTo')){
                                    if(result.get('AmountLocal') != null){
                                        request.AmountLocalForCollection__c = request.AmountLocalForCollection__c == null? 0 : request.AmountLocalForCollection__c;
                                        request.AmountLocalForCollection__c -= (Decimal)result.get('AmountLocal');
                                    }

                                    if(result.get('AmountUSD') != null){
                                        request.AmountUSDForCollection__c = request.AmountUSDForCollection__c == null? 0 : request.AmountUSDForCollection__c;
                                        request.AmountUSDForCollection__c -= (Decimal)result.get('AmountUSD');
                                    }
                            } 
                        }

                        if(!String.isBlank(request.PaymentTo__c)){
                            if(result.get('PaymentTo') != null && request.PaymentTo__c == (String)result.get('PaymentTo')){
                                if(result.get('AmountLocal') != null){
                                    request.AmountLocal__c = request.AmountLocal__c == null? 0 : request.AmountLocal__c;
                                    request.AmountLocal__c += (Decimal)result.get('AmountLocal');
                                }

                                if(result.get('AmountUSD') != null){
                                    request.AmountUSD__c = request.AmountUSD__c == null? 0 : request.AmountUSD__c;
                                    request.AmountUSD__c += (Decimal)result.get('AmountUSD');
                                }
                            }
                            if(result.get('InvoiceTo') != null && request.PaymentTo__c == (String)result.get('InvoiceTo')){
                                    if(result.get('AmountLocalForCollection') != null){
                                        request.AmountLocal__c = request.AmountLocal__c == null? 0 : request.AmountLocal__c;
                                        request.AmountLocal__c -= (Decimal)result.get('AmountLocalForCollection');
                                    }

                                    if(result.get('AmountUSDForCollection') != null){
                                        request.AmountUSD__c = request.AmountUSD__c == null? 0 : request.AmountUSD__c;
                                        request.AmountUSD__c -= (Decimal)result.get('AmountUSDForCollection');
                                    }
                            }
                        }
                    }
                }
            }

            FlsService.doUpdate(mapPaymentRequest.values());
        }catch(Exception ex){
            lisBillReqOld[0].addError(ex.getMessage());
        }

    }
}