force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/TaxInitial__c.field-meta.xml
<CustomField>
    <fullName>TaxInitial__c</fullName>
    <defaultValue>0</defaultValue>
    <description>管理者コメント
2013/09/02
本来はレコード作成時にデフォルトで「0.05」の値を持ち、数式「TaxShow__c」に値を渡して金額系の計算をしていた。
しかし、この項目を普段の運用から手で入力したいとのこと。以下の変更を行う
・デフォルト値を空にする
・ワークフローで値を自動代入する（TaxDefaultの値）

2013/09/10
消費税率に販売用と仕入れ用が必要になるため（例）仕入は免税・販売は課税など
こちらの項目は販売用とする。
【注意】消費税率(販売)のAPI名が
「SellTaxInitial__c」
「TaxInitial__c」な点に注意</description>
    <inlineHelpText>The consumption Tax Ratio will be input automatically when remain Empty. Input the Tax ratio and the amount of value will be changed to amount that included the Tax. For item that is Tax-free or non-Tax, the Tax Ratio will be set 0%.</inlineHelpText>
    <label>CONSUMPTION TAX RATIO-SELLING</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/INVOICING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS BILL+VAT</label>
    <nameField>
        <displayFormat>IV-{0000000}</displayFormat>
        <label>FMS BILL+VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/fields/INVOICING__c.field-meta.xml
<CustomField>
    <fullName>INVOICING__c</fullName>
    <inlineHelpText>Filter Type:Optional.
-Pricing:Active equals True</inlineHelpText>
    <label>INVOICING</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>AnkenMeisai__c.Tariff__r.ProductFlag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Filter Type:Optional.
-PRICING:ACTIVE equals True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False. 
VAT Invoice is approved and locked. Contact System Administrator to unlock VAT Invoice.</errorMessage>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VAT_INVOICE__c/fields/Number_of_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Invoicing__c</fullName>
    <label>Number of Invoicing</label>
    <summaryForeignKey>INVOICING_VAT__c.VAT_INVOICE__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/Selling_Tax_Ratio__c.field-meta.xml
<CustomField>
    <fullName>Selling_Tax_Ratio__c</fullName>
    <description>Hold the Selling Tax Ratio for attached INVOICING. Only INVOICING records with the same Selling Tax Ratio are allowed to attached to one VAT INVOICE</description>
    <inlineHelpText>Hold the Selling Tax Ratio for attached Invoicing. Only Invoicing records with the same Selling Tax Ratio are allowed to attached to one VAT Invoice</inlineHelpText>
    <label>Selling Tax Ratio</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/InvoicingVATTriggerHandler.cls
public with sharing class InvoicingVATTriggerHandler extends AbstractTriggerHandler {
    private Map<Id, VAT_INVOICE__c> mapVATInvoices = new Map<Id, VAT_INVOICE__c>();
    private Map<Id, AnkenMeisai__c> mapHBLSB = new Map<Id, AnkenMeisai__c>();
    private Set<VAT_INVOICE__c> toBeUpdatedVATInvoices = new Set<VAT_INVOICE__c>();
    private static TranslationService translationService = new TranslationService('VAT_Invoice', UserInfo.getLanguage());
    
    public override void bulkBefore() {
        loadVATInvoices(Trigger.new);
    }
    
    public override void beforeInsert(SObject so) {
        INVOICING_VAT__c iv = (INVOICING_VAT__c) so;
        // disable checking same tax ratio in invoice
        //if (!isAcceptedInvoicing(iv)) {
        //    return;
        //}
    } 
    
    public override void beforeUpdate(SObject oldSo, SObject so) {
        INVOICING_VAT__c iv = (INVOICING_VAT__c) so;
        // disable checking same tax ratio in invoice
        //if (!isAcceptedInvoicing(iv)) {
        //    return;
        //}
    }
    
    public override void andFinally() {
        if (!toBeUpdatedVATInvoices.isEmpty()) {
            FlsService.doUpdate(new List<VAT_INVOICE__c>(toBeUpdatedVATInvoices));
        }
    }
    // disable checking same tax ratio in invoice
    /*private boolean isAcceptedInvoicing(INVOICING_VAT__c iv) {
        VAT_INVOICE__c vatInvoice = mapVATInvoices.get(iv.VAT_INVOICE__c);
        AnkenMeisai__c hblsb = mapHBLSB.get(iv.INVOICING__c);
        
        if (vatInvoice.Number_of_Invoicing__c == null || vatInvoice.Number_of_Invoicing__c == 0) {
            vatInvoice.Selling_Tax_Ratio__c = hblsb.TaxInitial__c;
            toBeUpdatedVATInvoices.add(vatInvoice);
            return true;
        } else if (vatInvoice.Selling_Tax_Ratio__c == hblsb.TaxInitial__c) {
            return true;
        }
        
        final String errorMessage = translationService.getTranslation('DIFF_TAX_RATIO');
        final List<String> fillers = new List<String>{String.valueOf(hblsb.TaxInitial__c), String.valueOf(vatInvoice.Selling_Tax_Ratio__c)};
        iv.addError(String.format(errorMessage, fillers));
        return false;
    }*/
	
    private void loadVATInvoices(List<INVOICING_VAT__c> ivs) {
        Set<Id> vatInvoiceIds = new Set<Id>();
        Set<Id> hblsbIds = new Set<Id>();
        
        for (INVOICING_VAT__c iv : ivs) {
            vatInvoiceIds.add(iv.VAT_INVOICE__c);
            hblsbIds.add(iv.INVOICING__c);
        }
        
        mapVATInvoices = new Map<Id, VAT_INVOICE__c>([SELECT Id, Selling_Tax_Ratio__c, Number_of_Invoicing__c FROM VAT_INVOICE__c WHERE Id IN :vatInvoiceIds]);
        mapHBLSB = new Map<Id, AnkenMeisai__c>([SELECT Id, TaxInitial__c FROM AnkenMeisai__c WHERE Id IN :hblsbIds]);
    }
}