force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/Anken__c.field-meta.xml
<CustomField>
    <fullName>Anken__c</fullName>
    <label>H B/L SHIPMENT ID</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>Anken</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyAmountJPN__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountJPN__c</fullName>
    <formula>ROUND(Suryo__c * BuyTankaJPY__c,0) + TotalAmountofBuyingLocalAdjust__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of Buying(Local)=Unit Price of Buying(Local)*Charge Unit (Total). This amount is before tax. If Tax-free or Non-tax, Total Amount of Buying(Local) will be equal to Amount Buying including Tax(Local).</inlineHelpText>
    <label>TOTAL AMOUNT OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>BuyDifferentiation__c</fullName>
    <formula>BuyInTaxAmountJPY__c - Siharaigaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Buying(Local)=Amount Buying including Tax(Local)-Amount Paid-Buying(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF BUYING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyInTaxAmountJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyInTaxAmountJPY__c</fullName>
    <description>IF (Tariff__r.wkTaxFlag__c, 
BuyAmountJPN__c * (1 + BuyTaxInitial__c), 
BuyAmountJPN__c 
)</description>
    <formula>BuyAmountJPN__c + BuyTaxNum__c + AmountBuyingLocalAdjustment__c
/* till Jan 4 , 2019
clofor_com_cfs__BuyAmountJPN__c * (1 + clofor_com_cfs__BuyTaxInitial__c) + clofor_com_cfs__TAX_ADJUSTMENT__c



※注意※
仕入金額に関してはこの計算
（レート*数量*USD単価）を適用しない
下記計算を備忘録として残す。

IF( TEXT(curr__c) = &apos;JPY&apos;,
ROUND(BuyAmountJPN__c * (1 + BuyTaxInitial__c) , 0 ),
ROUND( BuyTankaUSD__c * Suryo__c * KawaseBay__c , 0)
)

*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The amount will be calculated as Total Amount of Buying(Local)+Total Amount of Buying(Local)*Tax Ratio</inlineHelpText>
    <label>AMOUNT BUYING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTaxNum__c.field-meta.xml
<CustomField>
    <fullName>BuyTaxNum__c</fullName>
    <formula>ROUND(BuyAmountJPN__c * BuyTaxInitial__c,0) + TAX_ADJUSTMENT__c
/*
IF (clofor_com_cfs__Tariff__r.clofor_com_cfs__wkTaxFlag__c,
clofor_com_cfs__BuyAmountJPN__c * clofor_com_cfs__BuyTaxInitial__c + clofor_com_cfs__TAX_ADJUSTMENT__c ,
0
)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Amount of Tax-Buying(Local)=Total Amount of Buying(Local)*Consumption Tax Ratio-Buying(Local)/100. ***Comsumption Tax Ratio-Buying Field shows percentage. **</inlineHelpText>
    <label>AMOUNT OF TAX-BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/InsatuyouSyohin__c.field-meta.xml
<CustomField>
    <fullName>InsatuyouSyohin__c</fullName>
    <inlineHelpText>Used for Invoice and Quotation for local customers. If this field is blank, it will refer the Service Name At Print(Local) in Service Master Object</inlineHelpText>
    <label>PRICING NAME AT PRINT(LOCAL)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Invoiceto_type__c.field-meta.xml
<CustomField>
    <fullName>Invoiceto_type__c</fullName>
    <formula>text(Seikyusaki__r.Custom_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CATEGORY OF INVOICE TO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SalesAccountedDate__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDate__c</fullName>
    <formula>Anken__r.SalesAccountedDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Accounted Date(will be deleted)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Seikyusaki__c.field-meta.xml
<CustomField>
    <fullName>Seikyusaki__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Export and Not EXW--&gt;Set shipper
Export and EXW--&gt;Set Partner
Import and Not DDP/DDU--&gt;Set Consignee
Import &amp; DDP/DDU--&gt;Set Partner</inlineHelpText>
    <label>INVOICE TO</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerB2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS BILL (INVOICE TO)</relationshipLabel>
    <relationshipName>Seikyusakis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellAmountJPN__c.field-meta.xml
<CustomField>
    <fullName>SellAmountJPN__c</fullName>
    <formula>ROUND(Suryo__c * SellTankaJPY__c ,0)+ TotalAmountofSellingLocalAdjust__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of Selling(Local)=Unit Price of Selling(Local)*Charge Unit (Total). This amount is before Tax.If Tax-Free or Non-Tax, Total Amount of Selling(Local) will be equal to Amount Selling including Tax(Local).</inlineHelpText>
    <label>TOTAL AMOUNT OF SELLING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>SellDifferentiation__c</fullName>
    <formula>SellInTaxAmountJPY__c - Nyukingaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Selling(Local)=Amount Selling including Tax(Local)-Amount Paid-Selling(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF SELLING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellInTaxAmountJPY__c.field-meta.xml
<CustomField>
    <fullName>SellInTaxAmountJPY__c</fullName>
    <description>[通貨：JPY]
「商品」の「課税」にチェックが入っている時のみ消費税込みで計算します。

[通貨：USD]
販売単価(USD)*数量*為替レート（Selling）の結果を四捨五入しています

IF (Tariff__r.wkTaxFlag__c, 
     SellAmountJPN__c  *  (1 + TaxInitial__c), 
     SellAmountJPN__c 
)

/----------------------------------------------


ROUND(SellAmountJPN__c  *  (1 + TaxInitial__c) , 0)</description>
    <formula>SellAmountJPN__c + SellTaxNum__c +AmountSellingLocalAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The amount will be calculated as Total Amount of Selling(Local)+Total Amount of Selling(Local)*Tax Ratio</inlineHelpText>
    <label>AMOUNT SELLING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellTaxNum__c.field-meta.xml
<CustomField>
    <fullName>SellTaxNum__c</fullName>
    <formula>ROUND(SellAmountJPN__c * TaxInitial__c,0)+ TAX_ADJUSTMENTSELL__c
/*
IF (clofor_com_cfs__Tariff__r.clofor_com_cfs__wkTaxFlag__c,
clofor_com_cfs__SellAmountJPN__c * clofor_com_cfs__TaxInitial__c+clofor_com_cfs__TAX_ADJUSTMENTSELL__c,
0
)
*/

/*
IF (clofor_com_cfs__Tariff__r.clofor_com_cfs__wkTaxFlag__c,
FLOOR(clofor_com_cfs__SellAmountJPN__c * clofor_com_cfs__TaxInitial__c+clofor_com_cfs__TAX_ADJUSTMENTSELL__c),
0
)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Amount of Tax-Selling(Local)=Total Amount of Selling(Local)*Consumption Tax Ratio-Selling(Local)/100 . ***Consumption Tax Ratio-Selling Field shows percentage. **</inlineHelpText>
    <label>AMOUNT OF TAX-SELLING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SiharaisakiSyubetu__c.field-meta.xml
<CustomField>
    <fullName>SiharaisakiSyubetu__c</fullName>
    <formula>text(PaymentTo__r.Custom_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CATEGORY OF PAYMENT TO-BUYING</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Tariff__c.field-meta.xml
<CustomField>
    <fullName>Tariff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Service: Active status equals True</inlineHelpText>
    <label>PRICING NAME</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TariffMaster__c.ProductFlag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Service: Active status equals True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>TariffMaster__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>Tariff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/SalesAccountedDate__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDate__c</fullName>
    <description>SALES ACCOUNTED DATE</description>
    <inlineHelpText>When any of following date is input, the latest date is selected as sales accounted date. 
Import – Shipment Order: ETA, C.Clearance:Permit Date, Delivery:Delivery Date. 
Export- Delivery:Delivery Date, C.Clearance:Permit Date, Shipment Order:ETD.</inlineHelpText>
    <label>SALES ACCOUNTED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/recordTypes/Bulk.recordType-meta.xml
<RecordType>
    <fullName>Bulk</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with bulk cargos.</description>
    <label>BULK</label>
</RecordType>

force-app/main/default/classes/BBCCFeeInvoiceReportDetailController.cls
public with sharing class BBCCFeeInvoiceReportDetailController {
    public String partnerName {get;set;}
    public Date currentDate {get;set;}
    public Map<String,BBCCReportWrapper> mapBBCC {get;set;}
    public List<BBCCReportWrapper> lstBBCC {get;set;}
    public String message {get;set;}
    public Decimal totalSellInTaxAmount {get;set;}
    public Decimal totalSellTax {get;set;}
    public Decimal totalSellAmount {get;set;}
    private static List<String> selectFields = new List<String>();
    
    static {
		selectFields.add('Id');
        selectFields.add('Name');
        selectFields.add('Seikyusaki__r.Name');
        selectFields.add('SellInTaxAmountJPY__c');
        selectFields.add('SellDifferentiation__c');
        selectFields.add('SellAmountJPN__c');
        selectFields.add('Anken__r.Break_Bulk_Agent__r.Name');
        selectFields.add('SellTaxNum__c');
        selectFields.add('BuyAmountJPN__c');
        selectFields.add('BuyTaxNum__c');
        selectFields.add('BuyInTaxAmountJPY__c');
        selectFields.add('BuyDifferentiation__c');
    }
    
    public BBCCFeeInvoiceReportDetailController() {
        message = '';
        totalSellTax = 0;
        totalSellInTaxAmount = 0;
        totalSellAmount = 0;
        currentDate = Date.today();
        mapBBCC = new Map<String,BBCCReportWrapper>();
        lstBBCC = new List<BBCCReportWrapper>();
        
        partnerName = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('partnerName'), 'UTF-8'));
        String fromDate = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('fromDate'));
        String toDate = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('toDate'));
        String soqlComm = generateSOQL(toDate, fromDate, partnerName);

        if (PermissionValidationUtil.isAccessibleAccount() && PermissionValidationUtil.isAccessibleHBL() 
            && PermissionValidationUtil.isAccessibleHBLBuying() && PermissionValidationUtil.isAccessibleServiceMaster()) {
            List<AnkenMeisai__c> lstAKM = Database.query(soqlComm);
            
            if (!lstAKM.isEmpty()) {
                collectReportData(lstAKM);
            } else {
                message = 'There is no data collected from the database';
            }
        } else {
            message = 'Insufficient Permissions';
        }
    }
    
    private void collectReportData(List<AnkenMeisai__c> lstAKM) {
        for (AnkenMeisai__c item : lstAKM) {
            Decimal diff = (item.SellDifferentiation__c == null ? 0 : item.SellDifferentiation__c) - (item.BuyDifferentiation__c == null ? 0 : item.BuyDifferentiation__c);
            BBCCReportWrapper wrapper = new BBCCReportWrapper(item.Seikyusaki__r.Name, diff, 1);
            
            if (!mapBBCC.containsKey(wrapper.invoiceName)) {
                mapBBCC.put(wrapper.invoiceName,wrapper);
            }
            else {
                mapBBCC.get(wrapper.invoiceName).recordCount += 1;
                mapBBCC.get(wrapper.invoiceName).totalBalance += diff;
            }
            
            totalSellTax += (item.SellTaxNum__c == null ? 0 : item.SellTaxNum__c) - (item.BuyTaxNum__c == null ? 0 : item.BuyTaxNum__c);
            totalSellInTaxAmount += (item.SellInTaxAmountJPY__c == null ? 0 : item.SellInTaxAmountJPY__c) - (item.BuyInTaxAmountJPY__c == null ? 0 : item.BuyInTaxAmountJPY__c);
            totalSellAmount += (item.SellAmountJPN__c == null ? 0 : item.SellAmountJPN__c) - (item.BuyAmountJPN__c == null ? 0 : item.BuyAmountJPN__c);
        }
        
        if (!mapBBCC.isEmpty()) {
            Integer i = 1;
            
            for(BBCCReportWrapper item : mapBBCC.values()) {
                item.index = i;
                lstBBCC.add(item); 
                i++;
            } 
        }
    }
    
    private String generateSOQL(String toDate,String fromDate,String partnerName) {
        String soqlComm = 'SELECT ' + String.join(selectFields, ',') + 
            ' FROM AnkenMeisai__c' +
            ' WHERE ((Invoiceto_type__c = \'' + PicklistReference.THIRD_VENDOR_BB_CUSTOMERS_CLEARANCE 
            	+ '\' AND SellDifferentiation__c != 0) ' 
            	+ 'OR (SiharaisakiSyubetu__c = \'' + PicklistReference.THIRD_VENDOR_BB_CUSTOMERS_CLEARANCE 
            	+ '\' AND BuyDifferentiation__c != 0 AND ' 
            	+ '(InsatuyouSyohin__c LIKE \'%Break Bulk Fee%\' OR InsatuyouSyohin__c = \'CC FEE\' ' 
            	+ 'OR Tariff__r.Name LIKE \'%写真%\')))';     
        
        String filter = '';
        
        if (partnerName != null && !String.isEmpty(partnerName)) {
            filter = ' AND Seikyusaki__r.Name = \'' + partnerName + '\' ';
        }
        
        if (fromDate != null && toDate != null) {
            filter += ' AND (Anken__r.SalesAccountedDate__c >= ' + fromDate;
            filter += ' AND Anken__r.SalesAccountedDate__c <= ' + toDate + ')';
        }
        else if (fromDate != null && toDate == null) {
            filter += ' AND Anken__r.SalesAccountedDate__c >= ' + fromDate ;
        }
        else if (fromDate == null && toDate != null) {
            filter += ' AND Anken__r.SalesAccountedDate__c <= ' + toDate ;
        }
        
        if (!String.isEmpty(filter)) {
            soqlComm += filter;
        }
        
        return soqlComm;
    }
    
    public class BBCCReportWrapper {
        public String invoiceName {get;set;}
        public Integer recordCount {get;set;}    
        public Integer index {get;set;}
        public Decimal totalBalance {get;set;}
        
        public BBCCReportWrapper(String invoiceName, Decimal sellDifferentiation, Integer recordCount) {
			this.index = 0;
			this.invoiceName = invoiceName;
            this.recordCount = recordCount;
            this.totalBalance = sellDifferentiation;
		}
    }
}