force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/VAT_INVOICE_ISSUE_STATUS__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE_ISSUE_STATUS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This field can be modified by below 3 profiles.
-Accountant
-Top Executive
-System Administrator</inlineHelpText>
    <label>SELLING LOCK AFTER VAT INVOICE ISSUE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/INVOICING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS BILL+VAT</label>
    <nameField>
        <displayFormat>IV-{0000000}</displayFormat>
        <label>FMS BILL+VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/fields/INVOICING__c.field-meta.xml
<CustomField>
    <fullName>INVOICING__c</fullName>
    <inlineHelpText>Filter Type:Optional.
-Pricing:Active equals True</inlineHelpText>
    <label>INVOICING</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>AnkenMeisai__c.Tariff__r.ProductFlag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Filter Type:Optional.
-PRICING:ACTIVE equals True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False. 
VAT Invoice is approved and locked. Contact System Administrator to unlock VAT Invoice.</errorMessage>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/VAT_Running_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Running_Number__c</fullName>
    <label>VAT Running Number</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VAT_INVOICE__c/fields/APPROVED_AND_LOCK__c.field-meta.xml
<CustomField>
    <fullName>APPROVED_AND_LOCK__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Once the Approval request approved by Approver, the check box will be checked.</inlineHelpText>
    <label>APPROVED AND LOCK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/RED_INVOICE_NO__c.field-meta.xml
<CustomField>
    <fullName>RED_INVOICE_NO__c</fullName>
    <label>RED INVOICE NO</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/VAT_INVOICE_ISSUE_STATUS__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE_ISSUE_STATUS__c</fullName>
    <label>VAT INVOICE ISSUE STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft VAT Sent</fullName>
            </value>
            <value>
                <fullName>Draft VAT Received</fullName>
            </value>
            <value>
                <fullName>Draft VAT Confirmed</fullName>
            </value>
            <value>
                <fullName>Original VAT Sent</fullName>
            </value>
            <value>
                <fullName>Original VAT Received</fullName>
            </value>
            <value>
                <fullName>Original VAT Mistaken</fullName>
            </value>
            <value>
                <fullName>Original VAT Returned</fullName>
            </value>
            <value>
                <fullName>Original VAT Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VATInvoiceTriggerHandler.cls
public with sharing class VATInvoiceTriggerHandler extends AbstractTriggerHandler {
    private Set<CustomObject1__c> toBeUpdatedHBLs = new Set<CustomObject1__c>();
    private Site_Custom_Settings__c settings = null;
    private Set<AnkenMeisai__c> toBeUpdateHBLSBs = new Set<AnkenMeisai__c>();
    private Map<Id, List<AnkenMeisai__c>> vatToHBLSB;
    
    public override String getHandlerName() {
        return 'VATInvoiceTriggerHandler';
    }
    
    public override void bulkAfter() {
        if (Trigger.isUpdate) {
            loadHBLSB(Trigger.new);           
        }
    }
    
    public override void beforeInsert(SObject so) {
        VAT_INVOICE__c invoice = (VAT_INVOICE__c) so;
        //Integer nextRunningNumber = getNextVATRunningNumber();
        //String vatRunningNumber = StringUtils.prependZerosToNumber(nextRunningNumber, Constants.RUNNING_NUMBER_LENGTH);
        //invoice.RED_INVOICE_NO__c = vatRunningNumber;
    }
        
    public override void afterUpdate(SObject old, SObject so) {
        VAT_INVOICE__c invoice = (VAT_INVOICE__c) so;
        syncIssueStatusToHBLSB(invoice);
    }
    
    public override void andFinally() {
        if (!toBeUpdatedHBLs.isEmpty()) {
            try {
                FlsService.doUpdate(new List<CustomObject1__c>(toBeUpdatedHBLs));
            } catch(Exception e) {
            }
        }
        
        if (Trigger.isUpdate && !toBeUpdateHBLSBs.isEmpty()) {
            try {
                FlsService.doUpdate(new List<AnkenMeisai__c>(toBeUpdateHBLSBs));
            } catch(Exception e) {
            }
        }
        
        if (settings != null) {
            FlsService.doUpdate(settings);
        }
    }
    
    private void syncIssueStatusToHBLSB(VAT_INVOICE__c invoice) {
        if (invoice.APPROVED_AND_LOCK__c && (vatToHBLSB != null && vatToHBLSB.containsKey(invoice.Id))) {
            List<AnkenMeisai__c> hblsbs = vatToHBLSB.get(invoice.Id);
            for (AnkenMeisai__c hblsb : hblsbs) {
                hblsb.VAT_INVOICE_ISSUE_STATUS__c = true;
                toBeUpdateHBLSBs.add(hblsb);
            }
        }
    }
    
    private void loadHBLSB(List<VAT_INVOICE__c> invoices) {
        Set<Id> hblsbIds = new Set<Id>();
        Set<Id> vatInvoiceIds = new Set<id>();

        for (VAT_INVOICE__c vi : invoices) {
            if (vi.Id != null && vi.APPROVED_AND_LOCK__c) {
            	vatInvoiceIds.add(vi.Id);    
            }
        }
        
		List<INVOICING_VAT__c> invoicingVATs = [SELECT Invoicing__c, VAT_INVOICE__c FROM INVOICING_VAT__c WHERE VAT_INVOICE__c IN :vatInvoiceIds];
        Map<Id, Id> invoicingToVAT = new Map<Id, Id>();
        if (invoicingVATs != null && !invoicingVATs.isEmpty()) {
            for (INVOICING_VAT__c iv : invoicingVATs) {
                hblsbIds.add(iv.Invoicing__c);
                invoicingToVAT.put(iv.Invoicing__c, iv.VAT_INVOICE__c);
            }
        }
        List<AnkenMeisai__c> lstHBLSBs = [SELECT Id, VAT_INVOICE_ISSUE_STATUS__c FROM AnkenMeisai__c WHERE Id IN :hblsbIds AND VAT_INVOICE_ISSUE_STATUS__c = False];
        vatToHBLSB = new Map<Id, List<AnkenMeisai__c>>();
        for (AnkenMeisai__c hblsb : lstHBLSBs) {
            Id invoicingVATId = invoicingToVAT.get(hblsb.Id);
            
            if (vatToHBLSB.containsKey(invoicingVATId)) {
                vatToHBLSB.get(invoicingVATId).add(hblsb);
            } else {
                List<AnkenMeisai__c> lst = new List<AnkenMeisai__c>();
                lst.add(hblsb);
                vatToHBLSB.put(invoicingVATId, lst);
            }
        }
    }
    
    private Integer getNextVATRunningNumber() {
        settings = Site_Custom_Settings__c.getOrgDefaults();
        Integer nextRunningNumber = null;
        
        if (settings.VAT_Running_Number__c == null) {
            nextRunningNumber = 1;
        } else {
            nextRunningNumber = (Integer)settings.VAT_Running_Number__c;
        }
        
        settings.VAT_Running_Number__c = settings.VAT_Running_Number__c == Constants.MAX_VAT_RUNNING_NUMBER ? 1 : nextRunningNumber + 1;
        FlsService.doupdate (settings);
        return nextRunningNumber;
    }
}