force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/AM_BuyInAfter_allocation__c.field-meta.xml
<CustomField>
    <fullName>AM_BuyInAfter_allocation__c</fullName>
    <formula>IF( OR(AM_MCBM__c = 0, ISBLANK(AM_MCBM__c)) , 0, (AM_BuyInBefore_Allocation__c * ANKEN_CBM__c) / AM_MCBM__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BUYING AFTER ALLOCATION-CHECKING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/AM_BuyInAfter_allocation_USD__c.field-meta.xml
<CustomField>
    <fullName>AM_BuyInAfter_allocation_USD__c</fullName>
    <formula>IF( OR(AM_MCBM__c = 0, ISBLANK(AM_MCBM__c)) , 0, (AM_Buyinbefore_allocation_USD__c * ANKEN_CBM__c) / AM_MCBM__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BUYING AFTER ALLOCATION-CHECKING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/AM_MasterMeisaiID__c.field-meta.xml
<CustomField>
    <fullName>AM_MasterMeisaiID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Input the M B/L Buying ID corresponds with cost allocation category</inlineHelpText>
    <label>CONSOL SHIPMENT BUYING ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AM_MasterID__c</field>
            <operation>equals</operation>
            <valueField>MasterAnkenMeisai__c.MasterAnken__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MasterAnkenMeisai__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>AM_MasterMeisaiID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyAmountJPN__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountJPN__c</fullName>
    <formula>ROUND(Suryo__c * BuyTankaJPY__c,0) + TotalAmountofBuyingLocalAdjust__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of Buying(Local)=Unit Price of Buying(Local)*Charge Unit (Total). This amount is before tax. If Tax-free or Non-tax, Total Amount of Buying(Local) will be equal to Amount Buying including Tax(Local).</inlineHelpText>
    <label>TOTAL AMOUNT OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountUSD__c</fullName>
    <formula>ROUND(Suryo__c * BuyTankaUSD__c,3) +TotalAmountofBuyingFCYAdjust__c
/*
clofor_com_cfs__Suryo__c * if( ISNULL(clofor_com_cfs__BuyTankaUSD__c), 0, clofor_com_cfs__BuyTankaUSD__c ) + clofor_com_cfs__Cost_Allocation_Margin_USD__c
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of Selling(FCY)=Unit Price of Selling(Local)*Charge Unit (Total).</inlineHelpText>
    <label>TOTAL AMOUNT OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyInTaxAmountJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyInTaxAmountJPY__c</fullName>
    <description>IF (Tariff__r.wkTaxFlag__c, 
BuyAmountJPN__c * (1 + BuyTaxInitial__c), 
BuyAmountJPN__c 
)</description>
    <formula>BuyAmountJPN__c + BuyTaxNum__c + AmountBuyingLocalAdjustment__c
/* till Jan 4 , 2019
clofor_com_cfs__BuyAmountJPN__c * (1 + clofor_com_cfs__BuyTaxInitial__c) + clofor_com_cfs__TAX_ADJUSTMENT__c



※注意※
仕入金額に関してはこの計算
（レート*数量*USD単価）を適用しない
下記計算を備忘録として残す。

IF( TEXT(curr__c) = &apos;JPY&apos;,
ROUND(BuyAmountJPN__c * (1 + BuyTaxInitial__c) , 0 ),
ROUND( BuyTankaUSD__c * Suryo__c * KawaseBay__c , 0)
)

*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The amount will be calculated as Total Amount of Buying(Local)+Total Amount of Buying(Local)*Tax Ratio</inlineHelpText>
    <label>AMOUNT BUYING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaJPY__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input. 1. It will refer the amount in Unit Price of Buying(Local) in Service Master Object. 2. If not, take the amount =Unit Price of Buying(USD)×Exchange Rate-Buying</inlineHelpText>
    <label>UNIT PRICE OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTankaUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaUSD__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input. 1. It will refer the amount in Unit Price of Buying(FCY) in Service Master Object. 2. If not, take the amount =Unit Price of Buying(Local)/Exchange Rate-Buying.</inlineHelpText>
    <label>UNIT PRICE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Cost_Allocation_Margin__c.field-meta.xml
<CustomField>
    <fullName>Cost_Allocation_Margin__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Use to add/deduct when Total of Unit Price of Buying is different from Total Buying After Allocation-Checking</description>
    <label>Cost Allocation Margin</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Cost_Allocation_Margin_USD__c.field-meta.xml
<CustomField>
    <fullName>Cost_Allocation_Margin_USD__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Use to add/deduct when Total of Unit Price of Buying is different from Total Buying After Allocation-Checking</description>
    <label>Cost Allocation Margin USD</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Suryo__c.field-meta.xml
<CustomField>
    <fullName>Suryo__c</fullName>
    <inlineHelpText>Multiplied to Unit Price of Selling(Buying) and automatically calculates Total Amount of Selling(Buying).</inlineHelpText>
    <label>CHARGE UNIT (TOTAL)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/MasterAnken__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLOnlineHelp</customHelpPage>
    <description>M B/L - SHIPMENTS</description>
    <label>混載</label>
    <nameField>
        <label>MASTER SHIPMENT NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnkenMeisai__c/MasterAnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLBUYINGOnlineHelp</customHelpPage>
    <description>M B/L - BUYING</description>
    <label>混載-請求・仕入</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>M B/L BUYING ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyAmountJPN__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountJPN__c</fullName>
    <formula>Suryo__c *  BuyTankaJPY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL AMOUNT OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountUSD__c</fullName>
    <formula>Suryo__c *  BuyTankaUSD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL AMOUNT OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyInTaxAmountJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyInTaxAmountJPY__c</fullName>
    <description>IF (MTariff__r.wkTaxFlag__c,
BuyAmountJPN__c * (1 + BuyTaxInitial__c),
BuyAmountJPN__c
)</description>
    <formula>BuyTaxNum__c + ROUND(BuyAmountJPN__c ,0)</formula>
    <label>AMOUNT BUYING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaJPY__c</fullName>
    <label>UNIT PRICE OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyTankaUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaUSD__c</fullName>
    <label>UNIT PRICE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/MasterAnken__c.field-meta.xml
<CustomField>
    <fullName>MasterAnken__c</fullName>
    <label>MASTER SHIPMENT NAME</label>
    <referenceTo>MasterAnken__c</referenceTo>
    <relationshipName>MasterAnken</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/Suryo__c.field-meta.xml
<CustomField>
    <fullName>Suryo__c</fullName>
    <defaultValue>1</defaultValue>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CostAllocationService.cls
global with sharing class CostAllocationService {
    private static TranslationService translationService = new TranslationService('COST_ALLOCATION', UserInfo.getLanguage());
    
    webservice static String balanceCostAllocation(String masterShipmentId) {
        String infoMessage = translationService.getTranslation('COST_ALLOCATION_MSG'); 
        
        if (StringUtils.isEmpty(infoMessage)) {
        	infoMessage = 'Cost Allocation has been balanced successfully';    
        }
        
        masterShipmentId = StringUtils.escapeSingleQuotes(masterShipmentId);
        
        if (PermissionValidationUtil.isAccessibleMBLBuying() 
            	&& PermissionValidationUtil.isAccessibleHBLBuying() && PermissionValidationUtil.isEditableHBLBuying()) {
			List<MasterAnkenMeisai__c> mblBuyings = findMBLBuyingRecords(masterShipmentId);
            List<String> masterMeisaiIds = new List<String>();
            
            if (mblBuyings != null && mblBuyings.size() > 0) {
                for (MasterAnkenMeisai__c mm : mblBuyings) {
                    masterMeisaiIds.add(mm.Id);
                }
                
                List<AnkenMeisai__c> hblSellingBuyings = findHBLSellingBuyingRecords(masterMeisaiIds);
                
                /* 
			     * Make sure the following database operations are atomic transaction
				 */ 
                Savepoint sp = Database.setSavepoint();
                
                try {
                    // clear cost allocation margin
                    resetCostMargin(hblSellingBuyings);
                    
                    hblSellingBuyings = findHBLSellingBuyingRecords(masterMeisaiIds);
                    
                    resetUnitPrice(hblSellingBuyings);
                    
                    for (MasterAnkenMeisai__c mm : mblBuyings) {
                        balanceCostAllocation(mm, hblSellingBuyings);
                    }
                    
                    FlsService.doUpdate(hblSellingBuyings);
                } catch(Exception e) {                    
                    infoMessage = e.getMessage();
                    Database.rollback(sp);
                }
            }
		} else {
            infoMessage = translationService.getTranslation('INSUFFICIENT_PERMISSION');
            
            if (StringUtils.isEmpty(infoMessage)) {
                infoMessage = 'Insufficient permission.';                        
            }			
		}
        
        return infoMessage;
    }
    
    private static void resetCostMargin(List<AnkenMeisai__c> meisais) {
        List<AnkenMeisai__c> toBeUpdated = new List<AnkenMeisai__c>();
        
        for (AnkenMeisai__c meisai : meisais) {
            if ((meisai.Cost_Allocation_Margin__c != null && meisai.Cost_Allocation_Margin__c != 0)
                || (meisai.Cost_Allocation_Margin_USD__c != null && meisai.Cost_Allocation_Margin_USD__c != 0)) {
				meisai.Cost_Allocation_Margin__c = 0;	
				meisai.Cost_Allocation_Margin_USD__c = 0;
				toBeUpdated.add(meisai);
			}
        }
        
        if (toBeUpdated.size() > 0) {
            FlsService.doUpdate(toBeUpdated);
        }
    }
    
    private static void resetUnitPrice(List<AnkenMeisai__c> meisais) {
        for (AnkenMeisai__c meisai : meisais) {
            meisai.BuyTankaJPY__c = meisai.AM_BuyInAfter_allocation__c;
            meisai.BuyTankaUSD__c = meisai.AM_BuyInAfter_allocation_USD__c;
        }
    }
    
    private static void balanceCostAllocation(MasterAnkenMeisai__c masterMeisai, List<AnkenMeisai__c> meisais) {
        Double totalAmountBuyingIncludeTax = 0;
        Double totalAmountBuyingUSD = 0;
        AnkenMeisai__c toBeBalancedMeisai = null;
        
        for (AnkenMeisai__c meisai : meisais) {
            if (meisai.AM_MasterMeisaiID__c == masterMeisai.Id) {
                totalAmountBuyingIncludeTax += meisai.BuyTankaJPY__c * meisai.Suryo__c;//meisai.BuyInTaxAmountJPY__c;
                totalAmountBuyingUSD += meisai.BuyTankaUSD__c * meisai.Suryo__c;//meisai.BuyAmountUSD__c;
                
                if (toBeBalancedMeisai == null) {
	                toBeBalancedMeisai = meisai;    
                }
            }
        }
        
        if (toBeBalancedMeisai != null) {
            Double margin = 0;
            if (totalAmountBuyingUSD != masterMeisai.BuyAmountUSD__c) {
                margin = masterMeisai.BuyAmountUSD__c - totalAmountBuyingUSD;
                
                if (!(margin < 0 && margin > -0.5)) {
	                toBeBalancedMeisai.Cost_Allocation_Margin_USD__c = margin;    
                }
            }
            
            if (totalAmountBuyingIncludeTax != masterMeisai.BuyAmountJPN__c) {
                margin = masterMeisai.BuyAmountJPN__c - totalAmountBuyingIncludeTax;
                
                if (!(margin < 0 && margin > -0.5)) {
                	toBeBalancedMeisai.Cost_Allocation_Margin__c = margin;
                }
            }
        }        
    }
    
    private static List<MasterAnkenMeisai__c> findMBLBuyingRecords(String masterShipmentId) {
        List<MasterAnkenMeisai__c> masters = [SELECT Id, BuyAmountJPN__c, BuyAmountUSD__c, BuyInTaxAmountJPY__c
                                              FROM MasterAnkenMeisai__c 
                                              WHERE MasterAnken__c = :masterShipmentId];
        
        if (masters == null) {
            masters = new List<MasterAnkenMeisai__c>();
        }
        
        return masters;
    }
    
    private static List<AnkenMeisai__c> findHBLSellingBuyingRecords(List<String> masterMeisaiIds) {
        List<AnkenMeisai__c> meisais = [SELECT Id, Cost_Allocation_Margin__c, Cost_Allocation_Margin_USD__c,
                                        	AM_MasterMeisaiID__c, BuyInTaxAmountJPY__c, BuyAmountUSD__c,
                                        	BuyTankaJPY__c, BuyTankaUSD__c, BuyAmountJPN__c, Suryo__c,
                                        	AM_BuyInAfter_allocation__c, AM_BuyInAfter_allocation_USD__c
                                        FROM AnkenMeisai__c 
                                        WHERE AM_MasterMeisaiID__c IN :masterMeisaiIds 
                                        ORDER BY Id];
        
        if (meisais == null) {
            meisais = new List<AnkenMeisai__c>();
        }
        
        return meisais;
    }
}