force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/SalesAccountedDate__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDate__c</fullName>
    <formula>Anken__r.SalesAccountedDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Accounted Date(will be deleted)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/VAT_INVOICE_ISSUE_STATUS__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE_ISSUE_STATUS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This field can be modified by below 3 profiles.
-Accountant
-Top Executive
-System Administrator</inlineHelpText>
    <label>SELLING LOCK AFTER VAT INVOICE ISSUE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/VAT_INVOICE_TO__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE_TO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Choose Red Invoice To only when Red Invoice To is different from Invoice To.</inlineHelpText>
    <label>VAT INVOICE TO</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VATINVOICE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Cnee__c.field-meta.xml
<CustomField>
    <fullName>Cnee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cnee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL__c.field-meta.xml
<CustomField>
    <fullName>HBL__c</fullName>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/REFNO__c.field-meta.xml
<CustomField>
    <fullName>REFNO__c</fullName>
    <label>REF NO</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/SalesAccountedDate__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDate__c</fullName>
    <description>SALES ACCOUNTED DATE</description>
    <inlineHelpText>When any of following date is input, the latest date is selected as sales accounted date. 
Import – Shipment Order: ETA, C.Clearance:Permit Date, Delivery:Delivery Date. 
Export- Delivery:Delivery Date, C.Clearance:Permit Date, Shipment Order:ETD.</inlineHelpText>
    <label>SALES ACCOUNTED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/FORWARDING_VAT__c/FORWARDING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS S/O+VAT</label>
    <nameField>
        <displayFormat>FV-{0000000}</displayFormat>
        <label>CONNECT FORWARDING &amp; VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FORWARDING_VAT__c/fields/FORWARDING__c.field-meta.xml
<CustomField>
    <fullName>FORWARDING__c</fullName>
    <inlineHelpText>The user-entered value must match filter criteria.
- Record Type equal to Air Import/Export, Ocean Import/Export, Domestic Transportation, Cross-Border, Logistics Service.
- Cargo Status not equal to Cancelled, Completed.</inlineHelpText>
    <label>FORWARDING</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CustomObject1__c.status__c</field>
            <operation>notEqual</operation>
            <value>見積 受付済(Inquiry Received), 見積 見積書作成中(Under Quotation), 見積 見積書送付完了(Quotation Issued), 見積 見積書修正中(Under Quotation Revision), 見積 見積書再送付完了 (Quotation Reissued), キャンセル(Cancelled), 完了(Completed)</value>
        </filterItems>
        <filterItems>
            <field>CustomObject1__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Air Import, Air Export, Ocean Export, Ocean Import, Domestic Transportation, Cross-Boarder, Logistics Service</value>
        </filterItems>
        <infoMessage>The user-entered value must match filter criteria.
- Record Type equal to Air Import/Export, Ocean Import/Export, Domestic Transportation, Cross-Border, Logistics Service.
- Cargo Status not equal to Cancelled, Completed.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipLabel>F/TMS S/O+VAT</relationshipLabel>
    <relationshipName>Junction_Forwarding_VAT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FORWARDING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria.
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria.
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>Junction_Object_Forwarding_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/INVOICING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS BILL+VAT</label>
    <nameField>
        <displayFormat>IV-{0000000}</displayFormat>
        <label>FMS BILL+VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False. 
VAT Invoice is approved and locked. Contact System Administrator to unlock VAT Invoice.</errorMessage>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VAT_INVOICE__c/fields/AmountOfTaxVATBuying__c.field-meta.xml
<CustomField>
    <fullName>AmountOfTaxVATBuying__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AMOUNT OF TAX-VAT BUYING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/AmountOfTaxVATSelling__c.field-meta.xml
<CustomField>
    <fullName>AmountOfTaxVATSelling__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AMOUNT OF TAX-VAT SELLING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/AmountVATBuyingIncludeVAT__c.field-meta.xml
<CustomField>
    <fullName>AmountVATBuyingIncludeVAT__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AMOUNT VAT BUYING INCLUDE TAX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/AmountVATSellingIncludeVAT__c.field-meta.xml
<CustomField>
    <fullName>AmountVATSellingIncludeVAT__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AMOUNT VAT SELLING INCLUDE TAX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/RED_INVOICE_NO__c.field-meta.xml
<CustomField>
    <fullName>RED_INVOICE_NO__c</fullName>
    <label>RED INVOICE NO</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/TotalAmountOfVATBuying__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfVATBuying__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TOTAL AMOUNT OF VAT BUYING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/TotalAmountOfVATSelling__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfVATSelling__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TOTAL AMOUNT OF VAT SELLING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/VAT_INVOICE_ISSUE_STATUS__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE_ISSUE_STATUS__c</fullName>
    <label>VAT INVOICE ISSUE STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft VAT Sent</fullName>
            </value>
            <value>
                <fullName>Draft VAT Received</fullName>
            </value>
            <value>
                <fullName>Draft VAT Confirmed</fullName>
            </value>
            <value>
                <fullName>Original VAT Sent</fullName>
            </value>
            <value>
                <fullName>Original VAT Received</fullName>
            </value>
            <value>
                <fullName>Original VAT Mistaken</fullName>
            </value>
            <value>
                <fullName>Original VAT Returned</fullName>
            </value>
            <value>
                <fullName>Original VAT Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/VAT_INVOICE_TO__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE_TO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VAT INVOICE TO</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VAT_INVOICE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/VATInvoiceNoFromVendor__c.field-meta.xml
<CustomField>
    <fullName>VATInvoiceNoFromVendor__c</fullName>
    <label>VAT INVOICE NO FROM VENDOR</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/VATInvoicePrintDate__c.field-meta.xml
<CustomField>
    <fullName>VATInvoicePrintDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>VAT INVOICE ISSUE DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/fields/VatIssueFrom__c.field-meta.xml
<CustomField>
    <fullName>VatIssueFrom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VAT ISSUE FROM</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VatIssueFrom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/recordTypes/CloWMSVATInvoice.recordType-meta.xml
<RecordType>
    <fullName>CloWMSVATInvoice</fullName>
    <active>true</active>
    <description>To Issue VAT Invoice for CloWMS</description>
    <label>CloWMS VAT INVOICE</label>
</RecordType>

force-app/main/default/objects/VAT_INVOICE__c/recordTypes/FMSTMSWMSVATInvoice.recordType-meta.xml
<RecordType>
    <fullName>FMSTMSWMSVATInvoice</fullName>
    <active>true</active>
    <description>To Issue VAT Invoice for FMS/TMS and WMS together</description>
    <label>FMS/TMS+WMS VAT Invoice</label>
</RecordType>

force-app/main/default/objects/VAT_INVOICE__c/recordTypes/MULTIPLE_SHIPMENT_TO_1VAT_INVOICE_SUMMARY.recordType-meta.xml
<RecordType>
    <fullName>MULTIPLE_SHIPMENT_TO_1VAT_INVOICE_SUMMARY</fullName>
    <active>true</active>
    <description>To Issue VAT Invoice for FMS/TMS</description>
    <label>MULTIPLE SHIPMENT TO 1 VAT INVOICE-SUMMARY</label>
</RecordType>

force-app/main/default/objects/VAT_INVOICE__c/recordTypes/VendorVATInvoice.recordType-meta.xml
<RecordType>
    <fullName>VendorVATInvoice</fullName>
    <active>true</active>
    <description>To manage VAT from Vendors</description>
    <label>Vendor VAT Invoice</label>
</RecordType>

force-app/main/default/objects/VATPayReq__c/VATPayReq__c.object-meta.xml
<CustomObject>
    <label>VAT+TRX Plan</label>
    <nameField>
        <displayFormat>VIPR-{000000}</displayFormat>
        <label>VAT+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VAT+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VATPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>PaymentRequestID</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VATPayReq__c/fields/VATInvoiceID__c.field-meta.xml
<CustomField>
    <fullName>VATInvoiceID__c</fullName>
    <label>VAT INVOICE ID</label>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>VATInvoiceID</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassiveNewInvoiceTRSPlanController.cls
public with sharing class MassiveNewInvoiceTRSPlanController {
	public VAT_INVOICE__c objectSearch{get; set;}
	public String shipmentOrderId{get; set;}
	public String fmsBillId{get; set;}
	public String invoiceName{get;set;}
	public String invoiceType{get; set;}
	public CustomObject1__c shipmentOrderSearch{get; set;}
	public AnkenMeisai__c billSearch{get; set;}
	public String shipmentTimeType{get; set;}
	public String shipmentFromTime{get; set;}
	public String shipmentToTime{get; set;}
	public String shipmentCustomerName{get; set;}
	public List <VAT_INVOICE__c> VATListInbound{get; set;}
	public List <VAT_INVOICE__c> VATListOutbound{get; set;}
	public Boolean isInboundVAT{get; set;}
	private Map<String, String> mapVATType{get; set;}
	private static Set<String> vatIds{get; set;}
	private static Set<String> combinedVATIds{get; set;} 
	private static Set<String> fieldsQuery = new Set<String>();
	private String transactionPlanId{get;set;}
	private String conditionBill{get;set;}
	private String conditionSbipment{get;set;}
    public Map<String, String> mapLabelVatType{get; set;}
	public String tabNameSelect{get;set;}

	static{
		fieldsQuery.add('Id');
		fieldsQuery.add('RecordTypeId');
		fieldsQuery.add('RecordType.DeveloperName');
		fieldsQuery.add('RecordType.Name');
		fieldsQuery.add('Name');
		fieldsQuery.add('RED_INVOICE_NO__c');
		fieldsQuery.add('VAT_INVOICE_TO__c');
		fieldsQuery.add('VAT_INVOICE_TO__r.Name');
		fieldsQuery.add('VAT_INVOICE_ISSUE_STATUS__c');
		fieldsQuery.add('AmountOfTaxVATSelling__c');
		fieldsQuery.add('TotalAmountOfVATSelling__c');
		fieldsQuery.add('AmountVATSellingIncludeVAT__c');
		fieldsQuery.add('VatIssueFrom__c');
		fieldsQuery.add('VatIssueFrom__r.Name');
		fieldsQuery.add('TotalAmountOfVATBuying__c');
		fieldsQuery.add('AmountOfTaxVATBuying__c');
		fieldsQuery.add('AmountVATBuyingIncludeVAT__c');
		fieldsQuery.add('AccountedDate__c');
		fieldsQuery.add('VATInvoicePrintDate__c');
		fieldsQuery.add('VATInvoiceNoFromVendor__c');
	}
	public MassiveNewInvoiceTRSPlanController() {
		transactionPlanId = ApexPages.currentPage().getParameters().get('requestId');
        mapLabelVatType = new Map<String, String>();
        Map<String, Schema.RecordTypeInfo> mapInvoiceRecs = Schema.SObjectType.VAT_INVOICE__c.getRecordTypeInfosByDeveloperName();
		for(String developerName : mapInvoiceRecs.keySet()){
			Schema.RecordTypeInfo recInfo = mapInvoiceRecs.get(developerName);
			mapLabelVatType.put(developerName, recInfo.getName());	
		}
		init();
	}
	private void init(){
		conditionBill = '';
		conditionSbipment = '';
		
		shipmentOrderSearch = new CustomObject1__c();
		billSearch = new AnkenMeisai__c();
		objectSearch = new VAT_INVOICE__c();
		VATListInbound = new List <VAT_INVOICE__c>();
		VATListOutbound = new List <VAT_INVOICE__c>();

		isInboundVAT = false;
		vatIds = new Set<String>();
		combinedVATIds = new Set<String>();
		mapVATType = new Map<String, String>();

		mapVATType.put('VendorVATInvoice','Inbound');
		mapVATType.put('FMSTMSWMSVATInvoice','Outbound');
		mapVATType.put('CloWMSVATInvoice','Outbound');
		mapVATType.put('MULTIPLE_SHIPMENT_TO_1VAT_INVOICE_SUMMARY','Outbound');
		
		//get recordTypedetail
		PaymentRequest__c trxPlan = getTransactionPlanDetail(transactionPlanId);
		if(trxPlan.RecordType.developerName == 'PaymentRequestUSDCurrency'
			|| trxPlan.RecordType.developerName == 'PaymentRequestlocalCurrency'){
			isInboundVAT = true;
			invoiceType = 'VendorVATInvoice';
			tabNameSelect = 'VATInbound';
		}else{
			isInboundVAT = false;
			invoiceType = 'MULTIPLE_SHIPMENT_TO_1VAT_INVOICE_SUMMARY';
			tabNameSelect = 'VATOutbound';
		}
		getCombinedVATIds();
		String vatQuery = buildVATQuery();
		handleVATList(Database.query(vatQuery));
	}
	private PaymentRequest__c getTransactionPlanDetail(String planId){
		List<PaymentRequest__c> trxPlans = [SELECT Id, Name, RecordTypeId, RecordType.DeveloperName 
								FROM PaymentRequest__c
								WHERE Id =: planId];
		if(!trxPlans.isEmpty()){
			return trxPlans[0];
		}
		return new PaymentRequest__c();
	}
	public List<SelectOption> getInvoiceTypes(){
		List<SelectOption> options = new List<SelectOption>();
		Map<String, Schema.RecordTypeInfo> mapInvoiceRecs = Schema.SObjectType.VAT_INVOICE__c.getRecordTypeInfosByDeveloperName();
		for(String developerName : mapInvoiceRecs.keySet()){
			Schema.RecordTypeInfo recInfo = mapInvoiceRecs.get(developerName);
			if(recInfo.isActive() && developerName != 'Master'){
				options.add(new SelectOption(developerName, recInfo.getName()));
			}
		}
		return options;
	}
	public void doSearch(){
		combinedVATIds = new Set<String>();
		vatIds = new Set<String>();
		getCombinedVATIds();
		VATListInbound = new List <VAT_INVOICE__c>();
		VATListOutbound = new List <VAT_INVOICE__c>();
		if( mapVATType.get(invoiceType) == 'Inbound'){
			isInboundVAT = true;
		}
		// search shipment
		String shipmnetQuery = buildShipmentQuery();
		if(!String.isBlank(conditionSbipment)){
			List<FORWARDING_VAT__c> shipmentVATList = Database.query(shipmnetQuery);
			
			for(FORWARDING_VAT__c shipmentVAT : shipmentVATList){
				vatIds.add(shipmentVAT.VAT_INVOICE__c);
			}
		}
		
		// Search bill
		String billQuery = buildBillQuery();
		if(!String.isBlank(conditionBill)){
			
			List<INVOICING_VAT__c> billVATList = Database.query(billQuery);
			for(INVOICING_VAT__c billVAT : billVATList){
				vatIds.add(billVAT.VAT_INVOICE__c);
			}
		}
		// Search vat
		String vatQuery = buildVATQuery();
		List<VAT_INVOICE__c> VATList = Database.query(vatQuery);
		handleVATList(Database.query(vatQuery));
		
	}
	public void actionChangeTab(){
		tabNameSelect = ApexPages.currentPage().getParameters().get('tabName');
	}

	public PageReference actionCombineVat(){
		PageReference page = new PageReference('/' + transactionPlanId);
		String strSelectedVatIds = ApexPages.currentPage().getParameters().get('selectedVatIds');
		List<String> selectedVatIds = strSelectedVatIds.split(',');
		List<VATPayReq__c> newVATPayReqs = new List<VATPayReq__c>();
		for(String vatId : selectedVatIds){
			VATPayReq__c vatPlan = new VATPayReq__c(
				PaymentRequestID__c = transactionPlanId,
				VATInvoiceID__c = vatId);
			newVATPayReqs.add(vatPlan);
		}
		try{
        	FlsService.doInsert(newVATPayReqs);
            //VATPayReqTriggerHelper.connectSOANDBillToTransactionPlan(newVATPayReqs);
			page.setRedirect(true);
			return page;
			//ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.confirm, 'Success!'));
		}catch(Exception ex){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error, ex.getMessage()));
			return null;
		}
	}

	private void getCombinedVATIds(){
		List<VATPayReq__c> listCombinedVat = [SELECT Id, VATInvoiceID__c FROM VATPayReq__c
			WHERE  PaymentRequestID__c =: transactionPlanId];
		for(VATPayReq__c vatPlan : listCombinedVat){
			combinedVATIds.add(vatPlan.VATInvoiceID__c);
		}
	}
	private void handleVATList(List<VAT_INVOICE__c> argVATList){

		for(VAT_INVOICE__c vat : argVATList){
			if(mapVATType.get(vat.RecordType.DeveloperName) == 'Inbound'){
				VATListInbound.add(vat);
			}else{
				VATListOutbound.add(vat);
			}
		}
		// if(VATListInbound.size() > 0){
		// 	tabNameSelect = 'VATInbound';
		// }else{
		// 	tabNameSelect = 'VATOutbound';
		// }
	}
	private Date formatStringDate(String strDate){
		try{
			Date result = date.parse(strDate);
			return result;
		}catch(Exception ex){
			return null;
		}
	}
	private String buildShipmentQuery(){
		String strQuery = 'SELECT ID, FORWARDING__c, VAT_INVOICE__c FROM FORWARDING_VAT__c';
		String condition = '';
		if(!String.isBlank(shipmentOrderId)){
			condition += ' AND FORWARDING__r.Name like \'%' + String.escapeSingleQuotes(shipmentOrderId) + '%\'';
		}
		if(!String.isBlank(shipmentOrderSearch.REFNO__c)){
			condition += ' AND FORWARDING__r.REFNO__c like \'%' + String.escapeSingleQuotes(shipmentOrderSearch.REFNO__c) + '%\'';
		}
		if(!String.isBlank(shipmentOrderSearch.Cnee__c)){
			condition += ' AND FORWARDING__r.Cnee__c = \'' + String.escapeSingleQuotes(shipmentOrderSearch.Cnee__c) + '\'';
		}
		if(!String.isBlank(shipmentTimeType)){
			Date fromDate = formatStringDate(shipmentFromTime);
			Date toDate = formatStringDate(shipmentToTime);
			if(shipmentTimeType == 'ETD'){
				if(fromDate != null){
					condition += ' AND FORWARDING__r.ETD__c >= ' + String.valueOf(fromDate);
				}
				if(toDate != null){
					condition += ' AND FORWARDING__r.ETD__c <= ' + String.valueOf(toDate);
				}
			}else if(shipmentTimeType == 'Accounted Date'){
				if(fromDate != null){
					condition += ' AND FORWARDING__r.SalesAccountedDate__c >= ' + String.valueOf(fromDate);
				}
				if(toDate != null){
					condition += ' AND FORWARDING__r.SalesAccountedDate__c <= ' + String.valueOf(toDate);
				}
			}else{
				if(fromDate != null){
					condition += ' AND FORWARDING__r.ETA__c >= ' + String.valueOf(fromDate);
				}
				if(toDate != null){
					condition += ' AND FORWARDING__r.ETA__c <= ' + String.valueOf(toDate);
				}
			}
			
		}
		if(!String.isBlank(shipmentOrderSearch.HBL__c)){
			condition += ' AND FORWARDING__r.HBL__c like \'%' + String.escapeSingleQuotes(shipmentOrderSearch.HBL__c) + '%\'';
		}
		if(!String.isBlank(shipmentCustomerName)){
			condition += ' AND FORWARDING__r.Field1__r.Name like \'%' + String.escapeSingleQuotes(shipmentCustomerName) + '%\'';
		}
		if(!String.isBlank(shipmentOrderSearch.Master_B_L__c)){
			condition += ' AND FORWARDING__r.Master_B_L__c like \'%' + String.escapeSingleQuotes(shipmentOrderSearch.Master_B_L__c) + '%\'';
		}
		if(!String.isBlank(shipmentOrderSearch.shipper__c)){
			condition += ' AND FORWARDING__r.shipper__c = \'' + String.escapeSingleQuotes(shipmentOrderSearch.shipper__c) + '\'';
		}

		if(!String.isBlank(shipmentOrderSearch.POL__c)){
			condition += ' AND FORWARDING__r.POL__c = \'' + String.escapeSingleQuotes(shipmentOrderSearch.POL__c) + '\'';
		}
		if(!String.isBlank(shipmentOrderSearch.POD__c)){
			condition += ' AND FORWARDING__r.POD__c = \'' + String.escapeSingleQuotes(shipmentOrderSearch.POD__c) + '\'';
		}
		conditionSbipment = condition;
		strQuery += condition.replaceFirst('AND', 'WHERE');
		return strQuery;
	}
	private String buildBillQuery(){
		String strQuery = 'SELECT Id, VAT_INVOICE__c, INVOICING__c FROM INVOICING_VAT__c';
		String condition = '';
		if(!String.isBlank(fmsBillId)){
			condition += ' AND INVOICING__r.Name like \'%' + String.escapeSingleQuotes(fmsBillId) + '%\'';
		}
		if(!String.isBlank(billSearch.Seikyusaki__c)){
			condition += ' AND INVOICING__r.Seikyusaki__c = \'' + String.escapeSingleQuotes(billSearch.Seikyusaki__c) + '\'';
		}
		if(!String.isBlank(billSearch.PaymentTo__c)){
			condition += ' AND INVOICING__r.PaymentTo__c = \'' + String.escapeSingleQuotes(billSearch.PaymentTo__c) + '\'';
		}
		conditionBill = condition;
		strQuery += condition.replaceFirst('AND', 'WHERE');
		return strQuery;
	}

	private String buildVATQuery(){
		String strQuery = 'SELECT ' + String.join(new List<String>(fieldsQuery), ',')+' FROM VAT_INVOICE__c';
		String condition = '';
		if(!String.isBlank(invoiceType)){
			condition += ' AND RecordType.DeveloperName = \'' + String.escapeSingleQuotes(invoiceType) + '\'';
		}
		if(!String.isBlank(invoiceName)){
			condition += ' AND Name like \'%' + String.escapeSingleQuotes(invoiceName) + '%\'';
		}
		if(!String.isBlank(objectSearch.RED_INVOICE_NO__c)){
			condition += ' AND (RED_INVOICE_NO__c like \'%' + String.escapeSingleQuotes(objectSearch.RED_INVOICE_NO__c) + '%\'';
			condition += ' OR VATInvoiceNoFromVendor__c like \'%' + String.escapeSingleQuotes(objectSearch.RED_INVOICE_NO__c) + '%\')';
		}
		if(!String.isBlank(objectSearch.VatIssueFrom__c)){
			condition += ' AND VatIssueFrom__c = \'' + String.escapeSingleQuotes(objectSearch.VatIssueFrom__c) + '\'';
		}
		if(!String.isBlank(objectSearch.VAT_INVOICE_TO__c)){
			condition += ' AND VAT_INVOICE_TO__c = \'' + String.escapeSingleQuotes(objectSearch.VAT_INVOICE_TO__c) + '\'';
		}
		if(!vatIds.isEmpty()){
			//if(String.isBlank(condition)){
				condition += ' AND Id IN: vatIds';
			//}
			//}else{
			//	condition = ' AND (' + condition.replaceFirst('AND', '') + ' ) OR Id IN: vatIds';
			//}

		}
		if(!combinedVATIds.isEmpty()){
			condition += ' AND Id NOT IN: combinedVATIds';
		}

		strQuery += condition.replaceFirst('AND', 'WHERE');
		return strQuery;
	}
	public void doClear(){
		init();
	}
	
}