force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>BuyDifferentiation__c</fullName>
    <formula>BuyInTaxAmountJPY__c - Siharaigaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Buying(Local)=Amount Buying including Tax(Local)-Amount Paid-Buying(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF BUYING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>SellDifferentiation__c</fullName>
    <formula>SellInTaxAmountJPY__c - Nyukingaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Selling(Local)=Amount Selling including Tax(Local)-Amount Paid-Selling(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF SELLING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/ConnectInvoicingAndCash__c.object-meta.xml
<CustomObject>
    <description>Joint function to connect Invoicing to Cash</description>
    <label>F/TMS請求・仕入+現金入出</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>FMS BILL+CASH ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_INVOICING_AND_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Invoicing__c</fullName>
    <label>INVOICING</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>CONNECT_INVOICING_AND_CASH</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoicingCashTriggerHandler.cls
/**
 * Created by khanhpham on 5/28/17.
 */

public with sharing class InvoicingCashTriggerHandler extends AbstractTriggerHandler {
    private static Map<String, CASH_BOOK__c> cashBookMap = new Map<String, CASH_BOOK__c>();
    private static Map<String, AnkenMeisai__c> invoiceMap = new Map<String, AnkenMeisai__c>();
    private static Map<String, CASH_BOOK__c> toBeUpdatedcashBookMap = new Map<String, CASH_BOOK__c>();

    public override void bulkAfter() {
        if (Trigger.isDelete) {
            loadReferences(Trigger.old);
        } else {
            loadReferences(Trigger.new);
        }
    }

    public override void afterInsert(SObject so) {
        ConnectInvoicingAndCash__c poCash = (ConnectInvoicingAndCash__c) so;

        updateCashBookTotalAmount(poCash);
    }

    public override void afterDelete(SObject so) {
        ConnectInvoicingAndCash__c poCash = (ConnectInvoicingAndCash__c) so;

        updateCashBookTotalAmount(poCash);
    }

    // public override void andFinally() {
    //     if (toBeUpdatedcashBookMap.values().size() > 0) {
    //     }
    // }

    private void updateCashBookTotalAmount(ConnectInvoicingAndCash__c link) {
        CASH_BOOK__c cashBook = cashBookMap.get(link.Cashbook__c);
        AnkenMeisai__c invoice = invoiceMap.get(link.Invoicing__c);

        if (cashBook != null && invoice != null) {
            if (Trigger.isInsert) {
                if (Util.isCashOut(cashBook)) {
                    if (cashBook.TotalAmount__c == null) {
                        cashBook.TotalAmount__c = invoice.BuyDifferentiation__c;
                    } else {
                        cashBook.TotalAmount__c += (invoice.BuyDifferentiation__c != null ? invoice.BuyDifferentiation__c : 0);
                    }
                } else {
                    if (cashBook.TotalAmount__c == null) {
                        cashBook.TotalAmount__c = invoice.SellDifferentiation__c;
                    } else {
                        cashBook.TotalAmount__c += (invoice.SellDifferentiation__c != null ? invoice.SellDifferentiation__c : 0);
                    }
                }
            } else if (Trigger.isDelete) {
                if (Util.isCashOut(cashBook)) {
                    if (cashBook.TotalAmount__c != null && invoice.BuyDifferentiation__c != null) {
                        cashBook.TotalAmount__c -= invoice.BuyDifferentiation__c;
                    }
                } else {
                    if (cashBook.TotalAmount__c != null && invoice.SellDifferentiation__c != null) {
                        cashBook.TotalAmount__c -= invoice.SellDifferentiation__c;
                    }
                }
            }

            toBeUpdatedcashBookMap.put(cashBook.Id, cashBook);
        }
    }

    private void loadReferences(List<ConnectInvoicingAndCash__c> links) {
        Set<Id> cashBookIds = new Set<Id>();
        Set<Id> invoiceIds = new Set<Id>();

        for (ConnectInvoicingAndCash__c link : links) {
            cashBookIds.add(link.Cashbook__c);
            invoiceIds.add(link.Invoicing__c);
        }

        cashBookMap = new Map<String, CASH_BOOK__c>([SELECT Id, TotalAmount__c, RecordTypeId FROM CASH_BOOK__c WHERE Id IN :cashBookIds]);
        invoiceMap = new Map<String, AnkenMeisai__c>([SELECT Id, BuyDifferentiation__c, SellDifferentiation__c FROM AnkenMeisai__c WHERE Id IN :invoiceIds]);
    }
}