force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/Anken__c.field-meta.xml
<CustomField>
    <fullName>Anken__c</fullName>
    <label>H B/L SHIPMENT ID</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>Anken</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/FMSBillPayReq__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+TRX Plan</label>
    <nameField>
        <displayFormat>FBPR-{000000}</displayFormat>
        <label>FMS BILL+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSBillID__c.field-meta.xml
<CustomField>
    <fullName>FMSBillID__c</fullName>
    <label>FMS BILL ID</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/INVOICING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS BILL+VAT</label>
    <nameField>
        <displayFormat>IV-{0000000}</displayFormat>
        <label>FMS BILL+VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/fields/INVOICING__c.field-meta.xml
<CustomField>
    <fullName>INVOICING__c</fullName>
    <inlineHelpText>Filter Type:Optional.
-Pricing:Active equals True</inlineHelpText>
    <label>INVOICING</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>AnkenMeisai__c.Tariff__r.ProductFlag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Filter Type:Optional.
-PRICING:ACTIVE equals True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False. 
VAT Invoice is approved and locked. Contact System Administrator to unlock VAT Invoice.</errorMessage>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VATPayReq__c/VATPayReq__c.object-meta.xml
<CustomObject>
    <label>VAT+TRX Plan</label>
    <nameField>
        <displayFormat>VIPR-{000000}</displayFormat>
        <label>VAT+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VAT+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VATPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>PaymentRequestID</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VATPayReq__c/fields/VATInvoiceID__c.field-meta.xml
<CustomField>
    <fullName>VATInvoiceID__c</fullName>
    <label>VAT INVOICE ID</label>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>VATInvoiceID</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VATPayReqTriggerHelper.cls
public with sharing class VATPayReqTriggerHelper {
	public static void connectSOANDBillToTransactionPlan( List<VATPayReq__c> listTransactionPlan){
		Set<Id> vatIds = new Set<Id>();
		Set<Id> planIds = new Set<Id>();
		Map<String, Set<String>> trxPlabByVATMap = new Map<String, Set<String>>();
		for(VATPayReq__c payRequest : listTransactionPlan){
			planIds.add(payRequest.PaymentRequestID__c);
			vatIds.add(payRequest.VATInvoiceID__c);
			if(trxPlabByVATMap.containsKey(payRequest.VATInvoiceID__c)){
				trxPlabByVATMap.get(payRequest.VATInvoiceID__c).add(payRequest.PaymentRequestID__c);
			}else{
				trxPlabByVATMap.put(payRequest.VATInvoiceID__c, new Set<String>{payRequest.PaymentRequestID__c});
			}
		}

		// get all bill combined to VAT
		List<INVOICING_VAT__c> listBillVAT = [SELECT Id, VAT_INVOICE__c, INVOICING__c
													FROM INVOICING_VAT__c 
		
													WHERE VAT_INVOICE__c IN: vatIds ];
		Set<Id> billIds = new Set<Id>();
		for(INVOICING_VAT__c billVAT: listBillVAT){
			billIds.add(billVAT.INVOICING__c);
		}
		// get bill combined to planed
		List<FMSBillPayReq__c> listBillPlan = [SELECT Id, PaymentRequestID__c, FMSBillID__c
													FROM FMSBillPayReq__c 
		
													WHERE PaymentRequestID__c IN: planIds
													AND  FMSBillID__c IN: billIds];
		Map<String, Set<String>> mapBillsByPlan = new Map<String, Set<String>>();
		for(FMSBillPayReq__c billPlan : listBillPlan){
			if(mapBillsByPlan.containsKey(billPlan.PaymentRequestID__c)){
				mapBillsByPlan.get(billPlan.PaymentRequestID__c).add(billPlan.FMSBillID__c);
			}else{
				mapBillsByPlan.put(billPlan.PaymentRequestID__c, new Set<String>{billPlan.FMSBillID__c});
			}
		}

		Set<String> billVATs = new Set<String>();
		Set<String> shipmentOrderVATs = new Set<String>();

		List<FMSBillPayReq__c> billTransactionPlans = new List<FMSBillPayReq__c>();

		for(INVOICING_VAT__c billVAT: listBillVAT){
			String key = (String)billVAT.INVOICING__c + (String)billVAT.VAT_INVOICE__c;
			if(!billVATs.contains(key)){
				billVATs.add(key);
				for(String trxPlan : trxPlabByVATMap.get(billVAT.VAT_INVOICE__c)){
					if(!mapBillsByPlan.containsKey(trxPlan) 
						|| (mapBillsByPlan.containsKey(trxPlan) && !mapBillsByPlan.get(trxPlan).contains(billVAT.INVOICING__c)) ){

						FMSBillPayReq__c billTrxPlan = new FMSBillPayReq__c(
							PaymentRequestID__c = trxPlan,
							FMSBillID__c = billVAT.INVOICING__c);
						billTransactionPlans.add(billTrxPlan);
						if(mapBillsByPlan.containsKey(trxPlan)){
							mapBillsByPlan.get(trxPlan).add(billVAT.INVOICING__c);
						}else{
							mapBillsByPlan.put(trxPlan, new Set<String>{billVAT.INVOICING__c});
						}
					}
					
				}
				
			}
			/*String keyShipment = billVAT.INVOICING__r.Anken__c + billVAT.VAT_INVOICE__c;
			if(!shipmentOrderVATs.contains(keyShipment)){
				shipmentOrderVATs.add(keyShipment);
				for(String trxPlan : trxPlabByVATMap.get(billVAT.VAT_INVOICE__c)){
					FMSBillPayReq__c billTrxPlan = new FMSBillPayReq__c(
						PaymentRequestID__c = trxPlan,
						FMSBillID__c = billVAT.INVOICING__c
					);
					billTransactionPlans.add(billTrxPlan);
				}
			}*/
		}
		try{
			FlsService.doInsert(billTransactionPlans);
		}catch(Exception ex){
			listTransactionPlan[0].addError(ex.getMessage());
		}
		// get all S/O Combined to VAT
	}
}