force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/CarrierType__c.field-meta.xml
<CustomField>
    <fullName>CarrierType__c</fullName>
    <label>TRANSPORT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEA</fullName>
                <default>true</default>
                <label>SEA</label>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>INLAND</fullName>
            </value>
            <value>
                <fullName>RIVER</fullName>
            </value>
            <value>
                <fullName>RAIL</fullName>
            </value>
            <value>
                <fullName>SEA&amp;AIR</fullName>
            </value>
            <value>
                <fullName>SEA&amp;INLAND</fullName>
            </value>
            <value>
                <fullName>SEA&amp;RIVER</fullName>
            </value>
            <value>
                <fullName>SEA&amp;RAIL</fullName>
            </value>
            <value>
                <fullName>AIR&amp;INLAND</fullName>
            </value>
            <value>
                <fullName>AIR&amp;RIVER</fullName>
            </value>
            <value>
                <fullName>AIR&amp;RAIL</fullName>
            </value>
            <value>
                <fullName>INLAND&amp;RIVER</fullName>
            </value>
            <value>
                <fullName>INLAND&amp;RAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/LoadLocation__c.field-meta.xml
<CustomField>
    <fullName>LoadLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Refer to Master A/N to confirm about loading Warehouse</inlineHelpText>
    <label>CARGO LOADING WAREHOUSE(LOCAL)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>LoadLocation__c.WharehouseCompany__c</field>
            <operation>equals</operation>
            <valueField>$Source.BookingNv__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LoadLocation__c</referenceTo>
    <relationshipLabel>F/TMS S/O</relationshipLabel>
    <relationshipName>LoadLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/LoadLocationPIC__c.field-meta.xml
<CustomField>
    <fullName>LoadLocationPIC__c</fullName>
    <formula>LoadLocation__r.LoadLocationPIC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PIC OF WAREHOUSE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Vessel_Type__c.field-meta.xml
<CustomField>
    <fullName>Vessel_Type__c</fullName>
    <label>VESSEL TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ferry</fullName>
            </value>
            <value>
                <fullName>Container Vessel</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Barging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/LoadLocation__c/LoadLocation__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_WarehouseOnlineHelp</customHelpPage>
    <description>Warehouse (Load Location)</description>
    <label>CFS・CY・DEPOT</label>
    <nameField>
        <label>WAREHOUSE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LoadLocation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ACTIVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LoadLocation__c/fields/LoadLocationPIC__c.field-meta.xml
<CustomField>
    <fullName>LoadLocationPIC__c</fullName>
    <label>PIC OF WAREHOUSE</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LoadLocation__c/fields/WharehouseCompany__c.field-meta.xml
<CustomField>
    <fullName>WharehouseCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE CORPORATE NAME</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>WharehouseCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/MasterAnken__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLOnlineHelp</customHelpPage>
    <description>M B/L - SHIPMENTS</description>
    <label>混載</label>
    <nameField>
        <label>MASTER SHIPMENT NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnken__c/fields/CarrierType__c.field-meta.xml
<CustomField>
    <fullName>CarrierType__c</fullName>
    <label>TRANSPORT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>海上(SEA)</fullName>
            </value>
            <value>
                <fullName>航空(AIR)</fullName>
            </value>
            <value>
                <fullName>複合(SEA&amp;AIR)</fullName>
            </value>
            <value>
                <fullName>複合(SEA&amp;RAIL)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/Document_Receipt_Time__c.field-meta.xml
<CustomField>
    <fullName>Document_Receipt_Time__c</fullName>
    <label>Document Receipt Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MasterAnkenTorihikisaki</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/First_Approval_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Approval_Time__c</fullName>
    <label>First Approval Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MBookingNv__c.field-meta.xml
<CustomField>
    <fullName>MBookingNv__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>当社を選択してください。</description>
    <inlineHelpText>Your company&apos;s consolidation;put your company name, Put the carrier name or consolidator(Co-loader) in other shipments</inlineHelpText>
    <label>MASTER CONSOLIDATOR/CARRIER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONSOLIDATION (MASTER CONSOLIDATOR/CARRIER)</relationshipLabel>
    <relationshipName>M_BL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MLoadLocation__c.field-meta.xml
<CustomField>
    <fullName>MLoadLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARGO LOADING WAREHOUSE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.MBookingNv__c</field>
            <operation>equals</operation>
            <valueField>LoadLocation__c.WharehouseCompany__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LoadLocation__c</referenceTo>
    <relationshipLabel>CONSOLIDATION (CARGO LOADING WAREHOUSE)</relationshipLabel>
    <relationshipName>M_BL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/Vessel_Type__c.field-meta.xml
<CustomField>
    <fullName>Vessel_Type__c</fullName>
    <label>Vessel Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ferry</fullName>
            </value>
            <value>
                <fullName>Container Vessel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName1__c</fullName>
    <label>FCY Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName2__c</fullName>
    <label>FCY Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName1__c</fullName>
    <label>Local Currency Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName2__c</fullName>
    <label>Local Currency Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName3__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName3__c</fullName>
    <label>Local Currency Bank Account Short Name-3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName4__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName4__c</fullName>
    <label>Local Currency Bank Account Short Name-4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName5__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName5__c</fullName>
    <label>Local Currency Bank Account Short Name-5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Calendar_Settings__c/SLA_Calendar_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SLA Calendar Settings</label>
</CustomObject>

force-app/main/default/objects/SLA_Calendar_Settings__c/fields/Holiday_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Name_Prefix__c</fullName>
    <label>Holiday Name Prefix</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Calendar_Settings__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLA_Calendar_Settings__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PerformanceReportControllerTest.cls
@isTest
private class PerformanceReportControllerTest {
	@testSetup static void setUp() {
        //Setup running user with timezone match test data
        Profile p = [SELECT Id FROM Profile WHERE UserType='Standard' LIMIT 1];
        DateTime currentTime = System.now();
        String username = 'dummy.' + currentTime.millisecond() + '@sample.com';
        User u = new User(Alias = 'alias', Email=username, 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='vi', 
                          LocaleSidKey='vi_VN', ProfileId = p.Id, 
                          TimeZoneSidKey='Asia/Ho_Chi_Minh', UserName=username);
        
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
        DateTime receiptTime = DateTime.newInstanceGmt(Date.newInstance(2016, 1, 19), Time.newInstance(2, 0, 0, 0));
        DateTime metSLATime = DateTime.newInstanceGmt(Date.newInstance(2016, 1, 19), Time.newInstance(4, 0, 0, 0));
        DateTime missedSLATime = DateTime.newInstanceGmt(Date.newInstance(2016, 1, 19), Time.newInstance(8, 0, 0, 0));
    
        System.runAs(u) {
			Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
            Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
            // Setup HBL
            Map<String, Object> additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => rt.Id, 
                'CarrierType__c' => PicklistReference.TRANSPORT_TYPE_AIR, 'Vessel_Type__c' => PicklistReference.VESSEL_FERRY, 
                'Document_Receipt_Time__c' => receiptTime, 'First_Approval_Time__c' => metSLATime};
			TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
            
            additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => rt.Id, 
                'CarrierType__c' => PicklistReference.TRANSPORT_TYPE_SEA_AIR, 'Vessel_Type__c' => PicklistReference.VESSEL_CONTAINER_FERRY, 
                'Document_Receipt_Time__c' => receiptTime, 'First_Approval_Time__c' => missedSLATime};
			TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
            
            // Setup MBL
            additionalFields = new Map<String, Object> {'WharehouseCompany__c' => account.Id, 
                'LoadLocationPIC__c' => 'LoadLocationPIC'};
			LoadLocation__c warehouse = (LoadLocation__c) TestDataFactory.createSObject(new LoadLocation__c(), true, additionalFields);
            
            additionalFields = new Map<String, Object> {'MLoadLocation__c' => warehouse.Id, 'MBookingNv__c' => account.Id, 
                'Document_Receipt_Time__c' => receiptTime, 'First_Approval_Time__c' => metSLATime,
                'Vessel_Type__c' => PicklistReference.VESSEL_FERRY};
			TestDataFactory.createSObject(new MasterAnken__c(), true, additionalFields);
            
            // Setup SLA Calendar Settings
            additionalFields = new Map<String, Object> {'Name' => 'Test Vietnam Team', 'Timezone__c' => 'Asia/Ho_Chi_Minh', 
                'Holiday_Name_Prefix__c' => 'Vi', 'Active__c' => true, 'Order__c' => 1};
			TestDataFactory.createSObject(new SLA_Calendar_Settings__c(), true, additionalFields);
            
            additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
                'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Local_Currency__c' => 'VND',
                'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Company_Country__c' => 'Japan',
                'Ocean_HBL_No_Prefix__c' => 'AFR', 'Ferry_SLA__c' => 120, 'Container_Vessel_SLA__c' => 480,
            	'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
			TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);
        }
    }
    
    testmethod static void shouldGenerateReport() {
        PageReference pageRef = Page.PerformanceReport;
        Test.setCurrentPage(pageRef);
        
        SLA_Calendar_Settings__c setting = [SELECT Id FROM SLA_Calendar_Settings__c WHERE Name = 'Test Vietnam Team' LIMIT 1];
        PerformanceReportController controller = new PerformanceReportController();
        controller.fromDate = '2016/1/10';
        controller.toDate = '2016/1/22';
        controller.selectedTeam = setting.Id;
        
        Test.startTest();
        controller.generateReport();
        Test.stopTest();
        System.assertEquals(3, controller.slaReport.reportLines.size());
    }

    testmethod static void shouldExportReportToPDF() {
        PageReference pageRef = Page.PerformanceReport;
        Test.setCurrentPage(pageRef);
        
        SLA_Calendar_Settings__c setting = [SELECT Id FROM SLA_Calendar_Settings__c WHERE Name = 'Test Vietnam Team' LIMIT 1];
        PerformanceReportController controller = new PerformanceReportController();
        controller.fromDate = '2016/1/10';
        controller.toDate = '2016/1/22';
        controller.selectedTeam = setting.Id;
        
        Test.startTest();
        controller.generateReport();
        PageReference exportPage = controller.exportPDF();
        Test.stopTest();
        System.assertEquals(3, controller.slaReport.reportLines.size());
        System.assertEquals('/apex/' + Constants.NAMESPACE + 'performancereportpdf', exportPage.getUrl());
    }

    testmethod static void shouldExportReportToExcel() {
        PageReference pageRef = Page.PerformanceReport;
        Test.setCurrentPage(pageRef);
        
        SLA_Calendar_Settings__c setting = [SELECT Id FROM SLA_Calendar_Settings__c WHERE Name = 'Test Vietnam Team' LIMIT 1];
        PerformanceReportController controller = new PerformanceReportController();
        controller.fromDate = '2016/1/10';
        controller.toDate = '2016/1/22';
        controller.selectedTeam = setting.Id;
        
        Test.startTest();
        controller.generateReport();
        PageReference exportPage = controller.exportExcel();
        Test.stopTest();
        System.assertEquals(3, controller.slaReport.reportLines.size());
        System.assertEquals('/apex/' + Constants.NAMESPACE + 'performancereportexcel', exportPage.getUrl());
    }
    
    testmethod static void shouldNotGenerateReportIfInvalidPeriod() {
        PageReference pageRef = Page.PerformanceReport;
        Test.setCurrentPage(pageRef);
        
        SLA_Calendar_Settings__c setting = [SELECT Id FROM SLA_Calendar_Settings__c WHERE Name = 'Test Vietnam Team' LIMIT 1];
        PerformanceReportController controller = new PerformanceReportController();
        controller.fromDate = '2016/1/22';
        controller.toDate = '2016/1/10';
        controller.selectedTeam = setting.Id;
        
        Test.startTest();
        controller.generateReport();
        Test.stopTest();
        System.assertEquals(0, controller.slaReport.reportLines.size());
    }
}