force-app/main/default/objects/Account/fields/Business_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Business_Relationship__c</fullName>
    <inlineHelpText>Choose Customer or Partner; if choose Customer, charge amount can be shown on local invoice and Customer Invoice Summary Report. If choose Partner, charge amount can be shown on D/N, C/N and Partner Outstanding Statement Report.</inlineHelpText>
    <label>Business Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>3rd Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Custom_Type__c.field-meta.xml
<CustomField>
    <fullName>Custom_Type__c</fullName>
    <description>Used as an alternative for standard field Type</description>
    <inlineHelpText>For Customer, choose from Domestic Customer-, and partner from Oversea Partner-、vendor from 3RD Vendor-. For your own company, choose Internal Use Only .</inlineHelpText>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>国内顧客 - 見込み</fullName>
                <label>LOCAL CUSTOMER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>国内顧客 - 既存</fullName>
                <default>true</default>
                <label>LOCAL CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>国内顧客 - フォワーダー</fullName>
                <label>LOCAL CUSTOMER - FORWARDER</label>
            </value>
            <value>
                <fullName>国内顧客 - 営業不要</fullName>
                <label>LOCAL CUSTOMER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>海外顧客 - 見込み</fullName>
                <label>OVERSEA CUSTOMER - LEAD(APPORACHING)</label>
            </value>
            <value>
                <fullName>海外顧客 - 既存</fullName>
                <label>OVERSEA CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>Oversea Customer - No Need Sales</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - LEAD(APPROACHING)</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - EXISTING</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - NO NEED SALES</fullName>
            </value>
            <value>
                <fullName>海外パートナー - 見込み</fullName>
                <label>OVERSEA PARTNER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>海外パートナー - 既存</fullName>
                <label>OVERSEA PARTNER - EXISTING</label>
            </value>
            <value>
                <fullName>海外パートナー - 営業不要</fullName>
                <label>OVERSEA PARTNER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>業者 - Co-Loader</fullName>
                <label>3RD VENDOR - CONSOLIDATOR</label>
            </value>
            <value>
                <fullName>Co-Loader</fullName>
            </value>
            <value>
                <fullName>業者 - 通関（当社手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - BB/通関（当社手配先）</fullName>
                <label>3RD VENDOR - BB/CUSTOMERS CLEARANCE/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - 通関（お客様手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/CUSTOMER AGENT</label>
            </value>
            <value>
                <fullName>業者 - 運送</fullName>
                <label>3RD VENDOR - TRUCKING</label>
            </value>
            <value>
                <fullName>Rail Agent</fullName>
            </value>
            <value>
                <fullName>Courier/Express</fullName>
            </value>
            <value>
                <fullName>業者 - 船社</fullName>
                <label>3RD VENDOR - CARRIER</label>
            </value>
            <value>
                <fullName>3RDVENDOR - AIRLINER</fullName>
                <label>3RD VENDOR - AIRLINER</label>
            </value>
            <value>
                <fullName>業者 - 倉庫・保管</fullName>
                <label>3RD VENDOR - WAREHOUSE/STORAGE</label>
            </value>
            <value>
                <fullName>Shipping Broker</fullName>
            </value>
            <value>
                <fullName>Packing Vendor</fullName>
            </value>
            <value>
                <fullName>Inspection Vendor</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>業者 - ポート</fullName>
                <label>3RD VENDOR - PORT</label>
            </value>
            <value>
                <fullName>業者 - DEPOT</fullName>
                <label>3RD VENDOR - DEPOT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Workflow_Rule__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Workflow_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Workflow Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Container_Vessel_SLA__c.field-meta.xml
<CustomField>
    <fullName>Container_Vessel_SLA__c</fullName>
    <defaultValue>240</defaultValue>
    <description>ETA Monday Ferry is the ferry arrives on Monday</description>
    <inlineHelpText>ETA Monday Ferry is the ferry arrives on Monday</inlineHelpText>
    <label>Container Vessel and ETA Monday Ferry SL</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ferry_SLA__c.field-meta.xml
<CustomField>
    <fullName>Ferry_SLA__c</fullName>
    <defaultValue>120</defaultValue>
    <description>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</description>
    <inlineHelpText>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</inlineHelpText>
    <label>Air and ETA Non-Monday Ferry SLA(Minutes</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ocean_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Ocean_HBL_No_Prefix__c</fullName>
    <description>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</description>
    <inlineHelpText>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</inlineHelpText>
    <label>Ocean HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutstandingStatementReportTest.cls
@isTest
private class OutstandingStatementReportTest {
    private static Account invoiceTo{get;set;}
    private static Account paymentTo{get;set;}
    private static CustomObject1__c shipment{get;set;}
    private static TariffMaster__c serviceMaster{get;set;}
    private static AnkenMeisai__c hblBuying{get;set;}
    private static AnkenMeisai__c hblBuying2{get;set;}
    static {
        Custom_Application_Config__c config = new Custom_Application_Config__c();
		config.Disabled_Workflow_Rule__c = true;
        config.Disabled_Trigger__c =true;
        FlsService.doInsert(config);
        Map<String, Object> additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
                'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Local_Currency__c' => 'JPY',
                'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Company_Country__c' => 'Japan',
                'Ocean_HBL_No_Prefix__c' => 'AFR', 'Ferry_SLA__c' => 120, 'Container_Vessel_SLA__c' => 480,
                'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
        TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);
        
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
        
        additionalFields = new Map<String, Object> {'Custom_Type__c' => '国内顧客 - 既存', 'Name' => 'INVOICE_TO',
                                                    'EnglishCompanyName__c' => 'INVOICE_TO_EN',
                                                    'Business_Relationship__c' => Constants.PARTNER_RELATIONSHIP};                                                                    
        invoiceTo = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);
        
        additionalFields = new Map<String, Object> {'Custom_Type__c' => '国内顧客 - 既存', 'Name' => 'PAYMENT_TO',
                                                    'EnglishCompanyName__c' => 'PAYMENT_TO_EN',            
                                                    'Business_Relationship__c' => Constants.PARTNER_RELATIONSHIP};                                                                    
        paymentTo = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);
        
        Date etd = Date.newInstance(2015, 07, 02);
        additionalFields = new Map<String, Object> {'Field1__c' => invoiceTo.Id, 'RecordTypeId' => rt.Id, 'ETD__c' => etd,
                                                    'Status__c' => '輸入 税関審査終了(Cunstoms Declared)'};
        shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
        
        additionalFields = new Map<String, Object> {'Name' => 'LCL', 'ProductSearch__c' => 'FCL輸入', 'Subcategory__c' => '基本料金',
                                                'EngProductSearch__c' => 'FCL Import', 'ProductFlag__c' => true, 'Supplier__c' => invoiceTo.Id};
        serviceMaster = (TariffMaster__c) TestDataFactory.createSObject(new TariffMaster__c(), true, additionalFields);
        
        /*additionalFields = new Map<String, Object> {'Anken__c' => shipment.Id, 'curr__c' => 'JPY', 'SerchSyubetu__c' => 'FCL輸入',
                                                'Tariff__c' => serviceMaster.Id, 'PaymentTo__c' => paymentTo.Id, 'Seikyusaki__c' => invoiceTo.Id,
                                                'SiharaiKakuninzumi__c' => false, 'Suryo__c' => 1, 'BuyTankaUSD__c' => 100};*/
        additionalFields = new Map<String, Object> {'Anken__c' => shipment.Id, 'curr__c' => 'JPY', 'SerchSyubetu__c' => 'FCL輸入',
                                                'Tariff__c' => serviceMaster.Id, 'Seikyusaki__c' => invoiceTo.Id,
                                                'SiharaiKakuninzumi__c' => false, 'Suryo__c' => 1, 'BuyTankaUSD__c' => 100};
        hblBuying = (AnkenMeisai__c) TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);
        hblBuying2 = (AnkenMeisai__c) TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);
        
    } 
    
    private static testmethod void shouldReturnRecordForOutstandingReportInvoice1() {
        
        
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Suryo__c = 10;
        hblBuying.SellTankaUSD__c = 10;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'Outstanding';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        Test.stopTest();

        System.assert(controller.lstReportWrapper.size() == controller.lstReportWrapper.size());
    }
    
    private static testmethod void shouldReturnRecordForOutstandingReportInvoice2() {
      
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Suryo__c = 10;
        hblBuying.SellTankaUSD__c = 10;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        //controller.sToDate = '2015/08/01';
        controller.reportType = 'Outstanding';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        Test.stopTest();

        System.assert(controller.lstReportWrapper.size() == controller.lstReportWrapper.size());
    }
    
    private static testmethod void shouldReturnRecordForOutstandingReportInvoice3() {
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Suryo__c = 10;
        hblBuying.SellTankaUSD__c = 10;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        //controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'Outstanding';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        Test.stopTest();

        System.assert(controller.lstReportWrapper.size() == controller.lstReportWrapper.size());
    }
    
    private static testmethod void shouldReturnRecordForOutstandingReportPayment() {
        
        hblBuying.SiharaiKakuninzumi__c = false;
        hblBuying.Suryo__c = 10;
        hblBuying.BuyTankaJPY__c = 10;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'Outstanding';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        Test.stopTest();

        System.assert(controller.lstReportWrapper.size() == controller.lstReportWrapper.size());
    }
    
    private static testmethod void shouldReturnRecordForOutstandingReportCus() {
        
        invoiceTo.Business_Relationship__c = Constants.CUSTOMER_RELATIONSHIP;
        FlsService.doUpdate(invoiceTo);
        
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Seikyusaki__c = invoiceTo.Id;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'DOMESTIC';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        
        controller.mapShowHideTableCustomer.put('INVOICE_TO', true);
        controller.displayDetailTableName();
        Test.stopTest();

        System.assert(controller.lstReportWrapper.size() == controller.lstReportWrapper.size());
    }

    private static testmethod void shouldReturnRecordForOutstandingReportCusCreditDebit() {
        
        invoiceTo.Business_Relationship__c = Constants.CUSTOMER_RELATIONSHIP;
        FlsService.doUpdate(invoiceTo);
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Seikyusaki__c = invoiceTo.Id;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'DOMESTIC_CREDIT_DEBIT';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        
        controller.mapShowHideTableCustomer.put('INVOICE_TO', true);
        controller.displayDetailTableName();
        Test.stopTest();

        System.assert(controller.lstReportWrapper.size() == controller.lstReportWrapper.size());
    }
    
    private static testmethod void shouldReturnRecordForOutstandingReport1() {
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'VENDOR';
        controller.searchType = 'ETA';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    static testMethod void onChangeType3(){
        Test.startTest();
        OutStandingStatementReportController ctr = new OutstandingStatementReportController();
        
        ctr.reportType = 'VENDOR';
        ctr.strTblName = Constants.VENDOR_RELATIONSHIP;
        ctr.sFromDate = '2015/06/30';
        ctr.sToDate = '2015/08/01';
        
        ctr.onChangeType();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    static testMethod void onChangeType1(){
        Test.startTest();
        OutStandingStatementReportController ctr = new OutstandingStatementReportController();
        
        ctr.reportType = 'Outstanding';
        ctr.strTblName = Constants.PARTNER_RELATIONSHIP;
        ctr.sFromDate = '2015/06/30';
        ctr.sToDate = '2015/08/01';
        
        ctr.onChangeType();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    static testMethod void onChangeType2(){
        Test.startTest();
        OutStandingStatementReportController ctr = new OutstandingStatementReportController();
        
        ctr.reportType = 'DOMESTIC';
        ctr.strTblName = Constants.CUSTOMER_RELATIONSHIP;
        ctr.sFromDate = '2015/06/30';
        ctr.sToDate = '2015/08/01';
        
        ctr.onChangeType();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void shouldExportPartnerPDFReport() {
        
        invoiceTo.Business_Relationship__c = Constants.CUSTOMER_RELATIONSHIP;
        FlsService.doUpdate(invoiceTo);
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Suryo__c = 10;
        hblBuying.SellTankaUSD__c = 10;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        
        controller.reportType = 'Outstanding';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        
        controller.pageType = 'pdf';
        //controller.partnerName = anken.Seikyusaki__r.Name;
        
        //controller.detailReportData = new ReportWrapper();
        //controller.detailReportData.partnerName = anken.Seikyusaki__r.Name;
        //controller.detailReportData.partnerEnglishName = anken.Seikyusaki__r.EnglishCompanyName__c;
        
        //controller.generateReport();
        PageReference detailPage = controller.generateDetailReport();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void generateCustomerReport(){
        invoiceTo.Business_Relationship__c = Constants.CUSTOMER_RELATIONSHIP;
        FlsService.doUpdate(invoiceTo);
        hblBuying.NyukinKakuninzumi__c = false;
        hblBuying.Seikyusaki__c = invoiceTo.Id;
        FlsService.doUpdate(hblBuying);
        
        PageReference pageRef = Page.page_OutStandingStatementReport;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        controller.sFromDate = '2015/06/30';
        controller.sToDate = '2015/08/01';
        controller.reportType = 'DOMESTIC';
        controller.strNameId = hblBuying.Seikyusaki__c;
        
        controller.generateReport();
        
        controller.pageType = 'pdf';
        
        PageReference detailPage = controller.generateCustomerReport();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();

    }
    
    private static testmethod void getLanguages(){
        
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        List<SelectOption> lstLanguage = controller.getLanguages();

        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void getReportTypes(){
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        List<SelectOption> lstLanguage = controller.getReportTypes();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void getSearchConditions(){
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        List<SelectOption> lstLanguage = controller.getSearchConditions();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void getShowTypes(){
        Test.startTest();
        OutStandingStatementReportController controller = new OutstandingStatementReportController();
        List<SelectOption> lstLanguage = controller.getShowTypes();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void shouldReturnRecordForOutstandingDetailReport1() {
        PageReference pageRef = Page.page_OutStandingStatementDetail;
        pageRef.getParameters().put('partnerName', 'PAYMENT_TO');
        pageRef.getParameters().put('fromDate', '2015-06-30');
        pageRef.getParameters().put('toDate', '2015-08-01');
        pageRef.getParameters().put('partnerENName', 'PAYMENT_TO');
        pageRef.getParameters().put('relationship', Constants.PARTNER_RELATIONSHIP);
        pageRef.getParameters().put('currency', 'USD');
        pageRef.getParameters().put('strWkid', String.valueOf(hblBuying2.Id));
        pageRef.getParameters().put('searchType', 'ETA');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementDetailController controller = new OutStandingStatementDetailController();
        
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
        //System.assert(controller.lstSTID.size() > 0);
    }
    
    private static testmethod void shouldReturnRecordForOutstandingDetailReport2() {
        PageReference pageRef = Page.page_OutStandingStatementDetail;
        pageRef.getParameters().put('partnerName', 'PAYMENT_TO');
        pageRef.getParameters().put('fromDate', '2015-06-30');
        pageRef.getParameters().put('toDate', '2015-08-01');
        pageRef.getParameters().put('partnerENName', 'PAYMENT_TO');
        pageRef.getParameters().put('relationship', Constants.PARTNER_RELATIONSHIP);
        pageRef.getParameters().put('currency', 'USD');
        pageRef.getParameters().put('strWkid', String.valueOf(hblBuying2.Id));
        pageRef.getParameters().put('searchType', 'SHIPMENTORDER');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementDetailController controller = new OutStandingStatementDetailController();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
        
        //System.assert(controller.lstSTID.size() > 0);
    }
    
    private static testmethod void shouldReturnRecordForOutstandingDetailReport3() {
        PageReference pageRef = Page.page_OutStandingStatementDetail;
        pageRef.getParameters().put('partnerName', 'PAYMENT_TO');
        pageRef.getParameters().put('fromDate', '2015-06-30');
        pageRef.getParameters().put('toDate', '2015-08-01');
        pageRef.getParameters().put('partnerENName', 'PAYMENT_TO');
        pageRef.getParameters().put('relationship', Constants.PARTNER_RELATIONSHIP);
        pageRef.getParameters().put('currency', 'USD');
        pageRef.getParameters().put('strWkid', String.valueOf(hblBuying2.Id));
        pageRef.getParameters().put('searchType', 'INVOICING');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementDetailController controller = new OutStandingStatementDetailController();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void shouldReturnRecordForOutstandingDetailReport4() {
        List<AnkenMeisai__c> lstAnlen = [SELECT Id FROM AnkenMeisai__c];
        PageReference pageRef = Page.page_OutStandingStatementDetail;
        pageRef.getParameters().put('partnerName', 'PAYMENT_TO');
        pageRef.getParameters().put('fromDate', null);
        pageRef.getParameters().put('toDate', '2015-08-01');
        pageRef.getParameters().put('partnerENName', 'PAYMENT_TO');
        pageRef.getParameters().put('relationship', Constants.PARTNER_RELATIONSHIP);
        pageRef.getParameters().put('currency', 'USD');
        pageRef.getParameters().put('strWkid', String.valueOf(hblBuying2.Id));
        pageRef.getParameters().put('searchType', 'INVOICING');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementDetailController controller = new OutStandingStatementDetailController();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void shouldReturnRecordForOutstandingDetailReport5() {
        List<AnkenMeisai__c> lstAnlen = [SELECT Id FROM AnkenMeisai__c];
        PageReference pageRef = Page.page_OutStandingStatementDetail;
        pageRef.getParameters().put('partnerName', 'PAYMENT_TO');
        pageRef.getParameters().put('fromDate', '2015-06-30');
        pageRef.getParameters().put('toDate', null);
        pageRef.getParameters().put('partnerENName', 'PAYMENT_TO');
        pageRef.getParameters().put('relationship', Constants.PARTNER_RELATIONSHIP);
        pageRef.getParameters().put('currency', 'USD');
        pageRef.getParameters().put('strWkid', String.valueOf(hblBuying2.Id));
        pageRef.getParameters().put('searchType', 'INVOICING');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementDetailController controller = new OutStandingStatementDetailController();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
    
    private static testmethod void shouldReturnRecordForOutstandingDetailReport() {
        List<AnkenMeisai__c> lstAnlen = [SELECT Id FROM AnkenMeisai__c];
        PageReference pageRef = Page.page_OutStandingStatementDetail;
        pageRef.getParameters().put('partnerName', 'PAYMENT_TO');
        pageRef.getParameters().put('fromDate', null);
        pageRef.getParameters().put('toDate', null);
        pageRef.getParameters().put('partnerENName', 'PAYMENT_TO');
        pageRef.getParameters().put('relationship', Constants.PARTNER_RELATIONSHIP);
        pageRef.getParameters().put('currency', 'USD');
        pageRef.getParameters().put('strWkid', String.valueOf(hblBuying2.Id));
        pageRef.getParameters().put('searchType', 'ETA');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        OutStandingStatementDetailController controller = new OutStandingStatementDetailController();
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
        
        //System.assert(controller.lstSTID.size() > 0);
    }
}