force-app/main/default/objects/Account/fields/Business_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Business_Relationship__c</fullName>
    <inlineHelpText>Choose Customer or Partner; if choose Customer, charge amount can be shown on local invoice and Customer Invoice Summary Report. If choose Partner, charge amount can be shown on D/N, C/N and Partner Outstanding Statement Report.</inlineHelpText>
    <label>Business Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>3rd Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/Anken__c.field-meta.xml
<CustomField>
    <fullName>Anken__c</fullName>
    <label>H B/L SHIPMENT ID</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>Anken</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>BuyDifferentiation__c</fullName>
    <formula>BuyInTaxAmountJPY__c - Siharaigaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Buying(Local)=Amount Buying including Tax(Local)-Amount Paid-Buying(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF BUYING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This will appear in Debit Note to local customer.</inlineHelpText>
    <label>DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/InsatuyouSyohin__c.field-meta.xml
<CustomField>
    <fullName>InsatuyouSyohin__c</fullName>
    <inlineHelpText>Used for Invoice and Quotation for local customers. If this field is blank, it will refer the Service Name At Print(Local) in Service Master Object</inlineHelpText>
    <label>PRICING NAME AT PRINT(LOCAL)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/NyukinKakuninzumi__c.field-meta.xml
<CustomField>
    <fullName>NyukinKakuninzumi__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only use when Full Amount is Paid. Box is checked, below updates processed 1.Amount Paid-Selling(Local):Syn with Amount Selling including Tax(Local) 2.Amount Paid-Selling(USD):Syn with Amount Selling including Tax(USD) 3.Unpaid Balance of Selling:&apos;0&apos;</inlineHelpText>
    <label>PAYMENT CONFIRMED-SELLING</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/PartnerCredit__c.field-meta.xml
<CustomField>
    <fullName>PartnerCredit__c</fullName>
    <formula>IF (CONTAINS(TEXT(PaymentTo__r.Business_Relationship__c), &apos;Partner&apos;),BuyAmountUSD__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/PartnerDebit__c.field-meta.xml
<CustomField>
    <fullName>PartnerDebit__c</fullName>
    <formula>IF ( CONTAINS(TEXT(Seikyusaki__r.Business_Relationship__c), &apos;Partner&apos;),SellAmountUSD__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Debit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/PartnerSeisan__c.field-meta.xml
<CustomField>
    <fullName>PartnerSeisan__c</fullName>
    <formula>IF ( CONTAINS(TEXT(Seikyusaki__r.Business_Relationship__c), &apos;Partner&apos;),
	Seikyusaki__r.Name,
	IF (CONTAINS(TEXT(PaymentTo__r.Business_Relationship__c), &apos;Partner&apos;), 
		PaymentTo__r.Name , 
		&apos;国内請求先&apos;
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>請求先と支払先の「種別」を見て、海外パートナーの取引先名を表示しています。
どちらも国内の場合は「国内」が表示されます。</inlineHelpText>
    <label>PARTNER INVOLVEMENT(INVOICE/PAYMENT TO)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/PartnerSeisanUSD__c.field-meta.xml
<CustomField>
    <fullName>PartnerSeisanUSD__c</fullName>
    <formula>IF ( AND(CONTAINS(TEXT(Seikyusaki__r.Business_Relationship__c), &apos;Partner&apos;), CONTAINS(TEXT(PaymentTo__r.Business_Relationship__c), &apos;Partner&apos;)), SellAmountUSD__c - BuyAmountUSD__c, IF ( CONTAINS(TEXT(Seikyusaki__r.Business_Relationship__c), &apos;Partner&apos;), SellAmountUSD__c, IF (CONTAINS(TEXT(PaymentTo__r.Business_Relationship__c), &apos;Partner&apos;), -1 * BuyAmountUSD__c, 10 )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>請求先と支払先の「種別」を見て、海外パートナーとのバランスの金額(USD)を表示します。
どちらも国内の場合は0で表示されます。</inlineHelpText>
    <label>BALANCE(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>To search available Bank Account list, please tab the mouse point on top of the company name in Payment to</inlineHelpText>
    <label>PAYMENT TO-BUYING</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>CustomerB2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bill (PAYMENT TO-BUYING)</relationshipLabel>
    <relationshipName>PaymentTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SalesAccountedDate__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDate__c</fullName>
    <formula>Anken__r.SalesAccountedDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Accounted Date(will be deleted)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SalesAccountedDateInvoicing__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDateInvoicing__c</fullName>
    <label>SALES ACCOUNTED DATE-INVOICING</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Seikyusaki__c.field-meta.xml
<CustomField>
    <fullName>Seikyusaki__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Export and Not EXW--&gt;Set shipper
Export and EXW--&gt;Set Partner
Import and Not DDP/DDU--&gt;Set Consignee
Import &amp; DDP/DDU--&gt;Set Partner</inlineHelpText>
    <label>INVOICE TO</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerB2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS BILL (INVOICE TO)</relationshipLabel>
    <relationshipName>Seikyusakis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SellDifferentiation__c.field-meta.xml
<CustomField>
    <fullName>SellDifferentiation__c</fullName>
    <formula>SellInTaxAmountJPY__c - Nyukingaku__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Selling(Local)=Amount Selling including Tax(Local)-Amount Paid-Selling(Local)</inlineHelpText>
    <label>UNPAID BALANCE OF SELLING</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/SiharaiKakuninzumi__c.field-meta.xml
<CustomField>
    <fullName>SiharaiKakuninzumi__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only use when full amount is paid. Check box is checked, below updates processed 1.Amount Paid-Buying(Local):Syn with Amount Buying including Tax(Local) 2.Amount Paid-Buying(USD):Syn with Amount Buying including Tax(USD) 3.Unpaid Balance of Buying:&apos;0&apos;</inlineHelpText>
    <label>PAYMENT CONFIRMED-BUYING</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Suryo__c.field-meta.xml
<CustomField>
    <fullName>Suryo__c</fullName>
    <inlineHelpText>Multiplied to Unit Price of Selling(Buying) and automatically calculates Total Amount of Selling(Buying).</inlineHelpText>
    <label>CHARGE UNIT (TOTAL)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/UNPAID_BALANCE_OF_BUYING_USD__c.field-meta.xml
<CustomField>
    <fullName>UNPAID_BALANCE_OF_BUYING_USD__c</fullName>
    <formula>BuyInTaxAmountUSD__c - AMOUNT_PAID_BUYING_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Buying(FCY)=Amount Buying including Tax(FCY)-Amount Paid-Buying(FCY)</inlineHelpText>
    <label>UNPAID BALANCE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/UNPAID_BALANCE_OF_SELLING_USD__c.field-meta.xml
<CustomField>
    <fullName>UNPAID_BALANCE_OF_SELLING_USD__c</fullName>
    <formula>SellInTaxAmount_USD__c - AMOUNT_PAID_SELLING_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unpaid Balance of Selling(FCY)=Amount Selling including Tax(FCY)-Amount Received from Customer(FCY)</inlineHelpText>
    <label>Unreceived Balance of Selling(FCY)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL_Number_SEA_AIR__c.field-meta.xml
<CustomField>
    <fullName>HBL_Number_SEA_AIR__c</fullName>
    <formula>IF ( ISNULL(HBL__c) || ISBLANK(HBL__c) ,  HAWB__c , HBL__c)</formula>
    <label>HBL Number（SEAorAIR）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/MBL_Number_SEA_AIR__c.field-meta.xml
<CustomField>
    <fullName>MBL_Number_SEA_AIR__c</fullName>
    <formula>IF (ISNULL(Master_B_L__c) || ISBLANK(Master_B_L__c) , MAWB__c , Master_B_L__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MBL Number（SEAorAIR）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/partnerSeisanTani__c.field-meta.xml
<CustomField>
    <fullName>partnerSeisanTani__c</fullName>
    <formula>&apos;WKID ： &apos; &amp; Name &amp;  &apos;　&apos; &amp;
&apos;HBL ： &apos;  &amp; HBL_Number_SEA_AIR__c  &amp; &apos;　&apos;&amp;
&apos;MBL ： &apos;  &amp; MBL_Number_SEA_AIR__c &amp;&apos;　&apos;&amp;  
&apos;ETA ： &apos;  &amp; TEXT(ETA__c) &amp; &apos;　&apos; &amp;
&apos;ETD ： &apos;  &amp; TEXT(ETD__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>S.T ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/SalesAccountedDate__c.field-meta.xml
<CustomField>
    <fullName>SalesAccountedDate__c</fullName>
    <description>SALES ACCOUNTED DATE</description>
    <inlineHelpText>When any of following date is input, the latest date is selected as sales accounted date. 
Import – Shipment Order: ETA, C.Clearance:Permit Date, Delivery:Delivery Date. 
Export- Delivery:Delivery Date, C.Clearance:Permit Date, Shipment Order:ETD.</inlineHelpText>
    <label>SALES ACCOUNTED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/UNPAID_BALANCE_OF_BUYING_USD__c.field-meta.xml
<CustomField>
    <fullName>UNPAID_BALANCE_OF_BUYING_USD__c</fullName>
    <label>UNPAID BALANCE OF BUYING(USD)</label>
    <summarizedField>AnkenMeisai__c.UNPAID_BALANCE_OF_BUYING_USD__c</summarizedField>
    <summaryForeignKey>AnkenMeisai__c.Anken__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/UNPAID_BALANCE_OF_SELLING_USD__c.field-meta.xml
<CustomField>
    <fullName>UNPAID_BALANCE_OF_SELLING_USD__c</fullName>
    <label>UNRECEIVED BAL OF SELL-COMBINED(USD)</label>
    <summarizedField>AnkenMeisai__c.UNPAID_BALANCE_OF_SELLING_USD__c</summarizedField>
    <summaryForeignKey>AnkenMeisai__c.Anken__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/QUOTATION.recordType-meta.xml
<RecordType>
    <fullName>QUOTATION</fullName>
    <active>false</active>
    <description>Choose this record type to create a new Quotation for any kinds of shipment.</description>
    <label>Quotation</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/classes/OutStandingStatementDetailController.cls
public with sharing class OutStandingStatementDetailController {
    public transient String partnerName {get;set;}
    public transient String partnerEnglishName {get;set;}
    public transient String businessRelationship {get;set;}
    public transient Decimal totalDebit {get;set;}
    public transient Decimal totalCredit {get;set;}
    public transient Decimal totalBalance {get;set;}
    public transient Decimal totalDebitLocal {get;set;}
    public transient Decimal totalCreditLocal {get;set;}
    public transient Decimal totalBalanceLocal {get;set;}
    public transient String currentDate {get;set;}
    public transient String reportDate {get;set;}
    public transient String period {get;set;}
    public transient Decimal recordQuantity {get;set;}
    public transient String currencyType {get; set;}
    public transient String searchType {get; set;}
    public transient Map<String, ReportLocal> mapLocal {get; set;}
    public transient String strWkid {get; set;}
    public List<AnkenDetail> lstAKMDetail {get; set;}
    
    Map<String,ReportDetailWrapper> mapTemp {get;set;}
    
    public transient List<ReportDetailWrapper> lstSTID {
        get {
            List<ReportDetailWrapper> lstMySTIDs = new List<ReportDetailWrapper>();
            Decimal i = 1;
            if (!mapTemp.isEmpty()) {
                for (ReportDetailWrapper item : mapTemp.values()) {
                    recordQuantity += item.myQuantity;
                    item.index = i;
					lstMySTIDs.add(item);                    
                    i++;
                }    
            }
            
            return lstMySTIDs;
        }
        set;
    }
    
    public OutStandingStatementDetailController() {
        totalDebit = 0;
        totalCredit = 0;
        totalBalance = 0;
        totalDebitLocal = 0;
        totalCreditLocal = 0;
        totalBalanceLocal = 0;
        recordQuantity = 0;
        lstAKMDetail = new List<AnkenDetail>();
        Boolean isDisplayDetail = false;
        
        mapLocal = new Map<String, ReportLocal>();
        
        reportDate = String.valueOf(System.today());
        
        currentDate = String.valueOf(Date.today());
        String fromDate = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('fromDate'));
        String toDate = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('toDate'));
        partnerName = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('partnerName'), 'UTF-8'));
        partnerEnglishName = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('partnerENName'), 'UTF-8'));
        businessRelationship = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('relationship'), 'UTF-8'));
		currencyType = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('currency'), 'UTF-8'));
        searchType = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('searchType'), 'UTF-8'));
        strWkid = StringUtils.escapeSingleQuotes(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('strWkid'), 'UTF-8'));
        List<String> lstWkid = new List<String>();
        lstWkid = strWkid.split(',');
        String strId = '';
        for(String idAnken : lstWkid){
            strId += '\'' + idAnken + '\', ';
        }
        strId = strId.removeEnd(', ');
        String soqlComm = 'SELECT Id, Name, PartnerSeisan__c, Anken__r.partnerSeisanTani__c, Anken__r.ETA__c, ' +
            '   Anken__r.Name, Anken__r.HBL_Number_Sea_Air__c, Anken__r.MBL_Number_Sea_Air__c, Anken__r.ETD__c, ' +
            '   PartnerDebit__c, PartnerCredit__c, PartnerSeisanUSD__c, PaymentTo__r.Business_Relationship__c, ' +  
            '   PaymentTo__r.Name, Seikyusaki__r.Business_Relationship__c, Seikyusaki__r.Name, ' +
            '	InsatuyouSyohin__c, Description__c , Suryo__c, ' +
            '   BuyDifferentiation__c, SellDifferentiation__c, SalesAccountedDate__c, SalesAccountedDateInvoicing__c, ' +
            '   UNPAID_BALANCE_OF_BUYING_USD__c, UNPAID_BALANCE_OF_SELLING_USD__c, SiharaiKakuninzumi__c, NyukinKakuninzumi__c' +
            ' FROM AnkenMeisai__c ' +
            ' WHERE Anken__r.RecordType.DeveloperName != \'Quotation\'' + 
            //' AND Id IN (' + strId + ') ' +
            '   AND ((PaymentTo__r.Business_Relationship__c = \'' + businessRelationship + '\'' +
            '           AND PaymentTo__r.Name = \'' + partnerName + '\'' +
            '           AND SiharaiKakuninzumi__c = false AND (UNPAID_BALANCE_OF_BUYING_USD__c != 0 OR BuyDifferentiation__c != 0))' +
            '       OR (Seikyusaki__r.Business_Relationship__c = \'' + businessRelationship + '\'' +
            '           AND Seikyusaki__r.Name = \'' + partnerName + '\'' +
            '           AND NyukinKakuninzumi__c = false AND (UNPAID_BALANCE_OF_SELLING_USD__c != 0 OR SellDifferentiation__c != 0)))' +
            '   AND Anken__r.status__c NOT IN (\'' + PicklistReference.CANCELLED_ST + '\',' + 
            '       \'' + PicklistReference.COMPLETED_ST + '\',' +
            '       \'' + PicklistReference.TEMPORARY_UNLOCK_FOR_ACCOUNTING_PURPOSE_ST + '\')';

        String filter = '';
        if (fromDate != null && toDate != null) {
            //filter = ' AND (Anken__r.ETD__c >= ' + fromDate + ' AND Anken__r.ETD__c <= ' + toDate + ')';
            if(searchType.equals('ETD')){
                filter = ' AND (Anken__r.ETD__c >= ' + String.valueOf(fromDate) + ' AND Anken__r.ETD__c <= ' + String.valueOf(toDate) + ')';
            }
            else if(searchType.equals('ETA')){
                filter = ' AND (Anken__r.ETA__c >= ' + String.valueOf(fromDate) + ' AND Anken__r.ETA__c <= ' + String.valueOf(toDate) + ')';
            }
            else if(searchType.equals('SHIPMENTORDER')){
                filter = ' AND (Anken__r.SalesAccountedDate__c >= ' + String.valueOf(fromDate) + ' AND Anken__r.SalesAccountedDate__c <= ' + String.valueOf(toDate) + ')';
            }
            else if(searchType.equals('INVOICING')){
                filter = ' AND (SalesAccountedDateInvoicing__c >= ' + String.valueOf(fromDate) + ' AND SalesAccountedDateInvoicing__c <= ' + String.valueOf(toDate) + ')';
            }
            
            period = 'From ' + fromDate + ' To ' + toDate;
        }        
        else if (fromDate != null && toDate == null) {
            //filter = ' AND Anken__r.ETD__c >= ' + fromDate;
            if(searchType.equals('ETD')){
                filter = ' AND Anken__r.ETD__c >= ' + String.valueOf(fromDate);
            }
            else if(searchType.equals('ETA')){
                filter = ' AND Anken__r.ETA__c >= ' + String.valueOf(fromDate);
            }
            else if(searchType.equals('SHIPMENTORDER')){
                filter = ' AND Anken__r.SalesAccountedDate__c >= ' + String.valueOf(fromDate);
            }
            else if(searchType.equals('INVOICING')){
                filter = ' AND SalesAccountedDateInvoicing__c >= ' + String.valueOf(fromDate);
            }
            period = 'From ' + fromDate;
        }
        else if (fromDate == null && toDate != null) {
            //filter = ' AND Anken__r.ETD__c <= ' + toDate;
            if(searchType.equals('ETD')){
                filter = ' AND Anken__r.ETD__c <= ' + String.valueOf(toDate);
            }
            else if(searchType.equals('ETA')){
                filter = ' AND Anken__r.ETA__c <= ' + String.valueOf(toDate);
            }
            else if(searchType.equals('SHIPMENTORDER')){
                filter = ' AND Anken__r.SalesAccountedDate__c <= ' + String.valueOf(toDate);
            }
            else if(searchType.equals('INVOICING')){
                filter = ' AND SalesAccountedDateInvoicing__c <= ' + String.valueOf(toDate);
            }
            period = 'To ' + toDate;
        }
        
        if(!String.isBlank(strWkid)){
            filter +=' AND Id IN (' + strId + ') ';
            isDisplayDetail = true;
        }
        
        if (filter != '') {
            soqlComm += filter;
        }
        soqlComm += ' ORDER BY PartnerSeisan__c, Anken__r.Name ';

        List<AnkenMeisai__c> lstAKM = new List<AnkenMeisai__c>();
        
        if (PermissionValidationUtil.isAccessibleHBL() && PermissionValidationUtil.isAccessibleHBLBuying()) {
            lstAKM = Database.query(soqlComm);
            lstSTID = new List<ReportDetailWrapper>();
            mapTemp = new Map<String,ReportDetailWrapper>();

            for (AnkenMeisai__c item : lstAKM) {
                String strSTID = item.Anken__r.partnerSeisanTani__c;
                Decimal debit = 0;
                Decimal credit = 0;
                Decimal balance = 0;
                Decimal debitLocal = 0;
                Decimal creditLocal = 0;
                Decimal balanceLocal = 0;
                String wkid = item.Anken__r.Name;
                String hbl = item.Anken__r.HBL_Number_Sea_Air__c;
                String mbl = item.Anken__r.MBL_Number_Sea_Air__c;
                String strEtd = String.valueof(item.Anken__r.ETD__c);
                String strEta = String.valueof(item.Anken__r.ETA__c);
                
                if(!String.isEmpty(strEtd)){
                    Date etd = item.Anken__r.ETD__c;
                    strEtd = etd.day() + '/' + etd.month() + '/' + etd.year();
                }
                if(!String.isEmpty(strEta)){
                    Date eta = item.Anken__r.ETA__c;
                    strEta = eta.day() + '/' + eta.month() + '/' + eta.year();
                }

                if (businessRelationship.equals(item.Seikyusaki__r.Business_Relationship__c)
                        && item.NyukinKakuninzumi__c == false 
                        && (item.UNPAID_BALANCE_OF_SELLING_USD__c != 0 || item.SellDifferentiation__c != 0)
                        && item.Seikyusaki__r.Name.equals(partnerName)) {
                    debit = item.UNPAID_BALANCE_OF_SELLING_USD__c;
                    debitLocal = item.SellDifferentiation__c;
                }
                    
                else if (businessRelationship.equals(item.PaymentTo__r.Business_Relationship__c)
                        && item.SiharaiKakuninzumi__c == false 
                        && (item.UNPAID_BALANCE_OF_BUYING_USD__c != 0 || item.BuyDifferentiation__c != 0)
                        && item.PaymentTo__r.Name.equals(partnerName)) {
                    credit = item.UNPAID_BALANCE_OF_BUYING_USD__c;
                    creditLocal = item.BuyDifferentiation__c;
                }
                
                balance = debit - credit;
                balanceLocal = debitLocal - creditLocal;
                
                if (mapTemp.isEmpty()) {
                    ReportDetailWrapper temp = new ReportDetailWrapper();
                    setSTIDData(temp, strSTID, debit, credit, balance, wkid, hbl, mbl, strEta, strEtd);
                    temp.myQuantity = 1;
                    mapTemp.put(temp.stid,temp);
                }
                else if (mapTemp.containsKey(strSTID)) {
                    mapTemp.get(strSTID).debit += debit;
                    mapTemp.get(strSTID).credit += credit;
                    mapTemp.get(strSTID).balance += balance;
                    mapTemp.get(strSTID).myQuantity += 1;
                }
                else {
                    ReportDetailWrapper temp = new ReportDetailWrapper();
                    setSTIDData(temp, strSTID, debit, credit, balance, wkid, hbl, mbl, strEta, strEtd);
                    temp.myQuantity = 1;
                    mapTemp.put(temp.stid,temp);
                }
                
                if(!mapLocal.containsKey(wkid)){
                    mapLocal.put(wkid, new ReportLocal());
                }
                
                String strSaleDate = String.valueOf(item.SalesAccountedDate__c);
                if(!String.isEmpty(strSaleDate)){
                    Date saleDate = item.SalesAccountedDate__c;
                    strSaleDate = saleDate.day() + '/' + saleDate.month() + '/' + saleDate.year();
                    mapLocal.get(wkid).salesAccountedDate = strSaleDate;
                }
                
                mapLocal.get(wkid).creditLocal += creditLocal;
                mapLocal.get(wkid).debitLocal += debitLocal;
                mapLocal.get(wkid).balanceLocal += balanceLocal;
                
                if(isDisplayDetail){
                    lstAKMDetail.add(new AnkenDetail(item, debit, debitLocal, credit, creditLocal, balance, balanceLocal));
                }

                totalDebit += debit;
                totalCredit += credit;
                totalBalance += balance;
                
                totalDebitLocal += debitLocal;
                totalCreditLocal += creditLocal;
                totalBalanceLocal += balanceLocal;
            }
        }
    }
    
    private void setSTIDData(ReportDetailWrapper temp, String stid, Decimal debit, 
                             Decimal credit, Decimal balance,String wkid,String hbl, 
                             String mbl,String eta, String etd) {
        temp.stid = stid;
        temp.debit = debit;
        temp.credit = credit;
        temp.balance = balance;
        temp.wkid = wkid;
        temp.hbl = hbl;
        temp.mbl = mbl;
        temp.eta = eta;
        temp.etd = etd;
    }
   	
    public class ReportLocal{
        public Decimal creditLocal {get; set;}
        public Decimal debitLocal {get; set;}
        public Decimal balanceLocal {get; set;}
        public String salesAccountedDate {get; set;}
        public ReportLocal(){
            this.creditLocal = 0;
            this.debitLocal = 0;
            this.balanceLocal = 0;
            this.salesAccountedDate = '';
        }
        
        public ReportLocal(Decimal dmlCredit, Decimal dmlDebit, Decimal dmlBalance, String strSalesAccountedDate){
            this.creditLocal = dmlCredit;
            this.debitLocal = dmlDebit;
            this.balanceLocal = dmlBalance;
            this.salesAccountedDate = strSalesAccountedDate;
        }
    }
    
    public class AnkenDetail{
        public AnkenMeisai__c anken {get; set;}
        public Decimal debitUSD {get; set;}
        public Decimal debitLocal {get; set;}
        public Decimal creditUSD {get; set;}
        public Decimal creditLocal {get; set;}
        public Decimal balanceUSD {get; set;}
        public Decimal balanceLocal {get; set;}
        public AnkenDetail(){
            this.anken = new AnkenMeisai__c();
            this.debitUSD = 0;
            this.debitLocal = 0;
            this.creditUSD = 0;
            this.creditLocal = 0;
            this.balanceUSD = 0;
            this.balanceLocal = 0;
        }
        public AnkenDetail(AnkenMeisai__c objAnken, Decimal dmlDebitUSD, Decimal dmlDebitLocal, 
                           Decimal dmlCreditUSD, Decimal dmlCreditLocal, Decimal dmlBalanceUSD, Decimal dmlBanlanceLocal){
            this.anken = objAnken;
            this.debitUSD = dmlDebitUSD;
            this.debitLocal = dmlDebitLocal;
            this.creditUSD = dmlCreditUSD;
            this.creditLocal = dmlCreditLocal;
            this.balanceUSD = dmlBalanceUSD;
            this.balanceLocal = dmlBanlanceLocal;
        }
    }
}