force-app/main/default/objects/Account/fields/Business_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Business_Relationship__c</fullName>
    <inlineHelpText>Choose Customer or Partner; if choose Customer, charge amount can be shown on local invoice and Customer Invoice Summary Report. If choose Partner, charge amount can be shown on D/N, C/N and Partner Outstanding Statement Report.</inlineHelpText>
    <label>Business Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>3rd Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/GoodsPOProduct__c.object-meta.xml
<CustomObject>
    <label>Goods P/O+Product</label>
    <nameField>
        <displayFormat>GPPD-{000000}</displayFormat>
        <label>GOODS P/O+PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods P/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GoodsPOProduct__c/fields/GoodsPOID__c.field-meta.xml
<CustomField>
    <fullName>GoodsPOID__c</fullName>
    <label>GOODS PURCHASING ORDER ID</label>
    <referenceTo>GoodsPurchasingOrder__c</referenceTo>
    <relationshipLabel>GOODS P/O+PRODUCT</relationshipLabel>
    <relationshipName>GoodsPOProduct</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>GOODS P/O+PRODUCT</relationshipLabel>
    <relationshipName>GoodsPOProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GoodsPurchasingOrder__c/GoodsPurchasingOrder__c.object-meta.xml
<CustomObject>
    <label>Goods P/O</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>GOODS PURCHASING ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods P/O</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GoodsPurchasingOrder__c/fields/GoodsPurchasingOrder__c.field-meta.xml
<CustomField>
    <fullName>GoodsPurchasingOrder__c</fullName>
    <label>GOODS PURCHASING ORDER STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OrderStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GoodsPurchasingOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>GOODS PURCHASING ORDER</relationshipLabel>
    <relationshipName>GoodsPurchasingOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/DeliveryServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryServiceBillingFreqType__c</fullName>
    <label>Delivery Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GuaranteeServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>GuaranteeServiceBillingFreqType__c</fullName>
    <label>Guarantee Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/InstallationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>InstallationServiceBillingFreqType__c</fullName>
    <label>Installation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/MaintenanceServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>MaintenanceServiceBillingFreqType__c</fullName>
    <label>Maintenance Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RelocationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>RelocationServiceBillingFreqType__c</fullName>
    <label>Relocation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ReplacementServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>ReplacementServiceBillingFreqType__c</fullName>
    <label>Replacement Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SetupServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SetupServiceBillingFreqType__c</fullName>
    <label>Setup Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SubscriptionChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionChargeBillingFreqType__c</fullName>
    <label>Subscription Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SupportServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SupportServiceBillingFreqType__c</fullName>
    <label>Support Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UsageChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>UsageChargeBillingFreqType__c</fullName>
    <label>Usage Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Air_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Air_HBL_No_Prefix__c</fullName>
    <label>Air HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ocean_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Ocean_HBL_No_Prefix__c</fullName>
    <description>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</description>
    <inlineHelpText>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</inlineHelpText>
    <label>Ocean HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/BillingFrequencyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Time Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>3 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>4 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Ad-Hoc</fullName>
    </customValue>
    <customValue>
        <fullName>No Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Times Billing</fullName>
        <isActive>false</isActive>
        <label>Multi-Times Billing</label>
    </customValue>
    <masterLabel>Billing Frequency Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OrderStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>On-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>In Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Full Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Partial Returned</fullName>
    </customValue>
    <customValue>
        <fullName>Full Returned</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>ORDER &amp; CONTRACT STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/POSummaryNoteNewControllerTest.cls
@isTest
private class POSummaryNoteNewControllerTest {
	private static GoodsPurchasingOrder__c gPurchasingOrder {get; set;}
	static{
		Custom_Application_Config__c config =  new Custom_Application_Config__c(Disabled_Trigger__c = true);
        FlsService.doInsert(config);
        Map<String, Object> additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
            'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Ocean_HBL_No_Prefix__c' => 'OCEAN', 
            'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Air_HBL_No_Prefix__c' => 'AIR',
            'Company_Country__c' => 'JAPAN', 'Local_Currency__c' => 'JPY',
            'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
		TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);

		Account acc = createAccount();
		PRODUCT__c product = new PRODUCT__c(MaintenanceServiceBillingFreqType__c = 'Continuous Billing',
                                           GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                 InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                 RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                 SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                 UsageChargeBillingFreqType__c = 'Continuous Billing');
        FlsService.doInsert(product);

		gPurchasingOrder = new GoodsPurchasingOrder__c();
        FlsService.doInsert(gPurchasingOrder);

		GoodsPOProduct__c gp = new GoodsPOProduct__c(
			GoodsPOID__c = gPurchasingOrder.Id,
			ProductID__c = product.Id);
        FlsService.doInsert(gp);
	}
	
	@isTest static void test_method_one() {
		// Implement test code
		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', gPurchasingOrder.Id);
			POSummaryNoteNewController ctrl = new POSummaryNoteNewController();
			String  totalAmountVND = ctrl.total.getTotalAmountVND();
			String  getTotalAmountTaxVND = ctrl.total.getTotalAmountTaxVND();
			String  getTotalAmountIncludeTaxVND = ctrl.total.getTotalAmountIncludeTaxVND();
			String  getNetPurchaseValueVND = ctrl.listGoodPOProductNode[0].getNetPurchaseValueVND();
			String  getVATVND = ctrl.listGoodPOProductNode[0].getVATVND();
			String  getAmountVND = ctrl.listGoodPOProductNode[0].getAmountVND();
			String  getTotalAmountVND = ctrl.listGoodPOProductNode[0].getTotalAmountVND();
			String  getAmountTaxVND = ctrl.listGoodPOProductNode[0].getAmountTaxVND();
			system.assert(gPurchasingOrder.Id != null);
		Test.stopTest();
	}
	
	

	private static Account createAccount(){
        Account accountSupplier = new Account(
            Name = 'accountSupplier',
            EnglishCompanyName__c = 'accountSupplier',
            Business_Relationship__c = '3rd Vendor');
        FlsService.doInsert(accountSupplier);
        return accountSupplier;
    }
	
}