force-app/main/default/objects/Account/fields/Business_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Business_Relationship__c</fullName>
    <inlineHelpText>Choose Customer or Partner; if choose Customer, charge amount can be shown on local invoice and Customer Invoice Summary Report. If choose Partner, charge amount can be shown on D/N, C/N and Partner Outstanding Statement Report.</inlineHelpText>
    <label>Business Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>3rd Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProdSvcPricingQuoteLine__c/ProdSvcPricingQuoteLine__c.object-meta.xml
<CustomObject>
    <label>PROD/SVC+Quote Line</label>
    <nameField>
        <displayFormat>PRQL-{000000}</displayFormat>
        <label>PROD/SVC PRICING+QUOTE LINE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PROD/SVC+Quote Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdSvcPricingQuoteLine__c/fields/ProdPricingID__c.field-meta.xml
<CustomField>
    <fullName>ProdPricingID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PROD PRICING ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipName>ProdSrvPricingQuoteLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdSvcPricingQuoteLine__c/fields/QuoteLineID__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineID__c</fullName>
    <label>QUOTE LINE ID</label>
    <referenceTo>QuoteLine__c</referenceTo>
    <relationshipName>ProdSrvPricinggQuoteLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/DeliveryServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryServiceBillingFreqType__c</fullName>
    <label>Delivery Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GuaranteeServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>GuaranteeServiceBillingFreqType__c</fullName>
    <label>Guarantee Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/InstallationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>InstallationServiceBillingFreqType__c</fullName>
    <label>Installation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/MaintenanceServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>MaintenanceServiceBillingFreqType__c</fullName>
    <label>Maintenance Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RelocationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>RelocationServiceBillingFreqType__c</fullName>
    <label>Relocation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ReplacementServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>ReplacementServiceBillingFreqType__c</fullName>
    <label>Replacement Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SetupServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SetupServiceBillingFreqType__c</fullName>
    <label>Setup Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SubscriptionChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionChargeBillingFreqType__c</fullName>
    <label>Subscription Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SupportServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SupportServiceBillingFreqType__c</fullName>
    <label>Support Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UsageChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>UsageChargeBillingFreqType__c</fullName>
    <label>Usage Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote.</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>QUOTE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/RequesterCompany__c.field-meta.xml
<CustomField>
    <fullName>RequesterCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REQUESTER COMPANY</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QUOTE</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/DomesticLogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>DomesticLogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Domestic Logistics Service</description>
    <label>Domestic Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/QuoteLine__c/QuoteLine__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QTLN-{000000}</displayFormat>
        <label>QUOTE LINE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <defaultValue>$Setup.Site_Custom_Settings__c.Local_Currency__c</defaultValue>
    <label>CURRENCY-SELLING</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>QUOTE ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>QUOTE LINE</relationshipLabel>
    <relationshipName>QuoteLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/RequesterCompany__c.field-meta.xml
<CustomField>
    <fullName>RequesterCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QUOTE LINE(REQUESTER COMPANY)</relationshipLabel>
    <relationshipName>QuoteLine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/recordTypes/DomesticLogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>DomesticLogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Logistics Service</description>
    <label>Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Air_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Air_HBL_No_Prefix__c</fullName>
    <label>Air HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ocean_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Ocean_HBL_No_Prefix__c</fullName>
    <description>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</description>
    <inlineHelpText>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</inlineHelpText>
    <label>Ocean HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/BillingFrequencyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Time Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>3 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>4 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Ad-Hoc</fullName>
    </customValue>
    <customValue>
        <fullName>No Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Times Billing</fullName>
        <isActive>false</isActive>
        <label>Multi-Times Billing</label>
    </customValue>
    <masterLabel>Billing Frequency Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
        <default>true</default>
        <label>VND</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>PHP</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <masterLabel>CURRENCY</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CopyQuotationControllerTest.cls
@isTest
private class CopyQuotationControllerTest {
    
    private static List<Quote__c> quotes{get; set;}
    private static List<QuoteLine__c> quoteLineItems = new List<QuoteLine__c>();
    private static List<Account> listAccount = new List<Account>();
    
    static{
        Custom_Application_Config__c config =  new Custom_Application_Config__c(Disabled_Trigger__c = true);
		FlsService.doInsert(config);
        // tao account
        // 
        Map<String, Object> additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
            'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Ocean_HBL_No_Prefix__c' => 'OCEAN', 
            'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Air_HBL_No_Prefix__c' => 'AIR',
            'Company_Country__c' => 'JAPAN', 'Local_Currency__c' => 'JPY',
            'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
                TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);
        
        listAccount = createAccounts();
        
    }
    @isTest static void test_fullCopy() {
        
        String domesticquote = Schema.SObjectType.Quote__c.getRecordTypeInfosByDeveloperName().get('DomesticLogisticsServiceQuote').getRecordTypeId();
        Quote__c quote = createQuote(domesticquote, listAccount[0].Id);
        List<QuoteLine__c> lineItems = createQuoteLines(quote.Id);
        PRODUCT__c product = new PRODUCT__c(GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                            InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                            RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                            SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                            UsageChargeBillingFreqType__c = 'Continuous Billing',
                                            MaintenanceServiceBillingFreqType__c = 'Continuous Billing');
		FlsService.doInsert(product);
        ProdSvcPricingQuoteLine__c pricingItem = new ProdSvcPricingQuoteLine__c(
            ProdPricingID__c = product.Id,
            QuoteLineID__c = lineItems[0].Id
        );
        Test.startTest();
        
        String newQuoteId = CopyQuotationController.cloneFull(quote.Id);
        System.assert(newQuoteId != null);
        Test.stopTest();
    }
    
    private static List<Account> createAccounts(){
        List<Account> lst = new List<Account>();
        Account accountVender = new Account(
            Name = 'Account vender',
            EnglishCompanyName__c = 'Account vender',
            Business_Relationship__c = '3rd Vendor');
        Account accountPartner = new Account(
            Name = 'Account Partner',
            EnglishCompanyName__c = 'Account Partner',
            Business_Relationship__c = 'Partner');
        Account accountCustomer = new Account(
            Name = 'Account Customer',
            EnglishCompanyName__c = 'Account Customer',
            Business_Relationship__c = 'Customer');
        lst.add(accountVender);
        lst.add(accountPartner);
        lst.add(accountCustomer);
		FlsService.doInsert(lst);
        return lst;
    }
    
    private static Quote__c createQuote(String recordTypeIdArg, String accountIdArg){
        Quote__c quote = new Quote__c(
            RecordTypeId = recordTypeIdArg,
            RequesterCompany__c = accountIdArg);
		FlsService.doInsert(quote);
        return quote;
    }
    
    private static List<QuoteLine__c> createQuoteLines(String quoteId){
        List<QuoteLine__c> lineItems = new List<QuoteLine__c>();
        QuoteLine__c quoteLineVND = new QuoteLine__c(
            QuoteID__c = quoteId,
            CurrencySelling__c = 'VND'
        );
        QuoteLine__c quoteLineUSD = new QuoteLine__c(
            QuoteID__c = quoteId,
            CurrencySelling__c = 'USD'
        );
        
        lineItems.add(quoteLineVND);
        lineItems.add(quoteLineUSD);
		FlsService.doInsert(lineItems);
        return lineItems;
    }
    
}