force-app/main/default/objects/Account/fields/Business_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Business_Relationship__c</fullName>
    <inlineHelpText>Choose Customer or Partner; if choose Customer, charge amount can be shown on local invoice and Customer Invoice Summary Report. If choose Partner, charge amount can be shown on D/N, C/N and Partner Outstanding Statement Report.</inlineHelpText>
    <label>Business Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>3rd Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <inlineHelpText>When Container Type and Container Qnty is input, Container Information object is automatically created. Input Container/Seal No in the object accordingly.</inlineHelpText>
    <label>CONTAINER TYPE-1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ContainerNumber__c.field-meta.xml
<CustomField>
    <fullName>ContainerNumber__c</fullName>
    <inlineHelpText>Number in this field create the same number of Container Information object.</inlineHelpText>
    <label>CONTAINER QNTY-1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL__c.field-meta.xml
<CustomField>
    <fullName>HBL__c</fullName>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType1.recordType-meta.xml
<RecordType>
    <fullName>RecordType1</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Import Shipment.</description>
    <label>Ocean Import</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/fields/ProductSearch__c.field-meta.xml
<CustomField>
    <fullName>ProductSearch__c</fullName>
    <inlineHelpText>This is a key data when you are search the service master from H B/L Selling/Buying and M B/L(Consol)-Buying.</inlineHelpText>
    <label>CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCL輸入</fullName>
                <label>FCL Import</label>
            </value>
            <value>
                <fullName>FCL輸出</fullName>
                <label>FCL Export</label>
            </value>
            <value>
                <fullName>FCL三国間</fullName>
                <label>FCL Triangular Trade</label>
            </value>
            <value>
                <fullName>LCL輸入</fullName>
                <label>LCL Import</label>
            </value>
            <value>
                <fullName>LCL輸出</fullName>
                <label>LCL Export</label>
            </value>
            <value>
                <fullName>LCL三国間</fullName>
                <label>LCL Triangular Trade</label>
            </value>
            <value>
                <fullName>海外現地費用</fullName>
                <label>Oversea Local Charge</label>
            </value>
            <value>
                <fullName>通関輸入</fullName>
                <label>Import Custom Clearance</label>
            </value>
            <value>
                <fullName>通関輸出</fullName>
                <label>Export Custom Clearance</label>
            </value>
            <value>
                <fullName>エア</fullName>
                <label>AIR</label>
            </value>
            <value>
                <fullName>マスター按分</fullName>
                <label>Consolidation Cost Allocation</label>
            </value>
            <value>
                <fullName>ドレー</fullName>
                <label>Full Container Truck(Drayage)</label>
            </value>
            <value>
                <fullName>配送</fullName>
                <label>Delivery</label>
            </value>
            <value>
                <fullName>倉庫</fullName>
                <label>Warehouse</label>
            </value>
            <value>
                <fullName>実費</fullName>
                <label>Actual Expense</label>
            </value>
            <value>
                <fullName>Empty Container</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/recordTypes/FCL.recordType-meta.xml
<RecordType>
    <fullName>FCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with FCL Forwarding.</description>
    <label>FCL</label>
</RecordType>

force-app/main/default/objects/TariffMaster__c/recordTypes/LCL.recordType-meta.xml
<RecordType>
    <fullName>LCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with LCL Forwarding.</description>
    <label>LCL</label>
</RecordType>

force-app/main/default/classes/FMS_SortByCurrentSOControllerTest.cls
@isTest
private class FMS_SortByCurrentSOControllerTest {
    
    @testSetup static void setup() {
        Custom_Application_Config__c config =  new Custom_Application_Config__c(Disabled_Trigger__c = true);
		FlsService.doInsert(config);
        RecordType oceanImportRecordType = [Select Id from RecordType where DeveloperName = 'RecordType1'];
        Map<String, Object> additionalFields = new Map<String, Object> {'Business_Relationship__c' => Constants.CUSTOMER_RELATIONSHIP};
        Account account = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);

        additionalFields = new Map<String, Object> {'Name' => 'PARTNER001', 'Business_Relationship__c' => Constants.PARTNER_RELATIONSHIP};
        Account partner = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);

        additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
            'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233',
            'Logo_URL__c' => 'http://afr-solutions.com/logo.png',
            'Company_Country__c' => 'JAPAN', 'Local_Currency__c' => 'JPY',
            'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
        TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);

        additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => oceanImportRecordType.Id,
                                                                        'ContainerNumber__c' => 1, 'Container__c' => '40`DC',
                                                                        'HBL__c' => 'IMPORT01'};
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);

        additionalFields = new Map<String, Object> {'Name' => 'LCL', 'ProductSearch__c' => 'FCL輸入',
                                                'Subcategory__c' => '基本料金', 'Supplier__c' => account.Id,
                                                'EngProductSearch__c' => 'FCL Import', 'ProductFlag__c' => true};
        TariffMaster__c tariff = (TariffMaster__c) TestDataFactory.createSObject(new TariffMaster__c(), true, additionalFields);
        additionalFields = new Map<String, Object> {'Anken__c' => shipment.Id, 'curr__c' => 'JPY',
                                                'SerchSyubetu__c' => 'FCL輸入', 'Tariff__c' => tariff.Id,
                                                'Seikyusaki__c' => account.Id,
                                                'Selling_Tatekae__c' => false, 'SellTankaJPY__c' => 100};
        TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);

        // create H B/L Selling/Buying
        additionalFields = new Map<String, Object> {'Anken__c' => shipment.Id, 'curr__c' => 'JPY',
                                                'Tariff__c' => tariff.Id,
                                                'Seikyusaki__c' => partner.Id, 'SerchSyubetu__c' => 'FCL輸入',
                                                'Cost_Allocation_Catetory__c' => 'Partner Cost allocation'};
        TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);
        System.assert(true);
    }
	
    testmethod static void getListAnkenMeisaiByShipment(){
        Test.startTest();
        List<AnkenMeisai__c> listMeisai = new List<AnkenMeisai__c>();
        listMeisai = [SELECT Id, Anken__c FROM AnkenMeisai__c ];
        List<clofor_com_cfs__AnkenMeisai__c> lstAnken = new List<clofor_com_cfs__AnkenMeisai__c>();
        lstAnken = FMS_SortByCurrentSOController.getListAnkenMeisaiByShipment(listMeisai.get(0).Anken__c);
        //List<AnkenWrapper> lstUpdate = FMS_SortByCurrentSOController.saveListAnken(lstAnkenData);
        System.assertEquals(2, lstAnken.size());
        Test.stopTest();
    }

    testmethod static void getPicklistValueFromObjectField(){
        Test.startTest();
        List<PicklistOption> lstOp = FMS_SortByCurrentSOController.getPicklistValueFromObjectField('clofor_com_cfs__AnkenMeisai__c',
                'clofor_com_cfs__ChargeUnit__c');
        System.assert(lstOp.size() > 0);
        Test.stopTest();
    }

    testmethod static void lookUp(){
        Test.startTest();
        List<sObject> lsAcc = FMS_SortByCurrentSOController.lookUp('', 'Account','', '', 'Name');
        System.assert(lsAcc.size() > 0);
        Test.stopTest();
    }

    testmethod static void saveListAnken(){
        Test.startTest();
        List<AnkenMeisai__c> listMeisai = new List<AnkenMeisai__c>();
        listMeisai = [SELECT Id, Anken__c FROM AnkenMeisai__c ];
        List<clofor_com_cfs__AnkenMeisai__c> lstAnken = new List<clofor_com_cfs__AnkenMeisai__c>();
        lstAnken = FMS_SortByCurrentSOController.getListAnkenMeisaiByShipment(listMeisai.get(0).Anken__c);
        FMS_SortByCurrentSOController.saveListAnken(lstAnken);
        System.assert(lstAnken.size() > 0);
        Test.stopTest();
    }

    testmethod static void deleteAnkenMeisai(){
        Test.startTest();
        List<AnkenMeisai__c> listMeisai = new List<AnkenMeisai__c>();
        listMeisai = [SELECT Id, Anken__c FROM AnkenMeisai__c ];
        List<clofor_com_cfs__AnkenMeisai__c> lstAnken = new List<clofor_com_cfs__AnkenMeisai__c>();
        lstAnken = FMS_SortByCurrentSOController.getListAnkenMeisaiByShipment(listMeisai.get(0).Anken__c);
        FMS_SortByCurrentSOController.deleteAnkenMeisai(lstAnken[0]);
        System.assert(lstAnken.size() > 0);
        Test.stopTest();
    }

}