force-app/main/default/objects/Account/fields/Carrier_Code__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If the account is Carrier/Airliner, choose its Carrier code in this field. - Carrier(Sea): 4 characters - Airline Carrier: 2 characters</inlineHelpText>
    <label>Carrier Code</label>
    <referenceTo>Carrier_Code__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amount_Wording_Setting__mdt/Amount_Wording_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Amount Wording Setting</label>
    <pluralLabel>Amount Wording Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo_Delivery__c/Cargo_Delivery__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CargoDeliveryOnlineHelp</customHelpPage>
    <description>Cargo Delivery</description>
    <label>配送</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Cargo Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Code__c/Carrier_Code__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CarrierCodeOnlineHelp</customHelpPage>
    <description>Carrier Code</description>
    <label>CARRIER/AIRLINER CODE</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Code__c/fields/Carrier_Code__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Code__c</fullName>
    <inlineHelpText>This code of Liner/Airliner includes both number and letter (2-4).</inlineHelpText>
    <label>Carrier Code</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectInvoicingAndCash__c/ConnectInvoicingAndCash__c.object-meta.xml
<CustomObject>
    <description>Joint function to connect Invoicing to Cash</description>
    <label>F/TMS請求・仕入+現金入出</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>FMS BILL+CASH ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectKickabckCash__c/ConnectKickabckCash__c.object-meta.xml
<CustomObject>
    <description>Joint function Object to link between Kickback and Cash</description>
    <label>リベート＋現金口座</label>
    <nameField>
        <displayFormat>KC-{000000}</displayFormat>
        <label>CONNECT KICKBACK &amp; CASH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/ConnectPurchasingInvoiceCash__c.object-meta.xml
<CustomObject>
    <label>購買発注明細＋現金入出</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>CONNECT PURCHASING INVOICE AND CASH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/PurchasingInvoice__c.field-meta.xml
<CustomField>
    <fullName>PurchasingInvoice__c</fullName>
    <label>PURCHASING INVOICE</label>
    <referenceTo>PurchasingInvoice__c</referenceTo>
    <relationshipName>CONNECT_PURCHASING_INVOICE_AND_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Clearance__c/Custom_Clearance__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CustomClearanceOnlineHelp</customHelpPage>
    <description>Custom Clearance</description>
    <label>通関</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Custom Clearance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HS_Code__c/HS_Code__c.object-meta.xml
<CustomObject>
    <customHelpPage>HSCodeOnlineHelp</customHelpPage>
    <label>HSコード</label>
    <nameField>
        <label>HS Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HS_Code__c/fields/HS_Code__c.field-meta.xml
<CustomField>
    <fullName>HS_Code__c</fullName>
    <label>HS Code</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/INVOICING_VAT__c/INVOICING_VAT__c.object-meta.xml
<CustomObject>
    <label>FMS BILL+VAT</label>
    <nameField>
        <displayFormat>IV-{0000000}</displayFormat>
        <label>FMS BILL+VAT</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INVOICING_VAT__c/fields/VAT_INVOICE__c.field-meta.xml
<CustomField>
    <fullName>VAT_INVOICE__c</fullName>
    <inlineHelpText>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT Invoice: Locked after Approved equals False.</inlineHelpText>
    <label>VAT INVOICE</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False. 
VAT Invoice is approved and locked. Contact System Administrator to unlock VAT Invoice.</errorMessage>
        <filterItems>
            <field>VAT_INVOICE__c.APPROVED_AND_LOCK__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Filter Type:Required.The user-entered value must match filter criteria. 
-VAT INVOICE: LOCKED AFTER APPROVED equals False.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VAT_INVOICE__c</referenceTo>
    <relationshipName>INVOICING_VAT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kickback__c/Kickback__c.object-meta.xml
<CustomObject>
    <label>リベート</label>
    <nameField>
        <displayFormat>KB-{000000}</displayFormat>
        <label>KICKBACK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LoadingLocation__c/LoadingLocation__c.object-meta.xml
<CustomObject>
    <description>Location where truck will load or unload cargo</description>
    <label>荷積み・荷下ろし</label>
    <nameField>
        <displayFormat>LL-{000000}</displayFormat>
        <label>LOADING LOCATION NUMBER</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnkenMeisai__c/MasterAnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLBUYINGOnlineHelp</customHelpPage>
    <description>M B/L - BUYING</description>
    <label>混載-請求・仕入</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>M B/L BUYING ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MgmtMaster__c/MgmtMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ExchangeRateOnlineHelp</customHelpPage>
    <description>為替や管理基準を管理するオブジェクト
Standard Exchange Rate</description>
    <label>為替</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>EXCHANGE RATE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherRevenueCost__c/OtherRevenueCost__c.object-meta.xml
<CustomObject>
    <label>Other</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>OTHER REVENUE &amp; COST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingInvoice__c/PurchasingInvoice__c.object-meta.xml
<CustomObject>
    <label>購買注文明細</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PURCHASING INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingInvoice__c/fields/PurchasingOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchasingOrder__c</fullName>
    <label>PURCHASING ORDER</label>
    <referenceTo>PurchasingOrder__c</referenceTo>
    <relationshipName>PURCHASING_INVOICE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchasingOrder__c/PurchasingOrder__c.object-meta.xml
<CustomObject>
    <label>購買注文</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>PURCHASING ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Ratio__c/Tax_Ratio__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_TaxratioOnlineHelp</customHelpPage>
    <description>Tax Ratio</description>
    <label>消費税</label>
    <nameField>
        <label>Tax Ratio</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time Entry</description>
    <label>打刻記録</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>TIME ENTRY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transit__c/Transit__c.object-meta.xml
<CustomObject>
    <label>積替</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>TRANSIT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TriggerHandlerFactory.cls
public with sharing class TriggerHandlerFactory {
    public static Map<String, Amount_Wording_Setting__mdt> wordingFieldMap = new Map<String, Amount_Wording_Setting__mdt>();
    
    public static void createHandler(Schema.sObjectType soType) {
        MetadataWordingSetting wordingSeting = MetadataWordingSetting.getInstance();
        if( wordingSeting.wordingFieldMapbyObject.containsKey(soType.getDescribe().getName())){
            wordingFieldMap = wordingSeting.wordingFieldMapbyObject.get(soType.getDescribe().getName());
        }else{
           wordingFieldMap = new Map<String, Amount_Wording_Setting__mdt>(); 
        }
       
        ITrigger handler = getHandler(soType);

        /*if (handler == null) {
            throw new TriggerException('No Trigger Handler registered for Object Type: ' + soType);
        }*/

        execute(handler);
    }

    private static void execute(ITrigger handler) { 
        
		if(handler == null) {
            if(Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate )){
                for (SObject so : Trigger.new) {
                    Util.wordingFields(so, wordingFieldMap);
                }
            }
            if(Trigger.isBefore && Trigger.isDelete){
                for (SObject so : Trigger.old) {
                    Util.wordingFields(so, wordingFieldMap);
                }
            }
			return;
		}
//        String handlerName = handler.getHandlerName();
//        if (!Test.isRunningTest()) {
//            if (TriggerExecutionHelper.isRunning(handlerName) || TriggerExecutionHelper.isForcedOff(handlerName)) {
//                return;
//            }
//        }

        if (Trigger.isBefore) {
            handler.bulkBefore();
           
            if (Trigger.isDelete) {
				handler.bulkBeforeDelete();
                for (SObject so : Trigger.old) {
                    if(handler != null){
                        handler.beforeDelete(so);
                    }
                }
            }  
			else if (Trigger.isInsert) {
				handler.bulkBeforeInsert();
                for (SObject so : Trigger.new) {
                    if(handler != null){
                        handler.beforeInsert(so);
                    }
                    Util.wordingFields(so, wordingFieldMap);
                }
            } 
			else if (Trigger.isUpdate) {
				handler.bulkBeforeUpdate();
                for (SObject so : Trigger.old) {
                    if(handler != null){
                        handler.beforeUpdate(so, Trigger.newMap.get(so.Id));
                    }
                    Util.wordingFields(Trigger.newMap.get(so.Id), wordingFieldMap);
                }
            }
        } 
		else {
            TriggerExecutionHelper.register(handler.getHandlerName());
            handler.bulkAfter();

            if (Trigger.isDelete) {
				handler.bulkAfterDelete();
                for (SObject so : Trigger.old) {
                    handler.afterDelete(so);
                }
            } 
			else if (Trigger.isInsert) {
				handler.bulkAfterInsert();
                for (SObject so : Trigger.new) {
                    handler.afterInsert(so);
                }
            } 
			else if (Trigger.isUpdate) {
				handler.bulkAfterUpdate();
                for (SObject so : Trigger.old) {
                    handler.afterUpdate(so, Trigger.newMap.get(so.Id));
                }
            }
        }
        handler.andFinally();
    }

    private static ITrigger getHandler(Schema.sObjectType soType) {
		
        if (soType == Account.sObjectType) {
            return new AccountTriggerHandler();
        } else if (soType == CustomObject1__c.sObjectType) {
            return new HBLShipmentsTriggerHandler();
        } else if (soType == AnkenMeisai__c.sObjectType) {
            return new HBLSellingBuyingTriggerHandler();
        } else if (soType == MasterAnkenMeisai__c.sObjectType) {
            return new MBLBuyingTriggerHandler();
        } /*else if (soType == MgmtMaster__c.sObjectType) {
            return new ExchangeRateTriggerHandler();
        } */else if (soType == Container_Info__c.sObjectType) {
            return new ContainerInfoTriggerHandler();
        } else if (soType == Contact.sObjectType) {
            return new ContactTriggerHandler();
        } else if (soType == Tax_Ratio__c.sObjectType) {
            return new TaxRatioTriggerHandler();
        } else if (soType == Cargo_Delivery__c.sObjectType) {
            return new CargoDeliveryTriggerHandler();
        } else if (soType == Carrier_Code__c.sObjectType) {
            return new CarrierCodeTriggerHandler();
        } else if (soType == Custom_Clearance__c.sObjectType) {
            return new CustomClearanceTriggerHandler();
        } else if (soType == HS_Code__c.sObjectType) {
            return new HSCodeTriggerHandler();
        } else if (soType == VAT_INVOICE__c.sObjectType) {
            return new VATInvoiceTriggerHandler();
        } else if (soType == INVOICING_VAT__c.sObjectType) {
            return new InvoicingVATTriggerHandler();
        } else if (soType == LoadingLocation__c.sObjectType) {
            return new LoadingLocationTriggerHandler();
        } else if (soType == PurchasingOrder__c.sObjectType) {
            return new PurchasingOrderTriggerHandler();
        } 
        //else if (soType == ConnectPurchasingInvoiceCash__c.sObjectType) {
        //    return new POCashTriggerHandler();
        //} 
        //else if (soType == ConnectInvoicingAndCash__c.sObjectType) {
        //    return new InvoicingCashTriggerHandler();
        //} 
        else if (soType == PurchasingInvoice__c.sObjectType) {
            return new PurchasingInvoiceTriggerHandler();
        } else if (soType == TimeEntry__c.sObjectType) {
            return new TimeEntryTriggerHandler();
        } else if (soType == Transit__c.sObjectType) {
            return new TransitTriggerHandler();
        } else if (soType == Kickback__c.sObjectType) {
            return new KickbackTriggerHandler();
        } 
        //else if (soType == ConnectKickabckCash__c.sObjectType) {
        //    return new KickbackCashTriggerHandler();
        //}
         else if (soType == CASH_BOOK__c.sObjectType) {
            return new CashBookTriggerHandler();
        }
        else if (soType == WorkOrder__c.sObjectType) {
            return new WorkOrderTriggerHandler();
        }
        else if (soType == OtherRevenueCost__c.sObjectType){
            return new OtherRevenueCostTriggerHelper();
        }
        else if (soType == clofor_com_cfs__ContainerGoodSO__c.sObjectType){
            return new ContainerGoodSOTriggerHandler();
        }
        else if (soType == clofor_com_cfs__SALES_ORDER__c.sObjectType){
            return new SalesOrderTriggerHelper();
        }

        return null;
    }

    public static void isBeforeDelContainerNumber(List<clofor_com_cfs__Container_Info__c> lstOld){
        String shipId = '';
        String ConId = '';
        for(clofor_com_cfs__Container_Info__c info : lstOld){
            shipId = info.clofor_com_cfs__HBL_SHIPMENT__c;
            ConId = info.Id;
        }
        system.debug('lstOld :' + lstOld);
        clofor_com_cfs__CustomObject1__c ship = [Select 
        Id,
        clofor_com_cfs__Container__c,clofor_com_cfs__ContainerNumber__c,
        clofor_com_cfs__Container2__c,clofor_com_cfs__ContainerNumber2__c,
        clofor_com_cfs__Container3__c,clofor_com_cfs__ContainerNumber3__c,
        clofor_com_cfs__Container4__c,clofor_com_cfs__ContainerNumber4__c,
        clofor_com_cfs__Container5__c,clofor_com_cfs__ContainerNumber5__c,
        clofor_com_cfs__Container6__c,clofor_com_cfs__ContainerNumber6__c,
        clofor_com_cfs__Container7__c,clofor_com_cfs__ContainerNumber7__c
        
        From clofor_com_cfs__CustomObject1__c 
        Where Id =: shipId];
        system.debug('ship1 :' +ship);
        List<clofor_com_cfs__Container_Info__c> lstinfo = [Select 
        Id,
        clofor_com_cfs__Container__c 
        From clofor_com_cfs__Container_Info__c 
        Where clofor_com_cfs__HBL_SHIPMENT__c =: shipId AND Id !=: ConId];
        system.debug('lstinfo :'+lstinfo);
        Integer count = 0;
        Integer count2 = 0;
        Integer count3 = 0;
        Integer count4 = 0;
        Integer count5 = 0;
        Integer count6 = 0;
        Integer count7 = 0;
        for(clofor_com_cfs__Container_Info__c inf : lstinfo){
            
            if(ship.clofor_com_cfs__Container__c == inf.clofor_com_cfs__Container__c){
                count ++;
            }else if(ship.clofor_com_cfs__Container2__c == inf.clofor_com_cfs__Container__c){
                count2 ++;
            }
            else if(ship.clofor_com_cfs__Container3__c == inf.clofor_com_cfs__Container__c){
                count3 ++;
            }
            else if(ship.clofor_com_cfs__Container4__c == inf.clofor_com_cfs__Container__c){
                count4 ++;
            }
            else if(ship.clofor_com_cfs__Container5__c == inf.clofor_com_cfs__Container__c){
                count5 ++;
            }
            else if(ship.clofor_com_cfs__Container6__c == inf.clofor_com_cfs__Container__c){
                count6 ++;
            }
            else if(ship.clofor_com_cfs__Container7__c == inf.clofor_com_cfs__Container__c){
                count7 ++;
            }
        }
        system.debug('count :' +count +count2 +count3 +count4 +count5 +count6 +count7);
        if(count != 0){
            ship.clofor_com_cfs__ContainerNumber__c = count;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber__c = null;
            ship.clofor_com_cfs__Container__c = null;
        }
        if(count2 != 0){
            ship.clofor_com_cfs__ContainerNumber2__c = count2;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber2__c = null;
            ship.clofor_com_cfs__Container2__c = null;
        }
        if(count3 != 0){
            ship.clofor_com_cfs__ContainerNumber3__c = count3;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber3__c = null;
            ship.clofor_com_cfs__Container3__c = null;
        }
        if(count4 != 0){
            ship.clofor_com_cfs__ContainerNumber4__c = count4;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber4__c = null;
            ship.clofor_com_cfs__Container4__c = null;
        }
        if(count5 != 0){
            ship.clofor_com_cfs__ContainerNumber5__c = count5;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber5__c = null;
            ship.clofor_com_cfs__Container5__c = null;
        }
        if(count6 != 0){
            ship.clofor_com_cfs__ContainerNumber6__c = count6;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber6__c = null;
            ship.clofor_com_cfs__Container6__c = null;
        }
        if(count7 != 0){
            ship.clofor_com_cfs__ContainerNumber7__c = count7;
        }else
        {
            ship.clofor_com_cfs__ContainerNumber7__c = null;
            ship.clofor_com_cfs__Container7__c = null;
        }
        system.debug('ship :'+ship);
        try {
            update ship;
        } catch (DmlException e){
            System.debug('ship mes: '+e.getMessage());
        }


    }

}