force-app/main/default/objects/Account/fields/CorporateMyNumber__c.field-meta.xml
<CustomField>
    <fullName>CorporateMyNumber__c</fullName>
    <label>Corporate My Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PersonInCharge__c.field-meta.xml
<CustomField>
    <fullName>PersonInCharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>営業担当</description>
    <label>DOC OPERATOR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesMan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/QuoationDescription__c.field-meta.xml
<CustomField>
    <fullName>QuoationDescription__c</fullName>
    <inlineHelpText>If there were any remarks on the quotation, put in this field. *Maximum input line is 3 lines.</inlineHelpText>
    <label>QUOTATION DETAIL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/SeikyusyoRemark__c.field-meta.xml
<CustomField>
    <fullName>SeikyusyoRemark__c</fullName>
    <inlineHelpText>Show in templates with button &apos;Print Dr Note to Customer v1 &amp; v2&apos;</inlineHelpText>
    <label>INVOICE REMARKS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/fields/EngProductSearch__c.field-meta.xml
<CustomField>
    <fullName>EngProductSearch__c</fullName>
    <label>CATEGORY(ENG)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductSearch__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>FCL Import</fullName>
            </value>
            <value>
                <fullName>FCL Export</fullName>
            </value>
            <value>
                <fullName>FCL Triangular trade</fullName>
            </value>
            <value>
                <fullName>LCL Import</fullName>
            </value>
            <value>
                <fullName>LCL Export</fullName>
            </value>
            <value>
                <fullName>LCL Triangular trade</fullName>
            </value>
            <value>
                <fullName>Import Custom Clearance</fullName>
            </value>
            <value>
                <fullName>Export Custom Clearance</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>Deliver</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Actual Expense</fullName>
            </value>
            <value>
                <fullName>Oversea Local Charge</fullName>
            </value>
            <value>
                <fullName>Consolidation Cost Allocation</fullName>
            </value>
            <value>
                <fullName>Empty Container</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/ProductSearch__c.field-meta.xml
<CustomField>
    <fullName>ProductSearch__c</fullName>
    <inlineHelpText>This is a key data when you are search the service master from H B/L Selling/Buying and M B/L(Consol)-Buying.</inlineHelpText>
    <label>CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCL輸入</fullName>
                <label>FCL Import</label>
            </value>
            <value>
                <fullName>FCL輸出</fullName>
                <label>FCL Export</label>
            </value>
            <value>
                <fullName>FCL三国間</fullName>
                <label>FCL Triangular Trade</label>
            </value>
            <value>
                <fullName>LCL輸入</fullName>
                <label>LCL Import</label>
            </value>
            <value>
                <fullName>LCL輸出</fullName>
                <label>LCL Export</label>
            </value>
            <value>
                <fullName>LCL三国間</fullName>
                <label>LCL Triangular Trade</label>
            </value>
            <value>
                <fullName>海外現地費用</fullName>
                <label>Oversea Local Charge</label>
            </value>
            <value>
                <fullName>通関輸入</fullName>
                <label>Import Custom Clearance</label>
            </value>
            <value>
                <fullName>通関輸出</fullName>
                <label>Export Custom Clearance</label>
            </value>
            <value>
                <fullName>エア</fullName>
                <label>AIR</label>
            </value>
            <value>
                <fullName>マスター按分</fullName>
                <label>Consolidation Cost Allocation</label>
            </value>
            <value>
                <fullName>ドレー</fullName>
                <label>Full Container Truck(Drayage)</label>
            </value>
            <value>
                <fullName>配送</fullName>
                <label>Delivery</label>
            </value>
            <value>
                <fullName>倉庫</fullName>
                <label>Warehouse</label>
            </value>
            <value>
                <fullName>実費</fullName>
                <label>Actual Expense</label>
            </value>
            <value>
                <fullName>Empty Container</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>SUB-CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductSearch__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Basic Charge</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Excluded</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Included</fullName>
            </value>
            <value>
                <fullName>CY CHARGE</fullName>
            </value>
            <value>
                <fullName>B/L FEE</fullName>
            </value>
            <value>
                <fullName>THC</fullName>
            </value>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>FAF</fullName>
            </value>
            <value>
                <fullName>BAF</fullName>
            </value>
            <value>
                <fullName>YAS</fullName>
            </value>
            <value>
                <fullName>EBS</fullName>
            </value>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>GBF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS</fullName>
            </value>
            <value>
                <fullName>FAF/BAF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS/EBS</fullName>
            </value>
            <value>
                <fullName>CO-LOAD</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>D/O FEE</fullName>
            </value>
            <value>
                <fullName>DOC FEE</fullName>
            </value>
            <value>
                <fullName>System Charges</fullName>
            </value>
            <value>
                <fullName>Detention Charge</fullName>
            </value>
            <value>
                <fullName>W/H IN &amp; OUT CHARGE</fullName>
            </value>
            <value>
                <fullName>SEAL</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges(Advance Payment)</fullName>
            </value>
            <value>
                <fullName>Consolidation Allocation</fullName>
            </value>
            <value>
                <fullName>Trucking(20&apos;)</fullName>
            </value>
            <value>
                <fullName>Trucking(40&apos;)</fullName>
            </value>
            <value>
                <fullName>Container Drayage(Tri-x chassis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/recordTypes/FCL.recordType-meta.xml
<RecordType>
    <fullName>FCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with FCL Forwarding.</description>
    <label>FCL</label>
</RecordType>

force-app/main/default/objects/TariffMaster__c/recordTypes/LCL.recordType-meta.xml
<RecordType>
    <fullName>LCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with LCL Forwarding.</description>
    <label>LCL</label>
</RecordType>

force-app/main/default/classes/InvoicePrintNewControllerTest.cls
@isTest
private class InvoicePrintNewControllerTest {
    private static Account acc{get;set;}
    private static Account acc2{get;set;}
    private static CustomObject1__c ank{get;set;}
    static{
        Custom_Application_Config__c config =  new Custom_Application_Config__c(Disabled_Trigger__c = true);
        FlsService.doInsert(config);
        acc = new Account();
        acc.Name  = 'SBS';
        acc.EnglishCompanyName__c = 'SBS';
        acc.BillingStreet = 'a';
        acc.BillingCity = 'a';
        acc.BillingState = 'a';
        acc.BillingPostalCode = 'a';
        acc.BillingCountry = 'a';
        acc.CorporateMyNumber__c = 'SBS-1';
        FlsService.doInsert(acc);
        acc2 = new Account();
        acc2.Name  = 'SBS 2';
        acc2.EnglishCompanyName__c = 'SBS 2';
        acc2.CorporateMyNumber__c = 'SBS-2';
        FlsService.doInsert(acc2);
        clofor_com_cfs__Site_Custom_Settings__c cus = new clofor_com_cfs__Site_Custom_Settings__c();
        cus.clofor_com_cfs__Company_Country__c = 'JAPAN';
        cus.clofor_com_cfs__Local_Currency__c = 'JPY';
        cus.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
         insert cus;
        User user1 = [ SELECT id from user limit 1 ];
        
        ank = new CustomObject1__c();
        ank.Field1__c = acc.id;
        ank.PersonInCharge__c      = user1.id;
        //ank.InChargeOfQuotation__c = user1.id;
        ank.QuoationDescription__c = 'test';
        ank.SeikyusyoRemark__c = 'test';
        ank.ETD__c = Date.today();
        ank.ETA__c = Date.today();
        FlsService.doInsert(ank);
        
        TariffMaster__c pro = new TariffMaster__c();
        pro.Name = 'LCL';
        pro.ProductSearch__c    = 'FCL輸入';      //大分類
        pro.Subcategory__c      = '基本料金';     //小分類
        pro.EngProductSearch__c = 'FCL Import';   //ENG大分類
        pro.EngSubcategory__c   = 'Basic charge'; //ENG子分類
        pro.ProductFlag__c      = true;
        pro.Supplier__c = acc.Id;
        FlsService.doInsert(pro);
        
        AnkenMeisai__c mei = new AnkenMeisai__c();        
        mei.Anken__c        = Ank.id;
        mei.curr__c         = 'USD';
        mei.SerchSyubetu__c = 'FCL輸入';
        mei.Tariff__c       = pro.id;
        //mei.PaymentTo__c    = acc2.id;
        mei.Seikyusaki__c   = acc.id;
        FlsService.doInsert(mei);
    }
    public static testMethod void  test_method_1() {
        Test.startTest();
        ApexPages.currentPage().getParameters().put('shipmentId', ank.Id);
        ApexPages.currentPage().getParameters().put('customerId', acc.Id);
        ApexPages.currentPage().getParameters().put('isTax', 'true');
        InvoicePrintNewController ctrl = new InvoicePrintNewController();
        Integer x = 1;
        system.assert(x==1);
        Test.stopTest();
    }

}