force-app/main/default/objects/Account/fields/CorporateMyNumber__c.field-meta.xml
<CustomField>
    <fullName>CorporateMyNumber__c</fullName>
    <label>Corporate My Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>WMS Bill</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>WMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WMS Bill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/BillingDisplayNo__c.field-meta.xml
<CustomField>
    <fullName>BillingDisplayNo__c</fullName>
    <label>BILLING DISPLAY NO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BILLING</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipName>BILLING</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Standard Billing</label>
</RecordType>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BillingTriggerHelperTest.cls
@isTest
private class BillingTriggerHelperTest {
	private static Facility__c warehouse;
	private static WorkOrder__c workOrder1;
	private static WorkOrder__c workOrder2;
	private static Account  accountTest1;
	
	private static Account  accountTest2;
	static{
		warehouse = createWarehouse();
		accountTest1 = new Account(Name = 'AccountTest1',
			EnglishCompanyName__c = 'AcountTest1',
            CorporateMyNumber__c = 'AcountTest1');
		FlsService.doInsert(accountTest1);

		accountTest2 = new Account(Name = 'AccountTest2',
			EnglishCompanyName__c = 'AcountTest2',
        CorporateMyNumber__c = 'AcountTest2');
		FlsService.doInsert(accountTest2);

		workOrder1 = new WorkOrder__c(
			WarehouseID__c = warehouse.Id,
			Customer__c = accountTest1.Id);
		FlsService.doInsert(workOrder1);

		workOrder2 = new WorkOrder__c(
			WarehouseID__c = warehouse.Id,
			Customer__c = accountTest2.Id);
		FlsService.doInsert(workOrder2);
	}

	@isTest static void test_method_onBeforeInsert() {
		Test.startTest();
		Billing__c billing = new Billing__c(
			WorkOrderID__c = workOrder1.Id);
		FlsService.doInsert(billing);

		// Implement test code
		Integer x = 1;
        System.assert(x != null);
		Test.stopTest();
	}
	
	@isTest static void test_method_onBeforeUpdate() {
		
		Billing__c billing = new Billing__c(
			WorkOrderID__c = workOrder1.Id);
		FlsService.doInsert(billing);

		Test.startTest();
			billing.BillingDisplayNo__c =1;
			FlsService.doUpdate(billing);
			Integer x = 1;
        System.assert(x != null);
		Test.stopTest();
	}

	private static Facility__c createWarehouse(){

		Facility__c warehouse = new clofor_com_cfs__Facility__c(
			clofor_com_cfs__FacilityName__c ='test Ware house'
			);
		FlsService.doInsert(warehouse);

		return warehouse;
	}
	
}