force-app/main/default/objects/Account/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <inlineHelpText>Choose the currency in which Customer/Partner prefer to receive invoice and calculate  Tax Ratio</inlineHelpText>
    <label>PRIMARY CURRENCY(INVOICE/TAX RATIO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Custom_Type__c.field-meta.xml
<CustomField>
    <fullName>Custom_Type__c</fullName>
    <description>Used as an alternative for standard field Type</description>
    <inlineHelpText>For Customer, choose from Domestic Customer-, and partner from Oversea Partner-、vendor from 3RD Vendor-. For your own company, choose Internal Use Only .</inlineHelpText>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>国内顧客 - 見込み</fullName>
                <label>LOCAL CUSTOMER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>国内顧客 - 既存</fullName>
                <default>true</default>
                <label>LOCAL CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>国内顧客 - フォワーダー</fullName>
                <label>LOCAL CUSTOMER - FORWARDER</label>
            </value>
            <value>
                <fullName>国内顧客 - 営業不要</fullName>
                <label>LOCAL CUSTOMER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>海外顧客 - 見込み</fullName>
                <label>OVERSEA CUSTOMER - LEAD(APPORACHING)</label>
            </value>
            <value>
                <fullName>海外顧客 - 既存</fullName>
                <label>OVERSEA CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>Oversea Customer - No Need Sales</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - LEAD(APPROACHING)</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - EXISTING</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - NO NEED SALES</fullName>
            </value>
            <value>
                <fullName>海外パートナー - 見込み</fullName>
                <label>OVERSEA PARTNER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>海外パートナー - 既存</fullName>
                <label>OVERSEA PARTNER - EXISTING</label>
            </value>
            <value>
                <fullName>海外パートナー - 営業不要</fullName>
                <label>OVERSEA PARTNER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>業者 - Co-Loader</fullName>
                <label>3RD VENDOR - CONSOLIDATOR</label>
            </value>
            <value>
                <fullName>Co-Loader</fullName>
            </value>
            <value>
                <fullName>業者 - 通関（当社手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - BB/通関（当社手配先）</fullName>
                <label>3RD VENDOR - BB/CUSTOMERS CLEARANCE/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - 通関（お客様手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/CUSTOMER AGENT</label>
            </value>
            <value>
                <fullName>業者 - 運送</fullName>
                <label>3RD VENDOR - TRUCKING</label>
            </value>
            <value>
                <fullName>Rail Agent</fullName>
            </value>
            <value>
                <fullName>Courier/Express</fullName>
            </value>
            <value>
                <fullName>業者 - 船社</fullName>
                <label>3RD VENDOR - CARRIER</label>
            </value>
            <value>
                <fullName>3RDVENDOR - AIRLINER</fullName>
                <label>3RD VENDOR - AIRLINER</label>
            </value>
            <value>
                <fullName>業者 - 倉庫・保管</fullName>
                <label>3RD VENDOR - WAREHOUSE/STORAGE</label>
            </value>
            <value>
                <fullName>Shipping Broker</fullName>
            </value>
            <value>
                <fullName>Packing Vendor</fullName>
            </value>
            <value>
                <fullName>Inspection Vendor</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>業者 - ポート</fullName>
                <label>3RD VENDOR - PORT</label>
            </value>
            <value>
                <fullName>業者 - DEPOT</fullName>
                <label>3RD VENDOR - DEPOT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>CURRENCY</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/ExchangeRate__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRate__c</fullName>
    <label>EXCHANGE RATE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashOutUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashOutUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-OUT(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/ExchangeRate__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRate__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Selling Ex-rate for customer. If Default Invoice Issued Date(Default ‘Today’) is in the period of active EX-Rate Mgmt record, ex-rate is automatically synchronized. Default Invoice Issued Date can be updated from Fixed Invoice Issue Date(If Fixed).</inlineHelpText>
    <label>EXCHANGE RATE FOR SELLING</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PrintDate__c.field-meta.xml
<CustomField>
    <fullName>PrintDate__c</fullName>
    <formula>if(LEN( text(PrinteDate_ED__c) ) &gt; 0 , PrinteDate_ED__c , TODAY() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>if Fixed Issue Date(If Fixed) is not set, automatically will be set as today.</inlineHelpText>
    <label>DATE INVOICE ISSUED</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Kickback__c/Kickback__c.object-meta.xml
<CustomObject>
    <label>リベート</label>
    <nameField>
        <displayFormat>KB-{000000}</displayFormat>
        <label>KICKBACK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kickback__c/fields/ExchangeRate__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRate__c</fullName>
    <inlineHelpText>Ex-rate for Kickback. If Default Invoice Issued Date(Default ‘Today’) in Shipment Order in the period of active EX-RATE Mgmt record, ex-rate is automatically synchronized.</inlineHelpText>
    <label>EXCHANGE RATE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/KickbackTo__c.field-meta.xml
<CustomField>
    <fullName>KickbackTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the company name which ask kickback</inlineHelpText>
    <label>KICKBACK TO</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KICKBACK</relationshipLabel>
    <relationshipName>KICKBACK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/PaidAmount__c.field-meta.xml
<CustomField>
    <fullName>PaidAmount__c</fullName>
    <label>AMOUNT PAID-KICKBACK(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/PaidAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>PaidAmountUSD__c</fullName>
    <label>AMOUNT PAID-KICKBACK(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/PaymentConfirmed__c.field-meta.xml
<CustomField>
    <fullName>PaymentConfirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PAYMENT CONFIRMED-KICKBACK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/PaymentSettledDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentSettledDate__c</fullName>
    <label>PAYMENT SETTLED DATE-KICKBACK</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/ShipmentOrder__c.field-meta.xml
<CustomField>
    <fullName>ShipmentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CloFMS SHIPMENT ORDER ID</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipLabel>KICKBACK</relationshipLabel>
    <relationshipName>KICKBACK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/TotalKickbackAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalKickbackAmount__c</fullName>
    <formula>ChargeUnit__c  *  UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL AMOUNT OF KICKBACK(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/TotalKickbackAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalKickbackAmountUSD__c</fullName>
    <formula>ChargeUnit__c  *  UnitPriceUSD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL AMOUNT OF KICKBACK(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UNIT PRICE OF KICKBACK(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/UnitPriceUSD__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceUSD__c</fullName>
    <label>UNIT PRICE OF KICKBACK(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/UnpaidBalance__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalance__c</fullName>
    <formula>TotalKickbackAmount__c  -  PaidAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF KICKBACK(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Kickback__c/fields/UnpaidBalanceUSD__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalanceUSD__c</fullName>
    <formula>TotalKickbackAmountUSD__c  -  PaidAmountUSD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF KICKBACK(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
        <default>true</default>
        <label>VND</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>PHP</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <masterLabel>CURRENCY</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/KickbackTriggerHandler.cls
/**
 * Created by khanhpham on 12/14/17.
 */

public with sharing class KickbackTriggerHandler extends AbstractTriggerHandler {
    private static List<MgmtMaster__c> exchangeRates = new List<MgmtMaster__c>();
    private Map<Id, Account> accountMap = new Map<Id, Account>();
    private Map<Id, CustomObject1__c> shipmentOrderMap = new Map<Id, CustomObject1__c>();
    private Map<Id, CASH_BOOK__c> toBeUpdatedCashBookMap = new Map<Id, CASH_BOOK__c>();
    private Map<Id, List<CASH_BOOK__c>> cashBooksByKickbackMap = new Map<Id, List<CASH_BOOK__c>>();

    static {
        exchangeRates = ExchangeRateSynchronizationService.loadMasterExchangeRates();
    }

    public override String getHandlerName() {
        return 'KickbackTriggerHandler';
    }

    public override void bulkBefore() {
        if (Trigger.isInsert) {
            loadReferences(Trigger.new);
        } else if (Trigger.isUpdate) {
            loadCashConnector(Trigger.new);
        } else if (Trigger.isDelete) {
            loadCashConnector(Trigger.old);
        }
    }

    public override void beforeInsert(SObject so) {
        Kickback__c kickback = (Kickback__c) so;
        syncExchangeRate(kickback);
        updateLocalUnitPrice(kickback);
    }

    public override void beforeUpdate(SObject oldSo, SObject so) {
        Kickback__c oldKickback = (Kickback__c) oldSo;
        Kickback__c kickback = (Kickback__c) so;
        confirmPaymentSettlement(kickback);
        updateLocalUnitPrice(kickback);
        //updateConnectedCashAmount(oldKickback, kickback);
    }
    public override void afterUpdate(SObject oldSo, SObject so) {
        Kickback__c oldKickback = (Kickback__c) oldSo;
        Kickback__c kickback = (Kickback__c) so;
        updateConnectedCashAmount(oldKickback, kickback);
    }

    public override void beforeDelete(SObject so) {
        Kickback__c kickback = (Kickback__c) so;
        List<CASH_BOOK__c> cashBookList = cashBooksByKickbackMap.get(kickback.Id);

        if (cashBookList != null && !cashBookList.isEmpty()) {
            for (CASH_BOOK__c cashBook : cashBookList) {
                if (!Util.isCashOut(cashBook)) continue;

                /*if (cashBook.TotalAmount__c != null && kickback.TotalKickbackAmount__c != null) {
                    cashBook.TotalAmount__c -= kickback.TotalKickbackAmount__c;*/
                if(cashBook.TotalAmount__c == null){
                        cashBook.TotalAmount__c = 0;
                }
                cashBook.TotalAmount__c -= kickback.UnpaidBalance__c;

                if(cashBook.TotalAmountOfCashOutUSD__c == null){
                        cashBook.TotalAmountOfCashOutUSD__c = 0;
                }
                cashBook.TotalAmountOfCashOutUSD__c -= kickback.UnpaidBalanceUSD__c;

                if (!toBeUpdatedCashBookMap.containsKey(cashBook.Id)) {
                    toBeUpdatedCashBookMap.put(cashBook.Id, cashBook);
                }
                /*}*/
            }
        }
    }

    private void updateConnectedCashAmount(Kickback__c oldKickback, Kickback__c kickback) {
        List<CASH_BOOK__c> cashBookList = cashBooksByKickbackMap.get(kickback.Id);

        if (cashBookList != null && !cashBookList.isEmpty()) {
            for (CASH_BOOK__c cashBook : cashBookList) {
                if (!Util.isCashOut(cashBook)) continue;

                Boolean hasChanged = false;

                if(oldKickback.UnpaidBalance__c != kickback.UnpaidBalance__c){
                    if(cashBook.TotalAmount__c == null){
                        cashBook.TotalAmount__c = 0;
                    }
                    cashBook.TotalAmount__c -= oldKickback.UnpaidBalance__c;
                    cashBook.TotalAmount__c += kickback.UnpaidBalance__c;
                    hasChanged =true;
                }
                if(oldKickback.UnpaidBalanceUSD__c != kickback.UnpaidBalanceUSD__c){
                    if(cashBook.TotalAmountOfCashOutUSD__c == null){
                        cashBook.TotalAmountOfCashOutUSD__c = 0;
                    }
                    cashBook.TotalAmountOfCashOutUSD__c -= oldKickback.UnpaidBalanceUSD__c;
                    cashBook.TotalAmountOfCashOutUSD__c += kickback.UnpaidBalanceUSD__c;
                    hasChanged =true;
                }

                /*if (cashBook.TotalAmount__c != null && oldKickback.TotalKickbackAmount__c != null) {
                    cashBook.TotalAmount__c -= oldKickback.TotalKickbackAmount__c;
                    hasChanged = true;
                }

                if (cashBook.TotalAmount__c != null && kickback.TotalKickbackAmount__c != null) {
                    cashBook.TotalAmount__c += kickback.TotalKickbackAmount__c;
                    hasChanged = true;
                } else if (kickback.TotalKickbackAmount__c != null) {
                    cashBook.TotalAmount__c = kickback.TotalKickbackAmount__c;
                    hasChanged = true;
                }*/

                if (hasChanged && !toBeUpdatedCashBookMap.containsKey(cashBook.Id)) {
                    toBeUpdatedCashBookMap.put(cashBook.Id, cashBook);
                }
            }
        }
    }

    private void updateLocalUnitPrice(Kickback__c kickback) {
        if ((kickback.UnitPrice__c == 0 || kickback.UnitPrice__c == null) && kickback.UnitPriceUSD__c != null && kickback.ExchangeRate__c != null) {
            kickback.UnitPrice__c = kickback.UnitPriceUSD__c * kickback.ExchangeRate__c;
        }
    }

    private void syncExchangeRate(Kickback__c kickback) {
        CustomObject1__c shipmentOrder = shipmentOrderMap.get(kickback.ShipmentOrder__c);

        if (shipmentOrder != null) {
            Date lookupDate = shipmentOrder.PrintDate__c;

            ExchangeRateSynchronizationService.applyExchangeRateToKickback(exchangeRates, kickback,
                    lookupDate, accountMap.get(kickback.KickbackTo__c));
        }
    }

    private void confirmPaymentSettlement(Kickback__c kickback) {
        if (kickback.PaymentConfirmed__c == true) {
            kickback.PaymentSettledDate__c = System.today();
            kickback.PaidAmount__c = kickback.TotalKickbackAmount__c;
            kickback.PaidAmountUSD__c = kickback.TotalKickbackAmountUSD__c;
        }
    }

    private void loadReferences(List<Kickback__c> kickbacks) {
        Set<Id> accountIds = new Set<Id>();
        Set<Id> shipmentOrderIds = new Set<Id>();

        for (Kickback__c kickback : kickbacks) {
            accountIds.add(kickback.KickbackTo__c);
            shipmentOrderIds.add(kickback.ShipmentOrder__c);
        }

        accountMap = new Map<Id, Account>([
                SELECT Id, Custom_Type__c, Currency__c, Business_Relationship__c,
                        Primary_Exchange_Rate_Currency__c, Secondary_Exchange_Rate_Currency__c
                FROM Account
                WHERE Id IN :accountIds
        ]);

        shipmentOrderMap = new Map<Id, CustomObject1__c>([SELECT Id, PrintDate__c FROM CustomObject1__c WHERE Id IN :shipmentOrderIds]);
    }
    
    private void loadCashConnector(List<Kickback__c> kickbacks) {
        Set<Id> kickbackIds = new Set<Id>();

        if (kickbacks != null && !kickbacks.isEmpty()) {
            for (Kickback__c kickback : kickbacks) {
                kickbackIds.add(kickback.Id);
            }
        }

        List<ConnectKickabckCash__c> kickbackCashList = [
                SELECT KickbackID__c, Cashbook__c
                FROM ConnectKickabckCash__c
                WHERE KickbackID__c IN :kickbackIds
        ];

        Map<Id, List<Id>> cashBookToKickbackList = new Map<Id, List<Id>>();
        for (ConnectKickabckCash__c pic : kickbackCashList) {
            if (cashBookToKickbackList.containsKey(pic.Cashbook__c)) {
                cashBookToKickbackList.get(pic.Cashbook__c).add(pic.KickbackID__c);
            } else {
                List<Id> kickbackIdList = new List<Id>();
                kickbackIdList.add(pic.KickbackID__c);
                cashBookToKickbackList.put(pic.Cashbook__c, kickbackIdList);
            }
        }

        // load cash book
        if (!cashBookToKickbackList.keySet().isEmpty()) {
            List<CASH_BOOK__c> cashBookList = [SELECT Id,  
                                                    TotalAmountCashIn__c, 
                                                    TotalAmount__c,
                                                    TotalAmountOfCashOutUSD__c,
                                                    TotalAmountOfCashInUSD__c, 
                                                    RecordTypeId FROM CASH_BOOK__c WHERE Id IN :cashBookToKickbackList.keySet()];

            for (CASH_BOOK__c cashBook : cashBookList) {
                List<Id> kickbackIdList = cashBookToKickbackList.get(cashBook.Id);

                if (!kickbackIdList.isEmpty()) {
                    for (Id piId : kickbackIdList) {
                        if (cashBooksByKickbackMap.containsKey(piId)) {
                            cashBooksByKickbackMap.get(piId).add(cashBook);
                        } else {
                            List<CASH_BOOK__c> kickbackCashBookList = new List<CASH_BOOK__c>();
                            kickbackCashBookList.add(cashBook);
                            cashBooksByKickbackMap.put(piId, kickbackCashBookList);
                        }
                    }
                }
            }
        }
    }
}