force-app/main/default/objects/Account/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <inlineHelpText>Choose the currency in which Customer/Partner prefer to receive invoice and calculate  Tax Ratio</inlineHelpText>
    <label>PRIMARY CURRENCY(INVOICE/TAX RATIO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Container_Vessel_SLA__c.field-meta.xml
<CustomField>
    <fullName>Container_Vessel_SLA__c</fullName>
    <defaultValue>240</defaultValue>
    <description>ETA Monday Ferry is the ferry arrives on Monday</description>
    <inlineHelpText>ETA Monday Ferry is the ferry arrives on Monday</inlineHelpText>
    <label>Container Vessel and ETA Monday Ferry SL</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ferry_SLA__c.field-meta.xml
<CustomField>
    <fullName>Ferry_SLA__c</fullName>
    <defaultValue>120</defaultValue>
    <description>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</description>
    <inlineHelpText>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</inlineHelpText>
    <label>Air and ETA Non-Monday Ferry SLA(Minutes</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ocean_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Ocean_HBL_No_Prefix__c</fullName>
    <description>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</description>
    <inlineHelpText>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</inlineHelpText>
    <label>Ocean HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/fields/EngProductSearch__c.field-meta.xml
<CustomField>
    <fullName>EngProductSearch__c</fullName>
    <label>CATEGORY(ENG)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductSearch__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>FCL Import</fullName>
            </value>
            <value>
                <fullName>FCL Export</fullName>
            </value>
            <value>
                <fullName>FCL Triangular trade</fullName>
            </value>
            <value>
                <fullName>LCL Import</fullName>
            </value>
            <value>
                <fullName>LCL Export</fullName>
            </value>
            <value>
                <fullName>LCL Triangular trade</fullName>
            </value>
            <value>
                <fullName>Import Custom Clearance</fullName>
            </value>
            <value>
                <fullName>Export Custom Clearance</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>Deliver</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Actual Expense</fullName>
            </value>
            <value>
                <fullName>Oversea Local Charge</fullName>
            </value>
            <value>
                <fullName>Consolidation Cost Allocation</fullName>
            </value>
            <value>
                <fullName>Empty Container</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/ProductSearch__c.field-meta.xml
<CustomField>
    <fullName>ProductSearch__c</fullName>
    <inlineHelpText>This is a key data when you are search the service master from H B/L Selling/Buying and M B/L(Consol)-Buying.</inlineHelpText>
    <label>CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCL輸入</fullName>
                <label>FCL Import</label>
            </value>
            <value>
                <fullName>FCL輸出</fullName>
                <label>FCL Export</label>
            </value>
            <value>
                <fullName>FCL三国間</fullName>
                <label>FCL Triangular Trade</label>
            </value>
            <value>
                <fullName>LCL輸入</fullName>
                <label>LCL Import</label>
            </value>
            <value>
                <fullName>LCL輸出</fullName>
                <label>LCL Export</label>
            </value>
            <value>
                <fullName>LCL三国間</fullName>
                <label>LCL Triangular Trade</label>
            </value>
            <value>
                <fullName>海外現地費用</fullName>
                <label>Oversea Local Charge</label>
            </value>
            <value>
                <fullName>通関輸入</fullName>
                <label>Import Custom Clearance</label>
            </value>
            <value>
                <fullName>通関輸出</fullName>
                <label>Export Custom Clearance</label>
            </value>
            <value>
                <fullName>エア</fullName>
                <label>AIR</label>
            </value>
            <value>
                <fullName>マスター按分</fullName>
                <label>Consolidation Cost Allocation</label>
            </value>
            <value>
                <fullName>ドレー</fullName>
                <label>Full Container Truck(Drayage)</label>
            </value>
            <value>
                <fullName>配送</fullName>
                <label>Delivery</label>
            </value>
            <value>
                <fullName>倉庫</fullName>
                <label>Warehouse</label>
            </value>
            <value>
                <fullName>実費</fullName>
                <label>Actual Expense</label>
            </value>
            <value>
                <fullName>Empty Container</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>SUB-CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductSearch__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Basic Charge</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Excluded</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Included</fullName>
            </value>
            <value>
                <fullName>CY CHARGE</fullName>
            </value>
            <value>
                <fullName>B/L FEE</fullName>
            </value>
            <value>
                <fullName>THC</fullName>
            </value>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>FAF</fullName>
            </value>
            <value>
                <fullName>BAF</fullName>
            </value>
            <value>
                <fullName>YAS</fullName>
            </value>
            <value>
                <fullName>EBS</fullName>
            </value>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>GBF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS</fullName>
            </value>
            <value>
                <fullName>FAF/BAF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS/EBS</fullName>
            </value>
            <value>
                <fullName>CO-LOAD</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>D/O FEE</fullName>
            </value>
            <value>
                <fullName>DOC FEE</fullName>
            </value>
            <value>
                <fullName>System Charges</fullName>
            </value>
            <value>
                <fullName>Detention Charge</fullName>
            </value>
            <value>
                <fullName>W/H IN &amp; OUT CHARGE</fullName>
            </value>
            <value>
                <fullName>SEAL</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges(Advance Payment)</fullName>
            </value>
            <value>
                <fullName>Consolidation Allocation</fullName>
            </value>
            <value>
                <fullName>Trucking(20&apos;)</fullName>
            </value>
            <value>
                <fullName>Trucking(40&apos;)</fullName>
            </value>
            <value>
                <fullName>Container Drayage(Tri-x chassis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/recordTypes/FCL.recordType-meta.xml
<RecordType>
    <fullName>FCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with FCL Forwarding.</description>
    <label>FCL</label>
</RecordType>

force-app/main/default/objects/TariffMaster__c/recordTypes/LCL.recordType-meta.xml
<RecordType>
    <fullName>LCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with LCL Forwarding.</description>
    <label>LCL</label>
</RecordType>

force-app/main/default/classes/MassInvoiceUpdateControllerTest.cls
@isTest
private class MassInvoiceUpdateControllerTest {
    @testsetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
            'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Local_Currency__c' => 'VND',
            'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Company_Country__c' => 'Japan',
            'Ocean_HBL_No_Prefix__c' => 'AFR', 'Ferry_SLA__c' => 120, 'Container_Vessel_SLA__c' => 480,
            'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
		TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);
        
        // Create an Account
        additionalFields = new Map<String, Object> {'Currency__c' => 'USD - U.S. Dollar'};                                                                        
            Account account = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);
        
        // Create Service Master
        additionalFields = new Map<String, Object> {'Name' => 'LCL', 'ProductSearch__c' => 'FCL輸入', 'Subcategory__c' => '基本料金',
            'EngProductSearch__c' => 'FCL Import', 'ProductFlag__c' => true,
            'Supplier__c' => account.Id, 'Zeibunrui__c' => PicklistReference.DUAL_PRODUCT_TAX};
                TariffMaster__c tariff = (TariffMaster__c) TestDataFactory.createSObject(new TariffMaster__c(), true, additionalFields); 
        
        // Create 2 HBL records
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType1'];
        
        additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => rt.Id, 'HBL__c' => 'TEST0001'};
            CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
        
        // Create 2 HBL S/B records
        additionalFields = new Map<String, Object> {'Anken__c' => shipment.Id, 'curr__c' => 'VND', 'VAT_INVOICE_ISSUE_STATUS__c' => false,
            'Tariff__c' => tariff.Id,
            'Seikyusaki__c' => account.Id, 'SerchSyubetu__c' => 'FCL輸入',
            'Cost_Allocation_Catetory__c' => 'Partner Cost allocation'};              
                TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);
        
        additionalFields = new Map<String, Object> {'Anken__c' => shipment.Id, 'curr__c' => 'VND', 'VAT_INVOICE_ISSUE_STATUS__c' => false,
            'Tariff__c' => tariff.Id,
            'Seikyusaki__c' => account.Id, 'SerchSyubetu__c' => 'FCL輸入',
            'Cost_Allocation_Catetory__c' => 'Partner Cost allocation'};              
                TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);
    }
    
    testmethod static void shouldUpdateInvoicingRecords() {
        CustomObject1__c shipment = [SELECT Id FROM CustomObject1__c WHERE HBL__c = 'TEST0001'];
        PageReference pageReference = Page.MassInvoicingUpdate;
        Test.setCurrentPage(pageReference);
        ApexPages.currentPage().getParameters().put('id', shipment.Id);
        //ApexPages.currentPage().getParameters().put('option', 'rp');
        MassInvoicingUpdateController controller = new MassInvoicingUpdateController();
        
        Test.startTest();
        controller.updateInvoicing();
        controller.isCreation = true;
        controller.numberOfRecords ='5';
        controller.createNewRecords();
        controller.updateInvoicing();
        controller.selectedActioningOption = 'test';
        List<SelectOption>  a = controller.transactionOptions;
        controller.selectedTransactionOption = 'test';
        Test.stopTest();
        System.assert(true);
    }
}