force-app/main/default/objects/Account/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <inlineHelpText>Choose the currency in which Customer/Partner prefer to receive invoice and calculate  Tax Ratio</inlineHelpText>
    <label>PRIMARY CURRENCY(INVOICE/TAX RATIO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container_Info__c/Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Info__c/fields/Container_NO__c.field-meta.xml
<CustomField>
    <fullName>Container_NO__c</fullName>
    <inlineHelpText>Please enter 11digits(4digit container ownership code+7digit container code)</inlineHelpText>
    <label>CONTAINER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Container_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/Seal_No__c.field-meta.xml
<CustomField>
    <fullName>Seal_No__c</fullName>
    <label>SEAL NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <inlineHelpText>Choose &apos;Yes&apos; and Customs Clearance Object will be created. Put detail of the customs clearance in to the object accordingly.</inlineHelpText>
    <label>CUSTOMS CLEARANCE SERVICE REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>×(NO)</fullName>
            </value>
            <value>
                <fullName>○(YES)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DeliveryService_required__c.field-meta.xml
<CustomField>
    <fullName>DeliveryService_required__c</fullName>
    <inlineHelpText>Choose the number of Pickup or Delivery Required and TRANSPORT object will be created according to the number. To create object, Transportation Type must be chosen. Input the detail of pickup/delivery information to the object.</inlineHelpText>
    <label>PICKUP OR DELIVERY REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL__c.field-meta.xml
<CustomField>
    <fullName>HBL__c</fullName>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType1.recordType-meta.xml
<RecordType>
    <fullName>RecordType1</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Import Shipment.</description>
    <label>Ocean Import</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Container_Vessel_SLA__c.field-meta.xml
<CustomField>
    <fullName>Container_Vessel_SLA__c</fullName>
    <defaultValue>240</defaultValue>
    <description>ETA Monday Ferry is the ferry arrives on Monday</description>
    <inlineHelpText>ETA Monday Ferry is the ferry arrives on Monday</inlineHelpText>
    <label>Container Vessel and ETA Monday Ferry SL</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ferry_SLA__c.field-meta.xml
<CustomField>
    <fullName>Ferry_SLA__c</fullName>
    <defaultValue>120</defaultValue>
    <description>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</description>
    <inlineHelpText>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</inlineHelpText>
    <label>Air and ETA Non-Monday Ferry SLA(Minutes</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ocean_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Ocean_HBL_No_Prefix__c</fullName>
    <description>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</description>
    <inlineHelpText>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</inlineHelpText>
    <label>Ocean HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContainerListingControllerTest.cls
/**
 * Created by khanhpham on 10/25/17.
 */
@IsTest(SeeAllData=false)
private with sharing class ContainerListingControllerTest {
    @testsetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object>{
                'Company_Address__c' => '123 ABC, Tokyo, Japan',
                'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Local_Currency__c' => 'VND',
                'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Company_Country__c' => 'Japan',
                'Ocean_HBL_No_Prefix__c' => 'AFR', 'Ferry_SLA__c' => 120, 'Container_Vessel_SLA__c' => 480,
                'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'
        };
        TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);

        // Create an Account
        additionalFields = new Map<String, Object>{
                'Currency__c' => 'USD - U.S. Dollar'
        };
        Account account = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);

        // Create SHIPMENT ORDER
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType1'];

        additionalFields = new Map<String, Object>{
                'Field1__c' => account.Id, 'RecordTypeId' => rt.Id, 'HBL__c' => 'TEST0001',
                'Custom__c' => PicklistReference.CUSTOMER_CLEARANCE_SERVICE_REQUIRED_YES,
                'DeliveryService_required__c' => '2'
        };
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);

        // Create Container Info
        additionalFields = new Map<String, Object>{
                'HBL_SHIPMENT__c' => shipment.Id, 'Container_NO__c' => 'BMOU6260034', 'Seal_No__c' => 'KG281561',
                'Container__c' => '20\'DC'
        };
        TestDataFactory.createSObject(new Container_Info__c(), true, additionalFields);
    }

    @IsTest static void shouldGenerateContainerLists() {
        CustomObject1__c shipment = [SELECT Id FROM CustomObject1__c WHERE HBL__c = 'TEST0001'];
        PageReference pageReference = Page.ContainersList;
        Test.setCurrentPage(pageReference);
        ApexPages.currentPage().getParameters().put(Constants.REQUEST_ID, String.valueOf(shipment.Id));
        ApexPages.currentPage().getParameters().put(Constants.REQUEST_CHECK_FLAG, 'true');

        ContainerListingController controller = new ContainerListingController();

        Test.startTest();
        controller.buildContainerLists();
        Test.stopTest();
        System.assertEquals(1, controller.pages.size());
    }
}