force-app/main/default/objects/Account/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <inlineHelpText>Choose the currency in which Customer/Partner prefer to receive invoice and calculate  Tax Ratio</inlineHelpText>
    <label>PRIMARY CURRENCY(INVOICE/TAX RATIO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL__c.field-meta.xml
<CustomField>
    <fullName>HBL__c</fullName>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType1.recordType-meta.xml
<RecordType>
    <fullName>RecordType1</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Import Shipment.</description>
    <label>Ocean Import</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Container_Vessel_SLA__c.field-meta.xml
<CustomField>
    <fullName>Container_Vessel_SLA__c</fullName>
    <defaultValue>240</defaultValue>
    <description>ETA Monday Ferry is the ferry arrives on Monday</description>
    <inlineHelpText>ETA Monday Ferry is the ferry arrives on Monday</inlineHelpText>
    <label>Container Vessel and ETA Monday Ferry SL</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ferry_SLA__c.field-meta.xml
<CustomField>
    <fullName>Ferry_SLA__c</fullName>
    <defaultValue>120</defaultValue>
    <description>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</description>
    <inlineHelpText>ETA Non-Monday Ferry is the ferry arrives on Wednesday, Friday.</inlineHelpText>
    <label>Air and ETA Non-Monday Ferry SLA(Minutes</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Ocean_HBL_No_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Ocean_HBL_No_Prefix__c</fullName>
    <description>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</description>
    <inlineHelpText>This is the prefix to be appended to the auto-generated HBL Number for Ocean Export shipment</inlineHelpText>
    <label>Ocean HBL No Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/fields/ProductSearch__c.field-meta.xml
<CustomField>
    <fullName>ProductSearch__c</fullName>
    <inlineHelpText>This is a key data when you are search the service master from H B/L Selling/Buying and M B/L(Consol)-Buying.</inlineHelpText>
    <label>CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCL輸入</fullName>
                <label>FCL Import</label>
            </value>
            <value>
                <fullName>FCL輸出</fullName>
                <label>FCL Export</label>
            </value>
            <value>
                <fullName>FCL三国間</fullName>
                <label>FCL Triangular Trade</label>
            </value>
            <value>
                <fullName>LCL輸入</fullName>
                <label>LCL Import</label>
            </value>
            <value>
                <fullName>LCL輸出</fullName>
                <label>LCL Export</label>
            </value>
            <value>
                <fullName>LCL三国間</fullName>
                <label>LCL Triangular Trade</label>
            </value>
            <value>
                <fullName>海外現地費用</fullName>
                <label>Oversea Local Charge</label>
            </value>
            <value>
                <fullName>通関輸入</fullName>
                <label>Import Custom Clearance</label>
            </value>
            <value>
                <fullName>通関輸出</fullName>
                <label>Export Custom Clearance</label>
            </value>
            <value>
                <fullName>エア</fullName>
                <label>AIR</label>
            </value>
            <value>
                <fullName>マスター按分</fullName>
                <label>Consolidation Cost Allocation</label>
            </value>
            <value>
                <fullName>ドレー</fullName>
                <label>Full Container Truck(Drayage)</label>
            </value>
            <value>
                <fullName>配送</fullName>
                <label>Delivery</label>
            </value>
            <value>
                <fullName>倉庫</fullName>
                <label>Warehouse</label>
            </value>
            <value>
                <fullName>実費</fullName>
                <label>Actual Expense</label>
            </value>
            <value>
                <fullName>Empty Container</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>SUB-CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductSearch__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Basic Charge</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Excluded</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Included</fullName>
            </value>
            <value>
                <fullName>CY CHARGE</fullName>
            </value>
            <value>
                <fullName>B/L FEE</fullName>
            </value>
            <value>
                <fullName>THC</fullName>
            </value>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>FAF</fullName>
            </value>
            <value>
                <fullName>BAF</fullName>
            </value>
            <value>
                <fullName>YAS</fullName>
            </value>
            <value>
                <fullName>EBS</fullName>
            </value>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>GBF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS</fullName>
            </value>
            <value>
                <fullName>FAF/BAF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS/EBS</fullName>
            </value>
            <value>
                <fullName>CO-LOAD</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>D/O FEE</fullName>
            </value>
            <value>
                <fullName>DOC FEE</fullName>
            </value>
            <value>
                <fullName>System Charges</fullName>
            </value>
            <value>
                <fullName>Detention Charge</fullName>
            </value>
            <value>
                <fullName>W/H IN &amp; OUT CHARGE</fullName>
            </value>
            <value>
                <fullName>SEAL</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges(Advance Payment)</fullName>
            </value>
            <value>
                <fullName>Consolidation Allocation</fullName>
            </value>
            <value>
                <fullName>Trucking(20&apos;)</fullName>
            </value>
            <value>
                <fullName>Trucking(40&apos;)</fullName>
            </value>
            <value>
                <fullName>Container Drayage(Tri-x chassis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/recordTypes/FCL.recordType-meta.xml
<RecordType>
    <fullName>FCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with FCL Forwarding.</description>
    <label>FCL</label>
</RecordType>

force-app/main/default/objects/TariffMaster__c/recordTypes/LCL.recordType-meta.xml
<RecordType>
    <fullName>LCL</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with LCL Forwarding.</description>
    <label>LCL</label>
</RecordType>

force-app/main/default/classes/PaymentReportControllerTest.cls
@isTest
private class PaymentReportControllerTest {
	private static CustomObject1__c forwarding;
	private static Account customer;
	static{
		
		Map<String, Object> additionalFields = new Map<String, Object>{'Company_Address__c' => '123 ABC, Tokyo, Japan',
                'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233', 'Local_Currency__c' => 'VND',
                'Logo_URL__c' => 'http://afr-solutions.com/logo.png', 'Company_Country__c' => 'Japan',
                'Ocean_HBL_No_Prefix__c' => 'AFR', 'Ferry_SLA__c' => 120, 'Container_Vessel_SLA__c' => 480,
            	'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'};
        TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);
        
        // Create an Account
        additionalFields = new Map<String, Object> {'Currency__c' => 'USD - U.S. Dollar'};                                                                        
        customer = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);
        
        // Create 2 HBL records
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType1'];
        additionalFields = new Map<String, Object> {'Field1__c' => customer.Id, 'RecordTypeId' => rt.Id, 'HBL__c' => 'TEST0001'};
        forwarding = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
        
        additionalFields = new Map<String, Object> {'Name' => 'LCL', 'ProductSearch__c' => 'FCL輸入', 'Subcategory__c' => '基本料金',
            									'EngProductSearch__c' => 'FCL Import', 'ProductFlag__c' => true,
									            'Supplier__c' => customer.Id, 'Zeibunrui__c' => PicklistReference.DUAL_PRODUCT_TAX};
		TariffMaster__c tariff = (TariffMaster__c) TestDataFactory.createSObject(new TariffMaster__c(), true, additionalFields);      
        
        RecordType rtAnken = [Select Id from RecordType where DeveloperName !=: Constants.SELLING_BUYING_CONSOLIDATION_RT and SObjectType = 'clofor_com_cfs__AnkenMeisai__c' AND IsActive = true Limit 1];
        additionalFields = new Map<String, Object> {'Anken__c' => forwarding.Id, 'curr__c' => 'VND', 'VAT_INVOICE_ISSUE_STATUS__c' => false,
            									'Tariff__c' => tariff.Id, 
            									'Seikyusaki__c' => customer.Id, 'SerchSyubetu__c' => 'FCL輸入',
            									'Cost_Allocation_Catetory__c' => 'Partner Cost allocation',
												'Suryo__c' => 5,
            									'SellTankaUSD__c' => 5,
            									'PrintFlag__c' => true,
            									'RecordTypeId' => rtAnken .Id };              
		TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);
        
        TestDataFactory.createSObject(new VAT_INVOICE__c(), true, null);
	}
	@isTest static void test_method_one() {
		Test.startTest();
		ApexPages.currentPage().getParameters().put(Constants.REQUEST_ID, forwarding.Id);
        ApexPages.currentPage().getParameters().put(Constants.REQUEST_REPORT_NAME, 'debitnote');
        ApexPages.currentPage().getParameters().put(Constants.REQUEST_LANGUAGE,'en' );
        ApexPages.currentPage().getParameters().put(Constants.REQUEST_CUSTOMER_ID, customer.Id);
		// Implement test code
		PaymentReportController ctrl = new PaymentReportController();
		system.assert(forwarding.Id != null);
		Test.stopTest();
	}
	
	
	
}