force-app/main/default/objects/Account/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <inlineHelpText>Choose the currency in which Customer/Partner prefer to receive invoice and calculate  Tax Ratio</inlineHelpText>
    <label>PRIMARY CURRENCY(INVOICE/TAX RATIO)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnkenMeisai__c/fields/AM_BuyInAfter_allocation__c.field-meta.xml
<CustomField>
    <fullName>AM_BuyInAfter_allocation__c</fullName>
    <formula>IF( OR(AM_MCBM__c = 0, ISBLANK(AM_MCBM__c)) , 0, (AM_BuyInBefore_Allocation__c * ANKEN_CBM__c) / AM_MCBM__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BUYING AFTER ALLOCATION-CHECKING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/AM_BuyInAfter_allocation_USD__c.field-meta.xml
<CustomField>
    <fullName>AM_BuyInAfter_allocation_USD__c</fullName>
    <formula>IF( OR(AM_MCBM__c = 0, ISBLANK(AM_MCBM__c)) , 0, (AM_Buyinbefore_allocation_USD__c * ANKEN_CBM__c) / AM_MCBM__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BUYING AFTER ALLOCATION-CHECKING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/AM_MasterMeisaiID__c.field-meta.xml
<CustomField>
    <fullName>AM_MasterMeisaiID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Input the M B/L Buying ID corresponds with cost allocation category</inlineHelpText>
    <label>CONSOL SHIPMENT BUYING ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AM_MasterID__c</field>
            <operation>equals</operation>
            <valueField>MasterAnkenMeisai__c.MasterAnken__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MasterAnkenMeisai__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>AM_MasterMeisaiID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountUSD__c</fullName>
    <formula>ROUND(Suryo__c * BuyTankaUSD__c,3) +TotalAmountofBuyingFCYAdjust__c
/*
clofor_com_cfs__Suryo__c * if( ISNULL(clofor_com_cfs__BuyTankaUSD__c), 0, clofor_com_cfs__BuyTankaUSD__c ) + clofor_com_cfs__Cost_Allocation_Margin_USD__c
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of Selling(FCY)=Unit Price of Selling(Local)*Charge Unit (Total).</inlineHelpText>
    <label>TOTAL AMOUNT OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyInTaxAmountJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyInTaxAmountJPY__c</fullName>
    <description>IF (Tariff__r.wkTaxFlag__c, 
BuyAmountJPN__c * (1 + BuyTaxInitial__c), 
BuyAmountJPN__c 
)</description>
    <formula>BuyAmountJPN__c + BuyTaxNum__c + AmountBuyingLocalAdjustment__c
/* till Jan 4 , 2019
clofor_com_cfs__BuyAmountJPN__c * (1 + clofor_com_cfs__BuyTaxInitial__c) + clofor_com_cfs__TAX_ADJUSTMENT__c



※注意※
仕入金額に関してはこの計算
（レート*数量*USD単価）を適用しない
下記計算を備忘録として残す。

IF( TEXT(curr__c) = &apos;JPY&apos;,
ROUND(BuyAmountJPN__c * (1 + BuyTaxInitial__c) , 0 ),
ROUND( BuyTankaUSD__c * Suryo__c * KawaseBay__c , 0)
)

*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The amount will be calculated as Total Amount of Buying(Local)+Total Amount of Buying(Local)*Tax Ratio</inlineHelpText>
    <label>AMOUNT BUYING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaJPY__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input. 1. It will refer the amount in Unit Price of Buying(Local) in Service Master Object. 2. If not, take the amount =Unit Price of Buying(USD)×Exchange Rate-Buying</inlineHelpText>
    <label>UNIT PRICE OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/BuyTankaUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaUSD__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input. 1. It will refer the amount in Unit Price of Buying(FCY) in Service Master Object. 2. If not, take the amount =Unit Price of Buying(Local)/Exchange Rate-Buying.</inlineHelpText>
    <label>UNIT PRICE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AnkenMeisai__c/fields/Cost_Allocation_Catetory__c.field-meta.xml
<CustomField>
    <fullName>Cost_Allocation_Catetory__c</fullName>
    <inlineHelpText>Input the allocation category which corresponds with the category of this buying</inlineHelpText>
    <label>Cost Allocation Catetory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Cost allocation</fullName>
            </value>
            <value>
                <fullName>Carrier Cost Allocation</fullName>
            </value>
            <value>
                <fullName>Warehouse Cost Allocation</fullName>
            </value>
            <value>
                <fullName>Carrier Cost Allocation(TAX)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterAnken__c/MasterAnken__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLOnlineHelp</customHelpPage>
    <description>M B/L - SHIPMENTS</description>
    <label>混載</label>
    <nameField>
        <label>MASTER SHIPMENT NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnken__c/fields/Master_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Master_Record_Type__c</fullName>
    <label>Master Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ocean Import</fullName>
            </value>
            <value>
                <fullName>Ocean Export</fullName>
                <default>true</default>
                <label>Ocean Export</label>
            </value>
            <value>
                <fullName>Air Import</fullName>
            </value>
            <value>
                <fullName>Air Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/META__c.field-meta.xml
<CustomField>
    <fullName>META__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/METD__c.field-meta.xml
<CustomField>
    <fullName>METD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/MasterAnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLBUYINGOnlineHelp</customHelpPage>
    <description>M B/L - BUYING</description>
    <label>混載-請求・仕入</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>M B/L BUYING ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountUSD__c</fullName>
    <formula>Suryo__c *  BuyTankaUSD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL AMOUNT OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyInTaxAmountJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyInTaxAmountJPY__c</fullName>
    <description>IF (MTariff__r.wkTaxFlag__c,
BuyAmountJPN__c * (1 + BuyTaxInitial__c),
BuyAmountJPN__c
)</description>
    <formula>BuyTaxNum__c + ROUND(BuyAmountJPN__c ,0)</formula>
    <label>AMOUNT BUYING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaJPY__c</fullName>
    <label>UNIT PRICE OF BUYING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/BuyTankaUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyTankaUSD__c</fullName>
    <label>UNIT PRICE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/Cost_Allocation_Catetory__c.field-meta.xml
<CustomField>
    <fullName>Cost_Allocation_Catetory__c</fullName>
    <inlineHelpText>Choose the category of the buying item of the MB/L(from partner, carrier, carrier(TAX), warehouse). In corresponding allocation HB/L buying, also input this category.</inlineHelpText>
    <label>COST ALLOCATION CATEGORY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Cost allocation</fullName>
            </value>
            <value>
                <fullName>Carrier Cost Allocation</fullName>
            </value>
            <value>
                <fullName>Warehouse Cost Allocation</fullName>
            </value>
            <value>
                <fullName>Carrier Cost Allocation(TAX)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/MasterAnken__c.field-meta.xml
<CustomField>
    <fullName>MasterAnken__c</fullName>
    <label>MASTER SHIPMENT NAME</label>
    <referenceTo>MasterAnken__c</referenceTo>
    <relationshipName>MasterAnken</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MasterAnkenMeisai__c/fields/MTariff__c.field-meta.xml
<CustomField>
    <fullName>MTariff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only show the available Service Master which mapped with Service Category for Search Engine</inlineHelpText>
    <label>SERVICE MASTER NAME</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>TariffMaster__c.Name</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>TariffMaster__c</referenceTo>
    <relationshipLabel>CONSOL-BUYING</relationshipLabel>
    <relationshipName>MTariff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/fields/BuyAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>BuyAmountUSD__c</fullName>
    <inlineHelpText>Input the number and it will be automatically inserted to Unit Price of Buying(USD) in HB/L S/B if the field is blank</inlineHelpText>
    <label>UNIT PRICE OF BUYING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Input company name providing the service</inlineHelpText>
    <label>SERVICE PROVIDER VENDOR</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MBLBuyingTriggerHandler.cls
public with sharing class MBLBuyingTriggerHandler extends AbstractTriggerHandler {
    private List<AnkenMeisai__c> meisais = null;
    private Set<AnkenMeisai__c> toBeUpdatedMeisais = new Set<AnkenMeisai__c>();
    private Map<Id, MasterAnken__c> mapMBLs = new Map<Id, MasterAnken__c>();
    private List<MgmtMaster__c> exchangeRates = new List<MgmtMaster__c>();
    private Map<Id, TariffMaster__c> mapServiceMasters = new Map<Id, TariffMaster__c>();
    private TaxRatioService taxRatioService;
    private static TranslationService translationService;
    
    static {
        translationService = new TranslationService('ERROR', UserInfo.getLanguage());
    }

    public override String getHandlerName() {
        return 'MBLBuyingTriggerHandler';
    }
 
    public override void bulkBefore() {
        exchangeRates = ExchangeRateSynchronizationService.loadMasterExchangeRates();
        loadReferenceData(Trigger.new);
        taxRatioService = new TaxRatioService();
    }
    
	public override void bulkAfter() {
        loadHBLSellingBuyingRecords(Trigger.new);
    }
    
    public override void beforeInsert(SObject so) {
        MasterAnkenMeisai__c mblBuying = (MasterAnkenMeisai__c) so;
        
        if (!validateCurrency(mblBuying)) {
            return;
        }
        
        MasterAnken__c mbl = mapMBLs.get(mblBuying.MasterAnken__c);
        
        syncTaxRation(mblBuying, mbl);
        syncExchangeRate(mblBuying, mbl);
        updateUnitPrice(mblBuying);
    }
    
    public override void afterInsert(SObject so) {
        MasterAnkenMeisai__c master = (MasterAnkenMeisai__c) so;
        linkHBLSellingBuying(master);
    }
    
    public override void beforeUpdate(SObject oldSo, SObject so) {
        MasterAnkenMeisai__c mblBuying = (MasterAnkenMeisai__c) so;
        
        if (!validateCurrency(mblBuying)) {
            return;
        }
        
        MasterAnken__c mbl = mapMBLs.get(mblBuying.MasterAnken__c);
        TariffMaster__c serviceMaster = mapServiceMasters.get(mblBuying.MTariff__c);
        if (serviceMaster != null && serviceMaster.Supplier__c != null && !StringUtils.isEmpty(serviceMaster.Supplier__r.Currency__c)) {
            taxRatioService.populateMBLTaxRatio(mblBuying, mbl, serviceMaster.Supplier__r.Currency__c);    
        }
        updateUnitPrice(mblBuying);
    }
    
    public override void afterUpdate(SObject oldSo, SObject so) {
        MasterAnkenMeisai__c oldMaster = (MasterAnkenMeisai__c) oldSo;
        MasterAnkenMeisai__c newMaster = (MasterAnkenMeisai__c) so;
            
        if ((newMaster.BuyInTaxAmountJPY__c != oldMaster.BuyInTaxAmountJPY__c) 
            	|| (newMaster.BuyAmountUSD__c != oldMaster.BuyAmountUSD__c)
           		|| (newMaster.Cost_Allocation_Catetory__c != oldMaster.Cost_Allocation_Catetory__c)) {
			linkHBLSellingBuying(newMaster);
		}
    }
    
    public override void andFinally() {
        if (!toBeUpdatedMeisais.isEmpty()) {
            FlsService.doUpdate(new List<AnkenMeisai__c>(toBeUpdatedMeisais));
        }
    }
    
    private void syncTaxRation(MasterAnkenMeisai__c mblBuying,  MasterAnken__c mbl) {
        TariffMaster__c serviceMaster = mapServiceMasters.get(mblBuying.MTariff__c);
        if (serviceMaster != null && serviceMaster.Supplier__c != null && !StringUtils.isEmpty(serviceMaster.Supplier__r.Currency__c)) {
            taxRatioService.populateMBLTaxRatio(mblBuying, mbl, serviceMaster.Supplier__r.Currency__c);    
        }
    }
    
    private void syncExchangeRate(MasterAnkenMeisai__c mblBuying,  MasterAnken__c mbl) {
        TariffMaster__c serviceMaster = mapServiceMasters.get(mblBuying.MTariff__c);
		Date lookupDate = null;
        
        if (ObjectClassificationUtils.isImportMBL(mbl.Master_Record_Type__c)) {
            lookupDate = mbl.META__c;
        } else if (ObjectClassificationUtils.isExportMBL(mbl.Master_Record_Type__c)) {
            lookupDate = mbl.METD__c;
        }
            
        if (lookupDate != null) {     
            if (serviceMaster != null && serviceMaster.Supplier__c != null) {
                ExchangeRateSynchronizationService.applyExchangeRateToMBLBuyings(mblBuying, lookupDate, serviceMaster.Supplier__r, exchangeRates);
            }
        }	
    }
    
    private void linkHBLSellingBuying(MasterAnkenMeisai__c master) {
        if (meisais != null && !meisais.isEmpty()) {
            for (AnkenMeisai__c meisai : meisais) {
                if (master.Id == meisai.AM_MasterMeisaiID__c 
                   || (!StringUtils.isEmpty(meisai.Cost_Allocation_Catetory__c) 
                       && meisai.Cost_Allocation_Catetory__c.equalsIgnoreCase(master.Cost_Allocation_Catetory__c))) {
                    meisai.AM_MasterMeisaiID__c = master.Id;
                    toBeUpdatedMeisais.add(meisai);
                }
            }
        }
    }
    
    private void loadHBLSellingBuyingRecords(List<MasterAnkenMeisai__c> masters) {
        Set<Id> masterMBLBuyingIds = new Set<Id>();
        Set<Id> masterMBLIds = new Set<Id>();
        
        for (MasterAnkenMeisai__c master : masters) {
            masterMBLBuyingIds.add(master.Id);
            masterMBLIds.add(master.MasterAnken__c);
        }
        
        meisais = [SELECT AM_MasterMeisaiID__c, BuyTankaJPY__c, BuyTankaUSD__c, AM_BuyInAfter_allocation__c, 
                   		  AM_BuyInAfter_allocation_USD__c, AM_MasterID__c, Cost_Allocation_Catetory__c 
				   FROM AnkenMeisai__c
                   WHERE AM_MasterMeisaiID__c IN :masterMBLBuyingIds OR AM_MasterID__c IN :masterMBLIds
				  ];
    }
    
    private void loadReferenceData(List<MasterAnkenMeisai__c> mblBuyings) {
        Set<Id> mblIds = new Set<Id>();
        Set<Id> serviceMasterIds = new Set<Id>();
        
        for (MasterAnkenMeisai__c mblBuying : mblBuyings) {
            mblIds.add(mblBuying.MasterAnken__c);
            serviceMasterIds.add(mblBuying.MTariff__c);
        }
        
        mapMBLs = new Map<Id, MasterAnken__c>([SELECT Id, METD__c, META__C, MPartner__c, Master_Record_Type__c 
                                               FROM MasterAnken__c 
                                               WHERE Id IN :mblIds]);
        
        mapServiceMasters = new Map<Id, TariffMaster__c>([SELECT Id, Supplier__r.Currency__c, Supplier__r.Secondary_Currency__c, 
                                                          	Supplier__r.Primary_Exchange_Rate_Currency__c, 
                                                          	Supplier__r.Secondary_Exchange_Rate_Currency__c,
                                                            Supplier__r.Business_Relationship__c, Supplier__r.Custom_Type__c
                                                          FROM TariffMaster__c 
                                                          WHERE Id IN :serviceMasterIds]);
    }
    
    private boolean validateCurrency(MasterAnkenMeisai__c meisai) {
        boolean result = true;
        Site_Custom_Settings__c setting = Site_Custom_Settings__c.getOrgDefaults();
        
        // if (!StringUtils.isEmpty(meisai.curr__c) && !meisai.curr__c.equalsIgnoreCase(setting.Local_Currency__c)
            	// && !meisai.curr__c.equalsIgnoreCase(PicklistReference.CURRENCY_USD)) {
            // result = false;
            // 
            // if (PicklistReference.CURRENCY_USD.equals(setting.Local_Currency__c)) {
                // meisai.addError(translationService.getTranslation(Constants.UNAVAILABLE_CURRENCY));    
            // } else {
                // meisai.addError(translationService.getTranslation(Constants.UNAVAILABLE_CURRENCY) + ', ' + setting.Local_Currency__c);
            // }
        // }
        return result;
    }
    
    private void updateUnitPrice(MasterAnkenMeisai__c meisai) {
        if (NumbericUtils.isNonZero(meisai.KawaseBay__c) && NumbericUtils.isNonZero(meisai.BuyTankaUSD__c)) {
            meisai.BuyTankaJPY__c = meisai.KawaseBay__c * meisai.BuyTankaUSD__c;
        }
    }
}