force-app/main/default/objects/Account/fields/Custom_Type__c.field-meta.xml
<CustomField>
    <fullName>Custom_Type__c</fullName>
    <description>Used as an alternative for standard field Type</description>
    <inlineHelpText>For Customer, choose from Domestic Customer-, and partner from Oversea Partner-、vendor from 3RD Vendor-. For your own company, choose Internal Use Only .</inlineHelpText>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>国内顧客 - 見込み</fullName>
                <label>LOCAL CUSTOMER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>国内顧客 - 既存</fullName>
                <default>true</default>
                <label>LOCAL CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>国内顧客 - フォワーダー</fullName>
                <label>LOCAL CUSTOMER - FORWARDER</label>
            </value>
            <value>
                <fullName>国内顧客 - 営業不要</fullName>
                <label>LOCAL CUSTOMER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>海外顧客 - 見込み</fullName>
                <label>OVERSEA CUSTOMER - LEAD(APPORACHING)</label>
            </value>
            <value>
                <fullName>海外顧客 - 既存</fullName>
                <label>OVERSEA CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>Oversea Customer - No Need Sales</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - LEAD(APPROACHING)</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - EXISTING</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - NO NEED SALES</fullName>
            </value>
            <value>
                <fullName>海外パートナー - 見込み</fullName>
                <label>OVERSEA PARTNER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>海外パートナー - 既存</fullName>
                <label>OVERSEA PARTNER - EXISTING</label>
            </value>
            <value>
                <fullName>海外パートナー - 営業不要</fullName>
                <label>OVERSEA PARTNER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>業者 - Co-Loader</fullName>
                <label>3RD VENDOR - CONSOLIDATOR</label>
            </value>
            <value>
                <fullName>Co-Loader</fullName>
            </value>
            <value>
                <fullName>業者 - 通関（当社手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - BB/通関（当社手配先）</fullName>
                <label>3RD VENDOR - BB/CUSTOMERS CLEARANCE/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - 通関（お客様手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/CUSTOMER AGENT</label>
            </value>
            <value>
                <fullName>業者 - 運送</fullName>
                <label>3RD VENDOR - TRUCKING</label>
            </value>
            <value>
                <fullName>Rail Agent</fullName>
            </value>
            <value>
                <fullName>Courier/Express</fullName>
            </value>
            <value>
                <fullName>業者 - 船社</fullName>
                <label>3RD VENDOR - CARRIER</label>
            </value>
            <value>
                <fullName>3RDVENDOR - AIRLINER</fullName>
                <label>3RD VENDOR - AIRLINER</label>
            </value>
            <value>
                <fullName>業者 - 倉庫・保管</fullName>
                <label>3RD VENDOR - WAREHOUSE/STORAGE</label>
            </value>
            <value>
                <fullName>Shipping Broker</fullName>
            </value>
            <value>
                <fullName>Packing Vendor</fullName>
            </value>
            <value>
                <fullName>Inspection Vendor</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>業者 - ポート</fullName>
                <label>3RD VENDOR - PORT</label>
            </value>
            <value>
                <fullName>業者 - DEPOT</fullName>
                <label>3RD VENDOR - DEPOT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Exchange_Rate_Currency__c.field-meta.xml
<CustomField>
    <fullName>Primary_Exchange_Rate_Currency__c</fullName>
    <inlineHelpText>Choose The Currency Which The Company Prefer to Convert from FCY</inlineHelpText>
    <label>PRIMARY EXCHANGE RATE CURRENCY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Exchange_Rate_Currency__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Exchange_Rate_Currency__c</fullName>
    <label>SECONDARY EXCHANGE RATE CURRENCY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>USD - U.S. Dollar</fullName>
                <default>true</default>
                <label>USD - U.S. Dollar</label>
            </value>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
            <value>
                <fullName>AUD - Australian Dollar</fullName>
            </value>
            <value>
                <fullName>HKD - Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>IDR - Indonesian Rupiah</fullName>
            </value>
            <value>
                <fullName>MMK - Myanmar Kyat</fullName>
            </value>
            <value>
                <fullName>MYR - Malaysian Ringgit</fullName>
            </value>
            <value>
                <fullName>NZD - New Zealand Dollar</fullName>
            </value>
            <value>
                <fullName>PPH - Philippine Peso</fullName>
            </value>
            <value>
                <fullName>THB - Thai Baht</fullName>
            </value>
            <value>
                <fullName>TWD - Taiwan Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <inlineHelpText>Choose &apos;Yes&apos; and Customs Clearance Object will be created. Put detail of the customs clearance in to the object accordingly.</inlineHelpText>
    <label>CUSTOMS CLEARANCE SERVICE REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>×(NO)</fullName>
            </value>
            <value>
                <fullName>○(YES)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL__c.field-meta.xml
<CustomField>
    <fullName>HBL__c</fullName>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PrinteDate_ED__c.field-meta.xml
<CustomField>
    <fullName>PrinteDate_ED__c</fullName>
    <inlineHelpText>Use this date when the invoice issue date need to be set for the certain date</inlineHelpText>
    <label>FIXED INVOICE ISSUE DATE(IF FIXED)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <defaultValue>&quot;Address&quot;</defaultValue>
    <description>use to contain company address information</description>
    <label>Company Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Fax__c.field-meta.xml
<CustomField>
    <fullName>Company_Fax__c</fullName>
    <defaultValue>&quot;Fax&quot;</defaultValue>
    <description>use to contain company fax number</description>
    <label>Company Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <defaultValue>&quot;Phone Number&quot;</defaultValue>
    <description>use to contain company phone number</description>
    <label>Company Phone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/EnableInvoiceTemplateSet1__c.field-meta.xml
<CustomField>
    <fullName>EnableInvoiceTemplateSet1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Invoice Template Set 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/InvoiceTemplateSet1Name__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplateSet1Name__c</fullName>
    <label>Invoice Template Set 1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/UtilTest.cls
@IsTest
public with sharing class UtilTest {
    @testSetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object>{
                'Company_Address__c' => '123 ABC, Tokyo, Japan',
                'Company_Fax__c' => '1234567', 'Company_Phone__c' => '11122233',
                'Logo_URL__c' => 'http://afr-solutions.com/logo.png',
                'Company_Country__c' => 'JAPAN', 'Local_Currency__c' => 'JPY',
                'EnableInvoiceTemplateSet1__c' => true, 'InvoiceTemplateSet1Name__c' => 'TEST'
        };
        TestDataFactory.createSObject(new Site_Custom_Settings__c(), true, additionalFields);
        // Setup an Account
        Date printDate = Date.newInstance(2015, 09, 09);
        additionalFields = new Map<String, Object>{
                'Custom_Type__c' => PicklistReference.DOMESTIC_CUSTOMER_EXISTING,
                'Primary_Exchange_Rate_Currency__c' => 'JPY - Japanese Yen',
                'Secondary_Exchange_Rate_Currency__c' => 'VND - Vietnamese Dong'
        };
        Account domesticCustomer = (Account) TestDataFactory.createSObject(new Account(), true, additionalFields);
        // Setup a SHIPMENT ORDER
        String shipmentRecordTypeOceIm = RecordTypeUtil.getRecordTypeIdByDeveloperName(CustomObject1__c.SObjectType, Constants.OCEAN_IMPORT_RT);
        additionalFields = new Map<String, Object>{
                'Field1__c' => domesticCustomer.Id, 'RecordTypeId' => shipmentRecordTypeOceIm,
                'Custom__c' => PicklistReference.CUSTOMER_CLEARANCE_SERVICE_REQUIRED_NO,
                'PrinteDate_ED__c' => printDate, 'HBL__c' => 'SO_TEST_123'
        };
        CustomObject1__c shipmentOrder = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);

        additionalFields = new Map<String, Object>{
            'Anken__c' => shipmentOrder.Id,'Suryo__c'=>3.000,'SellTankaJPY__c'=>0,'TaxInitial__c'=>0,'TAX_ADJUSTMENTSELL__c'=>0,'BuyTankaJPY__c'=>0
            ,'BuyTaxInitial__c'=>0,'Cost_Allocation_Margin__c'=>0
        }; 
        AnkenMeisai__c bill = (AnkenMeisai__c) TestDataFactory.createSObject(new AnkenMeisai__c(), true, additionalFields);

        additionalFields = new Map<String, Object>{
            'AccoutantFullName__c' => 'Test1234'
        };
        CASH_BOOK__c cash = (CASH_BOOK__c) TestDataFactory.createSObject(new CASH_BOOK__c(), true, additionalFields);
    }

    @IsTest
    static void TestUnit() {
    System.assertEquals(5,Util.ConvertWeightToBaseUnit('g',5));
    System.assertEquals(null,Util.ConvertWeightToBaseUnit('g',null));
    System.assertEquals(5,Util.ConvertWeightFromBaseUnit('g',5));
    System.assertEquals(null,Util.ConvertWeightFromBaseUnit('g',null));
    System.assertEquals(5000,Util.ConvertWeightToUnit('Kg','g',5));
    System.assertEquals(5,Util.ConvertWeightToUnit('g','g',5));
    }
    @IsTest
    static void TestgetObjectCustomFields() {
        List<String> lstfield = Util.getObjectCustomFields(CustomObject1__c.SObjectType);
        System.assertEquals('a06',Util.getObjectTypeId('clofor_com_cfs__CustomObject1__c'));
        // System.assertEquals(true,ObjectClassificationUtils.isOverseaCustomerOrPartner('海外'));
        }
    @IsTest
    static void TestURL(){
        String url = Util.getServerInstance();
        String domain = Util.getServerInstanceByDomainName('quan');
        String domain2 = Util.getSFDomainFromBaseURL('https://api.status.salesforce.com/v1/instanceAliases/quan');
        // System.assertEquals(true,ObjectClassificationUtils.isImportMBL('import'));
    }
    @IsTest
    static void TestCashBook(){
        CASH_BOOK__c cash = [SELECT id,RecordTypeId FROM CASH_BOOK__c LIMIT 1];
        System.assertEquals(true,Util.isCashOut(cash));
        System.assertEquals(false,Util.isCashIn(cash));
    }
    @IsTest
    static void TestBill(){
        AnkenMeisai__c bill = [SELECT id,RecordTypeId,Suryo__c,SellTankaJPY__c,TaxInitial__c,TAX_ADJUSTMENTSELL__c,BuyTankaJPY__c,BuyTaxInitial__c,Cost_Allocation_Margin__c FROM AnkenMeisai__c LIMIT 1];
        System.assertEquals(0,Util.calculateSellingAmount(bill));
        System.assertEquals(0,Util.calculateBuyingAmount(bill));
        System.assertEquals(0,Util.calculateBuyingInTaxAmount(bill));
        System.assertEquals(0,Util.calculateSellingInTaxAmount(bill));
    }
    @IsTest
    static void TestField(){
        AnkenMeisai__c bill = [SELECT id,RecordTypeId FROM AnkenMeisai__c LIMIT 1];
        Map<String, Amount_Wording_Setting__mdt> wordingFieldMap = new Map<String, Amount_Wording_Setting__mdt>(); 
        Util.listOutFieldsWordingForObject('clofor_com_cfs__CustomObject1__c');
        Util.wordingFields(bill,wordingFieldMap);
    }
}