force-app/main/default/objects/Account/fields/Custom_Type__c.field-meta.xml
<CustomField>
    <fullName>Custom_Type__c</fullName>
    <description>Used as an alternative for standard field Type</description>
    <inlineHelpText>For Customer, choose from Domestic Customer-, and partner from Oversea Partner-、vendor from 3RD Vendor-. For your own company, choose Internal Use Only .</inlineHelpText>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>国内顧客 - 見込み</fullName>
                <label>LOCAL CUSTOMER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>国内顧客 - 既存</fullName>
                <default>true</default>
                <label>LOCAL CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>国内顧客 - フォワーダー</fullName>
                <label>LOCAL CUSTOMER - FORWARDER</label>
            </value>
            <value>
                <fullName>国内顧客 - 営業不要</fullName>
                <label>LOCAL CUSTOMER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>海外顧客 - 見込み</fullName>
                <label>OVERSEA CUSTOMER - LEAD(APPORACHING)</label>
            </value>
            <value>
                <fullName>海外顧客 - 既存</fullName>
                <label>OVERSEA CUSTOMER - EXISTING</label>
            </value>
            <value>
                <fullName>Oversea Customer - No Need Sales</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - LEAD(APPROACHING)</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - EXISTING</fullName>
            </value>
            <value>
                <fullName>LOCAL PARTNER - NO NEED SALES</fullName>
            </value>
            <value>
                <fullName>海外パートナー - 見込み</fullName>
                <label>OVERSEA PARTNER - LEAD(APPROACHING)</label>
            </value>
            <value>
                <fullName>海外パートナー - 既存</fullName>
                <label>OVERSEA PARTNER - EXISTING</label>
            </value>
            <value>
                <fullName>海外パートナー - 営業不要</fullName>
                <label>OVERSEA PARTNER - NO NEED SALES</label>
            </value>
            <value>
                <fullName>業者 - Co-Loader</fullName>
                <label>3RD VENDOR - CONSOLIDATOR</label>
            </value>
            <value>
                <fullName>Co-Loader</fullName>
            </value>
            <value>
                <fullName>業者 - 通関（当社手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - BB/通関（当社手配先）</fullName>
                <label>3RD VENDOR - BB/CUSTOMERS CLEARANCE/OUR AGENT</label>
            </value>
            <value>
                <fullName>業者 - 通関（お客様手配先）</fullName>
                <label>3RD VENDOR - CUSTOMS CLEARANCE AGENT/CUSTOMER AGENT</label>
            </value>
            <value>
                <fullName>業者 - 運送</fullName>
                <label>3RD VENDOR - TRUCKING</label>
            </value>
            <value>
                <fullName>Rail Agent</fullName>
            </value>
            <value>
                <fullName>Courier/Express</fullName>
            </value>
            <value>
                <fullName>業者 - 船社</fullName>
                <label>3RD VENDOR - CARRIER</label>
            </value>
            <value>
                <fullName>3RDVENDOR - AIRLINER</fullName>
                <label>3RD VENDOR - AIRLINER</label>
            </value>
            <value>
                <fullName>業者 - 倉庫・保管</fullName>
                <label>3RD VENDOR - WAREHOUSE/STORAGE</label>
            </value>
            <value>
                <fullName>Shipping Broker</fullName>
            </value>
            <value>
                <fullName>Packing Vendor</fullName>
            </value>
            <value>
                <fullName>Inspection Vendor</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>業者 - ポート</fullName>
                <label>3RD VENDOR - PORT</label>
            </value>
            <value>
                <fullName>業者 - DEPOT</fullName>
                <label>3RD VENDOR - DEPOT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/MailS__c.field-meta.xml
<CustomField>
    <fullName>MailS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the contact person do not want to receive CloTra automail, check the box and CloTra automail delivery will be stopped.</inlineHelpText>
    <label>DO NOT WANT CARGO TRACKING EMAIL SERVICE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/CustmerInCharge__c.field-meta.xml
<CustomField>
    <fullName>CustmerInCharge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>PIC OF CUSTOMER</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Field1__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>F/TMS S/O (PIC OF CUSTOMER)</relationshipLabel>
    <relationshipName>CIC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Customer_Do_Not_Disturb_State__c.field-meta.xml
<CustomField>
    <fullName>Customer_Do_Not_Disturb_State__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Store Customer selection for &quot;DO NOT WANT TO EMAIL ANNOUNCE&quot; option (to whether want to receive email notification from HBL or not). 
This field is required because of limitation from SF for number of relationships in an object (15 relationships).</description>
    <label>Customer Do Not Disturb State</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Partner_Do_Not_Disturb_State__c.field-meta.xml
<CustomField>
    <fullName>Partner_Do_Not_Disturb_State__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Store Partner selection for &quot;DO NOT WANT TO EMAIL ANNOUNCE&quot; option (to whether want to receive email notification from HBL or not).
This field is required because of limitation from SF for number of relationships in an object (15 relationships).</description>
    <label>Partner Do Not Disturb State</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PartnerRep__c.field-meta.xml
<CustomField>
    <fullName>PartnerRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PIC OF PARTNER</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>F/TMS S/O (PIC OF PARTNER)</relationshipLabel>
    <relationshipName>Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
@isTest(SeeAllData=false)
public class ContactTriggerHandlerTest {
      testmethod static void shouldPopulateDoNotSendEmailFlagsOnCreation() {
		RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
        Map<String, Object> additionFields = new Map<String, Object> {'Custom_Type__c' => PicklistReference.DOMESTIC_CUSTOMER_EXISTING};
		Account account = (Account) TestDataFactory.createSObject(new Account(), true, additionFields);
        clofor_com_cfs__Site_Custom_Settings__c cus = new clofor_com_cfs__Site_Custom_Settings__c();
        cus.clofor_com_cfs__Company_Country__c = 'JAPAN';
        cus.clofor_com_cfs__Local_Currency__c = 'JPY';
        cus.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
         insert cus;
        additionFields = new Map<String, Object> {'Phone' => '12345678', 'MailS__c' => true, 'AccountId' => account.Id};
        Contact customer = (Contact) TestDataFactory.createSObject(new Contact(), true, additionFields);
        
        additionFields = new Map<String, Object> {'Phone' => '12345678', 'MailS__c' => false, 'AccountId' => account.Id};
        Contact partner = (Contact) TestDataFactory.createSObject(new Contact(), true, additionFields);

        Map<String, Object> additionalFields = new Map<String, Object> {'clofor_com_cfs__Country_Name__c' => 'BELIZE'};     
        clofor_com_cfs__Port__c	objPort =  (clofor_com_cfs__Port__c) TestDataFactory.createSObject(new clofor_com_cfs__Port__c(), true, additionalFields);
     
        additionFields = new Map<String, Object> {'Field1__c' => account.Id, 'Partner__c' => account.Id,
            										'CustmerInCharge__c' => customer.Id, 
                                                    'PartnerRep__c' => partner.Id, 'RecordTypeId' => rt.Id,
                                                    'clofor_com_cfs__POD__c' => objPort.Id
                                                };
		CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), 
                                                                                     false, additionFields);        
        
        Test.startTest();
		FlsService.doInsert(shipment);
        Test.stopTest();
        
        shipment = [SELECT Partner_Do_Not_Disturb_State__c, Customer_Do_Not_Disturb_State__c 
                    FROM CustomObject1__c 
                    WHERE Id = :shipment.Id];
        System.assertEquals(false, shipment.Partner_Do_Not_Disturb_State__c);
        System.assertEquals(true, shipment.Customer_Do_Not_Disturb_State__c);
    }
    
    testmethod static void shouldPopulateDoNotSendEmailFlagsOnUpdate() {
		RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
        Map<String, Object> additionFields = new Map<String, Object> {'Custom_Type__c' => PicklistReference.DOMESTIC_CUSTOMER_EXISTING};
		Account account = (Account) TestDataFactory.createSObject(new Account(), true, additionFields);
        clofor_com_cfs__Site_Custom_Settings__c cus = new clofor_com_cfs__Site_Custom_Settings__c();
        cus.clofor_com_cfs__Company_Country__c = 'JAPAN';
        cus.clofor_com_cfs__Local_Currency__c = 'JPY';
        cus.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
         insert cus;
        additionFields = new Map<String, Object> {'Phone' => '12345678', 'MailS__c' => true, 'AccountId' => account.Id};
        Contact customer = (Contact) TestDataFactory.createSObject(new Contact(), true, additionFields);
        
        additionFields = new Map<String, Object> {'Phone' => '12345678', 'MailS__c' => false, 'AccountId' => account.Id};
        Contact partner = (Contact) TestDataFactory.createSObject(new Contact(), true, additionFields);

        Map<String, Object> additionalFields = new Map<String, Object> {'clofor_com_cfs__Country_Name__c' => 'BELIZE'};     
        clofor_com_cfs__Port__c	objPort =  (clofor_com_cfs__Port__c) TestDataFactory.createSObject(new clofor_com_cfs__Port__c(), true, additionalFields);
     
        additionFields = new Map<String, Object> {'Field1__c' => account.Id, 'Partner__c' => account.Id,
            										'CustmerInCharge__c' => customer.Id,
                                                    'RecordTypeId' => rt.Id, 'PartnerRep__c' => partner.Id,
                                                    'clofor_com_cfs__POD__c' => objPort.Id
                                                };
		CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), 
                                                                                     true, additionFields);        
        
        Test.startTest();
        shipment = [SELECT Partner_Do_Not_Disturb_State__c, Customer_Do_Not_Disturb_State__c 
                    FROM CustomObject1__c 
                    WHERE Id = :shipment.Id];
        System.assertEquals(false, shipment.Partner_Do_Not_Disturb_State__c);
        System.assertEquals(true, shipment.Customer_Do_Not_Disturb_State__c);
        
        partner.MailS__c = true;
        FlsService.doUpdate(partner);
        Test.stopTest();
        
        shipment = [SELECT Partner_Do_Not_Disturb_State__c, Customer_Do_Not_Disturb_State__c 
                    FROM CustomObject1__c 
                    WHERE Id = :shipment.Id];
        System.assertEquals(true, shipment.Partner_Do_Not_Disturb_State__c);
        System.assertEquals(true, shipment.Customer_Do_Not_Disturb_State__c);
    }
}