force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WorkOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderStatus__c</fullName>
    <label>WORK ORDER STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WorkStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/WorkStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Resource Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Accept Cargo Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>On Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Data Transfer To Next Process</fullName>
        <isActive>false</isActive>
        <label>Data Transfer To Next Process</label>
    </customValue>
    <masterLabel>WORK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderTriggerHandlerTest.cls
@isTest
private class WorkOrderTriggerHandlerTest {
	private static Facility__c warehouse;
	private static WorkOrder__c workOrder;
	private static Account  accountTest;
	static{
		warehouse = createWarehouse();
		accountTest = new Account(Name = 'AccountTest1',
			EnglishCompanyName__c = 'AcountTest1');
		FlsService.doInsert(accountTest);
	}
	
	@isTest static void test_method_onAfterUpdate() {
		workOrder = new WorkOrder__c(
			WarehouseID__c = warehouse.Id,
			Customer__c = accountTest.Id);
		FlsService.doInsert(workOrder);
		Test.startTest();
			workOrder.WorkOrderStatus__c = 'Completed';
			FlsService.doUpdate(workOrder);
			system.assert(workOrder != null);
		Test.stopTest();
	}
	
	private static Facility__c createWarehouse(){
		Facility__c warehouse = new clofor_com_cfs__Facility__c(
			clofor_com_cfs__FacilityName__c ='test Ware house'
		);
		FlsService.doInsert(warehouse);
		return warehouse;
	}
}