force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>WMS Bill</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>WMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WMS Bill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/AmountOfTaxSelling__c.field-meta.xml
<CustomField>
    <fullName>AmountOfTaxSelling__c</fullName>
    <label>AMOUNT OF TAX-SELLING(LOCAL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/ChargeUnitTotal__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnitTotal__c</fullName>
    <label>CHARGE UNIT(TOTAL)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BILLING</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>INVOICE TO</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BillingInvoiceTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAYMENT TO</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BillingPaymentTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/PeriodUnit__c.field-meta.xml
<CustomField>
    <fullName>PeriodUnit__c</fullName>
    <defaultValue>1</defaultValue>
    <label>PERIOD UNIT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/PricingNameAtPrintENG__c.field-meta.xml
<CustomField>
    <fullName>PricingNameAtPrintENG__c</fullName>
    <label>PRICING NAME AT PRINT(ENG)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/PricingNameAtPrintLocal__c.field-meta.xml
<CustomField>
    <fullName>PricingNameAtPrintLocal__c</fullName>
    <label>PRICING NAME AT PRINT(LOCAL)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/TaxRatioBuying__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioBuying__c</fullName>
    <label>TAX RATE-BUYING</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/TaxRatioSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioSelling__c</fullName>
    <label>TAX RATE-SELLING</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/TotalAmountOfSellingUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfSellingUSD__c</fullName>
    <label>TOTAL AMOUNT OF SELLING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/UnitPriceOfSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceOfSellingLocal__c</fullName>
    <label>UNIT PRICE OF SELLING(LOCAL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipName>BILLING</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Standard Billing</label>
</RecordType>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WMS_InvoiceSelectionControllerTest.cls
@isTest
private class WMS_InvoiceSelectionControllerTest {
	private static WorkOrder__c workOrder{get; set;}
	private static Account customer{get; set;}
	private static Billing__c billing{get; set;}
	static{

		customer = new Account(
			name = 'Test',
			EnglishCompanyName__c = 'Test');
		Facility__c wareHouse = new Facility__c();
		FlsService.doInsert(new List<SObject> { customer, wareHouse });
		
		workOrder = new WorkOrder__c(
			Customer__c = customer.Id,
			WarehouseID__c = wareHouse.Id
			);
		FlsService.doInsert(workOrder);

		billing = new Billing__c(
			WorkOrderID__c = workOrder.Id,
			PaymentTo__c = customer.Id, 
			InvoiceTo__c = customer.Id,
			Unit__c = 'Container',
			TimeUnit__c = 'Day',
			ChargeUnitTotal__c = 10,
			PeriodUnit__c = 2,
			PricingNameAtPrintENG__c ='test',
			PricingNameAtPrintLocal__c ='Test',
			TaxRatioSelling__c = 10,
			TaxRatioBuying__c = 10,
			UnitPriceOfSellingLocal__c = 1000,
			TotalAmountOfSellingUSD__c = 1000,
			AmountOfTaxSelling__c = 100
			);
		FlsService.doInsert(billing);
	}
	
	@isTest static void test_method_initDisplay() {
		// Implement test code
		Test.startTest();
		WMS_InvoiceSelectionController.DisplayWrapper displayResult = WMS_InvoiceSelectionController.initDisplay(workOrder.Id, 'en', 'DEBIT_LOCAL');
		Map<String, String > translation = WMS_InvoiceSelectionController.getTranslationMap();
		System.assert(displayResult != null);
		Test.stopTest();
	}

	@isTest static void test_method_initDisplay2() {
		// Implement test code
		Test.startTest();
		WMS_InvoiceSelectionController.DisplayWrapper displayResult = WMS_InvoiceSelectionController.initDisplay(workOrder.Id, '', 'CREDIT_LOCAL');
		WMS_InvoiceSelectionController.createAttatchment(workOrder.Id, customer.Id,'DEBIT_LOCAL','en');
		System.assert(displayResult != null);
		Test.stopTest();
	}
	
}