force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/ConnectWOProduct__c.object-meta.xml
<CustomObject>
    <label>W/O+Product</label>
    <nameField>
        <displayFormat>WP-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/W/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectWOProduct__c/fields/BuyingWeightUnit__c.field-meta.xml
<CustomField>
    <fullName>BuyingWeightUnit__c</fullName>
    <formula>text(ProductID__r.BuyingWeightUnit__c)</formula>
    <label>BUYING WEIGHT UNIT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>ProductID__r.ProductName__c</formula>
    <label>PRODUCT NAME</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GoodsPurchasingOrder__c/GoodsPurchasingOrder__c.object-meta.xml
<CustomObject>
    <label>Goods P/O</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>GOODS PURCHASING ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods P/O</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GoodsPurchasingOrder__c/fields/GoodsPurchasingOrder__c.field-meta.xml
<CustomField>
    <fullName>GoodsPurchasingOrder__c</fullName>
    <label>GOODS PURCHASING ORDER STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OrderStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GoodsPurchasingOrder__c/fields/GoodsPurchasingOrderName__c.field-meta.xml
<CustomField>
    <fullName>GoodsPurchasingOrderName__c</fullName>
    <label>GOODS PURCHASING ORDER NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BuyingWeightUnit__c.field-meta.xml
<CustomField>
    <fullName>BuyingWeightUnit__c</fullName>
    <label>BUYING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/DeliveryServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryServiceBillingFreqType__c</fullName>
    <label>Delivery Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GuaranteeServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>GuaranteeServiceBillingFreqType__c</fullName>
    <label>Guarantee Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/InstallationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>InstallationServiceBillingFreqType__c</fullName>
    <label>Installation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/MaintenanceServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>MaintenanceServiceBillingFreqType__c</fullName>
    <label>Maintenance Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RelocationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>RelocationServiceBillingFreqType__c</fullName>
    <label>Relocation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ReplacementServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>ReplacementServiceBillingFreqType__c</fullName>
    <label>Replacement Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SetupServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SetupServiceBillingFreqType__c</fullName>
    <label>Setup Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SubscriptionChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionChargeBillingFreqType__c</fullName>
    <label>Subscription Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SupportServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SupportServiceBillingFreqType__c</fullName>
    <label>Support Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UsageChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>UsageChargeBillingFreqType__c</fullName>
    <label>Usage Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>SELLING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/recordTypes/Picking.recordType-meta.xml
<RecordType>
    <fullName>Picking</fullName>
    <active>true</active>
    <label>Picking</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/recordTypes/Putaway.recordType-meta.xml
<RecordType>
    <fullName>Putaway</fullName>
    <active>true</active>
    <label>Putaway</label>
</RecordType>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BillingFrequencyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Time Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>3 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>4 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Ad-Hoc</fullName>
    </customValue>
    <customValue>
        <fullName>No Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Times Billing</fullName>
        <isActive>false</isActive>
        <label>Multi-Times Billing</label>
    </customValue>
    <masterLabel>Billing Frequency Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OrderStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>On-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>In Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <label>Full Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Partial Returned</fullName>
    </customValue>
    <customValue>
        <fullName>Full Returned</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>ORDER &amp; CONTRACT STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WeightUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>WEIGHT UNIT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CargosPickingControllerTest.cls
@isTest
private class CargosPickingControllerTest {
	static Boolean isDataSetup = false;
	static PRODUCT__c prod;
	static PRODUCT__c prod1;
	static Account acc;
	static Facility__c fac;
	static GoodsPurchasingOrder__c po;
	static GoodsPurchasingOrder__c po1;
	static SALES_ORDER__c so;
	static SALES_ORDER__c so1;
	static GoodsPOProduct__c poProd;
	static SalesOrderProduct__c soProd;
	static WorkOrder__c wo;
	static WorkOrder__c wo1;
    static Cargo__c cargoTest;
    static Cargo__c cargoTest1;
    static ConnectWOProduct__c wop;
    static{
        Custom_Application_Config__c config =  new Custom_Application_Config__c(Disabled_Trigger__c = true);
        Contract__c con = new Contract__c();
		FlsService.doInsert(new List<SObject>{ config, con });

        fac = new Facility__c(FacilityName__c = 'Fac');
		prod = new Product__c(ProductName__c = 'prod', WeightUnit__c = 'g', BuyingWeightUnit__c = 'Kg',GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                 InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                 RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                 SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                 UsageChargeBillingFreqType__c = 'Continuous Billing', MaintenanceServiceBillingFreqType__c = 'Continuous Billing');
		prod1 = new Product__c(ProductName__c = 'prod1', GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                 InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                 RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                 SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                 UsageChargeBillingFreqType__c = 'Continuous Billing',MaintenanceServiceBillingFreqType__c = 'Continuous Billing');
        acc = new Account(name = 'testAcc', EnglishCompanyName__c = 'test');
		po = new GoodsPurchasingOrder__c(ApprovalStatus__c ='Approved', GoodsPurchasingOrderName__c = 'po', ContractID__c = con.Id);
		po1 = new GoodsPurchasingOrder__c(ApprovalStatus__c ='Approved',GoodsPurchasingOrderName__c = 'po1', ContractID__c = con.Id);
		so = new SALES_ORDER__c(ApprovalStatus__c ='Approved',SalesOrderName__c = 'so', ContractID__c = con.Id);
		so1 = new SALES_ORDER__c(ApprovalStatus__c ='Approved',SalesOrderName__c = 'so1', ContractID__c = con.Id);

		FlsService.doInsert(new List<SObject> { prod, prod1, acc, po, po1, so, so1, fac});

        wo = new WorkOrder__c(Customer__c = acc.id, SalesOrderId__c = so.Id, PurchasingOrderID__c = po.Id, WarehouseId__c = fac.Id);
        wo1 = new WorkOrder__c(Customer__c = acc.id, SalesOrderId__c = so1.Id, PurchasingOrderID__c = po1.Id, WarehouseId__c = fac.Id);
		poProd = new GoodsPOProduct__c(ProductId__c = prod.Id, GoodsPOID__c = po.Id, PlanQuantity__c = 2, TotalNetWeight__c = 1500);
		soProd = new SalesOrderProduct__c(ProductId__c = prod.Id, GoodSalesOrderID__c = so.Id, PlannedQuantity__c = 3, TotalNetWeight__c = 1500);

        FlsService.doInsert(new List<SObject> { wo, wo1, poProd, soProd});
        
        cargoTest = new Cargo__c(Product__c = prod.Id);
        cargoTest1 = new Cargo__c(Product__c = prod.Id);
        FlsService.doInsert(new List<Cargo__c>{ cargoTest, cargoTest1 });
        
        WorkOrderService__c wosPutaway= new WorkOrderService__c(
        	WorkOrder__c = wo.Id,
            RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('Putaway').getRecordTypeId()
        );
		FlsService.doInsert(wosPutaway);

        WOSLineItem__c wosl = new WOSLineItem__c(
            WorkOrderService__c = wosPutaway.Id,
            Cargo__c = cargoTest.Id
        );
        WOSLineItem__c wosl1 = new WOSLineItem__c(
            WorkOrderService__c = wosPutaway.Id,
            Cargo__c = cargoTest1.Id
        );
		FlsService.doInsert(new List<WOSLineItem__c>{wosl,wosl1});

        cargoTest.LastWosLineItem__c = wosl.Id;
        cargoTest.CargoLifeCycle__c = 'For sales';
        cargoTest1.LastWosLineItem__c = wosl.Id;
        cargoTest1.CargoLifeCycle__c = 'For sales';
        FlsService.doUpdate(new List<Cargo__c>{cargoTest, cargoTest1});

        WorkOrderService__c wosPicking= new WorkOrderService__c(
        	WorkOrder__c = wo1.Id,
            RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('Picking').getRecordTypeId()
        );
        FlsService.doInsert(wosPicking);
        
        WOSLineItem__c wosl2 = new WOSLineItem__c(
            WorkOrderService__c = wosPicking.Id,
            Cargo__c = cargoTest1.Id
        );
		FlsService.doInsert(wosl2);

        wop = new ConnectWOProduct__c(
            ProductID__c = prod.Id,
            WorkOrderID__c = wo1.Id,
            Quantity__c = 10
        );
		FlsService.doInsert(wop);
    }
    @IsTest static void test_CargosPicking() {
        Test.startTest();
        CargosPickingController.getData(wop.Id, null, null);
        CargosPickingController.pickCargos(wop.Id, new List<String> {cargoTest.Id},'Name','asc' );
        Integer x = 1;
        system.assert(x !=null);
        Test.stopTest();
    }
}