force-app/main/default/objects/Account/fields/EnglishAddress__c.field-meta.xml
<CustomField>
    <fullName>EnglishAddress__c</fullName>
    <inlineHelpText>Input Company Address in English and it will appear On B/L, A/N and other documents.</inlineHelpText>
    <label>ENGLISH ADDRESS</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/ContainerGoodSO__c.object-meta.xml
<CustomObject>
    <label>Container (Goods S/O)</label>
    <nameField>
        <displayFormat>CTR-{000000}</displayFormat>
        <label>CNTR (Goods S/O) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Container (Goods S/Os)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContainerGoodSO__c/fields/GrossWeightMT__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightMT__c</fullName>
    <label>Gross Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/NetWeightMT__c.field-meta.xml
<CustomField>
    <fullName>NetWeightMT__c</fullName>
    <label>Net Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContainerGoodSO__c/fields/TRSBill__c.field-meta.xml
<CustomField>
    <fullName>TRSBill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TRS Bill</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TRSBill__c.SalesOrderID__c</field>
            <operation>equals</operation>
            <valueField>$Source.GOODSSO__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TRSBill__c</referenceTo>
    <relationshipLabel>Container (Goods S/Os)</relationshipLabel>
    <relationshipName>TRSBill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract.</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>CONTRACT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <label>CONTRACT NUMBER</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ContractSignedDate__c.field-meta.xml
<CustomField>
    <fullName>ContractSignedDate__c</fullName>
    <label>CONTRACT SIGNED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/NotifyParty__c.field-meta.xml
<CustomField>
    <fullName>NotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONTRACT. (Notify Party)</relationshipLabel>
    <relationshipName>CONTRACT1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/NotifyPartysAddress__c.field-meta.xml
<CustomField>
    <fullName>NotifyPartysAddress__c</fullName>
    <label>Notify Party&apos;s Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PortofDischarge__c.field-meta.xml
<CustomField>
    <fullName>PortofDischarge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>CONTRACT. (Port of Discharge)</relationshipLabel>
    <relationshipName>CONTRACT1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PortofLoading__c.field-meta.xml
<CustomField>
    <fullName>PortofLoading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>CONTRACT.</relationshipLabel>
    <relationshipName>CONTRACT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/SellerCompany__c.field-meta.xml
<CustomField>
    <fullName>SellerCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONTRACT. (Seller Company)</relationshipLabel>
    <relationshipName>CONTRACTSeller</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <customHelpPage>OnlineHelpPorts</customHelpPage>
    <description>Port</description>
    <label>ポートコード</label>
    <nameField>
        <label>Port name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
            <value>
                <fullName>BULGARIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/SALES_ORDER__c.object-meta.xml
<CustomObject>
    <label>Goods S/O</label>
    <nameField>
        <displayFormat>GS-{000000}</displayFormat>
        <label>GOODS SALES ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods S/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SALES_ORDER__c/fields/CommercialInvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>CommercialInvoiceNo__c</fullName>
    <label>Commercial Invoice No#</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/CommodityDescriptionofGoods__c.field-meta.xml
<CustomField>
    <fullName>CommodityDescriptionofGoods__c</fullName>
    <label>Commodity Description of Goods</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/ContractID__c.field-meta.xml
<CustomField>
    <fullName>ContractID__c</fullName>
    <label>CONTRACT ID</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/CustomerAddress__c.field-meta.xml
<CustomField>
    <fullName>CustomerAddress__c</fullName>
    <label>Customer&apos; Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/CustomerCompanyName__c.field-meta.xml
<CustomField>
    <fullName>CustomerCompanyName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER COMPANY NAME</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/LCDate__c.field-meta.xml
<CustomField>
    <fullName>LCDate__c</fullName>
    <label>L/C Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/LCNo__c.field-meta.xml
<CustomField>
    <fullName>LCNo__c</fullName>
    <label>L/C No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/NotifyParty__c.field-meta.xml
<CustomField>
    <fullName>NotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GOODS S/O (Notify Party)</relationshipLabel>
    <relationshipName>GOODS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/NumberofContainer_inwords__c.field-meta.xml
<CustomField>
    <fullName>NumberofContainer_inwords__c</fullName>
    <label>Number of Container (in words)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/Packing__c.field-meta.xml
<CustomField>
    <fullName>Packing__c</fullName>
    <label>Packing</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <label>Payment Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/PortofDischarge__c.field-meta.xml
<CustomField>
    <fullName>PortofDischarge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>GOODS S/O (Port of Discharge)</relationshipLabel>
    <relationshipName>GOODS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/PortofLoading__c.field-meta.xml
<CustomField>
    <fullName>PortofLoading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>GOODS S/O</relationshipLabel>
    <relationshipName>GOODS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/RollupJumboBagWeightMTfromTRSBill__c.field-meta.xml
<CustomField>
    <fullName>RollupJumboBagWeightMTfromTRSBill__c</fullName>
    <inlineHelpText>Sum of Weight of jumbo bags and pallets (MT) from related TRS Billing</inlineHelpText>
    <label>Rollup JumboBag Weight(MT)-from TRS Bill</label>
    <summarizedField>TRSBill__c.Weightofjumbobagsandpallets_MT__c</summarizedField>
    <summaryForeignKey>TRSBill__c.SalesOrderID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SALES_ORDER__c/fields/SellerCompany__c.field-meta.xml
<CustomField>
    <fullName>SellerCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GOODS S/O (Seller Company)</relationshipLabel>
    <relationshipName>GoodSOAccountSeller</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/TRSBill__c.object-meta.xml
<CustomObject>
    <label>TRS Bill</label>
    <nameField>
        <displayFormat>TB-{000000}</displayFormat>
        <label>TRS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TRS Bill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TRSBill__c/fields/GrossWeightMT__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightMT__c</fullName>
    <label>Gross Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/fields/NetWeightMT__c.field-meta.xml
<CustomField>
    <fullName>NetWeightMT__c</fullName>
    <label>Net Weight(MT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/fields/ProductNamedetailatprintEng__c.field-meta.xml
<CustomField>
    <fullName>ProductNamedetailatprintEng__c</fullName>
    <label>Product Name detail at print(Eng)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TRSBill__c/fields/SalesOrderID__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderID__c</fullName>
    <label>SALES ORDER ID</label>
    <referenceTo>SALES_ORDER__c</referenceTo>
    <relationshipLabel>TRS BILL</relationshipLabel>
    <relationshipName>TRSBill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorldExportController.cls
public with sharing class WorldExportController {
    public Site_Custom_Settings__c siteSetting {get; set;}
    public SALES_ORDER__c so {get; set;}
    public List<BillWrapper> billWrappers {get; set;}
    public Decimal totalShipmentNetWeightMT {get; set;}
    public Decimal totalShipmentGrossWeightMT {get; set;}
    public Boolean showFooter{get;set;}

    public WorldExportController() {
        String soId = ApexPages.currentPage().getParameters().get('id').escapeHtml4();
        showFooter = Boolean.valueOf(ApexPages.currentPage().getParameters().get('showFooter'));
        siteSetting = Site_Custom_Settings__c.getOrgDefaults();
        so = new SALES_ORDER__c();
        billWrappers = new List<BillWrapper>();
        totalShipmentNetWeightMT = 0;
        totalShipmentGrossWeightMT = 0;

        if(!String.isBlank(soId)){
            so = getSalesOrder(soId);
            getBillWrappers(soId);
        }
    }

    private SALES_ORDER__c getSalesOrder(String soId){
        SALES_ORDER__c salesOrder = new SALES_ORDER__c();
        salesOrder = [
            SELECT Id,
            CommercialInvoiceNo__c,
            InvoiceDate__c,
            ContractID__r.ContractNumber__c,
            ContractID__r.ContractSignedDate__c,
            ContractID__r.SellerCompany__r.Name,
            ContractID__r.SellerCompany__r.EnglishAddress__c,
            CustomerAddress__c,
            CustomerCompanyName__r.Name, 
            NotifyParty__r.Name,
            NotifyPartysAddress__c,
            PortofLoading__r.Name,
            PortofLoading__r.Country_Name__c,
            PortofDischarge__r.Name,
            PortofDischarge__r.Country_Name__c,
            PaymentCondition__c,
            LCNo__c,
            LCDate__c,
            CommodityDescriptionofGoods__c,
            NETWeightKG__c,
            RollupJumboBagWeightMTfromTRSBill__c,
            GrossWeightKG__c, 
            Packing__c,
            NumberofContainer_inwords__c,
            (SELECT ProductNamedetailatprintEng__c, NetWeightMT__c, GrossWeightMT__c FROM TRSBill__r ORDER BY name),
            RollupNWMTfromTRSBill__c,
            RollupGWMTfromTRSBill__c,
            ReceiptancePaymentType__c
            FROM SALES_ORDER__c
            WHERE Id =: soId WITH SECURITY_ENFORCED ];
        return salesOrder;
    }
    
    private void getBillWrappers(string soId){
        List<TRSBill__c> trsBills = [
            SELECT Id, ProductNameonPackingList__c
                FROM TRSBill__c
                WHERE SalesOrderID__c = :soId WITH SECURITY_ENFORCED ORDER BY Name];
        
        List<ContainerGoodSO__c> containerGoodSOs = [
            SELECT ContainerNumber__c,
                SealNumber__c,
                NetWeightMT__c,
                GrossWeightMT__c,
                TRSBill__c
                FROM ContainerGoodSO__c
                WHERE GOODSSO__c = :soId and TRSBill__c != null WITH SECURITY_ENFORCED ORDER BY TRSBill__r.Name];

        for(TRSBill__c trsBill : trsBills){
            BillWrapper billWrapper = new BillWrapper();

            billWrapper.productNameonPackingList = trsBill.ProductNameonPackingList__c;
            for(ContainerGoodSO__c containerGoodSO: containerGoodSOs){
                if(containerGoodSO.TRSBill__c == trsBill.Id){
                    billWrapper.containerGoodSOs.add(containerGoodSO);
                    
                    if(containerGoodSO.NetWeightMT__c!= null){
                        billWrapper.totalNetWeightMT += containerGoodSO.NetWeightMT__c;
                    }
                    if(containerGoodSO.GrossWeightMT__c!= null){
                        billWrapper.totalGrossWeightMT += containerGoodSO.GrossWeightMT__c;
                    }
                }
            }

            if(billWrapper.containerGoodSOs.size() != 0){
                totalShipmentNetWeightMT += billWrapper.totalNetWeightMT;
                totalShipmentGrossWeightMT += billWrapper.totalGrossWeightMT;
                
                billWrapper.romanNumber = intToRoman(billWrappers.size() + 1) + '/';
                billWrappers.add(billWrapper);
            }
        }
    }

    public static string intToRoman(integer index){
        return  'I'.repeat(index)
                  .replace('IIIII', 'V')
                  .replace('IIII', 'IV')
                  .replace('VV', 'X')
                  .replace('VIV', 'IX')
                  .replace('XXXXX', 'L')
                  .replace('XXXX', 'XL')
                  .replace('LL', 'C');
                //   .replace('LXL', 'XC')
                //   .replace('CCCCC', 'D')
                //   .replace('CCCC', 'CD')
                //   .replace('DD', 'M')
                //   .replace('DCD', 'CM');
      }

    public class BillWrapper{
        public string productNameonPackingList{get; set;}
        public string id{get; set;}
        public string romanNumber{get; set;}
        public List<ContainerGoodSO__c> containerGoodSOs{get; set;}
        public Decimal totalNetWeightMT{get; set;}
        public Decimal totalGrossWeightMT{get; set;}

        public BillWrapper(){
            productNameonPackingList = '';
            romanNumber = '';
            containerGoodSOs = new List<ContainerGoodSO__c>();
            totalNetWeightMT = 0;
            totalGrossWeightMT = 0;
        }
    }
}