force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/VAT_Running_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Running_Number__c</fullName>
    <label>VAT Running Number</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/TariffMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ServiceMasterOnlineHelp</customHelpPage>
    <description>Service Master</description>
    <label>サービスプライシング</label>
    <nameField>
        <label>SERVICE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TariffMaster__c/fields/CUSTOMER__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PRICING</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/EngSubcategory__c.field-meta.xml
<CustomField>
    <fullName>EngSubcategory__c</fullName>
    <label>SUB-CATEGORY(ENG)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subcategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Basic charge</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Excluded</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Included</fullName>
            </value>
            <value>
                <fullName>CY Charge</fullName>
            </value>
            <value>
                <fullName>B/L FEE</fullName>
            </value>
            <value>
                <fullName>THC</fullName>
            </value>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>FAF</fullName>
            </value>
            <value>
                <fullName>BAF</fullName>
            </value>
            <value>
                <fullName>YAS</fullName>
            </value>
            <value>
                <fullName>EBS</fullName>
            </value>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>GBF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS</fullName>
            </value>
            <value>
                <fullName>FAF/BAF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS/EBS</fullName>
            </value>
            <value>
                <fullName>CO-LOAD</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>D/O FEE</fullName>
            </value>
            <value>
                <fullName>DOC FEE</fullName>
            </value>
            <value>
                <fullName>System Charges</fullName>
            </value>
            <value>
                <fullName>W/H IN &amp; OUT CHARGE</fullName>
            </value>
            <value>
                <fullName>SEAL</fullName>
            </value>
            <value>
                <fullName>PORT CHARGE(OWN COMPANY FORWARDING)</fullName>
            </value>
            <value>
                <fullName>PORT CHARGE(OTHER&apos;S FORWARDING)</fullName>
            </value>
            <value>
                <fullName>Consolidation Allocation</fullName>
            </value>
            <value>
                <fullName>DETENTION CHARGE</fullName>
            </value>
            <value>
                <fullName>TRUCKING FEE</fullName>
            </value>
            <value>
                <fullName>Triaxial</fullName>
            </value>
            <value>
                <fullName>Wait charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>SUB-CATEGORY(LOCAL)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductSearch__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Basic Charge</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Excluded</fullName>
            </value>
            <value>
                <fullName>OCEAN FREIGHT Surcharge Included</fullName>
            </value>
            <value>
                <fullName>CY CHARGE</fullName>
            </value>
            <value>
                <fullName>B/L FEE</fullName>
            </value>
            <value>
                <fullName>THC</fullName>
            </value>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>FAF</fullName>
            </value>
            <value>
                <fullName>BAF</fullName>
            </value>
            <value>
                <fullName>YAS</fullName>
            </value>
            <value>
                <fullName>EBS</fullName>
            </value>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>GBF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS</fullName>
            </value>
            <value>
                <fullName>FAF/BAF</fullName>
            </value>
            <value>
                <fullName>FAF/YAS/EBS</fullName>
            </value>
            <value>
                <fullName>CO-LOAD</fullName>
            </value>
            <value>
                <fullName>HDS</fullName>
            </value>
            <value>
                <fullName>D/O FEE</fullName>
            </value>
            <value>
                <fullName>DOC FEE</fullName>
            </value>
            <value>
                <fullName>System Charges</fullName>
            </value>
            <value>
                <fullName>Detention Charge</fullName>
            </value>
            <value>
                <fullName>W/H IN &amp; OUT CHARGE</fullName>
            </value>
            <value>
                <fullName>SEAL</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges</fullName>
            </value>
            <value>
                <fullName>Ocean Freight including all charges(Advance Payment)</fullName>
            </value>
            <value>
                <fullName>Consolidation Allocation</fullName>
            </value>
            <value>
                <fullName>Trucking(20&apos;)</fullName>
            </value>
            <value>
                <fullName>Trucking(40&apos;)</fullName>
            </value>
            <value>
                <fullName>Container Drayage(Tri-x chassis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/UNIT__c.field-meta.xml
<CustomField>
    <fullName>UNIT__c</fullName>
    <inlineHelpText>When R/TON is chosen, weight and CBM are compared and larger one is taken as R/TON in Charge Unit of HB/L S/B. When CBM is chosen, CBM is taken as charge unit in HB/L S/B.</inlineHelpText>
    <label>UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bale</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>件</fullName>
                <label>Case</label>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>コンテナ</fullName>
                <label>Container</label>
            </value>
            <value>
                <fullName>CTN</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>KM</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Packet</fullName>
            </value>
            <value>
                <fullName>PALLET</fullName>
            </value>
            <value>
                <fullName>Piece</fullName>
            </value>
            <value>
                <fullName>R/TON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>本</fullName>
                <label>Unit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TariffMaster__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipName>PRICING</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TariffMaster__c/recordTypes/Warehouse.recordType-meta.xml
<RecordType>
    <fullName>Warehouse</fullName>
    <active>true</active>
    <description>Choose this Pricing when related with Warehouse.</description>
    <label>WAREHOUSING</label>
</RecordType>

force-app/main/default/objects/VAT_INVOICE__c/VAT_INVOICE__c.object-meta.xml
<CustomObject>
    <label>VAT/INV</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>VAT INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VAT_INVOICE__c/recordTypes/CloWMSVATInvoice.recordType-meta.xml
<RecordType>
    <fullName>CloWMSVATInvoice</fullName>
    <active>true</active>
    <description>To Issue VAT Invoice for CloWMS</description>
    <label>CloWMS VAT INVOICE</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FMS_VATInvoiceSelectionControllerTest.cls
@isTest
private class FMS_VATInvoiceSelectionControllerTest {
	private static WorkOrder__c workOrder{get; set;}
	private static VAT_INVOICE__c currentVAT_FMS{get; set;}
	private static TariffMaster__c pricingName{get; set;}
	private static Account customer{get; set;}
	static{
		Site_Custom_Settings__c setting = new Site_Custom_Settings__c(
			VAT_Running_Number__c = 1,
			Company_Country__c ='VietNam' ,
			Local_Currency__c='VND');
		FlsService.doInsert(setting);
		pricingName = new TariffMaster__c(
			UNIT__c = 'B/L',
			Subcategory__c = 'B/L FEE',
			EngSubcategory__c ='B/L FEE',
			VATInvoiceAtPrintLocal__c='pricing test',
			VATInvoiceAtPrintENG__c ='pricing test'

		);
		FlsService.doInsert(pricingName);
		customer = new Account(
			name = 'Test',
			EnglishCompanyName__c = 'Test');
		FlsService.doInsert(customer);
		Facility__c wareHouse = new Facility__c();
		FlsService.doInsert(wareHouse);
		workOrder = new WorkOrder__c(
			Customer__c = customer.Id,
			WarehouseID__c = wareHouse.Id
			);
		FlsService.doInsert(workOrder);
		
        Map<String,Schema.RecordTypeInfo> recordTypeInfosMap = Schema.SObjectType.VAT_INVOICE__c.getRecordTypeInfosByDeveloperName();

		currentVAT_FMS = new VAT_INVOICE__c(
			RecordTypeId = recordTypeInfosMap.get('CloWMSVATInvoice').getRecordTypeId()
			);
		FlsService.doInsert(currentVAT_FMS);
	}
	@isTest static void test_method_Contructor() {
		Test.startTest();
		ApexPages.currentPage().getParameters().put('invoiceId', currentVAT_FMS.Id);
		FMS_VATInvoiceSelectionController ctrl = new FMS_VATInvoiceSelectionController();
		ctrl.requiredAttachmentCreation = true;
		ctrl.generateInvoice();
		System.assert(currentVAT_FMS.Id != NULL);
		Test.stopTest();
		// Implement test code
	}

	
	
	
}