force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract.</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>CONTRACT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacExternalID__c.field-meta.xml
<CustomField>
    <fullName>FacExternalID__c</fullName>
    <externalId>true</externalId>
    <label>FAC EXTERNAL ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/BuyingWeightUnit__c.field-meta.xml
<CustomField>
    <fullName>BuyingWeightUnit__c</fullName>
    <label>BUYING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/DeliveryServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryServiceBillingFreqType__c</fullName>
    <label>Delivery Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GuaranteeServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>GuaranteeServiceBillingFreqType__c</fullName>
    <label>Guarantee Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/InstallationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>InstallationServiceBillingFreqType__c</fullName>
    <label>Installation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/MaintenanceServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>MaintenanceServiceBillingFreqType__c</fullName>
    <label>Maintenance Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IF(ISBLANK(External_ID__c), Name, External_ID__c)</formula>
    <inlineHelpText>Manufacture Code will be set as default. If there is no Manufacture Code, the Product ID will be set.</inlineHelpText>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RelocationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>RelocationServiceBillingFreqType__c</fullName>
    <label>Relocation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ReplacementServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>ReplacementServiceBillingFreqType__c</fullName>
    <label>Replacement Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SetupServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SetupServiceBillingFreqType__c</fullName>
    <label>Setup Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SubscriptionChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionChargeBillingFreqType__c</fullName>
    <label>Subscription Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SupportServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SupportServiceBillingFreqType__c</fullName>
    <label>Support Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UsageChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>UsageChargeBillingFreqType__c</fullName>
    <label>Usage Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>SELLING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BillingFrequencyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Time Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>3 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>4 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Ad-Hoc</fullName>
    </customValue>
    <customValue>
        <fullName>No Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Times Billing</fullName>
        <isActive>false</isActive>
        <label>Multi-Times Billing</label>
    </customValue>
    <masterLabel>Billing Frequency Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WeightUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>WEIGHT UNIT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TruckMarketApiV2Test.cls
@isTest
private class TruckMarketApiV2Test {
	static PRODUCT__c prod;
	static PRODUCT__c prod1;
	static Account acc;
	static Facility__c fac;
	static Facility__c fac1;
	static Facility__c fac2;
    static Map<String, Object> apiRequest;
	
	static void queryTestData() {
		fac   = [SELECT Id, FacExternalID__c FROM Facility__c WHERE FacExternalID__c = 'Origin' LIMIT 1];
		fac1  = [SELECT Id, FacExternalID__c FROM Facility__c WHERE FacExternalID__c = 'Destination1' LIMIT 1];
		fac2  = [SELECT Id, FacExternalID__c FROM Facility__c WHERE FacExternalID__c = 'Destination2' LIMIT 1];
		prod  = [SELECT Id, Name, QR_Code__c FROM Product__c WHERE ProductName__c = 'prod' LIMIT 1];
		prod1 = [SELECT Id, Name, QR_Code__c FROM Product__c WHERE ProductName__c = 'prod1' LIMIT 1];
		acc   = [SELECT Id, EnglishCompanyName__c FROM Account LIMIT 1];
        
		apiRequest = new Map<String, Object> {
            'Warehouses' => new Object[] {
                new Map<String, Object> {
                    'OriginWarehouseID' => fac.FacExternalID__c,
                    'AccountName' => acc.EnglishCompanyName__c,
                    'Destinations' => new Object[] {
                        new Map<String, Object> {
                            'DestinationWarehouseID' => fac1.FacExternalID__c,
                            'Customers' => new Object[] {},
                            'ProductOrder' => new Object[] {
                                new Map<String, Object> { 'ProductID' => prod.Name, 'Amount' => 3 },
                                new Map<String, Object> { 'ProductID' => prod1.Name, 'Amount' => 7000 }
                            }
                        },
                        new Map<String, Object> {
                            'DestinationWarehouseID' => fac2.FacExternalID__c,
                            'Customers' => new Object[] {},
                            'ProductOrder' => new Object[] {
                                new Map<String, Object> { 'ProductID' => prod.Name, 'Amount' => 4 },
                                new Map<String, Object> { 'ProductID' => prod1.Name, 'Amount' => 8000 }
                            }
                        }
                    }
                }
            }
        };
	}

    @TestSetUp static void testSetup(){
        fac   = new Facility__c(FacExternalID__c = 'Origin');
        fac1  = new Facility__c(FacExternalID__c = 'Destination1');
        fac2  = new Facility__c(FacExternalID__c = 'Destination2');
        prod  = new Product__c(ProductName__c = 'prod', BillingType__c = 'Unit', WeightUnit__c = 'g', BuyingWeightUnit__c = 'Kg', MaintenanceServiceBillingFreqType__c = 'Continuous Billing',
                              GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                 InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                 RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                 SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                 UsageChargeBillingFreqType__c = 'Continuous Billing');
        prod1 = new Product__c(ProductName__c = 'prod1', BillingType__c = 'Weight', WeightUnit__c = 'g', BuyingWeightUnit__c = 'Kg', MaintenanceServiceBillingFreqType__c = 'Continuous Billing',
                              GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                 InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                 RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                 SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                 UsageChargeBillingFreqType__c = 'Continuous Billing');
        acc   = new Account(name = 'testAcc', EnglishCompanyName__c = 'testAcc');

        FlsService.doInsert(new List<SObject> { prod, prod1, acc, fac, fac1, fac2, new Contract__c() });
    }
    
    @IsTest static void test(){
        queryTestData();

        Test.startTest();
        TruckMarketWrapper.TruckMarketResponse apiResponse = new TruckMarketApiV2.TruckMarketApiService().execute(JSON.serialize(apiRequest));
        Test.stopTest();

        System.assert(apiResponse.status);
    }
}