force-app/main/default/objects/Account/fields/EnglishCompanyName__c.field-meta.xml
<CustomField>
    <fullName>EnglishCompanyName__c</fullName>
    <description>英語の会社名を入れるところです。</description>
    <inlineHelpText>Input Company Name in English</inlineHelpText>
    <label>ACCOUNT NAME(ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WMS_WO_CombineServiceTest.cls
@isTest
private class WMS_WO_CombineServiceTest {
	@TestSetUp static void testSetUP(){
        Account acc = new Account();
        acc.name = 'testAcc';
        acc.EnglishCompanyName__c = 'test';
        FlsService.doInsert(acc);
        
        facility__c fac = new facility__c();
        FlsService.doInsert(fac);
        
        WorkOrder__c wo = new WorkOrder__c();
        wo.Customer__c = acc.id;
        wo.WarehouseID__c = fac.id;
        //Id RecordTypeIdWorkOrder = Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByName().get('DeveloperNameOfRecordType').getRecordTypeId();
        FlsService.doInsert(wo);
        
        WorkOrderService__c wos = new WorkOrderService__c();
        wos.WorkOrder__c = wo.id;
        FlsService.doInsert(wos);
    }
	@isTest static void test_getInfo() {
        Test.startTest();
        WorkOrder__c wo = [select id from WorkOrder__c limit 1];
        Facility__c fac = [select id from facility__c limit 1];
        WMS_WO_CombineService.getInfo(wo.id, fac.id);
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
	}
	
	@isTest static void test_getInfoNegative() {
        Test.startTest();
        try{
            Facility__c fac = [select id from facility__c limit 1];
			WMS_WO_CombineService.getInfo('001000000000000', fac.id);
        }catch(exception ex){
            
        }
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
	}
    
    @IsTest static void test_CombineTransfer(){
        Test.startTest();
        try{
            WorkOrder__c wo = [select id, WarehouseID__c from WorkOrder__c limit 1];
            WorkOrderService__c wos = [select id from WorkOrderService__c limit 1];
            String payloadStr = '[{"destinationId":"'+wo.WarehouseId__c+'","destination":{"Name":"FC-000242","clofor_com_cfs__FacilityName__c":"Test Facility","Id":"a0r0K00005VH5kKQAT"},"cargos":[{"productId":"a0s0K000005fyqNQAQ","productQty":"4","cargoQty":"5","cargoType":"Barrel"}]}]';
            List<String> payloads = new List<String>();
            payloads.add(wos.id);
            
            WMS_WO_CombineService.combineService(wo.id, payloads);
            
        }catch(exception ex){
            
        }	
        Integer x = 1;
        System.assert(x != null);
        Test.stopTest();
    }
	
}