force-app/main/default/objects/Account/fields/EnglishAddress__c.field-meta.xml
<CustomField>
    <fullName>EnglishAddress__c</fullName>
    <inlineHelpText>Input Company Address in English and it will appear On B/L, A/N and other documents.</inlineHelpText>
    <label>ENGLISH ADDRESS</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract.</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>CONTRACT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/BuyersAddress__c.field-meta.xml
<CustomField>
    <fullName>BuyersAddress__c</fullName>
    <label>Buyer&apos;s Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/CommodityDescriptionofGoodsPI__c.field-meta.xml
<CustomField>
    <fullName>CommodityDescriptionofGoodsPI__c</fullName>
    <label>Commodity Description of Goods-PI</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <label>CONTRACT NUMBER</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CONTRACTOR NAME</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONTRACT</relationshipLabel>
    <relationshipName>Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ContractSignedDate__c.field-meta.xml
<CustomField>
    <fullName>ContractSignedDate__c</fullName>
    <label>CONTRACT SIGNED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/NotifyParty__c.field-meta.xml
<CustomField>
    <fullName>NotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONTRACT. (Notify Party)</relationshipLabel>
    <relationshipName>CONTRACT1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/NotifyPartysAddress__c.field-meta.xml
<CustomField>
    <fullName>NotifyPartysAddress__c</fullName>
    <label>Notify Party&apos;s Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PortofDischarge__c.field-meta.xml
<CustomField>
    <fullName>PortofDischarge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>CONTRACT. (Port of Discharge)</relationshipLabel>
    <relationshipName>CONTRACT1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PortofLoading__c.field-meta.xml
<CustomField>
    <fullName>PortofLoading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>CONTRACT.</relationshipLabel>
    <relationshipName>CONTRACT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ProformaInvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>ProformaInvoiceDate__c</fullName>
    <label>Proforma Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ProformaInvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>ProformaInvoiceNo__c</fullName>
    <label>Proforma Invoice No#</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/SellerCompany__c.field-meta.xml
<CustomField>
    <fullName>SellerCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONTRACT. (Seller Company)</relationshipLabel>
    <relationshipName>CONTRACTSeller</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/TotalAmountofSellingFCYtext__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingFCYtext__c</fullName>
    <label>Total Amount of Selling(FCY)-text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/UnitpriceChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>UnitpriceChargeUnit__c</fullName>
    <label>Unit price/Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Unitpricewillbechargedbaseon__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD/MT</fullName>
            </value>
            <value>
                <fullName>USD/Pallet</fullName>
            </value>
            <value>
                <fullName>USD/Bag</fullName>
            </value>
            <value>
                <fullName>USD/Carton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Unitpricewillbechargedbaseon__c.field-meta.xml
<CustomField>
    <fullName>Unitpricewillbechargedbaseon__c</fullName>
    <label>Unit price will be charged base on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gross Weight</fullName>
            </value>
            <value>
                <fullName>Net Weight</fullName>
            </value>
            <value>
                <fullName>G.W (MT)</fullName>
            </value>
            <value>
                <fullName>N.W (MT)</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Bag</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractProduct__c/ContractProduct__c.object-meta.xml
<CustomObject>
    <label>Contract+Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Contract+Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract+Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractProduct__c/fields/BillNameatPrintENG__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintENG__c</fullName>
    <label>Bill Name at Print(ENG)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/CONTRACT__c.field-meta.xml
<CustomField>
    <fullName>CONTRACT__c</fullName>
    <label>CONTRACT</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract+Products</relationshipLabel>
    <relationshipName>Contract_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanChargeQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlanChargeQuantity__c</fullName>
    <label>Plan Charge Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanGrossWeightMT__c.field-meta.xml
<CustomField>
    <fullName>PlanGrossWeightMT__c</fullName>
    <label>Plan Gross Weight(MT)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanNetWeightMT__c.field-meta.xml
<CustomField>
    <fullName>PlanNetWeightMT__c</fullName>
    <label>Plan Net Weight(MT)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/PlanTotalAmountofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>PlanTotalAmountofSellingFCY__c</fullName>
    <formula>PlanChargeQuantity__c   *  UnitPriceofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan Total Amount of Selling(FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractProduct__c/fields/UnitPriceofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingFCY__c</fullName>
    <label>Unit Price of Selling(FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <customHelpPage>OnlineHelpPorts</customHelpPage>
    <description>Port</description>
    <label>ポートコード</label>
    <nameField>
        <label>Port name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
            <value>
                <fullName>BULGARIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/classes/ProformaInvoiceController.cls
public with sharing class ProformaInvoiceController {
  public Site_Custom_Settings__c siteSetting { get; set; }
  public Contract__c contract { get; set; }
  public List<ContractProduct__c> contractProducts { get; set; }
  public Decimal totalWeightMT { get; set; }
  public Decimal totalUnitPrice { get; set; }
  public Decimal totalAmount { get; set; }
  public String bankType { get; set; }
  public Boolean showFooter{get;set;}
  public String sayContext{get;set;}

  public ProformaInvoiceController() {
    String contractId = ApexPages.currentPage()
      .getParameters()
      .get('id')
      .escapeHtml4();
    bankType = ApexPages.currentPage().getParameters().get('bankType');
    showFooter = Boolean.valueOf(ApexPages.currentPage().getParameters().get('showFooter'));

    siteSetting = Site_Custom_Settings__c.getOrgDefaults();
    contract = new Contract__c();
    contractProducts = new List<ContractProduct__c>();
    totalWeightMT = 0;
    totalUnitPrice = 0;
    totalAmount = 0;
    sayContext = '';

    if (bankType == null) {
      bankType = 'local1';
    }

    if (!String.isBlank(contractId)) {
      contract = getContract(contractId);
      getContractProducts(contractId);
      if(contract != null && contract.TotalAmountofSellingFCYtext__c != null) {
 
        sayContext = contract.TotalAmountofSellingFCYtext__c;
      }
    }
  }

  private Contract__c getContract(String contractId) {
    Contract__c con = new Contract__c();
    con = [
      SELECT
        Id,
        SellerCompany__r.Name,
        SellerCompany__r.EnglishAddress__c,
        ProformaInvoiceNo__c,
        ProformaInvoiceDate__c,
        ContractNumber__c,
        ContractSignedDate__c,
        ContractorName__r.Name,
        BuyersAddress__c,
        PortofLoading__r.Name,
        PortofLoading__r.Country_Name__c,
        PortofDischarge__r.Name,
        PortofDischarge__r.Country_Name__c,
        PaymentCondition__c,
        //LCNo__c,
        //LCDate__c,
        Unitpricewillbechargedbaseon__c,
        UnitpriceChargeUnit__c,
        CommodityDescriptionofGoodsPI__c,
        TotalAmountofSellingFCYtext__c,
        Notes__c,
        ReceiptancePaymentType__c,
        NotifyParty__c,
        NotifyParty__r.Name,
        NotifyPartysAddress__c
      FROM Contract__c
      WHERE Id = :contractId
      WITH SECURITY_ENFORCED
    ];
    return con;
  }

  private void getContractProducts(string contractId) {
    contractProducts = [
      SELECT
        BillNameatPrintENG__c,
        PlanGrossWeightMT__c,
        PlanNetWeightMT__c,
        PlanChargeQuantity__c,
        UnitPriceofSellingFCY__c,
        PlanTotalAmountofSellingFCY__c
      FROM ContractProduct__c
      WHERE CONTRACT__c = :contractId
      WITH SECURITY_ENFORCED
    ];

    for (ContractProduct__c conProc : contractProducts) {
      if (
        contract.Unitpricewillbechargedbaseon__c == 'G.W (MT)' &&
        conProc.PlanGrossWeightMT__c != null
      ) {
        totalWeightMT += conProc.PlanGrossWeightMT__c;
      }

      if (
        contract.Unitpricewillbechargedbaseon__c == 'N.W (MT)' &&
        conProc.PlanNetWeightMT__c != null
      ) {
        totalWeightMT += conProc.PlanNetWeightMT__c;
      }

      if (
        contract.Unitpricewillbechargedbaseon__c != 'G.W (MT)' &&
        contract.Unitpricewillbechargedbaseon__c != 'N.W (MT)' &&
        conProc.PlanChargeQuantity__c != null
      ) {
        totalWeightMT += conProc.PlanChargeQuantity__c;
      }

      if (conProc.UnitPriceofSellingFCY__c != null) {
        totalUnitPrice += conProc.UnitPriceofSellingFCY__c;
      }
      if (conProc.PlanTotalAmountofSellingFCY__c != null) {
        totalAmount += conProc.PlanTotalAmountofSellingFCY__c;
      }
    }
  }
}