force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <inlineHelpText>Choose &apos;Yes&apos; and Customs Clearance Object will be created. Put detail of the customs clearance in to the object accordingly.</inlineHelpText>
    <label>CUSTOMS CLEARANCE SERVICE REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>×(NO)</fullName>
            </value>
            <value>
                <fullName>○(YES)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL__c.field-meta.xml
<CustomField>
    <fullName>HBL__c</fullName>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/MultiTransitRequired__c.field-meta.xml
<CustomField>
    <fullName>MultiTransitRequired__c</fullName>
    <label>MULTI TRANSIT REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO</fullName>
                <default>true</default>
                <label>NO</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TranporationType__c.field-meta.xml
<CustomField>
    <fullName>TranporationType__c</fullName>
    <label>CONTAINER MODE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>MTY</fullName>
            </value>
            <value>
                <fullName>MTY &amp; FCL</fullName>
            </value>
            <value>
                <fullName>Consol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName1__c</fullName>
    <label>FCY Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName2__c</fullName>
    <label>FCY Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName1__c</fullName>
    <label>Local Currency Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName2__c</fullName>
    <label>Local Currency Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName3__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName3__c</fullName>
    <label>Local Currency Bank Account Short Name-3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName4__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName4__c</fullName>
    <label>Local Currency Bank Account Short Name-4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName5__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName5__c</fullName>
    <label>Local Currency Bank Account Short Name-5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transit__c/Transit__c.object-meta.xml
<CustomObject>
    <label>積替</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>TRANSIT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transit__c/fields/InOrderOfTransit__c.field-meta.xml
<CustomField>
    <fullName>InOrderOfTransit__c</fullName>
    <label>IN ORDER OF TRANSIT</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transit__c/fields/ShipmentOrder__c.field-meta.xml
<CustomField>
    <fullName>ShipmentOrder__c</fullName>
    <label>SHIPMENT ORDER</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipLabel>TRANSIT</relationshipLabel>
    <relationshipName>TRANSIT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TransitTriggerHandlerTest.cls
/**
 * Created by khanhpham on 7/17/17.
 */

@IsTest
private with sharing class TransitTriggerHandlerTest {
    @testsetup static void setUp() {
        Date etd = Date.newInstance(2015, 01, 02);
        Date eta = Date.newInstance(2015, 02, 02);
        RecordType rt = [Select Id from RecordType where DeveloperName = :Constants.OCEAN_IMPORT_RT];
        Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
        Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
        Map<String, Object> additionFields = new Map<String, Object>{
                'Field1__c' => account.Id, 'HBL__c' => 'T123',
                'RecordTypeId' => rt.Id, 'ETD__c' => etd, 'ETA__c' => eta,
                'Custom__c' => PicklistReference.CUSTOMER_CLEARANCE_SERVICE_REQUIRED_YES,
                'TranporationType__c' => 'LCL', 'MultiTransitRequired__c' => '1'
        };
        TestDataFactory.createSObject(new CustomObject1__c(), true, additionFields);
        System.assert(true);
    }

    @IsTest static void shouldAssignCorrectOrder() {
        CustomObject1__c shipment = [SELECT Id FROM CustomObject1__c WHERE HBL__c = 'T123'];
        System.assertNotEquals(null, shipment);

        RecordType rt = [Select Id from RecordType where DeveloperName = :Constants.TRANSIT_SHIPMENT_RT];
        Map<String, Object> additionFields = new Map<String, Object>{
                'RecordTypeId' => rt.Id, 'ShipmentOrder__c' => shipment.Id
        };
        Transit__c transit = (Transit__c) TestDataFactory.createSObject(new Transit__c(), false, additionFields);

        Test.startTest();
        FlsService.doInsert(transit);
        Test.stopTest();
        transit = [SELECT Id, InOrderOfTransit__c FROM Transit__c WHERE Id = :transit.Id];
        System.assertEquals(2, transit.InOrderOfTransit__c);
    }

    @IsTest static void shouldFailIfOutOfRangeOrder() {
        CustomObject1__c shipment = [SELECT Id FROM CustomObject1__c WHERE HBL__c = 'T123'];
        Transit__c transit = [SELECT Id, InOrderOfTransit__c FROM Transit__c WHERE ShipmentOrder__c = :shipment.Id];

        System.assertEquals(1, transit.InOrderOfTransit__c);
        Test.startTest();

        try {
            transit.InOrderOfTransit__c = 10;
            FlsService.doUpdate(transit);
            
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }

        Test.stopTest();
    }
}