force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONTAINER__c/CONTAINER__c.object-meta.xml
<CustomObject>
    <label>CNTR In W/D/Y</label>
    <nameField>
        <displayFormat>CTNR-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR In W/D/Y</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Container2__c.field-meta.xml
<CustomField>
    <fullName>Container2__c</fullName>
    <label>CONTAINER TYPE-2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Container3__c.field-meta.xml
<CustomField>
    <fullName>Container3__c</fullName>
    <label>CONTAINER TYPE-3</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Container4__c.field-meta.xml
<CustomField>
    <fullName>Container4__c</fullName>
    <label>CONTAINER TYPE-4</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <inlineHelpText>When Container Type and Container Qnty is input, Container Information object is automatically created. Input Container/Seal No in the object accordingly.</inlineHelpText>
    <label>CONTAINER TYPE-1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/LoadLocation__c.field-meta.xml
<CustomField>
    <fullName>LoadLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Refer to Master A/N to confirm about loading Warehouse</inlineHelpText>
    <label>CARGO LOADING WAREHOUSE(LOCAL)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>LoadLocation__c.WharehouseCompany__c</field>
            <operation>equals</operation>
            <valueField>$Source.BookingNv__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LoadLocation__c</referenceTo>
    <relationshipLabel>F/TMS S/O</relationshipLabel>
    <relationshipName>LoadLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/MasterAnkenName__c.field-meta.xml
<CustomField>
    <fullName>MasterAnkenName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Choose only when Consolidation Cargo or Groupage Cargo</inlineHelpText>
    <label>MASTER SHIPMENT NAME</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ETD__c</field>
            <operation>equals</operation>
            <valueField>MasterAnken__c.METD__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>MasterAnken__c</referenceTo>
    <relationshipName>MasterBL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/InAir.recordType-meta.xml
<RecordType>
    <fullName>InAir</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Air Import Shipment.</description>
    <label>Air Import</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/LoadLocation__c/LoadLocation__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_WarehouseOnlineHelp</customHelpPage>
    <description>Warehouse (Load Location)</description>
    <label>CFS・CY・DEPOT</label>
    <nameField>
        <label>WAREHOUSE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LoadLocation__c/fields/WharehouseCompany__c.field-meta.xml
<CustomField>
    <fullName>WharehouseCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE CORPORATE NAME</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>WharehouseCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/MasterAnken__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLOnlineHelp</customHelpPage>
    <description>M B/L - SHIPMENTS</description>
    <label>混載</label>
    <nameField>
        <label>MASTER SHIPMENT NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnken__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MasterAnkenTorihikisaki</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MBookingNv__c.field-meta.xml
<CustomField>
    <fullName>MBookingNv__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>当社を選択してください。</description>
    <inlineHelpText>Your company&apos;s consolidation;put your company name, Put the carrier name or consolidator(Co-loader) in other shipments</inlineHelpText>
    <label>MASTER CONSOLIDATOR/CARRIER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CONSOLIDATION (MASTER CONSOLIDATOR/CARRIER)</relationshipLabel>
    <relationshipName>M_BL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/METD__c.field-meta.xml
<CustomField>
    <fullName>METD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MLoadLocation__c.field-meta.xml
<CustomField>
    <fullName>MLoadLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARGO LOADING WAREHOUSE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.MBookingNv__c</field>
            <operation>equals</operation>
            <valueField>LoadLocation__c.WharehouseCompany__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LoadLocation__c</referenceTo>
    <relationshipLabel>CONSOLIDATION (CARGO LOADING WAREHOUSE)</relationshipLabel>
    <relationshipName>M_BL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CopyingMShipDataToHShipControllerTest.cls
@isTest(SeeAllData=false)
public class CopyingMShipDataToHShipControllerTest {

    static testmethod void shouldCopyDataFromMShipToHShips() {
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'InAir'];
        Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
        clofor_com_cfs__Site_Custom_Settings__c cus = new clofor_com_cfs__Site_Custom_Settings__c();
        cus.clofor_com_cfs__Company_Country__c = 'JAPAN';
        cus.clofor_com_cfs__Local_Currency__c = 'JPY';
        cus.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
         insert cus;
        Map<String, Object> additionFields = new Map<String, Object> {'WharehouseCompany__c' => account.Id};
        LoadLocation__c loadLocation = (LoadLocation__c) TestDataFactory.createSObject(new LoadLocation__c(), true, additionFields);
        
        Date etd = Date.newInstance(2015, 07, 04);
        additionFields = new Map<String, Object> {'METD__c' => etd, 'MBookingNv__c' => account.Id, 'MLoadLocation__c' => loadLocation.Id};
        MasterAnken__c mship = (MasterAnken__c) TestDataFactory.createSObject(new MasterAnken__c(), true, additionFields);
        
        additionFields = new Map<String, Object> {'Field1__c' => account.Id, 'MasterAnkenName__c' => mship.Id, 'RecordTypeId' => rt.Id,
                                                    'Container2__c' =>'AIR',
                                                    'Container3__c' =>'AIR',
                                                    'Container4__c' =>'AIR',
                                                    'Container__c' =>'AIR',
                                                    'clofor_com_cfs__ContainerNumber__c' => 1, 'clofor_com_cfs__ContainerNumber2__c' => 1, 'clofor_com_cfs__ContainerNumber3__c' => 1,
                                                    'clofor_com_cfs__ContainerNumber4__c' => 1
                                                };
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionFields);
        
        PageReference pageRef = Page.page_CopyingMShipDataToHShips;
        pageRef.getParameters().put('Id', mship.Id);
        Test.setCurrentPage(pageRef);
		
        Test.startTest();
        CopyingMShipDataToHShipController controller = new CopyingMShipDataToHShipController();
        controller.copy();
        Test.stopTest();
        
        CustomObject1__c actual = [SELECT ETD__c FROM CustomObject1__c WHERE Id = :shipment.Id];
        System.assertEquals(actual.ETD__c, actual.ETD__c);
    }
}