force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container_Info__c/Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Info__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <label>CONTAINER TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexitank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/Container_NO__c.field-meta.xml
<CustomField>
    <fullName>Container_NO__c</fullName>
    <inlineHelpText>Please enter 11digits(4digit container ownership code+7digit container code)</inlineHelpText>
    <label>CONTAINER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONTAINER_INFO_MAPPINGS__c/CONTAINER_INFO_MAPPINGS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Container Info Mappings</label>
</CustomObject>

force-app/main/default/objects/CONTAINER_INFO_MAPPINGS__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONTAINER_INFO_MAPPINGS__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONTAINER_INFO_MAPPINGS__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Container2__c.field-meta.xml
<CustomField>
    <fullName>Container2__c</fullName>
    <label>CONTAINER TYPE-2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <inlineHelpText>When Container Type and Container Qnty is input, Container Information object is automatically created. Input Container/Seal No in the object accordingly.</inlineHelpText>
    <label>CONTAINER TYPE-1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>20&apos;ISO</fullName>
            </value>
            <value>
                <fullName>40&apos;ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ContainerNumber2__c.field-meta.xml
<CustomField>
    <fullName>ContainerNumber2__c</fullName>
    <label>CONTAINER QNTY-2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ContainerNumber3__c.field-meta.xml
<CustomField>
    <fullName>ContainerNumber3__c</fullName>
    <label>CONTAINER QNTY-3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ContainerNumber__c.field-meta.xml
<CustomField>
    <fullName>ContainerNumber__c</fullName>
    <inlineHelpText>Number in this field create the same number of Container Information object.</inlineHelpText>
    <label>CONTAINER QNTY-1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TakeContainerUnitfromSO__c.field-meta.xml
<CustomField>
    <fullName>TakeContainerUnitfromSO__c</fullName>
    <label>Take Container Unit from S/O?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName1__c</fullName>
    <label>FCY Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName2__c</fullName>
    <label>FCY Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName1__c</fullName>
    <label>Local Currency Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName2__c</fullName>
    <label>Local Currency Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName3__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName3__c</fullName>
    <label>Local Currency Bank Account Short Name-3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName4__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName4__c</fullName>
    <label>Local Currency Bank Account Short Name-4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName5__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName5__c</fullName>
    <label>Local Currency Bank Account Short Name-5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetupContainerInfoControllerTest.cls
@isTest
public class SetupContainerInfoControllerTest {
    @testSetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object>{'Name' => 'F40DC', 'Type__c' => '40\'DC', 
            												'Code__c' => 'GP : Dry Container', 'Size__c' => '42'};
        TestDataFactory.createSObject(new CONTAINER_INFO_MAPPINGS__c(), true, additionalFields);
        
        additionalFields = new Map<String, Object>{'Name' => 'F20DC', 'Type__c' => '20\'DC', 
				            								'Code__c' => 'GP : Dry Container', 'Size__c' => '22'};
		TestDataFactory.createSObject(new CONTAINER_INFO_MAPPINGS__c(), true, additionalFields);

		additionalFields = new Map<String, Object>{'Name' => 'F20DC', 'Type__c' => '40\'HC', 
				            								'Code__c' => 'GP : Dry Container', 'Size__c' => '22'};
		TestDataFactory.createSObject(new CONTAINER_INFO_MAPPINGS__c(), true, additionalFields);

		additionalFields = new Map<String, Object>{'Name' => 'F20DC', 'Type__c' => '40\'OT', 
				            								'Code__c' => 'GP : Dry Container', 'Size__c' => '22'};
		TestDataFactory.createSObject(new CONTAINER_INFO_MAPPINGS__c(), true, additionalFields);
    }
    
    testmethod static void shouldNotSaveDuplicatedContainerNumbers() {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
		Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
        Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
        Map<String, Object> additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => rt.Id,
            															'ContainerNumber__c' => 2, 'Container__c' => '40\'DC', 'TakeContainerUnitfromSO__c' => 'Yes'
            															};
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
        
        PageReference pageReference = new PageReference('/apex/page_SetupContainerInfo?parentId=' + shipment.Id);
        Test.setCurrentPage(pageReference);
        
        Test.startTest();
        SetupContainerInfoController controller = new SetupContainerInfoController();
        if(controller.containers.size()>0) {
            Container_Info__c info1 = controller.containers.get(0);
            info1.Container_NO__c = 'AAAA1234567';
        }
        if(controller.containers.size()>1) {
            Container_Info__c info2 = controller.containers.get(1);
            info2.Container_NO__c = 'AAAA1234567';
        }
        PageReference nextPage = controller.save();
        Test.stopTest();
        System.assert(true);
    }

    testmethod static void shouldNotSaveInvalidContainerNumber() {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
		Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
        Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
        Map<String, Object> additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => rt.Id,
            															'ContainerNumber__c' => 1, 'Container__c' => '40\'DC'
            															};
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
        PageReference pageReference = new PageReference('/apex/page_SetupContainerInfo?parentId=' + shipment.Id);
        Test.setCurrentPage(pageReference);
        
        Test.startTest();
        
        SetupContainerInfoController controller = new SetupContainerInfoController();
        if(controller.containers.size() > 0) {
            Container_Info__c info = controller.containers.get(0);
            info.Container_NO__c = '123';
        }
        PageReference nextPage = controller.save();
        
        Test.stopTest();
        //System.assert(nextPage != null);
        System.assert(true);
    }

	testmethod static void shouldSaveInfo() {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'RecordType'];
        
		Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
        Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
        Map<String, Object> additionalFields = new Map<String, Object> {'Field1__c' => account.Id, 'RecordTypeId' => rt.Id,
            															'ContainerNumber__c' => 5, 'Container__c' => '40\'DC',
															            'ContainerNumber2__c' => 6, 'Container2__c' => '20\'DC',
            															'ContainerNumber3__c' => 7, 'Container3__c' => '40\'HC',
            															'ContainerNumber4__c' => 8, 'Container4__c' => '40\'OT',
            															'TakeContainerUnitfromSO__c' => 'Yes'
															            };
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionalFields);
        PageReference pageReference = new PageReference('/apex/page_SetupContainerInfo?parentId=' + shipment.Id);
        Test.setCurrentPage(pageReference);
        
        Test.startTest();

        SetupContainerInfoController controller = new SetupContainerInfoController();
        PageReference nextPage = controller.save();

        Test.stopTest();

        //System.assertEquals('/' + shipment.Id, nextPage.getUrl());
    }
}