force-app/main/default/objects/Account/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/Cargo_Delivery__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CargoDeliveryOnlineHelp</customHelpPage>
    <description>Cargo Delivery</description>
    <label>配送</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Cargo Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo_Delivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Expected Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L-SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Cargo_Delivery</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/fields/Pickupdate__c.field-meta.xml
<CustomField>
    <fullName>Pickupdate__c</fullName>
    <inlineHelpText>Pickup Date must be earlier than Delivery Date.</inlineHelpText>
    <label>Pickup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/recordTypes/Consolidation_Truck_Import.recordType-meta.xml
<RecordType>
    <fullName>Consolidation_Truck_Import</fullName>
    <active>true</active>
    <description>Arrange a truck combine several individual cargo to make up a full for Inbound cargo</description>
    <label>Consolidation Truck-Inbound</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <inlineHelpText>Choose &apos;Yes&apos; and Customs Clearance Object will be created. Put detail of the customs clearance in to the object accordingly.</inlineHelpText>
    <label>CUSTOMS CLEARANCE SERVICE REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>×(NO)</fullName>
            </value>
            <value>
                <fullName>○(YES)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>EXPECTED DELIVERY DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DeliveryService_required__c.field-meta.xml
<CustomField>
    <fullName>DeliveryService_required__c</fullName>
    <inlineHelpText>Choose the number of Pickup or Delivery Required and TRANSPORT object will be created according to the number. To create object, Transportation Type must be chosen. Input the detail of pickup/delivery information to the object.</inlineHelpText>
    <label>PICKUP OR DELIVERY REQUIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TranporationType__c.field-meta.xml
<CustomField>
    <fullName>TranporationType__c</fullName>
    <label>CONTAINER MODE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>MTY</fullName>
            </value>
            <value>
                <fullName>MTY &amp; FCL</fullName>
            </value>
            <value>
                <fullName>Consol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/classes/CargoDeliveryTriggerTest.cls
@isTest
private class CargoDeliveryTriggerTest {
    @testsetup static void setUp() {
        Date etd = Date.newInstance(2015, 01, 02);
        Date eta = Date.newInstance(2015, 02, 02);
        RecordType rt = [Select Id from RecordType where DeveloperName = :Constants.CROSS_BOARDER_RT AND SobjectType = 'clofor_com_cfs__CustomObject1__c'];
        Account account = (Account) TestDataFactory.createSObject(new Account(), true, null);
        clofor_com_cfs__Site_Custom_Settings__c cus = new clofor_com_cfs__Site_Custom_Settings__c();
        cus.clofor_com_cfs__Company_Country__c = 'JAPAN';
        cus.clofor_com_cfs__Local_Currency__c = 'JPY';
        cus.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
         insert cus;
        Map<String, Object> additionFields = new Map<String, Object> {'clofor_com_cfs__Country_Name__c' => 'BELIZE'};     
        clofor_com_cfs__Port__c	objPort =  (clofor_com_cfs__Port__c) TestDataFactory.createSObject(new clofor_com_cfs__Port__c(), true, additionFields);

        additionFields = new Map<String, Object> {'Field1__c' => account.Id, 
            									'RecordTypeId' => rt.Id, 'ETD__c' => etd, 'ETA__c' => eta,
            									'Custom__c' => PicklistReference.CUSTOMER_CLEARANCE_SERVICE_REQUIRED_YES,
                                                'TranporationType__c' => 'LCL', 'DeliveryService_required__c' => '1',
                                                'clofor_com_cfs__POD__c' => objPort.Id};
        CustomObject1__c shipment = (CustomObject1__c) TestDataFactory.createSObject(new CustomObject1__c(), true, additionFields);        
    }
    
    testmethod static void shouldInsertCargoDelivery() {
        Date pickupDate = Date.newInstance(2015, 04, 02);
        Date deliveryDate = Date.newInstance(2015, 05, 02);
        CustomObject1__c shipment = [select Id, DeliveryService_required__c from CustomObject1__c limit 1];
        
        System.assertNotEquals(null, shipment);
        System.assertEquals('1', shipment.DeliveryService_required__c);
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Consolidation_Truck_Import'];
        Map<String, Object> additionalFields = new Map<String, Object> {'HBL_SHIPMENT__c' => shipment.Id, 'RecordTypeId' => rt.Id,
            									'Pickupdate__c' => pickupDate, 'DeliveryDate__c' => deliveryDate};
		Cargo_Delivery__c cd = (Cargo_Delivery__c) TestDataFactory.createSObject(new Cargo_Delivery__c(), false, additionalFields);
        
        Test.startTest();
		FlsService.doInsert(cd);
        Test.stopTest();
        shipment = [select Id, DeliveryService_required__c from CustomObject1__c where Id = :shipment.Id];
        
        System.assertNotEquals(null, shipment);
        System.assertEquals('2', shipment.DeliveryService_required__c);
    }
    
    testmethod static void shouldUpdateCargoDelivery() {
        Date pickupDate = Date.newInstance(2015, 04, 02);
        Date deliveryDate = Date.newInstance(2015, 05, 02);
        CustomObject1__c shipment = [select Id, DeliveryService_required__c from CustomObject1__c limit 1];
        
        System.assertNotEquals(null, shipment);
        System.assertEquals('1', shipment.DeliveryService_required__c);

		Cargo_Delivery__c cd = [select Id, Pickupdate__c, DeliveryDate__c from Cargo_Delivery__c limit 1];
        cd.DeliveryDate__c = deliveryDate;
        cd.Pickupdate__c = pickupDate;
        
        Test.startTest();
			FlsService.doUpdate(cd);
        Test.stopTest();
        
        cd = [select Id, Pickupdate__c, DeliveryDate__c from Cargo_Delivery__c limit 1];
        System.assertEquals(pickupDate, cd.Pickupdate__c);
        System.assertEquals(deliveryDate, cd.DeliveryDate__c);
    }
    
    testmethod static void shouldUpdateShipmentOnCargoDeliveryDelete() {
        CustomObject1__c shipment = [select Id, DeliveryService_required__c from CustomObject1__c limit 1];
        
        System.assertNotEquals(null, shipment);
        System.assertEquals('1', shipment.DeliveryService_required__c);

		Cargo_Delivery__c cd = [select Id, Pickupdate__c, DeliveryDate__c from Cargo_Delivery__c limit 1];
        
        Test.startTest();
        FlsService.doDelete(cd);
        Test.stopTest();
        
        shipment = [select Id, DeliveryService_required__c from CustomObject1__c where Id = :shipment.Id];
        System.assertEquals('0', shipment.DeliveryService_required__c);
    }
}