force-app/main/default/objects/Account/fields/Mail_Merge_Company_Signature__c.field-meta.xml
<CustomField>
    <fullName>Mail_Merge_Company_Signature__c</fullName>
    <formula>$Setup.Site_Custom_Settings__c.Company_Signature__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mail Merge Company Signature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/Cargo_Delivery__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_CargoDeliveryOnlineHelp</customHelpPage>
    <description>Cargo Delivery</description>
    <label>配送</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Cargo Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo_Delivery__c/fields/DeliveryCompany__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TRUCKING COMPANY</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cargo_Delivery</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo_Delivery__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L-SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Cargo_Delivery</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/carton__c.field-meta.xml
<CustomField>
    <fullName>carton__c</fullName>
    <inlineHelpText>Synchronized with Sum of Cargo Quantity in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are not null, Cargo Quantity in CNTR IN TRANS is not Null.</inlineHelpText>
    <label>QUANTITY(TOTAL PACKAGES)</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/CBM__c.field-meta.xml
<CustomField>
    <fullName>CBM__c</fullName>
    <inlineHelpText>Synchronized with Sum of Measurement(CBM) in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are is not null, Measurement(CBM) in CNTR IN TRANS is not null.</inlineHelpText>
    <label>MEASUREMENT(TOTAL CBM)</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Cnee__c.field-meta.xml
<CustomField>
    <fullName>Cnee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cnee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HAWB__c.field-meta.xml
<CustomField>
    <fullName>HAWB__c</fullName>
    <label>HAWB No.</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Mail_Merge_Company_Signature__c.field-meta.xml
<CustomField>
    <fullName>Mail_Merge_Company_Signature__c</fullName>
    <formula>$Setup.Site_Custom_Settings__c.Company_Signature__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mail Merge Company Signature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Marks_and_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Marks_and_Numbers__c</fullName>
    <label>Marks and Numbers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bag</fullName>
            </value>
            <value>
                <fullName>Bale</fullName>
            </value>
            <value>
                <fullName>Bale,compressed</fullName>
            </value>
            <value>
                <fullName>Bale,non-compressed</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Barrel</fullName>
            </value>
            <value>
                <fullName>Basket</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
            </value>
            <value>
                <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
            </value>
            <value>
                <fullName>Bulk, liquid</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, fineparticles(powders）</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, granular particles(grains）</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, large particles(nodules）</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Cage</fullName>
            </value>
            <value>
                <fullName>Can,cylindrical</fullName>
            </value>
            <value>
                <fullName>Can,rectangular</fullName>
            </value>
            <value>
                <fullName>Carboy,non-protected</fullName>
            </value>
            <value>
                <fullName>Carboy,protected</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
                <default>true</default>
                <label>Carton</label>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Cask</fullName>
            </value>
            <value>
                <fullName>Chest</fullName>
            </value>
            <value>
                <fullName>Coil</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Crate</fullName>
            </value>
            <value>
                <fullName>Cylinder</fullName>
            </value>
            <value>
                <fullName>DemiJohn,non-protected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/weight__c.field-meta.xml
<CustomField>
    <fullName>weight__c</fullName>
    <inlineHelpText>Synchronized with Sum of Gross Weight(Kg) in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are is not null, Gross Weight(Kg) in CNTR IN TRANS is not null.</inlineHelpText>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/recordTypes/CrossBoarder.recordType-meta.xml
<RecordType>
    <fullName>CrossBoarder</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Cross-Boarder Shipment.</description>
    <label>Cross-Boarder</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/CrossBoarderLock.recordType-meta.xml
<RecordType>
    <fullName>CrossBoarderLock</fullName>
    <active>true</active>
    <label>Cross-Boarder(Lock)</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/Domestic_Transportation.recordType-meta.xml
<RecordType>
    <fullName>Domestic_Transportation</fullName>
    <active>true</active>
    <description>Choose this record type to create a new Domestic Shipment.</description>
    <label>Domestic Transportation</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/Domestic_Transportation_Lock.recordType-meta.xml
<RecordType>
    <fullName>Domestic_Transportation_Lock</fullName>
    <active>true</active>
    <label>Domestic Transportation(Lock)</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/InAir.recordType-meta.xml
<RecordType>
    <fullName>InAir</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Air Import Shipment.</description>
    <label>Air Import</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/OutAir.recordType-meta.xml
<RecordType>
    <fullName>OutAir</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Air Export Shipment.</description>
    <label>Air Export</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Export Shipment.</description>
    <label>Ocean Export</label>
</RecordType>

force-app/main/default/objects/CustomObject1__c/recordTypes/RecordType1.recordType-meta.xml
<RecordType>
    <fullName>RecordType1</fullName>
    <active>true</active>
    <description>Choose this record type to create a new shipment record for Ocean Import Shipment.</description>
    <label>Ocean Import</label>
</RecordType>

force-app/main/default/classes/DeliveryLetterSelectionController.cls
public with sharing class DeliveryLetterSelectionController {
    public CustomObject1__c shipment { get; private set; }
    public Cargo_Delivery__c cargoDelivery { get; private set; }
    public boolean requiredAttachmentCreation { get; set; }
    public String openUrl { get; private set; }
    public String errorMessage { get; private set; }
    public Map<String, String> translations { get; private set; }
    public List<SelectOption> languages { get; private set; }
    public String selectedLanguage { get; set; }
    public List<SelectOption> letters { get; private set; }
    public String selectedLetter { get; set; }
    public List<SelectOption> locations { get; private set; }
    public String selectedLocation { get; set; }

    private String shipmentId;
    private Map<String, List<SelectOption>> lettersPerLanguage;
    private Map<String, ReportMappings> reportMappings = new Map<String, ReportMappings>();

    public DeliveryLetterSelectionController() {
        selectedLanguage = UserInfo.getLanguage();
        initializeTranslation();

        shipmentId = ApexPages.currentPage().getParameters().get('id');
        shipmentId = StringUtils.escapeSingleQuotes(shipmentId);

        if (PermissionValidationUtil.isAccessibleAccount() && PermissionValidationUtil.isAccessibleHBL()) {
            loadCargoDeliveries(shipmentId);
        }

        buildLanguagesPerReportMappings();
        languages = new List<SelectOption>();
        languages.add(new SelectOption('en_US', 'English'));
        languages.add(new SelectOption('ja', '日本語'));
        languages.add(new SelectOption('vi', 'Tiếng Việt'));
        languages.add(new SelectOption('ko', '한국어'));

        letters = lettersPerLanguage.get(selectedLanguage);
    }

    public void showDeliveryLetter() {
        errorMessage = null;
        if (StringUtils.isEmpty(selectedLocation) || String.isBlank(selectedLetter)) {
            errorMessage = 'You have not selected any report or no report is applicable.';
        } else {
            ReportMappings reportMapping = reportMappings.get(selectedLetter);
            if (requiredAttachmentCreation) {
                String attachmentId = createAttachment(shipmentId, selectedLocation, selectedLanguage, reportMapping);
                openUrl = '/servlet/servlet.FileDownload?file=' + attachmentId;
            } else {
                openUrl = '/apex/' + Constants.NAMESPACE + reportMapping.reportPage + '?shipmentId=' + shipmentId
                        + '&cargoId=' + selectedLocation + '&lang=' + selectedLanguage;
            }
        }
    }

    public void refreshLettersList() {
        letters = lettersPerLanguage.get(selectedLanguage);
    }

    private void initializeTranslation() {
        TranslationService translationService = new TranslationService('InvoiceSelection', UserInfo.getLanguage());
        translations = translationService.getTranslations();
    }

    private void buildLanguagesPerReportMappings() {
        String recordType = getRecordType(shipmentId);
        List<ReportMappings> mappings = setupReportMappings();
        lettersPerLanguage = new Map<String, List<SelectOption>>();

        for (ReportMappings mapping : mappings) {
            // 2019/08/13 Chien Truong MODIFY START
            /*
            if (StringUtils.isContainedInCommaSeparateString(mapping.recordTypes, recordType)) {
                reportMappings.put(mapping.id, mapping);
                if (lettersPerLanguage.containsKey(mapping.language)) {
                    lettersPerLanguage.get(mapping.language).add(new SelectOption(mapping.id, mapping.reportDisplayedName));
                } else {
                    List<SelectOption> report = new List<SelectOption>();
                    report.add(new SelectOption(mapping.id, mapping.reportDisplayedName));
                    lettersPerLanguage.put(mapping.language, report);
                }
            }*/

            reportMappings.put(mapping.id, mapping);
            if (lettersPerLanguage.containsKey(mapping.language)) {
                lettersPerLanguage.get(mapping.language).add(new SelectOption(mapping.id, mapping.reportDisplayedName));
            } else {
                List<SelectOption> report = new List<SelectOption>();
                report.add(new SelectOption(mapping.id, mapping.reportDisplayedName));
                lettersPerLanguage.put(mapping.language, report);
            }
            // 2019/08/13 Chien Truong MODIFY END
        }
    }

    private String getRecordType(String recordId) {
        if (PermissionValidationUtil.isAccessibleHBL()) {
            CustomObject1__c hbl = [SELECT RecordTypeId FROM CustomObject1__c WHERE Id = :recordId];
            String recordType = RecordTypeUtil.getRecordTypeDeveloperNameById(CustomObject1__c.SObjectType, hbl.RecordTypeId);

            return recordType;
        }
        return null;
    }

    private List<ReportMappings> setupReportMappings() {
        List<ReportMappings> mappings = new List<ReportMappings>();

        //[AIR/OCEAN IMPORT]Loading and unloading Request Form
        mappings.add(new ReportMappings('en_US_loading_unloading', 'Cargo Delivery Request Form（Common）', 'page_LoadUnloadLocations', 'en_US', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ja_loading_unloading', '配送依頼書（共通）', 'page_LoadUnloadLocations_JP', 'ja', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ko_loading_unloading', '배송의뢰서(공통)', 'page_LoadUnloadLocations_KR', 'ko', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('vi_loading_unloading', 'Mẫu yêu cầu giao hàng – Thông thường', 'page_LoadUnloadLocationsVI', 'vi', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));

        //[AIR/OCEAN EXPORT]Loading and unloading Request Form For Truck
        mappings.add(new ReportMappings('en_US_loading_unloading_truck', 'Cargo Delivery Request Form（Truck）', 'page_LoadUnloadTruck', 'en_US', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ja_loading_unloading_truck', '配送依頼書（トラック用）', 'page_LoadUnloadTruck_JP', 'ja', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ko_loading_unloading_truck', '배송의뢰서(트럭용)', 'page_LoadUnloadTruck_KR', 'ko', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('vi_loading_unloading_truck', 'Mẫu yêu cầu giao hàng cho vận chuyển', 'page_LoadUnloadTruckVI', 'vi', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));

        //[OCEAN IMPORT/EXPORT]Drayage Request Form
        mappings.add(new ReportMappings('en_US_oceanexport_drayage_request', 'Cargo Delivery Request Form（Drayage）', 'page_DrayageRequest', 'en_US', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ja_oceanexport_drayage_request', '配送依頼書（ドレー用）', 'page_DrayageRequest_JP', 'ja', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ko_oceanexport_drayage_request', '배송의뢰서(도레지용)', 'page_DrayageRequest_KR', 'ko', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('vi_oceanexport_drayage_request', 'Mẫu yêu cầu giao hàng cho Container Drayage', 'page_DrayageRequestVI', 'vi', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));

        //[Drayage] Invoice of Cargo
        mappings.add(new ReportMappings('en_US_drayage_invoice', 'Cargo Receipt Note（Drayage）', 'page_DrayageInvoiceOfCargo', 'en_US', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ja_drayage_invoice', '貨物受取証（ドレージ用）', 'page_DrayageInvoiceOfCargo_JP', 'ja', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ko_drayage_invoice', '화물수령증（도레지용）', 'page_DrayageInvoiceOfCargo_KR', 'ko', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('vi_drayage_invoice', 'Giấy nhận hàng cho Container Drayage', 'page_DrayageInvoiceOfCargoVI', 'vi', 'RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));

        //[Truck] Invoice of Cargo
        mappings.add(new ReportMappings('en_US_truck_invoice', 'Cargo Receipt Note（Truck）', 'page_TruckInvoiceOfCargo', 'en_US', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ja_truck_invoice', '貨物受取証（トラック用）', 'page_TruckInvoiceOfCargo_JP', 'ja', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('ko_truck_invoice', '화물수령증（트럭용）', 'page_TruckInvoiceOfCargo_KR', 'ko', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));
        mappings.add(new ReportMappings('vi_truck_invoice', 'Giấy nhận hàng cho vận chuyển', 'page_TruckInvoiceOfCargoVI', 'vi', 'InAir,OutAir,RecordType1,RecordType, Domestic_Transportation, Domestic_Transportation_Lock, CrossBoarderLock, CrossBoarder'));

        return mappings;
    }

    private void loadCargoDeliveries(String shipmentId) {
        shipment = [
                SELECT Id, Name, Mail_Merge_Company_Signature__c, Cnee__c, UnitType__c, carton__c, CBM__c,
                        weight__c, HAWB__c, Marks_and_Numbers__c, (
                        SELECT Id, Name, DeliveryCompany__r.Name, RecordTypeId
                        FROM Cargo_Delivery__r
                        ORDER BY CreatedDate ASC
                )
                FROM CustomObject1__c
                WHERE Id = :shipmentId
        ];

        locations = new List<SelectOption>();

        List<Cargo_Delivery__c> cargoDeliveries = shipment.Cargo_Delivery__r;

        if (!cargoDeliveries.isEmpty()) {
            for (Cargo_Delivery__c cd : cargoDeliveries) {
                String deliveryName = (StringUtils.isEmpty(cd.DeliveryCompany__r.Name) ? '' : cd.DeliveryCompany__r.Name);
                String recordType = RecordTypeUtil.getRecordTypeName(Cargo_Delivery__c.SObjectType, cd.RecordTypeId);
                locations.add(new SelectOption(cd.Id, cd.Name + ' - ' + recordType + ' - ' + deliveryName));
            }
            locations.add(new SelectOption('all', translations.get('ALL')));
        }
    }

    private static String createAttachment(String shipmentId, String cargoDeliveryId, String language, ReportMappings reportMapping) {
        if (PermissionValidationUtil.isCreatableAttachment()) {
            PageReference pageRef = new PageReference('/apex/' + Constants.NAMESPACE + reportMapping.reportPage);
            pageRef.getParameters().put('shipmentId', shipmentId);
            pageRef.getParameters().put('cargoId', cargoDeliveryId);
            pageRef.getParameters().put('lang', language);

            Attachment attachment = new Attachment();
            attachment.Name = reportMapping.reportDisplayedName + '.pdf';

            String attachmentId = null;
            if (!Test.IsRunningTest()) {
                attachment.Body = pageRef.getContentAsPDF();
                attachment.ParentId = shipmentId;
                FlsService.doInsert(attachment);

                attachmentId = attachment.Id;
            }

            return attachmentId;
        }
        return null;
    }

    public class ReportMappings {
        public String id { get; private set; }
        public String reportDisplayedName { get; private set; }
        public String language { get; private set; }
        public String reportPage { get; private set; }
        public String recordTypes { get; private set; }

        public ReportMappings(String id, String reportDisplayedName, String reportPage,
                String language, String recordTypes) {
            this.id = id;
            this.reportDisplayedName = reportDisplayedName;
            this.reportPage = reportPage;
            this.language = language;
            this.recordTypes = recordTypes;
        }
    }
}