force-app/main/default/objects/ConnectInvoicingAndCash__c/ConnectInvoicingAndCash__c.object-meta.xml
<CustomObject>
    <description>Joint function to connect Invoicing to Cash</description>
    <label>F/TMS請求・仕入+現金入出</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>FMS BILL+CASH ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_INVOICING_AND_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Invoicing__c</fullName>
    <label>INVOICING</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>CONNECT_INVOICING_AND_CASH</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/FMSBillPayReq__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill+TRX Plan</label>
    <nameField>
        <displayFormat>FBPR-{000000}</displayFormat>
        <label>FMS BILL+TRX PLAN ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bill+TRX Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FMSBillPayReq__c/fields/CashID__c.field-meta.xml
<CustomField>
    <fullName>CashID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CASH ID</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipLabel>FMS BILL+TRX PLAN</relationshipLabel>
    <relationshipName>FMSBillTrxPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/FMSBillID__c.field-meta.xml
<CustomField>
    <fullName>FMSBillID__c</fullName>
    <label>FMS BILL ID</label>
    <referenceTo>AnkenMeisai__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FMSBillPayReq__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>FMSBillPayReq</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayReqCash__c/PayReqCash__c.object-meta.xml
<CustomObject>
    <label>TRX Plan+Cash</label>
    <nameField>
        <displayFormat>PRCA-{000000}</displayFormat>
        <label>TRX PLAN+CASH ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TRX Plan+Cash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayReqCash__c/fields/CashID__c.field-meta.xml
<CustomField>
    <fullName>CashID__c</fullName>
    <label>CASH ID</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>PayReqCash</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayReqCash__c/fields/PaymentRequestID__c.field-meta.xml
<CustomField>
    <fullName>PaymentRequestID__c</fullName>
    <label>PAYMENT REQUEST ID</label>
    <referenceTo>PaymentRequest__c</referenceTo>
    <relationshipName>PayReqCash</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PayReqCashTriggerHelper.cls
public with sharing class PayReqCashTriggerHelper {
    public static void connectBillToCash(List<PayReqCash__c> payReqCashNews) {
        Set<Id> paymentRequestIds = new Set<Id>();
		Set<Id> cashIds = new Set<Id>();
		Map<String, Set<String>> cashByPaymentRquestMap = new Map<String, Set<String>>();
		for(PayReqCash__c payReqCash : payReqCashNews){
			cashIds.add(payReqCash.CashID__c);
			paymentRequestIds.add(payReqCash.PaymentRequestID__c);
			if(cashByPaymentRquestMap.containsKey(payReqCash.PaymentRequestID__c)){
				cashByPaymentRquestMap.get(payReqCash.PaymentRequestID__c).add(payReqCash.CashID__c);
			}else{
				cashByPaymentRquestMap.put(payReqCash.PaymentRequestID__c, new Set<String>{payReqCash.CashID__c});
			}
		}

		// get all bill combined to Plan
		List<FMSBillPayReq__c> listBillPaymentRequest = [SELECT Id, PaymentRequestID__c, FMSBillID__c
													FROM FMSBillPayReq__c 
		
													WHERE PaymentRequestID__c IN: paymentRequestIds ];
		Set<Id> billIds = new Set<Id>();
		for(FMSBillPayReq__c billPayReq: listBillPaymentRequest){
			billIds.add(billPayReq.FMSBillID__c);
		}
		// get bill combined to planed
		List<ConnectInvoicingAndCash__c> listBillCash = [SELECT Id, Cashbook__c, Invoicing__c
													FROM ConnectInvoicingAndCash__c 
		
													WHERE Cashbook__c IN: cashIds
													AND  Invoicing__c IN: billIds];
		Map<String, Set<String>> mapBillsByCash = new Map<String, Set<String>>();
		for(ConnectInvoicingAndCash__c billCash : listBillCash){
			if(mapBillsByCash.containsKey(billCash.Cashbook__c)){
				mapBillsByCash.get(billCash.Cashbook__c).add(billCash.Invoicing__c);
			}else{
				mapBillsByCash.put(billCash.Cashbook__c, new Set<String>{billCash.Invoicing__c});
			}
		}

		Set<String> billPayReqs = new Set<String>();

		List<ConnectInvoicingAndCash__c> billCashNews = new List<ConnectInvoicingAndCash__c>();

		for(FMSBillPayReq__c billPayReq: listBillPaymentRequest){
			String key = (String)billPayReq.FMSBillID__c + (String)billPayReq.PaymentRequestID__c;
			if(!billPayReqs.contains(key)){
				billPayReqs.add(key);
				for(String cashId : cashByPaymentRquestMap.get(billPayReq.PaymentRequestID__c)){
					if(!mapBillsByCash.containsKey(cashId) 
						|| (mapBillsByCash.containsKey(cashId) && !mapBillsByCash.get(cashId).contains(billPayReq.FMSBillID__c)) ){

						ConnectInvoicingAndCash__c billCash = new ConnectInvoicingAndCash__c(
							Cashbook__c = cashId,
							Invoicing__c = billPayReq.FMSBillID__c);
						billCashNews.add(billCash);
						if(mapBillsByCash.containsKey(cashId)){
							mapBillsByCash.get(cashId).add(billPayReq.FMSBillID__c);
						}else{
							mapBillsByCash.put(cashId, new Set<String>{billPayReq.FMSBillID__c});
						}
					}
					
				}
            }
        }
        try{
        	FlsService.doInsert(billCashNews);
		}catch(Exception ex){
			payReqCashNews[0].addError(ex.getMessage());
		}
    }
}