force-app/main/default/objects/LoadLocation__c/LoadLocation__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_WarehouseOnlineHelp</customHelpPage>
    <description>Warehouse (Load Location)</description>
    <label>CFS・CY・DEPOT</label>
    <nameField>
        <label>WAREHOUSE NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnken__c/MasterAnken__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_MBLOnlineHelp</customHelpPage>
    <description>M B/L - SHIPMENTS</description>
    <label>混載</label>
    <nameField>
        <label>MASTER SHIPMENT NAME</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterAnken__c/fields/bondedtimetoCFS__c.field-meta.xml
<CustomField>
    <fullName>bondedtimetoCFS__c</fullName>
    <inlineHelpText>Put the date when cargo manifest to customs is done</inlineHelpText>
    <label>LCL MANIFEST SUBMISSION TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MContainer_No__c.field-meta.xml
<CustomField>
    <fullName>MContainer_No__c</fullName>
    <inlineHelpText>Container Number/Seal Number</inlineHelpText>
    <label>Container No &amp; Seal No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MDevan__c.field-meta.xml
<CustomField>
    <fullName>MDevan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>When consolidation, put the company name responsible for Vanning/Export - Devanning/Import</inlineHelpText>
    <label>VANNING/DEVAN OPERATION COMPANY</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MDevan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MDevanningDate__c.field-meta.xml
<CustomField>
    <fullName>MDevanningDate__c</fullName>
    <inlineHelpText>When consolidation, put the date of Vanning for export and date of Devanning for import</inlineHelpText>
    <label>VANNING/DEVAN DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MDevanRep__c.field-meta.xml
<CustomField>
    <fullName>MDevanRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PIC OF VANNING/DEVAN COMPANY</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.MDevan__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MDevanRep</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MDevanWarehouse__c.field-meta.xml
<CustomField>
    <fullName>MDevanWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VANNING/DEVAN WAREHOUSE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.MDevan__c</field>
            <operation>equals</operation>
            <valueField>LoadLocation__c.WharehouseCompany__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LoadLocation__c</referenceTo>
    <relationshipLabel>CONSOLIDATION (VANNING/DEVAN WAREHOUSE)</relationshipLabel>
    <relationshipName>MDevanWarehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/META__c.field-meta.xml
<CustomField>
    <fullName>META__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/METD__c.field-meta.xml
<CustomField>
    <fullName>METD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPlace_Of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>MPlace_Of_Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Delivery</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_DELIVERY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPlace_Of_Receipt__c.field-meta.xml
<CustomField>
    <fullName>MPlace_Of_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Receipt</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_RECEIPT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPOD__c.field-meta.xml
<CustomField>
    <fullName>MPOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Dispatch</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MPOL__c.field-meta.xml
<CustomField>
    <fullName>MPOL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>M_B_L_SHIPMENTS_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MTRANSIT_PORT__c.field-meta.xml
<CustomField>
    <fullName>MTRANSIT_PORT__c</fullName>
    <label>TRANSIT PORT</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MTRANSIT_T_ETD__c.field-meta.xml
<CustomField>
    <fullName>MTRANSIT_T_ETD__c</fullName>
    <label>ETD AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MTRANSIT_VESSEL__c.field-meta.xml
<CustomField>
    <fullName>MTRANSIT_VESSEL__c</fullName>
    <inlineHelpText>Enter First Vessel in case there are more than 1 vessels involved</inlineHelpText>
    <label>1ST VESSEL/FLIGHT</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MVessel__c.field-meta.xml
<CustomField>
    <fullName>MVessel__c</fullName>
    <label>MVessel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterAnken__c/fields/MVoy_No__c.field-meta.xml
<CustomField>
    <fullName>MVoy_No__c</fullName>
    <label>Voyage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <customHelpPage>OnlineHelpPorts</customHelpPage>
    <description>Port</description>
    <label>ポートコード</label>
    <nameField>
        <label>Port name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Port__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
            <value>
                <fullName>BULGARIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MasterAnkenLookupController.cls
public with sharing class MasterAnkenLookupController {
    public List<MasterAnken__c> lstMasterAnkens {get;set;}
    public String strSearchValue {get;set;}
    public String strMasterAnkenID {get;set;}
    public String strHShipmentID {get;set;}
    public String radioValue {get;set;}
    public Integer listSize {get;set;}
    private static List<String> fieldsToQuery = new List<String>();
    public Map<String, String> translations {get; private set;}
    
    static {
        fieldsToQuery.add('Id');
        fieldsToQuery.add('Name');
        fieldsToQuery.add('MPOL__r.Country_Name__c');
        fieldsToQuery.add('MPOL__r.City_Name__c');
        fieldsToQuery.add('MPOL__r.Name');
        fieldsToQuery.add('MPlace_of_Receipt__r.Name');
        fieldsToQuery.add('METD__c');
        fieldsToQuery.add('MPOD__r.Country_Name__c');
        fieldsToQuery.add('MPOD__r.City_Name__c');
        fieldsToQuery.add('MPOD__r.Name');        
        fieldsToQuery.add('MPlace_of_Delivery__r.Name');
        fieldsToQuery.add('META__c');
        fieldsToQuery.add('MVoy_No__c');
        fieldsToQuery.add('MContainer_No__c');
        fieldsToQuery.add('MDevan__r.Name');
        fieldsToQuery.add('MDevanRep__r.Name');
        fieldsToQuery.add('MDevanningDate__c');
        fieldsToQuery.add('MTRANSIT_VESSEL__c');
        fieldsToQuery.add('MTRANSIT_PORT__c');
        fieldsToQuery.add('MTRANSIT_T_ETD__c');
        fieldsToQuery.add('MDevanWarehouse__r.Name');
        fieldsToQuery.add('bondedtimetoCFS__c');
        fieldsToQuery.add('MVessel__c');
    }
    
    public MasterAnkenLookupController() {
        strHShipmentID = StringUtils.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('id'));
    	lstMasterAnkens = new List<MasterAnken__c>();            
        String soqlComm = 'SELECT ' + String.join(fieldsToQuery, ',') + ' FROM MasterAnken__c LIMIT 50';
        
        if (PermissionValidationUtil.isAccessibleAccount() && PermissionValidationUtil.isAccessiblePort() 
	            && PermissionValidationUtil.isAccessibleWarehouse() && PermissionValidationUtil.isAccessibleMBL()) {
			lstMasterAnkens = Database.query(soqlComm);                
        }
        
        listSize = lstMasterAnkens.size();
        radioValue= 'Name';
        initializeTranslation();
    }
    
    private void initializeTranslation() {
        TranslationService translationService = new TranslationService('COPY_MBL_HBL', UserInfo.getLanguage());
        translations = translationService.getTranslations();
    }
    
    public List<SelectOption> radioType {
        get {
        	List<SelectOption> lstOptions = new List<SelectOption>();
        	lstOptions.add(new SelectOption('Name','Name'));
        	lstOptions.add(new SelectOption('Allfield','All fields'));
        
        	return lstOptions;    
        }
        set;
    }
    
    public PageReference doSearch() {
        if (strSearchValue != null) {
            if (PermissionValidationUtil.isAccessibleAccount() && PermissionValidationUtil.isAccessiblePort() 
                	&& PermissionValidationUtil.isAccessibleWarehouse() && PermissionValidationUtil.isAccessibleMBL()) {
                if (radioValue != null && radioValue == 'Allfield') {
                    String soslString = 'FIND {' + StringUtils.escapeSingleQuotes(strSearchValue) 
                        + '} IN ALL FIELDS RETURNING MasterAnken__c (' + String.join(fieldsToQuery, ',') + ')'; 
                    
                    List<List<SObject>> lstSObj = Search.query(soslString);
                    lstMasterAnkens = (List<MasterAnken__c>)lstSObj[0];
                }
                else if (radioValue != null && radioValue == 'Name'){
                    String soqlComm = 'SELECT '+ String.join(fieldsToQuery, ',') 
                        + ' FROM MasterAnken__c WHERE Name LIKE \'%' + StringUtils.escapeSingleQuotes(strSearchValue) + '%\'';
                    lstMasterAnkens = Database.query(soqlComm);
                }
                listSize = lstMasterAnkens.size();
            }
        }

        return null;
    }
    
    public void copyFromMasterAnken() {
        try {
            if (strMasterAnkenID != null && strHShipmentID != null) {
                cntl_opportunityCopy.copyFieldsFromMasterAnken(StringUtils.escapeSingleQuotes(strHShipmentID), 
                                                               StringUtils.escapeSingleQuotes(strMasterAnkenID));
            }        
        }catch(Exception e) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Error occurred: ' + e.getMessage()));
        }
    }
}