force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <formula>text( Product__r.BillingType__c )</formula>
    <label>BILLING TYPE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locator for Manual Operation</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/ConnectWOProduct__c.object-meta.xml
<CustomObject>
    <label>W/O+Product</label>
    <nameField>
        <displayFormat>WP-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/W/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectWOProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/LOCATOR__c.object-meta.xml
<CustomObject>
    <label>Locator</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>LOCATOR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>LOCATOR</relationshipLabel>
    <relationshipName>Locator</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/DeliveryServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryServiceBillingFreqType__c</fullName>
    <label>Delivery Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GuaranteeServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>GuaranteeServiceBillingFreqType__c</fullName>
    <label>Guarantee Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/InstallationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>InstallationServiceBillingFreqType__c</fullName>
    <label>Installation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IF(ISBLANK(External_ID__c), Name, External_ID__c)</formula>
    <inlineHelpText>Manufacture Code will be set as default. If there is no Manufacture Code, the Product ID will be set.</inlineHelpText>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RelocationServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>RelocationServiceBillingFreqType__c</fullName>
    <label>Relocation Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ReplacementServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>ReplacementServiceBillingFreqType__c</fullName>
    <label>Replacement Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SetupServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SetupServiceBillingFreqType__c</fullName>
    <label>Setup Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SubscriptionChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionChargeBillingFreqType__c</fullName>
    <label>Subscription Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SupportServiceBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>SupportServiceBillingFreqType__c</fullName>
    <label>Support Service Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UsageChargeBillingFreqType__c.field-meta.xml
<CustomField>
    <fullName>UsageChargeBillingFreqType__c</fullName>
    <label>Usage Charge Billing Freq Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingFrequencyType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>SELLING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WO_Cargo__c/WO_Cargo__c.object-meta.xml
<CustomObject>
    <label>WO+Cargo</label>
    <nameField>
        <displayFormat>WOC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WO+Cargoes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WO_Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WO_Cargo__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/recordTypes/CombinedTransfer.recordType-meta.xml
<RecordType>
    <fullName>CombinedTransfer</fullName>
    <active>true</active>
    <description>Massive cargo transfer after combining many cargo to the same destination</description>
    <label>Combined Transfer</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/recordTypes/Inbound.recordType-meta.xml
<RecordType>
    <fullName>Inbound</fullName>
    <active>true</active>
    <description>Cargo Inbound coming into warehouse and store in warehouse</description>
    <label>Inbound</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/recordTypes/InboundReceiving.recordType-meta.xml
<RecordType>
    <fullName>InboundReceiving</fullName>
    <active>true</active>
    <description>Receiving for cargo inbound from customer</description>
    <label>Inbound Receiving</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/recordTypes/OutboundDispatch.recordType-meta.xml
<RecordType>
    <fullName>OutboundDispatch</fullName>
    <active>true</active>
    <description>Dispatch for cargo outbound to the customers</description>
    <label>Outbound Dispatch</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/recordTypes/Picking.recordType-meta.xml
<RecordType>
    <fullName>Picking</fullName>
    <active>true</active>
    <label>Picking</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/recordTypes/Putaway.recordType-meta.xml
<RecordType>
    <fullName>Putaway</fullName>
    <active>true</active>
    <label>Putaway</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/recordTypes/TransferDispatch.recordType-meta.xml
<RecordType>
    <fullName>TransferDispatch</fullName>
    <active>true</active>
    <description>Dispatch for cargo transferred to another location</description>
    <label>Transfer Dispatch</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/recordTypes/TransferReceiving.recordType-meta.xml
<RecordType>
    <fullName>TransferReceiving</fullName>
    <active>true</active>
    <description>Receiving for cargo transferred from another location</description>
    <label>Transfer Receiving</label>
</RecordType>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipName>WOSLineItemID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Worker__c.field-meta.xml
<CustomField>
    <fullName>Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WORKER</label>
    <referenceTo>WORKER__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/BillingFrequencyType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Time Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>3 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>4 Times Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Ad-Hoc</fullName>
    </customValue>
    <customValue>
        <fullName>No Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Times Billing</fullName>
        <isActive>false</isActive>
        <label>Multi-Times Billing</label>
    </customValue>
    <masterLabel>Billing Frequency Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WeightUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>WEIGHT UNIT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WMS_QrServiceTest.cls
@isTest
private class WMS_QrServiceTest {
	static Account acc;
	static Worker__c wk;
	static Facility__c fac;
	static Facility__c fac1;
	static Locator__c lo;
	static Locator__c lo1;
	static PRODUCT__c prod;
	static Cargo__c cargo;
	static WorkOrder__c wo;
	static WorkOrder__c wo1;
	static WorkOrderService__c wos_InboundReceiving;
	static WorkOrderService__c wos_Putaway;
	static WorkOrderService__c wos_Picking;
	static WorkOrderService__c wos_Dispatch;
	static WorkOrderService__c wos_TransferDispatch;
	static WorkOrderService__c wos_CombinedDispatch;
	static WorkOrderService__c wos_TransferReceiving;
	static WorkOrderService__c wos_CombinedReceiving;
	static WMS_QrService.ProcessCargoRequest req = new WMS_QrService.ProcessCargoRequest();

	static void queryTestData() {
		acc = [SELECT Id FROM Account LIMIT 1];
		prod = [SELECT Id, Name, QR_Code__c FROM Product__c LIMIT 1];
		cargo = [SELECT Id, Name FROM Cargo__c LIMIT 1];
		wk = [SELECT Id FROM Worker__c LIMIT 1];
		fac = [SELECT Id FROM Facility__c WHERE FacilityName__c = 'Fac' LIMIT 1];
		fac1 = [SELECT Id FROM Facility__c WHERE FacilityName__c = 'Fac1' LIMIT 1];
		lo = [SELECT Id FROM Locator__c WHERE WarehouseID__c = :fac.Id LIMIT 1];
		lo1 = [SELECT Id FROM Locator__c WHERE WarehouseID__c = :fac1.Id LIMIT 1];
		wo = [SELECT Id FROM WorkOrder__c WHERE RecordType.DeveloperName = 'Inbound' LIMIT 1];
		wo1 = [SELECT Id FROM WorkOrder__c WHERE RecordType.DeveloperName = 'CombinedTransfer' LIMIT 1];
		wos_InboundReceiving = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'InboundReceiving' LIMIT 1];
		wos_Putaway = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'Putaway' LIMIT 1];
		wos_Picking = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'Picking' LIMIT 1];
		wos_Dispatch = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'OutboundDispatch' LIMIT 1];
		wos_TransferDispatch = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'TransferDispatch' AND WorkOrder__c = :wo.Id LIMIT 1];
		wos_TransferReceiving = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'TransferReceiving' AND WorkOrder__c = :wo.Id LIMIT 1];
		wos_CombinedDispatch = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'TransferDispatch' AND WorkOrder__c = :wo1.Id LIMIT 1];
		wos_CombinedReceiving = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'TransferReceiving' AND WorkOrder__c = :wo1.Id LIMIT 1];

		req = new WMS_QrService.ProcessCargoRequest();
		req.CargoId = cargo.Id;
		req.WorkerId = wk.Id;
		req.LocatorId = lo.Id;
		req.LotNumber = 'test';
		req.ProcessServiceIds = new List<Id>();
		req.AddToServiceIds = new List<Id>();
	}

    @TestSetUp static void testSetup(){
		prod = new Product__c(WeightUnit__c = 'g', BillingType__c = 'Weight', GuaranteeServiceBillingFreqType__c = 'Continuous Billing',DeliveryServiceBillingFreqType__c = 'Continuous Billing', 
                                 InstallationServiceBillingFreqType__c = 'Continuous Billing',SetupServiceBillingFreqType__c = 'Continuous Billing',
                                 RelocationServiceBillingFreqType__c = 'Continuous Billing',ReplacementServiceBillingFreqType__c = 'Continuous Billing',
                                 SupportServiceBillingFreqType__c = 'Continuous Billing',SubscriptionChargeBillingFreqType__c = 'Continuous Billing',
                                 UsageChargeBillingFreqType__c = 'Continuous Billing',MaintenanceServiceBillingFreqType__c = 'Continuous Billing' );
        acc = new Account(name = 'testAcc', EnglishCompanyName__c = 'test');
        wk = new Worker__c();
        fac = new Facility__c(FacilityName__c = 'Fac');
        fac1 = new Facility__c(FacilityName__c = 'Fac1');

		FlsService.doInsert(new List<SObject> { prod, acc, wk, fac, fac1});

        lo = new Locator__c(WarehouseID__c = fac.Id, LocatorLayer__c = 'Floor Layer', LocationAreaType__c = 'Floor', FloorCode__c = 'F01', AreaCode__c = 'A', SectionCode__c = 'S', Rack__c = 'R', Level__C = 'L');
        lo1 = new Locator__c(WarehouseID__c = fac1.Id, LocatorLayer__c = 'Floor Layer', LocationAreaType__c = 'Floor', FloorCode__c = 'F01', AreaCode__c = 'A', SectionCode__c = 'S', Rack__c = 'R', Level__C = 'L');
        wo = new WorkOrder__c(Customer__c = acc.id, WarehouseID__c = fac.id, RecordTypeId = Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByDeveloperName().get('Inbound').getRecordTypeId());
        wo1 = new WorkOrder__c(Customer__c = acc.id, WarehouseID__c = fac1.id, RecordTypeId = Schema.SObjectType.WorkOrder__c.getRecordTypeInfosByDeveloperName().get('CombinedTransfer').getRecordTypeId());

		FlsService.doInsert(new List<SObject> { lo, lo1, wo, wo1});

		wos_InboundReceiving = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac.Id, Locator__c = lo.Id, WorkOrder__c = wo.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('InboundReceiving').getRecordTypeId());
		wos_Putaway = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac.Id, Locator__c = lo.Id, WorkOrder__c = wo.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('Putaway').getRecordTypeId());
		wos_Picking = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac.Id, Locator__c = lo.Id, WorkOrder__c = wo.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('Picking').getRecordTypeId());
		wos_Dispatch = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac.Id, Locator__c = lo.Id, WorkOrder__c = wo.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('OutboundDispatch').getRecordTypeId());
		wos_TransferDispatch = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac.Id, Locator__c = lo.Id, DestinationWarehouse__c = fac1.Id, CombinedWorkOrder__c = wo1.Id, WorkOrder__c = wo.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('TransferDispatch').getRecordTypeId());
		wos_TransferReceiving = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac1.Id, Locator__c = lo1.Id, CombinedWorkOrder__c = wo1.Id, WorkOrder__c = wo.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('TransferReceiving').getRecordTypeId());
		wos_CombinedDispatch = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac.Id, Locator__c = lo.Id, WorkOrder__c = wo1.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('TransferDispatch').getRecordTypeId());
		wos_CombinedReceiving = new WorkOrderService__c(Status__c = 'Resource Assigned', Warehouse__c = fac1.Id, Locator__c = lo.Id, WorkOrder__c = wo1.Id, RecordTypeId = Schema.SObjectType.WorkOrderService__c.getRecordTypeInfosByDeveloperName().get('TransferReceiving').getRecordTypeId());
        cargo = new Cargo__c (Product__c = prod.Id, PlannedWeight__c = 1000);

		FlsService.doInsert(new List<SObject> { cargo, wos_InboundReceiving, wos_Putaway, wos_Picking, wos_Dispatch, wos_TransferDispatch, wos_TransferReceiving, wos_CombinedDispatch, wos_CombinedReceiving });
    }

	@isTest static void test_getRelatedServices() {
		Test.startTest();
		queryTestData();
		System.assertEquals(5, ((List<WorkOrderService__c>)WMS_QrService.getRelatedServices(wos_InboundReceiving.Id)).size());
		Test.stopTest();
	}
     
	@isTest static void test_getTasks() {
		test.startTest();
		// Implement test code
		List<WorkOrderService__c> lsWOS = (List<WorkOrderService__c>)WMS_QrService.getTasks(null, null);
		System.assertEquals(lsWOS.size(), 0);
		test.stopTest();
	}

	@isTest static void test_startTask() {
		queryTestData();
        Test.startTest();
        try {
            WMS_QrService.startTask(null); 
        }
        catch (Exception ex) {
        }
        try {
            WMS_QrService.finalizeTask(null, null);
        }
        catch (Exception ex) {
        }
        WorkOrderService__c WOS = [SELECT Id, Name, Status__c, ScheduledStartTime__c, ActualStartTime__c,
                                   				ActualEndTime__c, RecordType.DeveloperName
        										FROM WorkOrderService__c LIMIT 1];
        WMS_QrService.startTask(WOS.id);

        WMS_QrService.startTaskV2(WOS.id);
        WOS = [SELECT Id, Name, Status__c, ScheduledStartTime__c, ActualStartTime__c,
                                   				ActualEndTime__c, RecordType.DeveloperName
        										FROM WorkOrderService__c
        										WHERE Id = :WOS.id];
        System.assertEquals(WOS.Status__c , 'On Progress');

        WMS_QrService.finalizeTask(wos_InboundReceiving.id, new List<Id> { wos_Putaway.Id });
        WMS_QrService.finalizeTask(wos_CombinedDispatch.id, null);
		WMS_QrService.finalizeTask(wos_CombinedReceiving.id, null);
		system.assert(WOS != null);
        Test.stopTest();
	}

    @IsTest static void testUpdate(){
		Test.startTest();
        account acc = [select id from account limit 1];
        WMS_QrService.updateRecord(acc);

        try{
            WMS_QrService.updateRecord(new Account());
        }catch(exception ex){
		}
		system.assert(acc != null);
        Test.stopTest();
    }

    @IsTest static void testGetWeightBasedCargoes(){
		queryTestData();
        
		FlsService.doInsert(new List<WosLineItem__c> {
			new WosLineItem__c (WorkOrderService__c = wos_InboundReceiving.Id, Cargo__c = cargo.Id)
		});

        Test.startTest(); 
		Map<Decimal, List<Id>> temp = WMS_QrService.getWeightBasedCargoes(wos_InboundReceiving.Id, prod.Id, lo.Id);
		System.assertEquals(true, temp.containsKey(1000.0));
		System.assertEquals(1, temp.get(1000.0).size());
        Test.stopTest();
    }

    @IsTest static void testProcessCargo_cargoNotLinked(){
		queryTestData();
        
        Test.startTest(); 
		req.ServiceId = wos_InboundReceiving.Id;
        //test cargo not linked
        try {
            WMS_QrService.processCargo_internal(req);
        }
		catch (Exception ex) {}
		System.assert(req.ServiceId != null);
        Test.stopTest();
    }

    @IsTest static void testProcessCargo_receive(){
		queryTestData();
        Test.startTest();
		req.ServiceId = wos_InboundReceiving.Id;
        req.LotNumber = 'test';
		req.ProcessServiceIds = new List<Id> { wos_Putaway.Id };
		FlsService.doInsert(new List<WosLineItem__c> {
			new WosLineItem__c (WorkOrderService__c = wos_InboundReceiving.Id, Cargo__c = cargo.Id),
			new WosLineItem__c (WorkOrderService__c = wos_Putaway.Id, Cargo__c = cargo.Id)
		}); 
        try{
			WMS_QrService.processCargo_internal(req);
        }catch(exception ex){
		}
        Test.stopTest();

		//the above 2 WOS line items should be marked as scanned
		System.assertEquals(1, [SELECT COUNT() FROM WosLineItem__c WHERE IsCargoScanned__c = true]);
    }
	
    @IsTest static void testProcessCargo_receive_productQrScan(){
		queryTestData();
        Test.startTest();
		req.ServiceId = wos_InboundReceiving.Id;
		req.ProductId = prod.Id;
		req.ProductQuantity = 1;
		req.PlannedWeight = 1000;
        req.LotNumber = 'test';
		req.ProcessServiceIds = new List<Id> { wos_Putaway.Id };
		FlsService.doInsert(new List<WosLineItem__c> {
			new WosLineItem__c (WorkOrderService__c = wos_InboundReceiving.Id, Cargo__c = cargo.Id),
			new WosLineItem__c (WorkOrderService__c = wos_Putaway.Id, Cargo__c = cargo.Id)
		}); 
        try{
			WMS_QrService.processCargo_internal(req);
        }catch(exception ex){
		}
        Test.stopTest();

		//the above 2 WOS line items should be marked as scanned
		System.assertEquals(1, [SELECT COUNT() FROM WosLineItem__c WHERE IsCargoScanned__c = true]);
    }
	
	
    @IsTest static void testProcessCargo_receive_productQrScan_notEnoughQty(){
		Test.startTest();
		queryTestData();
		req.ServiceId = wos_InboundReceiving.Id;
		req.ProductId = prod.Id;
		req.ProductQuantity = 2;
		try{
			WMS_QrService.processCargo_internal(req);
        }catch(exception ex){
		}
		system.assert( req.ServiceId != null);
		Test.stopTest();
	}
	
    @IsTest static void testProcessCargo_combinedDispatch(){
		queryTestData();
        Test.startTest();
		req.ServiceId = wos_CombinedDispatch.Id;
        req.LotNumber = 'test';
		req.ProcessServiceIds = new List<Id> { wos_CombinedReceiving.Id };
		FlsService.doInsert(new List<WosLineItem__c> {
			new WosLineItem__c (WorkOrderService__c = wos_CombinedDispatch.Id, Cargo__c = cargo.Id),
			new WosLineItem__c (WorkOrderService__c = wos_CombinedReceiving.Id, Cargo__c = cargo.Id),
			new WosLineItem__c (WorkOrderService__c = wos_TransferDispatch.Id, Cargo__c = cargo.Id),
			new WosLineItem__c (WorkOrderService__c = wos_TransferReceiving.Id, Cargo__c = cargo.Id)
		}); 
		try{
			WMS_QrService.processCargo_internal(req);
        }catch(exception ex){
		}
        Test.stopTest();

		//source dispatch line and receiving line should be marked as completed also
		System.assertEquals(3, [SELECT COUNT() FROM WosLineItem__c WHERE IsCargoScanned__c = true]);
    }
	
    @IsTest static void testProcessCargo_combinedReceiving(){
		queryTestData();
        Test.startTest();
		req.ServiceId = wos_CombinedReceiving.Id;
		FlsService.doInsert(new List<WosLineItem__c> {
			new WosLineItem__c (WorkOrderService__c = wos_CombinedReceiving.Id, Cargo__c = cargo.Id),
			new WosLineItem__c (WorkOrderService__c = wos_TransferReceiving.Id, Cargo__c = cargo.Id)
		}); 
        WMS_QrService.processCargo_internal(req);
        Test.stopTest();

		//source receiving line should be marked as completed also
		System.assertEquals(2, [SELECT COUNT() FROM WosLineItem__c WHERE IsCargoScanned__c = true]);
    }
	@isTest static void test_getWosRecordTypes() {
		test.startTest();
		// Implement test code
		List<Map<String,String>> lsMap = (List<Map<String,String>>)WMS_QrService.getWosRecordTypes(null, null);
		System.assertEquals(lsMap.size(), 7);
		test.stopTest();
	}
	// @isTest static void test_processCargo() {
		// test.startTest();
		// List<WosLineItem__c> lsWLI = (List<WosLineItem__c>)WMS_QrService.processCargo(wos_Picking.Id, cargo.Id,prod.Id,0,0,0,'Completed',wk.Id,null,null,null,null);
		// System.assertEquals(lsWLI.size(), 0);
		// test.stopTest();
	// }
	@isTest static void test_getWoProductsByWosId() {
		test.startTest();
		// Implement test code
		List<ConnectWOProduct__c> lsCWP = (List<ConnectWOProduct__c>)WMS_QrService.getWoProductsByWosId(null);
		System.assertEquals(lsCWP.size(), 0);
		test.stopTest();
	}
	@isTest static void test_getWoCargoesByWosId() {
		test.startTest();
		// Implement test code
		List<WO_Cargo__c> lsWC = (List<WO_Cargo__c>)WMS_QrService.getWoCargoesByWosId(null);
		System.assertEquals(lsWC.size(), 0);
		test.stopTest();
	}
	@isTest static void test_createWoProductAndcreateCargo() {
		test.startTest();
		WorkOrderService__c wos = [SELECT Id FROM WorkOrderService__c LIMIT 1];
		PRODUCT__c pro = [SELECT Id FROM PRODUCT__c LIMIT 1];
		// Implement test code
		ConnectWOProduct__c CWP = (ConnectWOProduct__c)WMS_QrService.createWoProduct(wos.Id,pro.Id);
		WO_Cargo__c lstWOC = (WO_Cargo__c)WMS_QrService.createCargo(wos.Id,pro.Id);
		test.stopTest();
	}
	// @isTest static void test_getCargoDetails() {
		// test.startTest();
		// WorkOrderService__c wos = [SELECT Id FROM WorkOrderService__c WHERE RecordType.DeveloperName = 'InboundReceiving' LIMIT 1];
		// Cargo__c car = [SELECT Id FROM Cargo__c LIMIT 1];
		// List<Cargo__c> lsCWP = (List<Cargo__c>)WMS_QrService.getCargoDetails(wos.Id,car.Id);
		// System.assertEquals(lsCWP.size(), 0);
		// test.stopTest();
	// }
	// @isTest static void test_processCargoV2() {
		// test.startTest();
		// Cargo__c car = [SELECT Id FROM Cargo__c LIMIT 1];
		// WosLineItem__c wli = new WosLineItem__c(WorkOrderService__c = wos_Picking.Id, Cargo__c = car.Id);
		// insert wli;
		// List<Id> lstId = new List<Id>();
		// for (WorkOrderService__c wos : [SELECT Id FROM WorkOrderService__c LIMIT 10]){
			// lstId.add(wos.Id);
		// }
		// WMS_QrService.processCargoV2(car,wli,lstId);
		// test.stopTest();
	// }
}