force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddress__c</fullName>
    <label>Delivery Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DeliveryAddressNew__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddressNew__c</fullName>
    <label>DELIVERY ADDRESS</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CargoTriggerHandler.cls
public with sharing class CargoTriggerHandler {
    public static void autoPopulateFields(List<Cargo__c> listNew, Map<Id, Cargo__c> mapOld) {
        for(Cargo__c item : listNew) {
            //sync address
            if (!String.isBlank(item.DeliveryAddressNew__c)) {
                item.DeliveryAddress__c = item.DeliveryAddressNew__c;
            } else if (!String.isBlank(item.DeliveryAddress__c)) {
                item.DeliveryAddressNew__c = item.DeliveryAddress__c.left(255);
            }
        }
    }
}