force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locator for Manual Operation</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ImplementStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOCATOR__c/LOCATOR__c.object-meta.xml
<CustomObject>
    <label>Locator</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>LOCATOR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/fields/FloorCode__c.field-meta.xml
<CustomField>
    <fullName>FloorCode__c</fullName>
    <defaultValue>&quot;F&quot;</defaultValue>
    <label>FLOOR CODE</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>LOCATOR</relationshipLabel>
    <relationshipName>Locator</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/Locator__c.field-meta.xml
<CustomField>
    <fullName>Locator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WorkStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ImplementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Planning</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Under Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>In Operation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Sold</fullName>
    </customValue>
    <customValue>
        <fullName>Disposed</fullName>
    </customValue>
    <customValue>
        <fullName>Decommissioned</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>IMPLEMENTATION STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WorkStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Resource Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Accept Cargo Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>On Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Data Transfer To Next Process</fullName>
        <isActive>false</isActive>
        <label>Data Transfer To Next Process</label>
    </customValue>
    <masterLabel>WORK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderServiceTriggerHelperTest.cls
@isTest
private class WorkOrderServiceTriggerHelperTest {
	
	@isTest static void test_method_one() {
		Test.startTest();
		Cargo__c car = new Cargo__c();
		insert car;
		Facility__c ware = new Facility__c();
		insert ware;
		Locator__c loc = new Locator__c(WarehouseID__c = ware.Id,FloorCode__c='F321');
		insert loc;
		Locator__c loc2 = new Locator__c(WarehouseID__c = ware.Id,FloorCode__c='F323');
		insert loc2;
		WorkOrderService__c workOrderService = new WorkOrderService__c(Locator__c = loc.Id, Status__c = 'Completed', RecordTypeId = '0120K000000ygE3QAI');
        FlsService.doInsert(workOrderService);
		workOrderService.Locator__c = loc2.Id;
		update workOrderService;
		system.assert(workOrderService != null);
		WorkOrderService__c workOrderService2 = new WorkOrderService__c(Locator__c = loc.Id, RecordTypeId = '0120K000000ygE3QAI');
		FlsService.doInsert(workOrderService2);
		workOrderService2.Locator__c = loc2.Id;
		workOrderService2.Status__c = 'Completed';
		update workOrderService2;
		system.assert(workOrderService2 != null);
		clofor_com_cfs__WOSLineItem__c wosline = new clofor_com_cfs__WOSLineItem__c (WorkOrderService__c = workOrderService2.Id, CargoStatus__c = 'Completed',clofor_com_cfs__Cargo__c = car.Id);
		insert wosline;
		Test.stopTest();
	}
}