force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>LastWosLineItem__r.WorkOrderID__r.Customer__r.Name</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Warehouse</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>CARGO (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>CargoDestinationWarehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ImplementStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>WorkOrderDestinationWarehouseID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/recordTypes/CombinedTransfer.recordType-meta.xml
<RecordType>
    <fullName>CombinedTransfer</fullName>
    <active>true</active>
    <description>Massive cargo transfer after combining many cargo to the same destination</description>
    <label>Combined Transfer</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARRIER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/CombinedWorkOrder__c.field-meta.xml
<CustomField>
    <fullName>CombinedWorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Combined Work Order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S (Combined Work Order)</relationshipLabel>
    <relationshipName>CombinedWos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-DESTINATION</relationshipLabel>
    <relationshipName>WorkOrderServiceDestination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/ServiceStage__c.field-meta.xml
<CustomField>
    <fullName>ServiceStage__c</fullName>
    <description>Unique key within a process, used to identify the service in a process</description>
    <inlineHelpText>Unique key within a process, used to identify the service in a process</inlineHelpText>
    <label>Service Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WorkStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASRequirement__c.field-meta.xml
<CustomField>
    <fullName>VASRequirement__c</fullName>
    <label>VAS REQUIREMENT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASServiceType__c.field-meta.xml
<CustomField>
    <fullName>VASServiceType__c</fullName>
    <label>VAS SERVICE TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueAddedServiceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/CargoStatus__c.field-meta.xml
<CustomField>
    <fullName>CargoStatus__c</fullName>
    <label>Cargo Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
                <isActive>false</isActive>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>WorkOrderService__r.WorkOrder__r.Customer__c</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/VASServiceType__c.field-meta.xml
<CustomField>
    <fullName>VASServiceType__c</fullName>
    <formula>IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Quality Check&quot; ), &quot;Quality Check; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Quality Assurance&quot; ), &quot;Quality Assurance; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Split Cargo&quot; ), &quot;Split Cargo; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Packing/Packaging&quot; ), &quot;Packing/Packaging; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Labelling&quot; ), &quot;Labelling; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Sorting&quot; ), &quot;Sorting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Measuring&quot; ), &quot;Measuring; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Marking&quot; ), &quot;Marking; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Repairing&quot; ), &quot;Repairing; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Consol&quot; ), &quot;Consol; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;De-Consol&quot; ), &quot;De-Consol; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Fumigation&quot; ), &quot;Fumigation; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Kitting&quot; ), &quot;Kitting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;	Assembling&quot; ), &quot;Assembling; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Sampling&quot; ), &quot;Sampling; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Testing&quot; ), &quot;Testing; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Inspection&quot; ), &quot;Inspection; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Physical Counting&quot; ), &quot;Physical Counting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Cyclic Counting&quot; ), &quot;Cyclic Counting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Elimination of Losts From Stock&quot; ), &quot;Elimination of Losts From Stock; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Inventory Updates&quot; ), &quot;Inventory Updates; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Disposal&quot; ), &quot;Disposal; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Damage Root-cause Analysis&quot; ), &quot;Damage Root-cause Analysis; &quot;,null )</formula>
    <label>VAS Service Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WOSLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/ImplementStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Planning</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Under Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>In Operation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Sold</fullName>
    </customValue>
    <customValue>
        <fullName>Disposed</fullName>
    </customValue>
    <customValue>
        <fullName>Decommissioned</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>IMPLEMENTATION STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ValueAddedServiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Quality Check</fullName>
        <default>true</default>
        <label>Quality Check</label>
    </customValue>
    <customValue>
        <fullName>Quality Assurance</fullName>
    </customValue>
    <customValue>
        <fullName>Damage Root-cause Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>Labelling</fullName>
    </customValue>
    <customValue>
        <fullName>Sorting</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Split Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Packing/Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Measuring</fullName>
    </customValue>
    <customValue>
        <fullName>Marking</fullName>
    </customValue>
    <customValue>
        <fullName>Repairing</fullName>
    </customValue>
    <customValue>
        <fullName>Consol</fullName>
    </customValue>
    <customValue>
        <fullName>De-Consol</fullName>
    </customValue>
    <customValue>
        <fullName>Fumigation</fullName>
    </customValue>
    <customValue>
        <fullName>Kitting</fullName>
    </customValue>
    <customValue>
        <fullName>Assembling</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Physical Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Cyclic Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Elimination of Losts From Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Updates</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Reconditioning</fullName>
        <isActive>false</isActive>
        <label>Reconditioning</label>
    </customValue>
    <customValue>
        <fullName>Accumulating</fullName>
        <isActive>false</isActive>
        <label>Accumulating</label>
    </customValue>
    <masterLabel>VALUE ADDED SERVICE TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WorkStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Resource Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Accept Cargo Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>On Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Data Transfer To Next Process</fullName>
        <isActive>false</isActive>
        <label>Data Transfer To Next Process</label>
    </customValue>
    <masterLabel>WORK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WMS_WO_CombineService.cls
public with sharing class WMS_WO_CombineService {
	@AuraEnabled
	public static Object getInfo(String recordId, String warehouseId) {//only 1 of recordId or warehouseId can have value, if both provided, warehouseId is ignored
		try{
			Map<String, Object> response = new Map<String, Object>();
			String destinationId = null;
			if (!String.isBlank(recordId)) {
				WorkOrder__c wo = [
					SELECT
						RecordType.Name, RecordType.DeveloperName,
						WarehouseID__c, WarehouseID__r.Name, WarehouseID__r.FacilityName__c,
						DestinationWarehouse__c, DestinationWarehouse__r.Name, DestinationWarehouse__r.FacilityName__c,
						(
							SELECT Id, VASServiceType__c, VASRequirement__c, ServiceStage__c, RecordTypeId,
								Warehouse__c, Warehouse__r.Name, Warehouse__r.FacilityName__c,
								DestinationWarehouse__c, DestinationWarehouse__r.Name, DestinationWarehouse__r.FacilityName__c
							FROM WorkOrderService__r
						),
						(
							SELECT Id
							FROM CombinedWos__r
						)
					FROM WorkOrder__c
					WHERE Id = :recordId
				];
				response.put('workOrder', wo);
				warehouseId = wo.WarehouseID__c;
				destinationId = wo.DestinationWarehouse__c;
			}

			response.put('recordTypeId', Schema.sObjectType.WorkOrder__c.getRecordTypeInfosByDeveloperName().get('CombinedTransfer').getRecordTypeId());
			response.put('listServices', database.query(
				' SELECT Id, ' +
				' 	Warehouse__c, ' +
				'	DestinationWarehouse__c, DestinationWarehouse__r.Name, DestinationWarehouse__r.FacilityName__c, ' +
				'	WorkOrder__c, WorkOrder__r.RecordType.Name, WorkOrder__r.Customer__c, WorkOrder__r.Customer__r.Name, WorkOrder__r.Name, ' +
				'	CombinedWorkOrder__c ' +
				'FROM WorkOrderService__c ' +
				'WHERE Status__c IN (\'Created\',\'Planned\',\'Scheduled\') ' +
				'	AND Warehouse__c = :warehouseId ' +
				//(String.isBlank(recordId) ? ' AND CombinedWorkOrder__c = null ' : ' AND CombinedWorkOrder__c = :recordId') +
				(String.isBlank(destinationId) ? ' AND DestinationWarehouse__c != null ' : ' AND DestinationWarehouse__c = :destinationId') +
				'	AND WorkOrder__c != null ' +
				'	AND WorkOrder__r.RecordType.DeveloperName != \'CombinedTransfer\''
			));

			return response;
		}
		catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage() + ' - ' + ex.getStackTraceString());
		}
	}

	@AuraEnabled
	public static void combineService(String recordId, List<String> payload) {
		WorkOrder__c wo = [
			SELECT (
				SELECT Id
				FROM WorkOrderService__r
			)
			FROM WorkOrder__c
			WHERE Id = :recordId
		];

		List<WorkOrderService__c> listWos = [
			SELECT (
				SELECT Cargo__c
				FROM WosLineItem__r
			)
			FROM WorkOrderService__c
			WHERE Id IN :payload
		];

		for (WorkOrderService__c item: listWos) {
			item.CombinedWorkOrder__c = recordId;
		}
		FlsService.doUpdate(listWos);

		List<WosLineItem__c> listWosLineItems = new List<WosLineItem__c>();
		for (WorkOrderService__c targetWos : wo.WorkOrderService__r) {
			for (WorkOrderService__c sourceWos : listWos) {
				for (WosLineItem__c wosLi : sourceWos.WosLineItem__r) {
					listWosLineItems.add(new WosLineItem__c(
						Cargo__c = wosLi.Cargo__c,
						WorkOrderService__c = targetWos.Id,
						CargoStatus__c = 'Planned'
					));
				}
			}
		}

		FlsService.doInsert(listWosLineItems);
	}
}