force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WorkStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/CargoStatus__c.field-meta.xml
<CustomField>
    <fullName>CargoStatus__c</fullName>
    <label>Cargo Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
                <isActive>false</isActive>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/WorkStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Resource Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>Accept Cargo Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>On Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Data Transfer To Next Process</fullName>
        <isActive>false</isActive>
        <label>Data Transfer To Next Process</label>
    </customValue>
    <masterLabel>WORK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WOServiceInputController.cls
public class WOServiceInputController {

    @AuraEnabled
    public static String loadWOService(String recId){
        String output = '';
        //WorkOrder__c wo = [select id, name, recordType.Name from WorkOrder__c where id = :recId];
        list<WorkOrderService__c> lstService = getListWorkOrderService(recId);
        for(WorkOrderService__c wos : lstService){
            output = ','+wos.id;
        }
        output = output.replaceFirst(',', '');
        //output = wo.recordType.name +'_'+output;
        return output;
    }

    @AuraEnabled
    public static String createCargo(String jsonStr, String recId){
        
        
        List<CargoWrapper> listCargoWrp = new List<CargoWrapper>();
       	listCargoWrp = (List<CargoWrapper>)JSON.deserialize(jsonStr, List<CargoWrapper>.class);
        List<Cargo__c> listCargo = CargoWrpToCargo(listCargoWrp);
        try{
            FlsService.doUpsert(listCargo);

            //Matching Service to Cargo
            List<WOSLineItem__c> lstWOSLineItem = new List<WOSLineItem__c>();
            integer cargoIdx = 0;
            for(integer j = 0; j < listCargoWrp.size(); j++){
                CargoWrapper cw = listCargoWrp[j];
                for(integer i = 0; i < cw.quantity; i++){
                    WOSLineItem__c WOSli = new WOSLineItem__c();
                    WOSli.WorkOrderService__c = cw.serviceIds;
                    WOSli.Cargo__c = listCargo[cargoIdx].id;
                    WOSli.CargoStatus__c = 'Planned';
                    lstWOSLineItem.add(WOSli);
                    cargoIdx++;
                }            
            }

            FlsService.doInsert(lstWOSLineItem);
        } catch(exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
        return 'success';
        //return JSON.serialize(listCargoOutput);
    }

    public static List<Cargo__c> CargoWrpToCargo(List<CargoWrapper> listCargoWrp){
        List<Cargo__c> listCargo = new List<Cargo__c>();
        for(integer j = 0; j < listCargoWrp.size(); j++){
            CargoWrapper cw = listCargoWrp[j];
            for(integer i = 0; i < cw.quantity; i++){
                Cargo__c c = new Cargo__c();
            	c.Product__c = cw.productId;
                listCargo.add(c);
            }            
        }
        return listCargo;
    }
    
    public static list<WorkOrderService__c> getListWorkOrderService(String recId){
        return [Select id, name, Status__c from WorkOrderService__c where WorkOrder__c = :recId];
    }
    
    public class CargoWrapper{
        public String cargoId{get;set;}
        public String productId{get;set;}
        public integer quantity{get;set;}
        public String serviceIds{get;set;}
    }

    public class ServiceWrapper{
        public String serviceIds{get;set;}
    }
}