force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Cargo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Warehouse</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>CARGO (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>CargoDestinationWarehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <deprecated>true</deprecated>
    <description>Quantity of product inside the cargo</description>
    <inlineHelpText>Quantity of product inside the cargo</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/ConnectWOProduct__c.object-meta.xml
<CustomObject>
    <label>W/O+Product</label>
    <nameField>
        <displayFormat>WP-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/W/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectWOProduct__c/fields/NETWeightKG__c.field-meta.xml
<CustomField>
    <fullName>NETWeightKG__c</fullName>
    <label>NET WEIGHT(KG)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>W/O+PRODUCT</relationshipLabel>
    <relationshipName>CONNECT_WORK_ORDER_PRODUCT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/ShippingTypeAtWarehouse__c.field-meta.xml
<CustomField>
    <fullName>ShippingTypeAtWarehouse__c</fullName>
    <label>SHIPPING TYPE AT WAREHOUSE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/ShippingTypeAtWarehouse__c.field-meta.xml
<CustomField>
    <fullName>ShippingTypeAtWarehouse__c</fullName>
    <label>SHIPPING TYPE AT WAREHOUSE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>WorkOrderDestinationWarehouseID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WorkOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-DESTINATION</relationshipLabel>
    <relationshipName>WorkOrderServiceDestination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/ServiceStage__c.field-meta.xml
<CustomField>
    <fullName>ServiceStage__c</fullName>
    <description>Unique key within a process, used to identify the service in a process</description>
    <inlineHelpText>Unique key within a process, used to identify the service in a process</inlineHelpText>
    <label>Service Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASRequirement__c.field-meta.xml
<CustomField>
    <fullName>VASRequirement__c</fullName>
    <label>VAS REQUIREMENT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASServiceType__c.field-meta.xml
<CustomField>
    <fullName>VASServiceType__c</fullName>
    <label>VAS SERVICE TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueAddedServiceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Cargo__r.Product__c ,  Cargo__r.Product__r.Name  , &apos;_top&apos;)</formula>
    <label>PRODUCT ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/VASServiceType__c.field-meta.xml
<CustomField>
    <fullName>VASServiceType__c</fullName>
    <formula>IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Quality Check&quot; ), &quot;Quality Check; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Quality Assurance&quot; ), &quot;Quality Assurance; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Split Cargo&quot; ), &quot;Split Cargo; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Packing/Packaging&quot; ), &quot;Packing/Packaging; &quot;,null ) &amp; 
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Labelling&quot; ), &quot;Labelling; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Sorting&quot; ), &quot;Sorting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Measuring&quot; ), &quot;Measuring; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Marking&quot; ), &quot;Marking; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Repairing&quot; ), &quot;Repairing; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Consol&quot; ), &quot;Consol; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;De-Consol&quot; ), &quot;De-Consol; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Fumigation&quot; ), &quot;Fumigation; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Kitting&quot; ), &quot;Kitting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;	Assembling&quot; ), &quot;Assembling; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Sampling&quot; ), &quot;Sampling; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Testing&quot; ), &quot;Testing; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Inspection&quot; ), &quot;Inspection; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Physical Counting&quot; ), &quot;Physical Counting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Cyclic Counting&quot; ), &quot;Cyclic Counting; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Elimination of Losts From Stock&quot; ), &quot;Elimination of Losts From Stock; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Inventory Updates&quot; ), &quot;Inventory Updates; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Disposal&quot; ), &quot;Disposal; &quot;,null )&amp;
IF ( INCLUDES ( WorkOrderService__r.VASServiceType__c  , &quot;Damage Root-cause Analysis&quot; ), &quot;Damage Root-cause Analysis; &quot;,null )</formula>
    <label>VAS Service Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/L</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bale</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liquid</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, fineparticles(powders）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, granular particles(grains）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, large particles(nodules）</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Cage</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,non-protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Cask</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>Chest</fullName>
    </customValue>
    <customValue>
        <fullName>Coil</fullName>
    </customValue>
    <masterLabel>CARGO TYPE(UNIT)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/ValueAddedServiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Quality Check</fullName>
        <default>true</default>
        <label>Quality Check</label>
    </customValue>
    <customValue>
        <fullName>Quality Assurance</fullName>
    </customValue>
    <customValue>
        <fullName>Damage Root-cause Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>Labelling</fullName>
    </customValue>
    <customValue>
        <fullName>Sorting</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Split Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Packing/Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Measuring</fullName>
    </customValue>
    <customValue>
        <fullName>Marking</fullName>
    </customValue>
    <customValue>
        <fullName>Repairing</fullName>
    </customValue>
    <customValue>
        <fullName>Consol</fullName>
    </customValue>
    <customValue>
        <fullName>De-Consol</fullName>
    </customValue>
    <customValue>
        <fullName>Fumigation</fullName>
    </customValue>
    <customValue>
        <fullName>Kitting</fullName>
    </customValue>
    <customValue>
        <fullName>Assembling</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Physical Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Cyclic Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Elimination of Losts From Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Updates</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Reconditioning</fullName>
        <isActive>false</isActive>
        <label>Reconditioning</label>
    </customValue>
    <customValue>
        <fullName>Accumulating</fullName>
        <isActive>false</isActive>
        <label>Accumulating</label>
    </customValue>
    <masterLabel>VALUE ADDED SERVICE TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WMS_WO_CreateCargo.cls
public with sharing class WMS_WO_CreateCargo {
	@AuraEnabled
	public static Object getInfo(Id recordId) {
		List<Map<String, String>> picklistUnit = new List<Map<String, String>>();

		for (PicklistEntry item : Cargo__c.CargoType__c.getDescribe().getPicklistValues()) {
			picklistUnit.add(new Map<String, String>{ 'label' => item.Label, 'value' => item.Value });
		}

		return new Map<String, Object> {
			'workOrder' => (WorkOrder__c)[
				SELECT
					RecordType.Name, RecordType.DeveloperName,
					WarehouseID__c, WarehouseID__r.Name, WarehouseID__r.FacilityName__c,
					DestinationWarehouse__c, DestinationWarehouse__r.Name, DestinationWarehouse__r.FacilityName__c,
					(
						SELECT Id, VASServiceType__c, VASRequirement__c, ServiceStage__c, RecordTypeId,
							Warehouse__c, Warehouse__r.Name, Warehouse__r.FacilityName__c,
							DestinationWarehouse__c, DestinationWarehouse__r.Name, DestinationWarehouse__r.FacilityName__c
						FROM WorkOrderService__r
					)
				FROM WorkOrder__c
				WHERE Id = :recordId
			],
			'woProducts' => [
				SELECT Id, ProductID__c, NETWeightKG__c, Quantity__c, ShippingTypeAtWarehouse__c, ProductID__r.UnitType__c, ProductID__r.BillingType__c
				FROM ConnectWOProduct__c 
				WHERE WorkOrderID__c = :recordId
			],
			/*'serviceRecordTypes' => [
				SELECT Id, Name, DeveloperName
				FROM RecordType
				WHERE SobjectType = 'clofor_com_cfs__WorkOrderService__c'
			], */
			'picklistUnit' => picklistUnit
		};
	}

	@AuraEnabled
	public static void saveCargos(Id recordId, String payload) {
		DestinationWrapper[] request = (DestinationWrapper[])JSON.deserialize(payload, DestinationWrapper[].class);
		List<Cargo__c> listCargos = new List<SObject>();
		WorkOrder__c wo = [
			SELECT
				RecordType.Name, RecordType.DeveloperName, WarehouseID__c, DestinationWarehouse__c,
				(
					SELECT Id, VASServiceType__c, VASRequirement__c, ServiceStage__c, RecordTypeId, Warehouse__c, DestinationWarehouse__c
					FROM WorkOrderService__r
				)
			FROM WorkOrder__c
			WHERE Id = :recordId
			LIMIT 1
		];

		//Group services into origin and destination services
		//Also group destination services by destination
		List<WorkOrderService__c> origServices = new List<WorkOrderService__c>();
		Map<Id, List<WorkOrderService__c>> destServices = new Map<Id, List<WorkOrderService__c>>();

		for (WorkOrderService__c wos : wo.WorkOrderService__r) {
			if (wos.Warehouse__c  == wo.WarehouseId__c && wos.DestinationWarehouse__c == null) {
				origServices.add(wos);
			}
			else {
				String destinationId = wos.DestinationWarehouse__c == null ? wos.Warehouse__c : wos.DestinationWarehouse__c;
				if (!destServices.containsKey(destinationId)) {
					destServices.put(destinationId, new List<WorkOrderService__c>{ wos });
				}
				else {
					destServices.get(destinationId).add(wos);
				}
			}
		}

		//loop through request then insert cargo
		for (DestinationWrapper dest : request) {
			for (CargoWrapper item : dest.Cargos) {
				item.Records = new Cargo__c[]{};
				for (Integer i = 0; i < item.CargoQty; i++) {
					Cargo__c record = new Cargo__c(
						Product__c = item.ProductId,
						PlannedWeight__c = item.Weight,
						CargoType__c = item.Unit
					);
					listCargos.add(record);
					item.Records.add(record);
				}
			}
		}
        FlsService.doInsert(listCargos);

		List<WosLineItem__c> listWosLineItems = new List<WosLineItem__c>();

		//insert origin service, all cargos will be linked to all orgin services
		for(WorkOrderService__c wos : origServices) {
			for (Cargo__c cargo : listCargos) {
				listWosLineItems.add(new WosLineItem__c(
					Cargo__c = cargo.Id,
					WorkOrderService__c = wos.Id
				));
			}
		}

		//insert destination services, only cargos belong to the same destination will be linked to aforementioned services
		for (DestinationWrapper dest : request) {
			if (dest.DestinationId == wo.WarehouseID__c || !destServices.containsKey(dest.DestinationId)) {
				continue;
			}

			for(WorkOrderService__c wos : destServices.get(dest.DestinationId)) {
				for (CargoWrapper item : dest.Cargos) {
					for (Cargo__c cargo : item.Records) {
						listWosLineItems.add(new WosLineItem__c(
							Cargo__c = cargo.Id,
							WorkOrderService__c = wos.Id,
							CargoStatus__c = 'Planned'
						));
					}
				}
			}
		}

        FlsService.doInsert(listWosLineItems);
	}

	public class DestinationWrapper {
		public String DestinationId { get; set; }
		public CargoWrapper[] Cargos { get; set; }
	}

	public class CargoWrapper {
		public String ProductId { get; set; }
		public Integer ProductQty { get; set; }
		public Integer CargoQty { get; set; }
		public Decimal Weight { get; set; }
		public String Unit { get; set; }
		public String CargoType { get; set; }
		public Cargo__c[] Records { get; set; }
	}
}