force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/ConnectWOProduct__c.object-meta.xml
<CustomObject>
    <label>W/O+Product</label>
    <nameField>
        <displayFormat>WP-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/W/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectWOProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>W/O+PRODUCT</relationshipLabel>
    <relationshipName>CONNECT_WORK_ORDER_PRODUCT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipName>CONNECT_WORK_ORDER_PRODUCT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WO_Cargo__c/WO_Cargo__c.object-meta.xml
<CustomObject>
    <label>WO+Cargo</label>
    <nameField>
        <displayFormat>WOC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WO+Cargoes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WO_Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WO_Cargo__c/fields/WO_Product__c.field-meta.xml
<CustomField>
    <fullName>WO_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WO+Product</label>
    <referenceTo>ConnectWOProduct__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WO_Cargo__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WorkOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WoCargoTriggerHandler.cls
public with sharing class WoCargoTriggerHandler {
    public static void autoPopulateFields(List<WO_Cargo__c> listNew) {
        Set<Id> setCargoIds = new Set<Id>();
        Set<Id> setWoIds = new Set<Id>();
        Set<Id> setProductIds = new Set<Id>();

        for (WO_Cargo__c item : listNew) {
            setWoIds.add(item.WorkOrder__c);
            setCargoIds.add(item.Cargo__c);
        }

        Map<Id, Cargo__c> mapCargo = new Map<Id, Cargo__c>([SELECT Id, Product__c FROM Cargo__c WHERE Id IN :setCargoIds]);
        for (Cargo__c item : mapCargo.values()) {
            setProductIds.add(item.Product__c);
        }

        List<ConnectWOProduct__c> listWoProducts = [SELECT 
            Id, ProductId__c, ProductId__r.Name, WorkOrderID__c, WorkOrderID__r.Name 
            FROM ConnectWOProduct__c 
            WHERE ProductId__c IN :setProductIds 
                AND WorkOrderID__c IN :setWoIds
        ];

        for (WO_Cargo__c item : listNew) {
            for (ConnectWOProduct__c woProd : listWoProducts) {
                if (item.WorkOrder__c == woProd.WorkOrderId__c && mapCargo.containsKey(item.Cargo__c) && mapCargo.get(item.Cargo__c).Product__c == woProd.ProductId__c) {
                    item.WO_Product__c = woProd.Id;
                    break;
                }
            }
            if (item.WO_Product__c == null) {
                item.WO_Product__c.addError('Cannot find any WO+Product record that link the provided Work Order and Cargo\'s product.');
            }
        }
    }
}