force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/CargoLifeCycle__c.field-meta.xml
<CustomField>
    <fullName>CargoLifeCycle__c</fullName>
    <label>CARGO LIFE CYCLE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoLifeCycle</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WO_Cargo__c/WO_Cargo__c.object-meta.xml
<CustomObject>
    <label>WO+Cargo</label>
    <nameField>
        <displayFormat>WOC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WO+Cargoes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WO_Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WO_Cargo__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <label>Work order</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WO+Cargoes</relationshipLabel>
    <relationshipName>WO_Cargoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/CargoStatus__c.field-meta.xml
<CustomField>
    <fullName>CargoStatus__c</fullName>
    <label>Cargo Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
                <isActive>false</isActive>
                <label>Finalized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/IsCargoScanned__c.field-meta.xml
<CustomField>
    <fullName>IsCargoScanned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cargo Scanned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WO_Cargo__c.field-meta.xml
<CustomField>
    <fullName>WO_Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WO+Cargo</label>
    <referenceTo>WO_Cargo__c</referenceTo>
    <relationshipLabel>W/O/S LINE</relationshipLabel>
    <relationshipName>WosLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WOSLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/CargoLifeCycle.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>For sales</fullName>
        <default>true</default>
        <label>For sales</label>
    </customValue>
    <customValue>
        <fullName>For processing</fullName>
    </customValue>
    <customValue>
        <fullName>Under quality check</fullName>
    </customValue>
    <customValue>
        <fullName>Picking Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Return to supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Returned from customer</fullName>
    </customValue>
    <customValue>
        <fullName>Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Damaged</fullName>
    </customValue>
    <customValue>
        <fullName>Replaced</fullName>
    </customValue>
    <customValue>
        <fullName>Disposed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Wet</fullName>
    </customValue>
    <customValue>
        <fullName>Expired</fullName>
    </customValue>
    <customValue>
        <fullName>No longer exists</fullName>
    </customValue>
    <customValue>
        <fullName>Under Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Under Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for Last Mile Delivery</fullName>
    </customValue>
    <masterLabel>CARGO LIFE CYCLE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WosLineItemTriggerHelper.cls
public with sharing class WosLineItemTriggerHelper {
    public static void autoPopulateFields(List<WosLineItem__c> listNew, Map<Id, WosLineItem__c> mapOld) {
        Set<Id> setFrom = new Set<Id>();
        List<WosLineItem__c> listProcess = new List<WosLineItem__c>();
        for (WosLineItem__c item : listNew) {
            if (item.WorkOrderService__c != null && (mapOld == null || mapOld.get(item.Id).WorkOrderService__c != item.WorkOrderService__c)) {
                setFrom.add(item.WorkOrderService__c);
                listProcess.add(item);
            }
        }
        if (setFrom.isEmpty()) {
            return;
        }
        Map<Id, WorkOrderService__c> mapFrom = new Map<Id, WorkOrderService__c>([SELECT WorkOrder__c FROM WorkOrderService__c WHERE Id IN :setFrom]);
        for (WosLineItem__c item : listProcess) {
            item.WorkOrderID__c = mapFrom.get(item.WorkOrderService__c).WorkOrder__c;
        }
    }

    public static void linkWoCargo(List<WosLineItem__c> listNew) {
        Set<Id> setCargoIds = new Set<Id>();
        Set<Id> setWosIds = new Set<Id>();

        for (WosLineItem__c item : listNew) {
            setWosIds.add(item.WorkOrderService__c);
            setCargoIds.add(item.Cargo__c);
        }

        Set<Id> setWoIds = new Set<Id>();
        Map<Id, WorkOrderService__c> mapWos = new Map<Id, WorkOrderService__c>([SELECT WorkOrder__c FROM WorkOrderService__c WHERE Id IN :setWosIds]);
        for (WorkOrderService__c item : mapWos.values()) {
            setWoIds.add(item.WorkOrder__c);
        }

        List<WO_Cargo__c> listWoCargo = [
            SELECT Id, WorkOrder__c, Cargo__c
            FROM WO_Cargo__c 
            WHERE Cargo__c IN :setCargoIds 
                AND WorkOrder__c IN :setWoIds
        ];

        for (WosLineItem__c item : listNew) {
            for (WO_Cargo__c woCargo : listWoCargo) {
                if (woCargo.WorkOrder__c == mapWos.get(item.WorkOrderService__c).WorkOrder__c && woCargo.Cargo__c == item.Cargo__c) {
                    item.WO_Cargo__c = woCargo.Id;
                    break;
                }
            }
            // [27/08/2019] enforce rule causing problem with all existing processes, so commented out.
            // if (item.WO_Cargo__c == null) {
            //     item.WO_Cargo__c.addError('Cannot find any WO+Cargo record that link the provided Work Order and Cargo.');
            // }
        }
    }

    public static void updateDamagedCargoes(List<WosLineItem__c> listNew, Map<Id, WosLineItem__c> mapOld) {
        List<Cargo__c> listCargoesToUpdate = new List<Cargo__c>();

        for (WosLineItem__c item : listNew) {
            if (
                item.IsCargoScanned__c == true && (item.CargoStatus__c == 'Damaged' || item.CargoStatus__c == 'Missing')
                && (
                    mapOld == null || item.IsCargoScanned__c != mapOld.get(item.Id).IsCargoScanned__c || item.CargoStatus__c != mapOld.get(item.Id).CargoStatus__c
                )
            ) {
                listCargoesToUpdate.add(new Cargo__c(Id = item.Cargo__c, CargoLifeCycle__c = item.CargoStatus__c));
            }
        }

        if (!listCargoesToUpdate.isEmpty()) {
            FlsService.doUpdate(listCargoesToUpdate);
        }
    }
}