force-app/main/default/objects/BankTransaction__c/BankTransaction__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <displayFormat>BT-{000000}</displayFormat>
        <label>BANK TRANSACTION ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankTransaction__c/fields/RollupAmountOfInboundDepositLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupAmountOfInboundDepositLocal__c</fullName>
    <label>ROLLUP AMOUNT OF INBOUND DEPOSIT(LOCAL)</label>
    <summarizedField>DepositBank__c.AmountOfInboundDepositLocalForBank__c</summarizedField>
    <summaryForeignKey>DepositBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupAmountOfInboundDepositUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupAmountOfInboundDepositUSD__c</fullName>
    <label>ROLLUP AMOUNT OF INBOUND DEPOSIT(USD)</label>
    <summarizedField>DepositBank__c.AmountOfInboundDepositUSDForBank__c</summarizedField>
    <summaryForeignKey>DepositBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupAmountOfOutboundDeposit__c.field-meta.xml
<CustomField>
    <fullName>RollupAmountOfOutboundDeposit__c</fullName>
    <label>ROLLUP AMOUNT OF OUTBOUND DEPOSIT(LOCAL)</label>
    <summarizedField>DepositBank__c.AmountOfOutboundDepositLocalForBank__c</summarizedField>
    <summaryForeignKey>DepositBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupAmountOfOutboundDepositUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupAmountOfOutboundDepositUSD__c</fullName>
    <label>ROLLUP AMOUNT OF OUTBOUND DEPOSIT(USD)</label>
    <summarizedField>DepositBank__c.AmountOfOutboundDepositUSDForBank__c</summarizedField>
    <summaryForeignKey>DepositBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupFMSUnpaidBalOfBuyingLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupFMSUnpaidBalOfBuyingLocal__c</fullName>
    <label>ROLLUP FMS UNPAID BAL OF BUYING(LOCAL)</label>
    <summarizedField>CloFMSBillBank__c.FMSUnpaidBalOfBuyingLocal__c</summarizedField>
    <summaryForeignKey>CloFMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupFMSUnpaidBalOfBuyingUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupFMSUnpaidBalOfBuyingUSD__c</fullName>
    <label>ROLLUP FMS UNPAID BAL OF BUYING(USD)</label>
    <summarizedField>CloFMSBillBank__c.FMSUnpaidBalOfBuyingUSD__c</summarizedField>
    <summaryForeignKey>CloFMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupFMSUnpaidBalOfSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupFMSUnpaidBalOfSellingLocal__c</fullName>
    <label>ROLLUP FMS UNRECEIVED BAL OF SELL(LOCAL)</label>
    <summarizedField>CloFMSBillBank__c.FMSUnreceivedBalOfSellingLocal__c</summarizedField>
    <summaryForeignKey>CloFMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupFMSUnpaidBalOfSellingUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupFMSUnpaidBalOfSellingUSD__c</fullName>
    <label>ROLLUP FMS UNRECEIVED BAL OF SELL(USD)</label>
    <summarizedField>CloFMSBillBank__c.FMSUnreceivedBalOfSellingUSD__c</summarizedField>
    <summaryForeignKey>CloFMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupKickbackUnpaidBalanceLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupKickbackUnpaidBalanceLocal__c</fullName>
    <label>ROLLUP KICKBACK UNPAID BAL(LOCAL)</label>
    <summarizedField>KickbackBank__c.KickbackUnpaidBalanceLocal__c</summarizedField>
    <summaryForeignKey>KickbackBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupKickbackUnpaidBalanceUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupKickbackUnpaidBalanceUSD__c</fullName>
    <label>ROLLUP KICKBACK UNPAID BAL(USD)</label>
    <summarizedField>KickbackBank__c.KickbackUnpaidBalanceUSD__c</summarizedField>
    <summaryForeignKey>KickbackBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupLoanAmountFCY__c.field-meta.xml
<CustomField>
    <fullName>RollupLoanAmountFCY__c</fullName>
    <label>ROLLUP LOAN AMOUNT(FCY)</label>
    <summarizedField>LoanBank__c.LoanAmountFCYBank__c</summarizedField>
    <summaryForeignKey>LoanBank__c.BankID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupLoanAmountLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupLoanAmountLocal__c</fullName>
    <label>ROLLUP LOAN AMOUNT(LOCAL)</label>
    <summarizedField>LoanBank__c.LocalAmountLocalBank__c</summarizedField>
    <summaryForeignKey>LoanBank__c.BankID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupOtherUnpaidBalance__c.field-meta.xml
<CustomField>
    <fullName>RollupOtherUnpaidBalance__c</fullName>
    <label>ROLLUP OTHER UNPAID BAL</label>
    <summarizedField>OtherBank__c.UnpaidBalanceOfOtherForBank__c</summarizedField>
    <summaryFilterItems>
        <field>OtherBank__c.OtherRecordTypeForBank__c</field>
        <operation>notContain</operation>
        <value>Bank Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>OtherBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupOtherUnreceivedBalance__c.field-meta.xml
<CustomField>
    <fullName>RollupOtherUnreceivedBalance__c</fullName>
    <label>ROLLUP OTHER UNRECEIVED BAL</label>
    <summarizedField>OtherBank__c.UnreceivedBalanceOfOtherForBank__c</summarizedField>
    <summaryFilterItems>
        <field>OtherBank__c.OtherRecordTypeForBank__c</field>
        <operation>notContain</operation>
        <value>Bank Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>OtherBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupOtherUnreceivedBalUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupOtherUnreceivedBalUSD__c</fullName>
    <label>ROLLUP OTHER UNRECEIVED BAL(USD)</label>
    <summarizedField>OtherBank__c.UnreceivedBalOfOtherUSDBank__c</summarizedField>
    <summaryFilterItems>
        <field>OtherBank__c.OtherRecordTypeForBank__c</field>
        <operation>notContain</operation>
        <value>Bank Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>OtherBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupPayslipUnpaidBal__c.field-meta.xml
<CustomField>
    <fullName>RollupPayslipUnpaidBal__c</fullName>
    <label>ROLLUP PAYSLIP UNPAID BAL</label>
    <summarizedField>Payslipbank__c.UnpaidBalUnpaidBalOfPayslipBank__c</summarizedField>
    <summaryForeignKey>Payslipbank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupPIUnpaidBalanceLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupPIUnpaidBalanceLocal__c</fullName>
    <label>ROLLUP P/I UNPAID BAL(LOCAL)</label>
    <summarizedField>PIBank__c.UnpaidBalancePILocalForBank__c</summarizedField>
    <summaryForeignKey>PIBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupPIUnpaidBalanceUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupPIUnpaidBalanceUSD__c</fullName>
    <label>ROLLUP P/I UNPAID BAL(USD)</label>
    <summarizedField>PIBank__c.UnpaidBalancePIUSDForBank__c</summarizedField>
    <summaryForeignKey>PIBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupTotalLoanRepayment__c.field-meta.xml
<CustomField>
    <fullName>RollupTotalLoanRepayment__c</fullName>
    <label>ROLLUP TOTAL LOAN REPAYMENT</label>
    <summarizedField>LoanPayBank__c.TotalAmountOfLoanRepaymentPayReq__c</summarizedField>
    <summaryForeignKey>LoanPayBank__c.LoanPayBankID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupWMSUnpaidBalOfBuyingLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupWMSUnpaidBalOfBuyingLocal__c</fullName>
    <label>ROLLUP WMS UNPAID BAL OF BUYING(LOCAL)</label>
    <summarizedField>CloWMSBillBank__c.WMSUnpaidBalOfBuyingLocal__c</summarizedField>
    <summaryForeignKey>CloWMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupWMSUnpaidBalOfBuyingUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupWMSUnpaidBalOfBuyingUSD__c</fullName>
    <label>ROLLUP WMS UNPAID BAL OF BUYING(USD)</label>
    <summarizedField>CloWMSBillBank__c.WMSUnpaidBalOfBuyingUSD__c</summarizedField>
    <summaryForeignKey>CloWMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupWMSUnpaidBalOfSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>RollupWMSUnpaidBalOfSellingLocal__c</fullName>
    <label>ROLLUP WMS UNRECEIVED BAL OF SELL(LOCAL)</label>
    <summarizedField>CloWMSBillBank__c.WMSUnreceivedBalOfSellingLocal__c</summarizedField>
    <summaryForeignKey>CloWMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/RollupWMSUnpaidBalOfSellingUSD__c.field-meta.xml
<CustomField>
    <fullName>RollupWMSUnpaidBalOfSellingUSD__c</fullName>
    <label>ROLLUP WMS UNRECEIVED BAL OF SELL(USD)</label>
    <summarizedField>CloWMSBillBank__c.WMSUnreceivedBalOfSellingUSD__c</summarizedField>
    <summaryForeignKey>CloWMSBillBank__c.BankTransactionID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/TotalAmountOfPayableLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfPayableLocal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TOTAL AMOUNT OF PAYABLE(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/TotalAmountOfPayableUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfPayableUSD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TOTAL AMOUNT OF PAYABLE(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/TotalAmountOfReceivableLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfReceivableLocal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TOTAL AMOUNT OF RECEIVABLE(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/TotalAmountOfReceivableUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfReceivableUSD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TOTAL AMOUNT OF RECEIVABLE(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BankTransactionTriggerHelper.cls
public with sharing class BankTransactionTriggerHelper {
    public static void calculateAmount(List<BankTransaction__c> bankNews) {
        // for(BankTransaction__c bank : bankNews){
        //     Decimal amountLocal = 0;
        //     amountLocal += bank.RollupFMSUnpaidBalOfBuyingLocal__c == null? 0: bank.RollupFMSUnpaidBalOfBuyingLocal__c;
        //     amountLocal += bank.RollupWMSUnpaidBalOfBuyingLocal__c == null? 0: bank.RollupWMSUnpaidBalOfBuyingLocal__c;
        //     amountLocal += bank.RollupPIUnpaidBalanceLocal__c == null? 0: bank.RollupPIUnpaidBalanceLocal__c;
        //     amountLocal += bank.RollupKickbackUnpaidBalanceLocal__c == null? 0: bank.RollupKickbackUnpaidBalanceLocal__c;
        //     amountLocal += bank.RollupAmountOfOutboundDeposit__c == null? 0: bank.RollupAmountOfOutboundDeposit__c;
        //     amountLocal += bank.RollupPayslipUnpaidBal__c == null? 0: bank.RollupPayslipUnpaidBal__c;
        //     amountLocal += bank.RollupOtherUnpaidBalance__c == null? 0: bank.RollupOtherUnpaidBalance__c;
        //     amountLocal += bank.RollupTotalLoanRepayment__c == null? 0: bank.RollupTotalLoanRepayment__c;
        //     Decimal amountUSD = 0;
        //     amountUSD += bank.RollupFMSUnpaidBalOfBuyingUSD__c == null? 0: bank.RollupFMSUnpaidBalOfBuyingUSD__c;
        //     amountUSD += bank.RollupWMSUnpaidBalOfBuyingUSD__c == null? 0: bank.RollupWMSUnpaidBalOfBuyingUSD__c;
        //     amountUSD += bank.RollupPIUnpaidBalanceUSD__c == null? 0: bank.RollupPIUnpaidBalanceUSD__c;
        //     amountUSD += bank.RollupKickbackUnpaidBalanceUSD__c == null? 0: bank.RollupKickbackUnpaidBalanceUSD__c;
        //     amountUSD += bank.RollupAmountOfOutboundDepositUSD__c == null? 0: bank.RollupAmountOfOutboundDepositUSD__c;
        //     //amountUSD += bank.RollupOtherUnpaidBalanceUSD__c == null? 0: bank.RollupOtherUnpaidBalanceUSD__c;

        //     Decimal amountSellLocal = 0;
        //     amountSellLocal += bank.RollupFMSUnpaidBalOfSellingLocal__c == null? 0: bank.RollupFMSUnpaidBalOfSellingLocal__c;
        //     amountSellLocal += bank.RollupOtherUnreceivedBalance__c == null? 0: bank.RollupOtherUnreceivedBalance__c;
        //     amountSellLocal += bank.RollupWMSUnpaidBalOfSellingLocal__c == null? 0: bank.RollupWMSUnpaidBalOfSellingLocal__c;
        //     amountSellLocal += bank.RollupAmountOfInboundDepositLocal__c  == null? 0: bank.RollupAmountOfInboundDepositLocal__c ;
        //     amountSellLocal += bank.RollupLoanAmountLocal__c == null? 0: bank.RollupLoanAmountLocal__c;

        //     Decimal amountSellUSD = 0;
        //     amountSellUSD += bank.RollupFMSUnpaidBalOfSellingUSD__c == null? 0: bank.RollupFMSUnpaidBalOfSellingUSD__c;
        //     amountSellUSD += bank.RollupOtherUnreceivedBalUSD__c == null? 0: bank.RollupOtherUnreceivedBalUSD__c;
        //     amountSellUSD += bank.RollupWMSUnpaidBalOfSellingUSD__c == null? 0: bank.RollupWMSUnpaidBalOfSellingUSD__c;
        //     amountSellUSD += bank.RollupAmountOfInboundDepositUSD__c  == null? 0: bank.RollupAmountOfInboundDepositUSD__c ;
        //     amountSellUSD += bank.RollupLoanAmountFCY__c == null? 0: bank.RollupLoanAmountFCY__c;

        //     bank.TotalAmountOfPayableLocal__c = amountLocal; 
        //     bank.TotalAmountOfPayableUSD__c = amountUSD; 
        //     bank.TotalAmountOfReceivableLocal__c = amountSellLocal;
        //     bank.TotalAmountOfReceivableUSD__c = amountSellUSD;
        // }
    }
}