force-app/main/default/objects/Site_Custom_Settings__c/Site_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Site Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Company_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName1__c</fullName>
    <label>FCY Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/FCYBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>FCYBankAccountShortName2__c</fullName>
    <label>FCY Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName1__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName1__c</fullName>
    <label>Local Currency Bank Account Short Name-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName2__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName2__c</fullName>
    <label>Local Currency Bank Account Short Name-2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName3__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName3__c</fullName>
    <label>Local Currency Bank Account Short Name-3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName4__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName4__c</fullName>
    <label>Local Currency Bank Account Short Name-4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Custom_Settings__c/fields/LocalCurrencyBankAccountShortName5__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrencyBankAccountShortName5__c</fullName>
    <label>Local Currency Bank Account Short Name-5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PrintHBLControllerTest.cls
@isTest
public with sharing class PrintHBLControllerTest {
    @isTest
    public static void testGetData(){
        Test.startTest();
        Account acc = new Account(Name = 'test acc');
        Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
        insert acc;
        clofor_com_cfs__CustomObject1__c shipment = new clofor_com_cfs__CustomObject1__c(clofor_com_cfs__Field1__c = acc.Id,
                                                                                        clofor_com_cfs__CBM__c = 34,
                                                                                        clofor_com_cfs__C_W_Dimension_dev__c = 78);
        
        insert shipment;
        ApexPages.currentPage().getParameters().put('id', shipment.Id);
        PrintHBLController ctrl = new PrintHBLController();
        System.assertNotEquals(null, ctrl.shipment);
        Test.stopTest();
    }

    @isTest
    public static void testIsAutoCheckedCreateAttachment(){
        Test.startTest();
        Account acc = new Account(Name = 'test acc');
        Site_Custom_Settings__c setting = new Site_Custom_Settings__c();
        setting.LocalCurrencyBankAccountShortName1__c = 'Bank 1';
        setting.LocalCurrencyBankAccountShortName2__c = 'Bank 2';
        setting.LocalCurrencyBankAccountShortName3__c = 'Bank 3';
        setting.LocalCurrencyBankAccountShortName4__c = 'Bank 4';
        setting.LocalCurrencyBankAccountShortName5__c = 'Bank 5';
        setting.FCYBankAccountShortName1__c = 'Bank Foreign 1';
        setting.FCYBankAccountShortName2__c = 'Bank Foreign 2';
        setting.Company_Country__c = 'VN';
        setting.Local_Currency__c = 'VND';
         setting.clofor_com_cfs__Disable_Monthly_Yearly_HBL_ID__c = false;
        insert setting;
        insert acc;
        clofor_com_cfs__CustomObject1__c shipment = new clofor_com_cfs__CustomObject1__c(clofor_com_cfs__Field1__c = acc.Id);
        insert shipment;
        System.assertEquals(false, PrintHBLController.isAutoCheckedCreateAttachment(shipment.Id));
        Test.stopTest();
    }
}