force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote.</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>QUOTE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine__c/QuoteLine__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QTLN-{000000}</displayFormat>
        <label>QUOTE LINE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>QUOTE ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>QUOTE LINE</relationshipLabel>
    <relationshipName>QuoteLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassEditBuyingQuoteLineControllerTest.cls
@isTest
public class MassEditBuyingQuoteLineControllerTest {
    @testSetup
    static void setup() {
 		Quote__c quote = new Quote__c();
        insert quote;
        QuoteLine__c quoteLine = new QuoteLine__c(QuoteID__c = quote.Id);
        insert quoteLine;
	}

	@isTest
    static void testReturnFirstRecordId(){
        String recordTypeId = MassEditBuyingQuoteLineController.getRecordTypeId();
        System.assertNotEquals('', recordTypeId);
    }
    
    @isTest
    static void testGetAllQuoteLines(){
        Quote__c quote = [SELECT Id FROM Quote__c LIMIT 1];
        List<QuoteLine__c> allQuoteLines = MassEditBuyingQuoteLineController.getAllQuoteLines(quote.Id);
        System.assertNotEquals(0, allQuoteLines.size());
    }
    @isTest
    static void testGetAllQuoteLines1(){
        Quote__c quote1 = [SELECT Id FROM Quote__c LIMIT 1];
        List<QuoteLine__c> allQuoteLines1 = MassEditBuyingQuoteLineController.getAllQuoteLines1(quote1.Id);
        System.assertNotEquals(0, allQuoteLines1.size());
    }
    
    @isTest
    static void testUpdateQuoteLines(){
        List<QuoteLine__c> allQuoteLines = [SELECT Id FROM QuoteLine__c];
        String jsonRecords = JSON.serialize(allQuoteLines);
        String res = MassEditBuyingQuoteLineController.updateQuoteLines(jsonRecords);
        System.assertEquals(false, res.contains('The following exception has occurred:'));
    }
    @isTest
    static void testDeleteQuoteLines(){

        QuoteLine__c quoteline = [SELECT Id FROM QuoteLine__c LIMIT 1];
        Boolean res = MassEditBuyingQuoteLineController.deleteQuoteline(quoteLine.Id);
        System.assertEquals(true, res);
        Boolean res1 = MassEditBuyingQuoteLineController.deleteQuoteline('quoteLine');
          System.assertEquals(false, res1);
    }
    @isTest
    static void testCloneQuoteLines(){

        QuoteLine__c quoteline = [SELECT Id FROM QuoteLine__c LIMIT 1];
        Boolean res = MassEditBuyingQuoteLineController.cloneQuoteline1(quoteLine.Id);
        System.assertEquals(true, res);
        Boolean res1 = MassEditBuyingQuoteLineController.cloneQuoteline1('quoteLine');
          System.assertEquals(false, res1);
    }

    @isTest
    static void testetFieldLabels(){
        String res = MassEditBuyingQuoteLineController.getFieldLabels();
        System.assertNotEquals(res, '');
    }
}