force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote.</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>QUOTE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/ContainerType__c.field-meta.xml
<CustomField>
    <fullName>ContainerType__c</fullName>
    <label>CONTAINER TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ContainerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/AirLogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>AirLogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Air Logistics Service</description>
    <label>Air Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/Quote__c/recordTypes/DomesticLogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>DomesticLogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Domestic Logistics Service</description>
    <label>Domestic Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/Quote__c/recordTypes/LogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>LogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Ocean(Sea) Logistic Service</description>
    <label>Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/Quote__c/recordTypes/ProductQuote.recordType-meta.xml
<RecordType>
    <fullName>ProductQuote</fullName>
    <active>true</active>
    <description>Product Quote Line for Trading</description>
    <label>Product Quote</label>
</RecordType>

force-app/main/default/objects/QuoteLine__c/QuoteLine__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QTLN-{000000}</displayFormat>
        <label>QUOTE LINE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine__c/fields/ContainerType__c.field-meta.xml
<CustomField>
    <fullName>ContainerType__c</fullName>
    <label>CONTAINER TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Unit__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ContainerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <defaultValue>$Setup.Site_Custom_Settings__c.Local_Currency__c</defaultValue>
    <label>CURRENCY-SELLING</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/Print__c.field-meta.xml
<CustomField>
    <fullName>Print__c</fullName>
    <defaultValue>true</defaultValue>
    <label>PRINT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/PrintingSection__c.field-meta.xml
<CustomField>
    <fullName>PrintingSection__c</fullName>
    <label>PRINTING SECTION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PrintingSection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>QUOTE ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>QUOTE LINE</relationshipLabel>
    <relationshipName>QuoteLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/QuoteLineNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineNumber__c</fullName>
    <label>QUOTE LINE NUMBER</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>REMARKS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/SellingListPriceLocal__c.field-meta.xml
<CustomField>
    <fullName>SellingListPriceLocal__c</fullName>
    <label>SELLING LIST PRICE(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/SellingListPriceUSD__c.field-meta.xml
<CustomField>
    <fullName>SellingListPriceUSD__c</fullName>
    <label>SELLING LIST PRICE(USD)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TAX RATE-SELLING(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLine__c/recordTypes/AirLogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>AirLogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Air Logistics Service</description>
    <label>Air Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/QuoteLine__c/recordTypes/DomesticLogisticsServiceQuote.recordType-meta.xml
<RecordType>
    <fullName>DomesticLogisticsServiceQuote</fullName>
    <active>true</active>
    <description>Service Quote Line for Logistics Service</description>
    <label>Logistics Service Quote</label>
</RecordType>

force-app/main/default/objects/QuoteLine__c/recordTypes/ProductQuoteLine.recordType-meta.xml
<RecordType>
    <fullName>ProductQuoteLine</fullName>
    <active>true</active>
    <label>Product Quote Line</label>
</RecordType>

force-app/main/default/objects/QuoteLine__c/recordTypes/ServiceQuoteLine.recordType-meta.xml
<RecordType>
    <fullName>ServiceQuoteLine</fullName>
    <active>true</active>
    <description>Service Quote Line for Ocean(Sea) Logistic Service</description>
    <label>Service Quote Line</label>
</RecordType>

force-app/main/default/globalValueSets/ContainerType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;All</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;All</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;DC</fullName>
    </customValue>
    <customValue>
        <fullName>2*20&apos;DC</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;DC</fullName>
    </customValue>
    <customValue>
        <fullName>45&apos;DC</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;HC</fullName>
    </customValue>
    <customValue>
        <fullName>45&apos;HC</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;RF</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;RF</fullName>
    </customValue>
    <customValue>
        <fullName>45&apos;RF</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;OT</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;OT</fullName>
    </customValue>
    <customValue>
        <fullName>45&apos;OT</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;FR</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;FR</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;ISO</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;ISO</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;IMO</fullName>
    </customValue>
    <customValue>
        <fullName>40&apos;IMO</fullName>
    </customValue>
    <customValue>
        <fullName>45&apos;IMO</fullName>
    </customValue>
    <customValue>
        <fullName>20&apos;DC-Flexi</fullName>
    </customValue>
    <customValue>
        <fullName>AIR</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>RTON</fullName>
    </customValue>
    <customValue>
        <fullName>5TONS</fullName>
    </customValue>
    <customValue>
        <fullName>10TONS</fullName>
    </customValue>
    <masterLabel>CONTAINER TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
        <default>true</default>
        <label>VND</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>PHP</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <masterLabel>CURRENCY</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PrintingSection.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1st Section</fullName>
        <default>true</default>
        <label>1st Section</label>
    </customValue>
    <customValue>
        <fullName>2nd Section</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Section</fullName>
    </customValue>
    <customValue>
        <fullName>4th Section</fullName>
    </customValue>
    <masterLabel>PRINTING SECTION</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MassiveNewQuoteLineController.cls
public with sharing class MassiveNewQuoteLineController {
    public Integer recordsNumber{get;set;}
    private String recordtypeId;
    public Boolean initialMode{get;set;}
    public Quote__c quote {get;set;}
    public List<QuoteLine__c> listQuoteLine{get;set;}
    private Decimal maxQuoteLineNumber{get;set;}
    public MassiveNewQuoteLineController() {
        initialMode = true;
        listQuoteLine = new List<QuoteLine__c>();
        maxQuoteLineNumber = 0;
        Map<String, String> recordTypesMap = new Map<String, String>();
        recordTypesMap.put('LogisticsServiceQuote','ServiceQuoteLine');
        recordTypesMap.put('AirLogisticsServiceQuote','AirLogisticsServiceQuote');
        recordTypesMap.put('DomesticLogisticsServiceQuote','DomesticLogisticsServiceQuote');
        recordTypesMap.put('ProductQuote ','ProductQuoteLine');
        String quoteId = ApexPages.currentPage().getParameters().get('quoteId');
        if(!String.isBlank(quoteId)){
            List<Quote__c> quotes = [Select Id, RecordType.DeveloperName From Quote__c where Id =: quoteId];
            if(!quotes.isEmpty()){
                quote = quotes[0];
            }else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'The Quote was not found.'));
                return;
            }
            recordtypeId = Schema.SObjectType.QuoteLine__c.getRecordTypeInfosByDeveloperName().get(recordTypesMap.get(quote.RecordType.DeveloperName)).getRecordTypeId();
            List<AggregateResult> maxResult = [SELECT MAX(clofor_com_cfs__QuoteLineNumber__c) maxNumber FROM QuoteLine__c where clofor_com_cfs__QuoteID__c =: quote.Id];
            if(maxResult.size() > 0 && maxResult[0].get('maxNumber') != null){
                maxQuoteLineNumber  = (Decimal)maxResult[0].get('maxNumber');
            }else{
                maxQuoteLineNumber = 0;
            }
            
        }else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please specify the quote Id.'));
            return;
        }
    }
    public void initiateQuoteLineItems(){
        if(recordsNumber <= 0 ){
            return;
        }
        for(Integer i = 0; i < recordsNumber; i++){
            QuoteLine__c newQuoteLine = new QuoteLine__c(
                RecordtypeId = recordtypeId,
                PrintingSection__c = '1st Section',
                Print__c = true,
                QuoteID__c = quote.Id
            );
            listQuoteLine.add(newQuoteLine);
        }
        initialMode = false;
    }
    public Pagereference createQuoteLines(){
        //try{
            List<QuoteLine__c> newLines = new List<QuoteLine__c>();
            for(QuoteLine__c line : listQuoteLine ){
                if(line.clofor_com_cfs__ServicePricingID__c != null 
                || !String.isBlank(line.clofor_com_cfs__LineItemName__c) 
                || line.Quantity__c != null || line.ContainerType__c != null 
                || line.CurrencySelling__c != null || line.SellingListPriceLocal__c != null
                || line.SellingListPriceUSD__c != null || line.TaxRate__c != null || !String.isBlank(Line.Remarks__c ) ){
                    line.QuoteLineNumber__c = maxQuoteLineNumber + 1;
                    maxQuoteLineNumber += 1;
                    newLines.add(line);
                }
            }
            
            FlsService.doInsert(newLines);
            PageReference pg = new PageReference('/'+quote.Id);
            pg.setRedirect(true);
            return pg;
        //}catch(Exception ex){
            //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));
           // return null;
        //}
    }
    public void addMore(){
        recordsNumber ++;
        listQuoteLine.add(new QuoteLine__c(
            RecordtypeId = recordtypeId,
            PrintingSection__c = '1st Section',
            Print__c = true,
            QuoteID__c = quote.Id
        ));
    }
}