force-app/main/default/objects/GoodsPOProduct__c/GoodsPOProduct__c.object-meta.xml
<CustomObject>
    <label>Goods P/O+Product</label>
    <nameField>
        <displayFormat>GPPD-{000000}</displayFormat>
        <label>GOODS P/O+PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods P/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GoodsPOProduct__c/fields/AmountOfBuyingTax__c.field-meta.xml
<CustomField>
    <fullName>AmountOfBuyingTax__c</fullName>
    <label>AMOUNT OF BUYING TAX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <formula>text(ProductID__r.BillingType__c)</formula>
    <label>BILLING TYPE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/BuyingAmountInclTax__c.field-meta.xml
<CustomField>
    <fullName>BuyingAmountInclTax__c</fullName>
    <label>BUYING AMOUNT INCL TAX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/FinalQuantity__c.field-meta.xml
<CustomField>
    <fullName>FinalQuantity__c</fullName>
    <label>FINAL QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/PlanQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlanQuantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>GOODS P/O+PRODUCT</relationshipLabel>
    <relationshipName>GoodsPOProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/RecommendNetWeight__c.field-meta.xml
<CustomField>
    <fullName>RecommendNetWeight__c</fullName>
    <label>RECOMMENDED NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/TotalAmountOfBuying__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfBuying__c</fullName>
    <label>Total Amount of Buying</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/TotalGrossWeight__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossWeight__c</fullName>
    <label>TOTAL GROSS WEIGHT(Kg)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/TotalMeasurement__c.field-meta.xml
<CustomField>
    <fullName>TotalMeasurement__c</fullName>
    <label>TOTAL MEASUREMENT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GoodsPOProduct__c/fields/TotalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>TotalNetWeight__c</fullName>
    <label>PLAN NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/BuyingCommercialValuePerUnitLocal__c.field-meta.xml
<CustomField>
    <fullName>BuyingCommercialValuePerUnitLocal__c</fullName>
    <label>BUYING COMMERCIAL VALUE PER UNIT(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/BuyingUnitPriceLocalKg__c.field-meta.xml
<CustomField>
    <fullName>BuyingUnitPriceLocalKg__c</fullName>
    <label>BUYING UNIT PRICE(LOCAL)/Kg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/BuyingWeightUnit__c.field-meta.xml
<CustomField>
    <fullName>BuyingWeightUnit__c</fullName>
    <label>BUYING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <inlineHelpText>= cubic inch/61023.744 or cubic feet/35.315 or cubic yard/1.308</inlineHelpText>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/NETWeight__c.field-meta.xml
<CustomField>
    <fullName>NETWeight__c</fullName>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/TaxRateBuying__c.field-meta.xml
<CustomField>
    <fullName>TaxRateBuying__c</fullName>
    <label>TAX RATE-BUYING(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WeightUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>WEIGHT UNIT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PoProductTriggerHelper.cls
public with sharing class PoProductTriggerHelper {
    public static void autoPopulateFields(List<GoodsPOProduct__c> listNew, Map<Id, GoodsPOProduct__c> mapOld) {
        Set<Id> setFromProduct = new Set<Id> ();
        List<GoodsPOProduct__c> listProcess = new List<GoodsPOProduct__c>();
        for (GoodsPOProduct__c item : listNew) {
            if (item.ProductId__c != null) {
                setFromProduct.add(item.ProductID__c);
                listProcess.add(item);
            }
        }
        Map<Id, Product__c> mapFromProdduct = new Map<Id, Product__c>([
            SELECT Id, BillingType__c, BuyingWeightUnit__c, NETWeight__c, Measurement__c, GrossWeight__c, TaxRateBuying__c, BuyingCommercialValuePerUnitLocal__c, BuyingUnitPriceLocalKg__c
            FROM Product__c 
            WHERE Id IN :setFromProduct
        ]);
        
        for (GoodsPOProduct__c item : listProcess) {
            //TODO move this first code block outside of loop
            Product__c prod = mapFromProdduct.get(item.ProductId__c);
            prod.NETWeight__c = prod.NETWeight__c == null ? 0 : prod.NETWeight__c;
            prod.GrossWeight__c = prod.GrossWeight__c == null ? 0 : prod.GrossWeight__c;
            prod.Measurement__c = prod.Measurement__c == null ? 0 : prod.Measurement__c;
            prod.TaxRateBuying__c = prod.TaxRateBuying__c == null ? 0 : prod.TaxRateBuying__c;
            prod.BuyingCommercialValuePerUnitLocal__c = prod.BuyingCommercialValuePerUnitLocal__c == null ? 0 : prod.BuyingCommercialValuePerUnitLocal__c;
            prod.BuyingUnitPriceLocalKg__c = prod.BuyingUnitPriceLocalKg__c == null ? 0 : prod.BuyingUnitPriceLocalKg__c;
            Decimal prodNetWeight = Util.ConvertWeightToUnit('Kg', prod.BuyingWeightUnit__c, prod.NETWeight__c);
            Decimal prodGrossWeight = Util.ConvertWeightToUnit('Kg', prod.BuyingWeightUnit__c, prod.GrossWeight__c);
            
            item.Quantity__c = item.Quantity__c == null ? 1 : item.Quantity__c;
            item.RecommendNetWeight__c = item.RecommendNetWeight__c == null ? 0 : item.RecommendNetWeight__c;

            //Uniprodt-based -> Calculate recommended weight from Recommended Quantity, Planned weight from planned quantity
            if (prod.BillingType__c == 'Unit') {
                if (item.PlanQuantity__c == null && item.Quantity__c > 0) {
                    item.PlanQuantity__c = item.Quantity__c;
                }
                //Measurement, gross weight, total amount of buying are populated in the following priority: Final > Plan > Recommend; set value in the reverse order to ensure the correct final value
                //recommend net weight
                if (item.Quantity__c > 0) {
                    item.RecommendNetWeight__c = item.Quantity__c * prodNetWeight;
                    item.TotalMeasurement__c = item.Quantity__c * prod.Measurement__c;
                    item.TotalGrossWeight__c = item.Quantity__c * prod.GrossWeight__c;
                    item.TotalAmountOfBuying__c = item.Quantity__c * prod.BuyingCommercialValuePerUnitLocal__c;
                }
                //planned net weight
                if (item.PlanQuantity__c > 0) {
                    item.TotalNetWeight__c = item.PlanQuantity__c * prodNetWeight;
                    item.TotalMeasurement__c = item.PlanQuantity__c * prod.Measurement__c;
                    item.TotalGrossWeight__c = item.PlanQuantity__c * prod.GrossWeight__c;
                    item.TotalAmountOfBuying__c = item.PlanQuantity__c * prod.BuyingCommercialValuePerUnitLocal__c;
                }
                //final net weight
                if (item.FinalQuantity__c > 0) {
                    item.FinalNetWeight__c = item.FinalQuantity__c * prodNetWeight;
                    item.TotalMeasurement__c = item.FinalQuantity__c * prod.Measurement__c;
                    item.TotalGrossWeight__c = item.FinalQuantity__c * prod.GrossWeight__c;
                    item.TotalAmountOfBuying__c = item.FinalQuantity__c * prod.BuyingCommercialValuePerUnitLocal__c;
                }
            } 
            //Weight-based -> RecommendNetWeight__c is populated
            else if (prod.BillingType__c == 'Weight' && (prod.NETWeight__c == null || prod.NETWeight__c == 0)) {
                if (item.TotalNetWeight__c == null && item.RecommendNetWeight__c > 0) {
                    item.TotalNetWeight__c = Util.ConvertWeightToUnit('Kg', prod.BuyingWeightUnit__c, item.RecommendNetWeight__c);
                }
                Decimal currentWeight = item.FinalNetWeight__c > 0 ? item.FinalNetWeight__c : item.TotalNetWeight__c > 0 ? item.TotalNetWeight__c : item.RecommendNetWeight__c;
                if (item.RecommendNetWeight__c > 0) {
                    item.Quantity__c = 1;
                    item.TotalAmountOfBuying__c = Util.ConvertWeightToUnit(prod.BuyingWeightUnit__c, 'Kg', item.RecommendNetWeight__c) * prod.BuyingUnitPriceLocalKg__c;
                }
                if (item.TotalNetWeight__c > 0) {
                    item.PlanQuantity__c = 1;
                    item.TotalAmountOfBuying__c = Util.ConvertWeightToUnit(prod.BuyingWeightUnit__c, 'Kg', item.TotalNetWeight__c) * prod.BuyingUnitPriceLocalKg__c;
                }
                if (item.FinalNetWeight__c > 0) {
                    item.FinalQuantity__c = 1;
                    item.TotalAmountOfBuying__c = Util.ConvertWeightToUnit(prod.BuyingWeightUnit__c, 'Kg', item.FinalNetWeight__c) * prod.BuyingUnitPriceLocalKg__c;
                }
            }
            //Weight-based but order by quantity, i.e net weight is estimated on product
            else {
                if (item.PlanQuantity__c == null && item.Quantity__c > 0) {
                    item.PlanQuantity__c = item.Quantity__c;
                }
            }
            item.TotalAmountOfBuying__c = item.TotalAmountOfBuying__c == null ? 0 : item.TotalAmountOfBuying__c;
            item.AmountOfBuyingTax__c = item.TotalAmountOfBuying__c * prod.TaxRateBuying__c / 100;
            item.BuyingAmountInclTax__c = item.TotalAmountOfBuying__c + item.AmountOfBuyingTax__c;
        } 
    }
}