force-app/main/default/objects/ApplicationLine__c/ApplicationLine__c.object-meta.xml
<CustomObject>
    <label>Application Line</label>
    <nameField>
        <displayFormat>APLN-{000000}</displayFormat>
        <label>Application Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>APPLICATION LINE</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationLineCargo__c/ApplicationLineCargo__c.object-meta.xml
<CustomObject>
    <label>Application Line+Cargo</label>
    <nameField>
        <displayFormat>ALCG-{000000}</displayFormat>
        <label>APPLICATION LINE+CARGO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line+Cargo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLineCargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>APPLICATION LINE+CARGO</relationshipLabel>
    <relationshipName>Cargo</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>LastWosLineItem__r.WorkOrderID__r.Customer__r.Name</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddress__c</fullName>
    <label>Delivery Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Warehouse</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>CARGO (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>CargoDestinationWarehouse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/FacilityForManualOperation__c.field-meta.xml
<CustomField>
    <fullName>FacilityForManualOperation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility for Manual Operation</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>CARGO</relationshipLabel>
    <relationshipName>CARGO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight(KG)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/QrCodeImage__c.field-meta.xml
<CustomField>
    <fullName>QrCodeImage__c</fullName>
    <formula>IF( Text(Product__r.CodeImageType__c)=&quot;Barcode&quot;,IMAGE(&quot;https://www.scandit.com/wp-content/themes/bridge-child/wbq_barcode_gen.php?symbology=code128&amp;value=&quot;+Product__r.QR_Code__c +&quot;&amp;size=80&amp;ec=L&quot;,Product__r.QR_Code__c), IMAGE(&apos;https://chart.googleapis.com/chart?chs=100x100&amp;cht=qr&amp;chl=&apos; + Product__r.QR_Code__c, &apos;Product QR Code&apos; ))</formula>
    <label>QR Code Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/QuantityPerUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityPerUnit__c</fullName>
    <formula>Product__r.QuantityPerUnit__c</formula>
    <label>Quantity Per Unit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <inlineHelpText>= cubic inch/61023.744 or cubic feet/35.315 or cubic yard/1.308</inlineHelpText>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QRCodeImage__c.field-meta.xml
<CustomField>
    <fullName>QRCodeImage__c</fullName>
    <formula>IMAGE(&apos;https://chart.googleapis.com/chart?chs=75x75&amp;cht=qr&amp;chl=&apos; + QR_Code__c, &apos;Product QR Code&apos; )</formula>
    <inlineHelpText>Code Text will be automatically converted to QR image.</inlineHelpText>
    <label>QR Code Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QuantityPerUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityPerUnit__c</fullName>
    <label>QUANTITY PER UNIT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRODUCT(SUPPLIER)</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>WorkOrderDestinationWarehouseID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WorkOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/recordTypes/CrossDock.recordType-meta.xml
<RecordType>
    <fullName>CrossDock</fullName>
    <active>true</active>
    <description>After Cargo inbound, directly cargo outbound without storage</description>
    <label>Cross-Docking</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/recordTypes/ExpressCargoTransfer.recordType-meta.xml
<RecordType>
    <fullName>ExpressCargoTransfer</fullName>
    <active>true</active>
    <description>Express cargo for 1 client to manage inbound and outsound</description>
    <label>Express</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/recordTypes/Inbound.recordType-meta.xml
<RecordType>
    <fullName>Inbound</fullName>
    <active>true</active>
    <description>Cargo Inbound coming into warehouse and store in warehouse</description>
    <label>Inbound</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARRIER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-DESTINATION</relationshipLabel>
    <relationshipName>WorkOrderServiceDestination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/recordTypes/InboundReceiving.recordType-meta.xml
<RecordType>
    <fullName>InboundReceiving</fullName>
    <active>true</active>
    <description>Receiving for cargo inbound from customer</description>
    <label>Inbound Receiving</label>
</RecordType>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>WorkOrderService__r.WorkOrder__r.Customer__c</formula>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOSLineItem__c/fields/WorkOrderService__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderService__c</fullName>
    <label>WORK ORDER SERVICE</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>WMS W/O/S LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/L</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bale</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liquid</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, fineparticles(powders）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, granular particles(grains）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, large particles(nodules）</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Cage</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,non-protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Cask</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>Chest</fullName>
    </customValue>
    <customValue>
        <fullName>Coil</fullName>
    </customValue>
    <masterLabel>CARGO TYPE(UNIT)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/WMS_WO_PrintLabel.cls
public with sharing class WMS_WO_PrintLabel {
	public List<WosLineItem__c> Records{ get; set; }
	public Integer noOfRecords{get; set;}
	public Map<String, String> translations{get; set;}
        
	public WMS_WO_PrintLabel(ApexPages.StandardController con) {
		translations = new Map<String, String>();
		translations = getTranslationMap();
		WorkOrder__c record = [SELECT RecordType.DeveloperName FROM WorkOrder__c WHERE Id = :con.getRecord().Id];
		this.Records = new List<WosLineItem__c>();

		if (!(new Set<String>{ 'Inbound', 'CrossDock', 'ExpressCargoTransfer'}.contains(record.RecordType.DeveloperName))) {
			return;
		}
		Set<Id> cargoIds = new Set<Id>();
		List<WosLineItem__c> wosls = [
			SELECT Id,
				Cargo__r.Product__r.ProductName__c, Cargo__r.Product__r.UnitType__c, Cargo__r.Name, Cargo__r.QrCodeImage__c, 
				Cargo__r.Product__r.QuantityPerUnit__c, Cargo__r.Product__r.Measurement__c, Cargo__r.Product__r.GrossWeight__c, 
				Cargo__r.DeliveryAddress__c,WorkOrderService__r.WorkOrder__r.Customer__r.Name, WorkOrderService__r.DestinationWarehouse__r.Name, 
				WorkOrderService__r.DestinationWarehouse__r.FacilityName__c, Cargo__r.Product__r.CodeImageType__c,
				Cargo__r.Product__r.QR_Code__c
			FROM WosLineItem__c
			WHERE WorkOrderService__r.WorkOrder__c = :record.Id
				AND (
					(WorkOrderService__r.WorkOrder__r.RecordType.DeveloperName = 'Inbound' AND WorkOrderService__r.RecordType.DeveloperName = 'InboundReceiving')
					OR (WorkOrderService__r.DestinationWarehouse__c != null)
				)
		];
        for(WosLineItem__c wosl : wosls){
            if(!String.isBlank(wosl.Cargo__c)
              && !cargoIds.contains(wosl.Cargo__c)){
                this.Records.add(wosl); 
               cargoIds.add(wosl.Cargo__c);
            }
        }
         

	}
	public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {                
                setCon = new ApexPages.StandardSetController(Records);
                setCon.setPageSize(1000);  
                noOfRecords = setCon.getResultSize();
            }            
            return setCon;
        }
        set;
    }
    public List<WosLineItem__c> getWosLineItems(){
        return (List<WosLineItem__c>) setCon.getRecords();
	}
	public Map<String,String> getTranslationMap(){
        String langCode = UserInfo.getLanguage();
        Map<String, Object> translate = TranslationService.getByLanguage(langCode.substringBefore('_'));
        Map<String, String> translateMapResult = new Map<String, String>();
        for(String key : translate.keySet()){
            if(key.contains('summary_note') || key.contains('unit_translation')){
                translateMapResult.put(key.substringAfter('.'), (String)translate.get(key));
            }
            
        }
        return translateMapResult; 
    }
}