force-app/main/default/objects/ApplicationLine__c/ApplicationLine__c.object-meta.xml
<CustomObject>
    <label>Application Line</label>
    <nameField>
        <displayFormat>APLN-{000000}</displayFormat>
        <label>Application Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>APPLICATION LINE</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationLineCargo__c/ApplicationLineCargo__c.object-meta.xml
<CustomObject>
    <label>Application Line+Cargo</label>
    <nameField>
        <displayFormat>ALCG-{000000}</displayFormat>
        <label>APPLICATION LINE+CARGO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line+Cargo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLineCargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>APPLICATION LINE+CARGO</relationshipLabel>
    <relationshipName>Cargo</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <displayFormat>CG-{0000000000}</displayFormat>
        <label>Cargo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cargo__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>Cargo</relationshipLabel>
    <relationshipName>Cargo1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Cargo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/DeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddress__c</fullName>
    <label>Delivery Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ExpireDateSKUNumber__c.field-meta.xml
<CustomField>
    <fullName>ExpireDateSKUNumber__c</fullName>
    <formula>Product__r.SKUNumber__c &amp; LPAD(Text(Month(ExpiredDate__c)),2,&quot;0&quot;) &amp; Right(Text(Year(ExpiredDate__c)),2)</formula>
    <label>EXPIRE DATE SKU NUMBER</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ExpiredDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiredDate__c</fullName>
    <label>EXPIRED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/FacilityForManualOperation__c.field-meta.xml
<CustomField>
    <fullName>FacilityForManualOperation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility for Manual Operation</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>CARGO</relationshipLabel>
    <relationshipName>CARGO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight(KG)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>Cargos</relationshipLabel>
    <relationshipName>Cargos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ProductDetails__c.field-meta.xml
<CustomField>
    <fullName>ProductDetails__c</fullName>
    <formula>Text( Product__r.UnitType__c) &amp; &apos; of &apos; &amp; Text( Product__r.QuantityPerUnit__c ) &amp; &apos; &apos; &amp; Product__r.ProductName__c</formula>
    <label>Product Details</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/QrCodeImage__c.field-meta.xml
<CustomField>
    <fullName>QrCodeImage__c</fullName>
    <formula>IF( Text(Product__r.CodeImageType__c)=&quot;Barcode&quot;,IMAGE(&quot;https://www.scandit.com/wp-content/themes/bridge-child/wbq_barcode_gen.php?symbology=code128&amp;value=&quot;+Product__r.QR_Code__c +&quot;&amp;size=80&amp;ec=L&quot;,Product__r.QR_Code__c), IMAGE(&apos;https://chart.googleapis.com/chart?chs=100x100&amp;cht=qr&amp;chl=&apos; + Product__r.QR_Code__c, &apos;Product QR Code&apos; ))</formula>
    <label>QR Code Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cargo__c/fields/QuantityPerUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityPerUnit__c</fullName>
    <formula>Product__r.QuantityPerUnit__c</formula>
    <label>Quantity Per Unit</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BarCodeImage__c.field-meta.xml
<CustomField>
    <fullName>BarCodeImage__c</fullName>
    <inlineHelpText>Please take a picture of Barcode on product and attach image of Barcode.</inlineHelpText>
    <label>Barcode Photo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/CodeImageType__c.field-meta.xml
<CustomField>
    <fullName>CodeImageType__c</fullName>
    <label>Code Image Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CodeImageType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/FoodCategory__c.field-meta.xml
<CustomField>
    <fullName>FoodCategory__c</fullName>
    <label>FOOD CATEGORY</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>FoodCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/FoodSubCategory__c.field-meta.xml
<CustomField>
    <fullName>FoodSubCategory__c</fullName>
    <label>FOOD SUB-CATEGORY</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FoodCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>FoodSubCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <inlineHelpText>= cubic inch/61023.744 or cubic feet/35.315 or cubic yard/1.308</inlineHelpText>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IF(ISBLANK(External_ID__c), Name, External_ID__c)</formula>
    <inlineHelpText>Manufacture Code will be set as default. If there is no Manufacture Code, the Product ID will be set.</inlineHelpText>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QR_Image__c.field-meta.xml
<CustomField>
    <fullName>QR_Image__c</fullName>
    <formula>IF( Text(CodeImageType__c)=&quot;Barcode&quot;,
IMAGE(&quot;https://www.scandit.com/wp-content/themes/bridge-child/wbq_barcode_gen.php?symbology=code128&amp;value=&quot;+QR_Code__c +&quot;&amp;size=80&amp;ec=L&quot;,QR_Code__c), IMAGE(&apos;https://chart.googleapis.com/chart?chs=100x100&amp;cht=qr&amp;chl=&apos; + QR_Code__c, &apos;Product QR Code&apos; ))</formula>
    <inlineHelpText>Code Text will be automatically converted to either QR image or Barcode image base on Code Image Type.</inlineHelpText>
    <label>Code Image in Document</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QRCodeImage__c.field-meta.xml
<CustomField>
    <fullName>QRCodeImage__c</fullName>
    <formula>IMAGE(&apos;https://chart.googleapis.com/chart?chs=75x75&amp;cht=qr&amp;chl=&apos; + QR_Code__c, &apos;Product QR Code&apos; )</formula>
    <inlineHelpText>Code Text will be automatically converted to QR image.</inlineHelpText>
    <label>QR Code Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/QuantityPerUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityPerUnit__c</fullName>
    <label>QUANTITY PER UNIT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SKUNumber__c.field-meta.xml
<CustomField>
    <fullName>SKUNumber__c</fullName>
    <label>Product SKU Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRODUCT(SUPPLIER)</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/SKUNumber__c.field-meta.xml
<CustomField>
    <fullName>SKUNumber__c</fullName>
    <label>SKU NUMBER</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/recordTypes/CrossDock.recordType-meta.xml
<RecordType>
    <fullName>CrossDock</fullName>
    <active>true</active>
    <description>After Cargo inbound, directly cargo outbound without storage</description>
    <label>Cross-Docking</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/recordTypes/ExpressCargoTransfer.recordType-meta.xml
<RecordType>
    <fullName>ExpressCargoTransfer</fullName>
    <active>true</active>
    <description>Express cargo for 1 client to manage inbound and outsound</description>
    <label>Express</label>
</RecordType>

force-app/main/default/objects/WorkOrder__c/recordTypes/Inbound.recordType-meta.xml
<RecordType>
    <fullName>Inbound</fullName>
    <active>true</active>
    <description>Cargo Inbound coming into warehouse and store in warehouse</description>
    <label>Inbound</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/recordTypes/InboundReceiving.recordType-meta.xml
<RecordType>
    <fullName>InboundReceiving</fullName>
    <active>true</active>
    <description>Receiving for cargo inbound from customer</description>
    <label>Inbound Receiving</label>
</RecordType>

force-app/main/default/objects/WOSLineItem__c/WOSLineItem__c.object-meta.xml
<CustomObject>
    <label>W/O/S Line</label>
    <nameField>
        <displayFormat>WOSL-{00000000}</displayFormat>
        <label>WOS LINE ITEM ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WOSLineItem__c/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <referenceTo>Cargo__c</referenceTo>
    <relationshipLabel>WOS LINE ITEMS</relationshipLabel>
    <relationshipName>WosLineItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/CodeImageType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barcode</fullName>
    </customValue>
    <customValue>
        <fullName>QR code</fullName>
    </customValue>
    <masterLabel>Code Image Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FoodCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fruits</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetables</fullName>
    </customValue>
    <customValue>
        <fullName>Protein</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Grains</fullName>
    </customValue>
    <customValue>
        <fullName>Oils</fullName>
    </customValue>
    <masterLabel>FOOD CATEGORY</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FoodSubCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fruit</fullName>
    </customValue>
    <customValue>
        <fullName>Fruit Juice</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable Juice</fullName>
    </customValue>
    <customValue>
        <fullName>Meat</fullName>
    </customValue>
    <customValue>
        <fullName>Poultry</fullName>
    </customValue>
    <customValue>
        <fullName>Seafood</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Seeds</fullName>
    </customValue>
    <customValue>
        <fullName>Beans</fullName>
    </customValue>
    <customValue>
        <fullName>Fluid Milk</fullName>
    </customValue>
    <customValue>
        <fullName>Cheese</fullName>
    </customValue>
    <customValue>
        <fullName>Yogurt</fullName>
    </customValue>
    <customValue>
        <fullName>Ice Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Pudding</fullName>
    </customValue>
    <customValue>
        <fullName>Wheat</fullName>
    </customValue>
    <customValue>
        <fullName>Rice</fullName>
    </customValue>
    <customValue>
        <fullName>Oats</fullName>
    </customValue>
    <customValue>
        <fullName>Barley</fullName>
    </customValue>
    <customValue>
        <fullName>Cornmeal</fullName>
    </customValue>
    <customValue>
        <fullName>Nuts Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Olives Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Avocados Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Fish Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Cafe</fullName>
    </customValue>
    <masterLabel>FOOD SUB-CATEGORY</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/L</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bale</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liquid</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, fineparticles(powders）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, granular particles(grains）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, large particles(nodules）</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Cage</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,non-protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Cask</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>Chest</fullName>
    </customValue>
    <customValue>
        <fullName>Coil</fullName>
    </customValue>
    <masterLabel>CARGO TYPE(UNIT)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CargoStandardLabelController.cls
public with sharing class CargoStandardLabelController {
    public List<WosLineItem__c> Records{ get; set; }
    public Site_Custom_Settings__c setting{ get; set; }
    public Integer noOfRecords{get; set;}
    public Map<String, String> translations{get; set;}
    public CargoStandardLabelController() {
        translations = new Map<String, String>();
		translations = getTranslationMap();
        setting = Site_Custom_Settings__c.getOrgDefaults();
        String prmId = ApexPages.currentPage().getParameters().get('id');
        WorkOrder__c record = [SELECT RecordType.DeveloperName FROM WorkOrder__c WHERE Id = :prmId];
        this.Records = new List<WosLineItem__c>();

        if (!(new Set<String>{ 'Inbound', 'CrossDock', 'ExpressCargoTransfer'}.contains(record.RecordType.DeveloperName))) {
            return;
        }

        this.Records = [
        SELECT Id, Cargo__r.CargoType__c, Cargo__r.QuantityPerUnit__c, Cargo__r.ExpiredDate__c, Cargo__r.Product__r.FoodSubCategory__c, Cargo__r.ProductDetails__c,
            Cargo__r.Product__r.Name, Cargo__r.Product__r.ProductCategory__c, Cargo__r.Product__r.CodeImageType__c, Cargo__r.Product__r.BarCodeImage__c, 
            Cargo__r.Product__r.CosmeticCategory__c,Cargo__r.Product__r.FoodCategory__c, Cargo__r.Product__r.QR_Image__c,
            Cargo__r.Product__r.QRCodeImage__c, Cargo__r.Product__r.QR_Code__c,
            Cargo__r.Product__r.SKUNumber__c, Cargo__r.Product__r.ProductName__c, Cargo__r.Product__r.UnitType__c, Cargo__r.ExpireDateSKUNumber__c,
            Cargo__r.Name, Cargo__r.QrCodeImage__c, Cargo__r.Product__r.QuantityPerUnit__c, Cargo__r.Product__r.Measurement__c, 
            Cargo__r.Product__r.GrossWeight__c, Cargo__r.DeliveryAddress__c, WorkOrderService__r.WorkOrder__r.Customer__r.Name,
            WorkOrderService__r.DestinationWarehouse__r.Name, WorkOrderService__r.DestinationWarehouse__r.FacilityName__c
        FROM WosLineItem__c
        WHERE WorkOrderService__r.WorkOrder__c = :record.Id
            AND (
            (WorkOrderService__r.WorkOrder__r.RecordType.DeveloperName = 'Inbound' AND WorkOrderService__r.RecordType.DeveloperName = 'InboundReceiving')
            OR (WorkOrderService__r.DestinationWarehouse__c != null)
            )
        ];

    }

    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {                
                setCon = new ApexPages.StandardSetController(Records);
                setCon.setPageSize(1000);  
                noOfRecords = setCon.getResultSize();
            }            
            return setCon;
        }
        set;
    }
    public List<WosLineItem__c> getWosLineItems(){
        return (List<WosLineItem__c>) setCon.getRecords();
    }
    public Map<String,String> getTranslationMap(){
        String langCode = UserInfo.getLanguage();
        Map<String, Object> translate = TranslationService.getByLanguage(langCode.substringBefore('_'));
        Map<String, String> translateMapResult = new Map<String, String>();
        for(String key : translate.keySet()){
            if(key.contains('summary_note') || key.contains('unit_translation')){
                translateMapResult.put(key.substringAfter('.'), (String)translate.get(key));
            }
            
        }
        return translateMapResult; 
    }
}