force-app/main/default/objects/ApplicationLine__c/ApplicationLine__c.object-meta.xml
<CustomObject>
    <label>Application Line</label>
    <nameField>
        <displayFormat>APLN-{000000}</displayFormat>
        <label>Application Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>APPLICATION LINE</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationLine__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/ConnectWOProduct__c/ConnectWOProduct__c.object-meta.xml
<CustomObject>
    <label>W/O+Product</label>
    <nameField>
        <displayFormat>WP-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/W/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectWOProduct__c/fields/FinalQuantity__c.field-meta.xml
<CustomField>
    <fullName>FinalQuantity__c</fullName>
    <label>FINAL QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>W/O+PRODUCT</relationshipLabel>
    <relationshipName>CONNECT_WORK_ORDER_PRODUCT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>ProductID__r.ProductName__c</formula>
    <label>PRODUCT NAME</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectWOProduct__c/fields/WorkOrderID__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderID__c</fullName>
    <label>WORK ORDER ID</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipName>CONNECT_WORK_ORDER_PRODUCT</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>SELLING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/ActualDate__c.field-meta.xml
<CustomField>
    <fullName>ActualDate__c</fullName>
    <label>ACTUAL DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>WorkOrderDestinationWarehouseID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/FinalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>FinalNetWeight__c</fullName>
    <label>FINAL NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/FinalQuantity__c.field-meta.xml
<CustomField>
    <fullName>FinalQuantity__c</fullName>
    <label>FINAL QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>WorkOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/SalesOrderID__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GOODS SALES ORDER ID</label>
    <referenceTo>SALES_ORDER__c</referenceTo>
    <relationshipLabel>WORK ORDER</relationshipLabel>
    <relationshipName>SalesOrderID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <description>Transfer Cargo for 1 client to another warehouse</description>
    <label>Single Transfer</label>
</RecordType>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-DESTINATION</relationshipLabel>
    <relationshipName>WorkOrderServiceDestination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/FinalQuantity__c.field-meta.xml
<CustomField>
    <fullName>FinalQuantity__c</fullName>
    <label>FINAL QUANTITY(DELETED)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/recordTypes/TransferDispatch.recordType-meta.xml
<RecordType>
    <fullName>TransferDispatch</fullName>
    <active>true</active>
    <description>Dispatch for cargo transferred to another location</description>
    <label>Transfer Dispatch</label>
</RecordType>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/L</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bale</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liquid</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, fineparticles(powders）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, granular particles(grains）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, large particles(nodules）</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Cage</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,non-protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Cask</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Charter</fullName>
    </customValue>
    <customValue>
        <fullName>Chest</fullName>
    </customValue>
    <customValue>
        <fullName>Coil</fullName>
    </customValue>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <masterLabel>CARGO TYPE(UNIT)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/WeightUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>WEIGHT UNIT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendCargoAPI.cls
@RestResource(urlMapping='/api/Cargo')
global with sharing class SendCargoAPI {
    @HttpGet
    global static String doGetCargo() {
        try{
            Date processDate = System.today();
            if (RestContext.request.params.containsKey('processdate')) {
                processDate = Date.parse(RestContext.request.params.get('processdate'));
            }
            return new SendCargoApiService().execute(processDate);
        } catch(Exception ex){
            // Create error
            clofor_com_cfs__Call_Out_Error__c error = CreateData.createError('CARGO API');
            error.clofor_com_cfs__Error_Content__c 	= ex.getMessage();
            error.clofor_com_cfs__Error_Content__c 	+= ex.getLineNumber();
            error.clofor_com_cfs__Error_Content__c 	+= ex.getStackTraceString();
            error.clofor_com_cfs__Error_Content__c 	+= ex.getTypeName();
		    FlsService.doUpsert(error);
            return 'Error';
        }
    }

    public class SendCargoApiService {
        public String execute(Date processDate) {
            List<Map<String, Object>> response = new List<Map<String, Object>>();
            for(WorkOrder__c wo :[                
                SELECT Id, Name, SalesOrderId__c, WarehouseId__r.Name, WarehouseId__r.FacilityName__c, DestinationWarehouse__r.FacilityName__c, DestinationWarehouse__r.Name, (
                    SELECT Id, FinalQuantity__c, FinalNetWeight__c,
                        ProductID__c, ProductID__r.Name, ProductID__r.ProductName__c, ProductID__r.UnitType__c, ProductID__r.BillingType__c, ProductID__r.WeightUnit__c
                    FROM CONNECT_WORK_ORDER_PRODUCT__r
                    WHERE ProductID__r.BillingType__c != NULL 
                        AND ( 
                            (ProductID__r.BillingType__c = 'Unit' AND FinalQuantity__c != NULL) OR 
                            (ProductID__r.BillingType__c = 'Weight' AND FinalNetWeight__c != NULL AND ProductID__r.WeightUnit__c != NULL )
                        )
                )
                FROM WorkOrder__c
                WHERE SalesOrderId__c != NULL
                    AND RecordType.DeveloperName = 'Transfer'
                    AND ActualDate__c = :processDate
            ]) {
                if (wo.CONNECT_WORK_ORDER_PRODUCT__r.isEmpty()) {
                    continue;
                }
                List<Map<String, Object>> products = new List<Map<String, Object>>();
			    for (ConnectWOProduct__c item : wo.CONNECT_WORK_ORDER_PRODUCT__r) {
                    Decimal weight = Util.ConvertWeightToBaseUnit(item.ProductID__r.WeightUnit__c, item.FinalNetWeight__c);
                    products.add(new Map<String, Object> {
                        'ProPricingId' => item.ProductID__r.Name,
                        'ProductUnitType' => item.ProductID__r.UnitType__c,
                        'ProductTotalQuantityPerUnit' => item.ProductID__r.BillingType__c == 'Unit' ? item.FinalQuantity__c : weight,
                        'ProductName' => item.ProductID__r.ProductName__c,
                        'ProductNetWeight' => weight
                    });
                }
                response.add(new Map<String, Object> {
                    'Warehouse' => new Map<String, Object> {
                        'WorkOrderName' => wo.Name,
                        'FacilityName' => wo.DestinationWarehouse__r.FacilityName__c,
                        'DestinationWarehouseName' => wo.DestinationWarehouse__r.Name
                    },
                    'Product' => products
                });
            }
            return JSON.serialize(response);
        }
    }

    /*
	@HttpGet
    global static String doGetCargo() {
        try{
            Date currentDate = System.today();
            List<clofor_com_cfs__Cargo__c> lstCargo = new List<clofor_com_cfs__Cargo__c>();
            lstCargo = [SELECT Id 
                       			,clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.clofor_com_cfs__DestinationWarehouse__r.clofor_com_cfs__FacilityName__c
                                ,clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.clofor_com_cfs__DestinationWarehouse__r.Name
                                ,clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.Name
                                ,clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderService__r.Name
                                ,clofor_com_cfs__Product__r.Name
                                ,clofor_com_cfs__Product__r.clofor_com_cfs__QuantityPerUnit__c
                                ,clofor_com_cfs__Product__r.clofor_com_cfs__ProductName__c
                                ,clofor_com_cfs__Product__r.clofor_com_cfs__UnitType__c
                                ,clofor_com_cfs__Product__r.clofor_com_cfs__GrossWeight__c
                        		,clofor_com_cfs__Product__r.clofor_com_cfs__NETWeightGram__c
                                ,clofor_com_cfs__ManufacturedDate__c
                                ,clofor_com_cfs__ExpiredDate__c
                        		,clofor_com_cfs__Product__c
                        		,clofor_com_cfs__LastWosLineItem__c
                        		,clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderService__c
                       FROM clofor_com_cfs__Cargo__c
                       WHERE clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderService__r.clofor_com_cfs__Status__c = 'Completed'
                       AND clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__CargoStatus__c = 'Completed'
                       AND clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderService__r.RecordType.DeveloperName = 'TransferDispatch'
                       AND clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.clofor_com_cfs__ActualDate__c =: currentDate];
        	Map<String, JsonObject> mapJson = new Map<String, JsonObject>();
            for(clofor_com_cfs__Cargo__c cargo : lstCargo){
                String strKey = '';
                strKey += cargo.clofor_com_cfs__Product__c;
                strKey += cargo.clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderService__c;
                if(mapJson.containsKey(strKey)){
                    if(cargo.clofor_com_cfs__Product__r.clofor_com_cfs__QuantityPerUnit__c != null){
                        mapJson.get(strKey).ProductTotalQuantityPerUnit += cargo.clofor_com_cfs__Product__r.clofor_com_cfs__QuantityPerUnit__c;
                    }
                    if(cargo.clofor_com_cfs__Product__r.clofor_com_cfs__NETWeightGram__c != null){
                        mapJson.get(strKey).ProductNetWeight += cargo.clofor_com_cfs__Product__r.clofor_com_cfs__NETWeightGram__c;
                    }
                }else{
                   mapJson.put(strKey, new JsonObject(cargo));
                }
            }
            
            Map<String, jsonDataIntergrate> mapDataIntegration = new Map<String, jsonDataIntergrate>();
            for(JsonObject jsObject : mapJson.values()){
                JsonProduct  jsPro = new JsonProduct(jsObject);
                if(mapDataIntegration.containsKey(jsObject.WorkOrderServiceName)){
                    mapDataIntegration.get(jsObject.WorkOrderServiceName).Product.add(jsPro);
                }else{
                    jsonDataIntergrate jsData = new jsonDataIntergrate(jsObject);
                    jsData.Product.add(jsPro);
                    mapDataIntegration.put(jsObject.WorkOrderServiceName, jsData);
                }
            }
            return System.JSON.serialize(mapDataIntegration.values());
        }catch(Exception ex){
            // Create error
            clofor_com_cfs__Call_Out_Error__c error = CreateData.createError('CARGO API');
            error.clofor_com_cfs__Error_Content__c 	= ex.getMessage();
            error.clofor_com_cfs__Error_Content__c 	+= ex.getLineNumber();
            error.clofor_com_cfs__Error_Content__c 	+= ex.getStackTraceString();
            error.clofor_com_cfs__Error_Content__c 	+= ex.getTypeName();
            upsert error;
            return 'Error';
        }
    }
    Private class JsonObject{
		Private String  FacilityName{get; set;}
        Private String  DestinationWarehouseName{get; set;}
        Private String  WorkOrderName{get; set;}
		Private String  WorkOrderServiceName{get; set;}
		Private String  ProPricingId{get; set;}
      	Private Decimal ProductTotalQuantityPerUnit{get; set;}
        Private String  ProductName{get; set;}
        Private String  ProductUnitType{get; set;}
        Private Decimal ProductGrossWeight{get; set;}
        Private Decimal ProductNetWeight{get; set;}
        Private Date  	CargoManufacturedDate{get; set;}
        Private Date  	CargoExpiredDate{get; set;}
        private JsonObject(clofor_com_cfs__Cargo__c recCargo){
           	FacilityName					= recCargo.clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.clofor_com_cfs__DestinationWarehouse__r.clofor_com_cfs__FacilityName__c ;
            DestinationWarehouseName		= recCargo.clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.clofor_com_cfs__DestinationWarehouse__r.Name ;
            WorkOrderName					= recCargo.clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderID__r.Name ;
            WorkOrderServiceName			= recCargo.clofor_com_cfs__LastWosLineItem__r.clofor_com_cfs__WorkOrderService__r.Name;
            ProPricingId					= recCargo.clofor_com_cfs__Product__r.Name;
            ProductTotalQuantityPerUnit		= recCargo.clofor_com_cfs__Product__r.clofor_com_cfs__QuantityPerUnit__c;
            ProductName						= recCargo.clofor_com_cfs__Product__r.clofor_com_cfs__ProductName__c;
            ProductUnitType					= recCargo.clofor_com_cfs__Product__r.clofor_com_cfs__UnitType__c;
            ProductGrossWeight				= recCargo.clofor_com_cfs__Product__r.clofor_com_cfs__GrossWeight__c;
            CargoManufacturedDate			= recCargo.clofor_com_cfs__ManufacturedDate__c;
            CargoExpiredDate				= recCargo.clofor_com_cfs__ExpiredDate__c;
            ProductNetWeight 				= recCargo.clofor_com_cfs__Product__r.clofor_com_cfs__NETWeightGram__c;
		}
	}
    Private class JsonProduct{
        Private String ProPricingId{get; set;}
        Private String ProductName{get; set;}
        Private String ProductUnitType{get; set;}
        Private Decimal ProductTotalQuantityPerUnit{get; set;}
        // Private Decimal ProductGrossWeight{get; set;}
        Private Decimal ProductNetWeight{get; set;}
        //Private Date 	CargoManufacturedDate{get; set;}
        //Private Date 	CargoExpiredDate{get; set;}
        Private JsonProduct(JsonObject js){
            proPricingId 				= js.proPricingId;
        	ProductName					= js.ProductName;
        	ProductUnitType				= js.ProductUnitType;
            ProductTotalQuantityPerUnit	= js.ProductTotalQuantityPerUnit;
            //ProductGrossWeight		= js.ProductGrossWeight;
        	ProductNetWeight			= js.ProductNetWeight;
        	//CargoManufacturedDate		= js.CargoManufacturedDate;
            //CargoExpiredDate			= js.CargoExpiredDate;
        }
    }
    
    Private class jsonWarehouse{
        Private String  FacilityName{get; set;}
        Private String  DestinationWarehouseName{get; set;}
        Private String  WorkOrderName{get; set;}
        Private String  WorkOrderServiceName{get; set;}
        Private jsonWarehouse(JsonObject js){
            FacilityName 				= js.FacilityName;
        	DestinationWarehouseName 	= js.DestinationWarehouseName;
            WorkOrderName 				= js.WorkOrderName;
        	WorkOrderServiceName 		= js.WorkOrderServiceName;
        }
    }
    
    Private class jsonDataIntergrate{
        Private jsonWarehouse Warehouse{get; set;}
        Private List<JsonProduct> Product{get; set;}
        Private jsonDataIntergrate(JsonObject js){
            Warehouse = new jsonWarehouse(js);
            Product = new List<JsonProduct>();
        }
    }
    */
}