force-app/main/default/objects/Contact/fields/MailS__c.field-meta.xml
<CustomField>
    <fullName>MailS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the contact person do not want to receive CloTra automail, check the box and CloTra automail delivery will be stopped.</inlineHelpText>
    <label>DO NOT WANT CARGO TRACKING EMAIL SERVICE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/CustmerInCharge__c.field-meta.xml
<CustomField>
    <fullName>CustmerInCharge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>PIC OF CUSTOMER</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Field1__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>F/TMS S/O (PIC OF CUSTOMER)</relationshipLabel>
    <relationshipName>CIC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Customer_Do_Not_Disturb_State__c.field-meta.xml
<CustomField>
    <fullName>Customer_Do_Not_Disturb_State__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Store Customer selection for &quot;DO NOT WANT TO EMAIL ANNOUNCE&quot; option (to whether want to receive email notification from HBL or not). 
This field is required because of limitation from SF for number of relationships in an object (15 relationships).</description>
    <label>Customer Do Not Disturb State</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Partner_Do_Not_Disturb_State__c.field-meta.xml
<CustomField>
    <fullName>Partner_Do_Not_Disturb_State__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Store Partner selection for &quot;DO NOT WANT TO EMAIL ANNOUNCE&quot; option (to whether want to receive email notification from HBL or not).
This field is required because of limitation from SF for number of relationships in an object (15 relationships).</description>
    <label>Partner Do Not Disturb State</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PartnerRep__c.field-meta.xml
<CustomField>
    <fullName>PartnerRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PIC OF PARTNER</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Partner__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>F/TMS S/O (PIC OF PARTNER)</relationshipLabel>
    <relationshipName>Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler extends AbstractTriggerHandler {
    private List<CustomObject1__c> toBeUpdatedShipments = new List<CustomObject1__c>();
    private Map<Id, Set<CustomObject1__c>> mapShipments = new Map<Id, Set<CustomObject1__c>>();
    
    public override String getHandlerName() {
        return 'ContactTriggerHandler';
    }
    
    public override void bulkAfter() {
        loadReferenceShipments(Trigger.newMap);
    }
    
    public override void afterUpdate(SObject oldSo, SObject so) {
        Contact oldContact = (Contact) oldSo;
        Contact newContact = (Contact) so;

        if (oldContact.MailS__c != newContact.MailS__c) {
            updateNotifyCustomersFlag(newContact.Id, newContact.MailS__c);
        }
    }
    
    public override void andFinally() {
        if (toBeUpdatedShipments.size() > 0) {
            try {
                FlsService.doUpdate(toBeUpdatedShipments);
            } catch(Exception e) {
            }
        }
    }
    
    private void updateNotifyCustomersFlag(Id contactId, Boolean flag) {
        Set<CustomObject1__c> shipments = mapShipments.get(contactId);
        
        if (shipments != null && shipments.size() > 0) {
            for (CustomObject1__c shipment : shipments) {
                if (shipment.CustmerInCharge__c == contactId) {
                    shipment.Customer_Do_Not_Disturb_State__c = flag;
                }
                
                if (shipment.PartnerRep__c == contactId) {
                    shipment.Partner_Do_Not_Disturb_State__c = flag;
                }

                toBeUpdatedShipments.add(shipment);
            }
        }
    }
    
    private void loadReferenceShipments(Map<Id, SObject> contacts) {
        Set<Id> contactIds = contacts.keySet();

        for (List<CustomObject1__c> shipments : [SELECT Partner_Do_Not_Disturb_State__c, Customer_Do_Not_Disturb_State__c,
                                                 PartnerRep__c, CustmerInCharge__c 
                                                 FROM CustomObject1__c 
                                                 WHERE PartnerRep__c IN :contactIds OR CustmerInCharge__c IN :contactIds]) {
            for (CustomObject1__c shipment : shipments) {
                addShipmentToMap(mapShipments, shipment, shipment.CustmerInCharge__c);
                addShipmentToMap(mapShipments, shipment, shipment.PartnerRep__c);
            }
        }
    }
    
    private void addShipmentToMap(Map<Id, Set<CustomObject1__c>> mapShipments, CustomObject1__c shipment, 
                                  Id contactId) {
		if (contactId != null) {
            if (mapShipments.containsKey(contactId)) {
                mapShipments.get(contactId).add(shipment);
            } else {
                Set<CustomObject1__c> shipments = new Set<CustomObject1__c>();
                shipments.add(shipment);
                mapShipments.put(contactId, shipments);
            }
		}
    }
}