force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ACTIVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>ADDRESS</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/CapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>CapacityCBM__c</fullName>
    <label>MAX STORAGE CAPACITY(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/CapacityKG__c.field-meta.xml
<CustomField>
    <fullName>CapacityKG__c</fullName>
    <label>MAX STORAGE CAPACITY(KG)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/ChargeType__c.field-meta.xml
<CustomField>
    <fullName>ChargeType__c</fullName>
    <label>CHARGE TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ChargeType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/FacilityImage__c.field-meta.xml
<CustomField>
    <fullName>FacilityImage__c</fullName>
    <label>FACILITY IMAGE</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>FACILITY NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/FacilityType__c.field-meta.xml
<CustomField>
    <fullName>FacilityType__c</fullName>
    <label>FACILITY TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FacilityType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/ItemType__c.field-meta.xml
<CustomField>
    <fullName>ItemType__c</fullName>
    <label>ITEM TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ItemType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/OwnerCompanyName__c.field-meta.xml
<CustomField>
    <fullName>OwnerCompanyName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OWNER COMPANY NAME</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FACILITY</relationshipLabel>
    <relationshipName>FACILITY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/OwnershipType__c.field-meta.xml
<CustomField>
    <fullName>OwnershipType__c</fullName>
    <label>OWNERSHIP TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OwnershipType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/RollUpActualOccupiedCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>RollUpActualOccupiedCapacityCBM__c</fullName>
    <label>OCCUPIED CAPACITY(CBM) INCLUDE PLANNED</label>
    <summarizedField>LOCATOR__c.ActualOccupiedCapacityCBM__c</summarizedField>
    <summaryFilterItems>
        <field>LOCATOR__c.LocationAreaType__c</field>
        <operation>equals</operation>
        <value>Storage Area</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>LOCATOR__c.LocatorLayer__c</field>
        <operation>equals</operation>
        <value>Floor Layer</value>
    </summaryFilterItems>
    <summaryForeignKey>LOCATOR__c.WarehouseID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/RollUpActualOccupiedCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>RollUpActualOccupiedCapacityKG__c</fullName>
    <label>OCCUPIED CAPACITY(KG) INCLUDE PLANNED</label>
    <summarizedField>LOCATOR__c.ActualOccupiedCapacityKG__c</summarizedField>
    <summaryFilterItems>
        <field>LOCATOR__c.LocationAreaType__c</field>
        <operation>equals</operation>
        <value>Storage Area</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>LOCATOR__c.LocatorLayer__c</field>
        <operation>equals</operation>
        <value>Floor Layer</value>
    </summaryFilterItems>
    <summaryForeignKey>LOCATOR__c.WarehouseID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/StorageType__c.field-meta.xml
<CustomField>
    <fullName>StorageType__c</fullName>
    <label>STORAGE TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StorageType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/WarehoueType__c.field-meta.xml
<CustomField>
    <fullName>WarehoueType__c</fullName>
    <label>WAREHOUSE TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WarehoueType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOCATOR__c/LOCATOR__c.object-meta.xml
<CustomObject>
    <label>Locator</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>LOCATOR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ACTIVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/ActualAvailableCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>ActualAvailableCapacityCBM__c</fullName>
    <formula>CapacityCBM__c - ActualOccupiedCapacityCBM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AVAILABLE CAPACITY(CBM) INCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/ActualAvailableCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>ActualAvailableCapacityKG__c</fullName>
    <formula>CapacityKG__c - ActualOccupiedCapacityKG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AVAILABLE CAPACITY(KG) INCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/ActualOccupiedCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>ActualOccupiedCapacityCBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (CBM) INCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/ActualOccupiedCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>ActualOccupiedCapacityKG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (KG) INCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BUYER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LACATOR (BUYER)</relationshipLabel>
    <relationshipName>LacatorBuyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>CapacityCBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MAX CAPACITY(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CapacityKG__c.field-meta.xml
<CustomField>
    <fullName>CapacityKG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MAX CAPACITY(KG)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CurrentAvailableCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>CurrentAvailableCapacityCBM__c</fullName>
    <formula>CapacityCBM__c - CurrentOccupiedCapacityCBM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AVAILABLE CAPACITY(CBM) EXCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CurrentAvailableCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>CurrentAvailableCapacityKG__c</fullName>
    <formula>CapacityKG__c - CurrentOccupiedCapacityKG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AVAILABLE CAPACITY(KG) EXCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CurrentOccupiedCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>CurrentOccupiedCapacityCBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (CBM) EXCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/CurrentOccupiedCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>CurrentOccupiedCapacityKG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OCCUPIED CAPACITY (KG) EXCLUDE PLANNED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/FastSlowClassification__c.field-meta.xml
<CustomField>
    <fullName>FastSlowClassification__c</fullName>
    <inlineHelpText>FSN
F:Fast-moving
S:Slow-moving
N:Non-moving</inlineHelpText>
    <label>FAST/SLOW CLASSIFICATION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FastSlowClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/LocatorCode__c.field-meta.xml
<CustomField>
    <fullName>LocatorCode__c</fullName>
    <formula>IF(OR(ISBLANK(FloorCode__c),FloorCode__c == &quot;F&quot;),&quot;F00&quot;,FloorCode__c) + &quot;-&quot; +
IF(OR(ISBLANK(AreaCode__c), AreaCode__c == &quot;A&quot;),&quot;A00&quot;,AreaCode__c) + &quot;-&quot; +
IF(OR(ISBLANK(SectionCode__c), SectionCode__c == &quot;S&quot;),&quot;S00&quot;,SectionCode__c)+ &quot;-&quot; +
IF(OR(ISBLANK(Rack__c), Rack__c  == &quot;R&quot;),&quot;R00&quot;,Rack__c)+ &quot;-&quot; +
IF(OR(ISBLANK(Level__c), Level__c == &quot;L&quot;),&quot;L00&quot;,Level__c)</formula>
    <label>LOCATOR CODE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/LocatorDescription__c.field-meta.xml
<CustomField>
    <fullName>LocatorDescription__c</fullName>
    <label>LOCATOR DESCRIPTION</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/LocatorLayer__c.field-meta.xml
<CustomField>
    <fullName>LocatorLayer__c</fullName>
    <label>LOCATOR LAYER</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Floor Layer</fullName>
            </value>
            <value>
                <fullName>Area Layer</fullName>
            </value>
            <value>
                <fullName>Section Layer</fullName>
            </value>
            <value>
                <fullName>Rack Layer</fullName>
            </value>
            <value>
                <fullName>Level Layer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/ParentLocator__c.field-meta.xml
<CustomField>
    <fullName>ParentLocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PARENT LOCATOR</label>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>CHILD LOCATOR</relationshipLabel>
    <relationshipName>LocatorHierarchy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/SharedCapacityCBM__c.field-meta.xml
<CustomField>
    <fullName>SharedCapacityCBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Shared Capacity (CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/SharedCapacityKG__c.field-meta.xml
<CustomField>
    <fullName>SharedCapacityKG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Shared Capacity (KG)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SUPPLIER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LACATOR (SUPPLIER)</relationshipLabel>
    <relationshipName>LacatorSupplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TENANT</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LACATOR</relationshipLabel>
    <relationshipName>LACATOR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>LOCATOR</relationshipLabel>
    <relationshipName>Locator</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/ChargeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Batch</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
        <default>true</default>
        <label>CBM</label>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Pack</fullName>
    </customValue>
    <customValue>
        <fullName>Packet</fullName>
    </customValue>
    <customValue>
        <fullName>Pallet</fullName>
    </customValue>
    <customValue>
        <fullName>Piece</fullName>
    </customValue>
    <customValue>
        <fullName>RTON</fullName>
    </customValue>
    <customValue>
        <fullName>Shipment</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>CHARGE TYPE</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/FacilityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Warehouse</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Warehouse</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Warehouse(Bike)</fullName>
    </customValue>
    <customValue>
        <fullName>Distribution Center</fullName>
    </customValue>
    <customValue>
        <fullName>Terminal</fullName>
    </customValue>
    <customValue>
        <fullName>Port</fullName>
    </customValue>
    <customValue>
        <fullName>Yard</fullName>
    </customValue>
    <customValue>
        <fullName>ICD</fullName>
    </customValue>
    <customValue>
        <fullName>Store</fullName>
    </customValue>
    <customValue>
        <fullName>Office Building</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>FACILITY TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FastSlowClassification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A:Fast-moving</fullName>
    </customValue>
    <customValue>
        <fullName>B:Slow-moving</fullName>
    </customValue>
    <customValue>
        <fullName>C:Non-moving</fullName>
    </customValue>
    <customValue>
        <fullName>B:Normal</fullName>
        <isActive>false</isActive>
        <label>B:Normal</label>
    </customValue>
    <masterLabel>FAST/SLOW CLASSIFICATION</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ItemType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General merchandise</fullName>
    </customValue>
    <customValue>
        <fullName>Household/furniture</fullName>
    </customValue>
    <customValue>
        <fullName>Special commodity</fullName>
    </customValue>
    <customValue>
        <fullName>Cold storage</fullName>
    </customValue>
    <masterLabel>ITEM TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OwnershipType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Public</fullName>
    </customValue>
    <customValue>
        <fullName>Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>OWNERSHIP TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SKU.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pallet</fullName>
    </customValue>
    <customValue>
        <fullName>Batch</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Pack</fullName>
    </customValue>
    <customValue>
        <fullName>Piece</fullName>
    </customValue>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Tray</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <masterLabel>SKU</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/StorageType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General storage area</fullName>
    </customValue>
    <customValue>
        <fullName>High rack storage area</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed bin storage area</fullName>
    </customValue>
    <customValue>
        <fullName>Rack storage area</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk storage area</fullName>
    </customValue>
    <masterLabel>STORAGE TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WarehoueType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Storage</fullName>
        <default>true</default>
        <label>Storage</label>
    </customValue>
    <customValue>
        <fullName>Bonded</fullName>
    </customValue>
    <customValue>
        <fullName>CFS</fullName>
    </customValue>
    <customValue>
        <fullName>Heavy Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Temperature Controlled</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>WAREHOUSE TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LocatorMapViewController.cls
public with sharing class LocatorMapViewController {
    public static Id warehouseId {get; set;}
    public Facility__c currentWarehouse {get; set;}
    public Boolean isDisplayWarehouseList{get; set;}
    public List<Facility__c> listWarehouse {get; set;}
    public List<LOCATOR__c>  listLocator{get; set;}
    public LOCATOR__c  parentLocator{get; set;}
    public Boolean isParentsSelected {get; set;}
    public List<LOCATOR__c> listTree{get; set;}
    public WapperLocator locatorSearch{get; set;}
    public String query {get; set;}
    public Boolean isDisplayResultSearch{get; set;}
    public List<LOCATOR__c> resultSearchLocator{get; set;}

    //==================Pagination variable===============
    Public Integer sizeSearch{get;set;}
    public Integer sizeChildLocator{get;set;}
    public Integer sizeWarehouse{get;set;}
    public List<SelectOption> paginationSizeOptions{get;set;}

    public Integer indexTree{get;set;}
    public LocatorMapViewController(){
        isDisplayResultSearch = false;
        locatorSearch = new WapperLocator();
        isDisplayWarehouseList = false;
        isParentsSelected = false;
        resultSearchLocator = new List<LOCATOR__c>();
        parentLocator = new LOCATOR__c();
        listLocator = new List<LOCATOR__c>();

        warehouseId = ApexPages.currentPage().getParameters().get('warehouseId');
        listTree = new List<LOCATOR__c>();
        indexTree = 0;
        sizeSearch=10;
        sizeChildLocator=10;
        sizeWarehouse=10;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));
        if(	!String.isBlank(warehouseId)){
            currentWarehouse = getWarehouseInfomationById(warehouseId);
        }else{
            isDisplayWarehouseList = true;
            listWarehouse = [SELECT 
                               	Id, 
                               	FacilityName__c,
                                FacilityImage__c,
                                FacilityType__c,
                                WarehoueType__c,
                                CapacityCBM__c,
                                CapacityKG__c,
                                ChargeType__c,
                                StorageType__c,
								                  Name
                               FROM 
                               	Facility__c
                               WHERE Active__c = true
                               Limit 50000];
        }
    }

    public void doInit(){
    warehouseId = null;
    isDisplayResultSearch = false;
    currentWarehouse = new Facility__c();
    isDisplayWarehouseList = true;
    listLocator = new List<LOCATOR__c>();
    parentLocator = new LOCATOR__c();
    isParentsSelected = false;
    listTree = new List<LOCATOR__c>();
    indexTree = 0;
    listWarehouse = [SELECT 
                                Id, 
                                FacilityName__c,
                                FacilityImage__c,
                                FacilityType__c,
                                WarehoueType__c,
                                CapacityCBM__c,
                                CapacityKG__c,
                                ChargeType__c,
                                StorageType__c,
                                  Name
                               FROM 
                                Facility__c
                               WHERE Active__c = true
                               Limit 50000];
    setWarehouseList = new ApexPages.StandardSetController(listWarehouse);
    setWarehouseList.setPageSize(sizeWarehouse);
    setWarehouseList.setPageNumber(1);
    }
    
    public void viewLocators(){
      isDisplayWarehouseList = false;
      isDisplayResultSearch = false;
      warehouseId = ApexPages.currentPage().getParameters().get('warehouseId');
      String locatorParentId = ApexPages.currentPage().getParameters().get('locatorParentId');
      String indexTreeParam = ApexPages.currentPage().getParameters().get('indexTreeParam');
      String locatorLayer = ApexPages.currentPage().getParameters().get('locatorLayer');
      if(!String.isBlank(locatorParentId)){
        isParentsSelected = true;
        parentLocator = getLocatorById(locatorParentId);
        if(!String.isBlank(indexTreeParam)){
          //indexTree = Integer.valueOf(indexTreeParam);
          Integer index = Integer.valueOf(indexTreeParam);
          if(index == 0){
            listTree = new List<LOCATOR__c>();
          }else{
            if(indexTree < index){

                listTree.add(parentLocator); 

              }else{
                for(Integer i = listTree.size()-1; i > Integer.valueOf(indexTreeParam) - 1; i--){

                  listTree.remove(i);
                }
              }

          }

          indexTree = index;

        }else{
          if(!String.isBlank(locatorLayer)){
              if(locatorLayer == 'Floor Layer'){
                listTree.add(parentLocator);
              }
              if(locatorLayer == 'Area Layer'){
                LOCATOR__c locatorFloorLayer = getLocatorById(parentLocator.ParentLocator__c);
                listTree.add(locatorFloorLayer);
                listTree.add(parentLocator);
              }
               if(locatorLayer == 'Section Layer'){
                LOCATOR__c locatorAreaLayer = getLocatorById(parentLocator.ParentLocator__c);
                LOCATOR__c locatorFloorLayer = getLocatorById(locatorAreaLayer.ParentLocator__c);
                listTree.add(locatorFloorLayer);
                listTree.add(locatorAreaLayer);
                listTree.add(parentLocator);
              }
              if(locatorLayer == 'Rack Layer'){
                LOCATOR__c locatorSectionLayer = getLocatorById(parentLocator.ParentLocator__c);
                LOCATOR__c locatorAreaLayer = getLocatorById(locatorSectionLayer.ParentLocator__c);
                LOCATOR__c locatorFloorLayer = getLocatorById(locatorAreaLayer.ParentLocator__c);
                listTree.add(locatorFloorLayer);
                listTree.add(locatorAreaLayer);
                listTree.add(locatorSectionLayer);
                listTree.add(parentLocator);
              }
              if(locatorLayer == 'Level Layer'){
                LOCATOR__c locatorRackLayer = getLocatorById(parentLocator.ParentLocator__c);
                LOCATOR__c locatorSectionLayer = getLocatorById(locatorRackLayer.ParentLocator__c);
                LOCATOR__c locatorAreaLayer = getLocatorById(locatorSectionLayer.ParentLocator__c);
                LOCATOR__c locatorFloorLayer = getLocatorById(locatorAreaLayer.ParentLocator__c);
                listTree.add(locatorFloorLayer);
                listTree.add(locatorAreaLayer);
                listTree.add(locatorSectionLayer);
                listTree.add(locatorRackLayer);
                listTree.add(parentLocator);
              }
              
            }else{
              listTree.add(parentLocator);
              
            }
            indexTree = listTree.size();
          
        }

      }else{
        locatorParentId = null;
        isParentsSelected = false;
        parentLocator = new LOCATOR__c();
        listTree = new List<LOCATOR__c>();
        indexTree = 0;
      }
      currentWarehouse = getWarehouseInfomationById(warehouseId);
      listLocator = getLocatorListByWareHouse(warehouseId, locatorParentId);
      setChildLocators = new ApexPages.StandardSetController(listLocator);
      setChildLocators.setPageSize(sizeChildLocator);
      setChildLocators.setPageNumber(1);
    }
    private List<LOCATOR__c> getLocatorListByCode(Set<String> codes, String argWareHouseId){
      List<LOCATOR__c> listLocator = [SELECT 
                                          Id, 
                                          Name,
                                          CapacityCBM__c,
                                          CapacityKG__c,
                                          ActualAvailableCapacityCBM__c,
                                          ActualAvailableCapacityKG__c,
                                          ChargeType__c,
                                          LocatorCode__c,
                                          LocatorLayer__c,
                                          ActualOccupiedCapacityCBM__c,
                                          ActualOccupiedCapacityKG__c,
                                          CurrentOccupiedCapacityCBM__c,
                                          CurrentOccupiedCapacityKG__c,
                                          CurrentAvailableCapacityCBM__c,
                                          CurrentAvailableCapacityKG__c,
                                          SKU__c,
                                          Supplier__c,
                                          Tenant__c,
                                          FastSlowClassification__c,
                                          Buyer__c,
                                          SharedCapacityCBM__c,
                                          SharedCapacityKG__c,
                                          WarehouseID__c,
                                          WarehouseID__r.FacilityName__c,
                                          LocatorDescription__c
                                         FROM LOCATOR__c
                                         WHERE 
                                          WarehouseID__c =: argWareHouseId
                                         AND LocatorCode__c IN: codes
                                         ORDER BY LocatorCode__c asc];
        return listLocator;
    }
    public List<LOCATOR__c> getLocatorListByWareHouse(ID warehouseId, Id locatorParentId){
        List<LOCATOR__c> listLocator = [SELECT 
                                          Id, 
                                          Name,
                                          CapacityCBM__c,
                                          CapacityKG__c,
                                          ActualAvailableCapacityCBM__c,
                                          ActualAvailableCapacityKG__c,
                                          ChargeType__c,
                                          LocatorCode__c,
                                          LocatorLayer__c,
                                          ActualOccupiedCapacityCBM__c,
                                          ActualOccupiedCapacityKG__c,
                                          CurrentOccupiedCapacityCBM__c,
                                          CurrentOccupiedCapacityKG__c,
                                          CurrentAvailableCapacityCBM__c,
                                          CurrentAvailableCapacityKG__c,
                                          SKU__c,
                                          Supplier__c,
                                          Tenant__c,
                                          FastSlowClassification__c,
                                          Buyer__c,
                                          SharedCapacityCBM__c,
                                          SharedCapacityKG__c,
                                          WarehouseID__c,
                                          WarehouseID__r.FacilityName__c,
                                          LocatorDescription__c,
                                          ParentLocator__c
                                         FROM LOCATOR__c
                                         WHERE 
                                          ParentLocator__c =: locatorParentId
                                         AND WarehouseID__c =: warehouseId];
        return listLocator;
    }

    private LOCATOR__c getLocatorById(String idSelectedLocator){

      List<LOCATOR__c> listLocator = [SELECT Id, 
                                          Name,
                                          CapacityCBM__c,
                                          CapacityKG__c,
                                          ActualAvailableCapacityCBM__c,
                                          ActualAvailableCapacityKG__c,
                                          ChargeType__c,
                                          LocatorCode__c,
                                          LocatorLayer__c,
                                          ActualOccupiedCapacityCBM__c,
                                          ActualOccupiedCapacityKG__c,
                                          CurrentOccupiedCapacityCBM__c,
                                          CurrentOccupiedCapacityKG__c,
                                          CurrentAvailableCapacityCBM__c,
                                          CurrentAvailableCapacityKG__c,
                                          SKU__c,
                                          Supplier__c,
                                          Tenant__c,
                                          FastSlowClassification__c,
                                          Buyer__c,
                                          SharedCapacityCBM__c,
                                          SharedCapacityKG__c,
                                          WarehouseID__c,
                                          WarehouseID__r.FacilityName__c,
                                          LocatorDescription__c,
                                          ParentLocator__c
                                         FROM LOCATOR__c
                                         WHERE 
                                          Id =: idSelectedLocator];
      if(!listLocator.isEmpty()){

        return listLocator[0];
      }

      return new LOCATOR__c();

    }
    private Facility__c getWarehouseInfomationById(Id argWarehouseId){

      List<Facility__c> warehouses = [SELECT Id,
                                        Name,
                                        FacilityName__c,
                                        FacilityImage__c,
                                        FacilityType__c,
                                        WarehoueType__c,
                                        CapacityCBM__c,
                                        CapacityKG__c,
                                        ChargeType__c,
                                        StorageType__c,
                                        Address__c,
                                        ItemType__c,
                                        OwnershipType__c,
                                        OwnerCompanyName__c,
                                        RollUpActualOccupiedCapacityCBM__c,
                                        RollUpActualOccupiedCapacityKG__c,
                                        RollUpCurrentOccupiedCapacityCBM__c,
                                        RollUpCurrentOccupiedCapacityKG__c,
                                        RollUpMaxMeasurementCapacity__c,
                                        RollUpMaxWeightKGCapacity__c
                                      FROM 
                                        Facility__c 
                                      WHERE 
                                        Id=: warehouseId
                                     AND Active__c = true];
      if(!warehouses.isEmpty()){
        return warehouses[0];
      }

      return new Facility__c();
    }

    public void doSearch(){

      String strQuery = buildQuery(locatorSearch);
      query = strQuery;
      resultSearchLocator = Database.query(strQuery);
      setLocatorSearch = new ApexPages.StandardSetController(resultSearchLocator);
      isDisplayWarehouseList = false;
      isDisplayResultSearch = true;
      setLocatorSearch.setPageNumber(1);
      setLocatorSearch.setPageSize(sizeSearch);
    }

    private string buildQuery(WapperLocator objSearch){
      String strQuery = '';

      String strSelectField = 'SELECT Id, '
                                + 'Name, '        
                                + 'CapacityCBM__c, '       
                                + 'CapacityKG__c, '    
                                + 'ActualAvailableCapacityCBM__c, '        
                                + 'ActualAvailableCapacityKG__c, '
                                + 'ChargeType__c, '                 
                                + 'LocatorCode__c, '
                                + 'LocatorLayer__c, '
                                + 'ActualOccupiedCapacityCBM__c, '
                                + 'ActualOccupiedCapacityKG__c, '
                                + 'CurrentOccupiedCapacityCBM__c, ' 
                                + 'CurrentOccupiedCapacityKG__c, '
                                + 'CurrentAvailableCapacityCBM__c, '
                                + 'CurrentAvailableCapacityKG__c, '
                                + 'SKU__c, '
                                + 'Supplier__c, '
                                + 'Tenant__c, '
                                + 'FastSlowClassification__c, '
                                + 'Buyer__c, '
                                + 'SharedCapacityCBM__c, '
                                + 'SharedCapacityKG__c, '
                                + 'WarehouseID__c, '
                                + 'WarehouseID__r.FacilityName__c, '
                                + 'ParentLocator__c, '
                                + 'LocatorDescription__c '
                                + 'FROM LOCATOR__c';
      String strCondition ='';

      if(!String.isBlank(objSearch.locatorLayer)){
        strCondition = strCondition + ' AND LocatorLayer__c =\'' + String.escapeSingleQuotes(objSearch.locatorLayer) + '\'';
      }
      if(!String.isBlank(objSearch.warehouseName)){

        strCondition = strCondition + ' AND WarehouseID__r.FacilityName__c LIKE \'%' + String.escapeSingleQuotes(objSearch.warehouseName) + '%\'';
      }
      if(objSearch.currentAvailableCBM != null && objSearch.currentAvailableCBM > 0){

        strCondition = strCondition + ' AND CurrentAvailableCapacityCBM__c = ' + objSearch.currentAvailableCBM ;
      }
      if(objSearch.currentAvailableKG != null && objSearch.currentAvailableKG > 0){
        
        strCondition = strCondition + ' AND CurrentAvailableCapacityKG__c = ' + objSearch.currentAvailableKG ;
      }
      if(objSearch.actualAvailableCBM != null && objSearch.actualAvailableCBM > 0){
        
        strCondition = strCondition + ' AND ActualAvailableCapacityCBM__c = ' + objSearch.actualAvailableCBM ;
      }
      if(objSearch.actualAvailableKG != null && objSearch.actualAvailableKG > 0){
        strCondition = strCondition + ' AND ActualAvailableCapacityKG__c = ' + objSearch.actualAvailableKG ;
      }
      if(objSearch.locator.CapacityCBM__c > 0){
        strCondition = strCondition + ' AND CapacityCBM__c = ' + objSearch.locator.CapacityCBM__c ;
      }
      if(objSearch.locator.CapacityKG__c > 0){
        strCondition = strCondition + ' AND CapacityKG__c = ' + objSearch.locator.CapacityKG__c ;
      }
      if(objSearch.locator.Tenant__c != null){
        strCondition = strCondition + ' AND Tenant__c = \'' + String.escapeSingleQuotes(objSearch.locator.Tenant__c) +'\'';
      }

      if(objSearch.locator.Supplier__c != null){
        strCondition = strCondition + ' AND Supplier__c = \'' + String.escapeSingleQuotes(objSearch.locator.Supplier__c) + '\'' ;
      }
      if(objSearch.locator.Buyer__c != null){
        strCondition = strCondition + ' AND Buyer__c = \'' + String.escapeSingleQuotes(objSearch.locator.Buyer__c) +'\'';
      }

      if(objSearch.locator.ChargeType__c != null){
        strCondition = strCondition + ' AND ChargeType__c =\'' + String.escapeSingleQuotes(objSearch.locator.ChargeType__c) + '\' ' ;
      }
      if(objSearch.locator.SKU__c != null){
        List<String> listSKUvalues = new List<String>();
        String skuValues =  objSearch.locator.SKU__c.replaceAll(';', '\',\'');
        skuValues = '(\''+ skuValues+'\')';

        strCondition = strCondition + ' AND SKU__c IN ' +  skuValues ;
      }
      if(objSearch.locator.FastSlowClassification__c != null){
        strCondition = strCondition + ' AND FastSlowClassification__c = \'' + String.escapeSingleQuotes(objSearch.locator.FastSlowClassification__c) + '\'' ;
      }
      strCondition = strCondition.replaceFirst('AND', 'WHERE');
      strQuery = strSelectField + strCondition;
      return strQuery;
    }

    public List<SelectOption> getLayerPickList() {
      List<SelectOption> options = new List<SelectOption>();
      Schema.DescribeFieldResult fieldResult = LOCATOR__c.LocatorLayer__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      options.add(new SelectOption('','--None--'));
      for( Schema.PicklistEntry f : ple){
        options.add(new SelectOption(f.getValue(), f.getLabel()));
       }     
      return options;
    }
    public ApexPages.StandardSetController setLocatorSearch{
        get {
            if(setLocatorSearch == null) {
                setLocatorSearch = new ApexPages.StandardSetController(resultSearchLocator);
                setLocatorSearch.setPageSize(sizeSearch);
            }
            return setLocatorSearch;
        }
        set;
    }
    public ApexPages.StandardSetController setChildLocators {
        get {
            if(setChildLocators == null) {
                setChildLocators = new ApexPages.StandardSetController(listLocator);
                setChildLocators.setPageSize(sizeChildLocator);
            }
            return setChildLocators;
        }
        set;
    }
    public ApexPages.StandardSetController setWarehouseList {
        get {
            if(setWarehouseList == null) {
                setWarehouseList = new ApexPages.StandardSetController(listWarehouse);
                setWarehouseList.setPageSize(sizeWarehouse);
            }
            return setWarehouseList;
        }
        set;
    }

    public List<LOCATOR__c> getLocatorSearchResult() {
        return (List<LOCATOR__c>) setLocatorSearch.getRecords();
    }
    public List<LOCATOR__c> getChildLocatorResult() {
        return (List<LOCATOR__c>) setChildLocators.getRecords();
    }
    public List<Facility__c> getWarehouseResult() {
        return (List<Facility__c>) setWarehouseList.getRecords();
    }

    public PageReference refreshPageSizeSearch() {
         setLocatorSearch.setPageSize(sizeSearch);
         return null;
    }
    public PageReference refreshPageSizeChildLocator() {
         setChildLocators.setPageSize(sizeSearch);
         return null;
    }
    public PageReference refreshPageSizeWarehouse() {
         setWarehouseList.setPageSize(sizeSearch);
         return null;
    }
    Public Integer getTotalPageSearchs(){
     Decimal totalSize = setLocatorSearch.getResultSize();
     Decimal pageSize = setLocatorSearch.getPageSize();
     Decimal pages = totalSize/pageSize;
     return (Integer)pages.round(System.RoundingMode.CEILING);
    }
    Public Integer getTotalPageChildLocators(){
     Decimal totalSize = setChildLocators.getResultSize();
     Decimal pageSize = setChildLocators.getPageSize();
     Decimal pages = totalSize/pageSize;
     return (Integer)pages.round(System.RoundingMode.CEILING);
    }
    Public Integer getTotalPageWarehouses(){
     Decimal totalSize = setWarehouseList.getResultSize();
     Decimal pageSize = setWarehouseList.getPageSize();
     Decimal pages = totalSize/pageSize;
     return (Integer)pages.round(System.RoundingMode.CEILING);
    }
    public class WapperLocator{

      public LOCATOR__c locator{get; set;}
      public String locatorLayer{get; set;}
      public Decimal currentAvailableCBM{get; set;}
      public Decimal currentAvailableKG {get; set;}
      public Decimal actualAvailableCBM{get; set;}
      public Decimal actualAvailableKG{get; set;}
      public String warehouseName{get; set;}

      public WapperLocator(){
        locator = new LOCATOR__c();
      }
    }
    

}