force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>FACILITY ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/LOCATOR__c.object-meta.xml
<CustomObject>
    <label>Locator</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>LOCATOR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locator</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LOCATOR__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BUYER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LACATOR (BUYER)</relationshipLabel>
    <relationshipName>LacatorBuyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/FastSlowClassification__c.field-meta.xml
<CustomField>
    <fullName>FastSlowClassification__c</fullName>
    <inlineHelpText>FSN
F:Fast-moving
S:Slow-moving
N:Non-moving</inlineHelpText>
    <label>FAST/SLOW CLASSIFICATION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FastSlowClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LOCATOR__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>LOCATOR</relationshipLabel>
    <relationshipName>Locator</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BUYER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRODUCTS (BUYER)</relationshipLabel>
    <relationshipName>buyer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/DangerousClassification__c.field-meta.xml
<CustomField>
    <fullName>DangerousClassification__c</fullName>
    <label>DANGEROUS CLASSIFICATION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DangerousClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GoodOwner__c.field-meta.xml
<CustomField>
    <fullName>GoodOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GOODS OWNER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRODUCTS</relationshipLabel>
    <relationshipName>PRODUCTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/HSCode__c.field-meta.xml
<CustomField>
    <fullName>HSCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HS CODE</label>
    <referenceTo>HS_Code__c</referenceTo>
    <relationshipLabel>PRODUCTS</relationshipLabel>
    <relationshipName>PRODUCTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/InventoryType__c.field-meta.xml
<CustomField>
    <fullName>InventoryType__c</fullName>
    <label>INVENTORY TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InventoryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <label>ITEM NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ItemType__c.field-meta.xml
<CustomField>
    <fullName>ItemType__c</fullName>
    <label>ITEM TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ItemType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/LOTNumber__c.field-meta.xml
<CustomField>
    <fullName>LOTNumber__c</fullName>
    <label>LOT NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MANUFACTURER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRODUCTS (MANUFACTURER)</relationshipLabel>
    <relationshipName>Manufacturer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <inlineHelpText>= cubic inch/61023.744 or cubic feet/35.315 or cubic yard/1.308</inlineHelpText>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/NETWeight__c.field-meta.xml
<CustomField>
    <fullName>NETWeight__c</fullName>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/PartNumber__c.field-meta.xml
<CustomField>
    <fullName>PartNumber__c</fullName>
    <label>PART NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <label>SERIAL NUMBER</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SKUNumber__c.field-meta.xml
<CustomField>
    <fullName>SKUNumber__c</fullName>
    <label>Product SKU Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>STOCK LIST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <formula>StockLocator__r.Buyer__r.Name</formula>
    <label>BUYER</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/FastSlowClassification__c.field-meta.xml
<CustomField>
    <fullName>FastSlowClassification__c</fullName>
    <formula>Text(StockLocator__r.FastSlowClassification__c)</formula>
    <label>FAST/SLOW CLASSIFICATION</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <label>ITEM NUMBER(Old)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/LOTNumber__c.field-meta.xml
<CustomField>
    <fullName>LOTNumber__c</fullName>
    <label>LOT NUMBER(Old)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MEASUREMENT (CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/NETWeight__c.field-meta.xml
<CustomField>
    <fullName>NETWeight__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK_LIST</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>PRODUCT NAME</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <formula>WOSLineID__r.Cargo__r.SerialNumber__c</formula>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/fields/SKUNumber__c.field-meta.xml
<CustomField>
    <fullName>SKUNumber__c</fullName>
    <label>SKU NUMBER(Old)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/STOCK__c.field-meta.xml
<CustomField>
    <fullName>STOCK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stock</relationshipLabel>
    <relationshipName>Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/StockDate__c.field-meta.xml
<CustomField>
    <fullName>StockDate__c</fullName>
    <label>STOCK DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/StockLocator__c.field-meta.xml
<CustomField>
    <fullName>StockLocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>STOCK LOCATOR</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>LOCATOR__c.LocationAreaType__c</field>
            <operation>equals</operation>
            <value>Storage Area, Storage Area</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>LOCATOR__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK_LIST</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/StockStatus__c.field-meta.xml
<CustomField>
    <fullName>StockStatus__c</fullName>
    <label>STOCK STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StockStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/recordTypes/StockIn.recordType-meta.xml
<RecordType>
    <fullName>StockIn</fullName>
    <active>true</active>
    <description>Record Type when Goods increase</description>
    <label>Stock-In</label>
</RecordType>

force-app/main/default/objects/Stock__c/recordTypes/StockOut.recordType-meta.xml
<RecordType>
    <fullName>StockOut</fullName>
    <active>true</active>
    <description>Record Type when Number of Goods decrease</description>
    <label>Stock-Out</label>
</RecordType>

force-app/main/default/globalValueSets/DangerousClassification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Dangerous Goods</fullName>
        <default>true</default>
        <label>No Dangerous Goods</label>
    </customValue>
    <customValue>
        <fullName>1.Explosives</fullName>
    </customValue>
    <customValue>
        <fullName>2.Gases</fullName>
    </customValue>
    <customValue>
        <fullName>3.Flammable Liquids</fullName>
    </customValue>
    <customValue>
        <fullName>4.Flammable Solids</fullName>
    </customValue>
    <customValue>
        <fullName>5.Oxidizing Substances</fullName>
    </customValue>
    <customValue>
        <fullName>6.Toxic &amp; Infectious Substances</fullName>
    </customValue>
    <customValue>
        <fullName>7.Radioactive Material</fullName>
    </customValue>
    <customValue>
        <fullName>8.Corrosives</fullName>
    </customValue>
    <customValue>
        <fullName>9.Miscellaneous Dangerous Goods</fullName>
    </customValue>
    <masterLabel>DANGEROUS CLASSIFICATION</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FastSlowClassification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A:Fast-moving</fullName>
    </customValue>
    <customValue>
        <fullName>B:Slow-moving</fullName>
    </customValue>
    <customValue>
        <fullName>C:Non-moving</fullName>
    </customValue>
    <customValue>
        <fullName>B:Normal</fullName>
        <isActive>false</isActive>
        <label>B:Normal</label>
    </customValue>
    <masterLabel>FAST/SLOW CLASSIFICATION</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InventoryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FIFO(First In First Out)</fullName>
    </customValue>
    <customValue>
        <fullName>LIFO(Last In First Out)</fullName>
    </customValue>
    <customValue>
        <fullName>FEFO( First Expiry First Out )</fullName>
    </customValue>
    <customValue>
        <fullName>Average</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>INVENTORY TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ItemType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General merchandise</fullName>
    </customValue>
    <customValue>
        <fullName>Household/furniture</fullName>
    </customValue>
    <customValue>
        <fullName>Special commodity</fullName>
    </customValue>
    <customValue>
        <fullName>Cold storage</fullName>
    </customValue>
    <masterLabel>ITEM TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SKU.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pallet</fullName>
    </customValue>
    <customValue>
        <fullName>Batch</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Pack</fullName>
    </customValue>
    <customValue>
        <fullName>Piece</fullName>
    </customValue>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Tray</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <masterLabel>SKU</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/StockStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planning</fullName>
        <label>Plannned</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>STOCK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GoodSearchController.cls
public with sharing class GoodSearchController {
	public PRODUCT__c objectProductSearch{get; set;}
	public Boolean isDisplayResultSearch{get; set;}
	public List<ProductWapper> listProductResult {get; set;}
	public List<LocatorWapper> currentListLocator {get; set;}
	public ProductWapper currentProductWapper{get; set;}
	public List<Stock__c> listResultSearch{get; set;}
	public Boolean isDisplayDetailProduct {get; set;}
	public String sqlStr {get; set;}
	public PRODUCT__c currentProduct {get; set;}
	//==================Pagination variable===============
    public Integer sizeSearchPage{get;set;}
    public Integer sizeDetailPage{get;set;}
    public List<SelectOption> paginationSizeOptions{get;set;}
    public ProductWapperIterable objProductIterable{get; set;}
    public LocatorWapperIterable objLocatorIterable{get; set;}
    public List<ProductWapper> listSetProduct{get; set;}
    public List<LocatorWapper> listSetLocator{get; set;}
    

	public GoodSearchController() {
		sizeSearchPage = 10;
		sizeDetailPage = 10;
		paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));


		objectProductSearch = new PRODUCT__c();
		isDisplayResultSearch = false;
		listResultSearch = new List<Stock__c>();
		isDisplayDetailProduct = false;
		sqlStr = '';

	}

	/*public ApexPages.StandardSetController setResultSearch{
        get {
            if(setResultSearch == null) {
                setResultSearch = new ApexPages.StandardSetController(listProductResult);
                setResultSearch.setPageSize(sizeSearchPage);
            }
            return setResultSearch;
        }
        set;
    }*/

	private String buildQuery(PRODUCT__c objectSearch){
		String strQuery = '';
		String strSelect = '';
		String strCondition = '';
		strSelect = 'SELECT '
		+ 'Id, Name, RecordType.Name, '
		+ 'ProductID__r.Name, '
		+ 'ProductID__r.ProductName__c, '
		+ 'ProductID__r.GoodOwner__c, '
		+ 'ProductID__r.Manufacturer__c, '
		+ 'ProductID__r.SKUNumber__c, '
		+ 'ProductID__r.Buyer__c, '
		+ 'ProductID__r.SerialNumber__c, '
		+ 'ProductID__r.Measurement__c, '
		+ 'ProductID__r.NETWeight__c, '
		+ 'ProductID__r.GrossWeight__c, '
		+ 'StockLocator__c, '
		+ 'StockLocator__r.Name, '
		+ 'StockStatus__c, '
		+ 'RecordTypeId, '
		+ 'RecordType.DeveloperName, '
		+ 'Measurement__c, '
		+ 'GrossWeight__c,'
		+ 'Quantity__c '
		+ 'FROM Stock__c ';
		if(!String.isBlank(objectProductSearch.Name)){
			strCondition = strCondition + ' AND ProductID__r.Name like \'%' + objectProductSearch.Name + '%\'';
		}

		if(!String.isBlank(objectProductSearch.ProductName__c)){
			strCondition = strCondition + ' AND ProductID__r.ProductName__c like \'%' + objectProductSearch.ProductName__c + '%\'';
		}

		if(objectProductSearch.GoodOwner__c != null){
			strCondition = strCondition + ' AND ProductID__r.GoodOwner__c = \'' + objectProductSearch.GoodOwner__c + '\'';
		}
		if(objectProductSearch.Buyer__c != null){
			strCondition = strCondition + ' AND ProductID__r.Buyer__c = \'' + objectProductSearch.Buyer__c + '\'';
		}
		if(objectProductSearch.Manufacturer__c != null){
			strCondition = strCondition + ' AND ProductID__r.Manufacturer__c = \'' + objectProductSearch.Manufacturer__c + '\'';
		}
		if(!String.isBlank(objectProductSearch.SKUNumber__c )){
			strCondition = strCondition + ' AND ProductID__r.SKUNumber__c like \'%' + objectProductSearch.SKUNumber__c + '%\'';
		}
		if(!String.isBlank(objectProductSearch.SerialNumber__c)){
			strCondition = strCondition + ' AND ProductID__r.SerialNumber__c like \'%' + objectProductSearch.SerialNumber__c + '%\'';
		}
		if(!String.isBlank(objectProductSearch.ItemNumber__c)){
			strCondition = strCondition + ' AND ProductID__r.ItemNumber__c like \'%' + objectProductSearch.ItemNumber__c + '%\'';
		}
		if(!String.isBlank(objectProductSearch.LOTNumber__c)){
			strCondition = strCondition + ' AND ProductID__r.LOTNumber__c like \'%' + objectProductSearch.LOTNumber__c + '%\'';
		}
		if(objectProductSearch.InventoryType__c != null){
			strCondition = strCondition + ' AND ProductID__r.InventoryType__c = \'' + objectProductSearch.InventoryType__c + '\'';
		}
		if(!String.isBlank(objectProductSearch.PartNumber__c)){
			strCondition = strCondition + ' AND ProductID__r.PartNumber__c like \'%' + objectProductSearch.PartNumber__c + '%\'';
		}
		if(objectProductSearch.FastSlowClassification__c != null){
			strCondition = strCondition + ' AND ProductID__r.FastSlowClassification__c = \'' + objectProductSearch.FastSlowClassification__c + '\'';
		}
		if(objectProductSearch.ItemType__c != null){
			strCondition = strCondition + ' AND ProductID__r.ItemType__c = \'' + objectProductSearch.ItemType__c + '\'';
		}
		if(objectProductSearch.InventoryType__c != null){
			strCondition = strCondition + ' AND ProductID__r.InventoryType__c = \'' + objectProductSearch.InventoryType__c + '\'';
		}
		if(objectProductSearch.DangerousClassification__c != null){
			strCondition = strCondition + ' AND ProductID__r.DangerousClassification__c = \'' + objectProductSearch.DangerousClassification__c + '\'';
		}
		if(objectProductSearch.HSCode__c != null){
			strCondition = strCondition + ' AND ProductID__r.HSCode__c = \'' + objectProductSearch.HSCode__c + '\'';
		}
		if(objectProductSearch.SKU__c != null){
			strCondition = strCondition + ' AND ProductID__r.SKU__c = \'' + objectProductSearch.SKU__c + '\'';
		}

		strCondition = strCondition + ' AND (StockStatus__c = \'Completed\' OR StockStatus__c = \'Planning\')';
		//strCondition =+ 'AND RecordTypeId.Name = \'StockIn \'';
		strCondition = strCondition + ' Order by ProductID__c, StockLocator__c   Limit 5000';

		if(strCondition != ''){
			strCondition = strCondition.replaceFirst('AND', 'WHERE');
		}
		strQuery = strSelect + strCondition;
		return strQuery;
	}

	public void doSearch(){
		isDisplayResultSearch = true;
		isDisplayDetailProduct = false;
		currentListLocator = new List<LocatorWapper>();
		currentProduct = new PRODUCT__c();
		String strQuery = buildQuery(objectProductSearch);
		listResultSearch = Database.query(strQuery);
		// get Stock by Product
		listProductResult = new List<ProductWapper>();
		sqlStr = strQuery;
		//Integer countLocator = 0;
		LocatorWapper locator = new LocatorWapper();
		ProductWapper prtWapper = new ProductWapper();
		String nextlocatorId;
		String nextProductId;
		Integer countStock = 0;
		Map<Id, LocatorWapper> stockHaveNoLocator = new Map<Id, LocatorWapper>();
		for(Stock__c objStock : listResultSearch){
			countStock = countStock + 1;
			if(listResultSearch.size() > countStock){
				nextlocatorId = listResultSearch[countStock].StockLocator__c;
				nextProductId = listResultSearch[countStock].ProductID__c;
			}else{
				nextlocatorId = null;
				nextProductId = null;
			}
			if(objStock.ProductID__c != prtWapper.product.Id){
				prtWapper = new ProductWapper();
				prtWapper.product.Id = objStock.ProductID__c;
				prtWapper.productName = objStock.ProductID__r.Name;
				prtWapper.product.ProductName__c = objStock.ProductID__r.ProductName__c;
				prtWapper.product.GoodOwner__c = objStock.ProductID__r.GoodOwner__c;
				prtWapper.product.Manufacturer__c = objStock.ProductID__r.Manufacturer__c;
				prtWapper.product.SKUNumber__c = objStock.ProductID__r.SKUNumber__c;
				prtWapper.product.Buyer__c = objStock.ProductID__r.Buyer__c;
				prtWapper.product.SerialNumber__c = objStock.ProductID__r.SerialNumber__c;
				prtWapper.product.Measurement__c = objStock.ProductID__r.Measurement__c;
				prtWapper.product.NETWeight__c = objStock.ProductID__r.NETWeight__c;
				prtWapper.product.GrossWeight__c = objStock.ProductID__r.GrossWeight__c;
				locator = new LocatorWapper();
				locator.locatorId = objStock.StockLocator__c;
				locator.locatorName = objStock.StockLocator__r.Name;
				locator.productName = objStock.ProductID__r.Name;
				locator.listStock = new List<Stock__c>();
			}
			if(objStock.Measurement__c == null){
				objStock.Measurement__c = 0;
			}
			if(objStock.GrossWeight__c == null){
				objStock.GrossWeight__c = 0;
			}
			if(objStock.Quantity__c == null){
				objStock.Quantity__c = 0;
			}
			if(locator.locatorId != objStock.StockLocator__c && objStock.ProductID__c == prtWapper.product.Id){
				locator = new LocatorWapper();
				locator.locatorId = objStock.StockLocator__c;
				locator.locatorName = objStock.StockLocator__r.Name;
				locator.productName = objStock.ProductID__r.Name;
				locator.listStock = new List<Stock__c>();
			}
			if(locator.locatorId == objStock.StockLocator__c && objStock.ProductID__c == prtWapper.product.Id){
				locator.listStock.add(objStock);
				if(objStock.RecordType.DeveloperName == 'StockIn'
				&& objStock.StockStatus__c == 'Completed'){

					locator.totalLocatorMeasurement = locator.totalLocatorMeasurement + objStock.Measurement__c == null? 0: objStock.Measurement__c;
					locator.totalLocatorGrossWeight = locator.totalLocatorGrossWeight + objStock.GrossWeight__c == null? 0: objStock.GrossWeight__c;
					
					locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan + objStock.Measurement__c == null? 0: objStock.Measurement__c;
					locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan + objStock.GrossWeight__c == null? 0: objStock.GrossWeight__c;
					locator.remainQuantity = locator.remainQuantity + (Integer)objStock.Quantity__c;
				}
				if(objStock.RecordType.DeveloperName == 'StockOut'
				&& objStock.StockStatus__c == 'Completed'){ 

					locator.totalLocatorMeasurement = locator.totalLocatorMeasurement - objStock.Measurement__c == null? 0: objStock.Measurement__c;
					locator.totalLocatorGrossWeight = locator.totalLocatorGrossWeight - objStock.GrossWeight__c == null? 0: objStock.GrossWeight__c;
					locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan - objStock.Measurement__c == null? 0: objStock.Measurement__c;
					locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan - objStock.GrossWeight__c == null? 0: objStock.GrossWeight__c;
					locator.remainQuantity = locator.remainQuantity - (Integer)objStock.Quantity__c;
				}
				if(objStock.RecordType.DeveloperName == 'StockIn'
				&& objStock.StockStatus__c == 'Planning'){
					locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan + objStock.Measurement__c == null? 0: objStock.Measurement__c;
					locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan + objStock.GrossWeight__c == null? 0: objStock.GrossWeight__c;
				}
				if(objStock.RecordType.DeveloperName == 'StockOut'
				&& objStock.StockStatus__c == 'Planning'){
					locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan - objStock.Measurement__c == null? 0: objStock.Measurement__c;
					locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan - objStock.GrossWeight__c == null? 0: objStock.GrossWeight__c;
				}
			}
			if(objStock.StockLocator__c != nextlocatorId && objStock.ProductID__c == prtWapper.product.Id
				|| objStock.ProductID__c != nextProductId){


				locator.totalLocatorMeasurement = locator.totalLocatorMeasurement.setScale(3);
				locator.totalLocatorGrossWeight = locator.totalLocatorGrossWeight.setScale(3);
				locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan.setScale(3);
				locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan.setScale(3);
				prtWapper.totalProductMeasurement = prtWapper.totalProductMeasurement + locator.totalLocatorMeasurement;
				prtWapper.totalProductGrossWeight = prtWapper.totalProductGrossWeight + locator.totalLocatorGrossWeight;
				prtWapper.totalProductMeasurementIncludePlan = prtWapper.totalProductMeasurementIncludePlan + locator.totalLocatorMeasurementIncludePlan;
				prtWapper.totalProductGrossWeightIncludePlan = prtWapper.totalProductGrossWeightIncludePlan + locator.totalLocatorGrossWeightIncludePlan;
				prtWapper.remainQuantityProduct = prtWapper.remainQuantityProduct + locator.remainQuantity;
				prtWapper.totalProductMeasurement = prtWapper.totalProductMeasurement.setScale(3);
				prtWapper.totalProductGrossWeight = prtWapper.totalProductGrossWeight.setScale(3);
				prtWapper.totalProductMeasurementIncludePlan = prtWapper.totalProductMeasurementIncludePlan.setScale(3);
				prtWapper.totalProductGrossWeightIncludePlan = prtWapper.totalProductGrossWeightIncludePlan.setScale(3);
				prtWapper.listLocator.add(locator);
				//continue;
			}
			
			if(nextProductId != objStock.ProductId__c){
				listProductResult.add(prtWapper);
			}

			
		}
		objProductIterable = new ProductWapperIterable(listProductResult); 
        objProductIterable.setPageSize(sizeSearchPage);
        listSetProduct = objProductIterable.next(); 
	}
	public void viewDetailProduct(){
		isDisplayResultSearch = false;
		isDisplayDetailProduct = true;
		currentProductWapper = new ProductWapper();
		string productId = ApexPages.currentPage().getParameters().get('productId');
		// query product
		List<PRODUCT__c> listProductSelected = [SELECT 
												Id,
												Name,
												ProductName__c,
												GoodOwner__c,
												Buyer__c,
												Manufacturer__c,
												SKUNumber__c,
												SerialNumber__c,
												ItemNumber__c,
												LOTNumber__c,
												PartNumber__c,
												FastSlowClassification__c,
												InventoryType__c,
												ItemType__c,
												DangerousClassification__c,
												HSCode__c,
												SKU__c,
												Measurement__c,
												NETWeight__c,
												GrossWeight__c
												FROM PRODUCT__c WHERE Id =: productId];

		// query stock
		if(!listProductSelected.isEmpty()){
			currentProductWapper.product = listProductSelected[0];
			currentProduct = listProductSelected[0];
			List<Stock__c> listStockbyProduct = [SELECT 
												Id, 
												StockLocator__r.Name, 
												StockLocator__c,
												Name, 
												Measurement__c, 
												GrossWeight__c,
												StockDate__c,
												Quantity__c,
												RecordType.Name, 
												StockStatus__c,
												StockLocator__r.WarehouseID__c,
												StockLocator__r.WarehouseID__r.Name,
												ProductID__c,
												RecordType.DeveloperName
												FROM Stock__c
												WHERE ProductID__c =: currentProduct.Id
												AND (StockStatus__c ='Completed' OR StockStatus__c ='Planning')
												ORDER BY StockLocator__c];
			String idLocatorTemp = null;
			LocatorWapper locator = new LocatorWapper();
			locator.locatorId = null;
			locator.listStock = new List<Stock__c>();
			Integer countStock = 0;
			Id nextLocatorId;
			for(Stock__c stock: listStockbyProduct){
				countStock = countStock + 1;
				if(listStockbyProduct.size() > countStock){
					nextLocatorId = listStockbyProduct[countStock].StockLocator__c;
				}else{
					nextLocatorId = null;
				}
				if(locator.locatorId != stock.StockLocator__c){
					locator = new LocatorWapper();
					locator.locatorId = stock.StockLocator__c;
					locator.listStock = new List<Stock__c>();
				}

				locator.locatorName = stock.StockLocator__r.Name;
				locator.facitityName = stock.StockLocator__r.WarehouseID__r.Name;
				locator.facitityId = stock.StockLocator__r.WarehouseID__c;
				if(stock.Measurement__c == null){
				stock.Measurement__c = 0;
				}
				if(stock.GrossWeight__c == null){
					stock.GrossWeight__c = 0;
				}
				if(stock.Quantity__c == null){
					stock.Quantity__c = 0;
				}
				if(locator.locatorId == stock.StockLocator__c){
					if(stock.RecordType.DeveloperName == 'StockIn'
						&& stock.StockStatus__c == 'Completed'){
							locator.totalLocatorMeasurement = locator.totalLocatorMeasurement + stock.Measurement__c;
							locator.totalLocatorGrossWeight = locator.totalLocatorGrossWeight + stock.GrossWeight__c;
							locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan + stock.Measurement__c;
							locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan + stock.GrossWeight__c;
							locator.remainQuantity = locator.remainQuantity + (Integer)stock.Quantity__c;
						}
					if(stock.RecordType.DeveloperName == 'StockOut'
					&& stock.StockStatus__c == 'Completed'){
						locator.totalLocatorMeasurement = locator.totalLocatorMeasurement - stock.Measurement__c;
						locator.totalLocatorGrossWeight = locator.totalLocatorGrossWeight - stock.GrossWeight__c;
						locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan - stock.Measurement__c;
						locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan - stock.GrossWeight__c;
						locator.remainQuantity = locator.remainQuantity - (Integer)stock.Quantity__c;
					}
					if(stock.RecordType.DeveloperName == 'StockIn'
					&& stock.StockStatus__c == 'Planning'){
						locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan + stock.Measurement__c;
						locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan + stock.GrossWeight__c;
					}
					if(stock.RecordType.DeveloperName == 'StockOut'
					&& stock.StockStatus__c == 'Planning'){
						locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan - stock.Measurement__c;
						locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan - stock.GrossWeight__c;
					}
					locator.listStock.add(stock);
				}
				if(nextlocatorId != stock.StockLocator__c
					|| (countStock == listStockbyProduct.size())){
					locator.totalLocatorMeasurement = locator.totalLocatorMeasurement.setScale(3);
					locator.totalLocatorGrossWeight = locator.totalLocatorGrossWeight.setScale(3);
					locator.totalLocatorMeasurementIncludePlan = locator.totalLocatorMeasurementIncludePlan.setScale(3);
					locator.totalLocatorGrossWeightIncludePlan = locator.totalLocatorGrossWeightIncludePlan.setScale(3);
					currentProductWapper.totalProductMeasurement = currentProductWapper.totalProductMeasurement + locator.totalLocatorMeasurement;
					currentProductWapper.totalProductGrossWeight = currentProductWapper.totalProductGrossWeight + locator.totalLocatorGrossWeight;
					currentProductWapper.totalProductMeasurementIncludePlan = currentProductWapper.totalProductMeasurementIncludePlan + locator.totalLocatorMeasurementIncludePlan;
					currentProductWapper.totalProductGrossWeightIncludePlan = currentProductWapper.totalProductGrossWeightIncludePlan + locator.totalLocatorGrossWeightIncludePlan;
					currentProductWapper.remainQuantityProduct = currentProductWapper.remainQuantityProduct + locator.remainQuantity;
					currentListLocator.add(locator);

				}
				
			}
		}
		objLocatorIterable = new LocatorWapperIterable(currentListLocator); 
        objLocatorIterable.setPageSize(sizeDetailPage);
        listSetLocator = objLocatorIterable.next(); 

	}

	public PageReference refreshPageSizeSearch(){
		objProductIterable.setPageSize(sizeSearchPage);
		listSetProduct = objProductIterable.next();
		return null;
	}

	public Boolean hasNextProduct {
            get 
            {
                return objProductIterable.hasNext();
            }
            set;
        }
        
    public Boolean hasPreviousProduct {
        get 
        {
            return objProductIterable.hasPrevious();
        }
        set;
    }
    
    public void nextProduct() 
    {
        listSetProduct = objProductIterable.next();
    }
    
    public void previousProduct() 
    {
        listSetProduct = objProductIterable.previous();
    }
    public Integer getPageNumberProduct() 
    {
        return objProductIterable.pageNumber;
    }
    public Integer getTotalPageProduct() 
    {
        return objProductIterable.totalPage;
    }

    public PageReference refreshPageSizeDetail(){
		objLocatorIterable.setPageSize(sizeDetailPage);
		listSetLocator = objLocatorIterable.next();
		return null;
	}

	public Boolean hasNextLocator {
            get 
            {
                return objLocatorIterable.hasNext();
            }
            set;
        }
        
    public Boolean hasPreviousLocator {
        get 
        {
            return objLocatorIterable.hasPrevious();
        }
        set;
    }
    
    public void nextLocator() 
    {
        listSetLocator = objLocatorIterable.next();
    }
    
    public void previousLocator() 
    {
        listSetLocator = objLocatorIterable.previous();
    }
    public Integer getPageNumberLocator() 
    {
        return objLocatorIterable.pageNumber;
    }
    public Integer getTotalPageLocator() 
    {
        return objLocatorIterable.totalPage;
    }
}