force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <label>BILLING TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <inlineHelpText>= cubic inch/61023.744 or cubic feet/35.315 or cubic yard/1.308</inlineHelpText>
    <label>MEASUREMENT(CBM)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/NETWeight__c.field-meta.xml
<CustomField>
    <fullName>NETWeight__c</fullName>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SellingUnitPriceLocal__c.field-meta.xml
<CustomField>
    <fullName>SellingUnitPriceLocal__c</fullName>
    <label>SELLING UNIT PRICE(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/SellingUnitPriceLocalKg__c.field-meta.xml
<CustomField>
    <fullName>SellingUnitPriceLocalKg__c</fullName>
    <label>SELLING UNIT PRICE(LOCAL)/Kg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/TaxRateSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRateSelling__c</fullName>
    <label>TAX RATE-SELLING(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/WeightUnit__c.field-meta.xml
<CustomField>
    <fullName>WeightUnit__c</fullName>
    <label>SELLING WEIGHT UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/SalesOrderProduct__c.object-meta.xml
<CustomObject>
    <label>Goods S/O+Product</label>
    <nameField>
        <displayFormat>GSPD-{000000}</displayFormat>
        <label>GOODS S/O+PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goods S/O+Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProduct__c/fields/AmountOfSellingTax__c.field-meta.xml
<CustomField>
    <fullName>AmountOfSellingTax__c</fullName>
    <label>AMOUNT OF SELLING TAX</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/BillingType__c.field-meta.xml
<CustomField>
    <fullName>BillingType__c</fullName>
    <formula>text( ProductID__r.BillingType__c )</formula>
    <label>BILLING TYPE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/FinalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>FinalNetWeight__c</fullName>
    <label>FINAL NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/PlannedQuantity__c.field-meta.xml
<CustomField>
    <fullName>PlannedQuantity__c</fullName>
    <label>PLAN QUANTITY</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <label>PRODUCT ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PRODUCT__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>GOODS S/O+PRODUCT</relationshipLabel>
    <relationshipName>GoodsSalesOrderProduct</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/SellingAmountInclTax__c.field-meta.xml
<CustomField>
    <fullName>SellingAmountInclTax__c</fullName>
    <label>SELLING AMOUNT INCL TAX</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/SellingUnitPriceLocal__c.field-meta.xml
<CustomField>
    <fullName>SellingUnitPriceLocal__c</fullName>
    <inlineHelpText>In case The Product is Unit Base, Selling Unit Price(Local)=Standard Selling Unit Price(Local)
In case The Product is Weight Base, Selling Unit Price(Local)=Standard Selling Unit Price(Local)/Kg or Gram</inlineHelpText>
    <label>Selling Unit Price(Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/TotalAmountOfSelling__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfSelling__c</fullName>
    <label>TOTAL AMOUNT OF SELLING</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/TotalGrossWeight__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossWeight__c</fullName>
    <label>TOTAL GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProduct__c/fields/TotalNetWeight__c.field-meta.xml
<CustomField>
    <fullName>TotalNetWeight__c</fullName>
    <label>TOTAL NET WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
    </customValue>
    <description>Critical field for QR code processing</description>
    <masterLabel>BILLING TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WeightUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
    </customValue>
    <masterLabel>WEIGHT UNIT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SoProductTriggerHelper.cls
public with sharing class SoProductTriggerHelper {
    public static void autoPopulateFields(List<SalesOrderProduct__c> listNew, Map<Id, SalesOrderProduct__c> mapOld) {
        Set<Id> setFromProduct = new Set<Id> ();
        List<SalesOrderProduct__c> listProcess = new List<SalesOrderProduct__c>();
        for (SalesOrderProduct__c item : listNew) {
            if (item.ProductId__c != null) {
                setFromProduct.add(item.ProductID__c);
                listProcess.add(item);
            }
        }
        Map<Id, Product__c> mapFromProdduct = new Map<Id, Product__c>([
            SELECT Id, BillingType__c, WeightUnit__c, NETWeight__c, Measurement__c, GrossWeight__c, TaxRateSelling__c, SellingUnitPriceLocal__c, SellingUnitPriceLocalKg__c
            FROM Product__c 
            WHERE Id IN :setFromProduct
        ]);
        
        for (SalesOrderProduct__c item : listProcess) {
            Product__c prod = mapFromProdduct.get(item.ProductId__c);
            prod.NETWeight__c = prod.NETWeight__c == null ? 0 : prod.NETWeight__c;
            prod.GrossWeight__c = prod.GrossWeight__c == null ? 0 : prod.GrossWeight__c;
            prod.Measurement__c = prod.Measurement__c == null ? 0 : prod.Measurement__c;
            prod.TaxRateSelling__c = prod.TaxRateSelling__c == null ? 0 : prod.TaxRateSelling__c;
            prod.SellingUnitPriceLocal__c = prod.SellingUnitPriceLocal__c == null ? 0 : prod.SellingUnitPriceLocal__c;
            prod.SellingUnitPriceLocalKg__c = prod.SellingUnitPriceLocalKg__c == null ? 0 : prod.SellingUnitPriceLocalKg__c;
            
            //Uniprodt-based -> Calculate recommended weight from Recommended Quantity, Planned weight from planned quantity
            if (prod.BillingType__c == 'Unit') {
                Decimal prodNetWeight = Util.ConvertWeightToUnit('Kg', prod.WeightUnit__c, prod.NETWeight__c);
                Decimal prodGrossWeight = Util.ConvertWeightToUnit('Kg', prod.WeightUnit__c, prod.GrossWeight__c);

                item.Quantity__c = item.Quantity__c == null ? 1 : item.Quantity__c;
                if (item.PlannedQuantity__c == null && item.Quantity__c > 0) {
                    item.PlannedQuantity__c = item.Quantity__c;
                }
                //Measurement, gross weight, total amount of Selling are populated in the following priority: Final > Plan > Recommend; set value in the reverse order to ensure the correct final value
                //recommend net weight
                if (item.Quantity__c > 0) {
                    item.RecommendNetWeight__c = item.Quantity__c * prodNetWeight;
                    item.TotalMeasurement__c = item.Quantity__c * prod.Measurement__c;
                    item.TotalGrossWeight__c = item.Quantity__c * prod.GrossWeight__c;
                    //item.TotalAmountOfSelling__c = item.Quantity__c * prod.SellingUnitPriceLocal__c;
                }
                //planned net weight
                if (item.PlannedQuantity__c > 0) {
                    item.TotalNetWeight__c = item.PlannedQuantity__c * prodNetWeight;
                    item.TotalMeasurement__c = item.PlannedQuantity__c * prod.Measurement__c;
                    item.TotalGrossWeight__c = item.PlannedQuantity__c * prod.GrossWeight__c;
                    //item.TotalAmountOfSelling__c = item.PlannedQuantity__c * prod.SellingUnitPriceLocal__c;
                }
                //final net weight
                if (item.FinalQuantity__c > 0) {
                    item.FinalNetWeight__c = item.FinalQuantity__c * prodNetWeight;
                    item.TotalMeasurement__c = item.FinalQuantity__c * prod.Measurement__c;
                    item.TotalGrossWeight__c = item.FinalQuantity__c * prod.GrossWeight__c;
                    //item.TotalAmountOfSelling__c = item.FinalQuantity__c * prod.SellingUnitPriceLocal__c;
                }
            } 
            //Weight-based -> RecommendNetWeight__c is populated
            else if (prod.BillingType__c == 'Weight') {
                item.RecommendNetWeight__c = item.RecommendNetWeight__c == null ? 0 : item.RecommendNetWeight__c;
                
                if (item.TotalNetWeight__c == null && item.RecommendNetWeight__c > 0) {
                    item.TotalNetWeight__c = Util.ConvertWeightToUnit('Kg', prod.WeightUnit__c, item.RecommendNetWeight__c);
                }
                Decimal currentWeight = item.FinalNetWeight__c > 0 ? item.FinalNetWeight__c : item.TotalNetWeight__c > 0 ? item.TotalNetWeight__c : item.RecommendNetWeight__c;
                if (item.RecommendNetWeight__c > 0) {
                    item.Quantity__c = 1;
                    //item.TotalAmountOfSelling__c = Util.ConvertWeightToUnit(prod.WeightUnit__c, 'Kg', item.RecommendNetWeight__c) * prod.SellingUnitPriceLocalKg__c;
                }
                if (item.TotalNetWeight__c > 0) {
                    item.PlannedQuantity__c = 1;
                    //item.TotalAmountOfSelling__c = Util.ConvertWeightToUnit(prod.WeightUnit__c, 'Kg', item.TotalNetWeight__c) * prod.SellingUnitPriceLocalKg__c;
                }
                if (item.FinalNetWeight__c > 0) {
                    item.FinalQuantity__c = 1;
                    //item.TotalAmountOfSelling__c = Util.ConvertWeightToUnit(prod.WeightUnit__c, 'Kg', item.FinalNetWeight__c) * prod.SellingUnitPriceLocalKg__c;
                }
            }
            //item.TotalAmountOfSelling__c = item.TotalAmountOfSelling__c == null ? 0 : item.TotalAmountOfSelling__c;
            //item.AmountOfSellingTax__c = item.TotalAmountOfSelling__c * prod.TaxRateSelling__c / 100;
            //item.SellingAmountInclTax__c = item.TotalAmountOfSelling__c + item.AmountOfSellingTax__c;
        } 
    }
}