force-app/main/default/objects/PRODUCT__c/PRODUCT__c.object-meta.xml
<CustomObject>
    <label>Products.</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>PRODUCT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRODUCT__c/fields/RollupStockIn__c.field-meta.xml
<CustomField>
    <fullName>RollupStockIn__c</fullName>
    <label>ROLLUP STOCK-IN</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRODUCT__c/fields/RollupStockOut__c.field-meta.xml
<CustomField>
    <fullName>RollupStockOut__c</fullName>
    <label>ROLLUP NUMBER OF STOCK OUTBOUND</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>STOCK LIST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRODUCT ID</label>
    <referenceTo>PRODUCT__c</referenceTo>
    <relationshipLabel>STOCK</relationshipLabel>
    <relationshipName>STOCK_LIST</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>QUANTITY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/STOCK__c.field-meta.xml
<CustomField>
    <fullName>STOCK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stock</relationshipLabel>
    <relationshipName>Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/StockStatus__c.field-meta.xml
<CustomField>
    <fullName>StockStatus__c</fullName>
    <label>STOCK STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StockStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/recordTypes/StockIn.recordType-meta.xml
<RecordType>
    <fullName>StockIn</fullName>
    <active>true</active>
    <description>Record Type when Goods increase</description>
    <label>Stock-In</label>
</RecordType>

force-app/main/default/objects/Stock__c/recordTypes/StockOut.recordType-meta.xml
<RecordType>
    <fullName>StockOut</fullName>
    <active>true</active>
    <description>Record Type when Number of Goods decrease</description>
    <label>Stock-Out</label>
</RecordType>

force-app/main/default/globalValueSets/StockStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Created</fullName>
        <default>true</default>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>Planning</fullName>
        <label>Plannned</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>STOCK STATUS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductTriggerHelper.cls
public with sharing class ProductTriggerHelper {
	public static void rollUpStockInAndOutNumber(Map<Id, PRODUCT__c> mapProductNew) {
		List<AggregateResult> listResult = [SELECT 
                                            ProductID__c, RecordType.DeveloperName, Sum(Quantity__c) quantityTotal 
                                          FROM Stock__c WHERE ProductID__c In: mapProductNew.keySet()
                                          AND StockStatus__c ='Completed'
                                          GROUP BY ProductID__c, RecordType.DeveloperName];

    	List<PRODUCT__c> listProductUpdate = new List<PRODUCT__c>();

    	Map<Id, PRODUCT__c> mapProductUpdate = new Map<Id, PRODUCT__c>();

      
    	for(AggregateResult result : listResult){
        	if(!String.isBlank((Id)result.get('clofor_com_cfs__ProductID__c'))){
        		if(mapProductNew.containsKey((Id)result.get('clofor_com_cfs__ProductID__c'))){
            
		            if((String)result.get('DeveloperName') == 'StockOut'){

		            	mapProductNew.get((Id)result.get('clofor_com_cfs__ProductID__c')).RollupStockOut__c = (Decimal)result.get('quantityTotal');
		            }
		            if((String)result.get('DeveloperName') == 'StockIn'){
		            	mapProductNew.get((Id)result.get('clofor_com_cfs__ProductID__c')).RollupStockIn__c = (Decimal)result.get('quantityTotal');
		        	}
          		}
          
    		}

		}
    	
	}
}