force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountCashIn__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountCashIn__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashInUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashInUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashOutUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashOutUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-OUT(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/ConnectPurchasingInvoiceCash__c.object-meta.xml
<CustomObject>
    <label>購買発注明細＋現金入出</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>CONNECT PURCHASING INVOICE AND CASH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_PURCHASING_INVOICE_AND_CASH</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/UnpaidBalancePurchasingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalancePurchasingLocal__c</fullName>
    <formula>PurchasingInvoice__r.UnpaidBalanceLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF PURCHASING(LOCAL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/UnpaidBalancePurchasingUSD__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalancePurchasingUSD__c</fullName>
    <formula>PurchasingInvoice__r.UnpaidBalance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/POCashTriggerHelper.cls
public with sharing class POCashTriggerHelper {
    public static void onAfterInsert(List<ConnectPurchasingInvoiceCash__c> purchasingCashNews){
        //Set<Id> cashBookIdSet = new Set<Id>();
        //for(ConnectPurchasingInvoiceCash__c link : purchasingCashNews){
        //  cashBookIdSet.add(link.Cashbook__c);
        //}

        //Map<Id, CASH_BOOK__c> cashBooksMap = getCashBookById(cashBookIdSet);

        //for(ConnectPurchasingInvoiceCash__c link : purchasingCashNews ){
        //  if(cashBooksMap.containsKey(link.Cashbook__c)){
        //      // local cash out amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmount__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmount__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmount__c += link.UnpaidBalancePurchasingLocal__c;
                
        //      // usd cash out amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c += link.UnpaidBalancePurchasingUSD__c;
                
        //  }
        //}
        //try{
        //  update cashBooksMap.values();
        //  }catch(Exception ex){
        //      System.debug('########Error#####' + ex.getMessage());
        //  }

    }

    

    public static void onBeforeDelete(List<ConnectPurchasingInvoiceCash__c> purchasingCashOlds){

        //Set<Id> cashBookIdSet = new Set<Id>();
        //for(ConnectPurchasingInvoiceCash__c link : purchasingCashOlds){
        //  cashBookIdSet.add(link.Cashbook__c);
        //}

        //Map<Id, CASH_BOOK__c> cashBooksMap = getCashBookById(cashBookIdSet);

        //for(ConnectPurchasingInvoiceCash__c link : purchasingCashOlds ){
        //  if(cashBooksMap.containsKey(link.Cashbook__c)){

        //      // local cash out amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmount__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmount__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmount__c -= link.UnpaidBalancePurchasingLocal__c;
                
        //      // usd cash out amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c -= link.UnpaidBalancePurchasingUSD__c;
            
        //  }
        //}
        //try{
        //  update cashBooksMap.values();
        //  }catch(Exception ex){
        //      System.debug('########Error#####' + ex.getMessage());
        //  }
    }

    //private static Map<Id, CASH_BOOK__c> getCashBookById(Set<Id> cashBookIdSet){

        
    //  Map<Id, CASH_BOOK__c> cashBooksMap = new Map<Id, clofor_com_cfs__CASH_BOOK__c>([SELECT Id, 
    //                                                          TotalAmountCashIn__c, 
    //                                                          TotalAmount__c,
    //                                                          TotalAmountOfCashOutUSD__c,
    //                                                          TotalAmountOfCashInUSD__c,
    //                                                          RecordTypeId
    //                                                      FROM CASH_BOOK__c
    //                                                      WHERE Id IN: cashBookIdSet]);
    //  return cashBooksMap;


    //}
}