force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/ExchangeRate__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRate__c</fullName>
    <label>EXCHANGE RATE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountCashIn__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountCashIn__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashInUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashInUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashOutUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashOutUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-OUT(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/ConnectPurchasingInvoiceCash__c.object-meta.xml
<CustomObject>
    <label>購買発注明細＋現金入出</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>CONNECT PURCHASING INVOICE AND CASH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_PURCHASING_INVOICE_AND_CASH</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/PurchasingInvoice__c.field-meta.xml
<CustomField>
    <fullName>PurchasingInvoice__c</fullName>
    <label>PURCHASING INVOICE</label>
    <referenceTo>PurchasingInvoice__c</referenceTo>
    <relationshipName>CONNECT_PURCHASING_INVOICE_AND_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/PurchasingInvoice__c.object-meta.xml
<CustomObject>
    <label>購買注文明細</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PURCHASING INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingInvoice__c/fields/AmountIncludedTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountIncludedTaxLocal__c</fullName>
    <formula>TotalAmountLocal__c  +  AmountOfTaxLocal__c</formula>
    <label>AMOUNT PURCHASING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/ExchangeRate__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRate__c</fullName>
    <label>EXCHANGE RATE</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/PaidAmount__c.field-meta.xml
<CustomField>
    <fullName>PaidAmount__c</fullName>
    <label>AMOUNT PAID-PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/PaidAmountLocal__c.field-meta.xml
<CustomField>
    <fullName>PaidAmountLocal__c</fullName>
    <label>AMOUNT PAID-PURCHASING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>UnitPrice__c  *  ChargeUnit__c</formula>
    <label>TOTAL AMOUNT OF PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UNIT PRICE OF PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/UnitPriceLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceLocal__c</fullName>
    <label>UNIT PRICE OF PURCHASING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/UnpaidBalance__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalance__c</fullName>
    <formula>AmountIncludedTax__c  -  PaidAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/UnpaidBalanceLocal__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalanceLocal__c</fullName>
    <formula>AmountIncludedTaxLocal__c  -  PaidAmountLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF PURCHASING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PurchasingInvoiceTriggerHandler.cls
/**
 * Created by khanhpham on 5/28/17.
 */

public with sharing class PurchasingInvoiceTriggerHandler extends AbstractTriggerHandler {
    private Map<Id, CASH_BOOK__c> toBeUpdatedCashBookMap = new Map<Id, CASH_BOOK__c>();
    private Map<Id, List<CASH_BOOK__c>> cashBooksByPIMap = new Map<Id, List<CASH_BOOK__c>>();

    public override void bulkAfter() {
        loadReferences(Trigger.new);
    }

    public override void bulkBefore() {
        if (Trigger.isDelete) {
            loadReferences(Trigger.old);
        }
    }

    public override void beforeInsert(SObject so) {
        PurchasingInvoice__c purchasingInvoice = (PurchasingInvoice__c) so;

        calculateLocalAmount(purchasingInvoice);
    }

    public override void beforeUpdate(SObject oldSo, SObject so) {
        PurchasingInvoice__c purchasingInvoice = (PurchasingInvoice__c) so;

        calculateLocalAmount(purchasingInvoice);
    }

    public override void afterUpdate(SObject oldSo, SObject so) {
        PurchasingInvoice__c oldPurchasingInvoice = (PurchasingInvoice__c) oldSo;
        PurchasingInvoice__c purchasingInvoice = (PurchasingInvoice__c) so;
        List<CASH_BOOK__c> cashBookList = cashBooksByPIMap.get(purchasingInvoice.Id);

        if (cashBookList != null && !cashBookList.isEmpty()) {
            for (CASH_BOOK__c cashBook : cashBookList) {
                if (!Util.isCashOut(cashBook)) continue;

                Boolean hasChanged = false;
                if(oldPurchasingInvoice.UnpaidBalanceLocal__c != purchasingInvoice.UnpaidBalanceLocal__c){
                    if(cashBook.TotalAmount__c == null){
                        cashBook.TotalAmount__c = 0;
                    }
                    cashBook.TotalAmount__c -= oldPurchasingInvoice.UnpaidBalanceLocal__c;
                    cashBook.TotalAmount__c += purchasingInvoice.UnpaidBalanceLocal__c;
                    hasChanged = true;
                }
                if(oldPurchasingInvoice.UnpaidBalance__c != purchasingInvoice.UnpaidBalance__c){
                    if(cashBook.TotalAmountOfCashOutUSD__c == null){
                        cashBook.TotalAmountOfCashOutUSD__c = 0;
                    }
                    cashBook.TotalAmountOfCashOutUSD__c -= oldPurchasingInvoice.UnpaidBalance__c;
                    cashBook.TotalAmountOfCashOutUSD__c += purchasingInvoice.UnpaidBalance__c;
                    hasChanged = true;
                }

                /* if (cashBook.TotalAmount__c != null && oldPurchasingInvoice.AmountIncludedTaxLocal__c != null) {
                    cashBook.TotalAmount__c -= oldPurchasingInvoice.AmountIncludedTaxLocal__c;
                    hasChanged = true;
                }

                if (cashBook.TotalAmount__c != null && purchasingInvoice.AmountIncludedTaxLocal__c != null) {
                    cashBook.TotalAmount__c += purchasingInvoice.AmountIncludedTaxLocal__c;
                    hasChanged = true;
                } else if (purchasingInvoice.AmountIncludedTaxLocal__c != null) {
                    cashBook.TotalAmount__c = purchasingInvoice.AmountIncludedTaxLocal__c;
                    hasChanged = true;
                }*/

                if (hasChanged && !toBeUpdatedCashBookMap.containsKey(cashBook.Id)) {
                    toBeUpdatedCashBookMap.put(cashBook.Id, cashBook);
                }
            }
        }
    }

    public override void beforeDelete(SObject so) {
        PurchasingInvoice__c purchasingInvoice = (PurchasingInvoice__c) so;
        List<CASH_BOOK__c> cashBookList = cashBooksByPIMap.get(purchasingInvoice.Id);

        if (cashBookList != null && !cashBookList.isEmpty()) {
            for (CASH_BOOK__c cashBook : cashBookList) {
                if (!Util.isCashOut(cashBook)) continue;

                //if (cashBook.TotalAmount__c != null && purchasingInvoice.AmountIncludedTaxLocal__c != null) {
                //    cashBook.TotalAmount__c -= purchasingInvoice.AmountIncludedTaxLocal__c;

                if(cashBook.TotalAmount__c == null){
                    cashBook.TotalAmount__c = 0;
                }
                cashBook.TotalAmount__c -= purchasingInvoice.UnpaidBalanceLocal__c;
                
                if(cashBook.TotalAmountOfCashOutUSD__c == null){
                    cashBook.TotalAmountOfCashOutUSD__c = 0;
                }
                cashBook.TotalAmountOfCashOutUSD__c -= purchasingInvoice.UnpaidBalance__c;
                if (!toBeUpdatedCashBookMap.containsKey(cashBook.Id)) {
                    toBeUpdatedCashBookMap.put(cashBook.Id, cashBook);
                }
                //}
            }
        }
    }

    private void loadReferences(List<PurchasingInvoice__c> invoices) {
        Set<Id> piIds = new Set<Id>();

        if (invoices != null && !invoices.isEmpty()) {
            for (PurchasingInvoice__c invoice : invoices) {
                piIds.add(invoice.Id);
            }
        }

        List<ConnectPurchasingInvoiceCash__c> piCashList = [
                SELECT PurchasingInvoice__c, Cashbook__c
                FROM ConnectPurchasingInvoiceCash__c
                WHERE PurchasingInvoice__c IN :piIds
        ];

        Map<Id, List<Id>> cashBookToPIList = new Map<Id, List<Id>>();
        for (ConnectPurchasingInvoiceCash__c pic : piCashList) {
            if (cashBookToPIList.containsKey(pic.Cashbook__c)) {
                cashBookToPIList.get(pic.Cashbook__c).add(pic.PurchasingInvoice__c);
            } else {
                List<Id> piIdList = new List<Id>();
                piIdList.add(pic.PurchasingInvoice__c);
                cashBookToPIList.put(pic.Cashbook__c, piIdList);
            }
        }

        // load cash book
        if (!cashBookToPIList.keySet().isEmpty()) {
            List<CASH_BOOK__c> cashBookList = [SELECT Id, 
                                                    TotalAmountCashIn__c, 
                                                    TotalAmount__c,
                                                    TotalAmountOfCashOutUSD__c,
                                                    TotalAmountOfCashInUSD__c, 
                                                    RecordTypeId FROM CASH_BOOK__c WHERE Id IN :cashBookToPIList.keySet()];

            for (CASH_BOOK__c cashBook : cashBookList) {
                List<Id> piIdList = cashBookToPIList.get(cashBook.Id);

                if (!piIdList.isEmpty()) {
                    for (Id piId : piIdList) {
                        if (cashBooksByPIMap.containsKey(piId)) {
                            cashBooksByPIMap.get(piId).add(cashBook);
                        } else {
                            List<CASH_BOOK__c> piCashBookList = new List<CASH_BOOK__c>();
                            piCashBookList.add(cashBook);
                            cashBooksByPIMap.put(piId, piCashBookList);
                        }
                    }
                }
            }
        }
    }

    private void calculateLocalAmount(PurchasingInvoice__c purchasingInvoice) {
        if (NumbericUtils.isNonZero(purchasingInvoice.ExchangeRate__c)
                && NumbericUtils.isNonZero(purchasingInvoice.UnitPrice__c)
                && NumbericUtils.isBlank(purchasingInvoice.UnitPriceLocal__c)) {
            purchasingInvoice.UnitPriceLocal__c = purchasingInvoice.ExchangeRate__c * purchasingInvoice.UnitPrice__c;
        }

        if (NumbericUtils.isNonZero(purchasingInvoice.ExchangeRate__c)
                && NumbericUtils.isNonZero(purchasingInvoice.PaidAmount__c)
                && NumbericUtils.isBlank(purchasingInvoice.PaidAmountLocal__c)) {
            purchasingInvoice.PaidAmountLocal__c = purchasingInvoice.ExchangeRate__c * purchasingInvoice.PaidAmount__c;
        }
    }
}