force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConnectKickabckCash__c/ConnectKickabckCash__c.object-meta.xml
<CustomObject>
    <description>Joint function Object to link between Kickback and Cash</description>
    <label>リベート＋現金口座</label>
    <nameField>
        <displayFormat>KC-{000000}</displayFormat>
        <label>CONNECT KICKBACK &amp; CASH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectKickabckCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_KICKBACK_CASH</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectKickabckCash__c/fields/KickbackID__c.field-meta.xml
<CustomField>
    <fullName>KickbackID__c</fullName>
    <label>KICKBACK ID</label>
    <referenceTo>Kickback__c</referenceTo>
    <relationshipName>CONNECT_KICKBACK_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kickback__c/Kickback__c.object-meta.xml
<CustomObject>
    <label>リベート</label>
    <nameField>
        <displayFormat>KB-{000000}</displayFormat>
        <label>KICKBACK ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kickback__c/fields/UnpaidBalance__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBalance__c</fullName>
    <formula>TotalKickbackAmount__c  -  PaidAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BALANCE OF KICKBACK(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/KickbackCashTriggerHandler.cls
/**
 * Created by khanhpham on 12/27/17.
 */

public with sharing class KickbackCashTriggerHandler extends AbstractTriggerHandler {
    private static Map<String, CASH_BOOK__c> cashBookMap = new Map<String, CASH_BOOK__c>();
    private static Map<String, Kickback__c> kickbackMap = new Map<String, Kickback__c>();
    private static Map<String, CASH_BOOK__c> toBeUpdatedcashBookMap = new Map<String, CASH_BOOK__c>();

    public override void bulkAfter() {
        if (Trigger.isDelete) {
            loadReferences(Trigger.old);
        } else {
            loadReferences(Trigger.new);
        }
    }

    public override void afterInsert(SObject so) {
        ConnectKickabckCash__c kickabckCash = (ConnectKickabckCash__c) so;

        updateCashBookTotalAmount(kickabckCash);
    }

    public override void afterDelete(SObject so) {
        ConnectKickabckCash__c kickabckCash = (ConnectKickabckCash__c) so;

        updateCashBookTotalAmount(kickabckCash);
    }

    // public override void andFinally() {
    //     if (toBeUpdatedcashBookMap.values().size() > 0) {
    //     }
    // }

    private void updateCashBookTotalAmount(ConnectKickabckCash__c link) {
        CASH_BOOK__c cashBook = cashBookMap.get(link.Cashbook__c);

        if (Util.isCashOut(cashBook)) {
            Kickback__c kickback = kickbackMap.get(link.KickbackID__c);

            if (cashBook != null && kickback != null) {
                if (Trigger.isInsert) {
                    if (cashBook.TotalAmount__c == null) {
                        cashBook.TotalAmount__c = kickback.UnpaidBalance__c;
                    } else {
                        cashBook.TotalAmount__c += (kickback.UnpaidBalance__c != null ? kickback.UnpaidBalance__c : 0);
                    }
                } else if (Trigger.isDelete) {
                    if (cashBook.TotalAmount__c != null && kickback.UnpaidBalance__c != null) {
                        cashBook.TotalAmount__c -= kickback.UnpaidBalance__c;
                    }
                }
                toBeUpdatedcashBookMap.put(cashBook.Id, cashBook);
            }
        }
    }

    private void loadReferences(List<ConnectKickabckCash__c> links) {
        Set<Id> cashBookIds = new Set<Id>();
        Set<Id> kickbackIds = new Set<Id>();

        for (ConnectKickabckCash__c link : links) {
            cashBookIds.add(link.Cashbook__c);
            kickbackIds.add(link.KickbackID__c);
        }

        cashBookMap = new Map<String, CASH_BOOK__c>([SELECT Id, TotalAmount__c, RecordTypeId FROM CASH_BOOK__c WHERE Id IN :cashBookIds]);
        kickbackMap = new Map<String, Kickback__c>([SELECT Id, UnpaidBalance__c FROM Kickback__c WHERE Id IN :kickbackIds]);
    }
}