force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountCashIn__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountCashIn__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashInUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashInUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashOutUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashOutUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-OUT(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit__c/Deposit__c.object-meta.xml
<CustomObject>
    <label>Deposit</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>DEPOSIT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposit__c/fields/AmountPaidToVendor__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidToVendor__c</fullName>
    <label>AMOUNT PAID TO VENDOR(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/AmountPaidToVendorLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidToVendorLocal__c</fullName>
    <label>AMOUNT PAID TO VENDOR(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/AmountReceivedFromCustomerLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedFromCustomerLocal__c</fullName>
    <label>AMOUNT RECEIVED FROM CUSTOMER(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposit__c/fields/AmountReceivedFromCustomerUSD__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedFromCustomerUSD__c</fullName>
    <label>AMOUNT RECEIVED FROM CUSTOMER(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DepositCash__c/DepositCash__c.object-meta.xml
<CustomObject>
    <label>Deposit+Cash</label>
    <nameField>
        <displayFormat>DPC-{000000}</displayFormat>
        <label>DEPOSIT+CASH ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit+Cash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DepositCash__c/fields/AmountPaidToVendorLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidToVendorLocal__c</fullName>
    <formula>Deposit__r.AmountPaidToVendorLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AMOUNT PAID TO VENDOR(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DepositCash__c/fields/AmountReceivedFromCustomerLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedFromCustomerLocal__c</fullName>
    <formula>Deposit__r.AmountReceivedFromCustomerLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AMOUNT RECEIVED FROM CUSTOMER(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DepositCash__c/fields/AmountReceivedFromCustomerUSD__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedFromCustomerUSD__c</fullName>
    <formula>Deposit__r.AmountReceivedFromCustomerUSD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AMOUNT RECEIVED FROM CUSTOMER(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DepositCash__c/fields/Cash__c.field-meta.xml
<CustomField>
    <fullName>Cash__c</fullName>
    <label>CASH</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipLabel>DEPOSIT+CASH</relationshipLabel>
    <relationshipName>DepositCash</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DepositCash__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>DEPOSIT</label>
    <referenceTo>Deposit__c</referenceTo>
    <relationshipLabel>DEPOSIT+CASH</relationshipLabel>
    <relationshipName>DepositCash</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DepositTriggerHelper.cls
public with sharing class DepositTriggerHelper {
    public static void onAfterUpdate(Map<Id, Deposit__c> depositsNewMap, Map<Id, Deposit__c> depositsOldMap){

        //List<DepositCash__c> depositCash = [SELECT Id, Cash__c, Deposit__c FROM DepositCash__c WHERE Deposit__c IN: depositsNewMap.keySet()];

        //Set<Id> cashIdSet = new Set<Id>();
        //Map<Id, List<Id>> idCashbyDepositMap = new Map<Id, List<Id>>();

        //for(DepositCash__c link : depositCash){
        //  cashIdSet.add(link.Cash__c);
        //  if(idCashbyDepositMap.containsKey(link.Deposit__c)){
        //      idCashbyDepositMap.get(link.Deposit__c).add(link.Cash__c);
        //  }else{
        //      idCashbyDepositMap.put(link.Deposit__c, new List<Id>{link.Cash__c});
        //  }
        //}

        //Map<Id, CASH_BOOK__c> cashBooksMap = new Map<Id, clofor_com_cfs__CASH_BOOK__c>([SELECT Id, 
        //                                                      TotalAmountCashIn__c, 
        //                                                      TotalAmount__c,
        //                                                      TotalAmountOfCashOutUSD__c,
        //                                                      TotalAmountOfCashInUSD__c,
        //                                                      RecordTypeId
        //                                                  FROM CASH_BOOK__c
        //                                                  WHERE Id IN: cashIdSet]);
        
        //for(Deposit__c deposit : depositsNewMap.values()){
        //  if(!idCashbyDepositMap.containsKey(deposit.Id)){
        //      continue;
        //  }

        //  for(Id cashId : idCashbyDepositMap.get(deposit.Id)){
        //      if(deposit.AmountPaidToVendorLocal__c != depositsOldMap.get(deposit.Id).AmountPaidToVendorLocal__c){
                    
        //          if(cashBooksMap.get(cashId).TotalAmount__c == null){
        //              cashBooksMap.get(cashId).TotalAmount__c = 0;
        //          }
        //          cashBooksMap.get(cashId).TotalAmount__c -= depositsOldMap.get(deposit.Id).AmountPaidToVendorLocal__c != null? depositsOldMap.get(deposit.Id).AmountPaidToVendorLocal__c : 0;
        //          cashBooksMap.get(cashId).TotalAmount__c += deposit.AmountPaidToVendorLocal__c != null? deposit.AmountPaidToVendorLocal__c :0;
        //      }
        //      if(deposit.AmountPaidToVendor__c != depositsOldMap.get(deposit.Id).AmountPaidToVendor__c){
                    
        //          if(cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c == null){
        //              cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c = 0;
        //          }
        //          cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c -= depositsOldMap.get(deposit.Id).AmountPaidToVendor__c != null? depositsOldMap.get(deposit.Id).AmountPaidToVendor__c :0;
        //          cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c += deposit.AmountPaidToVendor__c != null? deposit.AmountPaidToVendor__c :0;
        //      }
        //      if(deposit.AmountReceivedFromCustomerLocal__c != depositsOldMap.get(deposit.Id).AmountReceivedFromCustomerLocal__c){
                    
        //          if(cashBooksMap.get(cashId).TotalAmountCashIn__c == null){
        //              cashBooksMap.get(cashId).TotalAmountCashIn__c = 0;
        //          }
        //          cashBooksMap.get(cashId).TotalAmountCashIn__c -= depositsOldMap.get(deposit.Id).AmountReceivedFromCustomerLocal__c != null? depositsOldMap.get(deposit.Id).AmountReceivedFromCustomerLocal__c :0;
        //          cashBooksMap.get(cashId).TotalAmountCashIn__c += deposit.AmountReceivedFromCustomerLocal__c != null? deposit.AmountReceivedFromCustomerLocal__c :0;
        //      }
        //      if(deposit.AmountReceivedFromCustomerUSD__c != depositsOldMap.get(deposit.Id).AmountReceivedFromCustomerUSD__c){
                    
        //          if(cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c == null){
        //              cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c = 0;
        //          }
        //          cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c -= depositsOldMap.get(deposit.Id).AmountReceivedFromCustomerUSD__c != null? depositsOldMap.get(deposit.Id).AmountReceivedFromCustomerUSD__c :0;
        //          cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c += deposit.AmountReceivedFromCustomerUSD__c != null? deposit.AmountReceivedFromCustomerUSD__c :0;
        //      }

        //  }
        //}
        //try{
        //  system.debug('#####cashBooksMap' + cashBooksMap.values());
        //  update cashBooksMap.values();
        //  }catch(Exception ex){
        //      System.debug('########Error#####' + ex.getMessage());
        //}
    }

    public static void onBeforeDelete(Map<Id, Deposit__c> depositsOldMap){

        //List<DepositCash__c> depositCash = [SELECT Id, Cash__c, Deposit__c FROM DepositCash__c WHERE Deposit__c IN: depositsOldMap.keySet()];

        //Set<Id> cashIdSet = new Set<Id>();
        //Map<Id, List<Id>> idCashbyDepositMap = new Map<Id, List<Id>>();

        //for(DepositCash__c link : depositCash){
        //  cashIdSet.add(link.Cash__c);
        //  if(idCashbyDepositMap.containsKey(link.Deposit__c)){
        //      idCashbyDepositMap.get(link.Deposit__c).add(link.Cash__c);
        //  }else{
        //      idCashbyDepositMap.put(link.Deposit__c, new List<Id>{link.Cash__c});
        //  }
        //}

        //Map<Id, CASH_BOOK__c> cashBooksMap = new Map<Id, clofor_com_cfs__CASH_BOOK__c>([SELECT Id, 
        //                                                      TotalAmountCashIn__c, 
        //                                                      TotalAmount__c,
        //                                                      TotalAmountOfCashOutUSD__c,
        //                                                      TotalAmountOfCashInUSD__c,
        //                                                      RecordTypeId
        //                                                  FROM CASH_BOOK__c
        //                                                  WHERE Id IN: cashIdSet]);
        
        //for(Deposit__c deposit : depositsOldMap.values()){
        //  if(!idCashbyDepositMap.containsKey(deposit.Id)){
        //      continue;
        //  }

        //  for(Id cashId : idCashbyDepositMap.get(deposit.Id)){
                
        //      if(cashBooksMap.get(cashId).TotalAmount__c == null){
        //          cashBooksMap.get(cashId).TotalAmount__c = 0;
        //      }
        //      cashBooksMap.get(cashId).TotalAmount__c -= deposit.AmountPaidToVendorLocal__c != null? deposit.AmountPaidToVendorLocal__c : 0;
        //      if(cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c == null){
        //          cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c = 0;
        //      }
        //      cashBooksMap.get(cashId).TotalAmountOfCashOutUSD__c -= deposit.AmountPaidToVendor__c != null? deposit.AmountPaidToVendor__c : 0;
                
        //      if(cashBooksMap.get(cashId).TotalAmountCashIn__c == null){
        //          cashBooksMap.get(cashId).TotalAmountCashIn__c = 0;
        //      }
        //      cashBooksMap.get(cashId).TotalAmountCashIn__c -= deposit.AmountReceivedFromCustomerLocal__c != null? deposit.AmountReceivedFromCustomerLocal__c : 0;
                
        //      if(cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c == null){
        //          cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c = 0;
        //      }
        //      cashBooksMap.get(cashId).TotalAmountOfCashInUSD__c -= deposit.AmountReceivedFromCustomerUSD__c!= null? deposit.AmountReceivedFromCustomerUSD__c : 0;
        //  }
        //}
        //try{
        //  system.debug('#####cashBooksMap' + cashBooksMap.values());
        //  update cashBooksMap.values();
        //  }catch(Exception ex){
        //      System.debug('########Error#####' + ex.getMessage());
        //}
    }

}