force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/recordTypes/CashIn.recordType-meta.xml
<RecordType>
    <fullName>CashIn</fullName>
    <active>true</active>
    <description>To manage cash inbound transaction for local currency</description>
    <label>CASH IN</label>
</RecordType>

force-app/main/default/objects/CASH_BOOK__c/recordTypes/CashOut.recordType-meta.xml
<RecordType>
    <fullName>CashOut</fullName>
    <active>true</active>
    <description>To manage cash outbound transaction for local currency</description>
    <label>CASH OUT</label>
</RecordType>

force-app/main/default/objects/ConnectOtherCash__c/ConnectOtherCash__c.object-meta.xml
<CustomObject>
    <label>Other+Cash</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>CONN OT-CA ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other+Cash</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectOtherCash__c/fields/CashID__c.field-meta.xml
<CustomField>
    <fullName>CashID__c</fullName>
    <label>CASH ID</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipLabel>CONNECT OTHER REVENUE/COST &amp; CASH</relationshipLabel>
    <relationshipName>ConnectOtherCash</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectOtherCash__c/fields/OtherRevenueCostID__c.field-meta.xml
<CustomField>
    <fullName>OtherRevenueCostID__c</fullName>
    <label>OTHER</label>
    <referenceTo>OtherRevenueCost__c</referenceTo>
    <relationshipLabel>CONNECT OTHER &amp; CASH</relationshipLabel>
    <relationshipName>ConnectRevenueCostID</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OtherRevenueCost__c/OtherRevenueCost__c.object-meta.xml
<CustomObject>
    <label>Other</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>OTHER REVENUE &amp; COST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherRevenueCost__c/fields/AmountCollectedOtherRevenue__c.field-meta.xml
<CustomField>
    <fullName>AmountCollectedOtherRevenue__c</fullName>
    <label>AMOUNT COLLECTED-OTHER REVENUE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherRevenueCost__c/fields/AmountOtherCostIncludeTax__c.field-meta.xml
<CustomField>
    <fullName>AmountOtherCostIncludeTax__c</fullName>
    <label>AMOUNT OTHER COST INCLUDE TAX</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherRevenueCost__c/fields/AmountOtherRevenueIncludeTax__c.field-meta.xml
<CustomField>
    <fullName>AmountOtherRevenueIncludeTax__c</fullName>
    <label>AMOUNT OTHER REVENUE INCLUDE TAX</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherRevenueCost__c/fields/AmountPaidOtherCost__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidOtherCost__c</fullName>
    <label>AMOUNT PAID-OTHER COST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherRevenueCost__c/fields/OtherRevenueCostName__c.field-meta.xml
<CustomField>
    <fullName>OtherRevenueCostName__c</fullName>
    <label>OTHER REVENUE/COST NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OtherRevenueCost__c/recordTypes/OtherCost.recordType-meta.xml
<RecordType>
    <fullName>OtherCost</fullName>
    <active>true</active>
    <label>Other Cost</label>
</RecordType>

force-app/main/default/objects/OtherRevenueCost__c/recordTypes/OtherRevenue.recordType-meta.xml
<RecordType>
    <fullName>OtherRevenue</fullName>
    <active>true</active>
    <label>Other Revenue</label>
</RecordType>

force-app/main/default/classes/OtherRevenueCostTriggerHelperTest.cls
@isTest
private class OtherRevenueCostTriggerHelperTest {
	
	private static List<OtherRevenueCost__c> listRevenue = new List<OtherRevenueCost__c>();
	private static List<CASH_BOOK__c> listCash = new List<CASH_BOOK__c>();
	static{
		Custom_Application_Config__c appConfig = new Custom_Application_Config__c(
			Disabled_Trigger__c = false
			);
        FlsService.doInsert(appConfig);

		Map<String, Schema.RecordTypeInfo> mapRevenueRecordTypeByDeveloperName = Schema.getGlobalDescribe().get('clofor_com_cfs__OtherRevenueCost__c').getDescribe().getRecordTypeInfosByDeveloperName();

		OtherRevenueCost__c otherRevenue1 = new OtherRevenueCost__c(
			RecordTypeId = mapRevenueRecordTypeByDeveloperName.get('OtherCost').getRecordTypeId(),
			OtherRevenueCostName__c = 'Test1',
			AmountOtherCostIncludeTax__c = 20,
			AmountPaidOtherCost__c = 10,
			AmountOtherRevenueIncludeTax__c =20,
			AmountCollectedOtherRevenue__c = 10
			);
		OtherRevenueCost__c otherRevenue2 = new OtherRevenueCost__c(
			RecordTypeId = mapRevenueRecordTypeByDeveloperName.get('OtherRevenue').getRecordTypeId(),
			OtherRevenueCostName__c = 'Test2',
			AmountOtherCostIncludeTax__c = 20,
			AmountPaidOtherCost__c = 10,
			AmountOtherRevenueIncludeTax__c =20,
			AmountCollectedOtherRevenue__c = 10
			);

		listRevenue.add(otherRevenue1);
		listRevenue.add(otherRevenue2);
        FlsService.doInsert(listRevenue);
		
		Map<String, Schema.RecordTypeInfo> mapCashRecordTypeByDeveloperName = Schema.getGlobalDescribe().get('clofor_com_cfs__CASH_BOOK__c').getDescribe().getRecordTypeInfosByDeveloperName();

		CASH_BOOK__c cash1 = new CASH_BOOK__c(
			RecordTypeId = mapCashRecordTypeByDeveloperName.get('CashIn').getRecordTypeId()
		);
		CASH_BOOK__c cash2 = new CASH_BOOK__c(
			RecordTypeId = mapCashRecordTypeByDeveloperName.get('CashOut').getRecordTypeId()
		);

		listCash.add(cash1);
		listCash.add(cash2);

        FlsService.doInsert(listCash);

		ConnectOtherCash__c link1 = new ConnectOtherCash__c(
			CashID__c = cash1.Id,
			OtherRevenueCostID__c= otherRevenue2.Id
			);
		ConnectOtherCash__c link2 = new ConnectOtherCash__c(
			CashID__c = cash2.Id,
			OtherRevenueCostID__c = otherRevenue1.Id);

		List<ConnectOtherCash__c> listLinks = new List<ConnectOtherCash__c>();

		listLinks.add(link1);
		listLinks.add(link2);
        FlsService.doInsert(listLinks);
	} 
	@isTest static void test_method_onAfterUpdate() {
		// Implement test code
		Test.startTest();
			listRevenue[0].AmountOtherCostIncludeTax__c = 40;
			listRevenue[0].AmountOtherRevenueIncludeTax__c =40;
			FlsService.doUpdate(listRevenue);
			system.assert(listRevenue != null);
		Test.stopTest();
	}
	
	@isTest static void test_method_onBeforeDelete() {
		// Implement test code
		Test.startTest();
			FlsService.doDelete(listRevenue);
			Integer x = 1;
			system.assert(x != null);
		Test.stopTest();
	}
	
}