force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/ACTUAL_PAID_TO_VENDOR__c.field-meta.xml
<CustomField>
    <fullName>ACTUAL_PAID_TO_VENDOR__c</fullName>
    <label>ACTUAL PAID TO VENDOR/FROM CUSTOMER</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/ActualPaidToVendorWording__c.field-meta.xml
<CustomField>
    <fullName>ActualPaidToVendorWording__c</fullName>
    <label>ACTUAL PAID TO VENDOR WORDING</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CashBookTriggerHandler.cls
/**
 * Created by khanhpham on 5/22/18.
 */

public with sharing class CashBookTriggerHandler extends AbstractTriggerHandler {
    public override String getHandlerName() {
        return 'CashBookTriggerHandler';
    }

    public override void beforeInsert(SObject so) {
        CASH_BOOK__c cashBook = (CASH_BOOK__c) so;
        cashBook.ActualPaidToVendorWording__c = getWordingForNumber(cashBook.ACTUAL_PAID_TO_VENDOR__c);
    }

    public override void beforeUpdate(SObject oldSO, SObject newSO) {
        CASH_BOOK__c cashBook = (CASH_BOOK__c) newSO;
        cashBook.ActualPaidToVendorWording__c = getWordingForNumber(cashBook.ACTUAL_PAID_TO_VENDOR__c);
    }

    private String getWordingForNumber(Decimal value) {
        // Only generate wording for whole-number part
        if (value != null) {
            return NumbericUtils.convertNumberToText(value);
        }

        return '';
    }
}