force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/recordTypes/CashIn.recordType-meta.xml
<RecordType>
    <fullName>CashIn</fullName>
    <active>true</active>
    <description>To manage cash inbound transaction for local currency</description>
    <label>CASH IN</label>
</RecordType>

force-app/main/default/objects/CASH_BOOK__c/recordTypes/CashOut.recordType-meta.xml
<RecordType>
    <fullName>CashOut</fullName>
    <active>true</active>
    <description>To manage cash outbound transaction for local currency</description>
    <label>CASH OUT</label>
</RecordType>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/ConnectPurchasingInvoiceCash__c.object-meta.xml
<CustomObject>
    <label>購買発注明細＋現金入出</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>CONNECT PURCHASING INVOICE AND CASH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_PURCHASING_INVOICE_AND_CASH</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectPurchasingInvoiceCash__c/fields/PurchasingInvoice__c.field-meta.xml
<CustomField>
    <fullName>PurchasingInvoice__c</fullName>
    <label>PURCHASING INVOICE</label>
    <referenceTo>PurchasingInvoice__c</referenceTo>
    <relationshipName>CONNECT_PURCHASING_INVOICE_AND_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Application_Config__c/Custom_Application_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Application Config</label>
</CustomObject>

force-app/main/default/objects/Custom_Application_Config__c/fields/Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/PurchasingInvoice__c.object-meta.xml
<CustomObject>
    <label>購買注文明細</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PURCHASING INVOICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingInvoice__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <defaultValue>1</defaultValue>
    <label>CHARGE UNIT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/PaidAmount__c.field-meta.xml
<CustomField>
    <fullName>PaidAmount__c</fullName>
    <label>AMOUNT PAID-PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/PaidAmountLocal__c.field-meta.xml
<CustomField>
    <fullName>PaidAmountLocal__c</fullName>
    <label>AMOUNT PAID-PURCHASING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/PurchasingOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchasingOrder__c</fullName>
    <label>PURCHASING ORDER</label>
    <referenceTo>PurchasingOrder__c</referenceTo>
    <relationshipName>PURCHASING_INVOICE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <label>TAX RATE-PURCHASING</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UNIT PRICE OF PURCHASING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingInvoice__c/fields/UnitPriceLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceLocal__c</fullName>
    <label>UNIT PRICE OF PURCHASING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchasingOrder__c/PurchasingOrder__c.object-meta.xml
<CustomObject>
    <label>購買注文</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>PURCHASING ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchasingOrder__c/recordTypes/PurchasingOrder.recordType-meta.xml
<RecordType>
    <fullName>PurchasingOrder</fullName>
    <active>true</active>
    <label>Purchasing Order</label>
</RecordType>

force-app/main/default/classes/POCashTriggerHelperTest.cls
@isTest
private class POCashTriggerHelperTest {
    
    private static List<ConnectPurchasingInvoiceCash__c> lishPurchasingCash = new List<ConnectPurchasingInvoiceCash__c>();
    private static List<CASH_BOOK__c> listCash = new List<CASH_BOOK__c>();
    static{
        Custom_Application_Config__c appConfig = new Custom_Application_Config__c(
            Disabled_Trigger__c = false
            );
        insert appConfig;
        PurchasingOrder__c purchasingOrder = new PurchasingOrder__c(
            );
        insert purchasingOrder;
        PurchasingInvoice__c purchasing  = new PurchasingInvoice__c(
            UnitPriceLocal__c = 10,
            ChargeUnit__c = 1,
            UnitPrice__c = 2,
            PaidAmountLocal__c = 0,
            PaidAmount__c =1,
            TaxRate__c =10,
            PurchasingOrder__c = purchasingOrder.Id
            );
        insert purchasing;
        
        Map<String, Schema.RecordTypeInfo> mapCashRecordTypeByDeveloperName = Schema.getGlobalDescribe().get('clofor_com_cfs__CASH_BOOK__c').getDescribe().getRecordTypeInfosByDeveloperName();

        CASH_BOOK__c cash1 = new CASH_BOOK__c(
            RecordTypeId = mapCashRecordTypeByDeveloperName.get('CashIn').getRecordTypeId()
        );
        CASH_BOOK__c cash2 = new CASH_BOOK__c(
            RecordTypeId = mapCashRecordTypeByDeveloperName.get('CashOut').getRecordTypeId()
        );

        listCash.add(cash1);
        listCash.add(cash2);

        insert listCash;
        ConnectPurchasingInvoiceCash__c link1 = new ConnectPurchasingInvoiceCash__c(
            Cashbook__c = listCash[0].Id,
            PurchasingInvoice__c = purchasing.Id

        );
        ConnectPurchasingInvoiceCash__c link2 = new ConnectPurchasingInvoiceCash__c(
            Cashbook__c = listCash[1].Id,
            PurchasingInvoice__c = purchasing.Id
        );
        lishPurchasingCash.add(link1);
        lishPurchasingCash.add(link2);
        

    } 
    
    @isTest static void test_method_onAfterInsert() {
        Test.startTest();

            insert lishPurchasingCash;
            System.assert(lishPurchasingCash != null);
        Test.stopTest();    
        // Implement test code
    }
    
    @isTest static void test_method_onBeforeDelete() {
        
        insert lishPurchasingCash;
        
        Test.startTest();
        
            delete lishPurchasingCash;
            Integer x =1;
            System.assert(x != null);
        Test.stopTest();    
    }
    
}