force-app/main/default/objects/CASH_BOOK__c/CASH_BOOK__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_cashbookOnlineHelp</customHelpPage>
    <label>現金入出</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Cash ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TOTAL AMOUNT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountCashIn__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountCashIn__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashInUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashInUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-IN(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CASH_BOOK__c/fields/TotalAmountOfCashOutUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountOfCashOutUSD__c</fullName>
    <label>TOTAL AMOUNT OF CASH-OUT(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/ConnectInvoicingAndCash__c.object-meta.xml
<CustomObject>
    <description>Joint function to connect Invoicing to Cash</description>
    <label>F/TMS請求・仕入+現金入出</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>FMS BILL+CASH ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/Cashbook__c.field-meta.xml
<CustomField>
    <fullName>Cashbook__c</fullName>
    <label>CASH BOOK</label>
    <referenceTo>CASH_BOOK__c</referenceTo>
    <relationshipName>CONNECT_INVOICING_AND_CASH</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/UnpaidBuyingAmountLocal__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBuyingAmountLocal__c</fullName>
    <formula>Invoicing__r.BuyDifferentiation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BUYING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/UnpaidBuyingAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>UnpaidBuyingAmountUSD__c</fullName>
    <formula>Invoicing__r.UNPAID_BALANCE_OF_BUYING_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNPAID BUYING INCLUDING TAX(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/UnreceiveSellingAmountLocal__c.field-meta.xml
<CustomField>
    <fullName>UnreceiveSellingAmountLocal__c</fullName>
    <formula>Invoicing__r.SellDifferentiation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNRECEIVE SELLING INCLUDING TAX(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConnectInvoicingAndCash__c/fields/UnreceiveSellingAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>UnreceiveSellingAmountUSD__c</fullName>
    <formula>Invoicing__r.UNPAID_BALANCE_OF_SELLING_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNRECEIVE SELLING INCLUDING TAX(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicingCashTriggerHelper.cls
public with sharing class InvoicingCashTriggerHelper {
    public  static void onAfterInsert(List<ConnectInvoicingAndCash__c> invoiceCashs){
        /*Set<Id> cashBookIdSet = new Set<Id>();
        for(ConnectInvoicingAndCash__c link : invoiceCashs){
            cashBookIdSet.add(link.Cashbook__c);
        }

        Map<Id, CASH_BOOK__c> cashBooksMap = getCashBookById(cashBookIdSet);

        for(ConnectInvoicingAndCash__c link : invoiceCashs){
            if(cashBooksMap.containsKey(link.Cashbook__c)){

                
                // local cash out amount
                if(cashBooksMap.get(link.Cashbook__c).TotalAmount__c == null){
                    cashBooksMap.get(link.Cashbook__c).TotalAmount__c = 0;
                }

                cashBooksMap.get(link.Cashbook__c).TotalAmount__c += link.UnpaidBuyingAmountLocal__c;
                
                // usd cash out amount
                if(cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c == null){
                    cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c = 0;
                }
                system.debug('######cashBooksMap.get(link.Cashbook__c).TotalAmount__c' + cashBooksMap.get(link.Cashbook__c).TotalAmount__c);

                cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c += link.UnpaidBuyingAmountUSD__c;
                
            
                // local cash in amount
                if(cashBooksMap.get(link.Cashbook__c).TotalAmountCashIn__c == null){
                    cashBooksMap.get(link.Cashbook__c).TotalAmountCashIn__c = 0;
                }

                cashBooksMap.get(link.Cashbook__c).TotalAmountCashIn__c += link.UnreceiveSellingAmountLocal__c;
                

                // usd cash in amount
                if(cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashInUSD__c == null){
                    cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashInUSD__c = 0;
                }

                cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashInUSD__c += link.UnreceiveSellingAmountUSD__c;
                    
                
            }

        }
        try{
            update cashBooksMap.values();
            }catch(Exception ex){
                System.debug('########Error#####' + ex.getMessage());
            }*/
        

    }


    public static void onBeforeDelete(List<ConnectInvoicingAndCash__c> invoiceCashs){

        //Set<Id> cashBookIdSet = new Set<Id>();
        //for(ConnectInvoicingAndCash__c link : invoiceCashs){
        //  cashBookIdSet.add(link.Cashbook__c);
        //}

        //Map<Id, CASH_BOOK__c> cashBooksMap = getCashBookById(cashBookIdSet);

        //for(ConnectInvoicingAndCash__c link : invoiceCashs){
        //  if(cashBooksMap.containsKey(link.Cashbook__c)){
        //      // local cash out amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmount__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmount__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmount__c -= link.UnpaidBuyingAmountLocal__c;
                
        //      // usd cash out amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashOutUSD__c -= link.UnpaidBuyingAmountUSD__c;
                
            

        //      // local cash in amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmountCashIn__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmountCashIn__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmountCashIn__c -= link.UnreceiveSellingAmountLocal__c;
                

        //      // usd cash in amount
        //      if(cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashInUSD__c == null){
        //          cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashInUSD__c = 0;
        //      }

        //      cashBooksMap.get(link.Cashbook__c).TotalAmountOfCashInUSD__c -= link.UnreceiveSellingAmountUSD__c;
                    
                
        //  }

        //}
        //try{
        //  update cashBooksMap.values();
        //  }catch(Exception ex){
        //      System.debug('########Error#####' + ex.getMessage());
        //  }
        
    }

    //private static Map<Id, CASH_BOOK__c> getCashBookById(Set<Id> cashBookIdSet){

        
    //  Map<Id, CASH_BOOK__c> cashBooksMap = new Map<Id, clofor_com_cfs__CASH_BOOK__c>([SELECT Id, 
    //                                                          TotalAmountCashIn__c, 
    //                                                          TotalAmount__c,
    //                                                          TotalAmountOfCashOutUSD__c,
    //                                                          TotalAmountOfCashInUSD__c,
    //                                                          RecordTypeId
    //                                                      FROM CASH_BOOK__c
    //                                                      WHERE Id IN: cashBookIdSet]);
    //  return cashBooksMap;


    //}
}