force-app/main/default/objects/WORKER__c/WORKER__c.object-meta.xml
<CustomObject>
    <label>ドライバー・作業員</label>
    <nameField>
        <displayFormat>WK-{000000}</displayFormat>
        <label>WORKER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WORKER__c/fields/FULL_NAME__c.field-meta.xml
<CustomField>
    <fullName>FULL_NAME__c</fullName>
    <label>FULL NAME</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/WorkOrder__c.object-meta.xml
<CustomObject>
    <label>W/O</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>WORK ORDER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (DESTINATION WAREHOUSE)</relationshipLabel>
    <relationshipName>WorkOrderDestinationWarehouseID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder__c/fields/WarehouseID__c.field-meta.xml
<CustomField>
    <fullName>WarehouseID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER (ORIGIN WAREHOUSE)</relationshipLabel>
    <relationshipName>WORK_ORDER</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/WorkOrderService__c.object-meta.xml
<CustomObject>
    <label>W/O/S</label>
    <nameField>
        <displayFormat>WOS-{000000}</displayFormat>
        <label>WORK ORDER SERVICE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>W/O/S</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderService__c/fields/DestinationWarehouse__c.field-meta.xml
<CustomField>
    <fullName>DestinationWarehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DESTINATION WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-DESTINATION</relationshipLabel>
    <relationshipName>WorkOrderServiceDestination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/PreviousWos__c.field-meta.xml
<CustomField>
    <fullName>PreviousWos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PREVIOUS WORK ORDER SERVICE ID</label>
    <referenceTo>WorkOrderService__c</referenceTo>
    <relationshipLabel>NEXT WORK ORDER SERVICE</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/ScheduledEndTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledEndTime__c</fullName>
    <label>SCHEDULED END TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/ScheduledStartTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledStartTime__c</fullName>
    <label>SCHEDULED START TIME</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/ServiceStage__c.field-meta.xml
<CustomField>
    <fullName>ServiceStage__c</fullName>
    <description>Unique key within a process, used to identify the service in a process</description>
    <inlineHelpText>Unique key within a process, used to identify the service in a process</inlineHelpText>
    <label>Service Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASRequirement__c.field-meta.xml
<CustomField>
    <fullName>VASRequirement__c</fullName>
    <label>VAS REQUIREMENT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/VASServiceType__c.field-meta.xml
<CustomField>
    <fullName>VASServiceType__c</fullName>
    <label>VAS SERVICE TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueAddedServiceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WAREHOUSE ID</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>WORK ORDER SERVICE-ORIGIN</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderService__c/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>WORK ORDER</label>
    <referenceTo>WorkOrder__c</referenceTo>
    <relationshipLabel>WMS W/O/S</relationshipLabel>
    <relationshipName>WorkOrderService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/ValueAddedServiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Quality Check</fullName>
        <default>true</default>
        <label>Quality Check</label>
    </customValue>
    <customValue>
        <fullName>Quality Assurance</fullName>
    </customValue>
    <customValue>
        <fullName>Damage Root-cause Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>Labelling</fullName>
    </customValue>
    <customValue>
        <fullName>Sorting</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Split Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Packing/Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Measuring</fullName>
    </customValue>
    <customValue>
        <fullName>Marking</fullName>
    </customValue>
    <customValue>
        <fullName>Repairing</fullName>
    </customValue>
    <customValue>
        <fullName>Consol</fullName>
    </customValue>
    <customValue>
        <fullName>De-Consol</fullName>
    </customValue>
    <customValue>
        <fullName>Fumigation</fullName>
    </customValue>
    <customValue>
        <fullName>Kitting</fullName>
    </customValue>
    <customValue>
        <fullName>Assembling</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Physical Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Cyclic Counting</fullName>
    </customValue>
    <customValue>
        <fullName>Elimination of Losts From Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Updates</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Reconditioning</fullName>
        <isActive>false</isActive>
        <label>Reconditioning</label>
    </customValue>
    <customValue>
        <fullName>Accumulating</fullName>
        <isActive>false</isActive>
        <label>Accumulating</label>
    </customValue>
    <masterLabel>VALUE ADDED SERVICE TYPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WMS_AssignResource.cls
public with sharing class WMS_AssignResource {

    @AuraEnabled
    public static Object getInfo(Id recordId){
        List<Map<String, String>> picklistStatus = new List<Map<String, String>>();

		for (PicklistEntry item : clofor_com_cfs__WorkOrderService__c.clofor_com_cfs__Status__c.getDescribe().getPicklistValues()) {
			picklistStatus.add(new Map<String, String>{ 'label' => item.Label, 'value' => item.Value });
		}
        
        List<Map<String, String>> picklistWorker = new List<Map<String, String>>();
        for(WORKER__c worker : [ SELECT Id, Name FROM WORKER__c Limit 50000]){
            picklistWorker.add(new Map<String, String>{'label' => worker.Name, 'value' => worker.Id});
        }
        
        return new Map<String, Object>{
            'workOrder' => (WorkOrder__c)[
				SELECT
					RecordType.Name, RecordType.DeveloperName, WarehouseId__c, DestinationWarehouse__c,
					(
						SELECT Id, Warehouse__c, DestinationWarehouse__c, VASServiceType__c, VASRequirement__c, 
                        		ServiceStage__c, RecordTypeId, ScheduledStartTime__c, ScheduledEndTime__c 
                        FROM WorkOrderService__r
					)
				FROM WorkOrder__c
				WHERE Id = :recordId
			],
            'workOrderServices' => [
                SELECT Id, Warehouse__c, DestinationWarehouse__c, VASServiceType__c, VASRequirement__c, 
                        		ServiceStage__c, RecordTypeId, ScheduledStartTime__c, ScheduledEndTime__c 
                FROM WorkOrderService__c 
            	WHERE WorkOrder__c = :recordId ],
            'serviceRecordTypes' => [
				SELECT Id, Name, DeveloperName
				FROM RecordType
				WHERE SobjectType = 'clofor_com_cfs__WorkOrderService__c'
			],
        	'picklistStatus' => picklistStatus,
            'picklistWorker' => picklistWorker
        };
    }
    
	@AuraEnabled
    public static String getWorkOrderWarehouseId(Id recordId){
        return [SELECT WarehouseId__c FROM WorkOrder__c WHERE Id = :recordId].WarehouseId__c;
    }
	@AuraEnabled
    public static List<Map<String, String>> getWorkerRole(){
        List<Map<String, String>> options = new List<Map<String, String>>();
        Schema.DescribeFieldResult fieldResult = clofor_com_cfs__ConnectWOSWorker__c.clofor_com_cfs__WorkRole__c.getDescribe();
        List<Schema.PicklistEntry> role = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry value: role) {
            options.add(new Map<String, String>{ 'label' => value.getLabel(), 'value' => value.getValue() });
        }
        return options;
    }
    
    @AuraEnabled
    public static List<clofor_com_cfs__WORKER__c> getWorker(){
        List<clofor_com_cfs__WORKER__c> listWorker = new List<clofor_com_cfs__WORKER__c>();
        listWorker = [SELECT Id, Name, FULL_NAME__c FROM clofor_com_cfs__WORKER__c Limit 50000];
        return listWorker;
    }
    @AuraEnabled
    public static List<Map<String, String>> getWorkOrderStatus(){
        List<Map<String, String>> options = new List<Map<String, String>>();
        Schema.DescribeFieldResult fieldResult = clofor_com_cfs__WorkOrderService__c.clofor_com_cfs__Status__c.getDescribe();
        List<Schema.PicklistEntry> role = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry value: role) {
            options.add(new Map<String, String>{ 'label' => value.getLabel(), 'value' => value.getValue() });
        }
        return options;
    }
    
	/*

	*/
	@AuraEnabled
    public static List <clofor_com_cfs__WorkOrderService__c> getWorkOrderService(String strTab, String recIdWorkOder) {
        WorkOrder__c wo = [SELECT WarehouseId__c FROM WorkOrder__c WHERE Id = :recIdWorkOder];
        List <clofor_com_cfs__WorkOrderService__c> lstOrderService = new List <clofor_com_cfs__WorkOrderService__c>();
        if(strTab == 'ORIGIN'){
            lstOrderService =  [SELECT Name
                                		, clofor_com_cfs__ScheduledStartTime__c
                                		, clofor_com_cfs__ScheduledEndTime__c
                                        , clofor_com_cfs__Status__c
                                        , clofor_com_cfs__FinalQuantityRollUp__c
                                        , RecordType.DeveloperName
                                FROM clofor_com_cfs__WorkOrderService__c
                                WHERE clofor_com_cfs__WorkOrder__c =:recIdWorkOder
                                    AND Warehouse__c = :wo.WarehouseId__c
                                    AND clofor_com_cfs__DestinationWarehouse__c = NULL];
        }else if(strTab == 'DESNATIONS'){
             lstOrderService =  [SELECT Id
                                 		, Name
                                 		, clofor_com_cfs__ScheduledStartTime__c
                                		, clofor_com_cfs__ScheduledEndTime__c
                                        , clofor_com_cfs__Status__c
                                        , clofor_com_cfs__FinalQuantityRollUp__c
                                        , RecordType.DeveloperName
                                FROM clofor_com_cfs__WorkOrderService__c
                                WHERE clofor_com_cfs__WorkOrder__c =:recIdWorkOder
                                    AND (clofor_com_cfs__DestinationWarehouse__c != NULL OR Warehouse__c != :wo.WarehouseId__c)];
        }
        return lstOrderService;
    }

    @AuraEnabled
    public static String createConnectWorker(  List<String> lstIdWorkOrderService
                                                       , List<clofor_com_cfs__ConnectWOSWorker__c> lstConnectWorker
                                                       , clofor_com_cfs__WorkOrderService__c updateInfor
                                                       , String strIdWorkOrder){
       // List Connect Worker 
       List<clofor_com_cfs__ConnectWOSWorker__c> lstConnectWorkerForInsert = new List<clofor_com_cfs__ConnectWOSWorker__c>();
       List<clofor_com_cfs__WorkOrderService__c> lstWorkOrderServiceUpdate = new List<clofor_com_cfs__WorkOrderService__c>();
       lstWorkOrderServiceUpdate = [SELECT Id
                                    		, clofor_com_cfs__Locator__c
                                    		, clofor_com_cfs__Status__c
                                    		, clofor_com_cfs__ScheduledStartTime__c
                                   			, clofor_com_cfs__ScheduledEndTime__c
                                   FROM clofor_com_cfs__WorkOrderService__c
                                   WHERE Id IN :lstIdWorkOrderService ];
       if(lstIdWorkOrderService.isEmpty() && (!String.isBlank(updateInfor.clofor_com_cfs__Locator__c)
          || !String.isBlank(updateInfor.clofor_com_cfs__Status__c)
          || updateInfor.clofor_com_cfs__ScheduledStartTime__c != null
          || updateInfor.clofor_com_cfs__ScheduledEndTime__c != null)){
             lstWorkOrderServiceUpdate = [SELECT Id
                                    		, clofor_com_cfs__Locator__c
                                    		, clofor_com_cfs__Status__c
                                    		, clofor_com_cfs__ScheduledStartTime__c
                                   			, clofor_com_cfs__ScheduledEndTime__c
                                   FROM clofor_com_cfs__WorkOrderService__c
                                   WHERE clofor_com_cfs__WorkOrder__c =:strIdWorkOrder ];                                                  
       }                                                  
       for(clofor_com_cfs__WorkOrderService__c wos : lstWorkOrderServiceUpdate){
           if(!String.isBlank(updateInfor.clofor_com_cfs__Locator__c)){
               wos.clofor_com_cfs__Locator__c = updateInfor.clofor_com_cfs__Locator__c;
           }
           if(!String.isBlank(updateInfor.clofor_com_cfs__Status__c)){
               wos.clofor_com_cfs__Status__c = updateInfor.clofor_com_cfs__Status__c;
           }
           
           if(updateInfor.clofor_com_cfs__ScheduledStartTime__c != null){
               wos.clofor_com_cfs__ScheduledStartTime__c = updateInfor.clofor_com_cfs__ScheduledStartTime__c;
           }
           if(updateInfor.clofor_com_cfs__ScheduledEndTime__c != null){
               wos.clofor_com_cfs__ScheduledEndTime__c = updateInfor.clofor_com_cfs__ScheduledEndTime__c;
           }
           for(clofor_com_cfs__ConnectWOSWorker__c connectWoker : lstConnectWorker){
               clofor_com_cfs__ConnectWOSWorker__c wk = new clofor_com_cfs__ConnectWOSWorker__c();
               wk.clofor_com_cfs__WorkOrderService__c = wos.Id;
               wk.clofor_com_cfs__Worker__c  = connectWoker.clofor_com_cfs__Worker__c;
               wk.clofor_com_cfs__WorkRole__c  = connectWoker.clofor_com_cfs__WorkRole__c;
               lstConnectWorkerForInsert.add(wk);
           }
        }
        String oErrorMsg = '';
        try{
            if(!lstWorkOrderServiceUpdate.isEmpty()){
                FlsService.doUpdate(lstWorkOrderServiceUpdate);
            }
            if(!lstConnectWorkerForInsert.isEmpty()){
                FlsService.doUpsert(lstConnectWorkerForInsert);
            }
        }catch(Exception ex){
            oErrorMsg = ex.getStackTraceString() + ': ' + ex.getMessage();
        }
        return oErrorMsg;
    }
}