force-app/main/default/objects/MgmtMaster__c/MgmtMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ExchangeRateOnlineHelp</customHelpPage>
    <description>為替や管理基準を管理するオブジェクト
Standard Exchange Rate</description>
    <label>為替</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>EXCHANGE RATE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_End_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_fromto__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_fromto__c</fullName>
    <label>EXCHANGE CURRENCY (FROM USD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_Validity__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_Validity__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>After creating exchange rate management record, press &apos;Submit for Approval&apos; button. After the review and approval by accounting team, it will be automatically activated.</inlineHelpText>
    <label>ACTIVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExchangeRateTriggerHandler.cls
/* 15-Jun-2019 | Remove exchange rate duplication rules */
public class ExchangeRateTriggerHandler {/* extends AbstractTriggerHandler {
    private List<MgmtMaster__c> exchangeRates = new List<MgmtMaster__c>();
    private static TranslationService translationService;
    
    static {
        translationService = new TranslationService('ERROR', UserInfo.getLanguage());
    }
    
    public override String getHandlerName() {
        return 'ExchangeRateTriggerHandler';
    }
    
    public override void bulkBefore() {
        loadValidExchangeRates();
    }
    
	public override void beforeInsert(SObject so) {
        MgmtMaster__c exchangeRate = (MgmtMaster__c) so;
        checkDuplicatedExchangeRate(exchangeRate);            
    }
    
    public override void beforeUpdate(SObject oldSo, SObject so) {
        MgmtMaster__c exchangeRate = (MgmtMaster__c) so;
        checkDuplicatedExchangeRate(exchangeRate);
    }
    
    private void loadValidExchangeRates() {
        exchangeRates = [SELECT Id, Name, Mgmt_Exrate_Start_Date__c, Mgmt_Exrate_End_Date__c, Mgmt_Exrate_fromto__c 
                         FROM MgmtMaster__c 
                         WHERE Mgmt_Exrate_Validity__c = True]; 
    }
    
    private void checkDuplicatedExchangeRate(MgmtMaster__c exchangeRate) {
        if (exchangeRates != null && !exchangeRates.isEmpty() && exchangeRate.Mgmt_Exrate_Validity__c) { 
            for (MgmtMaster__c exRate : exchangeRates) {
                if (exRate.Id != exchangeRate.Id 
                    	&& exchangeRate.Mgmt_Exrate_fromto__c.equals(exRate.Mgmt_Exrate_fromto__c)
                    	&& exchangeRate.Mgmt_Exrate_Start_Date__c <= exRate.Mgmt_Exrate_End_Date__c 
                    	&& exchangeRate.Mgmt_Exrate_End_Date__c >= exRate.Mgmt_Exrate_Start_Date__c) {
					String fullFileURL = URL.getSalesforceBaseUrl().toExternalForm();
                    String errorMessage = translationService.getTranslation(Constants.OVERLAPPED_EXCHANGE_RATE) + ' <a href="' + fullFileURL + '/' 
                            + exRate.Id + '" target="_blank">' + exRate.Name + '</a>';
                    Trigger.new[0].addError(new TriggerException(errorMessage), false);
				}
            }
        }
    }
    */
}