force-app/main/default/objects/MgmtMaster__c/MgmtMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ExchangeRateOnlineHelp</customHelpPage>
    <description>為替や管理基準を管理するオブジェクト
Standard Exchange Rate</description>
    <label>為替</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>EXCHANGE RATE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_End_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_fromto__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_fromto__c</fullName>
    <label>EXCHANGE CURRENCY (FROM USD)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VND - Vietnam Dong</fullName>
                <default>true</default>
                <label>VND - Vietnam Dong</label>
            </value>
            <value>
                <fullName>KHR - Cambodian Riel</fullName>
            </value>
            <value>
                <fullName>JPY - Japanese Yen</fullName>
            </value>
            <value>
                <fullName>KRW - Korean Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_Validity__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_Validity__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>After creating exchange rate management record, press &apos;Submit for Approval&apos; button. After the review and approval by accounting team, it will be automatically activated.</inlineHelpText>
    <label>ACTIVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Master_type__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Master_type__c</fullName>
    <label>MANAGEMENT CATEGORY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>為替管理</fullName>
                <default>true</default>
                <label>為替管理</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExchangeRateValidationBatchTest.cls
@isTest
public class ExchangeRateValidationBatchTest {
    testmethod static void shouldInvalidatePassedExchangeRates() {
        Date currentDate = System.today();
        Date startDate = currentDate.addDays(-30);
        Date endDate = currentDate.addDays(-1);
        Date startDate1 = currentDate;
        Date endDate1 = currentDate.addDays(10);
        
        Map<String, Object> additionalFields = new Map<String, Object>{'Mgmt_Exrate_Validity__c' => true,
													'Mgmt_Exrate_End_Date__c' => endDate, 'Mgmt_Exrate_Start_Date__c' => startDate,
            										'Mgmt_Master_type__c' => '為替管理', 'Mgmt_Exrate_fromto__c' => 'JPY - Japanese Yen'};
        MgmtMaster__c passedExRate = (MgmtMaster__c) TestDataFactory.createSObject(new MgmtMaster__c(), true, additionalFields);
        
        additionalFields = new Map<String, Object>{'Mgmt_Exrate_Validity__c' => true, 'Mgmt_Exrate_End_Date__c' => endDate1, 
            									'Mgmt_Exrate_Start_Date__c' => startDate1,
            									'Mgmt_Master_type__c' => '為替管理', 'Mgmt_Exrate_fromto__c' => 'JPY - Japanese Yen'};
        MgmtMaster__c liveExRate = (MgmtMaster__c) TestDataFactory.createSObject(new MgmtMaster__c(), true, additionalFields);
        
        Test.startTest();
      	ExchangeRateValidationBatch batch = new ExchangeRateValidationBatch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        MgmtMaster__c actual = [SELECT Id, Mgmt_Exrate_Validity__c FROM MgmtMaster__c WHERE Id = :passedExRate.Id];
        System.assertEquals(false, actual.Mgmt_Exrate_Validity__c);
        
        actual = [SELECT Id, Mgmt_Exrate_Validity__c FROM MgmtMaster__c WHERE Id = :liveExRate.Id];
        System.assertEquals(true, actual.Mgmt_Exrate_Validity__c);
    }
    
    testmethod static void shouldExecuteScheduledJob() {
        String CRON_EXP = '0 0 0 16 4 ? 2024';
        
        Test.startTest();
        System.schedule('ExchangeRateValidationScheduler', CRON_EXP, new ExchangeRateValidationScheduler());
        Test.stopTest();
        
        System.assert(true);
    }
}