force-app/main/default/objects/MgmtMaster__c/MgmtMaster__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ExchangeRateOnlineHelp</customHelpPage>
    <description>為替や管理基準を管理するオブジェクト
Standard Exchange Rate</description>
    <label>為替</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>EXCHANGE RATE ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_End_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MgmtMaster__c/fields/Mgmt_Exrate_Validity__c.field-meta.xml
<CustomField>
    <fullName>Mgmt_Exrate_Validity__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>After creating exchange rate management record, press &apos;Submit for Approval&apos; button. After the review and approval by accounting team, it will be automatically activated.</inlineHelpText>
    <label>ACTIVE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExchangeRateValidationBatch.cls
/**
 * The batch job will find any Exchange Rate that effective period was passed and invalidate them.
 * Note: It is necessary to setup a Apex job run at the beginning for the day such as 0:00 AM
 */ 
global with sharing class ExchangeRateValidationBatch implements Database.Batchable<SObject> {
	global final String query;
    
    global ExchangeRateValidationBatch() {
        DateTime currentTime = System.now();
        
        query = 'SELECT Mgmt_Exrate_Validity__c FROM MgmtMaster__c ' + 
            	'WHERE (Mgmt_Exrate_Validity__c = True) AND (Mgmt_Exrate_End_Date__c < ' + currentTime.format('yyyy-MM-dd') + ')';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        for (SObject s : scope) {
            MgmtMaster__c exRate = (MgmtMaster__c) s;
            exRate.Mgmt_Exrate_Validity__c = false;
        }
        
        FlsService.doUpdate(scope);
    }
    
    global void finish(Database.BatchableContext bc) {}
}