force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Provide multiple language ability.
Need to update on PostInstallationSetup also.</description>
    <label>Translation</label>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Where to use?</description>
    <inlineHelpText>Where to use?</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/en_US__c.field-meta.xml
<CustomField>
    <fullName>en_US__c</fullName>
    <description>in English</description>
    <inlineHelpText>in English</inlineHelpText>
    <label>en_US</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/ja__c.field-meta.xml
<CustomField>
    <fullName>ja__c</fullName>
    <description>in Japanese</description>
    <inlineHelpText>in Japanese</inlineHelpText>
    <label>ja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/vi__c.field-meta.xml
<CustomField>
    <fullName>vi__c</fullName>
    <description>in Vietnamese</description>
    <inlineHelpText>in Vietnamese</inlineHelpText>
    <label>vi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TranslationServiceTest.cls
@isTest
private class TranslationServiceTest {
    @testSetup static void setUp() {
        Map<String, Object> additionalFields = new Map<String, Object>{'Context__c' => 'TEST', 'Active__c' => true,
            'Name' => 'greeting', 'en_US__c' => 'Hello', 'vi__c' => 'Xin chào', 'ja__c' => 'こんにちは'};
		TestDataFactory.createSObject(new Translation__c(), true, additionalFields);
    }
    
    testmethod static void shouldReturnTranslationInEnglish() {
        TranslationService service = new TranslationService('TEST', 'en_US');
        
        Test.startTest();
        
        System.assertEquals('Hello', service.getTranslation('greeting'));
        String message = service.getTranslation('COST_ALLOCATION_MSG','Cost Allocation has been balanced successfully');
        String langCode = UserInfo.getLanguage();
        Map<String, Object> translate = TranslationService.getByLanguage(langCode.substringBefore('_'));
        
        Map<String, String> translations = service.getTranslations();
        System.assertEquals('Hello', translations.get('greeting'));
        
        
        Test.stopTest();
    }   
    
    testmethod static void shouldReturnTranslationInVietnamese() {
        TranslationService service = new TranslationService('TEST', 'vi');
        
        Test.startTest();
        
        System.assertEquals('Xin chào', service.getTranslation('greeting'));
        
        Map<String, String> translations = service.getTranslations();
        System.assertEquals('Xin chào', translations.get('greeting'));
        Map<String, Object> translate = TranslationService.getByLanguage('en_US');
        
        Test.stopTest();
    }
    
    testmethod static void shouldReturnTranslationInJapanese() {
        TranslationService service = new TranslationService('TEST', 'ja');
        
        Test.startTest();
        
        System.assertEquals('こんにちは', service.getTranslation('greeting'));
        
        Map<String, String> translations = service.getTranslations();
        Map<String, Object> translate = TranslationService.getByLanguage('');
        System.assertEquals('こんにちは', translations.get('greeting'));
        System.assertEquals('', service.getTranslation('nonexistence'));
        
        Test.stopTest();
    }
}