force-app/main/default/objects/Flow_Sub_Tab_Setting__c/Flow_Sub_Tab_Setting__c.object-meta.xml
<CustomObject>
    <label>Flow Sub Tab Setting</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Flow Sub Tab Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flow Sub Tab Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flow_Sub_Tab_Setting__c/fields/Developer_Name_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Developer_Name_Record_Type__c</fullName>
    <label>Developer Name Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Sub_Tab_Setting__c/fields/ParentTab__c.field-meta.xml
<CustomField>
    <fullName>ParentTab__c</fullName>
    <label>Flow Tab Setting</label>
    <referenceTo>Flow_Tab_Setting__c</referenceTo>
    <relationshipLabel>Flow Sub Tab Settings</relationshipLabel>
    <relationshipName>Flow_Sub_Tab_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/Flow_Tab_Setting__c.object-meta.xml
<CustomObject>
    <label>Flow Tab Setting</label>
    <nameField>
        <displayFormat>FL-{00000}</displayFormat>
        <label>Flow Tab Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flow Tab Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/API_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Object_Name__c</fullName>
    <label>API Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FMS</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CloWTM-EBooking &amp; Cargo Tracking Module</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>CloCRM-Cust/Ptnr/Vendor Relationship and Pricing Module</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>CloCRM-Quotation &amp; Contract</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CloFMS-Forwarding System</label>
            </value>
            <value>
                <fullName>CloSMS-Ship System</fullName>
            </value>
            <value>
                <fullName>CloTOS-Terminal System</fullName>
            </value>
            <value>
                <fullName>5</fullName>
                <label>CloTMS-Transportation System</label>
            </value>
            <value>
                <fullName>TRS</fullName>
                <label>CloTRS-Trading System</label>
            </value>
            <value>
                <fullName>WMS</fullName>
                <label>CloWMS-Warehouse System</label>
            </value>
            <value>
                <fullName>CloIoT</fullName>
                <label>CloIoT-IoT Integration</label>
            </value>
            <value>
                <fullName>INV</fullName>
                <label>CloINV-Inventory Module</label>
            </value>
            <value>
                <fullName>CloAuditModule</fullName>
                <label>CloAudit-Audit/Inventory Check Module</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>CloLog-Logistic Module</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>CloCSM-Consolidation Module</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>CloFIM-JP24H AFR Module</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>CloFCM-Facility Module</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CloASM-Asset Module</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>CloACM-Accounting Module-FMS/TMS</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CloACM-Accounting Module-WMS</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>CloACM-Accounting Module-Shared Accounting Service</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>CloACM-Accounting Module-Purchasing/Expenses &amp; Management</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>CloACM-Accounting Module-Transaction</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>CloFRM-Financial Report Module</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>CloCha-Chatter Module</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>CloHRM-Human Resource Module</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>CloKPI-KPI Module</label>
            </value>
            <value>
                <fullName>API</fullName>
                <label>CloAPI-API Module for External Integration</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CloSCM Package-Customization</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>CloSCM Package-Setup</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Flow_Style__c.field-meta.xml
<CustomField>
    <fullName>Flow_Style__c</fullName>
    <label>Flow Style</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Report_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Developer_Name__c</fullName>
    <label>Report Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Tab_Link__c.field-meta.xml
<CustomField>
    <fullName>Tab_Link__c</fullName>
    <label>Tab Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Tab_Name__c.field-meta.xml
<CustomField>
    <fullName>Tab_Name__c</fullName>
    <label>Tab Name Default</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Tab_Order__c.field-meta.xml
<CustomField>
    <fullName>Tab_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Tab Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flow_Tab_Setting__c/fields/Tab_Style__c.field-meta.xml
<CustomField>
    <fullName>Tab_Style__c</fullName>
    <label>Tab Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>User Info</fullName>
            </value>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>View</fullName>
                <isActive>false</isActive>
                <label>View</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/New_NavigationFlowControllerTest.cls
@isTest
private class New_NavigationFlowControllerTest {
	private static List<Flow_Tab_Setting__c> flowtabList = new List<Flow_Tab_Setting__c>();
	
	private static Flow_Sub_Tab_Setting__c subTabSetting = new Flow_Sub_Tab_Setting__c();
	static{

		Flow_Tab_Setting__c tab1 = new Flow_Tab_Setting__c(
				Tab_Style__c = 'Link',
				Is_Active__c = true,
				Flow__c = '1',
				Tab_Link__c='/001',
				Tab_Order__c = 1,
				Tab_Name__c = 'tab 1',
				Flow_Style__c = 'Flow',
				External_Id__c = 1

			);
		Flow_Tab_Setting__c tab2 = new Flow_Tab_Setting__c(
				Tab_Style__c = 'Object',
				Is_Active__c = true,
				Flow__c = '1',
				API_Object_Name__c = 'clofor_com_cfs__Stock__c',
				Tab_Order__c = 2,
				Tab_Name__c = 'tab 2',
				Flow_Style__c = 'Flow',
				External_Id__c = 2
			);

		Flow_Tab_Setting__c tab3 = new Flow_Tab_Setting__c(
				Tab_Style__c = 'Report',
				Is_Active__c = true,
				Flow__c = '1',
				Report_Developer_Name__c = 'Account',
				Tab_Order__c = 3,
				Tab_Name__c = 'tab 3',
				Flow_Style__c = 'Flow',
				External_Id__c = 3
			);

		flowtabList.add(tab1);
		flowtabList.add(tab2);
		flowtabList.add(tab3);
        FlsService.doInsert(flowtabList);
		subTabSetting = new Flow_Sub_Tab_Setting__c(
			
			ParentTab__c = tab2.Id,
			Developer_Name_Record_Type__c = 'StockIn'
			);
        FlsService.doInsert(subTabSetting);
	}

	@isTest static void test_method_one() {
		// Implement test code
		Test.startTest();
		New_NavigationFlowController ctrl = new New_NavigationFlowController();
		ctrl.getListFlows();
		Test.stopTest();
		system.assertEquals(ctrl.languageSettingTab.subTabs.size(), 0);
	}
	
	
	
}