force-app/main/default/objects/Container_Info__c/Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Info__c/fields/Container_NO__c.field-meta.xml
<CustomField>
    <fullName>Container_NO__c</fullName>
    <inlineHelpText>Please enter 11digits(4digit container ownership code+7digit container code)</inlineHelpText>
    <label>CONTAINER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/GOODS__c.field-meta.xml
<CustomField>
    <fullName>GOODS__c</fullName>
    <label>DESCRIPTION OF GOODS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/GROSS_WEIGHT__c.field-meta.xml
<CustomField>
    <fullName>GROSS_WEIGHT__c</fullName>
    <label>GROSS WEIGHT(KG)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>HBL_SHIPMENT__c</fullName>
    <label>H B/L SHIPMENT</label>
    <referenceTo>CustomObject1__c</referenceTo>
    <relationshipName>Container_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>F/TMS CNTR (P.O.D)</relationshipLabel>
    <relationshipName>FTMSCNTRPOD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/POL__c.field-meta.xml
<CustomField>
    <fullName>POL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>F/TMS CNTR (P.O.L)</relationshipLabel>
    <relationshipName>FTMSCNTRPOL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Container_Info__c/fields/Seal_No__c.field-meta.xml
<CustomField>
    <fullName>Seal_No__c</fullName>
    <label>SEAL NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObject1__c/fields/ADDRESS_ON_B_L__c.field-meta.xml
<CustomField>
    <fullName>ADDRESS_ON_B_L__c</fullName>
    <inlineHelpText>Input the Address for L/C or special case when Address on B/L is different from English Address.</inlineHelpText>
    <label>SHIPPER ADDRESS ON B/L</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/CARGO_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARGO_TYPE__c</fullName>
    <label>CARGO TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CY/CY</fullName>
            </value>
            <value>
                <fullName>CFS/CFS</fullName>
            </value>
            <value>
                <fullName>CY/CFS</fullName>
            </value>
            <value>
                <fullName>CFS/CY</fullName>
            </value>
            <value>
                <fullName>FCL/FCL</fullName>
            </value>
            <value>
                <fullName>LCL/LCL</fullName>
            </value>
            <value>
                <fullName>FCL/LCL</fullName>
            </value>
            <value>
                <fullName>LCL/FCL</fullName>
            </value>
            <value>
                <fullName>FI/CY</fullName>
            </value>
            <value>
                <fullName>CY/FO</fullName>
            </value>
            <value>
                <fullName>FI/FO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/carton__c.field-meta.xml
<CustomField>
    <fullName>carton__c</fullName>
    <inlineHelpText>Synchronized with Sum of Cargo Quantity in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are not null, Cargo Quantity in CNTR IN TRANS is not Null.</inlineHelpText>
    <label>QUANTITY(TOTAL PACKAGES)</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/CNEE_ADDRESS_ON_B_L__c.field-meta.xml
<CustomField>
    <fullName>CNEE_ADDRESS_ON_B_L__c</fullName>
    <inlineHelpText>Input the CNEE company name and Address for B/L or special case when Address on B/L is different from English Address.</inlineHelpText>
    <label>CNEE ADDRESS ON B/L</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/DATE_OF_MASTER_BL_ISSUED__c.field-meta.xml
<CustomField>
    <fullName>DATE_OF_MASTER_BL_ISSUED__c</fullName>
    <label>DATE OF MASTER B/L ISSUED</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <label>Gross Weight</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/HBL_Number_SEA_AIR__c.field-meta.xml
<CustomField>
    <fullName>HBL_Number_SEA_AIR__c</fullName>
    <formula>IF ( ISNULL(HBL__c) || ISBLANK(HBL__c) ,  HAWB__c , HBL__c)</formula>
    <label>HBL Number（SEAorAIR）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/MBL_Number_SEA_AIR__c.field-meta.xml
<CustomField>
    <fullName>MBL_Number_SEA_AIR__c</fullName>
    <formula>IF (ISNULL(Master_B_L__c) || ISBLANK(Master_B_L__c) , MAWB__c , Master_B_L__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MBL Number（SEAorAIR）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/NOTIFY_ADDRESS_ON_B_L__c.field-meta.xml
<CustomField>
    <fullName>NOTIFY_ADDRESS_ON_B_L__c</fullName>
    <inlineHelpText>Input the Notify company name and Address for B/L or special case when Address on B/L is different from English Address.</inlineHelpText>
    <label>NOTIFY ADDRESS ON B/L</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Place_Of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Place_Of_Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Delivery</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_DELIVERY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Place_Of_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Place_Of_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place Of Receipt</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_RECEIPT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/POD__c.field-meta.xml
<CustomField>
    <fullName>POD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/POL__c.field-meta.xml
<CustomField>
    <fullName>POL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/PrintDate__c.field-meta.xml
<CustomField>
    <fullName>PrintDate__c</fullName>
    <formula>if(LEN( text(PrinteDate_ED__c) ) &gt; 0 , PrinteDate_ED__c , TODAY() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>if Fixed Issue Date(If Fixed) is not set, automatically will be set as today.</inlineHelpText>
    <label>DATE INVOICE ISSUED</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <inlineHelpText>Remarks show on A/N, S/I, Cargo Manifest</inlineHelpText>
    <label>REMARKS FOR OFFICIAL DOCUMENT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TranporationType__c.field-meta.xml
<CustomField>
    <fullName>TranporationType__c</fullName>
    <label>CONTAINER MODE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>MTY</fullName>
            </value>
            <value>
                <fullName>MTY &amp; FCL</fullName>
            </value>
            <value>
                <fullName>Consol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/TS__c.field-meta.xml
<CustomField>
    <fullName>TS__c</fullName>
    <inlineHelpText>Input the transit port of the shipment. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. Transit Port in final Transit record  will be automatically inserted in this field.</inlineHelpText>
    <label>TRANSIT PORT</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomObject1__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bag</fullName>
            </value>
            <value>
                <fullName>Bale</fullName>
            </value>
            <value>
                <fullName>Bale,compressed</fullName>
            </value>
            <value>
                <fullName>Bale,non-compressed</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Barrel</fullName>
            </value>
            <value>
                <fullName>Basket</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
            </value>
            <value>
                <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
            </value>
            <value>
                <fullName>Bulk, liquid</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, fineparticles(powders）</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, granular particles(grains）</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, large particles(nodules）</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Cage</fullName>
            </value>
            <value>
                <fullName>Can,cylindrical</fullName>
            </value>
            <value>
                <fullName>Can,rectangular</fullName>
            </value>
            <value>
                <fullName>Carboy,non-protected</fullName>
            </value>
            <value>
                <fullName>Carboy,protected</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
                <default>true</default>
                <label>Carton</label>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Cask</fullName>
            </value>
            <value>
                <fullName>Chest</fullName>
            </value>
            <value>
                <fullName>Coil</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Crate</fullName>
            </value>
            <value>
                <fullName>Cylinder</fullName>
            </value>
            <value>
                <fullName>DemiJohn,non-protected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MANIFEST__c/MANIFEST__c.object-meta.xml
<CustomObject>
    <label>マニフェストコード</label>
    <nameField>
        <displayFormat>MF-{000000}</displayFormat>
        <label>MANIFEST ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MANIFEST__c/fields/CODE__c.field-meta.xml
<CustomField>
    <fullName>CODE__c</fullName>
    <label>CODE</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HouseBillLadingReportController.cls
public with sharing class HouseBillLadingReportController {
    private String shipmentId;
    private static List<String> shipmentFields;
    private static List<String> containerFields;
    private static List<String> manifestFields;
    
    public ShipmentWrapper wrapper {get; private set;}
    public Manifest manifest {get; private set;}
    
    public HouseBillLadingReportController() {
        readParameters();
        if (PermissionValidationUtil.isAccessibleHBL()) {
            prepareReportData();
        }
        
        manifest = new Manifest();
        buildManifestList();
    }
    
    public String xlsHeader {
        get {
            String strHeader = '';
            strHeader += '<?xml version="1.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    
    private void readParameters() {
        shipmentId = ApexPages.currentPage().getParameters().get('id');
    }
    
    private void prepareReportData() {
        final String query = buildQuery(shipmentId);
        CustomObject1__c shipmentWithContainers = Database.query(query);
        wrapper = new ShipmentWrapper();
        
        if (shipmentWithContainers != null) {
            wrapper.consignerAddress = shipmentWithContainers.ADDRESS_ON_B_L__c;
            wrapper.consigneeAddress = shipmentWithContainers.CNEE_ADDRESS_ON_B_L__c;
            wrapper.notifyAddress = shipmentWithContainers.NOTIFY_ADDRESS_ON_B_L__c;
            wrapper.portOfTransit = shipmentWithContainers.TS__c;
            wrapper.placeOfDelivery = shipmentWithContainers.Place_Of_Delivery__r.Name;
            wrapper.portOfLoad = shipmentWithContainers.POL__r.Name;
            wrapper.portOfDischarge = shipmentWithContainers.POD__r.Name;
            wrapper.cargoType = shipmentWithContainers.CARGO_TYPE__c;
            wrapper.houseBillNumber = shipmentWithContainers.HBL_Number_SEA_AIR__c;
            wrapper.dateOfBill = shipmentWithContainers.PrintDate__c;
            wrapper.masterBillNumber = shipmentWithContainers.MBL_Number_SEA_AIR__c;
            wrapper.dateOfMasterBillIssued = shipmentWithContainers.DATE_OF_MASTER_BL_ISSUED__c;
            wrapper.departureDate = shipmentWithContainers.ETD__c;
            wrapper.numberOfPackages = shipmentWithContainers.carton__c;
            wrapper.unitType = shipmentWithContainers.UnitType__c;
            wrapper.remarks = shipmentWithContainers.Remarks__c;
            //wrapper.hsCode = shipmentWithContainers.HSCode__r.Name;
            wrapper.hsCode = '';
            wrapper.placeOfReceipt = shipmentWithContainers.Place_Of_Receipt__r.Name;
            
            String transportationType = shipmentWithContainers.TranporationType__c;
            if (PicklistReference.TRANSPORTATION_FCL.equalsIgnoreCase(transportationType)) {
                List<Container_Info__c> containerInfos = shipmentWithContainers.Container_Info__r;
                if (containerInfos != null && !containerInfos.isEmpty()) {
                    for (Container_Info__c ci : containerInfos) {
                        ContainerWrapper container = new ContainerWrapper();
                        container.goods = ci.GOODS__c;
                        container.containerNo = ci.Container_NO__c;
                        container.sealNo = ci.Seal_No__c;
                        container.grossWeigth = ci.GROSS_WEIGHT__c;
                        container.measurement = ci.MEASUREMENT_CBM__c;
                        container.netWeigth = ci.NET_WEIGHT__c;
                        
                        wrapper.addContainer(container);
                    }
                }
                
            } else {
                ContainerWrapper container = new ContainerWrapper();
                String containerAndSealNo = shipmentWithContainers.CONTAINERSEALNO__c;
                
                if (!StringUtils.isEmpty(containerAndSealNo)) {
                    List<String> tokens = containerAndSealNo.split('/');
                    
                    if (tokens.size() == 2) {
                        container.containerNo = tokens.get(0);
                        container.sealNo = tokens.get(1);
                    } else if (tokens.size() == 1) {
                        container.containerNo = tokens.get(0);
                        container.sealNo = '';
                    }
                }
                
                container.goods = shipmentWithContainers.Item__c;
                container.grossWeigth = shipmentWithContainers.weight__c;
                container.measurement = shipmentWithContainers.CBM__c;
                container.netWeigth = shipmentWithContainers.NET_NET_Weight__c;
                
                wrapper.addContainer(container); 
            }
        }
    }
    
    private String buildQuery(String shipmentId) {
        final String query = 'SELECT ' + String.join(shipmentFields, ',') + ', (SELECT ' + String.join(containerFields, ',') 
                            + ' FROM Container_Info__r) FROM CustomObject1__c WHERE Id = \'' + StringUtils.escapeSingleQuotes(shipmentId) + '\'';
        return query;
    }
    
    private void buildManifestList() {
        if (PermissionValidationUtil.isAccessibleManifest()) {
            final String query = 'SELECT ' + String.join(manifestFields, ',') + ' FROM MANIFEST__c ORDER BY Code__c';
            List<Manifest__c> manifestList = Database.query(query);
            
            if (manifestList != null && !manifestList.isEmpty()) {
                for (MANIFEST__c m : manifestList) {
                    manifest.addManifestRecord(m.Category__c, m.Code__c, m.NAME__c);
                }
            }
        }
    }
    
    static {
        shipmentFields = new List<String>();
        //shipmentFields.add('HSCode__r.Name');
        shipmentFields.add('Name');
        shipmentFields.add('ADDRESS_ON_B_L__c');
        shipmentFields.add('CNEE_ADDRESS_ON_B_L__c');
        shipmentFields.add('NOTIFY_ADDRESS_ON_B_L__c');
        shipmentFields.add('TS__c');
        shipmentFields.add('Place_Of_Delivery__r.Name');
        shipmentFields.add('POL__r.Name');
        shipmentFields.add('POD__r.Name');
        shipmentFields.add('CARGO_TYPE__c');
        shipmentFields.add('HBL_Number_SEA_AIR__c');
        shipmentFields.add('PrintDate__c');
        shipmentFields.add('MBL_Number_SEA_AIR__c');
        shipmentFields.add('DATE_OF_MASTER_BL_ISSUED__c');
        shipmentFields.add('ETD__c');
        shipmentFields.add('carton__c');
        shipmentFields.add('UnitType__c');
        shipmentFields.add('Remarks__c');
        shipmentFields.add('Place_Of_Receipt__r.Name');
        shipmentFields.add('TranporationType__c');
        shipmentFields.add('Item__c');
        shipmentFields.add('weight__c');
        shipmentFields.add('CBM__c');
        shipmentFields.add('NET_NET_Weight__c');
        shipmentFields.add('CONTAINERSEALNO__c');
        
        containerFields = new List<String>();
        containerFields.add('GOODS__c');
        containerFields.add('GROSS_WEIGHT__c');
        containerFields.add('MEASUREMENT_CBM__c');
        containerFields.add('Container_NO__c');
        containerFields.add('Seal_No__c');
        containerFields.add('NET_WEIGHT__c');
        
        manifestFields = new List<String>();
        manifestFields.add('Category__c');
        manifestFields.add('Code__c');
        manifestFields.add('NAME__c');
    }

    class ShipmentWrapper{
        public List<ContainerWrapper> containers {get; private set;}
        public String consignerAddress {get; set;}
        public String consigneeAddress {get; set;}
        public String notifyAddress {get; set;}
        public String portOfTransit {get; set;}
        public String placeOfDelivery {get; set;}
        public String placeOfReceipt {get; set;}
        public String portOfLoad {get; set;}
        public String portOfDischarge {get; set;}
        public String cargoType {get; set;}
        public String houseBillNumber {get; set;}
        public Date dateOfBill {get; set;}
        public String masterBillNumber {get; set;}
        public Date dateOfMasterBillIssued {get; set;}
        public Date departureDate {get; set;}
        public Decimal numberOfPackages {get; set;}
        public String unitType {get; set;}
        public String remarks {get; set;}
        public String hsCode {get; set;}
        
        public ShipmentWrapper() {
            containers = new List<ContainerWrapper>();
        }
        
        public void addContainer(ContainerWrapper container) {
            if (container != null) {
                containers.add(container);
            }
        }
    }
    
    class ContainerWrapper{
        public String goods {get; set;}
        public String containerNo {get; set;}
        public String sealNo {get; set;}
        public Decimal grossWeigth {get; set;}
        public Decimal measurement {get; set;}
        public Decimal netWeigth {get; set;}
    }
    
    class Manifest {
        public Integer numberOfPorts {get; private set;}
        public Integer numberOfGrossUnits {get; private set;}
        public Integer numberOfDocFunctions {get; private set;}
        public List<ManifestRecord> manifestRecords {get; set;}
        
        public Manifest() {
            manifestRecords = new List<ManifestRecord>();
            numberOfPorts = 0;
            numberOfGrossUnits = 0;
            numberOfDocFunctions = 0;
        }
        
        public void addManifestRecord(final String category, final String code, final String description) {
            if (!StringUtils.isEmpty(category) && !StringUtils.isEmpty(code)) {
                if (category.contains('Port')) {
                    ManifestRecord mr = getManifestRecord(numberOfPorts);
                    mr.portCode = code;
                    mr.portCodeName = description;
                    numberOfPorts++;
                } else if (category.contains('Document')) {
                    ManifestRecord mr = getManifestRecord(numberOfDocFunctions);
                    mr.docFunction = code;
                    mr.docFunctionName = description;
                    numberOfDocFunctions++;
                } else if (category.contains('GrossUnit')) {
                    ManifestRecord mr = getManifestRecord(numberOfGrossUnits);
                    mr.grossUnit = code;
                    mr.grossUnitName = description;
                    numberOfGrossUnits++;
                }
            }
        }
        
        private ManifestRecord getManifestRecord(Integer index) {
            ManifestRecord mr = null;
            
            if ((index + 1) > manifestRecords.size() || manifestRecords.isEmpty()) {
                mr = new ManifestRecord();
                manifestRecords.add(mr);
            } else {
                mr = manifestRecords.get(index);
            }
            return mr;
        }
    }
    
    class ManifestRecord {
        public String portCode {get; set;}
        public String portCodeName {get; set;}
        public String grossUnit {get; set;}
        public String grossUnitName {get; set;}
        public String docFunction {get; set;}
        public String docFunctionName {get; set;}
    }
}